import {randomUUID} from 'node:crypto';
import {sql} from 'kysely';
import {parseExactSafeInteger} from '../../platform/serialization/exact-json-integer.js';
import {applyCoordinator,canonicalPlan,planBinding,fileIntake,boundedParse,recordOwnerFileValidation,type CatalogTransactionScope,type ApplyOwnerPort,type OwnerFact,type ImportJob,type ImportContractItem,type KeyProviderPort,type ValidationEvaluation} from '../governance-catalog/index.js';
import {localTime,covered,intersect,subtract} from '../organization-master/index.js';
import {UseId} from './usage-type-contracts.js';
import type {LocationUsageTypeOwner} from './usage-types.js';
import {useRuntime,useCheck,type UseEnvelope} from './use-runtime.js';
import {LocationUseStageSchema,LocationUseDirectStageSchema,LocationUseStoredStageSchema,LocationUseVerifySchema,LocationUseInputSchema,LocationUsePlanSchema,LocationUseReadSchema,LocationUseHistorySchema,LocationUseExactSchema,LocationUseDiffSchema,LocationUseListSchema,LocationUseWindowSchema,LocationUseReceiveSchema,ORG13_FIELDS,USE_TARGET_OWNERS,normalizeLocationUseRow,type LocationUseStage,type LocationUseStoredStage,type LocationUseVerification,type LocationUseReceive,type LocationUseHistory,type LocationUseFacts,type LocationUseWrite,type LocationUseIssue,type LocationUseUpstreamPorts,type LocationUseWindow} from './use-contracts.js';
import {knownLocationUse,useDeclaration,useEnd,useReserved,useAt,useConflicts} from './use-timeline.js';

type Scope=CatalogTransactionScope;
interface InputRecord {id:string;revision:string;job_id:string;job_revision:string;identity_code:string;withdrawn?:boolean;digest:string;campus_ids:string[];scope:'NORTH'|'SOUTH';envelope:UseEnvelope;verification:null|{id:string;number:string;actor:string;identity_code:string;digest:string;envelope:UseEnvelope}}
type Staged={inputId:string;revisionId:string;digest:string};
const same=(a:unknown,b:unknown)=>canonicalPlan(a)===canonicalPlan(b);
const verificationCovers=(rows:LocationUseVerification['rows'],count:number)=>rows.length===count&&new Set(rows.map(v=>v.row)).size===count&&rows.every(v=>v.row>=1&&v.row<=count);

/** The Location Owner publishes declarations; upstream references never imply ownership. */
export function openLocationUse(connection:string,provider:KeyProviderPort,ports:LocationUseUpstreamPorts,dictionary:LocationUsageTypeOwner){
 const runtime=useRuntime(connection,provider),{db,root,seal,unseal,material,recoverable}=runtime;
 const clock=async(s:Scope)=>(await sql<{v:string}>`select to_char(timezone('Asia/Shanghai',clock_timestamp()),'YYYY-MM-DD"T"HH24:MI:SS.US') v`.execute(s)).rows[0]!.v;
 const times=new WeakMap<Scope,{recordAt:string;recordAtProof:string}>();
 const publicationTime=async(s:Scope)=>{let point=times.get(s);if(!point){point=(await sql<{r:{recordAt:string;recordAtProof:string}}>`select location_master.use_record_time() r`.execute(s)).rows[0]!.r;times.set(s,point);}return point;};
 const mutate=<T>(s:Scope,actor:string,value:Record<string,unknown>)=>runtime.signed<T>(s,actor,'use_mutate',value);
 const snapshot=async(s:Scope,actor:string,id:string,r?:string)=>(await (r?sql<{r:LocationUseHistory}>`select location_master.use_snapshot_at(${actor},${id}::uuid,${localTime(r)}::timestamp) r`:sql<{r:LocationUseHistory}>`select location_master.use_snapshot(${actor},${id}::uuid) r`).execute(s)).rows[0]!.r;
 const exactSnapshot=async(s:Scope,actor:string,id:string,version:string)=>(await sql<{r:LocationUseHistory}>`select location_master.use_snapshot_version(${actor},${id}::uuid,${version}) r`.execute(s)).rows[0]!.r;
 const histories=async(s:Scope,actor:string,campus:string,r?:string)=>(await (r?sql<{r:LocationUseHistory[]}>`select location_master.use_list_at(${actor},${campus},${localTime(r)}::timestamp) r`:sql<{r:LocationUseHistory[]}>`select location_master.use_list(${actor},${campus}) r`).execute(s)).rows[0]!.r;
 const scopedHistories=async(s:Scope,actor:string,a:LocationUseHistory['applicability'],r:string)=>(await sql<{r:LocationUseHistory[]}>`select location_master.use_scope_histories(${actor},${JSON.stringify(a)}::jsonb,${r}::timestamp) r`.execute(s)).rows[0]!.r;
 const record=async(s:Scope,actor:string,id:string,p='READ_RESTRICTED')=>(await sql<{r:InputRecord}>`select location_master.use_input_read(${actor},${id}::uuid,${p}) r`.execute(s)).rows[0]!.r;
 const inputJob=async(s:Scope,actor:string,id:string)=>(await sql<{r:ImportJob}>`select location_master.use_job_read(${actor},${id}::uuid) r`.execute(s)).rows[0]!.r;
 const job=async(s:Scope,actor:string,id:string)=>(await sql<{r:ImportJob}>`select governance_catalog.import_job_read(${actor},${JSON.stringify({scope:'SYNTHETIC',jobId:id})}::jsonb) r`.execute(s)).rows[0]!.r;
 const authorize=async(s:Scope,actor:string,id:string,p:string)=>(await sql<{r:string}>`select location_master.use_authorize(${actor},${id}::uuid,${p}) r`.execute(s)).rows[0]!.r;
 const evidence=(s:Scope,actor:string,id:string,c:ImportContractItem,campus:string)=>{if(!c.definition.sourceVersionId)throw new Error('BLOCKED_DEPENDENCY');return material(s,actor,id,c.definition.sourceVersionId,campus);};
 const sourceCoverage=async(s:Scope,actor:string,id:string,from:string,to:string|null,r:string)=>(await sql<{r:unknown}>`select governance_catalog.use_source_coverage(${actor},${id}::uuid,${from}::timestamp,${to}::timestamp,${r}::timestamp) r`.execute(s)).rows[0]!.r;
 const sourceWindows=async(s:Scope,actor:string,id:string,from:string,to:string|null,r:string)=>(await sql<{r:Array<{from:string;to:string|null}>}>`select governance_catalog.use_source_windows(${actor},${id}::uuid,${from}::timestamp,${to}::timestamp,${r}::timestamp) r`.execute(s)).rows[0]!.r;
 const referenceAccess=async(s:Scope,actor:string,input:LocationUseStoredStage,c:ImportContractItem,extra:readonly string[]=[])=>{
  for(const e of input.entries){await ports.referenceAccess(s,actor,e.applicability);await dictionary.referenceInTransaction(s,actor,e.usageType);if('target' in e)await exactSnapshot(s,actor,e.target.id,e.target.expectedHead);}
  for(const id of new Set(input.entries.map(e=>e.row.source_system_id)))await sql`select governance_catalog.use_source_reference(${actor},${id}::uuid,${c.definition.sourceVersionId}::uuid)`.execute(s);
  for(const id of new Set([...input.entries.map(e=>e.evidenceId),...(input.sourceArtifactId?[input.sourceArtifactId]:[]),...extra]))await sql`select governance_catalog.registration_evidence_access(${actor},${id}::uuid,${c.definition.sourceVersionId}::uuid,${input.campus})`.execute(s);
 };
 const stageIn=async(s:Scope,actor:string,input:LocationUseStoredStage)=>{
  const j=await job(s,actor,input.jobId);if(j.currentRevisionId!==input.revisionId)throw new Error('STALE_REVISION');
  if(input.timePolicy==='SOURCE_PLUS08_TO_LOCAL'&&!j.contract.definition.rules.some(rule=>rule.id==='LOCATION_USE_SOURCE_PLUS08_V1'&&rule.status==='MACHINE'))throw new Error('BLOCKED_DEPENDENCY');
  for(const e of input.entries){normalizeLocationUseRow(e.row,input.timePolicy);if(e.action==='END')localTime(e.endAt);}
  return mutate<Staged>(s,actor,{operation:'STAGE',requestId:input.requestId,jobId:input.jobId,revisionId:input.revisionId,campus:input.campus,campusIds:[...new Set(input.entries.map(e=>e.applicability.campus.id))].sort(),...seal('LOCATION_USE_INPUT_V1',input)});
 };
 const currentBasis=async(s:Scope,actor:string,a:LocationUseHistory['applicability'],facts:LocationUseFacts,from:string,to:string|null,r:string)=>({
  ...await ports.admit(s,actor,a,from,to,r),source:await sourceCoverage(s,actor,facts.source.sourceSystemId,from,to,r),usageType:await dictionary.evaluateReferenceWindowInTransaction(s,actor,facts.usageType,{validFrom:from,validTo:to,recordAsOf:r}),
 });
 const inspectInput=async(s:Scope,actor:string,id:string)=>{
  const r=await record(s,actor,id),input=unseal<LocationUseStoredStage>('LOCATION_USE_INPUT_V1',r,LocationUseStoredStageSchema),j=await inputJob(s,actor,id),c=j.contract,now=(await publicationTime(s)).recordAt,issues:LocationUseIssue[]=[],writes:LocationUseWrite[]=[],materials:Array<{id:string;digest:string}>=[],dependencies:unknown[]=[],original:LocationUseHistory[]=[];
  const issue=(row:number,field:string,code:string,status:LocationUseIssue['status']='FAIL')=>issues.push({row,field,code,status});
  if(r.withdrawn)throw new Error('INPUT_WITHDRAWN');if(j.currentRevisionId!==r.job_revision||j.status==='REJECTED')throw new Error('STALE_REVISION');await referenceAccess(s,actor,input,c);
  if(c.dataset!=='ORG13'||c.definition.templateVersion!=='ORG13_CORE_V1')throw new Error('BLOCKED_DEPENDENCY');
  if(input.profile!=='CORE'||j.profile!=='CORE')issue(0,'profile','BLOCKED_DEPENDENCY','BLOCKED');
  if(c.definition.fields.length!==15||!ORG13_FIELDS.every(field=>c.definition.fields.some(f=>f.code===field)))throw new Error('FULL_FIELD_OMISSION');
  if(input.timePolicy==='SOURCE_PLUS08_TO_LOCAL'&&!c.definition.rules.some(rule=>rule.id==='LOCATION_USE_SOURCE_PLUS08_V1'&&rule.status==='MACHINE'))issue(0,'timePolicy','BLOCKED_DEPENDENCY','BLOCKED');
  const verification=r.verification?unseal<LocationUseVerification>('LOCATION_USE_VERIFICATION_V1',r.verification,LocationUseVerifySchema):null;
  if(!verification)issue(0,'verification','LEGAL_REVIEW_REQUIRED','BLOCKED');else{
   if(verification.inputDigest!==r.digest)throw new Error('STALE_VALIDATION');for(const id of r.campus_ids)if(await authorize(s,r.verification!.actor,id,'VERIFY')!==r.verification!.identity_code)throw new Error('ACCESS_DENIED');
   await referenceAccess(s,r.verification!.actor,input,c);if(!verificationCovers(verification.rows,input.entries.length))issue(0,'verification','VERIFICATION_ROW_MISMATCH');
  }
  const touched=new Set<string>(),aliases=new Set<string>();let expanding=false;
  for(const [index,entry] of input.entries.entries())try{await recoverable(s,async()=>{
   const n=index+1,e=normalizeLocationUseRow(entry.row,input.timePolicy),a=entry.applicability,target='target' in entry?entry.target:null,h=target?await snapshot(s,actor,target.id):null,head=h?.versions.at(-1),d=h?useDeclaration(h):null;
   if(e.row.target_type!==a.targetType||a.target.owner!==USE_TARGET_OWNERS[a.targetType]||e.row.target_id!==a.target.id||e.row.location_id!==a.location.id||a.usageType.id!==entry.usageType.id||(await ports.referenceAccess(s,actor,a)).scope!==r.scope)throw new Error('LOCATION_USE_ANCHOR_MISMATCH');
   const type=await dictionary.referenceInTransaction(s,actor,entry.usageType);if(type.code!==e.row.usage_type)throw new Error('USAGE_TYPE_CODE_MISMATCH');
   if(target){if(touched.has(target.id))throw new Error('BATCH_CONFLICT');touched.add(target.id);if(head?.number!==target.expectedHead)throw new Error('STALE_HEAD');const end=useEnd(h!);if(end!==null&&(entry.action!=='END'||localTime(entry.endAt)>end))throw new Error('LOCATION_USE_ENDED');if(!same(h!.applicability,a))throw new Error('LOCATION_USE_ANCHOR_MISMATCH');if(e.row.object_location_rel_id!==h!.versions[0]!.facts.source.sourceAlias||e.row.source_system_id!==h!.versions[0]!.facts.source.sourceSystemId)throw new Error('LOCATION_USE_SOURCE_IDENTITY_MISMATCH');original.push(h!);}
   else{const alias=e.row.source_system_id+'|'+e.row.object_location_rel_id;if(aliases.has(alias))throw new Error('BATCH_CONFLICT');aliases.add(alias);if((await sql<{r:boolean}>`select location_master.use_source_conflict(${actor},${e.row.source_system_id}::uuid,${e.row.object_location_rel_id}) r`.execute(s)).rows[0]!.r)throw new Error('LOCATION_USE_SOURCE_ALREADY_REGISTERED');}
   const checked=verification?.rows.find(v=>v.row===n);if(verification&&(!checked||!checked.classificationAccepted||!checked.scopeAccepted||!checked.policyAccepted||!same(checked.policy,entry.policy)))throw new Error('LOCATION_USE_REVIEW_REQUIRED');
   if(checked&&!covered([{from:localTime(checked.validFrom),to:checked.validTo===null?null:localTime(checked.validTo)}],e.from,e.to))throw new Error('LOCATION_USE_REVIEW_PERIOD_NOT_COVERED');
   materials.push(await evidence(s,actor,entry.evidenceId,c,r.scope));if(checked){materials.push(await evidence(s,actor,checked.evidenceId,c,r.scope));await evidence(s,r.verification!.actor,checked.evidenceId,c,r.scope);}
   const facts:LocationUseFacts={isPrimary:e.row.is_primary==='Y',sharingDescription:e.row.sharing_description,policy:entry.policy,usageType:entry.usageType,usageCode:e.row.usage_type,contractVersionId:c.versionId,verificationBasis:{id:r.verification?.id??'',version:String(r.verification?.number??0),digest:r.digest},dependencies:d?.facts.dependencies??null,source:{sourceAlias:e.row.object_location_rel_id,sourceVersion:String(e.row.version_no),sourceSystemId:e.row.source_system_id,sourceRecordedAt:e.sourceRecordedAt,recordLocatorEvidence:{inputId:r.id,row:input.sourceRows?.[index]??n},recordStatus:e.row.record_status,approvalReference:e.row.approval_ref}};
   const unchanged=!!d&&facts.isPrimary===d.facts.isPrimary&&facts.sharingDescription===d.facts.sharingDescription&&same(facts.policy,d.facts.policy)&&same(facts.usageType,d.facts.usageType)&&facts.usageCode===d.facts.usageCode;
   let from=e.from,to=e.to,reduction=false;
   if(entry.action==='END'){
    const boundary=localTime(entry.endAt);if(!d||e.from!==d.validFrom||e.to!==d.validTo||(boundary<localTime(d.validFrom)&&localTime(d.validFrom)<=localTime(now))||(d.validTo!==null&&boundary>d.validTo)||e.row.record_status!=='RETIRED')throw new Error('LOCATION_USE_LIFECYCLE_INVALID');if(!unchanged)throw new Error('LOCATION_USE_CONTENT_CHANGED');from=boundary;to=null;reduction=true;
   }else{
    if(e.row.record_status!=='ACTIVE'||entry.action==='REVISE'&&e.from!==d?.validFrom)throw new Error('LOCATION_USE_REVISE_INVALID');
    reduction=entry.action==='REVISE'&&unchanged&&to!==null&&(d!.validTo===null||to<d!.validTo);
    if(!reduction){expanding=true;await dictionary.requireEnabledInTransaction(s,actor,entry.usageType,now);if(!covered([{from:c.validFrom,to:c.validTo}],from,to))throw new Error('BLOCKED_DEPENDENCY');for(const field of ['target_type','is_primary','record_status'] as const){const codes=c.definition.codeSets.find(x=>x.field===field);if(!codes||codes.status!=='SYNTHETIC_ADOPTED'||!codes.codes.includes(e.row[field])||!covered([{from:codes.validFrom,to:codes.validTo}],from,to))throw new Error('BLOCKED_DEPENDENCY');}facts.dependencies=await currentBasis(s,actor,a,facts,from,to,now);dependencies.push(facts.dependencies);}
   }
   writes.push({key:target?.id??'alias:'+e.row.source_system_id+':'+e.row.object_location_rel_id,targetId:target?.id??null,expectedHead:target?.expectedHead??null,action:entry.action,validFrom:from,validTo:to,applicability:a,facts,reason:entry.reason,sourceRow:input.sourceRows?.[index]??n,verificationRow:n,scope:r.scope,reduction});
  });}catch(error){if(error instanceof Error&&['ACCESS_DENIED','KEY_UNAVAILABLE','PAYLOAD_UNAVAILABLE'].includes(error.message))throw error;issue(index+1,'',error instanceof Error?error.message:'CLOSED_INPUT_REQUIRED',error instanceof Error&&['LEGAL_REVIEW_REQUIRED','LOCATION_USE_REVIEW_REQUIRED','BLOCKED_DEPENDENCY','CROSS_CAMPUS_POLICY_REQUIRED'].includes(error.message)?'BLOCKED':'FAIL');}
  const existing=(await Promise.all(input.entries.map(e=>scopedHistories(s,actor,e.applicability,now)))).flat(),projected=new Map(existing.map(h=>[h.id,h]));dependencies.push({reservations:[...projected.values()]});
  for(const w of writes){const h=w.targetId?projected.get(w.targetId):undefined;projected.set(w.key,{id:w.key,scope:w.scope,applicability:w.applicability,versions:[...(h?.versions??[]),{id:'proposed',number:String(BigInt(h?.versions.at(-1)?.number??'0')+1n),action:w.action,validFrom:w.validFrom,validTo:w.validTo,recordedAt:now,facts:w.facts,reason:w.reason,changeId:'proposed'}]});}
  for(const code of useConflicts([...projected.values()]))issue(0,'policy',code);
  if(expanding){const active=(await sql<{r:ImportContractItem[]}>`select governance_catalog.contract_read(${actor},${JSON.stringify({scope:'SYNTHETIC',mode:'EFFECTIVE',target:c.id,businessAt:now})}::jsonb) r`.execute(s)).rows[0]!.r;if(active[0]?.versionId!==c.versionId)issue(0,'contract','STALE_VALIDATION','BLOCKED');}
  writes.sort((a,b)=>Number(a.action!=='END')-Number(b.action!=='END'));return {r,input,contract:c,verification,issues,writes,materials,dependencies,original};
 };
 const port:ApplyOwnerPort={
  async authorize(s,actor,input,p){const r=await record(s,actor,input.jobId,p);if(r.revision!==input.revisionId||r.scope!==input.campus||input.purpose!=='IDENTITY_VERIFY')throw new Error('ACCESS_DENIED');},
  async authorizeApproval(s,actor,input){const r=await record(s,actor,input.jobId,'REVIEW');for(const id of r.campus_ids)if(await authorize(s,actor,id,'REVIEW')===r.identity_code)throw new Error('MAKER_CHECKER_REQUIRED');},
  async authorizeFrozen(s,actor,unit){useCheck(LocationUseStoredStageSchema,unit.basis['input']);const materials=unit.basis['materials'];if(!Array.isArray(materials)||!Array.isArray(unit.basis['dependencies']))throw new Error('INVALID_PLAN_TOKEN');const ids=materials.map(m=>{useCheck(UseId,m?.id);return m.id as string;});const j=await inputJob(s,actor,unit.input.jobId);await referenceAccess(s,actor,unit.basis['input'] as LocationUseStoredStage,j.contract,ids);},
  async observe(s,actor,input){const v=await inspectInput(s,actor,input.jobId);return {input,atomicRule:'ORG13_WHOLE_REVISION_V1',basis:{input:v.input,inputDigest:v.r.digest,contract:v.contract,verificationId:v.r.verification?.id??null,verificationDigest:v.r.verification?.digest??null,issues:v.issues,heads:v.original,materials:v.materials,dependencies:v.dependencies},commands:v.writes.map((w,index)=>({owner:'location-master/location-use',row:index+1,intent:w.action==='CREATE'?'CREATE' as const:'REVISE' as const,target:w.targetId?{owner:'location-master/location-use',id:w.targetId,version:w.expectedHead!}:null,aliases:[],value:{inputId:v.r.id,...(index===0?{writes:canonicalPlan(v.writes)}:{}),writeIndex:String(index+1),writesDigest:planBinding(provider,'LOCATION_USE_WRITES_V1',v.writes)}})),diff:v.writes.map(w=>({action:w.action,targetId:w.targetId,from:w.validFrom,to:w.validTo}))};},
  async validate(_s,_actor,unit,_stage){const issues=unit.basis['issues'] as LocationUseIssue[];if(issues.length||!unit.commands.length)throw new Error(issues[0]?.code??'BATCH_REJECTED');},
  async afterFreeze(s,actor,unit,c){const v=unit.commands[0]!.value;await mutate(s,actor,{operation:'FREEZE',inputId:v['inputId'],writes:JSON.parse(v['writes']!),writesDigest:v['writesDigest'],...c});},
  async apply(s,actor,command,_resolved,approval){return {ok:true,fact:await mutate<OwnerFact>(s,actor,{operation:'APPLY',inputId:command.value['inputId'],writes:JSON.parse(command.value['writes']??'[]'),writeIndex:Number(command.value['writeIndex']),writesDigest:command.value['writesDigest'],...approval,...await publicationTime(s)})};},
  async exactRead(s,actor,_input,fact){if(fact.owner!=='location-master/location-use')return null;return (await exactSnapshot(s,actor,fact.id,fact.version)).versions.some(v=>v.number===fact.version)?fact:null;},
 };
 const applyAt=async(s:Scope,actor:string,command:Parameters<ApplyOwnerPort['apply']>[2],approval:Parameters<ApplyOwnerPort['apply']>[4],recordAt?:string):ReturnType<ApplyOwnerPort['apply']>=>{
  const point=await publicationTime(s),writes:LocationUseWrite[]=JSON.parse(command.value['writes']??'[]'),resolutions:Array<{key:string;basis:unknown}>=[],locationResolutions:Array<{key:string;basis:unknown}>=[];
  for(const w of writes){const location=w.facts.dependencies&&typeof w.facts.dependencies==='object'&&'location' in w.facts.dependencies?w.facts.dependencies.location:null;if(location&&typeof location==='object'&&'kind' in location&&location.kind==='LIFECYCLE_LOCATION_INPUT')locationResolutions.push({key:w.key,basis:await ports.admitLocation(s,actor,w.applicability,w.validFrom,w.validTo,recordAt??point.recordAt)});const deps=w.facts.dependencies,upstream=deps&&typeof deps==='object'&&'upstream' in deps?deps.upstream:null;if(upstream&&typeof upstream==='object'&&'kind' in upstream&&upstream.kind==='LIFECYCLE_CARE_INPUT')resolutions.push({key:w.key,basis:await ports.admitTarget(s,actor,w.applicability,w.validFrom,w.validTo,recordAt??point.recordAt)});}
  return {ok:true,fact:await mutate<OwnerFact>(s,actor,{operation:'APPLY',inputId:command.value['inputId'],writes,writeIndex:Number(command.value['writeIndex']),writesDigest:command.value['writesDigest'],...approval,...point,resolutions,locationResolutions})};
 };
 port.apply=(s,actor,command,_resolved,approval)=>applyAt(s,actor,command,approval);
 const coordinator=applyCoordinator(db,provider,port),files=fileIntake(db,provider);
 const historyIn=async(s:Scope,actor:string,id:string,r?:string)=>{const h=knownLocationUse(await snapshot(s,actor,id,r),r);if(!h.versions.length)throw new Error('NOT_FOUND');return h;};
 const readIn=async(s:Scope,actor:string,input:{id:string;businessAt?:string;recordAsOf?:string})=>{const h=await historyIn(s,actor,input.id,input.recordAsOf),at=input.businessAt?localTime(input.businessAt):await clock(s),end=useEnd(h);return {id:h.id,applicability:h.applicability,head:h.versions.at(-1)!.number,state:useAt(h,at)?'ACTIVE' as const:end!==null&&end<=at?'ENDED' as const:'NOT_EFFECTIVE' as const,version:useDeclaration(h),clinicalReadiness:'NOT_READY' as const};};
 type DependencyCheck={owner:'LOCATION'|'ORGANIZATION'|'USAGE_TYPE'|'SOURCE';status:'SATISFIED'|'NOT_SATISFIED';reason:string;basisChanged:boolean;basis:unknown};
 const dependencyChecks=async(s:Scope,actor:string,h:LocationUseHistory,facts:LocationUseFacts,from:string,to:string|null,r:string)=>{
  const result:DependencyCheck[]=[],basis:Record<string,unknown>={},accepted=facts.dependencies!==null&&typeof facts.dependencies==='object'?facts.dependencies as Record<string,unknown>:{};
  const reads:Array<{owner:DependencyCheck['owner'];key:string;read:()=>Promise<unknown>}>=
   [{owner:'LOCATION',key:'location',read:()=>ports.admitLocation(s,actor,h.applicability,from,to,r)},
    {owner:'ORGANIZATION',key:'upstream',read:()=>ports.admitTarget(s,actor,h.applicability,from,to,r)},
    {owner:'USAGE_TYPE',key:'usageType',read:()=>dictionary.evaluateReferenceWindowInTransaction(s,actor,facts.usageType,{validFrom:from,validTo:to,recordAsOf:r})},
    {owner:'SOURCE',key:'source',read:()=>sourceCoverage(s,actor,facts.source.sourceSystemId,from,to,r)}];
  for(const read of reads)try{const value=await recoverable(s,read.read);basis[read.key]=value;result.push({owner:read.owner,status:'SATISFIED',reason:'SATISFIED',basisChanged:!same(accepted[read.key]??null,value),basis:value});}catch(error){if(error instanceof Error&&['ACCESS_DENIED','KEY_UNAVAILABLE','PAYLOAD_UNAVAILABLE'].includes(error.message))throw error;result.push({owner:read.owner,status:'NOT_SATISFIED',reason:error instanceof Error?error.message:'BLOCKED_DEPENDENCY',basisChanged:true,basis:null});}
  const failed=result.find(c=>c.status==='NOT_SATISFIED');return {status:failed?'NOT_SATISFIED' as const:'SATISFIED' as const,reason:failed?.reason??'SATISFIED',basis,dependencyChecks:result};
 };
 const evaluateIn=async(s:Scope,actor:string,input:LocationUseWindow)=>{
  const from=localTime(input.validFrom),to=input.validTo===null?null:localTime(input.validTo);if(to!==null&&to<=from)throw new Error('INVALID_BUSINESS_PERIOD');if(input.mode==='CURRENT_ADMISSION'&&input.recordAsOf)throw new Error('CURRENT_RECORD_TIME_REQUIRED');
  const r=input.mode==='HISTORICAL'&&input.recordAsOf?localTime(input.recordAsOf):(await publicationTime(s)).recordAt,h=await historyIn(s,actor,input.id,r),d=useDeclaration(h),declared=useReserved(h).flatMap(p=>intersect(p,{from,to})),checks:Array<{from:string;to:string|null;status:'SATISFIED'|'NOT_SATISFIED';reason:string;acceptedBasis:unknown;basis:unknown;dependencyChecks:DependencyCheck[]}>=[],successful:Array<{from:string;to:string|null}>=[],aggregateGaps:Array<{from:string;to:string|null}>=[];
  if(d)for(const span of declared){
   const boundaryRead=async<T>(work:()=>Promise<T>,fallback:T)=>{try{return await recoverable(s,work);}catch(error){if(error instanceof Error&&['ACCESS_DENIED','KEY_UNAVAILABLE','PAYLOAD_UNAVAILABLE'].includes(error.message))throw error;return fallback;}};
   const points=await boundaryRead(()=>ports.boundaries(s,actor,h.applicability,span.from,span.to,r),[]),dict=await boundaryRead(()=>dictionary.readReferenceBoundariesInTransaction(s,actor,d.facts.usageType,{validFrom:span.from,validTo:span.to,recordAsOf:r}),[]),sources=await boundaryRead(()=>sourceWindows(s,actor,d.facts.source.sourceSystemId,span.from,span.to,r),[]);
   const starts=[span.from,...new Set([...points,...dict,...sources.flatMap(p=>[p.from,p.to])].filter((p):p is string=>p!==null).map(localTime).filter(p=>p>span.from&&(span.to===null||p<span.to)))].sort(),admitted:Array<{from:string;to:string|null}>=[];
   for(const [i,start] of starts.entries()){const piece={from:start,to:starts[i+1]??span.to},evaluation=await dependencyChecks(s,actor,h,d.facts,piece.from,piece.to,r);if(evaluation.status==='SATISFIED'){admitted.push(piece);successful.push(piece);}checks.push({...piece,...evaluation,acceptedBasis:d.facts.dependencies});}
   // Fragment success does not replace a whole-window contract such as one source version.
   if(starts.length>1&&covered(admitted,span.from,span.to)){const evaluation=await dependencyChecks(s,actor,h,d.facts,span.from,span.to,r);if(evaluation.status==='NOT_SATISFIED'){aggregateGaps.push(span);checks.push({...span,...evaluation,acceptedBasis:d.facts.dependencies});}}
  }
  const declarationGaps=subtract({from,to},declared),primaryGaps=subtract({from,to},d?.facts.isPrimary?declared:[]),currentGaps=[...subtract({from,to},successful),...aggregateGaps];for(const gap of declarationGaps)checks.push({...gap,status:'NOT_SATISFIED',reason:'LOCATION_USE_WINDOW_GAP',acceptedBasis:null,basis:null,dependencyChecks:[]});
  return {id:h.id,mode:input.mode,recordAsOf:r,declarationCovered:covered(declared,from,to),primaryCovered:covered(d?.facts.isPrimary?declared:[],from,to),currentAdmissionCovered:aggregateGaps.length===0&&covered(successful,from,to),declarationGaps,primaryGaps,currentGaps,checks,clinicalReadiness:'NOT_READY' as const,moving:'NOT_EVALUABLE' as const};
 };
 return {
  lifecyclePort:port,
  lifecycleApplyAtInTransaction:(s:Scope,actor:string,command:Parameters<ApplyOwnerPort['apply']>[2],_resolved:Parameters<ApplyOwnerPort['apply']>[3],approval:Parameters<ApplyOwnerPort['apply']>[4],recordAt:string)=>applyAt(s,actor,command,approval,recordAt),
  async lifecycleReferenceInTransaction(s:Scope,actor:string,inputId:string){const r=await record(s,actor,inputId);const j=await inputJob(s,actor,inputId);return {inputId:r.id,revisionId:r.revision,digest:r.digest,contractVersionId:j.contract.versionId,makerIdentity:r.identity_code,campus:r.scope};},
  async stage(actor:string,input:LocationUseStage){useCheck(LocationUseDirectStageSchema,input);input=structuredClone(input);for(const e of input.entries)if(typeof e.row.version_no!=='number')throw new Error('CLOSED_INPUT_REQUIRED');return root(async s=>{const j=await job(s,actor,input.jobId);if(j.revisions.at(-1)?.input.kind!=='METADATA_ONLY')throw new Error('FILE_REVISION_REQUIRED');return stageIn(s,actor,input);});},
  async readInput(actor:string,input:{inputId:string}){useCheck(LocationUseInputSchema,input);return root(async s=>{const r=await record(s,actor,input.inputId),value=unseal<LocationUseStoredStage>('LOCATION_USE_INPUT_V1',r,LocationUseStoredStageSchema),j=await inputJob(s,actor,r.id);await referenceAccess(s,actor,value,j.contract);return value;});},
  async verify(actor:string,input:LocationUseVerification){useCheck(LocationUseVerifySchema,input);input=structuredClone(input);for(const row of input.rows){const f=localTime(row.validFrom),t=row.validTo===null?null:localTime(row.validTo);if(t!==null&&t<=f)throw new Error('INVALID_BUSINESS_PERIOD');}return root(async s=>{const r=await record(s,actor,input.inputId,'VERIFY'),j=await inputJob(s,actor,r.id),value=unseal<LocationUseStoredStage>('LOCATION_USE_INPUT_V1',r,LocationUseStoredStageSchema);if(!verificationCovers(input.rows,value.entries.length))throw new Error('VERIFICATION_ROW_MISMATCH');await referenceAccess(s,actor,value,j.contract);for(const row of input.rows)await evidence(s,actor,row.evidenceId,j.contract,r.scope);return mutate<{verificationId:string}>(s,actor,{operation:'VERIFY',inputId:input.inputId,inputDigest:input.inputDigest,requestId:input.requestId,rows:input.rows,policyVersion:input.policyVersion,...seal('LOCATION_USE_VERIFICATION_V1',input)});});},
  async preview(actor:string,input:{inputId:string}){useCheck(LocationUseInputSchema,input);return root(async s=>{const v=await inspectInput(s,actor,input.inputId);return {decision:v.issues.length?'BLOCKED' as const:'PASS' as const,issues:v.issues,changes:v.writes.map(w=>({action:w.action,targetId:w.targetId,validFrom:w.validFrom,validTo:w.validTo}))};});},
  async plan(actor:string,input:{inputId:string;requestId:string}){useCheck(LocationUsePlanSchema,input);const r=await root(s=>record(s,actor,input.inputId,'WRITE'));return coordinator.planOwnerUnit(actor,{requestId:input.requestId,jobId:r.id,revisionId:r.revision,scope:'SYNTHETIC',campus:r.scope,purpose:'IDENTITY_VERIFY'});},
  readApplyCandidate:coordinator.readApplyCandidate,approveApplyUnit:coordinator.approveApplyUnit,applyUnit:coordinator.applyUnit,resumeOutcome:coordinator.resumeOutcome,reconcileCommittedUnit:coordinator.reconcileCommittedUnit,
  async withdraw(actor:string,input:{inputId:string;requestId:string}){useCheck(LocationUsePlanSchema,input);return root(s=>mutate<{inputId:string;status:'WITHDRAWN'}>(s,actor,{operation:'WITHDRAW',...input}));},
  async history(actor:string,input:{id:string;recordAsOf?:string}){useCheck(LocationUseHistorySchema,input);return root(s=>historyIn(s,actor,input.id,input.recordAsOf));},
  async read(actor:string,input:{id:string;businessAt?:string;recordAsOf?:string}){useCheck(LocationUseReadSchema,input);return root(s=>readIn(s,actor,input));},
  async exact(actor:string,input:{id:string;version:string;recordAsOf?:string}){useCheck(LocationUseExactSchema,input);return root(async s=>{const h=await exactSnapshot(s,actor,input.id,input.version),v=h.versions.find(v=>v.number===input.version);if(!v||input.recordAsOf&&v.recordedAt>localTime(input.recordAsOf))throw new Error('NOT_FOUND');return v;});},
  async diff(actor:string,input:{id:string;fromVersion:string;toVersion:string}){useCheck(LocationUseDiffSchema,input);return root(async s=>{const h=await historyIn(s,actor,input.id),before=h.versions.find(v=>v.number===input.fromVersion),after=h.versions.find(v=>v.number===input.toVersion);if(!before||!after)throw new Error('NOT_FOUND');return {id:h.id,before,after};});},
  async list(actor:string,input:{campus:'NORTH'|'SOUTH';campusId?:string;targetId?:string;locationId?:string;usageTypeId?:string;after?:string;limit?:number;businessAt?:string;recordAsOf?:string}){useCheck(LocationUseListSchema,input);return root(async s=>{const all=(await histories(s,actor,input.campus,input.recordAsOf)).filter(h=>h.versions.length&&(!input.targetId||h.applicability.target.id===input.targetId)&&(!input.locationId||h.applicability.location.id===input.locationId)&&(!input.usageTypeId||h.applicability.usageType.id===input.usageTypeId)&&(!input.campusId||h.applicability.campus.id===input.campusId)&&(!input.after||h.id>input.after)),page=all.slice(0,input.limit??50);return {items:await Promise.all(page.map(h=>readIn(s,actor,{id:h.id,...(input.businessAt?{businessAt:input.businessAt}:{}),...(input.recordAsOf?{recordAsOf:input.recordAsOf}:{})}))),nextAfterId:all.length>page.length?page.at(-1)!.id:null};});},
  async evaluateWindow(actor:string,input:LocationUseWindow){useCheck(LocationUseWindowSchema,input);return root(s=>evaluateIn(s,actor,input));},
  async evaluateWindowInTransaction(s:Scope,actor:string,input:LocationUseWindow){useCheck(LocationUseWindowSchema,input);return evaluateIn(s,actor,input);},
  async receiveFile(actor:string,input:LocationUseReceive,bytes:Uint8Array){
   useCheck(LocationUseReceiveSchema,input);input=structuredClone(input);if(input.job.input.kind!=='FILE'||input.job.input.parserPolicy!=='STRICT_LOCATION_USE_V1'||!(bytes instanceof Uint8Array)||bytes.length<1||bytes.length>1048576)throw new Error('CLOSED_FILE_REQUIRED');const privateBytes=Buffer.from(bytes);
   try{const received=await files.receiveFile(actor,{job:input.job,fileRequestId:input.fileRequestId,extension:input.job.input.format==='CSV'?'.csv':input.job.input.format==='JSON'?'.json':'.xlsx',campus:input.campus,purpose:'IDENTITY_VERIFY',retentionSeconds:input.retentionSeconds},privateBytes);return await root(async s=>{
    const j=await job(s,actor,received.job.id),parsed=await boundedParse(privateBytes,input.job.input.kind==='FILE'?input.job.input.format:'JSON',j.contract.definition.fields,'STRICT_LOCATION_USE_V1',input.timePolicy==='SOURCE_PLUS08_TO_LOCAL'),issues:LocationUseIssue[]=parsed.issues.map(i=>({row:i.row,field:i.row>0&&i.column>0?(parsed.cells.find(c=>c.sourceRow===i.row&&c.column===i.column)?.field??''):'',code:i.code,status:'FAIL'})),conversions:Array<{row:number;field:string;sourceValue:unknown;value:unknown;ruleVersion:string}>=[];
    const rows=(parsed.nativeRows??parsed.rows).map((row,index)=>{let next={...row};if(input.job.input.kind==='FILE'&&input.job.input.format==='JSON'&&typeof next['version_no']!=='number')issues.push({row:index+1,field:'version_no',code:'NATIVE_INTEGER_REQUIRED',status:'FAIL'});if(input.job.input.kind==='FILE'&&input.job.input.format!=='JSON'){
     if(next['valid_to']===''){if(!j.contract.definition.rules.some(r=>r.id==='LOCATION_USE_EMPTY_END_V1'&&r.status==='MACHINE'&&r.version==='P3_07_EMPTY_END_V1'))issues.push({row:index+1,field:'valid_to',code:'LOCATION_USE_EMPTY_END_RULE_REQUIRED',status:'BLOCKED'});else{conversions.push({row:index+1,field:'valid_to',sourceValue:'',value:null,ruleVersion:'P3_07_EMPTY_END_V1'});next={...next,valid_to:null};}}
     const sourceVersion=next['version_no'],numericCell=input.job.input.format==='XLSX'&&parsed.cells.some(cell=>cell.row===index+1&&cell.field==='version_no'&&cell.sourceType==='n');
     const version=typeof sourceVersion==='string'?(numericCell?parseExactSafeInteger(sourceVersion):/^[1-9][0-9]{0,9}$/.test(sourceVersion)?Number(sourceVersion):null):null;
     if(version!==null&&version>=1&&version<=2147483647){if(!j.contract.definition.rules.some(rule=>rule.id==='LOCATION_USE_NATIVE_VERSION_V1'&&rule.field==='version_no'&&rule.status==='MACHINE'&&rule.version==='P3_07_NATIVE_VERSION_V1'))issues.push({row:index+1,field:'version_no',code:'LOCATION_USE_NATIVE_VERSION_RULE_REQUIRED',status:'BLOCKED'});else{conversions.push({row:index+1,field:'version_no',sourceValue:sourceVersion,value:version,ruleVersion:'P3_07_NATIVE_VERSION_V1'});next={...next,version_no:version};}}
    }return next;});let staged:Staged|null=null;
    if(parsed.structuralStatus==='PARSED'&&rows.length===input.operations.length&&!issues.length)try{const value={requestId:input.requestId,jobId:j.id,revisionId:j.currentRevisionId,campus:input.campus,profile:j.profile,timePolicy:input.timePolicy,entries:input.operations.map((operation,index)=>({...operation,row:rows[index]!})),sourceArtifactId:received.artifact.artifactId,sourceRows:parsed.rows.map((_,index)=>parsed.cells.find(c=>c.row===index+1)?.sourceRow??index+2)};useCheck(LocationUseStoredStageSchema,value);staged=await recoverable(s,()=>stageIn(s,actor,value as LocationUseStoredStage));}catch(error){if(error instanceof Error&&error.message==='ACCESS_DENIED')throw error;issues.push({row:0,field:'',code:error instanceof Error?error.message:'CLOSED_INPUT_REQUIRED',status:'FAIL'});}else if(rows.length!==input.operations.length)issues.push({row:0,field:'operations',code:'BATCH_CONFLICT',status:'FAIL'});
    const evaluation:ValidationEvaluation={decision:issues.length?'FAIL':'BLOCKED',issues:issues.length?issues.map(i=>({rule:'ORG13_'+i.code,layer:2,row:i.row,field:i.field,status:'FAIL',code:i.code})):[{rule:'ORG13_USE_REVIEW',layer:7,row:0,field:'',status:'UNKNOWN',code:'LEGAL_REVIEW_REQUIRED'}],layers:[{layer:1,status:parsed.structuralStatus==='PARSED'?'PASS':'FAIL'},{layer:2,status:issues.length?'FAIL':'UNKNOWN'}],evidenceRequirements:[],dependencies:[],interpretationPolicy:'EXACT_TEXT_V1'};
    const validation=await recordOwnerFileValidation(s,provider,actor,{jobId:j.id,revisionId:j.currentRevisionId,sourceArtifactId:received.artifact.artifactId,campus:input.campus,requestId:randomUUID(),parseRequestId:randomUUID(),outputRequestId:randomUUID(),contractVersionId:j.contract.versionId,ruleVersion:j.contract.definition.ruleVersion,parserPolicy:'STRICT_LOCATION_USE_V1',structuralStatus:parsed.structuralStatus,parsed:{sourceArtifactId:received.artifact.artifactId,result:parsed,conversions},evaluation});return {jobId:j.id,revisionId:j.currentRevisionId,sourceArtifactId:received.artifact.artifactId,structuralStatus:parsed.structuralStatus,input:staged,issues,validation};
   });}finally{privateBytes.fill(0);}
  },
  close:runtime.close,
 };
}
export type LocationUseOwner=ReturnType<typeof openLocationUse>;
