/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export interface AccessControlObjectPermissionGrant {
  created_at: Generated<string>;
  governance_object_id: string;
  grant_effect: string;
  grant_sequence: Int8;
  granted_by: string;
  object_permission_grant_id: Generated<string>;
  permission_code: string;
  reason: string;
  security_principal_id: string;
  valid_from: string;
  valid_to: string | null;
}

export interface AuditAuditEvent {
  action: string;
  actor_principal_id: string;
  after_hash: Buffer | null;
  audit_event_id: Generated<string>;
  audit_sequence: Int8;
  audit_stream_id: string;
  authority_scope: string;
  correlation_id: string;
  created_at: Generated<string>;
  current_hash: Buffer;
  entity_type: string;
  entity_version_id: string | null;
  event_payload_hash: Buffer;
  governance_object_id: string;
  occurred_at: string;
  previous_hash: Buffer;
  request_id: string;
  stable_entity_id: string;
}

export interface ChargeCatalogChargeItem {
  charge_item_id: string;
  created_at: Generated<string>;
  created_by: string;
  internal_code: string;
  origin_campus_id: string | null;
  origin_scope: string;
}

export interface ChargeCatalogChargeItemVersion {
  billing_unit_code: string;
  business_period: Generated<string | null>;
  business_status: string;
  business_valid_from: string;
  business_valid_to: string | null;
  charge_item_id: string;
  charge_item_version_id: Generated<string>;
  charging_method_code: string;
  content_hash: Buffer;
  created_at: Generated<string>;
  created_by: string;
  formal_name: string;
  governance_status: string;
  recorded_from: string;
  recorded_period: Generated<string | null>;
  recorded_to: string | null;
  release_id: string | null;
  service_definition: string;
  version_no: Int8;
}

export interface ChargeCatalogPricedObject {
  created_at: Generated<string>;
  created_by: string;
  object_kind: string;
  priced_object_id: Generated<string>;
}

export interface PlatformBrowserSession {
  created_at: Generated<string>;
  csrf_digest: Buffer;
  expires_at: string;
  revoked_at: string | null;
  security_principal_id: string;
  session_digest: Buffer;
  session_sequence: Int8;
}

export interface PlatformCampus {
  campus_code: string;
  campus_id: Generated<string>;
  created_at: Generated<string>;
  display_name: string;
  status: Generated<string>;
}

export interface PlatformExternalIdentityBinding {
  binding_kind: string;
  binding_sequence: Int8;
  created_at: Generated<string>;
  external_client_id: string | null;
  external_identity_binding_id: Generated<string>;
  external_subject: string;
  issuer_url: string;
  security_principal_id: string;
  status: string;
}

export interface PlatformGovernanceObject {
  created_at: Generated<string>;
  created_by: string;
  display_name: string;
  governance_object_id: Generated<string>;
  object_code: string;
  object_type: string;
  status: Generated<string>;
}

export interface PlatformOidcLoginTransaction {
  code_verifier: string;
  consumed_at: string | null;
  created_at: Generated<string>;
  expires_at: string;
  nonce: string;
  redirect_uri: string;
  return_to: string;
  state_digest: Buffer;
}

export interface PlatformSchemaMigration {
  applied_at: Generated<string>;
  migration_id: string;
}

export interface PlatformSecurityPrincipal {
  created_at: Generated<string>;
  principal_code: string;
  principal_kind: string;
  security_principal_id: Generated<string>;
  status: Generated<string>;
}

export interface PriceListPriceEntry {
  billing_unit_code: string;
  business_period: Generated<string | null>;
  business_valid_from: string;
  business_valid_to: string | null;
  campus_id: string | null;
  content_hash: Buffer;
  created_at: Generated<string>;
  currency_code: string;
  encounter_coverage: Generated<string | null>;
  encounter_mode: string;
  encounter_type: string | null;
  entry_no: Int8;
  fixed_unit_price: Numeric;
  price_entry_id: Generated<string>;
  price_list_release_id: string;
  price_nature: string;
  priced_object_id: string;
  scope_key: Generated<string | null>;
  scope_level: string;
  zero_price_reason: string | null;
}

export interface PriceListPriceEntryChargeItemTarget {
  charge_item_id: string;
  charge_item_version_id: string;
  price_entry_id: string;
}

export interface PriceListPriceList {
  created_at: Generated<string>;
  created_by: string;
  governance_object_id: string;
  price_list_code: string;
  price_list_id: Generated<string>;
}

export interface PriceListPriceListRelease {
  business_period: Generated<string | null>;
  business_status: string;
  business_valid_from: string;
  business_valid_to: string | null;
  content_hash: Buffer;
  created_at: Generated<string>;
  created_by: string;
  currency_code: string;
  display_name: string;
  governance_release_id: string | null;
  governance_status: string;
  price_list_id: string;
  price_list_release_id: Generated<string>;
  recorded_from: string;
  recorded_period: Generated<string | null>;
  recorded_to: string | null;
  release_no: Int8;
}

export interface PriceResolutionPriceResolution {
  campus_id: string;
  created_at: Generated<string>;
  encounter_type: string;
  input_context_hash: Buffer;
  price_list_id: string;
  price_list_release_id: string | null;
  price_resolution_id: Generated<string>;
  priced_object_id: string;
  published_view_hash: Buffer | null;
  record_as_of: string;
  request_hash: Buffer;
  request_id: string;
  resolution_status: string;
  resolved_at: string;
  service_occurred_at: string;
}

export interface PriceResolutionPriceResolutionChargeItemTarget {
  charge_item_id: string;
  charge_item_version_id: string;
  price_resolution_id: string;
}

export interface PriceResolutionPriceResolutionResult {
  amount_before_rounding: Numeric;
  currency_code: string;
  final_amount: Numeric;
  matched_encounter_mode: string;
  matched_scope_level: string;
  price_entry_hash: Buffer;
  price_entry_id: string;
  price_list_release_hash: Buffer;
  price_list_release_id: string;
  price_resolution_id: string;
  price_resolution_result_id: Generated<string>;
  quantity: Numeric;
  result_hash: Buffer;
  unit_price: Numeric;
}

export interface PriceResolutionPriceResolutionStep {
  candidate_count: number;
  candidate_set_hash: Buffer;
  decision: string;
  encounter_mode_checked: string;
  explanation_code: string;
  price_entry_id: string | null;
  price_resolution_id: string;
  price_resolution_step_id: Generated<string>;
  scope_checked: string;
  step_no: Int8;
}

export interface ReleaseDistributionConsumerCheckpoint {
  applied_aggregate_version: Int8;
  consumer_subscription_id: string;
  governance_object_id: string;
  updated_at: Generated<string>;
}

export interface ReleaseDistributionConsumerCompatibilityIssue {
  consumer_compatibility_issue_id: Generated<string>;
  consumer_subscription_id: string;
  created_at: Generated<string>;
  event_id: string;
  issue_code: string;
  opened_compatibility_id: string;
}

export interface ReleaseDistributionConsumerCompatibilityIssueEvent {
  compatibility_id: string;
  consumer_compatibility_issue_event_id: Generated<string>;
  consumer_compatibility_issue_id: string;
  correlation_id: string;
  evidence_hash: Buffer;
  issue_sequence: Int8;
  issue_status: string;
  occurred_at: string;
}

export interface ReleaseDistributionConsumerProjectionSupport {
  consumer_subscription_version_id: string;
  projection_schema_digest: Buffer;
  projection_schema_version: string;
  projection_type: string;
}

export interface ReleaseDistributionConsumerReceipt {
  apply_result: string;
  consumer_receipt_id: Generated<string>;
  consumer_subscription_id: string;
  created_at: Generated<string>;
  event_id: string;
  processed_at: string;
  processing_digest: Buffer;
  receipt_sequence: Int8;
  receive_result: string;
  validation_result: string;
}

export interface ReleaseDistributionConsumerSubscription {
  consumer_subscription_id: Generated<string>;
  created_at: Generated<string>;
  governance_object_id: string;
  service_principal_id: string;
  subscription_code: string;
}

export interface ReleaseDistributionConsumerSubscriptionVersion {
  consumer_subscription_id: string;
  consumer_subscription_version_id: Generated<string>;
  created_at: Generated<string>;
  recorded_sequence: Int8;
  status: string;
  version_no: Int8;
}

export interface ReleaseDistributionDeliveryOperationalIssue {
  created_at: Generated<string>;
  delivery_operational_issue_id: Generated<string>;
  issue_code: string;
  outbox_delivery_id: string;
}

export interface ReleaseDistributionDeliveryOperationalIssueEvent {
  correlation_id: string;
  delivery_operational_issue_event_id: Generated<string>;
  delivery_operational_issue_id: string;
  error_code: string;
  issue_sequence: Int8;
  issue_status: string;
  occurred_at: string;
  outbox_delivery_attempt_id: string;
}

export interface ReleaseDistributionGovernanceRelease {
  approved_at: string;
  approved_by: string;
  business_valid_from: string;
  business_valid_to: string | null;
  change_reason: string;
  content_hash: Buffer;
  created_at: Generated<string>;
  governance_object_id: string;
  recorded_from: string;
  release_id: Generated<string>;
  release_kind: Generated<string>;
  release_no: Int8;
  submitted_by: string;
}

export interface ReleaseDistributionOutboxDelivery {
  consumer_subscription_id: string;
  created_at: Generated<string>;
  event_id: string;
  outbox_delivery_id: Generated<string>;
}

export interface ReleaseDistributionOutboxDeliveryAttempt {
  attempt_no: Int8;
  correlation_id: string;
  error_code: string | null;
  occurred_at: string;
  outbox_delivery_attempt_id: Generated<string>;
  outbox_delivery_id: string;
  outbox_delivery_state_id: string;
  response_digest: Buffer | null;
  result: string;
}

export interface ReleaseDistributionOutboxDeliveryState {
  compatibility_id: string;
  consumer_subscription_id: string;
  created_at: Generated<string>;
  delivery_status: string;
  event_id: string;
  lease_expires_at: string | null;
  lease_owner: string | null;
  next_attempt_at: string | null;
  outbox_delivery_id: string;
  outbox_delivery_state_id: Generated<string>;
  state_sequence: Int8;
}

export interface ReleaseDistributionOutboxEvent {
  aggregate_id: string;
  aggregate_type: string;
  aggregate_version: Int8;
  created_at: Generated<string>;
  event_id: Generated<string>;
  event_type: string;
  projection_payload_digest: Buffer;
  projection_schema_digest: Buffer;
  projection_schema_version: string;
  projection_type: string;
  release_id: string;
  release_snapshot_id: string;
  snapshot_artifact_digest: Buffer;
}

export interface ReleaseDistributionReleaseConsumerCompatibility {
  consumer_subscription_id: string;
  consumer_subscription_version_id: string;
  created_at: Generated<string>;
  event_id: string;
  evidence_hash: Buffer;
  release_consumer_compatibility_id: Generated<string>;
  release_id: string;
  result: string;
  result_sequence: Int8;
}

export interface ReleaseDistributionReleaseMemberChargeItem {
  charge_item_id: string;
  charge_item_version_id: string;
  member_hash: Buffer;
  release_id: string;
  release_member_id: Generated<string>;
  snapshot_name: string;
}

export interface ReleaseDistributionReleaseMemberPriceList {
  member_hash: Buffer;
  price_list_id: string;
  price_list_release_id: string;
  release_id: string;
  release_member_id: Generated<string>;
  snapshot_name: string;
}

export interface ReleaseDistributionReleaseSnapshot {
  artifact_byte_length: Generated<Int8 | null>;
  artifact_bytes: Buffer;
  artifact_media_type: string;
  artifact_role: Generated<string>;
  created_at: Generated<string>;
  envelope_contract_version: string;
  item_count: Int8;
  projection_payload_digest: Buffer;
  projection_schema_digest: Buffer;
  projection_schema_version: string;
  projection_type: string;
  release_id: string;
  release_snapshot_id: Generated<string>;
  serialization_profile_version: string;
  snapshot_artifact_digest: Buffer;
}

export interface WorkflowApprovalAction {
  action_result: string;
  action_sequence: Int8;
  actor_principal_id: string;
  approval_action_id: Generated<string>;
  change_request_id: string;
  occurred_at: string;
  reason: string;
  seen_content_hash: Buffer;
  stage_type: string;
}

export interface WorkflowApprovalTemplate {
  approval_template_id: string;
  created_at: Generated<string>;
  display_name: string;
  status: string;
  template_code: string;
}

export interface WorkflowApprovalTemplateVersion {
  approval_template_id: string;
  approval_template_version_id: string;
  content_hash: Buffer;
  governance_status: string;
  published_at: string;
  stage_type: string;
  submitter_may_approve: boolean;
  version_no: Int8;
}

export interface WorkflowChangeRequest {
  approval_template_version_id: string;
  change_kind: string;
  change_reason: string;
  change_request_id: Generated<string>;
  created_at: Generated<string>;
  decided_at: string | null;
  entity_version_id: string;
  governance_object_id: string;
  request_status: string;
  stable_entity_id: string;
  submitted_by: string;
  submitted_content_hash: Buffer;
}

export interface DB {
  "access_control.object_permission_grant": AccessControlObjectPermissionGrant;
  "audit.audit_event": AuditAuditEvent;
  "charge_catalog.charge_item": ChargeCatalogChargeItem;
  "charge_catalog.charge_item_version": ChargeCatalogChargeItemVersion;
  "charge_catalog.priced_object": ChargeCatalogPricedObject;
  "platform.browser_session": PlatformBrowserSession;
  "platform.campus": PlatformCampus;
  "platform.external_identity_binding": PlatformExternalIdentityBinding;
  "platform.governance_object": PlatformGovernanceObject;
  "platform.oidc_login_transaction": PlatformOidcLoginTransaction;
  "platform.schema_migration": PlatformSchemaMigration;
  "platform.security_principal": PlatformSecurityPrincipal;
  "price_list.price_entry": PriceListPriceEntry;
  "price_list.price_entry_charge_item_target": PriceListPriceEntryChargeItemTarget;
  "price_list.price_list": PriceListPriceList;
  "price_list.price_list_release": PriceListPriceListRelease;
  "price_resolution.price_resolution": PriceResolutionPriceResolution;
  "price_resolution.price_resolution_charge_item_target": PriceResolutionPriceResolutionChargeItemTarget;
  "price_resolution.price_resolution_result": PriceResolutionPriceResolutionResult;
  "price_resolution.price_resolution_step": PriceResolutionPriceResolutionStep;
  "release_distribution.consumer_checkpoint": ReleaseDistributionConsumerCheckpoint;
  "release_distribution.consumer_compatibility_issue": ReleaseDistributionConsumerCompatibilityIssue;
  "release_distribution.consumer_compatibility_issue_event": ReleaseDistributionConsumerCompatibilityIssueEvent;
  "release_distribution.consumer_projection_support": ReleaseDistributionConsumerProjectionSupport;
  "release_distribution.consumer_receipt": ReleaseDistributionConsumerReceipt;
  "release_distribution.consumer_subscription": ReleaseDistributionConsumerSubscription;
  "release_distribution.consumer_subscription_version": ReleaseDistributionConsumerSubscriptionVersion;
  "release_distribution.delivery_operational_issue": ReleaseDistributionDeliveryOperationalIssue;
  "release_distribution.delivery_operational_issue_event": ReleaseDistributionDeliveryOperationalIssueEvent;
  "release_distribution.governance_release": ReleaseDistributionGovernanceRelease;
  "release_distribution.outbox_delivery": ReleaseDistributionOutboxDelivery;
  "release_distribution.outbox_delivery_attempt": ReleaseDistributionOutboxDeliveryAttempt;
  "release_distribution.outbox_delivery_state": ReleaseDistributionOutboxDeliveryState;
  "release_distribution.outbox_event": ReleaseDistributionOutboxEvent;
  "release_distribution.release_consumer_compatibility": ReleaseDistributionReleaseConsumerCompatibility;
  "release_distribution.release_member_charge_item": ReleaseDistributionReleaseMemberChargeItem;
  "release_distribution.release_member_price_list": ReleaseDistributionReleaseMemberPriceList;
  "release_distribution.release_snapshot": ReleaseDistributionReleaseSnapshot;
  "workflow.approval_action": WorkflowApprovalAction;
  "workflow.approval_template": WorkflowApprovalTemplate;
  "workflow.approval_template_version": WorkflowApprovalTemplateVersion;
  "workflow.change_request": WorkflowChangeRequest;
}
