/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export interface AccessControlAuthorizationDecision {
  authorization_decision_id: Generated<string>;
  correlation_id: string;
  decided_at: string;
  decision: string;
  explanation_code: string;
  governance_object_id: string;
  permission_code: string;
  request_id: string;
  requested_campus_id: string | null;
  requested_scope_level: string;
  security_principal_id: string;
}

export interface AccessControlObjectPermissionGrant {
  campus_id: string | null;
  created_at: Generated<string>;
  governance_object_id: string;
  grant_effect: string;
  grant_sequence: Int8;
  granted_by: string;
  object_permission_grant_id: Generated<string>;
  permission_code: string;
  reason: string;
  scope_level: Generated<string>;
  security_principal_id: string;
  valid_from: string;
  valid_to: string | null;
}

export interface AuditAuditEvent {
  action: string;
  actor_principal_id: string;
  after_hash: Buffer | null;
  audit_event_id: Generated<string>;
  audit_sequence: Int8;
  audit_stream_id: string;
  authority_scope: string;
  correlation_id: string;
  created_at: Generated<string>;
  current_hash: Buffer;
  entity_type: string;
  entity_version_id: string | null;
  /**
   * Minimal business facts for typed governance events; credentials and complete request bodies are forbidden.
   */
  event_payload: Json | null;
  event_payload_hash: Buffer;
  governance_object_id: string;
  occurred_at: string;
  previous_hash: Buffer;
  /**
   * Asia/Shanghai local database time at which the audit event was durably recorded.
   */
  recorded_at: string | null;
  request_id: string;
  stable_entity_id: string;
}

export interface BatchImportImportJob {
  completed_at: string | null;
  created_at: string;
  failed_count: Generated<number>;
  governance_object_id: string;
  import_job_id: Generated<string>;
  import_type: string;
  job_status: string;
  normalized_content_digest: Buffer;
  raw_content_digest: Buffer;
  row_count: number;
  schema_version: string;
  source_kind: string;
  submitted_by: string;
  succeeded_count: Generated<number>;
}

export interface BatchImportImportRow {
  business_key: string;
  current_error_code: string | null;
  entity_version_id: string | null;
  import_job_id: string;
  import_row_id: Generated<string>;
  normalized_payload: Json;
  normalized_payload_digest: Buffer;
  result_kind: string | null;
  retryable: Generated<boolean>;
  row_no: Int8;
  row_status: string;
  source_row_id: string;
  stable_entity_id: string | null;
}

export interface BatchImportImportRowAttempt {
  attempt_result: string;
  attempt_sequence: Int8;
  attempted_at: string;
  attempted_by: string;
  error_code: string | null;
  evidence: Json;
  import_row_attempt_id: Generated<string>;
  import_row_id: string;
  rule_version: string;
}

export interface ChargeCatalogChargeItem {
  charge_item_id: string;
  created_at: Generated<string>;
  created_by: string;
  governance_object_id: string;
  internal_code: string;
  origin_campus_id: string | null;
  origin_scope: string;
}

export interface ChargeCatalogChargeItemVersion {
  billing_unit_code: string;
  business_period: Generated<string | null>;
  business_status: string;
  business_valid_from: string;
  business_valid_to: string | null;
  charge_item_id: string;
  charge_item_version_id: Generated<string>;
  charging_method_code: string;
  content_hash: Buffer;
  created_at: Generated<string>;
  created_by: string;
  formal_name: string;
  governance_status: string;
  recorded_from: string;
  recorded_period: Generated<string | null>;
  recorded_to: string | null;
  release_id: string | null;
  service_definition: string;
  version_no: Int8;
}

export interface ChargeCatalogPricedObject {
  created_at: Generated<string>;
  created_by: string;
  object_kind: string;
  priced_object_id: Generated<string>;
}

export interface DepartmentMasterDepartment {
  created_at: Generated<string>;
  created_by: string;
  department_code: string;
  department_id: Generated<string>;
  governance_object_id: string;
  updated_at: Generated<string>;
  updated_by: string;
}

export interface DepartmentMasterDepartmentAlias {
  confidence_score: Numeric | null;
  created_at: Generated<string>;
  department_alias_id: Generated<string>;
  department_id: string;
  mapping_status: string;
  source_code: string;
  source_name: string;
  source_system: string;
  updated_at: Generated<string>;
}

export interface DepartmentMasterDepartmentCampusAssignment {
  business_period: Generated<string | null>;
  business_valid_from: string;
  business_valid_to: string | null;
  campus_id: string;
  content_hash: Buffer;
  created_at: Generated<string>;
  created_by: string;
  department_campus_assignment_id: Generated<string>;
  department_id: string;
  recorded_from: string;
  recorded_period: Generated<string | null>;
  recorded_to: string | null;
  updated_at: Generated<string>;
  updated_by: string;
}

export interface DepartmentMasterDepartmentHierarchyGroup {
  created_at: Generated<string>;
  created_by: string;
  department_hierarchy_group_id: Generated<string>;
  department_hierarchy_view_id: string;
  group_code: string;
  updated_at: Generated<string>;
  updated_by: string;
}

export interface DepartmentMasterDepartmentHierarchyGroupVersion {
  business_period: Generated<string | null>;
  business_valid_from: string;
  business_valid_to: string | null;
  content_hash: Buffer;
  created_at: Generated<string>;
  created_by: string;
  department_hierarchy_group_id: string;
  department_hierarchy_group_version_id: Generated<string>;
  department_hierarchy_view_id: string;
  display_name: string;
  recorded_from: string;
  recorded_period: Generated<string | null>;
  recorded_to: string | null;
  updated_at: Generated<string>;
  updated_by: string;
  version_no: Int8;
}

export interface DepartmentMasterDepartmentHierarchyNode {
  created_at: Generated<string>;
  department_hierarchy_group_id: string | null;
  department_hierarchy_group_version_id: string | null;
  department_hierarchy_node_id: Generated<string>;
  department_hierarchy_view_id: string;
  department_hierarchy_view_version_id: string;
  department_id: string | null;
  department_version_id: string | null;
  display_name: string;
  node_kind: string;
  parent_node_id: string | null;
  sort_order: Generated<number>;
  updated_at: Generated<string>;
}

export interface DepartmentMasterDepartmentHierarchyView {
  created_at: Generated<string>;
  created_by: string;
  department_hierarchy_view_id: Generated<string>;
  governance_object_id: string;
  operational_enabled: boolean;
  updated_at: Generated<string>;
  updated_by: string;
  view_code: string;
  view_name: string;
  view_type: string;
}

export interface DepartmentMasterDepartmentHierarchyViewVersion {
  business_period: Generated<string | null>;
  business_valid_from: string;
  business_valid_to: string | null;
  content_hash: Buffer;
  created_at: Generated<string>;
  created_by: string;
  department_hierarchy_view_id: string;
  department_hierarchy_view_version_id: Generated<string>;
  governance_status: string;
  recorded_from: string;
  recorded_period: Generated<string | null>;
  recorded_to: string | null;
  release_id: string | null;
  updated_at: Generated<string>;
  updated_by: string;
  version_no: Int8;
}

export interface DepartmentMasterDepartmentPublishedProjection {
  campuses: Json;
  content_hash: Buffer;
  created_at: Generated<string>;
  department_code: string;
  department_id: string;
  department_published_projection_id: Generated<string>;
  department_type: string;
  department_version_id: string;
  hierarchies: Json;
  published_at: string;
  published_release_id: string;
  quality_score: Numeric | null;
  standard_name: string;
  subject_mapping_applicability: string;
  superseded_at: string | null;
  updated_at: Generated<string | null>;
}

export interface DepartmentMasterDepartmentQualityScore {
  calculated_at: string;
  completeness_score: Numeric;
  created_at: Generated<string>;
  department_id: string;
  department_quality_score_id: Generated<string>;
  overall_score: Numeric;
  standardization_score: Numeric;
  uniqueness_score: Numeric;
  updated_at: Generated<string>;
}

export interface DepartmentMasterDepartmentSourceMapping {
  created_at: Generated<string>;
  department_id: string;
  department_mapping_id: Generated<string>;
  mapping_status: string;
  match_method: string;
  source_department_code: string;
  source_department_name: string;
  source_system: string;
  updated_at: Generated<string>;
}

export interface DepartmentMasterDepartmentVersion {
  business_period: Generated<string | null>;
  business_status: string;
  business_valid_from: string;
  business_valid_to: string | null;
  clinical_flag: boolean;
  content_hash: Buffer;
  created_at: Generated<string>;
  created_by: string;
  department_id: string;
  department_type: string;
  department_version_id: Generated<string>;
  description: string | null;
  governance_status: string;
  management_flag: boolean;
  recorded_from: string;
  recorded_period: Generated<string | null>;
  recorded_to: string | null;
  release_id: string | null;
  short_name: string | null;
  standard_name: string;
  subject_mapping_applicability: string;
  updated_at: Generated<string>;
  updated_by: string;
  version_no: Int8;
}

export interface DepartmentMasterMasterDataSource {
  created_at: Generated<string>;
  enabled: Generated<boolean>;
  master_data_source_id: string;
  source_code: string;
  source_name: string;
  system_type: string;
  updated_at: Generated<string>;
}

export interface EmergencyControlImpactCase {
  case_status: string;
  closed_at: string | null;
  created_at: string;
  emergency_actor_principal_id: string;
  impact_case_id: Generated<string>;
  priority: string;
  recovery_release_id: string | null;
  suspension_event_id: string;
}

export interface EmergencyControlImpactCaseAction {
  action_sequence: Int8;
  action_type: string;
  actor_principal_id: string;
  evidence: Json;
  impact_case_action_id: Generated<string>;
  impact_case_id: string;
  occurred_at: string;
  reason: string;
}

export interface EmergencyControlSuspensionEvent {
  actor_principal_id: string;
  campus_id: string | null;
  correlation_id: string;
  effective_from: string;
  event_sequence: Int8;
  evidence: Json;
  governance_object_id: string;
  price_list_id: string;
  price_list_release_id: string;
  reason: string;
  recorded_at: string;
  request_id: string;
  scope_level: string;
  suspension_event_id: Generated<string>;
}

export interface PersonMasterEngagement {
  created_at: Generated<string>;
  created_by: string;
  creation_request_id: string;
  engagement_id: Generated<string>;
  governance_object_id: string;
  person_id: string;
}

export interface PersonMasterEngagementClassification {
  classified_at: Generated<string>;
  classified_by: string;
  engagement_id: string;
  engagement_type_id: string;
  engagement_type_version_id: string;
  governance_object_id: string;
  person_id: string;
  request_id: string;
}

export interface PersonMasterEngagementLifecycleEvent {
  /**
   * Asia/Shanghai business-effective local timestamp; never replaced by record or creation time.
   */
  business_effective_at: string;
  created_by: string;
  engagement_id: string;
  engagement_lifecycle_event_id: Generated<string>;
  event_type: string;
  governance_object_id: string;
  operation_hash: Buffer;
  reason_code: string;
  recorded_at: Generated<string>;
  request_id: string;
  /**
   * Monotonic per-Engagement append sequence. Business-state ordering also respects business_effective_at and recordAsOf.
   */
  sequence_no: Int8;
}

export interface PersonMasterEngagementLifecycleRejection {
  created_by: string;
  engagement_id: string;
  engagement_lifecycle_rejection_id: Generated<string>;
  governance_object_id: string;
  operation_hash: Buffer;
  operation_type: string;
  recorded_at: Generated<string>;
  rejection_code: string;
  request_id: string;
}

export interface PersonMasterEngagementOverlapRule {
  created_at: Generated<string>;
  created_by: string;
  creation_request_id: string;
  engagement_overlap_rule_id: Generated<string>;
  governance_object_id: string;
  left_type_code: string;
  right_type_code: string;
}

export interface PersonMasterEngagementOverlapRuleVersion {
  business_period: Generated<string | null>;
  business_valid_from: string;
  business_valid_to: string | null;
  created_by: string;
  decision: string;
  engagement_overlap_rule_id: string;
  engagement_overlap_rule_version_id: Generated<string>;
  governance_object_id: string;
  operation_hash: Buffer;
  recorded_from: Generated<string>;
  request_id: string;
  supersedes_engagement_overlap_rule_version_id: string | null;
  version_no: Int8;
}

export interface PersonMasterEngagementType {
  created_at: Generated<string>;
  created_by: string;
  creation_request_id: string;
  engagement_type_id: Generated<string>;
  governance_object_id: string;
  type_code: string;
}

export interface PersonMasterEngagementTypeVersion {
  business_period: Generated<string | null>;
  business_valid_from: string;
  business_valid_to: string | null;
  category_code: string;
  created_by: string;
  display_name: string;
  engagement_type_id: string;
  engagement_type_version_id: Generated<string>;
  governance_object_id: string;
  operation_hash: Buffer;
  recorded_from: Generated<string>;
  request_id: string;
  supersedes_engagement_type_version_id: string | null;
  version_no: Int8;
}

export interface PersonMasterEngagementVersion {
  business_period: Generated<string | null>;
  business_valid_from: string;
  business_valid_to: string | null;
  created_by: string;
  engagement_id: string;
  engagement_version_id: Generated<string>;
  governance_object_id: string;
  operation_hash: Buffer;
  person_id: string;
  /**
   * Asia/Shanghai database record time, strictly increasing per Engagement.
   */
  recorded_from: Generated<string>;
  request_id: string;
  /**
   * B-01 revision provenance only; it is not an Engagement lifecycle or business-state field.
   */
  revision_reason_code: string | null;
  supersedes_engagement_version_id: string | null;
  version_no: Int8;
}

export interface PersonMasterPersonIdentifier {
  created_at: Generated<string>;
  created_by: string;
  creation_request_id: string;
  governance_object_id: string;
  identifier_system: string;
  identifier_value: string;
  person_id: string;
  person_identifier_id: Generated<string>;
}

export interface PersonMasterPersonIdentifierVersion {
  assertion_status: string;
  business_period: Generated<string | null>;
  business_valid_from: string;
  business_valid_to: string | null;
  created_by: string;
  governance_object_id: string;
  /**
   * Retry identity for operation kind and assertion validity only. Never contains identifier value or its hash; never exported to audit.
   */
  operation_hash: Buffer;
  person_id: string;
  person_identifier_id: string;
  person_identifier_version_id: Generated<string>;
  recorded_from: Generated<string>;
  request_id: string;
  version_no: Int8;
}

export interface PersonMasterPersonSourceMapping {
  created_at: Generated<string>;
  created_by: string;
  creation_request_id: string;
  governance_object_id: string;
  person_source_mapping_id: Generated<string>;
  source_entity: string;
  /**
   * Opaque canonical source-adapter key. It is not a Person Identifier and must not enter audit, logs, errors or metrics.
   */
  source_record_key: string;
  source_system: string;
}

export interface PersonMasterPersonSourceMappingVersion {
  business_period: Generated<string | null>;
  business_valid_from: string;
  business_valid_to: string | null;
  change_kind: string;
  created_by: string;
  governance_object_id: string;
  mapping_status: string;
  /**
   * Internal retry identity only. Never exported to audit, logs or metrics.
   */
  operation_hash: Buffer;
  person_id: string;
  person_source_mapping_id: string;
  person_source_mapping_version_id: Generated<string>;
  reason_code: string | null;
  recorded_from: Generated<string>;
  request_id: string;
  supersedes_mapping_version_id: string | null;
  version_no: Int8;
}

export interface PersonMasterPersonSubject {
  created_at: Generated<string>;
  created_by: string;
  creation_request_id: string;
  governance_object_id: string;
  person_id: Generated<string>;
}

export interface PersonMasterPersonSubjectVersion {
  /**
   * Optional calendar date, never a timestamp.
   */
  birth_date: string | null;
  business_period: Generated<string | null>;
  business_valid_from: string;
  business_valid_to: string | null;
  canonical_name: string;
  created_by: string;
  governance_object_id: string;
  operation_hash: Buffer;
  person_id: string;
  person_version_id: Generated<string>;
  /**
   * Asia/Shanghai database record time; per-person version_no owns ordering.
   */
  recorded_from: Generated<string>;
  request_id: string;
  version_no: Int8;
}

export interface PlatformBrowserSession {
  created_at: Generated<string>;
  csrf_digest: Buffer;
  expires_at: string;
  revoked_at: string | null;
  security_principal_id: string;
  session_digest: Buffer;
  session_sequence: Int8;
}

export interface PlatformCampus {
  campus_code: string;
  campus_id: Generated<string>;
  created_at: Generated<string>;
  display_name: string;
  status: Generated<string>;
}

export interface PlatformExternalIdentityBinding {
  binding_kind: string;
  binding_sequence: Int8;
  created_at: Generated<string>;
  external_client_id: string | null;
  external_identity_binding_id: Generated<string>;
  external_subject: string;
  issuer_url: string;
  security_principal_id: string;
  status: string;
}

export interface PlatformGovernanceObject {
  created_at: Generated<string>;
  created_by: string;
  display_name: string;
  governance_object_id: Generated<string>;
  object_code: string;
  object_type: string;
  status: Generated<string>;
}

export interface PlatformOidcLoginTransaction {
  code_verifier: string;
  consumed_at: string | null;
  created_at: Generated<string>;
  expires_at: string;
  nonce: string;
  redirect_uri: string;
  return_to: string;
  state_digest: Buffer;
}

export interface PlatformSchemaMigration {
  applied_at: Generated<string>;
  migration_id: string;
}

export interface PlatformSecurityPrincipal {
  created_at: Generated<string>;
  principal_code: string;
  principal_kind: string;
  security_principal_id: Generated<string>;
  status: Generated<string>;
}

export interface PriceListPriceEntry {
  billing_unit_code: string;
  business_period: Generated<string | null>;
  business_valid_from: string;
  business_valid_to: string | null;
  campus_id: string | null;
  content_hash: Buffer;
  created_at: Generated<string>;
  currency_code: string;
  encounter_coverage: Generated<string | null>;
  encounter_mode: string;
  encounter_type: string | null;
  entry_no: Int8;
  fixed_unit_price: Numeric;
  price_entry_id: Generated<string>;
  price_list_release_id: string;
  price_nature: string;
  priced_object_id: string;
  scope_key: Generated<string | null>;
  scope_level: string;
  zero_price_reason: string | null;
}

export interface PriceListPriceEntryChargeItemTarget {
  charge_item_id: string;
  charge_item_version_id: string;
  price_entry_id: string;
}

export interface PriceListPriceList {
  created_at: Generated<string>;
  created_by: string;
  governance_object_id: string;
  price_list_code: string;
  price_list_id: Generated<string>;
}

export interface PriceListPriceListRelease {
  business_period: Generated<string | null>;
  business_status: string;
  business_valid_from: string;
  business_valid_to: string | null;
  content_hash: Buffer;
  created_at: Generated<string>;
  created_by: string;
  currency_code: string;
  display_name: string;
  governance_release_id: string | null;
  governance_status: string;
  price_list_id: string;
  price_list_release_id: Generated<string>;
  recorded_from: string;
  recorded_period: Generated<string | null>;
  recorded_to: string | null;
  release_no: Int8;
}

export interface PriceResolutionPriceResolution {
  campus_id: string;
  created_at: Generated<string>;
  encounter_type: string;
  input_context_hash: Buffer;
  price_list_id: string;
  price_list_release_id: string | null;
  price_resolution_id: Generated<string>;
  priced_object_id: string;
  published_view_hash: Buffer | null;
  record_as_of: string;
  request_hash: Buffer;
  request_id: string;
  resolution_status: string;
  resolved_at: string;
  service_occurred_at: string;
}

export interface PriceResolutionPriceResolutionChargeItemTarget {
  charge_item_id: string;
  charge_item_version_id: string;
  price_resolution_id: string;
}

export interface PriceResolutionPriceResolutionResult {
  amount_before_rounding: Numeric;
  currency_code: string;
  final_amount: Numeric;
  matched_encounter_mode: string;
  matched_scope_level: string;
  price_entry_hash: Buffer;
  price_entry_id: string;
  price_list_release_hash: Buffer;
  price_list_release_id: string;
  price_resolution_id: string;
  price_resolution_result_id: Generated<string>;
  quantity: Numeric;
  result_hash: Buffer;
  unit_price: Numeric;
}

export interface PriceResolutionPriceResolutionStep {
  candidate_count: number;
  candidate_set_hash: Buffer;
  decision: string;
  encounter_mode_checked: string;
  explanation_code: string;
  price_entry_id: string | null;
  price_resolution_id: string;
  price_resolution_step_id: Generated<string>;
  scope_checked: string;
  step_no: Int8;
}

export interface ReleaseDistributionConsumerCheckpoint {
  applied_aggregate_version: Int8;
  consumer_subscription_id: string;
  governance_object_id: string;
  updated_at: Generated<string>;
}

export interface ReleaseDistributionConsumerCompatibilityIssue {
  consumer_compatibility_issue_id: Generated<string>;
  consumer_subscription_id: string;
  created_at: Generated<string>;
  event_id: string;
  issue_code: string;
  opened_compatibility_id: string;
}

export interface ReleaseDistributionConsumerCompatibilityIssueEvent {
  compatibility_id: string;
  consumer_compatibility_issue_event_id: Generated<string>;
  consumer_compatibility_issue_id: string;
  correlation_id: string;
  evidence_hash: Buffer;
  issue_sequence: Int8;
  issue_status: string;
  occurred_at: string;
}

export interface ReleaseDistributionConsumerProjectionSupport {
  consumer_subscription_version_id: string;
  projection_schema_digest: Buffer;
  projection_schema_version: string;
  projection_type: string;
}

export interface ReleaseDistributionConsumerReceipt {
  apply_result: string;
  consumer_receipt_id: Generated<string>;
  consumer_subscription_id: string;
  created_at: Generated<string>;
  event_id: string;
  processed_at: string;
  processing_digest: Buffer;
  receipt_sequence: Int8;
  receive_result: string;
  validation_result: string;
}

export interface ReleaseDistributionConsumerSubscription {
  consumer_subscription_id: Generated<string>;
  created_at: Generated<string>;
  governance_object_id: string;
  lifecycle_changed_at: Generated<string>;
  lifecycle_status: Generated<string>;
  service_principal_id: string;
  subscription_code: string;
}

export interface ReleaseDistributionConsumerSubscriptionVersion {
  consumer_subscription_id: string;
  consumer_subscription_version_id: Generated<string>;
  created_at: Generated<string>;
  criticality: Generated<string>;
  expected_apply_within_seconds: number | null;
  recorded_sequence: Int8;
  retry_window_seconds: number | null;
  status: string;
  version_no: Int8;
}

export interface ReleaseDistributionDeliveryOperationalIssue {
  created_at: Generated<string>;
  delivery_operational_issue_id: Generated<string>;
  issue_code: string;
  outbox_delivery_id: string;
}

export interface ReleaseDistributionDeliveryOperationalIssueEvent {
  correlation_id: string;
  delivery_operational_issue_event_id: Generated<string>;
  delivery_operational_issue_id: string;
  error_code: string;
  issue_sequence: Int8;
  issue_status: string;
  occurred_at: string;
  outbox_delivery_attempt_id: string;
}

export interface ReleaseDistributionGovernanceRelease {
  approved_at: string;
  approved_by: string;
  business_valid_from: string;
  business_valid_to: string | null;
  change_reason: string;
  content_hash: Buffer;
  created_at: Generated<string>;
  governance_object_id: string;
  recorded_from: string;
  release_id: Generated<string>;
  release_kind: Generated<string>;
  release_no: Int8;
  submitted_by: string;
}

export interface ReleaseDistributionOutboxDelivery {
  consumer_subscription_id: string;
  created_at: Generated<string>;
  event_id: string;
  outbox_delivery_id: Generated<string>;
}

export interface ReleaseDistributionOutboxDeliveryAttempt {
  attempt_no: Int8;
  correlation_id: string;
  error_code: string | null;
  occurred_at: string;
  outbox_delivery_attempt_id: Generated<string>;
  outbox_delivery_id: string;
  outbox_delivery_state_id: string;
  response_digest: Buffer | null;
  result: string;
}

export interface ReleaseDistributionOutboxDeliveryState {
  compatibility_id: string;
  consumer_subscription_id: string;
  created_at: Generated<string>;
  delivery_status: string;
  event_id: string;
  lease_expires_at: string | null;
  lease_owner: string | null;
  next_attempt_at: string | null;
  outbox_delivery_id: string;
  outbox_delivery_state_id: Generated<string>;
  state_sequence: Int8;
}

export interface ReleaseDistributionOutboxEvent {
  aggregate_id: string;
  aggregate_type: string;
  aggregate_version: Int8;
  created_at: Generated<string>;
  event_id: Generated<string>;
  event_type: string;
  projection_payload_digest: Buffer;
  projection_schema_digest: Buffer;
  projection_schema_version: string;
  projection_type: string;
  release_id: string;
  release_snapshot_id: string;
  snapshot_artifact_digest: Buffer;
}

export interface ReleaseDistributionReleaseConsumerCompatibility {
  consumer_subscription_id: string;
  consumer_subscription_version_id: string;
  created_at: Generated<string>;
  event_id: string;
  evidence_hash: Buffer;
  release_consumer_compatibility_id: Generated<string>;
  release_id: string;
  result: string;
  result_sequence: Int8;
}

export interface ReleaseDistributionReleaseMemberChargeItem {
  charge_item_id: string;
  charge_item_version_id: string;
  member_hash: Buffer;
  release_id: string;
  release_member_id: Generated<string>;
  snapshot_name: string;
}

export interface ReleaseDistributionReleaseMemberDepartment {
  created_at: Generated<string>;
  department_id: string;
  department_version_id: string;
  member_hash: Buffer;
  release_id: string;
  release_member_id: Generated<string>;
  snapshot_name: string;
  updated_at: Generated<string>;
}

export interface ReleaseDistributionReleaseMemberDepartmentHierarchy {
  created_at: Generated<string>;
  department_hierarchy_view_id: string;
  department_hierarchy_view_version_id: string;
  member_hash: Buffer;
  release_id: string;
  release_member_id: Generated<string>;
  snapshot_name: string;
  updated_at: Generated<string>;
}

export interface ReleaseDistributionReleaseMemberPriceList {
  member_hash: Buffer;
  price_list_id: string;
  price_list_release_id: string;
  release_id: string;
  release_member_id: Generated<string>;
  snapshot_name: string;
}

export interface ReleaseDistributionReleaseRelationship {
  created_at: string;
  reason: string;
  relationship_type: string;
  release_relationship_id: Generated<string>;
  source_release_id: string;
  target_release_id: string;
}

export interface ReleaseDistributionReleaseSnapshot {
  artifact_byte_length: Generated<Int8 | null>;
  artifact_bytes: Buffer;
  artifact_media_type: string;
  artifact_role: Generated<string>;
  created_at: Generated<string>;
  envelope_contract_version: string;
  item_count: Int8;
  projection_payload_digest: Buffer;
  projection_schema_digest: Buffer;
  projection_schema_version: string;
  projection_type: string;
  release_id: string;
  release_snapshot_id: Generated<string>;
  serialization_profile_version: string;
  snapshot_artifact_digest: Buffer;
}

export interface WorkflowApprovalAction {
  action_result: string;
  action_sequence: Int8;
  actor_principal_id: string;
  approval_action_id: Generated<string>;
  change_request_id: string;
  occurred_at: string;
  reason: string;
  seen_content_hash: Buffer;
  stage_type: string;
}

export interface WorkflowApprovalTemplate {
  approval_template_id: string;
  created_at: Generated<string>;
  display_name: string;
  status: string;
  template_code: string;
}

export interface WorkflowApprovalTemplateStage {
  approval_template_version_id: string;
  campus_scope_required: Generated<boolean>;
  permission_code: string;
  stage_sequence: Int8;
  stage_type: string;
}

export interface WorkflowApprovalTemplateVersion {
  approval_template_id: string;
  approval_template_version_id: string;
  content_hash: Buffer;
  governance_status: string;
  published_at: string;
  stage_type: string;
  submitter_may_approve: boolean;
  version_no: Int8;
}

export interface WorkflowChangeRequest {
  approval_template_version_id: string;
  change_kind: string;
  change_reason: string;
  change_request_id: Generated<string>;
  created_at: Generated<string>;
  decided_at: string | null;
  entity_version_id: string;
  frozen_evidence: Generated<Json>;
  governance_object_id: string;
  next_action_sequence: Generated<Int8>;
  request_status: string;
  required_stage_count: Generated<number>;
  risk_classification: Generated<string>;
  stable_entity_id: string;
  submitted_by: string;
  submitted_content_hash: Buffer;
}

export interface DB {
  "access_control.authorization_decision": AccessControlAuthorizationDecision;
  "access_control.object_permission_grant": AccessControlObjectPermissionGrant;
  "audit.audit_event": AuditAuditEvent;
  "batch_import.import_job": BatchImportImportJob;
  "batch_import.import_row": BatchImportImportRow;
  "batch_import.import_row_attempt": BatchImportImportRowAttempt;
  "charge_catalog.charge_item": ChargeCatalogChargeItem;
  "charge_catalog.charge_item_version": ChargeCatalogChargeItemVersion;
  "charge_catalog.priced_object": ChargeCatalogPricedObject;
  "department_master.department": DepartmentMasterDepartment;
  "department_master.department_alias": DepartmentMasterDepartmentAlias;
  "department_master.department_campus_assignment": DepartmentMasterDepartmentCampusAssignment;
  "department_master.department_hierarchy_group": DepartmentMasterDepartmentHierarchyGroup;
  "department_master.department_hierarchy_group_version": DepartmentMasterDepartmentHierarchyGroupVersion;
  "department_master.department_hierarchy_node": DepartmentMasterDepartmentHierarchyNode;
  "department_master.department_hierarchy_view": DepartmentMasterDepartmentHierarchyView;
  "department_master.department_hierarchy_view_version": DepartmentMasterDepartmentHierarchyViewVersion;
  "department_master.department_published_projection": DepartmentMasterDepartmentPublishedProjection;
  "department_master.department_quality_score": DepartmentMasterDepartmentQualityScore;
  "department_master.department_source_mapping": DepartmentMasterDepartmentSourceMapping;
  "department_master.department_version": DepartmentMasterDepartmentVersion;
  "department_master.master_data_source": DepartmentMasterMasterDataSource;
  "emergency_control.impact_case": EmergencyControlImpactCase;
  "emergency_control.impact_case_action": EmergencyControlImpactCaseAction;
  "emergency_control.suspension_event": EmergencyControlSuspensionEvent;
  "person_master.engagement": PersonMasterEngagement;
  "person_master.engagement_classification": PersonMasterEngagementClassification;
  "person_master.engagement_lifecycle_event": PersonMasterEngagementLifecycleEvent;
  "person_master.engagement_lifecycle_rejection": PersonMasterEngagementLifecycleRejection;
  "person_master.engagement_overlap_rule": PersonMasterEngagementOverlapRule;
  "person_master.engagement_overlap_rule_version": PersonMasterEngagementOverlapRuleVersion;
  "person_master.engagement_type": PersonMasterEngagementType;
  "person_master.engagement_type_version": PersonMasterEngagementTypeVersion;
  "person_master.engagement_version": PersonMasterEngagementVersion;
  "person_master.person_identifier": PersonMasterPersonIdentifier;
  "person_master.person_identifier_version": PersonMasterPersonIdentifierVersion;
  "person_master.person_source_mapping": PersonMasterPersonSourceMapping;
  "person_master.person_source_mapping_version": PersonMasterPersonSourceMappingVersion;
  "person_master.person_subject": PersonMasterPersonSubject;
  "person_master.person_subject_version": PersonMasterPersonSubjectVersion;
  "platform.browser_session": PlatformBrowserSession;
  "platform.campus": PlatformCampus;
  "platform.external_identity_binding": PlatformExternalIdentityBinding;
  "platform.governance_object": PlatformGovernanceObject;
  "platform.oidc_login_transaction": PlatformOidcLoginTransaction;
  "platform.schema_migration": PlatformSchemaMigration;
  "platform.security_principal": PlatformSecurityPrincipal;
  "price_list.price_entry": PriceListPriceEntry;
  "price_list.price_entry_charge_item_target": PriceListPriceEntryChargeItemTarget;
  "price_list.price_list": PriceListPriceList;
  "price_list.price_list_release": PriceListPriceListRelease;
  "price_resolution.price_resolution": PriceResolutionPriceResolution;
  "price_resolution.price_resolution_charge_item_target": PriceResolutionPriceResolutionChargeItemTarget;
  "price_resolution.price_resolution_result": PriceResolutionPriceResolutionResult;
  "price_resolution.price_resolution_step": PriceResolutionPriceResolutionStep;
  "release_distribution.consumer_checkpoint": ReleaseDistributionConsumerCheckpoint;
  "release_distribution.consumer_compatibility_issue": ReleaseDistributionConsumerCompatibilityIssue;
  "release_distribution.consumer_compatibility_issue_event": ReleaseDistributionConsumerCompatibilityIssueEvent;
  "release_distribution.consumer_projection_support": ReleaseDistributionConsumerProjectionSupport;
  "release_distribution.consumer_receipt": ReleaseDistributionConsumerReceipt;
  "release_distribution.consumer_subscription": ReleaseDistributionConsumerSubscription;
  "release_distribution.consumer_subscription_version": ReleaseDistributionConsumerSubscriptionVersion;
  "release_distribution.delivery_operational_issue": ReleaseDistributionDeliveryOperationalIssue;
  "release_distribution.delivery_operational_issue_event": ReleaseDistributionDeliveryOperationalIssueEvent;
  "release_distribution.governance_release": ReleaseDistributionGovernanceRelease;
  "release_distribution.outbox_delivery": ReleaseDistributionOutboxDelivery;
  "release_distribution.outbox_delivery_attempt": ReleaseDistributionOutboxDeliveryAttempt;
  "release_distribution.outbox_delivery_state": ReleaseDistributionOutboxDeliveryState;
  "release_distribution.outbox_event": ReleaseDistributionOutboxEvent;
  "release_distribution.release_consumer_compatibility": ReleaseDistributionReleaseConsumerCompatibility;
  "release_distribution.release_member_charge_item": ReleaseDistributionReleaseMemberChargeItem;
  "release_distribution.release_member_department": ReleaseDistributionReleaseMemberDepartment;
  "release_distribution.release_member_department_hierarchy": ReleaseDistributionReleaseMemberDepartmentHierarchy;
  "release_distribution.release_member_price_list": ReleaseDistributionReleaseMemberPriceList;
  "release_distribution.release_relationship": ReleaseDistributionReleaseRelationship;
  "release_distribution.release_snapshot": ReleaseDistributionReleaseSnapshot;
  "workflow.approval_action": WorkflowApprovalAction;
  "workflow.approval_template": WorkflowApprovalTemplate;
  "workflow.approval_template_stage": WorkflowApprovalTemplateStage;
  "workflow.approval_template_version": WorkflowApprovalTemplateVersion;
  "workflow.change_request": WorkflowChangeRequest;
}
