/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface GovernanceCatalogEvent {
  actor_code: string;
  head: Generated<Int8>;
  object_id: string;
  reason: string;
  recorded_at: Generated<string>;
  status: string;
  version_id: string;
}

export interface GovernanceCatalogObject {
  code: string;
  id: Generated<string>;
  kind: string;
  scope: string;
}

export interface GovernanceCatalogSourceSnapshot {
  content: Json;
  id: Generated<string>;
  recorded_at: Generated<string>;
  sha256: string;
  source_key: string;
}

export interface GovernanceCatalogVersion {
  id: Generated<string>;
  maker_identity: string;
  number: number;
  object_id: string;
  payload: Json;
  recorded_at: Generated<string>;
  valid_from: string;
  valid_to: string | null;
}

export interface VnextControlActor {
  active: boolean;
  code: string;
  identity_code: string;
}

export interface VnextControlActorGrant {
  actor_code: string;
  permission: string;
  scope: string;
}

export interface VnextControlAudit {
  action: string;
  actor_code: string;
  content_digest: string;
  id: Generated<string>;
  object_id: string;
  reason: string;
  recorded_at: Generated<string>;
}

export interface VnextControlMigration {
  applied_at: Generated<string>;
  id: string;
  lineage: string;
  runner_version: string;
  sha256: string;
}

export interface VnextControlOutcome {
  actor_code: string;
  input_digest: string;
  recorded_at: Generated<string>;
  request_id: string;
  result: Json;
}

export interface VnextControlRequestIdentity {
  identity_code: string;
  original_actor_code: string;
  request_id: string;
}

export interface DB {
  "governance_catalog.event": GovernanceCatalogEvent;
  "governance_catalog.object": GovernanceCatalogObject;
  "governance_catalog.source_snapshot": GovernanceCatalogSourceSnapshot;
  "governance_catalog.version": GovernanceCatalogVersion;
  "vnext_control.actor": VnextControlActor;
  "vnext_control.actor_grant": VnextControlActorGrant;
  "vnext_control.audit": VnextControlAudit;
  "vnext_control.migration": VnextControlMigration;
  "vnext_control.outcome": VnextControlOutcome;
  "vnext_control.request_identity": VnextControlRequestIdentity;
}
