/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface DepartmentMasterAccess {
  actor: string;
  permission: string;
  scope: string;
}

export interface DepartmentMasterDepartment {
  code: string;
  id: Generated<string>;
}

export interface DepartmentMasterHierarchyCandidate {
  applied_at: string | null;
  approved_at: string | null;
  approved_by: string | null;
  approved_identity: string | null;
  digest: string;
  envelope: Json;
  id: Generated<string>;
  maker: string;
  maker_identity: string;
  payload: Json;
  payload_digest: string;
  recorded_at: Generated<string>;
  request_id: string;
  source_client_key: string;
  status: string;
  view_id: string | null;
}

export interface DepartmentMasterHierarchyClosure {
  candidate_id: string;
  id: Generated<string>;
  reason: string;
  recorded_at: Generated<string>;
  status: string;
  version_no: Int8;
  view_id: string;
}

export interface DepartmentMasterHierarchyGrant {
  actor_code: string;
  object_id: string;
  permission: string;
}

export interface DepartmentMasterHierarchyNode {
  department_id: string | null;
  department_version_id: string | null;
  depth: number;
  display_name: string;
  group_code: string | null;
  group_id: string | null;
  group_version_id: string | null;
  is_primary_path: boolean;
  node_id: Generated<string>;
  node_key: string;
  node_kind: string;
  parent_node_key: string | null;
  relation_name: string;
  sort_order: number;
  source_definition_version_id: string | null;
  source_evidence: Json | null;
  view_version_id: string;
}

export interface DepartmentMasterHierarchyView {
  created_at: Generated<string>;
  id: Generated<string>;
  registration_payload: Json | null;
  registration_request_id: string | null;
  source_client_key: string;
  view_code: string;
}

export interface DepartmentMasterHierarchyViewVersion {
  aggregation_rule: string;
  approval_ref: string;
  approved_by: string | null;
  approved_identity: string | null;
  content_digest: string;
  created_at: Generated<string>;
  id: Generated<string>;
  maker: string;
  maker_identity: string;
  owner_department_id: string | null;
  owner_department_version_id: string | null;
  parent_cardinality: string;
  purpose: string;
  recorded_at: string;
  source_definition_version_id: string | null;
  source_record_id: string;
  source_record_status: string | null;
  source_system_id: string;
  source_version: string;
  status: string;
  valid_from: string;
  valid_to: string | null;
  version_no: Int8;
  view_code: string;
  view_id: string;
  view_name: string;
  view_type: string;
}

export interface DepartmentMasterInput {
  campus: string;
  digest: string;
  envelope: Json;
  id: Generated<string>;
  identity_code: string;
  job_id: string;
  job_revision: string;
  maker: string;
  recorded_at: Generated<string>;
  request_id: string;
  revision: Generated<string>;
}

export interface DepartmentMasterMappingAccess {
  actor: string;
  campus: string;
  context: string;
  entity_type: string;
  from_system_id: string;
  permission: string;
}

export interface DepartmentMasterMappingInput {
  campus: string;
  digest: string;
  envelope: Json;
  id: Generated<string>;
  identity_code: string;
  job_id: string;
  job_revision: string;
  maker: string;
  namespaces: Json;
  recorded_at: Generated<string>;
  request_id: string;
  revision: Generated<string>;
}

export interface DepartmentMasterMappingTargetAccess {
  actor: string;
  campus: string;
  target_id: string;
  target_type: string;
}

export interface DepartmentMasterMappingVerification {
  actor: string;
  digest: string;
  envelope: Json;
  id: Generated<string>;
  identity_code: string;
  input_id: string;
  number: Int8;
  recorded_at: Generated<string>;
  request_id: string;
}

export interface DepartmentMasterOrganizationMapping {
  campus: string;
  context: string;
  entity_type: string;
  from_system_id: string;
  id: Generated<string>;
  source_code: string;
}

export interface DepartmentMasterOrganizationMappingVersion {
  action: string;
  content_digest: string;
  facts: Json;
  id: Generated<string>;
  input_id: string;
  mapping_id: string;
  number: Int8;
  predecessor: string | null;
  reason: string;
  recorded_at: Generated<string>;
  source_row: number;
  target_id: string;
  target_type: string;
  valid_from: string;
  valid_to: string | null;
}

export interface DepartmentMasterVerification {
  actor: string;
  digest: string;
  envelope: Json;
  id: Generated<string>;
  identity_code: string;
  input_id: string;
  number: Int8;
  recorded_at: Generated<string>;
  request_id: string;
}

export interface DepartmentMasterVersion {
  content_digest: string;
  department_id: string;
  facts: Json;
  id: Generated<string>;
  input_id: string;
  number: Int8;
  recorded_at: Generated<string>;
  source_row: number;
  valid_from: string;
  valid_to: string | null;
}

export interface GovernanceCatalogApplyApproval {
  actor_code: string;
  candidate_id: string;
  digest: string;
  identity_code: string;
  recorded_at: Generated<string>;
  review_audit_id: string | null;
}

export interface GovernanceCatalogApplyCandidate {
  digest: string;
  envelope: Json;
  id: Generated<string>;
  input: Json;
  maker: string;
  maker_identity: string;
  recorded_at: Generated<string>;
}

export interface GovernanceCatalogApplyCommit {
  actor_code: string;
  candidate_id: string;
  identity_code: string;
  request_id: string;
}

export interface GovernanceCatalogContractImpactEvent {
  assessment_head: Int8;
  case_id: Generated<string>;
  contract_id: string;
  contract_version: string;
  event_sequence: number;
  evidence: Json;
  obligation_spans: string;
  recorded_at: Generated<string>;
  resolution_contract_event: Int8 | null;
  resolution_source_event: Int8 | null;
  upstream_event: Int8;
  upstream_object: string;
}

export interface GovernanceCatalogEvent {
  actor_code: string;
  head: Generated<Int8>;
  object_id: string;
  reason: string;
  recorded_at: Generated<string>;
  status: string;
  version_id: string;
}

export interface GovernanceCatalogImpactEvent {
  actor_code: string;
  assessment_head: Int8 | null;
  case_id: string;
  downstream_object: string;
  downstream_version: string;
  event_sequence: Int8;
  reason: string;
  recorded_at: Generated<string>;
  resolution_event: Int8 | null;
  status: string;
  upstream_event: Int8;
  upstream_object: string;
}

export interface GovernanceCatalogImportContract {
  bundle_org: Generated<boolean>;
  dataset_id: string;
  id: Generated<string>;
  manual_org03: Generated<boolean>;
  profile: string;
}

export interface GovernanceCatalogImportContractEvent {
  actor_code: string;
  approval_context: Json | null;
  contract_id: string;
  head: Generated<Int8>;
  recorded_at: Generated<string>;
  status: string;
  stream_sequence: Int8;
  version_id: string;
}

export interface GovernanceCatalogImportContractVersion {
  contract_id: string;
  dataset_version_id: string;
  definition: Json;
  id: Generated<string>;
  maker_identity: string;
  number: number;
  recorded_at: Generated<string>;
  schemas: Json;
  semantics_digest: string;
  source_snapshot_id: string;
  valid_from: string;
  valid_to: string | null;
}

export interface GovernanceCatalogImportInputRevision {
  digest_status: Generated<string>;
  id: Generated<string>;
  job_id: string;
  metadata: Json;
  metadata_digest: string;
  number: Int8;
  previous_revision_id: string | null;
  recorded_at: Generated<string>;
  request_id: string;
  request_identity: string;
}

export interface GovernanceCatalogImportJob {
  contract_id: string;
  contract_snapshot: Json;
  contract_version_id: string;
  current_revision_id: string;
  id: Generated<string>;
  profile: string;
  quality_disposition_sequence: Generated<Int8>;
  quality_issue_sequence: Generated<Int8>;
  scope: string;
  status: Generated<string>;
  submitter_identity: string;
}

export interface GovernanceCatalogIssueDisposition {
  actor_identity: string;
  disposition_no: Int8;
  id: Generated<string>;
  issue_id: string | null;
  job_id: string;
  kind: string;
  owner_ref: Generated<string>;
  payload: Generated<Json>;
  reason: string;
  recorded_at: Generated<string>;
  request_id: string;
  target_revision_id: string | null;
  target_row: number | null;
  target_run_id: string | null;
}

export interface GovernanceCatalogObject {
  code: string;
  id: Generated<string>;
  kind: string;
  scope: string;
}

export interface GovernanceCatalogParameter {
  id: Generated<string>;
  parameter_key: string;
  system_object_id: string;
}

export interface GovernanceCatalogParameterApproval {
  actor_code: string;
  definition_digest: string;
  id: Generated<string>;
  recorded_at: Generated<string>;
  reviewer_identity: string;
  version_id: string;
}

export interface GovernanceCatalogParameterGrant {
  actor_code: string;
  parameter_id: string;
  permission: string;
}

export interface GovernanceCatalogParameterVersion {
  campus: string;
  definition: Json;
  definition_digest: string;
  id: Generated<string>;
  maker_identity: string;
  number: number;
  owner_role: string;
  parameter_group: string;
  parameter_id: string;
  purpose: string;
  recorded_at: Generated<string>;
  system_version_id: string;
  valid_from: string;
  valid_to: string | null;
}

export interface GovernanceCatalogParseProvenance {
  artifact_id: string;
  contract_version_id: string;
  job_id: string;
  policy: string;
  recorded_at: Generated<string>;
  revision_id: string;
  signature: string;
  source_artifact_id: string;
  structural_status: string;
}

export interface GovernanceCatalogProtectedArtifact {
  campus: string;
  expires_at: string;
  id: Generated<string>;
  job_id: string;
  kind: string;
  purpose: string;
  recorded_at: Generated<string>;
  request_id: string;
  revision_id: string;
  status: Generated<string>;
}

export interface GovernanceCatalogProtectedPayload {
  artifact_id: string;
  ciphertext: Buffer;
  key_id: string;
  nonce: Buffer;
  tag: Buffer;
}

export interface GovernanceCatalogQualityIssue {
  bounded_code: string;
  campus: string;
  classification: string;
  dataset_code: string;
  field_code: Generated<string>;
  id: Generated<string>;
  issue_sequence: Int8;
  job_id: string;
  layer: number;
  owner_ref: Generated<string>;
  purpose: string;
  recorded_at: Generated<string>;
  related_refs: Generated<Json>;
  requirement_id: Generated<string>;
  revision_id: string;
  row_number: number;
  rule_code: string;
  run_id: string;
  sheet_name: string | null;
  source_format: string;
  source_kind: string;
  source_status: string;
}

export interface GovernanceCatalogSourceAssessment {
  action: string;
  content: Json;
  digest: string;
  event_head: Int8;
  object_id: string;
  reason: string;
  recorded_at: Generated<string>;
  request_id: string;
  reviewer_actor: string;
  reviewer_identity: string;
}

export interface GovernanceCatalogSourceSnapshot {
  content: Json;
  id: Generated<string>;
  recorded_at: Generated<string>;
  sha256: string;
  source_key: string;
}

export interface GovernanceCatalogValidationRun {
  contract_version_id: string;
  decision: string;
  id: Generated<string>;
  interpretation_policy: string;
  issue_count: number;
  job_id: string;
  parse_artifact_id: string;
  quality_candidate_digest: string | null;
  quality_eligibility_digest: string | null;
  quality_resolution_digest: string | null;
  recorded_at: Generated<string>;
  request_id: string;
  request_identity: string;
  result_artifact_id: string;
  revision_id: string;
  rule_version: string;
  signature: string;
}

export interface GovernanceCatalogVersion {
  id: Generated<string>;
  maker_identity: string;
  number: number;
  object_id: string;
  payload: Json;
  recorded_at: Generated<string>;
  valid_from: string;
  valid_to: string | null;
}

export interface OrganizationMasterAccess {
  actor: string;
  campus: string;
  permission: string;
  subject_id: string;
}

export interface OrganizationMasterBundleAdministrator {
  actor: string;
}

export interface OrganizationMasterBundleChild {
  candidate_id: string;
  command_digest: string;
  input_id: string;
  legal_review_id: string;
  step_key: string;
}

export interface OrganizationMasterBundleControlEvent {
  actor: string;
  details: Json;
  digest: string;
  id: Generated<string>;
  identity_code: string;
  job_id: string;
  kind: string;
  recorded_at: Generated<string>;
  revision_id: string;
  sequence: Generated<Int8>;
}

export interface OrganizationMasterBundleRevision {
  bindings: Json;
  campus: string;
  contracts_digest: string;
  dimensions: Json;
  job_id: string;
  manifest_digest: string;
  manifest_id: string;
  raw_id: string;
  recorded_at: Generated<string>;
  revision_id: string;
  scopes: Json;
}

export interface OrganizationMasterCampus {
  id: Generated<string>;
  scope: string;
}

export interface OrganizationMasterCampusCode {
  campus_id: string;
  code: string;
}

export interface OrganizationMasterCampusEvent {
  action: string;
  campus_id: string;
  id: Generated<string>;
  input_id: string;
  lifecycle: Json | null;
  number: Int8;
  recorded_at: Generated<string>;
  valid_from: string;
  valid_to: string | null;
}

export interface OrganizationMasterCampusOperation {
  event_id: string;
  state: string;
}

export interface OrganizationMasterCampusPlan {
  event_id: string;
  planned_opening_at: string | null;
}

export interface OrganizationMasterCampusVersion {
  event_id: string;
  facts: Json;
}

export interface OrganizationMasterIdentifier {
  input_id: string;
  kind: string;
  lookup_digest: string;
  namespace: string;
  subject_id: string;
}

export interface OrganizationMasterInput {
  campus: string;
  digest: string;
  domain: Generated<string>;
  envelope: Json;
  id: Generated<string>;
  identity_code: string;
  job_id: string;
  job_revision: string;
  maker: string;
  recorded_at: Generated<string>;
  request_id: string;
  revision: Generated<string>;
  target: string | null;
}

export interface OrganizationMasterInputRequest {
  input_id: string;
  request_id: string;
}

export interface OrganizationMasterLicense {
  id: Generated<string>;
  subject_id: string;
}

export interface OrganizationMasterLicenseVersion {
  authority: string;
  end_kind: string;
  evidence: string;
  id: Generated<string>;
  input_id: string;
  license_id: string;
  number: Int8;
  recorded_at: Generated<string>;
  revoked: Generated<boolean>;
  valid_from: string;
  valid_to: string | null;
}

export interface OrganizationMasterOperatingAccess {
  actor: string;
  campus_id: string;
  permission: string;
  subject_id: string;
}

export interface OrganizationMasterOperatingInput {
  action: string;
  campus_id: string;
  input_id: string;
  kind: string;
  subject_id: string;
}

export interface OrganizationMasterOperatingObject {
  campus_id: string;
  id: Generated<string>;
  kind: string;
  scope: string;
  subject_id: string;
}

export interface OrganizationMasterOperatingVersion {
  action: string;
  basis: Json;
  facts: Json | null;
  id: Generated<string>;
  input_id: string;
  number: Int8;
  object_id: string;
  recorded_at: Generated<string>;
  reviewer: string;
  valid_from: string;
  valid_to: string | null;
}

export interface OrganizationMasterSubject {
  campus: string;
  id: Generated<string>;
}

export interface OrganizationMasterVerification {
  evidence: string;
  id: Generated<string>;
  input_id: string;
  licenses: string[];
  recorded_at: Generated<string>;
  subject_id: string;
  subject_version: string;
  valid_from: string;
  valid_to: string | null;
}

export interface OrganizationMasterVersion {
  authority: string | null;
  entity_nature: string;
  id: Generated<string>;
  identifier_keys: Generated<Json>;
  input_id: string;
  legal_address: string | null;
  legal_name: string;
  number: Int8;
  recorded_at: Generated<string>;
  registration_evidence: string;
  subject_id: string;
  valid_from: string;
  valid_to: string | null;
}

export interface OrganizationMasterWithdrawal {
  actor: string;
  input_id: string;
  recorded_at: Generated<string>;
  request_id: string;
}

export interface OrganizationMasterWorkspaceDraftRevision {
  digest: string;
  envelope: Json;
  id: string;
  identity_code: string;
  maker: string;
  metadata: Json;
  number: Int8;
  recorded_at: Generated<string>;
  request_id: string;
  state: string;
  submission: Json | null;
}

export interface VnextControlActor {
  active: boolean;
  code: string;
  identity_code: string;
}

export interface VnextControlActorGrant {
  actor_code: string;
  permission: string;
  scope: string;
}

export interface VnextControlAudit {
  action: string;
  actor_code: string;
  content_digest: string;
  id: Generated<string>;
  object_id: string;
  reason: string;
  recorded_at: Generated<string>;
}

export interface VnextControlAuditChain {
  audit_id: string | null;
  audit_sequence: Int8;
  audit_stream_id: string;
  canonical_payload: Json;
  current_hash: string;
  kind: string;
  previous_hash: string;
}

export interface VnextControlAuditStreamGrant {
  actor_code: string;
  purpose: string;
  stream_id: string;
}

export interface VnextControlBundleWriteAuthority {
  key_hex: string;
  singleton: Generated<boolean>;
}

export interface VnextControlCampusWriteAuthority {
  key_hex: string;
  singleton: Generated<boolean>;
}

export interface VnextControlCreationPolicy {
  campus: string;
  creator_actor: string;
  field_group: string;
  object_kind: string;
  permission: string;
  purpose: string;
  recipient_actor: string;
}

export interface VnextControlDepartmentWriteAuthority {
  key_hex: string;
  singleton: Generated<boolean>;
}

export interface VnextControlMigration {
  applied_at: Generated<string>;
  id: string;
  lineage: string;
  runner_version: string;
  sha256: string;
}

export interface VnextControlObjectGrant {
  actor_code: string;
  campus: string;
  field_group: string;
  object_id: string;
  object_kind: string;
  permission: string;
  purpose: string;
  scope: string;
}

export interface VnextControlOperatingWriteAuthority {
  key_hex: string;
  singleton: Generated<boolean>;
}

export interface VnextControlOrganizationKeyBinding {
  lookup_fingerprint: string;
  payload_fingerprint: string;
  singleton: Generated<boolean>;
}

export interface VnextControlOutcome {
  actor_code: string;
  input_digest: string;
  recorded_at: Generated<string>;
  request_id: string;
  result: Json;
}

export interface VnextControlProtectedGrant {
  actor_code: string;
  campus: string;
  dataset_id: string;
  permission: string;
  purpose: string;
}

export interface VnextControlRequestIdentity {
  identity_code: string;
  original_actor_code: string;
  request_id: string;
}

export interface DB {
  "department_master.access": DepartmentMasterAccess;
  "department_master.department": DepartmentMasterDepartment;
  "department_master.hierarchy_candidate": DepartmentMasterHierarchyCandidate;
  "department_master.hierarchy_closure": DepartmentMasterHierarchyClosure;
  "department_master.hierarchy_grant": DepartmentMasterHierarchyGrant;
  "department_master.hierarchy_node": DepartmentMasterHierarchyNode;
  "department_master.hierarchy_view": DepartmentMasterHierarchyView;
  "department_master.hierarchy_view_version": DepartmentMasterHierarchyViewVersion;
  "department_master.input": DepartmentMasterInput;
  "department_master.mapping_access": DepartmentMasterMappingAccess;
  "department_master.mapping_input": DepartmentMasterMappingInput;
  "department_master.mapping_target_access": DepartmentMasterMappingTargetAccess;
  "department_master.mapping_verification": DepartmentMasterMappingVerification;
  "department_master.organization_mapping": DepartmentMasterOrganizationMapping;
  "department_master.organization_mapping_version": DepartmentMasterOrganizationMappingVersion;
  "department_master.verification": DepartmentMasterVerification;
  "department_master.version": DepartmentMasterVersion;
  "governance_catalog.apply_approval": GovernanceCatalogApplyApproval;
  "governance_catalog.apply_candidate": GovernanceCatalogApplyCandidate;
  "governance_catalog.apply_commit": GovernanceCatalogApplyCommit;
  "governance_catalog.contract_impact_event": GovernanceCatalogContractImpactEvent;
  "governance_catalog.event": GovernanceCatalogEvent;
  "governance_catalog.impact_event": GovernanceCatalogImpactEvent;
  "governance_catalog.import_contract": GovernanceCatalogImportContract;
  "governance_catalog.import_contract_event": GovernanceCatalogImportContractEvent;
  "governance_catalog.import_contract_version": GovernanceCatalogImportContractVersion;
  "governance_catalog.import_input_revision": GovernanceCatalogImportInputRevision;
  "governance_catalog.import_job": GovernanceCatalogImportJob;
  "governance_catalog.issue_disposition": GovernanceCatalogIssueDisposition;
  "governance_catalog.object": GovernanceCatalogObject;
  "governance_catalog.parameter": GovernanceCatalogParameter;
  "governance_catalog.parameter_approval": GovernanceCatalogParameterApproval;
  "governance_catalog.parameter_grant": GovernanceCatalogParameterGrant;
  "governance_catalog.parameter_version": GovernanceCatalogParameterVersion;
  "governance_catalog.parse_provenance": GovernanceCatalogParseProvenance;
  "governance_catalog.protected_artifact": GovernanceCatalogProtectedArtifact;
  "governance_catalog.protected_payload": GovernanceCatalogProtectedPayload;
  "governance_catalog.quality_issue": GovernanceCatalogQualityIssue;
  "governance_catalog.source_assessment": GovernanceCatalogSourceAssessment;
  "governance_catalog.source_snapshot": GovernanceCatalogSourceSnapshot;
  "governance_catalog.validation_run": GovernanceCatalogValidationRun;
  "governance_catalog.version": GovernanceCatalogVersion;
  "organization_master.access": OrganizationMasterAccess;
  "organization_master.bundle_administrator": OrganizationMasterBundleAdministrator;
  "organization_master.bundle_child": OrganizationMasterBundleChild;
  "organization_master.bundle_control_event": OrganizationMasterBundleControlEvent;
  "organization_master.bundle_revision": OrganizationMasterBundleRevision;
  "organization_master.campus": OrganizationMasterCampus;
  "organization_master.campus_code": OrganizationMasterCampusCode;
  "organization_master.campus_event": OrganizationMasterCampusEvent;
  "organization_master.campus_operation": OrganizationMasterCampusOperation;
  "organization_master.campus_plan": OrganizationMasterCampusPlan;
  "organization_master.campus_version": OrganizationMasterCampusVersion;
  "organization_master.identifier": OrganizationMasterIdentifier;
  "organization_master.input": OrganizationMasterInput;
  "organization_master.input_request": OrganizationMasterInputRequest;
  "organization_master.license": OrganizationMasterLicense;
  "organization_master.license_version": OrganizationMasterLicenseVersion;
  "organization_master.operating_access": OrganizationMasterOperatingAccess;
  "organization_master.operating_input": OrganizationMasterOperatingInput;
  "organization_master.operating_object": OrganizationMasterOperatingObject;
  "organization_master.operating_version": OrganizationMasterOperatingVersion;
  "organization_master.subject": OrganizationMasterSubject;
  "organization_master.verification": OrganizationMasterVerification;
  "organization_master.version": OrganizationMasterVersion;
  "organization_master.withdrawal": OrganizationMasterWithdrawal;
  "organization_master.workspace_draft_revision": OrganizationMasterWorkspaceDraftRevision;
  "vnext_control.actor": VnextControlActor;
  "vnext_control.actor_grant": VnextControlActorGrant;
  "vnext_control.audit": VnextControlAudit;
  "vnext_control.audit_chain": VnextControlAuditChain;
  "vnext_control.audit_stream_grant": VnextControlAuditStreamGrant;
  "vnext_control.bundle_write_authority": VnextControlBundleWriteAuthority;
  "vnext_control.campus_write_authority": VnextControlCampusWriteAuthority;
  "vnext_control.creation_policy": VnextControlCreationPolicy;
  "vnext_control.department_write_authority": VnextControlDepartmentWriteAuthority;
  "vnext_control.migration": VnextControlMigration;
  "vnext_control.object_grant": VnextControlObjectGrant;
  "vnext_control.operating_write_authority": VnextControlOperatingWriteAuthority;
  "vnext_control.organization_key_binding": VnextControlOrganizationKeyBinding;
  "vnext_control.outcome": VnextControlOutcome;
  "vnext_control.protected_grant": VnextControlProtectedGrant;
  "vnext_control.request_identity": VnextControlRequestIdentity;
}
