/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface GovernanceCatalogContractImpactEvent {
  assessment_head: Int8;
  case_id: Generated<string>;
  contract_id: string;
  contract_version: string;
  event_sequence: number;
  evidence: Json;
  obligation_spans: string;
  recorded_at: Generated<string>;
  resolution_contract_event: Int8 | null;
  resolution_source_event: Int8 | null;
  upstream_event: Int8;
  upstream_object: string;
}

export interface GovernanceCatalogEvent {
  actor_code: string;
  head: Generated<Int8>;
  object_id: string;
  reason: string;
  recorded_at: Generated<string>;
  status: string;
  version_id: string;
}

export interface GovernanceCatalogImpactEvent {
  actor_code: string;
  assessment_head: Int8 | null;
  case_id: string;
  downstream_object: string;
  downstream_version: string;
  event_sequence: Int8;
  reason: string;
  recorded_at: Generated<string>;
  resolution_event: Int8 | null;
  status: string;
  upstream_event: Int8;
  upstream_object: string;
}

export interface GovernanceCatalogImportContract {
  dataset_id: string;
  id: Generated<string>;
  profile: string;
}

export interface GovernanceCatalogImportContractEvent {
  actor_code: string;
  approval_context: Json | null;
  contract_id: string;
  head: Generated<Int8>;
  recorded_at: Generated<string>;
  status: string;
  stream_sequence: Int8;
  version_id: string;
}

export interface GovernanceCatalogImportContractVersion {
  contract_id: string;
  dataset_version_id: string;
  definition: Json;
  id: Generated<string>;
  maker_identity: string;
  number: number;
  recorded_at: Generated<string>;
  schemas: Json;
  semantics_digest: string;
  source_snapshot_id: string;
  valid_from: string;
  valid_to: string | null;
}

export interface GovernanceCatalogImportInputRevision {
  digest_status: Generated<string>;
  id: Generated<string>;
  job_id: string;
  metadata: Json;
  metadata_digest: string;
  number: Int8;
  previous_revision_id: string | null;
  recorded_at: Generated<string>;
  request_id: string;
  request_identity: string;
}

export interface GovernanceCatalogImportJob {
  contract_id: string;
  contract_snapshot: Json;
  contract_version_id: string;
  current_revision_id: string;
  id: Generated<string>;
  profile: string;
  scope: string;
  status: Generated<string>;
  submitter_identity: string;
}

export interface GovernanceCatalogObject {
  code: string;
  id: Generated<string>;
  kind: string;
  scope: string;
}

export interface GovernanceCatalogParameter {
  id: Generated<string>;
  parameter_key: string;
  system_object_id: string;
}

export interface GovernanceCatalogParameterApproval {
  actor_code: string;
  definition_digest: string;
  id: Generated<string>;
  recorded_at: Generated<string>;
  reviewer_identity: string;
  version_id: string;
}

export interface GovernanceCatalogParameterGrant {
  actor_code: string;
  parameter_id: string;
  permission: string;
}

export interface GovernanceCatalogParameterVersion {
  campus: string;
  definition: Json;
  definition_digest: string;
  id: Generated<string>;
  maker_identity: string;
  number: number;
  owner_role: string;
  parameter_group: string;
  parameter_id: string;
  purpose: string;
  recorded_at: Generated<string>;
  system_version_id: string;
  valid_from: string;
  valid_to: string | null;
}

export interface GovernanceCatalogProtectedArtifact {
  campus: string;
  expires_at: string;
  id: Generated<string>;
  job_id: string;
  kind: string;
  purpose: string;
  recorded_at: Generated<string>;
  request_id: string;
  revision_id: string;
  status: Generated<string>;
}

export interface GovernanceCatalogProtectedPayload {
  artifact_id: string;
  ciphertext: Buffer;
  key_id: string;
  nonce: Buffer;
  tag: Buffer;
}

export interface GovernanceCatalogSourceAssessment {
  action: string;
  content: Json;
  digest: string;
  event_head: Int8;
  object_id: string;
  reason: string;
  recorded_at: Generated<string>;
  request_id: string;
  reviewer_actor: string;
  reviewer_identity: string;
}

export interface GovernanceCatalogSourceSnapshot {
  content: Json;
  id: Generated<string>;
  recorded_at: Generated<string>;
  sha256: string;
  source_key: string;
}

export interface GovernanceCatalogVersion {
  id: Generated<string>;
  maker_identity: string;
  number: number;
  object_id: string;
  payload: Json;
  recorded_at: Generated<string>;
  valid_from: string;
  valid_to: string | null;
}

export interface VnextControlActor {
  active: boolean;
  code: string;
  identity_code: string;
}

export interface VnextControlActorGrant {
  actor_code: string;
  permission: string;
  scope: string;
}

export interface VnextControlAudit {
  action: string;
  actor_code: string;
  content_digest: string;
  id: Generated<string>;
  object_id: string;
  reason: string;
  recorded_at: Generated<string>;
}

export interface VnextControlAuditChain {
  audit_id: string | null;
  audit_sequence: Int8;
  audit_stream_id: string;
  canonical_payload: Json;
  current_hash: string;
  kind: string;
  previous_hash: string;
}

export interface VnextControlAuditStreamGrant {
  actor_code: string;
  purpose: string;
  stream_id: string;
}

export interface VnextControlCreationPolicy {
  campus: string;
  creator_actor: string;
  field_group: string;
  object_kind: string;
  permission: string;
  purpose: string;
  recipient_actor: string;
}

export interface VnextControlMigration {
  applied_at: Generated<string>;
  id: string;
  lineage: string;
  runner_version: string;
  sha256: string;
}

export interface VnextControlObjectGrant {
  actor_code: string;
  campus: string;
  field_group: string;
  object_id: string;
  object_kind: string;
  permission: string;
  purpose: string;
  scope: string;
}

export interface VnextControlOutcome {
  actor_code: string;
  input_digest: string;
  recorded_at: Generated<string>;
  request_id: string;
  result: Json;
}

export interface VnextControlProtectedGrant {
  actor_code: string;
  campus: string;
  dataset_id: string;
  permission: string;
  purpose: string;
}

export interface VnextControlRequestIdentity {
  identity_code: string;
  original_actor_code: string;
  request_id: string;
}

export interface DB {
  "governance_catalog.contract_impact_event": GovernanceCatalogContractImpactEvent;
  "governance_catalog.event": GovernanceCatalogEvent;
  "governance_catalog.impact_event": GovernanceCatalogImpactEvent;
  "governance_catalog.import_contract": GovernanceCatalogImportContract;
  "governance_catalog.import_contract_event": GovernanceCatalogImportContractEvent;
  "governance_catalog.import_contract_version": GovernanceCatalogImportContractVersion;
  "governance_catalog.import_input_revision": GovernanceCatalogImportInputRevision;
  "governance_catalog.import_job": GovernanceCatalogImportJob;
  "governance_catalog.object": GovernanceCatalogObject;
  "governance_catalog.parameter": GovernanceCatalogParameter;
  "governance_catalog.parameter_approval": GovernanceCatalogParameterApproval;
  "governance_catalog.parameter_grant": GovernanceCatalogParameterGrant;
  "governance_catalog.parameter_version": GovernanceCatalogParameterVersion;
  "governance_catalog.protected_artifact": GovernanceCatalogProtectedArtifact;
  "governance_catalog.protected_payload": GovernanceCatalogProtectedPayload;
  "governance_catalog.source_assessment": GovernanceCatalogSourceAssessment;
  "governance_catalog.source_snapshot": GovernanceCatalogSourceSnapshot;
  "governance_catalog.version": GovernanceCatalogVersion;
  "vnext_control.actor": VnextControlActor;
  "vnext_control.actor_grant": VnextControlActorGrant;
  "vnext_control.audit": VnextControlAudit;
  "vnext_control.audit_chain": VnextControlAuditChain;
  "vnext_control.audit_stream_grant": VnextControlAuditStreamGrant;
  "vnext_control.creation_policy": VnextControlCreationPolicy;
  "vnext_control.migration": VnextControlMigration;
  "vnext_control.object_grant": VnextControlObjectGrant;
  "vnext_control.outcome": VnextControlOutcome;
  "vnext_control.protected_grant": VnextControlProtectedGrant;
  "vnext_control.request_identity": VnextControlRequestIdentity;
}
