import {
  DepartmentContractError,
  type DepartmentErrorCode,
} from '../../modules/department-master/index.js';

export interface HttpErrorMapping {
  readonly statusCode: 400 | 401 | 403 | 404 | 409 | 500 | 503;
  readonly code: string;
}

const departmentErrorStatus = {
  DEPARTMENT_NOT_FOUND: 404,
  DEPARTMENT_VERSION_NOT_FOUND: 404,
  DEPARTMENT_PERMISSION_DENIED: 403,
  DEPARTMENT_STATUS_INVALID: 409,
  DEPARTMENT_APPROVAL_REQUIRED: 409,
  DEPARTMENT_CONTENT_CHANGED: 409,
  DEPARTMENT_EVOLUTION_RELATION_REQUIRED: 409,
} as const satisfies Readonly<Record<DepartmentErrorCode, HttpErrorMapping['statusCode']>>;

const publicErrorStatus: Readonly<Record<string, HttpErrorMapping['statusCode']>> = {
  PHASE_01_RUNTIME_NOT_CONFIGURED: 503,
  AUTHENTICATION_RUNTIME_NOT_CONFIGURED: 503,
  DEPARTMENT_RUNTIME_NOT_CONFIGURED: 503,

  BROWSER_SESSION_UNAUTHENTICATED: 401,
  EXTERNAL_IDENTITY_UNBOUND: 401,
  OIDC_ID_TOKEN_INVALID: 401,
  OIDC_ID_TOKEN_REQUIRED: 401,
  PROTOTYPE_PRINCIPAL_UNAUTHENTICATED: 401,
  SERVICE_TOKEN_SUBJECT_REQUIRED: 401,
  SERVICE_TOKEN_UNAUTHENTICATED: 401,

  BROWSER_CSRF_FORBIDDEN: 403,
  CONSUMER_SUBSCRIPTION_FORBIDDEN: 403,
  OBJECT_PERMISSION_FORBIDDEN: 403,
  PRINCIPAL_KIND_FORBIDDEN: 403,
  PROTOTYPE_CSRF_FORBIDDEN: 403,
  PROTOTYPE_PRODUCTION_FORBIDDEN: 403,

  APPROVAL_STAGE_NOT_FOUND: 404,
  APPROVAL_TEMPLATE_VERSION_NOT_FOUND: 404,
  BLOCKED_DELIVERY_NOT_FOUND: 404,
  CHANGE_REQUEST_NOT_FOUND: 404,
  CHARGE_ITEM_NOT_FOUND: 404,
  CHARGE_ITEM_PUBLISHED_REFERENCE_NOT_FOUND: 404,
  CHARGE_ITEM_VERSION_HISTORY_NOT_FOUND: 404,
  CHARGE_ITEM_VERSION_NOT_FOUND: 404,
  CONSUMER_EVENT_NOT_AVAILABLE: 404,
  CONSUMER_SUBSCRIPTION_NOT_FOUND: 404,
  DEPARTMENT_HIERARCHY_VERSION_NOT_FOUND: 404,
  IMPACT_CASE_NOT_FOUND: 404,
  IMPORT_JOB_NOT_FOUND: 404,
  PRICE_LIST_RELEASE_NOT_FOUND: 404,
  SNAPSHOT_NOT_AVAILABLE_TO_SUBSCRIPTION: 404,
  SNAPSHOT_NOT_FOUND: 404,

  APPROVAL_DUTY_SEPARATION_CONFLICT: 409,
  APPROVAL_STAGE_ORDER_CONFLICT: 409,
  CHARGE_ITEM_APPROVAL_WORKFLOW_REQUIRED: 409,
  CHARGE_ITEM_BITEMPORAL_CONFLICT: 409,
  CHARGE_ITEM_DRAFT_IMMUTABLE: 409,
  CHARGE_ITEM_OPEN_VERSION_CANDIDATE_CONFLICT: 409,
  CHARGE_ITEM_PUBLICATION_STATE_CONFLICT: 409,
  CHARGE_ITEM_RECORDED_TIME_CONFLICT: 409,
  CONSUMER_CHECKPOINT_GAP: 409,
  EMERGENCY_ACTOR_CLOSURE_CONFLICT: 409,
  EMERGENCY_ACTOR_REVIEW_CONFLICT: 409,
  IMPACT_CASE_STATE_CONFLICT: 409,
  PRICE_IMPORT_APPLICABILITY_CONFLICT: 409,
  PRICE_LIST_CURRENT_RELEASE_CLOSE_CONFLICT: 409,
  PRICE_LIST_DRAFT_IMMUTABLE: 409,
  PRICE_LIST_APPROVAL_WORKFLOW_REQUIRED: 409,
  PRICE_LIST_PUBLICATION_STATE_CONFLICT: 409,
  PRICE_LIST_RECORDED_TIME_CONFLICT: 409,
  PRICE_LIST_RELEASE_CONFLICT: 409,
  PRICE_LIST_STABLE_CODE_IMMUTABLE: 409,
  PRICE_RESOLUTION_IDEMPOTENCY_CONFLICT: 409,

  APPROVAL_CAMPUS_CONFIRMATION_REQUIRED: 400,
  APPROVAL_CAMPUS_EVIDENCE_INVALID: 400,
  AUDIT_STREAM_GOVERNANCE_OBJECT_MISMATCH: 400,
  AUTHENTICATION_CONFIGURATION_INVALID: 400,
  AUTHENTICATION_LIFETIME_INVALID: 400,
  BROWSER_SESSION_CSRF_STATE_INVALID: 400,
  CAMPUS_PRICE_SCOPE_REQUIRED: 400,
  CHARGE_ITEM_BILLING_UNIT_INVALID: 400,
  CHARGE_ITEM_BUSINESS_PERIOD_INVALID: 400,
  CHARGE_ITEM_CHARGING_METHOD_INVALID: 400,
  CHARGE_ITEM_FORMAL_NAME_INVALID: 400,
  CHARGE_ITEM_INTERNAL_CODE_INVALID: 400,
  CHARGE_ITEM_SERVICE_DEFINITION_INVALID: 400,
  CONSUMER_PROCESSING_DIGEST_MISMATCH: 400,
  CURRENCY_CODE_INVALID: 400,
  EMERGENCY_SUSPENSION_SCOPE_INVALID: 400,
  EMERGENCY_SUSPENSION_PUBLISHED_RELEASE_REQUIRED: 400,
  FIXED_UNIT_PRICE_INVALID: 400,
  IMPORT_BUSINESS_KEY_REQUIRED: 400,
  IMPORT_CSV_COLUMN_COUNT_INVALID: 400,
  IMPORT_CSV_HEADER_INVALID: 400,
  IMPORT_JSON_ROWS_INVALID: 400,
  IMPORT_RETRY_INPUT_DIGEST_MISMATCH: 400,
  IMPORT_ROW_ID_REQUIRED: 400,
  IMPORT_ROW_VALUE_TYPE_INVALID: 400,
  IMPORT_ROWS_REQUIRED: 400,
  IMPACT_CASE_GOVERNANCE_OBJECT_MISMATCH: 400,
  IMPACT_RECOVERY_PUBLICATION_REQUIRED: 400,
  IMPACT_REVIEW_REQUIRED: 400,
  LOCAL_DATETIME_INVALID: 400,
  NOTIFICATION_TARGET_AUTHORIZATION_REQUIRED: 400,
  NOTIFICATION_TARGET_URL_INVALID: 400,
  OIDC_AUTHORIZATION_RESPONSE_ISSUER_MISMATCH: 400,
  OIDC_DISCOVERY_INVALID: 400,
  OIDC_LOGIN_TRANSACTION_INVALID: 400,
  OUTBOX_WORKER_ID_INVALID: 400,
  PRICE_ENTRY_BILLING_UNIT_MISMATCH: 400,
  PRICE_ENTRY_BUSINESS_PERIOD_INVALID: 400,
  PRICE_ENTRY_ENCOUNTER_MODE_INVALID: 400,
  PRICE_ENTRY_ENCOUNTER_TYPE_INVALID: 400,
  PRICE_ENTRY_SCOPE_INVALID: 400,
  PRICE_LIST_BUSINESS_PERIOD_INVALID: 400,
  PRICE_LIST_CONTENT_HASH_INVALID: 400,
  PRICE_LIST_ENTRIES_REQUIRED: 400,
  PRICE_LIST_GOVERNANCE_OBJECT_MISMATCH: 400,
  PRICE_LIST_HIGH_RISK_CLASSIFICATION_REQUIRED: 400,
  PRICE_QUANTITY_INVALID: 400,
  POSTGRES_LOCAL_DATETIME_INVALID: 400,
  PROJECTION_ITEM_COUNT_INVALID: 400,
  PROJECTION_PAYLOAD_SCHEMA_INVALID: 400,
  PROTOTYPE_LOOPBACK_BIND_REQUIRED: 400,
  PROTOTYPE_MODE_REQUIRED: 400,
  RECOVERY_CONSUMER_RECEIPT_REQUIRED: 400,
  RECOVERY_IMPACT_CASE_REQUIRED: 400,
  RECOVERY_PUBLICATION_CLASSIFICATION_REQUIRED: 400,
  RETURN_TO_INVALID: 400,
  SCHEMA_UPGRADE_CONTRACT_IDENTITY_INVALID: 400,
  SCHEMA_UPGRADE_DOMAIN_EQUIVALENCE_MISMATCH: 400,
  SCHEMA_UPGRADE_RISK_CLASSIFICATION_REQUIRED: 400,
  SCHEMA_UPGRADE_SCOPE_MISMATCH: 400,
  ZERO_PRICE_REASON_REQUIRED: 400,
};

const safeExclusionConstraintCodes = new Set(['PRICE_PERIOD_EXCLUSION_CONFLICT']);
const safeCheckConstraintCodes = new Set(['PRICE_ENTRY_CHECK_INVALID']);

export function mapHttpError(error: unknown): HttpErrorMapping {
  if (!(error instanceof Error)) return internalError();

  if (error instanceof DepartmentContractError) {
    return {
      statusCode: departmentErrorStatus[error.code],
      code: error.code,
    };
  }

  const candidate = error as Error & { readonly code?: string; readonly validation?: unknown };
  if (candidate.validation) return { statusCode: 400, code: 'REQUEST_SCHEMA_INVALID' };

  if (isSqlState(candidate.code)) return mapDatabaseError(candidate.code, candidate.message);

  const statusCode = Object.hasOwn(publicErrorStatus, candidate.message)
    ? publicErrorStatus[candidate.message]
    : undefined;
  if (statusCode !== undefined) return { statusCode, code: candidate.message };

  return internalError();
}

function isSqlState(code: string | undefined): code is string {
  return code !== undefined && /^[0-9A-Z]{5}$/u.test(code);
}

function mapDatabaseError(code: string, message: string): HttpErrorMapping {
  if (code === '23505') return { statusCode: 409, code: 'UNIQUE_CONSTRAINT_CONFLICT' };
  if (code === '55000') return { statusCode: 409, code: 'IMMUTABLE_RECORD_CONFLICT' };
  if (code === '23P01') {
    return {
      statusCode: 409,
      code: safeExclusionConstraintCodes.has(message)
        ? message
        : 'EXCLUSION_CONSTRAINT_CONFLICT',
    };
  }
  if (code === '23514') {
    return {
      statusCode: 400,
      code: safeCheckConstraintCodes.has(message) ? message : 'CHECK_CONSTRAINT_INVALID',
    };
  }
  return internalError();
}

function internalError(): HttpErrorMapping {
  return { statusCode: 500, code: 'INTERNAL_ERROR' };
}
