import type {FastifyInstance,FastifyRequest} from 'fastify';
import {Type,type Static,type TSchema} from 'typebox';
import {Check} from 'typebox/value';
import {UsageTypeCommandSchema,UsageTypeReadSchema,UsageTypeListSchema,UsageTypeItemSchema,UsageTypePermissionsSchema,UsageTypeMaterialReadSchema,UsageTypeMaterialSchema,UseId,UseTime,UseEnd,UseHead,UseDigest,UseScopeSchema,UsePolicySchema,UsageTypeReferenceSchema,LocationUseDirectStageSchema,LocationUseStoredStageSchema,LocationUseVerifySchema,LocationUseInputSchema,LocationUsePlanSchema,LocationUseReadSchema,LocationUseHistorySchema,LocationUseExactSchema,LocationUseDiffSchema,LocationUseListSchema,LocationUseWindowSchema,LocationUseReceiveSchema,type LocationUseOwner,type LocationUsageTypeOwner,type LocationUseHistory,type LocationUseVersion} from '../../modules/location-master/index.js';
import {ApproveApplyUnitSchema,ApplyUnitSchema,PlanOwnerUnitSchema,ContractItemSchema,canonicalPlan,type ImportContractItem} from '../../modules/governance-catalog/index.js';
import {parseStrictJson} from './strict-json.js';

const closed={additionalProperties:false} as const,Text=Type.String();
const ErrorSchema=Type.Object({code:Text,message:Text,field:Type.Optional(Text),budget:Type.Optional(Type.Object({kind:Type.Enum(['REFERENCE_COUNT','ASSESSMENT_BYTES']),observed:Type.Integer(),limit:Type.Integer()},closed))},closed);
const errors={400:ErrorSchema,403:ErrorSchema,404:ErrorSchema,409:ErrorSchema,413:ErrorSchema,500:ErrorSchema,503:ErrorSchema};
export interface LocationUseHttpContext {owner?:LocationUseOwner;usageTypes?:LocationUsageTypeOwner;actor:(request:FastifyRequest)=>string}

const Source=Type.Object({sourceAlias:Text,sourceVersion:Text,sourceSystemId:UseId,sourceRecordedAt:UseTime,recordLocatorEvidence:Type.Object({inputId:UseId,row:Type.Integer()},closed),recordStatus:Text,approvalReference:Type.Union([Text,Type.Null()])},closed);
const OpaqueBasis=Type.Object({format:Type.Literal('OWNER_BASIS_JSON_V1'),canonicalJson:Text},closed);
const opaqueBasis=(value:unknown)=>({format:'OWNER_BASIS_JSON_V1' as const,canonicalJson:canonicalPlan(value)});
const publicVersion=(value:LocationUseVersion)=>({...value,facts:{...value.facts,dependencies:opaqueBasis(value.facts.dependencies)}});
const publicHistory=(value:LocationUseHistory)=>({...value,versions:value.versions.map(publicVersion)});
const PublicContract=Type.Object({...ContractItemSchema.properties,schemas:OpaqueBasis,sourcePolicies:OpaqueBasis},closed);
const publicContract=(value:ImportContractItem)=>({...value,schemas:opaqueBasis(value.schemas),sourcePolicies:opaqueBasis(value.sourcePolicies)});
const Facts=Type.Object({isPrimary:Type.Boolean(),sharingDescription:Type.Union([Text,Type.Null()]),policy:UsePolicySchema,usageType:UsageTypeReferenceSchema,usageCode:Text,contractVersionId:UseId,verificationBasis:Type.Object({id:UseId,version:UseHead,digest:UseDigest},closed),dependencies:OpaqueBasis,source:Source},closed);
const Version=Type.Object({id:UseId,number:UseHead,action:Type.Enum(['CREATE','REVISE','END']),validFrom:UseTime,validTo:UseEnd,recordedAt:UseTime,facts:Facts,reason:Text,changeId:UseId},closed);
const Read=Type.Object({id:UseId,applicability:UseScopeSchema,head:UseHead,state:Type.Enum(['ACTIVE','ENDED','NOT_EFFECTIVE']),version:Type.Union([Version,Type.Null()]),clinicalReadiness:Type.Literal('NOT_READY')},closed);
const History=Type.Object({id:UseId,scope:Type.Enum(['NORTH','SOUTH']),applicability:UseScopeSchema,versions:Type.Array(Version)},closed);
const Fact=Type.Object({owner:Type.Literal('location-master/location-use'),id:UseId,version:UseHead,source:Type.Optional(Type.Object({dataset:Type.Literal('ORG13'),row:Type.Integer(),step:Text},closed))},closed);
const Outcome=Type.Union([Type.Object({status:Type.Literal('COMMITTED'),candidateId:UseId,requestId:UseId,facts:Type.Array(Fact),recordedAt:UseTime,responseStatus:Type.Optional(Type.Enum(['DELIVERED','POST_COMMIT_FAILED']))},closed),Type.Object({status:Type.Literal('COMMIT_UNKNOWN'),candidateId:UseId,requestId:UseId},closed)]);
const Issue=Type.Object({row:Type.Integer(),field:Text,code:Text,status:Type.Enum(['FAIL','BLOCKED'])},closed),Candidate=Type.Object({candidateId:UseId},closed);
const Change=Type.Object({action:Text,targetId:Type.Union([UseId,Type.Null()]),validFrom:UseTime,validTo:UseEnd},closed),Period=Type.Object({from:UseTime,to:UseEnd},closed);
const Unit=Type.Object({input:PlanOwnerUnitSchema,atomicRule:Type.Literal('ORG13_WHOLE_REVISION_V1'),basis:Type.Object({input:LocationUseStoredStageSchema,inputDigest:UseDigest,contract:PublicContract,verificationId:Type.Union([UseId,Type.Null()]),verificationDigest:Type.Union([UseDigest,Type.Null()]),issues:Type.Array(Issue),heads:Type.Array(History),materials:Type.Array(Type.Object({id:UseId,digest:UseDigest},closed)),dependencies:Type.Array(OpaqueBasis)},closed),commands:Type.Array(Type.Object({owner:Type.Literal('location-master/location-use'),row:Type.Integer(),intent:Type.Enum(['CREATE','REVISE']),target:Type.Union([Fact,Type.Null()]),aliases:Type.Array(Type.Integer()),value:Type.Object({inputId:UseId,writes:Type.Optional(Text),writeIndex:Text,writesDigest:UseDigest},closed)},closed)),diff:Type.Array(Type.Object({action:Text,targetId:Type.Union([UseId,Type.Null()]),from:UseTime,to:UseEnd},closed))},closed);
const NullableDigest=Type.Union([UseDigest,Type.Null()]);
const ValidationRun=Type.Object({runId:UseId,jobId:UseId,revisionId:UseId,parseArtifactId:UseId,sourceArtifactId:UseId,parserPolicy:Text,contractVersionId:UseId,ruleVersion:Text,interpretationPolicy:Text,decision:Type.Enum(['PASS','FAIL','BLOCKED']),issueCount:Type.Integer(),resultArtifactId:UseId,recordedAt:UseTime,adapterReadiness:Type.Enum(['NOT_READY','READY']),securityScan:Type.Literal('NOT_RUN'),qualityCandidateDigest:Type.Optional(NullableDigest),qualityEligibilityDigest:Type.Optional(NullableDigest),qualityResolutionDigest:Type.Optional(NullableDigest)},closed);
const RuleStatus=Type.Enum(['PASS','FAIL','UNKNOWN','NOT_EVALUATED']),LayerStatus=Type.Enum(['PASS','FAIL','UNKNOWN','NOT_EVALUATED','NOT_RUN']);
const ValidationEvaluation=Type.Object({decision:Type.Enum(['PASS','FAIL','BLOCKED']),issues:Type.Array(Type.Object({rule:Text,layer:Type.Integer(),row:Type.Integer(),field:Text,status:RuleStatus,code:Text},closed)),layers:Type.Array(Type.Object({layer:Type.Integer(),status:LayerStatus},closed)),evidenceRequirements:Type.Array(Type.Object({rule:Text,requirementId:Text,row:Type.Integer(),field:Text,status:Type.Literal('BLOCKED_DEPENDENCY'),details:Type.Optional(Type.Object({evidenceOwner:Text,requiredEvidence:Text,sourceDataset:Text,sourceField:Text,sourceText:Text,sourceVersion:Text,inputs:Type.Array(Text),dispositionReason:Text,whenTrue:Text,whenFalse:Text,whenUnknown:Text},closed))},closed)),dependencies:Type.Array(Type.Object({target:Text,status:Type.Enum(['NOT_READY','OBSERVED']),scope:Text,identity:Text,version:Type.Union([Text,Type.Null()]),periods:Type.Array(Period)},closed)),interpretationPolicy:Type.Literal('EXACT_TEXT_V1'),executionCoverage:Type.Optional(Type.Object({version:Type.Literal('RULE_EXECUTION_V1'),checks:Type.Array(Type.Object({rule:Text,layer:Type.Integer(),field:Text,status:LayerStatus,code:Text,rows:Type.Array(Type.Integer())},closed))},closed)),deduplicationPolicy:Type.Optional(Type.Enum(['EXACT_ROW_V1','DECLARED_KEY_V2'])),duplicates:Type.Optional(Type.Array(Type.Object({row:Type.Integer(),duplicateOf:Type.Integer()},closed)))},closed);
// A structural rejection retains parser/report artifacts without creating a
// semantic validation run for malformed source content.
const FileValidation=Type.Union([
 Type.Object({run:ValidationRun,evaluation:ValidationEvaluation},closed),
 Type.Object({status:Type.Literal('STRUCTURAL_REJECTED'),semanticValidation:Type.Literal('NOT_RUN'),sourceArtifactId:UseId,parseArtifactId:UseId,resultArtifactId:UseId,evaluation:Type.Object({...ValidationEvaluation.properties,decision:Type.Literal('FAIL')},closed)},closed),
]);

// These import surfaces retain original scalar types and reject duplicate JSON
// keys before AJV has an opportunity to coerce a source number or null.
export function registerLocationUseRoutes(app:FastifyInstance,context?:LocationUseHttpContext){
 app.register(async scoped=>{
  scoped.removeContentTypeParser('application/json');
  scoped.addContentTypeParser('application/json',{parseAs:'string'},(_request,body,done)=>{try{if(typeof body!=='string')throw new Error('CLOSED_INPUT_REQUIRED');done(null,parseStrictJson(body,'EXACT_SAFE_INTEGER'));}catch{done(new Error('CLOSED_INPUT_REQUIRED'));}});
  const route=<S extends TSchema>(path:string,operationId:string,body:S,response:TSchema,handle:(owner:LocationUsageTypeOwner,actor:string,input:Static<S>)=>Promise<unknown>)=>scoped.post<{Body:Static<S>}>('/api/vnext/location-usage-types/'+path,{
   validatorCompiler:({schema})=>input=>Check(schema as never,input)?{value:input}:{error:new Error('CLOSED_INPUT_REQUIRED')},
   schema:{operationId,body,response:{200:response,...errors}},
  },request=>{if(!context?.usageTypes)throw new Error('BLOCKED_DEPENDENCY');return handle(context.usageTypes,context.actor(request),request.body as Static<S>);});
  route('command','commandLocationUsageType',UsageTypeCommandSchema,UsageTypeItemSchema,(owner,actor,input)=>owner.command(actor,input));
  route('permissions','permissionsLocationUsageTypes',Type.Object({},closed),UsageTypePermissionsSchema,(owner,actor)=>owner.permissions(actor));
  route('material','readLocationUsageTypeMaterial',UsageTypeMaterialReadSchema,UsageTypeMaterialSchema,(owner,actor,input)=>owner.readMaterial(actor,input));
  route('query','readLocationUsageType',UsageTypeReadSchema,UsageTypeItemSchema,(owner,actor,input)=>owner.read(actor,input));
  route('history','historyLocationUsageType',Type.Omit(UsageTypeReadSchema,['versionId'],closed),Type.Array(UsageTypeItemSchema),(owner,actor,input)=>owner.history(actor,input));
  route('list','listLocationUsageTypes',UsageTypeListSchema,Type.Object({items:Type.Array(UsageTypeItemSchema),nextAfterId:Type.Union([UsageTypeReadSchema.properties.id,Type.Null()])},closed),(owner,actor,input)=>owner.list(actor,input));
  const useRoute=<S extends TSchema>(path:string,operationId:string,body:S,response:TSchema,handle:(owner:LocationUseOwner,actor:string,input:Static<S>)=>Promise<unknown>)=>scoped.post<{Body:Static<S>}>('/api/vnext/location-uses/'+path,{validatorCompiler:({schema})=>input=>Check(schema as never,input)?{value:input}:{error:new Error('CLOSED_INPUT_REQUIRED')},schema:{operationId,body,response:{200:response,...errors}}},request=>{if(!context?.owner)throw new Error('BLOCKED_DEPENDENCY');return handle(context.owner,context.actor(request),request.body as Static<S>);});
  useRoute('inputs','stageLocationUseInput',LocationUseDirectStageSchema,Type.Object({inputId:UseId,revisionId:UseId,digest:UseDigest},closed),(owner,actor,input)=>owner.stage(actor,input));
  useRoute('inputs/read','readLocationUseInput',LocationUseInputSchema,LocationUseStoredStageSchema,(owner,actor,input)=>owner.readInput(actor,input));
  useRoute('verify','verifyLocationUseInput',LocationUseVerifySchema,Type.Object({verificationId:UseId},closed),(owner,actor,input)=>owner.verify(actor,input));
  useRoute('preview','previewLocationUseInput',LocationUseInputSchema,Type.Object({decision:Type.Enum(['PASS','BLOCKED']),issues:Type.Array(Issue),changes:Type.Array(Change)},closed),(owner,actor,input)=>owner.preview(actor,input));
  useRoute('plan','planLocationUseInput',LocationUsePlanSchema,Type.Object({candidateId:UseId,digest:UseDigest},closed),(owner,actor,input)=>owner.plan(actor,input));
  useRoute('withdraw','withdrawLocationUseInput',LocationUsePlanSchema,Type.Object({inputId:UseId,status:Type.Literal('WITHDRAWN')},closed),(owner,actor,input)=>owner.withdraw(actor,input));
  useRoute('review','reviewLocationUseCandidate',Candidate,Type.Object({candidateId:UseId,digest:UseDigest,unit:Unit,approvedBy:Type.Union([Text,Type.Null()])},closed),async(owner,actor,input)=>{const result=await owner.readApplyCandidate(actor,input);return {...result,unit:{...result.unit,basis:{...result.unit.basis,contract:publicContract(result.unit.basis['contract'] as ImportContractItem),heads:(result.unit.basis['heads'] as LocationUseHistory[]).map(publicHistory),dependencies:(result.unit.basis['dependencies'] as unknown[]).map(opaqueBasis)}}};});
  useRoute('approve','approveLocationUseCandidate',ApproveApplyUnitSchema,Type.Object({candidateId:UseId,approvedBy:Text},closed),(owner,actor,input)=>owner.approveApplyUnit(actor,input));
  useRoute('apply','applyLocationUseCandidate',ApplyUnitSchema,Outcome,(owner,actor,input)=>owner.applyUnit(actor,input));
  useRoute('resume','resumeLocationUseOutcome',ApplyUnitSchema,Type.Union([Outcome,Type.Null()]),(owner,actor,input)=>owner.resumeOutcome(actor,input));
  useRoute('reconcile','reconcileLocationUseOutcome',ApplyUnitSchema,Type.Object({status:Type.Enum(['MATCHED','MISMATCH']),receiptId:UseId},closed),(owner,actor,input)=>owner.reconcileCommittedUnit(actor,input));
  useRoute('query','getLocationUseAsOf',LocationUseReadSchema,Read,async(owner,actor,input)=>{const result=await owner.read(actor,input);return {...result,version:result.version?publicVersion(result.version):null};});
  useRoute('history','getLocationUseHistory',LocationUseHistorySchema,History,async(owner,actor,input)=>publicHistory(await owner.history(actor,input)));
  useRoute('exact','getLocationUseVersion',LocationUseExactSchema,Version,async(owner,actor,input)=>publicVersion(await owner.exact(actor,input)));
  useRoute('diff','diffLocationUseVersions',LocationUseDiffSchema,Type.Object({id:UseId,before:Version,after:Version},closed),async(owner,actor,input)=>{const result=await owner.diff(actor,input);return {...result,before:publicVersion(result.before),after:publicVersion(result.after)};});
  useRoute('list','listLocationUses',LocationUseListSchema,Type.Object({items:Type.Array(Read),nextAfterId:Type.Union([UseId,Type.Null()])},closed),async(owner,actor,input)=>{const result=await owner.list(actor,input);return {...result,items:result.items.map(item=>({...item,version:item.version?publicVersion(item.version):null}))};});
  useRoute('evaluate','evaluateLocationUseWindow',LocationUseWindowSchema,Type.Object({id:UseId,mode:LocationUseWindowSchema.properties.mode,recordAsOf:UseTime,declarationCovered:Type.Boolean(),primaryCovered:Type.Boolean(),currentAdmissionCovered:Type.Boolean(),declarationGaps:Type.Array(Period),primaryGaps:Type.Array(Period),currentGaps:Type.Array(Period),checks:Type.Array(Type.Object({...Period.properties,status:Type.Enum(['SATISFIED','NOT_SATISFIED']),reason:Text,acceptedBasis:OpaqueBasis,basis:OpaqueBasis,dependencyChecks:Type.Array(Type.Object({owner:Type.Enum(['LOCATION','ORGANIZATION','USAGE_TYPE','SOURCE']),status:Type.Enum(['SATISFIED','NOT_SATISFIED']),reason:Text,basisChanged:Type.Boolean(),basis:OpaqueBasis},closed))},closed)),clinicalReadiness:Type.Literal('NOT_READY'),moving:Type.Literal('NOT_EVALUABLE')},closed),async(owner,actor,input)=>{const result=await owner.evaluateWindow(actor,input);return {...result,checks:result.checks.map(check=>({...check,acceptedBasis:opaqueBasis(check.acceptedBasis),basis:opaqueBasis(check.basis),dependencyChecks:check.dependencyChecks.map(dependency=>({...dependency,basis:opaqueBasis(dependency.basis)}))}))};});
  const File=Type.Object({input:LocationUseReceiveSchema,contentBase64:Type.String({minLength:4,maxLength:1398104,pattern:'^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'})},closed);
  scoped.post<{Body:Static<typeof File>}>('/api/vnext/location-uses/files',{bodyLimit:1500000,validatorCompiler:({schema})=>input=>Check(schema as never,input)?{value:input}:{error:new Error('CLOSED_INPUT_REQUIRED')},schema:{operationId:'receiveLocationUseFile',body:File,response:{200:Type.Object({jobId:UseId,revisionId:UseId,sourceArtifactId:UseId,structuralStatus:Type.Enum(['PARSED','REJECTED']),input:Type.Union([Type.Object({inputId:UseId,revisionId:UseId,digest:UseDigest},closed),Type.Null()]),issues:Type.Array(Issue),validation:FileValidation},closed),...errors}}},async request=>{if(!context?.owner)throw new Error('BLOCKED_DEPENDENCY');const bytes=Buffer.from(request.body.contentBase64,'base64');try{return await context.owner.receiveFile(context.actor(request),request.body.input,bytes);}finally{bytes.fill(0);}});
 });
}
