import type {FastifyInstance,FastifyRequest} from 'fastify';
import {Type,type Static,type TSchema} from 'typebox';
import {openDepartmentLifecycle,DepartmentLifecycleStoredStageSchema,DepartmentLifecycleStoredVerifySchema,DepartmentLifecycleStageSchema,DepartmentLifecycleVerifySchema,DepartmentLifecycleCommandSchema,DepartmentAdmissionSchema,DepartmentLifecycleReadSchema,DepartmentLifecycleHistorySchema,DepartmentLifecycleInputSchema,DepartmentLifecyclePlanSchema,DepartmentRelationListSchema,DepartmentRelationDiffSchema,DepartmentAssessmentSchema,EvolutionImpactSchema,lifecycleCheck} from '../../modules/department-master/index.js';
import {ApplyUnitSchema,ApproveApplyUnitSchema} from '../../modules/governance-catalog/index.js';
import {DepartmentHistoryResponseSchema} from './vnext-department-routes.js';
import {OperatingEvaluationResponseSchema} from './vnext-operating-routes.js';

const closed={additionalProperties:false} as const,Text=Type.String(),Id=Type.String({pattern:'^[a-f0-9-]{36}$'}),Time=Type.String(),Nullable=Type.Union([Text,Type.Null()]);
const ErrorSchema=Type.Object({code:Text,message:Text,field:Type.Optional(Text)},closed);
const errors={400:ErrorSchema,403:ErrorSchema,404:ErrorSchema,409:ErrorSchema,500:ErrorSchema,503:ErrorSchema};
const Fact=Type.Object({owner:Type.Literal('department-master/lifecycle'),id:Id,version:Text},closed);
const Outcome=Type.Object({status:Type.Enum(['COMMITTED','COMMIT_UNKNOWN']),candidateId:Id,requestId:Id,facts:Type.Optional(Type.Array(Fact)),recordedAt:Type.Optional(Time),responseStatus:Type.Optional(Type.Enum(['DELIVERED','POST_COMMIT_FAILED']))},closed);
const Candidate=Type.Object({candidateId:Id},closed);
const Period=Type.Object({from:Time,to:Type.Union([Time,Type.Null()])},closed);
const Life=Type.Object({id:Id,departmentId:Id,version:Text,action:Type.Enum(['SUSPEND','RESUME','DEPRECATE']),effectiveAt:Time,recordedAt:Time,operationId:Id},closed);
const RelationVersion=Type.Object({id:Id,version:Text,action:Type.Enum(['ASSIGN','REVISE','END','MOVE_SOURCE','MOVE_TARGET']),services:Type.Array(Text),validFrom:Time,validTo:Type.Union([Time,Type.Null()]),recordedAt:Time,operationId:Id},closed);
const Relation=Type.Object({id:Id,departmentId:Id,campusId:Id,subjectId:Id,scope:Type.Enum(['NORTH','SOUTH']),head:Text,versions:Type.Array(RelationVersion)},closed);
const History=Type.Object({id:Id,head:Text,lifecycleHead:Text,lifecycle:Type.Array(Life),relations:Type.Array(Relation),replacement:Type.Union([Type.Object({eventId:Id,effectiveAt:Time,recordedAt:Time},closed),Type.Null()])},closed);
const Material=Type.Object({id:Id,digest:Text},closed);
const FrozenAssessment=Type.Object({reference:Type.Object({id:Id,digest:Text},closed),content:DepartmentAssessmentSchema,binding:Type.Object({contractVersionId:Id,sourceVersionId:Type.Union([Id,Type.Null()]),impacts:Type.Array(EvolutionImpactSchema),materials:Type.Array(Material)},closed)},closed);
const ExpandedWrite=Type.Union([Type.Object({kind:Type.Literal('LIFECYCLE'),departmentId:Id,action:Type.Enum(['SUSPEND','RESUME','DEPRECATE']),effectiveAt:Time},closed),Type.Object({kind:Type.Literal('RELATION'),departmentId:Id,campusId:Id,subjectId:Id,relationId:Type.Union([Id,Type.Null()]),expectedVersion:Nullable,action:Type.Enum(['ASSIGN','REVISE','END','MOVE_SOURCE','MOVE_TARGET']),services:Type.Array(Text),validFrom:Time,validTo:Type.Union([Time,Type.Null()])},closed)]);
const Review=Type.Object({candidateId:Id,digest:Text,approvedBy:Nullable,input:DepartmentLifecycleStoredStageSchema,changes:Type.Array(DepartmentLifecycleCommandSchema),issues:Type.Array(Type.Object({code:Text},closed)),verification:Type.Union([DepartmentLifecycleStoredVerifySchema,Type.Null()]),states:Type.Array(Type.Object({...History.properties,department:DepartmentHistoryResponseSchema},closed)),materials:Type.Array(Material),dependencies:Type.Array(Type.Omit(OperatingEvaluationResponseSchema,['observedAt','asOf'])),assessment:Type.Union([FrozenAssessment,Type.Null()]),writes:Type.Array(ExpandedWrite)},closed);
type Owner=ReturnType<typeof openDepartmentLifecycle>;
export interface DepartmentLifecycleHttpContext {owner:Owner;actor:(request:FastifyRequest)=>string}
function historyDTO(s:Awaited<ReturnType<Owner['history']>>){return {id:s.department.id,head:String(s.department.versions.at(-1)?.number??0),lifecycleHead:s.lifecycle.at(-1)?.number??'0',lifecycle:s.lifecycle.map(v=>({id:v.id,departmentId:v.department_id,version:v.number,action:v.action,effectiveAt:v.effective_at,recordedAt:v.recorded_at,operationId:v.operation_id})),relations:s.relations.map(r=>({id:r.id,departmentId:r.department_id,campusId:r.campus_id,subjectId:r.subject_id,scope:r.governance_scope,head:r.versions.at(-1)?.number??'0',versions:r.versions.map(v=>({id:v.id,version:v.number,action:v.action,services:v.services,validFrom:v.valid_from,validTo:v.valid_to,recordedAt:v.recorded_at,operationId:v.operation_id}))})),replacement:s.replacement?{eventId:s.replacement.event_id,effectiveAt:s.replacement.effective_at.replace(' ','T'),recordedAt:s.replacement.recorded_at.replace(' ','T')}:null};}
export function registerDepartmentLifecycleRoutes(app:FastifyInstance,context?:DepartmentLifecycleHttpContext){
 const route=<S extends TSchema>(path:string,operationId:string,body:S,response:TSchema,handler:(o:Owner,a:string,b:Static<S>)=>Promise<unknown>)=>{
  app.post<{Body:Static<S>}>('/api/vnext/department-lifecycle/'+path,{preValidation:async r=>{lifecycleCheck(body,r.body);},schema:{operationId,body,response:{200:response,...errors}}},r=>{if(!context)throw new Error('BLOCKED_DEPENDENCY');return handler(context.owner,context.actor(r),r.body as Static<S>);});
 };
 route('inputs','stageDepartmentLifecycle',DepartmentLifecycleStageSchema,Type.Object({inputId:Id,revisionId:Id,digest:Text},closed),(o,a,b)=>o.stage(a,b));
 route('inputs/read','readDepartmentLifecycleInput',DepartmentLifecycleInputSchema,DepartmentLifecycleStoredStageSchema,(o,a,b)=>o.readInput(a,b));
 route('verify','verifyDepartmentLifecycle',DepartmentLifecycleVerifySchema,Type.Object({verificationId:Id},closed),(o,a,b)=>o.verify(a,b));
 route('plan','planDepartmentLifecycle',DepartmentLifecyclePlanSchema,Type.Object({candidateId:Id,digest:Text},closed),(o,a,b)=>o.plan(a,b));
 route('review','reviewDepartmentLifecycle',Candidate,Review,async(o,a,b)=>{const result=await o.readApplyCandidate(a,b),basis=result.unit.basis,input=basis['rawInput'] as Static<typeof DepartmentLifecycleStageSchema>,states=(basis['states']??[]) as Array<Awaited<ReturnType<Owner['history']>>>;return {candidateId:result.candidateId,digest:result.digest,approvedBy:result.approvedBy,input,changes:input.commands,issues:basis['issues'],verification:basis['verification']??null,states:states.map(s=>({...historyDTO(s),department:{id:s.department.id,initialCode:s.department.code,versions:s.department.versions}})),materials:basis['materials']??[],dependencies:basis['dependencies']??[],assessment:basis['assessment']??null,writes:result.unit.commands.flatMap(c=>(JSON.parse(c.value['writes']!) as Array<Record<string,unknown>>).map(({dependencies:_,...write})=>write))};});
 route('approve','approveDepartmentLifecycle',ApproveApplyUnitSchema,Type.Object({candidateId:Id,approvedBy:Text},closed),(o,a,b)=>o.approveApplyUnit(a,b));
 route('apply','applyDepartmentLifecycle',ApplyUnitSchema,Outcome,(o,a,b)=>o.applyUnit(a,b));
 route('resume','resumeDepartmentLifecycleOutcome',ApplyUnitSchema,Type.Union([Outcome,Type.Null()]),(o,a,b)=>o.resumeOutcome(a,b));
 route('history','getDepartmentLifecycleHistory',DepartmentLifecycleHistorySchema,History,async(o,a,b)=>historyDTO(await o.history(a,b)));
 route('query','getDepartmentLifecycleAsOf',DepartmentLifecycleReadSchema,Type.Object({...History.properties,businessState:Type.Enum(['ACTIVE','SUSPENDED','DEPRECATED','SUPERSEDED','NOT_EFFECTIVE'])},closed),async(o,a,b)=>{const result=await o.read(a,b);return {...historyDTO(result),businessState:result.businessState};});
 route('relations','listDepartmentCampusRelations',DepartmentRelationListSchema,Type.Object({items:Type.Array(Relation),nextAfterId:Type.Union([Id,Type.Null()])},closed),async(o,a,b)=>{const result=await o.listRelations(a,b),state=await o.history(a,{id:b.id,...(b.recordAsOf?{recordAsOf:b.recordAsOf}:{})});return {items:historyDTO({...state,relations:result.items}).relations,nextAfterId:result.nextAfterId};});
 route('relations/diff','diffDepartmentCampusRelation',DepartmentRelationDiffSchema,Type.Object({id:Id,before:RelationVersion,after:RelationVersion},closed),async(o,a,b)=>{const result=await o.diffRelation(a,b);const dto=(v:typeof result.before)=>({id:v.id,version:v.number,action:v.action,services:v.services,validFrom:v.valid_from,validTo:v.valid_to,recordedAt:v.recorded_at,operationId:v.operation_id});return {id:result.relation.id,before:dto(result.before),after:dto(result.after)};});
 route('admission','getDepartmentAdmissionWindow',DepartmentAdmissionSchema,Type.Object({owner:Type.Literal('department-master'),id:Id,covered:Type.Boolean(),parts:Type.Array(Period)},closed),(o,a,b)=>o.readAdmissionWindow(a,b));
}
