import {SubjectListSchema} from '../../modules/care-organization/index.js';
import type {FastifyInstance,FastifyRequest} from 'fastify';
import {Type,type Static,type TSchema} from 'typebox';
import {subjectCheck,SubjectId,SubjectTime,SubjectEnd,SubjectDigest,ApproveApplyUnitSchema,ApplyUnitSchema} from '../../modules/governance-catalog/index.js';
import {SubjectReceiveSchema,SubjectRecheckSchema,SubjectScopeSchema,SubjectAdoptionSchema,SubjectLicenseSchema,SubjectLimitationsSchema,SubjectRelationContextSchema,SubjectWindowSchema,SubjectWindowResultSchema,SubjectStageSchema,SubjectStoredStageSchema,SubjectVerificationSchema,SubjectInputSchema,SubjectPlanSchema,SubjectReadSchema,SubjectHistorySchema,SubjectExactSchema,type SubjectPermissionOwner} from '../../modules/care-organization/index.js';
const closed={additionalProperties:false} as const,Text=Type.String(),Kind=Type.Enum(['MAPPING','PERMISSION']),Action=Type.Enum(['RECORD','REVISE','RETIRE']);
const Pointer=Type.Object({inputId:SubjectId,row:Type.Integer()},closed);
const Source=Type.Object({codeSystemId:Text,codeSystemVersion:Text,sourceAlias:Text,sourceVersion:Text,sourceSystemId:SubjectId,sourceRecordedAt:SubjectTime,recordLocatorEvidence:Pointer,recordStatus:Text,approvalReference:Text,licenseDocumentEvidence:Pointer},closed);
const Facts=Type.Object({adoption:SubjectAdoptionSchema,context:Type.Union([SubjectRelationContextSchema,Type.Null()]),semantic:Type.Union([Type.Enum(['EQUIVALENT','NARROWER','BROADER','RELATED']),Type.Null()]),license:Type.Union([SubjectLicenseSchema,Type.Null()]),limitations:Type.Union([SubjectLimitationsSchema,Type.Null()]),verifierRole:Text,contractVersionId:SubjectId,verificationBasis:Type.Object({id:SubjectId,digest:SubjectDigest},closed),dependencies:Type.Unknown(),source:Source},closed);
const Version=Type.Object({id:SubjectId,number:Text,action:Action,validFrom:SubjectTime,validTo:SubjectEnd,recordedAt:SubjectTime,facts:Facts,reason:Text,changeId:SubjectId},closed);
const History=Type.Object({id:SubjectId,kind:Kind,scope:SubjectScopeSchema,versions:Type.Array(Version)},closed);
const Fact=Type.Object({owner:Type.Enum(['care-organization/subject-permission','care-organization/subject-mapping']),id:SubjectId,version:Text,source:Type.Optional(Type.Object({dataset:Type.Literal('ORG17'),row:Type.Integer(),step:Text},closed))},closed);
const Outcome=Type.Union([Type.Object({status:Type.Literal('COMMITTED'),candidateId:SubjectId,requestId:SubjectId,facts:Type.Array(Fact),recordedAt:SubjectTime,responseStatus:Type.Optional(Type.Enum(['DELIVERED','POST_COMMIT_FAILED']))},closed),Type.Object({status:Type.Literal('COMMIT_UNKNOWN'),candidateId:SubjectId,requestId:SubjectId},closed)]);
const Issue=Type.Object({row:Type.Integer(),field:Text,code:Text,status:Type.Enum(['FAIL','BLOCKED'])},closed),Staged=Type.Object({inputId:SubjectId,revisionId:SubjectId,digest:SubjectDigest},closed);
const ErrorSchema=Type.Object({code:Text,message:Text,field:Type.Optional(Text)},closed),errors={400:ErrorSchema,403:ErrorSchema,404:ErrorSchema,409:ErrorSchema,503:ErrorSchema};
export interface SubjectPermissionHttpContext {owner:SubjectPermissionOwner;actor:(request:FastifyRequest)=>string}
export function registerSubjectPermissionRoutes(app:FastifyInstance,context?:SubjectPermissionHttpContext){
 const route=<S extends TSchema>(path:string,operationId:string,body:S,response:TSchema,handle:(owner:SubjectPermissionOwner,actor:string,input:Static<S>)=>Promise<unknown>)=>app.post<{Body:Static<S>}>('/api/vnext/subject-permissions/'+path,{validatorCompiler:({schema})=>value=>{try{subjectCheck(schema,value);return {value};}catch(error){return {error:error instanceof Error?error:new Error('CLOSED_INPUT_REQUIRED')};}},schema:{operationId,body,response:{200:response,...errors}}},r=>{if(!context)throw new Error('BLOCKED_DEPENDENCY');return handle(context.owner,context.actor(r),r.body as Static<S>);});
 const Candidate=Type.Object({candidateId:SubjectId},{additionalProperties:false});
 route('inputs','stageSubjectPermissionInput',SubjectStageSchema,Type.Object({inputId:SubjectId,revisionId:SubjectId,digest:SubjectDigest},{additionalProperties:false}),(o,a,b)=>o.stage(a,b));
 route('inputs/read','readSubjectPermissionInput',SubjectInputSchema,SubjectStoredStageSchema,(o,a,b)=>o.readInput(a,b));
 route('verify','verifySubjectPermissionInput',SubjectVerificationSchema,Type.Object({verificationId:SubjectId},{additionalProperties:false}),(o,a,b)=>o.verify(a,b));
 route('preview','previewSubjectPermissionInput',SubjectInputSchema,Type.Object({decision:Type.Enum(['PASS','BLOCKED']),issues:Type.Array(Issue),changes:Type.Array(Type.Object({kind:Kind,action:Action,targetId:Type.Union([SubjectId,Type.Null()]),validFrom:SubjectTime,validTo:SubjectEnd},closed))},closed),(o,a,b)=>o.preview(a,b));
 route('plan','planSubjectPermissionInput',SubjectPlanSchema,Type.Object({candidateId:SubjectId,digest:SubjectDigest},{additionalProperties:false}),(o,a,b)=>o.plan(a,b));
 route('review','reviewSubjectPermissionCandidate',Candidate,Type.Unknown(),(o,a,b)=>o.readApplyCandidate(a,b));
 route('approve','approveSubjectPermissionCandidate',ApproveApplyUnitSchema,Type.Unknown(),(o,a,b)=>o.approveApplyUnit(a,b));
 route('apply','applySubjectPermissionCandidate',ApplyUnitSchema,Outcome,(o,a,b)=>o.applyUnit(a,b));
 route('resume','resumeSubjectPermissionOutcome',ApplyUnitSchema,Type.Union([Outcome,Type.Null()]),(o,a,b)=>o.resumeOutcome(a,b));
 route('reconcile','reconcileSubjectPermissionOutcome',ApplyUnitSchema,Type.Unknown(),(o,a,b)=>o.reconcileCommittedUnit(a,b));
 route('withdraw','withdrawSubjectPermissionInput',SubjectPlanSchema,Type.Object({inputId:SubjectId,status:Type.Literal('WITHDRAWN')},closed),(o,a,b)=>o.withdraw(a,b));
 route('query','querySubjectPermission',SubjectReadSchema,Type.Object({id:SubjectId,kind:Kind,scope:SubjectScopeSchema,head:Text,state:Type.Enum(['ACTIVE','RETIRED','NOT_EFFECTIVE']),version:Version,clinicalReadiness:Type.Literal('NOT_READY')},closed),(o,a,b)=>o.read(a,b));
 route('list','listSubjectRelations',SubjectListSchema,Type.Object({items:Type.Array(Type.Object({id:SubjectId,kind:Kind,scope:SubjectScopeSchema,head:Text,state:Type.Enum(['ACTIVE','RETIRED','NOT_EFFECTIVE']),version:Version,clinicalReadiness:Type.Literal('NOT_READY')},closed)),nextAfterId:Type.Union([SubjectId,Type.Null()])},closed),(o,a,b)=>o.list(a,b));
 route('history','historySubjectPermission',SubjectHistorySchema,History,(o,a,b)=>o.history(a,b));
 route('exact','exactSubjectPermission',SubjectExactSchema,Version,(o,a,b)=>o.exact(a,b));
 route('recheck','recheckSubjectPermission',SubjectRecheckSchema,Type.Object({id:SubjectId,kind:Kind,status:Type.Enum(['SATISFIED','REVIEW_REQUIRED']),reason:Text,acceptedBasis:Type.Unknown(),basis:Type.Unknown(),cases:Type.Array(Type.Unknown()),clinicalReadiness:Type.Literal('NOT_READY')},closed),(o,a,b)=>o.recheck(a,b));
 route('evaluate','evaluateSubjectPermissionWindow',SubjectWindowSchema,SubjectWindowResultSchema,(o,a,b)=>o.evaluateWindow(a,b));
 const File=Type.Object({input:SubjectReceiveSchema,contentBase64:Type.String({minLength:4,maxLength:1398104,pattern:'^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'})},closed);
 app.post<{Body:Static<typeof File>}>('/api/vnext/subject-permissions/files',{validatorCompiler:({schema})=>value=>{try{subjectCheck(schema,value);return {value};}catch(error){return {error:error instanceof Error?error:new Error('CLOSED_INPUT_REQUIRED')};}},bodyLimit:1500000,schema:{operationId:'receiveSubjectPermissionFile',body:File,response:{200:Type.Object({jobId:SubjectId,revisionId:SubjectId,sourceArtifactId:SubjectId,structuralStatus:Type.Enum(['PARSED','REJECTED']),input:Type.Union([Staged,Type.Null()]),issues:Type.Array(Issue),validation:Type.Unknown()},closed),...errors}}},async r=>{if(!context)throw new Error('BLOCKED_DEPENDENCY');const bytes=Buffer.from(r.body.contentBase64,'base64');try{return await context.owner.receiveFile(context.actor(r),r.body.input,bytes);}finally{bytes.fill(0);}});
}
