import type {FastifyInstance,FastifyRequest} from 'fastify';
import {Type,type Static,type TSchema} from 'typebox';
import {capabilityCheck,CapabilityId,CapabilityTime,CapabilityStageSchema,CapabilityStoredStageSchema,CapabilityInputSchema,CapabilityPlanSchema,CapabilityVerifySchema,CapabilityReceiveSchema,CapabilityReadSchema,CapabilityHistorySchema,CapabilityExactSchema,CapabilityListSchema,CapabilityWindowSchema,CapabilityDiffSchema,CapabilityRuleSchema,type CapabilityOwner} from '../../modules/care-organization/index.js';
import {CapabilityScopeSchema,ApproveApplyUnitSchema,ApplyUnitSchema} from '../../modules/governance-catalog/index.js';
const closed={additionalProperties:false} as const,Text=Type.String(),End=Type.Union([CapabilityTime,Type.Null()]);
const ErrorSchema=Type.Object({code:Text,message:Text,field:Type.Optional(Text)},closed),errors={400:ErrorSchema,403:ErrorSchema,404:ErrorSchema,409:ErrorSchema,503:ErrorSchema};
const Source=Type.Object({sourceAlias:Text,sourceVersion:Text,sourceSystemId:CapabilityId,sourceRecordedAt:CapabilityTime,recordLocatorEvidence:Type.Object({inputId:CapabilityId,row:Type.Integer()},closed),recordStatus:Text,approvalReference:Text},closed);
const Facts=Type.Object({approvalDepartment:Text,initiallyEnabled:Type.Boolean(),rule:CapabilityRuleSchema,contractVersionId:CapabilityId,verificationBasis:Type.Object({id:CapabilityId,version:Text,digest:Text},closed),dependencies:Type.Unknown(),source:Source},closed);
const Version=Type.Object({id:CapabilityId,number:Text,action:Type.Enum(['GRANT','REVISE','ACTIVATE','SUSPEND','RESUME','END']),validFrom:CapabilityTime,validTo:End,recordedAt:CapabilityTime,facts:Facts,reason:Text,changeId:CapabilityId},closed);
const Read=Type.Object({id:CapabilityId,applicability:CapabilityScopeSchema,head:Text,state:Type.Enum(['ACTIVE','DISABLED','SUSPENDED','ENDED','NOT_EFFECTIVE']),version:Type.Union([Version,Type.Null()]),clinicalReadiness:Type.Literal('NOT_READY')},closed);
const History=Type.Object({id:CapabilityId,scope:Type.Enum(['NORTH','SOUTH']),applicability:CapabilityScopeSchema,versions:Type.Array(Version)},closed);
const Fact=Type.Object({owner:Type.Literal('care-organization/unit-capability'),id:CapabilityId,version:Text,source:Type.Optional(Type.Object({dataset:Type.Literal('ORG16'),row:Type.Integer(),step:Text},closed))},closed);
const Outcome=Type.Union([Type.Object({status:Type.Literal('COMMITTED'),candidateId:CapabilityId,requestId:CapabilityId,facts:Type.Array(Fact),recordedAt:CapabilityTime,responseStatus:Type.Optional(Type.Enum(['DELIVERED','POST_COMMIT_FAILED']))},closed),Type.Object({status:Type.Literal('COMMIT_UNKNOWN'),candidateId:CapabilityId,requestId:CapabilityId},closed)]);
const Issue=Type.Object({row:Type.Integer(),field:Text,code:Text,status:Type.Enum(['FAIL','BLOCKED'])},closed),Candidate=Type.Object({candidateId:CapabilityId},closed);
export interface CapabilityHttpContext {owner:CapabilityOwner;actor:(request:FastifyRequest)=>string}
export function registerUnitCapabilityRoutes(app:FastifyInstance,context?:CapabilityHttpContext){
 const route=<S extends TSchema>(path:string,operationId:string,body:S,response:TSchema,handle:(owner:CapabilityOwner,actor:string,input:Static<S>)=>Promise<unknown>)=>app.post<{Body:Static<S>}>('/api/vnext/unit-capabilities/'+path,{validatorCompiler:({schema})=>input=>{try{capabilityCheck(schema,input);return {value:input};}catch(error){return {error:error instanceof Error?error:new Error('CLOSED_INPUT_REQUIRED')};}},schema:{operationId,body,response:{200:response,...errors}}},r=>{if(!context)throw new Error('BLOCKED_DEPENDENCY');return handle(context.owner,context.actor(r),r.body as Static<S>);});
 route('inputs','stageUnitCapabilityInput',CapabilityStageSchema,Type.Object({inputId:CapabilityId,revisionId:CapabilityId,digest:Text},closed),(o,a,b)=>o.stage(a,b));
 route('inputs/read','readUnitCapabilityInput',CapabilityInputSchema,CapabilityStoredStageSchema,(o,a,b)=>o.readInput(a,b));
 route('verify','verifyUnitCapabilityInput',CapabilityVerifySchema,Type.Object({verificationId:CapabilityId},closed),(o,a,b)=>o.verify(a,b));
 route('preview','previewUnitCapabilityInput',CapabilityInputSchema,Type.Object({decision:Type.Enum(['PASS','BLOCKED']),issues:Type.Array(Issue),changes:Type.Array(Type.Object({action:Text,targetId:Type.Union([CapabilityId,Type.Null()]),validFrom:CapabilityTime,validTo:End},closed))},closed),(o,a,b)=>o.preview(a,b));
 route('plan','planUnitCapabilityInput',CapabilityPlanSchema,Type.Object({candidateId:CapabilityId,digest:Text},closed),(o,a,b)=>o.plan(a,b));
 route('withdraw','withdrawUnitCapabilityInput',CapabilityPlanSchema,Type.Object({inputId:CapabilityId,status:Type.Literal('WITHDRAWN')},closed),(o,a,b)=>o.withdraw(a,b));
 route('review','reviewUnitCapabilityCandidate',Candidate,Type.Unknown(),(o,a,b)=>o.readApplyCandidate(a,b));
 route('approve','approveUnitCapabilityCandidate',ApproveApplyUnitSchema,Type.Unknown(),(o,a,b)=>o.approveApplyUnit(a,b));
 route('apply','applyUnitCapabilityCandidate',ApplyUnitSchema,Outcome,(o,a,b)=>o.applyUnit(a,b));
 route('resume','resumeUnitCapabilityOutcome',ApplyUnitSchema,Type.Union([Outcome,Type.Null()]),(o,a,b)=>o.resumeOutcome(a,b));
 route('reconcile','reconcileUnitCapabilityOutcome',ApplyUnitSchema,Type.Unknown(),(o,a,b)=>o.reconcileCommittedUnit(a,b));
 route('query','getUnitCapabilityAsOf',CapabilityReadSchema,Read,(o,a,b)=>o.read(a,b));
 route('history','getUnitCapabilityHistory',CapabilityHistorySchema,History,(o,a,b)=>o.history(a,b));
 route('exact','getUnitCapabilityVersion',CapabilityExactSchema,Version,(o,a,b)=>o.exact(a,b));
 route('diff','diffUnitCapabilityVersions',CapabilityDiffSchema,Type.Object({id:CapabilityId,before:Version,after:Version},closed),(o,a,b)=>o.diff(a,b));
 route('list','listUnitCapabilities',CapabilityListSchema,Type.Object({items:Type.Array(Read),nextAfterId:Type.Union([CapabilityId,Type.Null()])},closed),(o,a,b)=>o.list(a,b));
 route('evaluate','evaluateUnitCapabilityWindow',CapabilityWindowSchema,Type.Object({mode:Type.Enum(['CURRENT_ADMISSION','HISTORICAL']),recordAsOf:CapabilityTime,status:Type.Enum(['SATISFIED','NOT_SATISFIED']),checks:Type.Array(Type.Object({service:Text,from:CapabilityTime,to:End,status:Type.Enum(['SATISFIED','NOT_SATISFIED']),reason:Text,capabilityId:Type.Union([CapabilityId,Type.Null()]),versionId:Type.Union([CapabilityId,Type.Null()]),acceptedBasis:Type.Unknown(),basis:Type.Unknown()},closed)),clinicalReadiness:Type.Literal('NOT_READY')},closed),(o,a,b)=>o.evaluateWindow(a,b));
 const File=Type.Object({input:CapabilityReceiveSchema,contentBase64:Type.String({minLength:4,maxLength:1398104,pattern:'^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'})},closed);
 app.post<{Body:Static<typeof File>}>('/api/vnext/unit-capabilities/files',{validatorCompiler:({schema})=>input=>{try{capabilityCheck(schema,input);return {value:input};}catch(error){return {error:error instanceof Error?error:new Error('CLOSED_INPUT_REQUIRED')};}},bodyLimit:1500000,schema:{operationId:'receiveUnitCapabilityFile',body:File,response:{200:Type.Object({jobId:CapabilityId,revisionId:CapabilityId,sourceArtifactId:CapabilityId,structuralStatus:Type.Enum(['PARSED','REJECTED']),input:Type.Union([Type.Object({inputId:CapabilityId,revisionId:CapabilityId,digest:Text},closed),Type.Null()]),issues:Type.Array(Issue),validation:Type.Unknown()},closed),...errors}}},async r=>{if(!context)throw new Error('BLOCKED_DEPENDENCY');const bytes=Buffer.from(r.body.contentBase64,'base64');try{return await context.owner.receiveFile(context.actor(r),r.body.input,bytes);}finally{bytes.fill(0);}});
}
