import type {FastifyInstance,FastifyRequest} from 'fastify';
import {Type,type Static,type TSchema} from 'typebox';
import {wardNursingCheck,WardNursingId,WardNursingTime,WardNursingStageSchema,WardNursingDirectStageSchema,WardNursingStoredStageSchema,WardNursingInputSchema,WardNursingPlanSchema,WardNursingVerifySchema,WardNursingReceiveSchema,WardNursingReadSchema,WardNursingHistorySchema,WardNursingExactSchema,WardNursingListSchema,WardNursingWindowSchema,WardNursingDiffSchema,WardNursingEndpointImpactSchema,WardNursingRuleSchema,WardNursingScopeSchema,CoverageScopeSchema,type WardNursingOwner} from '../../modules/care-organization/index.js';
import {ApproveApplyUnitSchema,ApplyUnitSchema} from '../../modules/governance-catalog/index.js';
import {parseStrictJson} from './strict-json.js';
const closed={additionalProperties:false} as const,Text=Type.String(),End=Type.Union([WardNursingTime,Type.Null()]);
const ErrorSchema=Type.Object({code:Text,message:Text,field:Type.Optional(Text)},closed),errors={400:ErrorSchema,403:ErrorSchema,404:ErrorSchema,409:ErrorSchema,413:ErrorSchema,500:ErrorSchema,503:ErrorSchema};
const Source=Type.Object({sourceAlias:Text,sourceVersion:Text,sourceSystemId:WardNursingId,sourceRecordedAt:WardNursingTime,recordLocatorEvidence:Type.Object({inputId:WardNursingId,row:Type.Integer()},closed),recordStatus:Text,approvalReference:Text},closed);
const Facts=Type.Object({coverageScope:CoverageScopeSchema,coverageSource:Text,isPrimary:Type.Boolean(),handoverRuleReference:Type.Union([Text,Type.Null()]),rule:WardNursingRuleSchema,handover:WardNursingVerifySchema.properties.rows.items.properties.handover,contractVersionId:WardNursingId,verificationBasis:Type.Object({id:WardNursingId,version:Text,digest:Text},closed),dependencies:Type.Unknown(),source:Source},closed);
const Version=Type.Object({id:WardNursingId,number:Text,action:Type.Enum(['CREATE','REVISE','END']),validFrom:WardNursingTime,validTo:End,recordedAt:WardNursingTime,facts:Facts,reason:Text,changeId:WardNursingId},closed);
const Read=Type.Object({id:WardNursingId,applicability:WardNursingScopeSchema,head:Text,state:Type.Enum(['ACTIVE','ENDED','NOT_EFFECTIVE']),version:Type.Union([Version,Type.Null()]),handoverStatus:Type.Enum(['NOT_COMPLETED','NOT_REQUIRED','CONFIRMED_SCHEDULED','CONFIRMED_EFFECTIVE']),clinicalReadiness:Type.Literal('NOT_READY')},closed);
const History=Type.Object({id:WardNursingId,scope:Type.Enum(['NORTH','SOUTH']),applicability:WardNursingScopeSchema,versions:Type.Array(Version)},closed);
const Fact=Type.Object({owner:Type.Enum(['care-organization/ward-nursing-coverage','care-organization/ward-nursing-scope']),id:WardNursingId,version:Text,source:Type.Optional(Type.Object({dataset:Type.Literal('ORG11'),row:Type.Integer(),step:Text},closed))},closed);
const Outcome=Type.Union([Type.Object({status:Type.Literal('COMMITTED'),candidateId:WardNursingId,requestId:WardNursingId,facts:Type.Array(Fact),recordedAt:WardNursingTime,responseStatus:Type.Optional(Type.Enum(['DELIVERED','POST_COMMIT_FAILED']))},closed),Type.Object({status:Type.Literal('COMMIT_UNKNOWN'),candidateId:WardNursingId,requestId:WardNursingId},closed)]);
const Issue=Type.Object({row:Type.Integer(),field:Text,code:Text,status:Type.Enum(['FAIL','BLOCKED'])},closed),Candidate=Type.Object({candidateId:WardNursingId},closed);
export interface WardNursingHttpContext {owner:WardNursingOwner;actor:(request:FastifyRequest)=>string}
export function registerWardNursingRoutes(app:FastifyInstance,context?:WardNursingHttpContext){
 app.register(async scoped=>{
  scoped.removeContentTypeParser('application/json');scoped.addContentTypeParser('application/json',{parseAs:'string'},(_request,body,done)=>{try{if(typeof body!=='string')throw new Error('CLOSED_INPUT_REQUIRED');done(null,parseStrictJson(body));}catch{done(new Error('CLOSED_INPUT_REQUIRED'));}});
  registerStrictWardNursingRoutes(scoped,context);
 });
}
function registerStrictWardNursingRoutes(app:FastifyInstance,context?:WardNursingHttpContext){
 const route=<S extends TSchema>(path:string,operationId:string,body:S,response:TSchema,handle:(owner:WardNursingOwner,actor:string,input:Static<S>)=>Promise<unknown>)=>app.post<{Body:Static<S>}>('/api/vnext/ward-nursing-coverages/'+path,{validatorCompiler:({schema})=>input=>{try{wardNursingCheck(schema,input);return {value:input};}catch(error){return {error:error instanceof Error?error:new Error('CLOSED_INPUT_REQUIRED')};}},schema:{operationId,body,response:{200:response,...errors}}},r=>{if(!context)throw new Error('BLOCKED_DEPENDENCY');return handle(context.owner,context.actor(r),r.body as Static<S>);});
 route('inputs','stageWardNursingInput',WardNursingDirectStageSchema,Type.Object({inputId:WardNursingId,revisionId:WardNursingId,digest:Text},closed),(o,a,b)=>o.stage(a,b));
 route('inputs/read','readWardNursingInput',WardNursingInputSchema,WardNursingStoredStageSchema,(o,a,b)=>o.readInput(a,b));
 route('verify','verifyWardNursingInput',WardNursingVerifySchema,Type.Object({verificationId:WardNursingId},closed),(o,a,b)=>o.verify(a,b));
 route('preview','previewWardNursingInput',WardNursingInputSchema,Type.Object({decision:Type.Enum(['PASS','BLOCKED']),issues:Type.Array(Issue),changes:Type.Array(Type.Object({action:Text,targetId:Type.Union([WardNursingId,Type.Null()]),validFrom:WardNursingTime,validTo:End},closed))},closed),(o,a,b)=>o.preview(a,b));
 route('plan','planWardNursingInput',WardNursingPlanSchema,Type.Object({candidateId:WardNursingId,digest:Text},closed),(o,a,b)=>o.plan(a,b));
 route('withdraw','withdrawWardNursingInput',WardNursingPlanSchema,Type.Object({inputId:WardNursingId,status:Type.Literal('WITHDRAWN')},closed),(o,a,b)=>o.withdraw(a,b));
 route('review','reviewWardNursingCandidate',Candidate,Type.Unknown(),(o,a,b)=>o.readApplyCandidate(a,b));
 route('approve','approveWardNursingCandidate',ApproveApplyUnitSchema,Type.Unknown(),(o,a,b)=>o.approveApplyUnit(a,b));
 route('apply','applyWardNursingCandidate',ApplyUnitSchema,Outcome,(o,a,b)=>o.applyUnit(a,b));
 route('resume','resumeWardNursingOutcome',ApplyUnitSchema,Type.Union([Outcome,Type.Null()]),(o,a,b)=>o.resumeOutcome(a,b));
 route('reconcile','reconcileWardNursingOutcome',ApplyUnitSchema,Type.Unknown(),(o,a,b)=>o.reconcileCommittedUnit(a,b));
 route('query','getWardNursingAsOf',WardNursingReadSchema,Read,(o,a,b)=>o.read(a,b));
 route('history','getWardNursingHistory',WardNursingHistorySchema,History,(o,a,b)=>o.history(a,b));
 route('exact','getWardNursingVersion',WardNursingExactSchema,Version,(o,a,b)=>o.exact(a,b));
 route('diff','diffWardNursingVersions',WardNursingDiffSchema,Type.Object({id:WardNursingId,before:Version,after:Version},closed),(o,a,b)=>o.diff(a,b));
 route('list','listWardNursingRelations',WardNursingListSchema,Type.Object({items:Type.Array(Read),nextAfterId:Type.Union([WardNursingId,Type.Null()])},closed),(o,a,b)=>o.list(a,b));
 const Gap=Type.Object({partitionId:Type.Union([WardNursingId,Type.Null()]),from:WardNursingTime,to:End},closed);
 route('evaluate','evaluateWardNursingWindow',WardNursingWindowSchema,Type.Object({mode:Type.Enum(['CURRENT_ADMISSION','HISTORICAL']),recordAsOf:WardNursingTime,handovers:Type.Array(Type.Object({relationId:WardNursingId,businessAt:WardNursingTime,status:Read.properties.handoverStatus,confirmation:Facts.properties.handover},closed)),status:Type.Enum(['SATISFIED','NOT_SATISFIED']),declaredCovered:Type.Boolean(),primaryCovered:Type.Boolean(),currentAdmissionCovered:Type.Boolean(),declaredGaps:Type.Array(Gap),primaryGaps:Type.Array(Gap),currentGaps:Type.Array(Gap),checks:Type.Array(Type.Object({...Gap.properties,status:Type.Enum(['SATISFIED','NOT_SATISFIED']),reason:Text,relationId:Type.Union([WardNursingId,Type.Null()]),acceptedBasis:Type.Unknown(),basis:Type.Unknown()},closed)),clinicalReadiness:Type.Literal('NOT_READY')},closed),(o,a,b)=>o.evaluateWindow(a,b));
 const Period=Type.Object({from:WardNursingTime,to:End},closed);
 route('impacts','evaluateWardNursingEndpointImpacts',WardNursingEndpointImpactSchema,Type.Object({owner:Type.Literal('WARD_NURSING_COVERAGE'),endpoint:Type.Object({kind:Type.Enum(['NURSING','WARD']),id:WardNursingId},closed),validFrom:WardNursingTime,validTo:End,recordAsOf:WardNursingTime,status:Type.Literal('EVALUATED'),clinicalReadiness:Type.Literal('NOT_READY'),items:Type.Array(Type.Object({id:WardNursingId,applicability:WardNursingScopeSchema,original:Type.Object({versionId:WardNursingId,version:Text,period:Period,coverage:CoverageScopeSchema,digest:Text,dependencies:Type.Unknown()},closed),current:Type.Object({versionId:WardNursingId,version:Text,action:Type.Enum(['CREATE','REVISE','END']),period:Period,coverage:CoverageScopeSchema},closed),active:Type.Boolean(),outstanding:Type.Boolean(),affectedSpans:Type.Array(Period),lifecycle:Type.Array(Type.Object({versionId:WardNursingId,action:Type.Enum(['SUSPEND','CLOSE']),from:WardNursingTime,to:Type.Null()},closed)),constraint:Type.Enum(['SATISFIED','UNSATISFIED'])},closed))},closed),(o,a,b)=>o.evaluateEndpointImpacts(a,b));
 const ScopeSet=Type.Object({id:WardNursingId,version:Type.Literal('1'),scope:Type.Enum(['NORTH','SOUTH']),applicability:Type.Omit(WardNursingScopeSchema,['nursing'],closed),partitions:Type.Array(Type.Object({id:WardNursingId,sourceAlias:Text,name:Text,boundary:Text},closed)),validFrom:WardNursingTime,validTo:End,recordedAt:WardNursingTime,sourceAlias:Text,verificationBasis:Type.Unknown(),changeId:WardNursingId},closed);
 route('scope-definitions/read','readWardNursingScopeDefinition',WardNursingHistorySchema,ScopeSet,(o,a,b)=>o.readScopeDefinition(a,b));
 const File=Type.Object({input:WardNursingReceiveSchema,contentBase64:Type.String({minLength:4,maxLength:1398104,pattern:'^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'})},closed);
 app.post<{Body:Static<typeof File>}>('/api/vnext/ward-nursing-coverages/files',{validatorCompiler:({schema})=>input=>{try{wardNursingCheck(schema,input);return {value:input};}catch(error){return {error:error instanceof Error?error:new Error('CLOSED_INPUT_REQUIRED')};}},bodyLimit:1500000,schema:{operationId:'receiveWardNursingFile',body:File,response:{200:Type.Object({jobId:WardNursingId,revisionId:WardNursingId,sourceArtifactId:WardNursingId,structuralStatus:Type.Enum(['PARSED','REJECTED']),input:Type.Union([Type.Object({inputId:WardNursingId,revisionId:WardNursingId,digest:Text},closed),Type.Null()]),issues:Type.Array(Issue),validation:Type.Unknown()},closed),...errors}}},async r=>{if(!context)throw new Error('BLOCKED_DEPENDENCY');const bytes=Buffer.from(r.body.contentBase64,'base64');try{return await context.owner.receiveFile(context.actor(r),r.body.input,bytes);}finally{bytes.fill(0);}});
}
