import type {FastifyInstance,FastifyRequest} from 'fastify';
import {Type,type Static,type TSchema} from 'typebox';
import {Check} from 'typebox/value';
import {openOrganizationEvolutions,DepartmentAssessmentSchema,EvolutionStageSchema,EvolutionStoredStageSchema,EvolutionVerifySchema,EvolutionStoredVerifySchema,EvolutionEventRowSchema,EvolutionImpactSchema,EvolutionReceiveSchema,EvolutionTemplateSchema} from '../../modules/department-master/index.js';
import {ApplyUnitSchema,ApproveApplyUnitSchema,ContractItemSchema} from '../../modules/governance-catalog/index.js';

const closed={additionalProperties:false} as const,Text=Type.String(),Id=Type.String({pattern:'^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$'}),Nullable=Type.Union([Text,Type.Null()]);
const Time=Type.String({pattern:'^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,6})?$'}),Hex=Type.String({pattern:'^[a-f0-9]{64}$'}),Campus=Type.Enum(['NORTH','SOUTH']);
const Input=Type.Object({inputId:Id},closed),Candidate=Type.Object({candidateId:Id},closed),Staged=Type.Object({inputId:Id,revisionId:Id,digest:Hex},closed),Planned=Type.Object({candidateId:Id,digest:Hex},closed);
const Issue=Type.Object({row:Type.Integer(),field:Text,code:Text,status:Type.Enum(['FAIL','BLOCKED']),sheet:Type.Optional(Text)},closed);
const Material=Type.Object({id:Id,digest:Hex},closed),SourcePin=Type.Object({sourceId:Id,versionId:Type.Optional(Type.Union([Id,Type.Null()]))},closed);
const DepartmentFacts=Type.Object({name:Text,shortName:Nullable,orgType:Text,establishedOn:Nullable,description:Nullable,virtual:Type.Boolean(),historicalException:Type.Boolean(),sourceVersion:Text,sourceRecordedAt:Text,sourceSystemId:Id,policyVersionId:Id,verificationId:Id,commandDigest:Type.Optional(Hex),sourcePin:Type.Optional(SourcePin)},closed);
const Version=Type.Object({id:Id,department_id:Id,number:Text,valid_from:Time,valid_to:Type.Union([Time,Type.Null()]),recorded_at:Time,source_row:Type.Integer(),facts:DepartmentFacts,content_digest:Hex,evolution_event_id:Type.Optional(Type.Union([Id,Type.Null()]))},closed);
const History=Type.Object({id:Id,code:Text,versions:Type.Array(Version)},closed);
const Facts=Type.Object({impactAssessment:Type.Optional(Type.Union([Type.Object({id:Id,digest:Hex},closed),Type.Null()])),event:EvolutionEventRowSchema,sourceSystemId:Id,contractVersionId:Id,companionVersions:EvolutionStageSchema.properties.contracts,verificationId:Type.Union([Id,Type.Null()]),impacts:Type.Array(EvolutionImpactSchema),materials:Type.Array(Material),sourcePin:Type.Union([SourcePin,Type.Null()]),sourceArtifact:Type.Union([Material,Type.Null()]),successorFacts:Type.Array(Type.Object({alias:Text,facts:DepartmentFacts,contentDigest:Hex},closed))},closed);
const Relation=Type.Object({id:Id,event_id:Id,source_client_key:Text,source_to_alias:Text,relation_kind:Type.Enum(['SAME_ID_VERSION','SUCCESSION']),from_department_id:Id,from_version_id:Id,to_department_id:Id,to_version_id:Id,fromVersion:Text,toVersion:Text,toSourceRow:Type.Integer(),transfer_scope:Text,context_rule:Text,source_row:Type.Integer(),source_recorded_at:Time,recorded_at:Time},closed);
const Reference=Type.Object({id:Id,version:Text,versionId:Id},closed);
const Query=Type.Object({id:Id,campus:Campus,businessAt:Time,recordAsOf:Type.Optional(Time)},closed);
const Event=Type.Object({id:Id,changeType:Type.Enum(['RENAME','SPLIT','MERGE']),effectiveAt:Time,recordedAt:Time,effective:Type.Boolean(),sourceClientKey:Text,aliasMap:Type.Array(Type.Object({dataset:Type.Enum(['ORG26','ORG27','ORG04']),sourceClientKey:Text,id:Id,version:Text,sourceRow:Type.Integer()},closed)),facts:Facts,predecessors:Type.Array(Reference),successors:Type.Array(Reference),relations:Type.Array(Relation),edges:Type.Array(Type.Object({id:Id,from:Id,to:Id,transferScope:Text,contextRule:Text},closed)),handoff:Type.Literal('NOT_EXECUTED')},closed);
const Outcome=Type.Object({status:Type.Enum(['COMMITTED','COMMIT_UNKNOWN']),candidateId:Id,requestId:Id,facts:Type.Optional(Type.Array(Type.Object({owner:Type.Literal('department-master/organization-evolution'),id:Id,version:Text,source:Type.Object({dataset:Type.Literal('ORG26'),row:Type.Integer(),step:Type.Literal('EVOLUTION')},closed)},closed))),recordedAt:Type.Optional(Time),responseStatus:Type.Optional(Type.Enum(['DELIVERED','POST_COMMIT_FAILED']))},closed);
const Review=Type.Object({assessment:Type.Union([DepartmentAssessmentSchema,Type.Null()]),candidateId:Id,digest:Hex,approvedBy:Nullable,inputCoverage:Type.Literal('COMPLETE'),entries:EvolutionStoredStageSchema,verification:Type.Union([EvolutionStoredVerifySchema,Type.Null()]),issues:Type.Array(Issue),policies:Type.Array(ContractItemSchema),heads:Type.Array(History),materials:Type.Array(Material),sourcePin:Type.Union([SourcePin,Type.Null()]),expandedCount:Type.Integer(),commandFacts:Type.Array(Facts)},closed);
const ErrorSchema=Type.Object({code:Text,message:Text,field:Type.Optional(Text),budget:Type.Optional(Type.Object({kind:Type.Enum(['REFERENCE_COUNT','ASSESSMENT_BYTES']),observed:Type.Integer(),limit:Type.Integer()},closed))},closed),errors={400:ErrorSchema,403:ErrorSchema,404:ErrorSchema,409:ErrorSchema,413:ErrorSchema,500:ErrorSchema,503:ErrorSchema};
export interface OrganizationEvolutionHttpContext {owner:ReturnType<typeof openOrganizationEvolutions>;actor:(request:FastifyRequest)=>string}
export function registerOrganizationEvolutionRoutes(app:FastifyInstance,context?:OrganizationEvolutionHttpContext){
 const route=<S extends TSchema>(path:string,operationId:string,body:S,response:TSchema,handler:(owner:OrganizationEvolutionHttpContext['owner'],actor:string,input:Static<S>)=>Promise<unknown>)=>app.post<{Body:Static<S>}>('/api/vnext/organization-evolutions/'+path,{schema:{operationId,body,response:{200:response,...errors}},...(path==='files'?{bodyLimit:1500000}:{}),preValidation:async request=>{if(!Check(body,request.body))throw new Error('CLOSED_INPUT_REQUIRED');}},r=>{if(!context)throw new Error('BLOCKED_DEPENDENCY');return handler(context.owner,context.actor(r),r.body as Static<S>);});
 route('template','getOrganizationEvolutionTemplate',EvolutionTemplateSchema,Type.Object({filename:Text,bytesBase64:Text,parserPolicy:Type.Literal('STRICT_ORGANIZATION_EVOLUTION_V1'),contractVersions:Type.Array(Type.Object({dataset:Text,contractId:Id,versionId:Id},closed))},closed),(o,a,b)=>o.template(a,b));
 route('files','receiveOrganizationEvolutionFile',Type.Object({metadata:EvolutionReceiveSchema,bytesBase64:Type.String({maxLength:1398104,pattern:'^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'})},closed),Type.Object({jobId:Id,revisionId:Id,sourceArtifactId:Id,structuralStatus:Type.Enum(['PARSED','REJECTED']),issues:Type.Array(Issue),input:Type.Union([Staged,Type.Null()])},closed),async(o,a,b)=>{const bytes=Buffer.from(b.bytesBase64,'base64');try{return await o.receiveFile(a,b.metadata,bytes);}finally{bytes.fill(0);}});
 route('inputs','stageOrganizationEvolution',EvolutionStageSchema,Staged,(o,a,b)=>o.stage(a,b));
 route('inputs/read','readOrganizationEvolutionInput',Input,EvolutionStoredStageSchema,(o,a,b)=>o.readInput(a,b));
 route('preview','previewOrganizationEvolution',Input,Type.Object({input:EvolutionStoredStageSchema,heads:Type.Array(History),verification:Type.Union([EvolutionStoredVerifySchema,Type.Null()]),issues:Type.Array(Issue)},closed),(o,a,b)=>o.preview(a,b));
 route('validate','validateOrganizationEvolution',Input,Type.Object({inputId:Id,digest:Hex,decision:Type.Enum(['PASS','FAIL','BLOCKED']),issues:Type.Array(Issue),expandedCount:Type.Integer(),validationRunId:Type.Union([Id,Type.Null()])},closed),(o,a,b)=>o.validate(a,b));
 route('verify','verifyOrganizationEvolutionEvidence',EvolutionVerifySchema,Type.Object({verificationId:Id},closed),(o,a,b)=>o.verify(a,b));
 route('plan','planOrganizationEvolution',Type.Object({inputId:Id,requestId:Id},closed),Planned,(o,a,b)=>o.plan(a,b));
 route('review','reviewOrganizationEvolution',Candidate,Review,async(o,a,b)=>{const c=await o.readApplyCandidate(a,b),basis=c.unit.basis;return {assessment:basis['assessment']??null,candidateId:c.candidateId,digest:c.digest,approvedBy:c.approvedBy,inputCoverage:'COMPLETE',entries:basis['entries'],verification:basis['verification'],issues:basis['issues'],policies:basis['policies'],heads:basis['heads'],materials:basis['materials'],sourcePin:basis['sourcePin'],expandedCount:basis['expandedCount'],commandFacts:c.unit.commands.map(command=>JSON.parse(command.value['facts']!))};});
 route('approve','approveOrganizationEvolution',ApproveApplyUnitSchema,Type.Object({candidateId:Id,approvedBy:Text},closed),(o,a,b)=>o.approveApplyUnit(a,b));
 route('apply','applyOrganizationEvolution',ApplyUnitSchema,Outcome,(o,a,b)=>o.applyUnit(a,b));
 route('resume','resumeOrganizationEvolution',ApplyUnitSchema,Type.Union([Outcome,Type.Null()]),(o,a,b)=>o.resumeOutcome(a,b));
 route('query','getOrganizationEvolutionAsOf',Query,Event,(o,a,b)=>o.query(a,b));
 route('graph','getOrganizationEvolutionGraph',Query,Type.Object({eventId:Id,effectiveAt:Time,recordedAt:Time,effective:Type.Boolean(),nodes:Type.Array(Type.Object({...Reference.properties,role:Type.Enum(['PREDECESSOR','SUCCESSOR'])},closed)),edges:Event.properties.edges},closed),(o,a,b)=>o.graph(a,b));
 route('history','getDepartmentEvolutionHistory',Type.Object({...Query.properties,after:Type.Optional(Id),limit:Type.Optional(Type.Integer({minimum:1,maximum:100}))},closed),Type.Object({departmentId:Id,events:Type.Array(Event),nextCursor:Type.Union([Id,Type.Null()])},closed),(o,a,b)=>o.history(a,b));
 route('list','listOrganizationEvolutions',Type.Object({campus:Campus,after:Type.Optional(Id),limit:Type.Optional(Type.Integer({minimum:1,maximum:100})),recordAsOf:Type.Optional(Time)},closed),Type.Array(Id),(o,a,b)=>o.list(a,b));
}
