import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { readReceipt,inspect,migrationFiles,checkPrefix } from './lineage.mjs';
const args=process.argv.slice(2);if(args.length>1)throw new Error('CLOSED_COMMAND_REQUIRED');
const receipt=readReceipt(args[0]);const actual=await inspect(receipt);
assert.equal(checkPrefix(migrationFiles(),actual.ledger),migrationFiles().length);
const types=readFileSync('apps/governance-api/src/platform/database/vnext-types.generated.ts','utf8');
assert.deepEqual([...types.matchAll(/^  "([^"]+\.[^"]+)":/gm)].map(match=>match[1]).sort(),actual.tables.slice().sort());
assert.ok(!types.includes('person_master')&&!types.includes('charge_catalog'));
const owner=readFileSync('apps/governance-api/src/modules/governance-catalog/index.ts','utf8');
assert.ok(owner.includes('vnext-types.generated.js'));
assert.ok(!owner.includes('database-types.generated.js'));
const ownership=JSON.parse(readFileSync('db/vnext/table-ownership.json','utf8'));
assert.deepEqual(Object.keys(ownership.schemas).sort(),actual.namespaces);
assert.deepEqual(ownership.businessInstanceSchemas.slice().sort(),actual.namespaces.filter(name=>Object.hasOwn(ownership.domainOwners,name)).sort());
console.log(JSON.stringify({status:'PASS',lineage:'HDIP-MC-VNEXT',tables:actual.tables.length,businessInstanceSchemas:ownership.businessInstanceSchemas.length,legacyDatabase:'LEGACY_OUT_OF_CURRENT_EXECUTION',schemaFingerprint:actual.schemaFingerprint}));
