import { writeFileSync, readFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs';
import {randomUUID} from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';
import { buildCatalogServer } from '../../apps/governance-api/src/composition/build-vnext-catalog.ts';
import {verifyCurrentContract} from './current-contract.mjs';
import {departmentUiContract} from './department-ui-contract.mjs';
const args=process.argv.slice(2);if(args.length>1||args.length===1&&args[0]!=='--check')throw new Error('CLOSED_COMMAND_REQUIRED');
const verify=args[0]==='--check';
const app=await buildCatalogServer();
await app.ready();
const current=app.swagger(),directory=resolve('.runtime/vnext/current-contract',randomUUID());
const uiPath='apps/admin-web/src/vnext/department-forms.generated.ts',ui=departmentUiContract(current);
if(verify){if(!existsSync(uiPath)||readFileSync(uiPath,'utf8')!==ui)throw new Error('CURRENT_UI_CONTRACT_DRIFT');}else writeFileSync(uiPath,ui);
if(verify)mkdirSync(directory,{recursive:true});
const apiPath=verify?resolve(directory,'openapi.json'):'contracts/openapi/vnext-catalog.openapi.json';
const clientPath=verify?resolve(directory,'client.ts'):'packages/generated-api-client/src/vnext-schema.generated.ts';
writeFileSync(apiPath,JSON.stringify(current,null,2)+'\n');
await app.close();
const cache='D:/npm-cache/_npx';
const local=resolve('node_modules/openapi-typescript/bin/cli.js');
const cli=existsSync(local)?local:existsSync(cache)?readdirSync(cache).map(name=>resolve(cache,name,'node_modules/openapi-typescript/bin/cli.js')).find(path=>existsSync(path)):undefined;
if(!cli)throw new Error('LOCAL_OPENAPI_GENERATOR_MISSING');
const result=spawnSync(process.execPath,[cli,apiPath,'-o',clientPath],{stdio:'inherit',windowsHide:true});
if(result.status!==0)process.exitCode=1;
else if(verify)console.log(JSON.stringify(verifyCurrentContract(current,JSON.parse(readFileSync('contracts/openapi/vnext-catalog.openapi.json','utf8')),readFileSync(clientPath,'utf8'),readFileSync('packages/generated-api-client/src/vnext-schema.generated.ts','utf8'))));
