import {randomUUID} from 'node:crypto';
import type {Catalog} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {conditionMappings} from '../../apps/governance-api/src/modules/governance-catalog/validation-sources.generated.js';
/** Explicit synthetic adoption, never an official medical service standard. */
export async function operatingCodeSet(catalog:Catalog,sourceVersionId:string,conditions:readonly string[]=['SRC-COND-007']){
 const cmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'SYNTHETIC_OPERATING',...extra});
 let dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.kind==='DATASET'&&i.code==='ORG03'&&i.status==='PUBLISHED');
 if(!dataset){const d=await catalog.command('maker',cmd('CREATE',{kind:'DATASET',code:'ORG03',values:{name:'DEMO 主体院区关系'},validFrom:'2026-01-01T00:00:00'}));const r=await catalog.command('maker',cmd('SUBMIT',{target:d.id,expectedHead:d.head}));await catalog.command('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:r.head,reviewDigest:r.reviewDigest}));dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.id===d.id)!;}
 const rules=conditions.map(id=>conditionMappings.find(r=>r.id===id)!);
 const hasServiceScope=conditions.includes('SRC-COND-007');
 const definition={ruleVersion:'OPERATING_'+randomUUID().replaceAll('-','').toUpperCase(),templateVersion:'ORG03_MANUAL_CORE_V1',sourceVersionId,businessKey:['legal_campus_rel_id'],fields:[{code:'legal_campus_rel_id',type:'id',required:'R',privacy:'INTERNAL',condition:'ALWAYS',enumValues:[]},{code:'relation_type',type:'text',required:'R',privacy:'INTERNAL',condition:'ALWAYS',enumValues:['OPERATOR','REGISTRANT','MANAGER','BILLING','OTHER']},{code:'is_primary_operator',type:'code',required:'R',privacy:'INTERNAL',condition:'ALWAYS',enumValues:['Y','N']},...rules.map(rule=>({code:rule.field,type:'text',required:'C',privacy:'INTERNAL',condition:'EVALUATED',enumValues:rule.field==='license_scope'?['DEMO_MEDICAL_A','DEMO_MEDICAL_B']:[]}))],rules:rules.map(rule=>({id:rule.id,field:rule.field,text:rule.text,status:'MACHINE',version:rule.version})),references:[{field:'is_primary_operator',target:'enum:yes_no',status:'ADOPTED_CODESET'}],codeSets:[{field:'relation_type',codeSystem:'SYNTHETIC_RELATION_ROLE',version:'DEMO_1',status:'SYNTHETIC_ADOPTED',codes:['OPERATOR','REGISTRANT','MANAGER','BILLING','OTHER'],validFrom:'2026-01-01T00:00:00',validTo:null,sourceVersionId},{field:'is_primary_operator',codeSystem:'SYNTHETIC_YES_NO',version:'DEMO_1',status:'SYNTHETIC_ADOPTED',codes:['Y','N'],validFrom:'2026-01-01T00:00:00',validTo:null,sourceVersionId},...(hasServiceScope?[{field:'license_scope',codeSystem:'SYNTHETIC_OPERATING_SERVICE' as const,version:'DEMO_1',status:'SYNTHETIC_ADOPTED',codes:['DEMO_MEDICAL_A','DEMO_MEDICAL_B'],validFrom:'2026-01-01T00:00:00',validTo:null,sourceVersionId}]:[])]};
 const old=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG03'&&c.profile==='CORE'&&c.definition.templateVersion==='ORG03_MANUAL_CORE_V1');
 const draft=await catalog.contractCommand('maker',cmd(old?'REVISE':'CREATE',{...(old?{target:old.id,expectedHead:old.head}:{profile:'CORE'}),datasetVersionId:dataset.versionId,definition,validFrom:'2026-01-01T00:00:00',validTo:null}));
 const approved=await catalog.contractCommand('reviewer',cmd('APPROVE',{target:draft.id,expectedHead:draft.head,reviewDigest:draft.reviewDigest}));
 const impact=await catalog.contractImpact('reviewer','SYNTHETIC',draft.id,'PUBLISH');
 const published=await catalog.contractCommand('reviewer',cmd('PUBLISH',{target:draft.id,expectedHead:approved.head,reviewDigest:approved.reviewDigest,impactDigest:impact.impactDigest}));
 return {reference:{contractId:published.id,contractVersionId:published.versionId,codeSystem:'SYNTHETIC_OPERATING_SERVICE' as const,version:'DEMO_1',sourceVersionId},published};
}
