import type {Catalog,KeyProviderPort} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {openDepartment,ORGANIZATION_IDENTIFIER_SCHEMES,type OrganizationIdentifierStageInput} from '../../apps/governance-api/src/modules/department-master/index.js';
import {peer,quote,identitySQL} from './lineage.mjs';
export async function persistentOrganizationIdentifierFixture(receipt:{name:string;oid:string},catalog:Catalog,provider:KeyProviderPort,connection:string,requestId:(name:string)=>string,freeze:<T extends Record<string,unknown>>(name:string,value:T)=>T){
 const department=openDepartment(connection,provider);let chosen='';try{for(const id of await department.list('maker',{limit:100}))if((await department.coverage('maker',{id,validFrom:'2026-01-01T00:00:00',validTo:null})).covered){chosen=id;break;}}finally{await department.close();}if(!chosen)throw new Error('P2_01_TARGET_REQUIRED');
 const targetId=freeze('target-selection',{id:chosen}).id,items=(await catalog.read('maker',{scope:'SYNTHETIC'})).items,selected=items.find(i=>i.kind==='SOURCE'&&i.status==='PUBLISHED'&&i.validTo===null);if(!selected)throw new Error('SOURCE_NOT_READY');const source=freeze('source-selection',{id:selected.id,versionId:selected.versionId});
 const cmd=<A extends string>(action:A,name:string,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:requestId(name),reason:'SYNTHETIC_ORG_IDENTIFIER',...extra});
 const existing=items.find(i=>i.kind==='DATASET'&&i.code==='ORG23');let dataset:{id:string;versionId:string};
 if(existing?.status==='PUBLISHED')dataset=existing;else{const draft=await catalog.command('maker',freeze('dataset-draft',existing?cmd('REVISE','dataset-create',{target:existing.id,expectedHead:existing.head,values:{name:'DEMO organization identifiers and aliases'},validFrom:'2026-01-01T00:00:00'}):cmd('CREATE','dataset-create',{kind:'DATASET',code:'ORG23',values:{name:'DEMO organization identifiers and aliases'},validFrom:'2026-01-01T00:00:00'})));const submitted=await catalog.command('maker',freeze('dataset-submit',cmd('SUBMIT','dataset-submit',{target:draft.id,expectedHead:draft.head})));dataset=await catalog.command('reviewer',freeze('dataset-publish',cmd('PUBLISH','dataset-publish',{target:draft.id,expectedHead:submitted.head,reviewDigest:submitted.reviewDigest})));}
 const fields=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.id===dataset.id)!.payload.fields!.map(f=>f.original),enums:Record<string,string[]>={target_type:['LEGAL','CAMPUS','ORG','UNIT','WARD','NURSING','TEAM','LOCATION'],identifier_kind:['HOSPITAL_CODE','SOURCE_CODE','ALIAS','FORMER_NAME','SEARCH_CODE'],is_preferred:['Y','N'],record_status:['DRAFT','REVIEW','ACTIVE','SUSPENDED','RETIRED'],identifier_system:Object.keys(ORGANIZATION_IDENTIFIER_SCHEMES)};
 const definition={templateVersion:'ORG23_CORE_V1',ruleVersion:'ORG23_CORE_V1',sourceVersionId:source.versionId,businessKey:['org_identifier_id'],fields:fields.map(f=>({code:f.code,type:f.type,required:f.required,privacy:f.privacy,condition:f.required==='C'?'EVALUATED':f.required==='R'?'ALWAYS':'OPTIONAL',enumValues:enums[f.code]??[]})),rules:[{id:'ORG_IDENTIFIER_APPROVAL_V1',field:'approval_ref',text:'Source approval never replaces platform approval.',status:'MACHINE',version:'P2_04_V1'}],references:fields.filter(f=>f.ref).map(f=>({field:f.code,target:f.ref,status:'ORGANIZATION_IDENTIFIER_CORE'})),codeSets:Object.entries(enums).map(([field,codes])=>({field,codes,codeSystem:field==='identifier_system'?'SYNTHETIC_ORGANIZATION_PERSONNEL':'SYNTHETIC_'+field.toUpperCase(),version:'DEMO_1',status:'SYNTHETIC_ADOPTED',sourceVersionId:source.versionId,validFrom:'2026-01-01T00:00:00',validTo:null}))};
 const prior=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG23'&&c.profile==='CORE');
 const draft=await catalog.contractCommand('maker',freeze('contract-draft',prior?cmd('REVISE','contract-create',{target:prior.id,expectedHead:prior.head,datasetVersionId:dataset.versionId,validFrom:'2026-01-01T00:00:00',validTo:null,definition}):cmd('CREATE','contract-create',{datasetVersionId:dataset.versionId,profile:'CORE',validFrom:'2026-01-01T00:00:00',validTo:null,definition})));
 const approved=await catalog.contractCommand('reviewer',freeze('contract-approve',cmd('APPROVE','contract-approve',{target:draft.id,expectedHead:draft.head,reviewDigest:draft.reviewDigest}))),impact=await catalog.contractImpact('reviewer','SYNTHETIC',draft.id,'PUBLISH'),contract=await catalog.contractCommand('reviewer',freeze('contract-publish',cmd('PUBLISH','contract-publish',{target:draft.id,expectedHead:approved.head,reviewDigest:approved.reviewDigest,impactDigest:impact.impactDigest})));
 const schemes=Object.keys(ORGANIZATION_IDENTIFIER_SCHEMES);peer(receipt.name,identitySQL(receipt)+` BEGIN;SELECT pg_advisory_xact_lock(901002);INSERT INTO vnext_control.protected_grant SELECT a,${quote(dataset.id)}::uuid,'NORTH','IDENTITY_VERIFY',p FROM unnest(ARRAY['maker','reviewer']) a CROSS JOIN unnest(ARRAY['READ','STORE']) p ON CONFLICT DO NOTHING;INSERT INTO department_master.identifier_access SELECT a,s,'NORTH',p FROM unnest(ARRAY['maker','reviewer']) a CROSS JOIN unnest(ARRAY[${schemes.map(quote).join(',')}]) s CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED']) p ON CONFLICT DO NOTHING;INSERT INTO department_master.identifier_access SELECT 'reviewer',s,'NORTH',p FROM unnest(ARRAY[${schemes.map(quote).join(',')}]) s CROSS JOIN unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;INSERT INTO department_master.mapping_target_access SELECT a,'ORG',${quote(targetId)}::uuid,'NORTH' FROM unnest(ARRAY['maker','reviewer']) a ON CONFLICT DO NOTHING;COMMIT;`);
 const job=await catalog.importJobCommand('maker',freeze('identifier-job',cmd('CREATE','identifier-job',{profile:'CORE',input:{kind:'METADATA_ONLY',declaredSha256:'a'.repeat(64)},contractId:contract.id,contractVersionId:contract.versionId}))),artifact=await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:requestId('identifier-evidence'),jobId:job.id,revisionId:job.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds:7200},Buffer.from('SYNTHETIC organization personnel evidence for persistent alias maintenance'));
 const input:OrganizationIdentifierStageInput={requestId:requestId('identifier-stage'),jobId:job.id,revisionId:job.revisionId,campus:'NORTH',profile:'CORE',entries:[{action:'REGISTER',identifier:null,reason:'DEMO persistent alias registration',evidenceId:artifact.artifactId,row:{org_identifier_id:'PERSISTENT_DEMO_ALIAS',target_type:'ORG',target_id:targetId,identifier_kind:'ALIAS',identifier_system:'SYNTHETIC_ALIAS',identifier_value:'DEMO persistent organization alias',language:'zh',is_preferred:'N',version_no:'1',valid_from:'2026-01-01T00:00:00',valid_to:'',record_status:'ACTIVE',source_system_id:source.id,source_record_id:'DEMO/ORG23/2',approval_ref:'DEMO_APPROVAL',recorded_at:'2026-01-02T00:00:00'}}]};
 return {input:freeze('identifier-stage-input',input),artifact,binding:{database:receipt.name,databaseOid:receipt.oid,schemes,campus:'NORTH',targetType:'ORG',targetId}};
}
