import {readFileSync} from 'node:fs';
import {randomUUID,createHmac} from 'node:crypto';
import {Pool} from 'pg';
import {beforeAll,afterAll,test,expect} from 'vitest';
import {openCatalog,canonicalPlan,planBinding,type Catalog} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import type {UsageTypeCommand,UsageTypeItem} from '../../apps/governance-api/src/modules/location-master/usage-type-contracts.js';
import {buildCatalogServer} from '../../apps/governance-api/src/composition/build-vnext-catalog.js';
import {actor} from '../../apps/governance-api/src/platform/fastify/vnext-catalog-routes.js';
import {createLocationUsageTypeClient} from '../../packages/generated-api-client/src/index.js';
import {locationUseFixture} from './p3-07-fixture.js';
import {validationKeys} from './p3-07-validation-keys.mjs';
import {peer,quote} from './lineage.mjs';
import type {LocationUseFixture} from './p3-07-validation-helpers.js';

const connection=process.env['VNEXT_VALIDATION_OWNER_URL']!,receipt=JSON.parse(readFileSync(process.env['VNEXT_TEST_RECEIPT']!,'utf8'));
let catalog:Catalog,f:LocationUseFixture,app:Awaited<ReturnType<typeof buildCatalogServer>>,url:string;
beforeAll(async()=>{const provider=validationKeys(receipt),pool=new Pool({connectionString:connection,max:1});try{catalog=await openCatalog(connection,provider);const role=(await pool.query('select current_user r')).rows[0]!.r;f=await locationUseFixture(receipt,role,catalog,provider,connection,process.env['VNEXT_P3_07_UPGRADED']==='1');const contexts:Parameters<typeof buildCatalogServer>=[catalog,'CONTROL_PLANE'];contexts[24]={owner:f.owner,usageTypes:f.dictionary,actor:r=>actor(r.headers)};app=await buildCatalogServer(...contexts);url=await app.listen({host:'127.0.0.1',port:0});}finally{await pool.end();}});
afterAll(async()=>{await app?.close();await f?.close();await catalog?.close();});

async function southMaterial(retentionSeconds=7200){const job=await f.newJob(),bytes=Buffer.from('TEST POLICY ONLY actual SOUTH dictionary evidence '+randomUUID()),artifact=await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),jobId:job.id,revisionId:job.revisionId,campus:'SOUTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds},bytes),read=await catalog.authorizeSensitiveRead('maker',{scope:'SYNTHETIC',requestId:randomUUID(),artifactId:artifact.artifactId,campus:'SOUTH',purpose:'IDENTITY_VERIFY'});try{expect(Buffer.from(read)).toEqual(bytes);}finally{read.fill(0);}return {artifact,bytes};}
const create=(evidenceId:string):Extract<UsageTypeCommand,{action:'CREATE'}>=>({action:'CREATE',requestId:randomUUID(),reason:'TEST whole hospital purpose with actual evidence scope',code:'REVIEW_SOUTH_'+randomUUID().replaceAll('-','').toUpperCase(),name:'TEST South office purpose',meaning:'TEST stable whole hospital office meaning',description:null,validFrom:'2026-01-01T00:00:00',validTo:null,sourceId:f.source.id,sourceVersionId:f.source.versionId,evidenceId});
const verify=(draft:UsageTypeItem,evidenceId=draft.evidenceId):Extract<UsageTypeCommand,{action:'VERIFY'}>=>({action:'VERIFY',requestId:randomUUID(),reason:'TEST independent actual evidence verification',target:draft.id,expectedHead:draft.head,versionId:draft.versionId,reviewDigest:draft.reviewDigest,evidenceId,meaningAccepted:true});
const approve=(draft:UsageTypeItem):Extract<UsageTypeCommand,{action:'APPROVE'}>=>({action:'APPROVE',requestId:randomUUID(),reason:'TEST independent whole hospital approval',target:draft.id,expectedHead:draft.head,versionId:draft.versionId,reviewDigest:draft.reviewDigest});
async function signedCommand(command:UsageTypeCommand,bytes:Buffer,actorCode='maker'){
 const provider=validationKeys(receipt),pool=new Pool({connectionString:connection,max:1}),client=await pool.connect(),key=Buffer.from(planBinding(provider,'LOCATION_USE_SQL_AUTHORITY_V1',{}),'hex');
 try{const identity=(await client.query('select current_user role,r.rolsuper,r.rolcreatedb,r.rolcreaterole,r.rolbypassrls,has_table_privilege(current_user,\'location_master.usage_type\',\'INSERT\') fact_insert from pg_roles r where r.rolname=current_user')).rows[0]!;expect(identity.role).toMatch(/^hdi_validation_[a-f0-9]{16}$/);expect(identity.rolsuper||identity.rolcreatedb||identity.rolcreaterole||identity.rolbypassrls||identity.fact_insert).toBe(false);await client.query('BEGIN');const transaction=(await client.query('select pg_current_xact_id()::text id')).rows[0]!.id,materials=[{id:'evidenceId' in command?command.evidenceId:'',digest:planBinding(provider,'LOCATION_USE_MATERIAL_V1',bytes.toString('base64'))}],ticket=canonicalPlan({actor:actorCode,transaction,command,materialDigest:planBinding(provider,'LOCATION_USAGE_TYPE_MATERIALS_V1',materials)});return await client.query('select location_master.usage_type_command($1,$2) r',[ticket,createHmac('sha256',key).update(ticket).digest('hex')]).then(()=>({code:'AUTHORIZED',identity}),error=>({code:String(error.message),identity}));}finally{await client.query('ROLLBACK');client.release();await pool.end();key.fill(0);}
}

test('R5: actual SOUTH material supports whole hospital dictionary CREATE, independent approval, material viewing and accurate replay',async()=>{
 const {artifact,bytes}=await southMaterial(10),command=create(artifact.artifactId),maker=createLocationUsageTypeClient(url,'maker'),reviewer=createLocationUsageTypeClient(url,'reviewer');
 const material=await f.dictionary.readMaterial('maker',{id:artifact.artifactId,sourceVersionId:f.source.versionId}).then(value=>({value,error:undefined}),error=>({value:undefined,error:String(error.message)}));expect.soft(material.error).toBeUndefined();if(material.value)expect(Buffer.from(material.value.bytesBase64,'base64')).toEqual(bytes);const materialHttp=await maker.readMaterial({id:artifact.artifactId,sourceVersionId:f.source.versionId});expect.soft(materialHttp.response.status,JSON.stringify(materialHttp.error)).toBe(200);if(materialHttp.data)expect(Buffer.from(materialHttp.data.bytesBase64,'base64')).toEqual(bytes);
 const owner=await f.dictionary.command('maker',command).then(value=>({value,error:undefined}),error=>({value:undefined,error:String(error.message)}));expect.soft(owner.error).toBeUndefined();const http=await maker.command(command);expect.soft(http.response.status,JSON.stringify(http.error)).toBe(200);console.log(JSON.stringify({gate:'P3_07_REVIEW3_SOUTH_PUBLIC_MATERIAL',protectedSouthRead:'PASS',ownerMaterial:material.error??'PASS',httpMaterialStatus:materialHttp.response.status,ownerCreate:owner.error??'PASS',httpCreateStatus:http.response.status,httpCode:http.error?.code??null,wholeHospital:true}));
 if(!owner.value||!http.data)return;expect(http.data).toEqual(owner.value);const draft=owner.value;expect((await reviewer.command(verify(draft))).response.status).toBe(200);const approved=await reviewer.command(approve(draft));expect(approved.response.status,JSON.stringify(approved.error)).toBe(200);expect(approved.data).toMatchObject({id:draft.id,status:'APPROVED',evidenceId:artifact.artifactId});expect((await maker.read({id:draft.id})).data?.status).toBe('APPROVED');expect((await maker.history({id:draft.id})).data).toHaveLength(1);expect((await maker.command(command)).data).toEqual(draft);
 const predicate=`actor_code='maker' AND dataset_id=${quote(f.dataset!.id)}::uuid AND campus='SOUTH' AND purpose='IDENTITY_VERIFY' AND permission='READ'`,grants=JSON.parse(peer(receipt.name,`SELECT coalesce(jsonb_agg(g),'[]')::text FROM vnext_control.protected_grant g WHERE ${predicate};`));expect(grants.length).toBeGreaterThan(0);peer(receipt.name,`DELETE FROM vnext_control.protected_grant WHERE ${predicate};`);
 try{await expect(f.dictionary.readMaterial('maker',{id:artifact.artifactId,sourceVersionId:f.source.versionId})).rejects.toThrow('ACCESS_DENIED');await expect(f.dictionary.read('maker',{id:draft.id})).rejects.toThrow('ACCESS_DENIED');await expect(f.dictionary.history('maker',{id:draft.id})).rejects.toThrow('ACCESS_DENIED');await expect(f.dictionary.command('maker',command)).rejects.toThrow('ACCESS_DENIED');expect((await maker.readMaterial({id:artifact.artifactId,sourceVersionId:f.source.versionId})).response.status).toBe(403);expect((await maker.command(command)).response.status).toBe(403);expect(await f.dictionary.readMaterial('maker',{id:f.artifact.artifactId,sourceVersionId:f.source.versionId})).toHaveProperty('bytesBase64');}finally{peer(receipt.name,`INSERT INTO vnext_control.protected_grant SELECT * FROM jsonb_populate_recordset(NULL::vnext_control.protected_grant,${quote(JSON.stringify(grants))}::jsonb) ON CONFLICT DO NOTHING;`);}
 expect((await maker.command(command)).data).toEqual(draft);
 const pool=new Pool({connectionString:connection,max:1});let remaining:number;try{remaining=(await pool.query<{ms:number}>('select greatest(0,ceil(extract(epoch from ($1::timestamp-timezone(\'Asia/Shanghai\',clock_timestamp()))) * 1000))::integer ms',[artifact.expiresAt])).rows[0]!.ms;}finally{await pool.end();}await new Promise(resolve=>setTimeout(resolve,remaining+30));
 peer(receipt.name,`INSERT INTO vnext_control.protected_grant VALUES('maker',${quote(f.dataset!.id)}::uuid,'SOUTH','IDENTITY_VERIFY','PURGE') ON CONFLICT DO NOTHING;`);
 await catalog.purgeOwnedExpiredArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),artifactId:artifact.artifactId,campus:'SOUTH',purpose:'IDENTITY_VERIFY'});
 await expect(f.dictionary.readMaterial('maker',{id:artifact.artifactId,sourceVersionId:f.source.versionId})).rejects.toThrow('PAYLOAD_UNAVAILABLE');expect((await maker.readMaterial({id:artifact.artifactId,sourceVersionId:f.source.versionId})).error?.code).toBe('PAYLOAD_UNAVAILABLE');expect((await maker.read({id:draft.id})).data?.status).toBe('APPROVED');expect((await maker.history({id:draft.id})).data).toHaveLength(1);expect((await maker.command(command)).data).toEqual(draft);
 console.log(JSON.stringify({gate:'P3_07_REVIEW3_SOUTH_PERMISSION_RETENTION',beforeExpirySouthReadRevoked:'DENIED',northReadPreserved:'PASS',expiredPayloadPurged:true,byteViewer:'PAYLOAD_UNAVAILABLE',metadataHistory:'PASS',accurateReplay:'PASS'}));
});

test('R5: NORTH content and independent SOUTH verification use each actual material scope without changing the purpose scope',async()=>{
 const {artifact,bytes}=await southMaterial(),north=create(f.artifact.artifactId),draft=await f.dictionary.command('maker',north);expect((await f.dictionary.readMaterial('maker',{id:f.artifact.artifactId,sourceVersionId:f.source.versionId})).bytesBase64).toEqual(expect.any(String));
 const review=verify(draft,artifact.artifactId),owner=await f.dictionary.command('reviewer',review).then(value=>({value,error:undefined}),error=>({value:undefined,error:String(error.message)}));expect.soft(owner.error).toBeUndefined();const http=await createLocationUsageTypeClient(url,'reviewer').command(review);expect.soft(http.response.status,JSON.stringify(http.error)).toBe(200);console.log(JSON.stringify({gate:'P3_07_REVIEW3_MIXED_EVIDENCE_SCOPES',northCreate:'PASS',protectedSouthRead:'PASS',ownerVerify:owner.error??'PASS',httpVerifyStatus:http.response.status,httpCode:http.error?.code??null}));if(!owner.value||!http.data)return;
 expect(http.data).toEqual(owner.value);const approved=await f.dictionary.command('reviewer',approve(draft));expect(approved).toMatchObject({id:draft.id,status:'APPROVED',evidenceId:f.artifact.artifactId,verification:{evidenceId:artifact.artifactId}});expect(Buffer.from((await f.dictionary.readMaterial('maker',{id:artifact.artifactId,sourceVersionId:f.source.versionId})).bytesBase64,'base64')).toEqual(bytes);
 const predicate=`actor_code='maker' AND dataset_id=${quote(f.dataset!.id)}::uuid AND campus='SOUTH' AND purpose='IDENTITY_VERIFY' AND permission='READ'`,grants=JSON.parse(peer(receipt.name,`SELECT coalesce(jsonb_agg(g),'[]')::text FROM vnext_control.protected_grant g WHERE ${predicate};`));peer(receipt.name,`DELETE FROM vnext_control.protected_grant WHERE ${predicate};`);try{await expect(f.dictionary.read('maker',{id:draft.id})).rejects.toThrow('ACCESS_DENIED');await expect(f.dictionary.history('maker',{id:draft.id})).rejects.toThrow('ACCESS_DENIED');await expect(f.dictionary.command('maker',north)).rejects.toThrow('ACCESS_DENIED');expect(await f.dictionary.readMaterial('maker',{id:f.artifact.artifactId,sourceVersionId:f.source.versionId})).toHaveProperty('bytesBase64');}finally{peer(receipt.name,`INSERT INTO vnext_control.protected_grant SELECT * FROM jsonb_populate_recordset(NULL::vnext_control.protected_grant,${quote(JSON.stringify(grants))}::jsonb) ON CONFLICT DO NOTHING;`);}
});

test('R5: authentic restricted SOUTH SQL enforces actual campus grants, exact source pin and current actor',async()=>{
 const {artifact,bytes}=await southMaterial(),command=create(artifact.artifactId),signed=await signedCommand(command,bytes);expect.soft(signed.code).toBe('AUTHORIZED');expect((await f.dictionary.list('maker')).items.some(item=>item.code===command.code)).toBe(false);
 await expect(catalog.authorizeSensitiveRead('maker',{scope:'SYNTHETIC',requestId:randomUUID(),artifactId:artifact.artifactId,campus:'NORTH',purpose:'IDENTITY_VERIFY'})).rejects.toThrow();await expect(f.dictionary.readMaterial('outsider',{id:artifact.artifactId,sourceVersionId:f.source.versionId})).rejects.toThrow('ACCESS_DENIED');expect((await createLocationUsageTypeClient(url,'outsider').readMaterial({id:artifact.artifactId,sourceVersionId:f.source.versionId})).response.status).toBe(403);expect((await signedCommand({...command,requestId:randomUUID(),code:'OUTSIDER_'+randomUUID().replaceAll('-','').toUpperCase()},bytes,'outsider')).code).toBe('ACCESS_DENIED');
 const sourceCmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'TEST_REVIEW_SOURCE_PIN',...extra}),raw=await catalog.command('maker',sourceCmd('CREATE',{kind:'SOURCE',code:'TEST_REVIEW_SOURCE_'+randomUUID().replaceAll('-','').toUpperCase(),values:{name:'TEST mismatched evidence source',environment:'SYNTHETIC',sourceKind:'MANUAL',deploymentScope:'SYNTHETIC_ALL',businessOwnerRole:'TEST',technicalRole:'TEST',sourceEvidence:f.source.id},validFrom:'2026-01-01T00:00:00',validTo:null})),submitted=await catalog.command('maker',sourceCmd('SUBMIT',{target:raw.id,expectedHead:raw.head})),other=await catalog.command('reviewer',sourceCmd('PUBLISH',{target:raw.id,expectedHead:submitted.head,reviewDigest:submitted.reviewDigest}));await expect(f.dictionary.readMaterial('maker',{id:artifact.artifactId,sourceVersionId:other.versionId})).rejects.toThrow();expect((await createLocationUsageTypeClient(url,'maker').readMaterial({id:artifact.artifactId,sourceVersionId:other.versionId})).response.status).not.toBe(200);expect((await signedCommand({...command,requestId:randomUUID(),sourceId:other.id,sourceVersionId:other.versionId},bytes)).code).not.toBe('AUTHORIZED');
 console.log(JSON.stringify({gate:'P3_07_REVIEW3_SOUTH_RESTRICTED_SQL',positive:signed.code,sqlIdentity:signed.identity,protectedSouthRead:'PASS',wrongExplicitCampus:'DENIED',wrongSourcePin:'DENIED',outsider:'ACCESS_DENIED',rolledBack:true}));
});
