import {randomUUID} from 'node:crypto';
import {openUnitCapabilities,ORG16_FIELDS,type CapabilityEntry,type CapabilityRow,type CapabilityStage,type CapabilityVerification} from '../../apps/governance-api/src/modules/care-organization/index.js';
import {openParameterValues,CAPABILITY_TYPES,CAPABILITY_CARE_SETTINGS,type Catalog,type KeyProviderPort,type CapabilityScope} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {unitCapabilityUpstreamPorts} from '../../apps/governance-api/src/composition/unit-capability-dependencies.js';
import {businessUnitFixture} from './p3-01-fixture.js';
import {provisionUnitCapability} from './p3-08-provisioning.mjs';
import {peer,quote} from './lineage.mjs';
export async function capabilityFixture(receipt:{name:string;oid:string},role:string,catalog:Catalog,provider:KeyProviderPort,connection:string,supplied?:Awaited<ReturnType<typeof businessUnitFixture>>,persistent=false,sourceOverride?:{id:string;versionId:string;validFrom:string;validTo:string|null}){
 const base=supplied??await businessUnitFixture(receipt,role,catalog,provider,connection,persistent),cmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'TEST_CAPABILITY',...extra});
 const source=sourceOverride??base.dep.source,contractFrom=sourceOverride?.validFrom??'2026-01-01T00:00:00',contractTo=sourceOverride?.validTo??null;if(sourceOverride&&!(await catalog.read('maker',{scope:'SYNTHETIC'})).items.some(i=>i.kind==='SOURCE'&&i.status==='PUBLISHED'&&i.id===source.id&&i.versionId===source.versionId))throw new Error('SOURCE_NOT_READY');
 let dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.kind==='DATASET'&&i.code==='ORG16'&&i.status==='PUBLISHED');
 if(!dataset){const d=await catalog.command('maker',cmd('CREATE',{kind:'DATASET',code:'ORG16',values:{name:'TEST POLICY ONLY 单元业务能力'},validFrom:'2026-01-01T00:00:00'})),s=await catalog.command('maker',cmd('SUBMIT',{target:d.id,expectedHead:d.head}));await catalog.command('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:s.head,reviewDigest:s.reviewDigest}));dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.id===d.id)!;}
 const fields=dataset.payload.fields!.map(f=>f.original);if(fields.length!==ORG16_FIELDS.length)throw new Error('FULL_FIELD_OMISSION');
 const enums:Record<string,string[]>={capability_type:[...CAPABILITY_TYPES],care_setting:[...CAPABILITY_CARE_SETTINGS],enabled:['Y','N'],record_status:['DRAFT','REVIEW','ACTIVE','SUSPENDED','RETIRED']};
 const definition={ruleVersion:sourceOverride?'ORG16_CORE_SRC_'+source.versionId.replaceAll('-','').toUpperCase():'ORG16_CORE_V1',templateVersion:'ORG16_CORE_V1',sourceVersionId:source.versionId,businessKey:['capability_id'],fields:fields.map(f=>({code:f.code,type:f.type,required:f.required,privacy:f.privacy,condition:f.required==='C'?'EVALUATED':f.required==='R'?'ALWAYS':'OPTIONAL',enumValues:enums[f.code]??[]})),references:fields.filter(f=>f.ref).map(f=>({field:f.code,target:f.ref,status:'CAPABILITY_CORE'})),rules:[{id:'CAPABILITY_EMPTY_END_V1',field:'valid_to',text:'CSV/XLSX blank valid_to is an explicit open end; JSON requires native null.',status:'MACHINE',version:'P3_08_EMPTY_END_V1'},{id:'CAPABILITY_SOURCE_PLUS08_V1',field:'valid_from',text:'Explicit source +08:00 to Asia/Shanghai local; retain original timestamps.',status:'MACHINE',version:'P3_08_TIME_V1'},{id:'CAPABILITY_APPROVAL_V1',field:'approval_ref',text:'Source approval never replaces platform approval.',status:'MACHINE',version:'P3_08_V1'},{id:'CAPABILITY_RULE_CONFIRMATION_V1',field:'rule_ref',text:'Empty rule requires independent no-additional-rule confirmation.',status:'MACHINE',version:'P3_08_V1'}],codeSets:Object.entries(enums).map(([field,codes])=>({field,codes,codeSystem:'SYNTHETIC_'+field.toUpperCase(),version:'TEST_POLICY_ONLY_1',status:'SYNTHETIC_ADOPTED',sourceVersionId:source.versionId,validFrom:contractFrom,validTo:contractTo}))};
 let contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG16'&&c.profile==='CORE'&&c.status==='PUBLISHED');
 if(!contract||(contract.definition.templateVersion!=='ORG16_CORE_V1'||contract.definition.sourceVersionId!==source.versionId||!contract.definition.rules.some(r=>r.id==='CAPABILITY_EMPTY_END_V1'))){const d=await catalog.contractCommand('maker',contract?cmd('REVISE',{target:contract.id,expectedHead:contract.head,datasetVersionId:dataset.versionId,definition,validFrom:contractFrom,validTo:contractTo}):cmd('CREATE',{datasetVersionId:dataset.versionId,profile:'CORE',definition,validFrom:contractFrom,validTo:contractTo})),preImpact=contract?await catalog.contractImpact('reviewer','SYNTHETIC',d.id,'PUBLISH'):undefined,a=await catalog.contractCommand('reviewer',cmd('APPROVE',{target:d.id,expectedHead:d.head,reviewDigest:d.reviewDigest,...(preImpact?{impactDigest:preImpact.impactDigest}:{})})),impact=contract?await catalog.contractImpact('reviewer','SYNTHETIC',d.id,'PUBLISH'):undefined;await catalog.contractCommand('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:a.head,reviewDigest:a.reviewDigest,...(impact?{impactDigest:impact.impactDigest}:{})}));contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.id===d.id)!;}
 const newJob=()=>catalog.importJobCommand('maker',cmd('CREATE',{profile:'CORE',contractId:contract!.id,contractVersionId:contract!.versionId,input:{kind:'METADATA_ONLY',declaredSha256:'a'.repeat(64)}}));
 peer(receipt.name,`INSERT INTO vnext_control.protected_grant SELECT a,${quote(dataset.id)}::uuid,s,'IDENTITY_VERIFY',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['NORTH','SOUTH']) s CROSS JOIN unnest(ARRAY['READ','STORE']) p ON CONFLICT DO NOTHING;`);
 const j=await newJob(),artifact=await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds:7200},Buffer.from('TEST POLICY ONLY independently verified capability and no additional rule'));
 provisionUnitCapability(receipt,role,provider);const values=openParameterValues(connection),owner=openUnitCapabilities(connection,provider,unitCapabilityUpstreamPorts(base.owner,values));
 const grant=(s:CapabilityScope)=>peer(receipt.name,`INSERT INTO care_organization.capability_access SELECT a,${quote(s.campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED']) p ON CONFLICT DO NOTHING;INSERT INTO care_organization.capability_access SELECT 'reviewer',${quote(s.campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;`);
 const endpoint=async():Promise<CapabilityScope>=>{const b=await base.endpoint(await base.newDepartment()),u=await base.apply(await base.input([base.entry(b)])),s:CapabilityScope={unit:{owner:'care-organization/unit',id:u.facts[0]!.id},campus:b.campus,subject:b.subject,services:b.services,capabilityType:'ORDER',careSetting:'OUTPATIENT'};grant(s);return s;};
 const row=(s:CapabilityScope):CapabilityRow=>({capability_id:randomUUID(),unit_id:s.unit.id,capability_type:s.capabilityType,care_setting:s.careSetting,enabled:'Y',rule_ref:null,approval_dept:'TEST 医务部',version_no:9,valid_from:contractFrom,valid_to:contractTo,record_status:'ACTIVE',source_system_id:source.id,source_record_id:'TEST/ORG16/2',approval_ref:'TEST_POLICY_ONLY',recorded_at:'2026-01-02T00:00:00'});
 const entry=(s:CapabilityScope):CapabilityEntry=>({action:'GRANT',applicability:s,rule:{kind:'NO_ADDITIONAL_RULE'},row:row(s),reason:'TEST independently granted capability',evidenceId:artifact.artifactId});
 const input=async(entries:CapabilityEntry[]):Promise<CapabilityStage>=>{const j=await newJob();return {requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',profile:'CORE',timePolicy:'LOCAL',entries};};
 const verification=(v:CapabilityStage,i:{inputId:string;digest:string}):CapabilityVerification=>({requestId:randomUUID(),inputId:i.inputId,inputDigest:i.digest,reason:'TEST independent capability and scope review',policyVersion:'ORG16_CORE_V1',rows:v.entries.map((e,index)=>({row:index+1,evidenceId:artifact.artifactId,classificationAccepted:true,scopeAccepted:true,ruleConfirmed:true,rule:e.rule,validFrom:e.row.valid_from,validTo:e.row.valid_to||null}))});
 const prepare=async(v:CapabilityStage)=>{const i=await owner.stage('maker',v);await owner.verify('reviewer',verification(v,i));const preview=await owner.preview('maker',{inputId:i.inputId});if(preview.decision!=='PASS')throw new Error(preview.issues.map(i=>i.code).join(','));const requestId=randomUUID(),c=await owner.plan('maker',{inputId:i.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:c.candidateId});await owner.approveApplyUnit('reviewer',c);return {candidateId:c.candidateId,requestId};};
 const apply=async(v:CapabilityStage)=>{const result=await owner.applyUnit('maker',await prepare(v));if(result.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');return result;};
 return {base,owner,values,contract,dataset,artifact,endpoint,grant,row,entry,input,newJob,verification,prepare,apply,close:async()=>{await owner.close();await values.close();if(!supplied)await base.close();}};
}
