import {openDepartmentLifecycle,openOrganizationEvolutions} from '../../apps/governance-api/src/modules/department-master/index.js';
import {withCareOrganizationImpacts} from '../../apps/governance-api/src/composition/nursing-unit-dependencies.js';
import {organizationMappingFixture} from './p2-03-fixture.js';
import {evolutionFixture} from './p2-05-fixture.js';
import {openCampus} from '../../apps/governance-api/src/modules/organization-master/index.js';
import {assertUnitCapabilityProvisioned} from './p3-08-provisioning.mjs';
import {buildCatalogServer} from '../../apps/governance-api/src/composition/build-vnext-catalog.js';
import {actor} from '../../apps/governance-api/src/platform/fastify/vnext-catalog-routes.js';
import {createUnitCapabilityClient,createParameterValueClient,createVNextCatalogClient} from '../../packages/generated-api-client/src/index.js';
import {ORG16_FIELDS,type CapabilityEntry} from '../../apps/governance-api/src/modules/care-organization/index.js';
import {organizationWorkbook} from './organization-workbook-fixture.js';
import {beforeAll,afterAll,test,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {randomUUID,createHmac} from 'node:crypto';
import {Pool,Client,type QueryConfig} from 'pg';
import {openCatalog,openParameterValues,canonicalPlan,planBinding,type Catalog,type ParameterValueOwner,type CapabilityScope} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {businessUnitFixture} from './p3-01-fixture.js';
import {validationKeys} from './p3-08-validation-keys.mjs';
import {peer,quote} from './lineage.mjs';
import {capabilityFixture} from './p3-08-fixture.js';
const connection=process.env['VNEXT_VALIDATION_OWNER_URL']!,receipt=JSON.parse(readFileSync(process.env['VNEXT_TEST_RECEIPT']!,'utf8'));
let catalog:Catalog,values:ParameterValueOwner,f:Awaited<ReturnType<typeof businessUnitFixture>>,scope:CapabilityScope;
let capabilities:Awaited<ReturnType<typeof capabilityFixture>>;
beforeAll(async()=>{const provider=validationKeys(receipt),pool=new Pool({connectionString:connection,max:1});try{const role=(await pool.query('select current_user r')).rows[0].r;catalog=await openCatalog(connection,provider);f=await businessUnitFixture(receipt,role,catalog,provider,connection,process.env['VNEXT_P3_08_UPGRADED']==='1');const binding=await f.endpoint(await f.newDepartment()),unit=await f.apply(await f.input([f.entry(binding)]));scope={unit:{owner:'care-organization/unit',id:unit.facts[0]!.id},campus:binding.campus,subject:binding.subject,services:binding.services,capabilityType:'ORDER',careSetting:'OUTPATIENT'};values=openParameterValues(connection);capabilities=await capabilityFixture(receipt,role,catalog,provider,connection,f);capabilities.grant(scope);peer(receipt.name,`GRANT EXECUTE ON FUNCTION governance_catalog.parameter_value_command(text,jsonb),governance_catalog.parameter_value_read(text,jsonb,boolean),governance_catalog.parameter_value_evaluate(text,jsonb),governance_catalog.parameter_value_access(text,uuid,text) TO ${role};`);}finally{await pool.end();}});
afterAll(async()=>{await capabilities?.close();await values?.close();await f?.close();await catalog?.close();});

async function definition(type:'TEXT'|'INTEGER'|'DECIMAL'|'BOOLEAN'){
 const d=await catalog.parameterCommand('maker',{action:'CREATE',scope:'SYNTHETIC',requestId:randomUUID(),reason:'TEST_PARAMETER',systemVersionId:f.dep.source.versionId,parameterKey:'CAP_'+randomUUID().replaceAll('-','').toUpperCase(),group:'CARE',campus:'SYNTHETIC_ALL',definition:{kind:'VALUE_SCHEMA_V1',valueType:type,enumValues:[],description:'TEST POLICY ONLY approved scoped value'},validFrom:'2026-01-01T00:00:00',validTo:null});
 await catalog.parameterCommand('reviewer',{action:'APPROVE',scope:'SYNTHETIC',requestId:randomUUID(),reason:'TEST_PARAMETER',target:d.id,versionId:d.versionId,reviewDigest:d.reviewDigest});return d;
}
test('approved scoped parameter value is distinct from its definition and is read without losing its value',async()=>{
 const d=await definition('BOOLEAN'),request={action:'CREATE' as const,requestId:randomUUID(),reason:'TEST scoped BOOLEAN gate',definitionVersionId:d.versionId,definitionDigest:d.reviewDigest,applicability:scope,value:{type:'BOOLEAN' as const,value:true},purpose:'BOOLEAN_GATE_V1' as const,validFrom:'2026-01-01T00:00:00',validTo:null,evidenceId:f.artifact.artifactId};
 const draft=await values.command('maker',request);expect(draft.status).toBe('DRAFT');expect((await values.evaluateWindow('maker',{id:draft.id,validFrom:request.validFrom,validTo:null})).covered).toBe(false);
 await expect(values.command('maker-alias',{action:'APPROVE',requestId:randomUUID(),reason:'TEST same human',target:draft.id,versionId:draft.versionId,reviewDigest:draft.reviewDigest})).rejects.toThrow('SELF_REVIEW_FORBIDDEN');
 const approved=await values.command('reviewer',{action:'APPROVE',requestId:randomUUID(),reason:'TEST independent approval',target:draft.id,versionId:draft.versionId,reviewDigest:draft.reviewDigest});
 expect(approved.value).toEqual({type:'BOOLEAN',value:true});expect(approved.status).toBe('APPROVED');expect((await values.read('maker',{id:approved.id})).applicability).toEqual(scope);
 expect((await values.evaluateWindow('maker',{id:approved.id,validFrom:'2026-02-01T00:00:00',validTo:'2026-03-01T00:00:00'})).covered).toBe(true);
 expect((await catalog.parameterRead('maker',{scope:'SYNTHETIC',versionId:d.versionId}))[0]?.runtimeReadiness).toBe('NOT_READY');
 expect(await values.command('maker',request)).toEqual(draft);
});

test('a published capability distinguishes ORDER from EXECUTE and retains its original source evidence',async()=>{
 capabilities.grant(scope);const entry=capabilities.entry(scope),out=await capabilities.apply(await capabilities.input([entry])),id=out.facts[0]!.id;
 expect(id).not.toBe(entry.row.capability_id);
 expect((await capabilities.owner.read('maker',{id,businessAt:'2026-02-01T00:00:00'})).state).toBe('ACTIVE');
 expect((await capabilities.owner.evaluateWindow('maker',{applicability:scope,validFrom:'2026-02-01T00:00:00',validTo:'2026-03-01T00:00:00',mode:'CURRENT_ADMISSION'})).status).toBe('SATISFIED');
 expect((await capabilities.owner.evaluateWindow('maker',{applicability:{...scope,capabilityType:'EXECUTE'},validFrom:'2026-02-01T00:00:00',validTo:'2026-03-01T00:00:00',mode:'CURRENT_ADMISSION'})).status).toBe('NOT_SATISFIED');
 expect((await capabilities.owner.history('maker',{id})).versions[0]!.facts.source.sourceVersion).toBe('9');
});

test('an explicit one-microsecond suspension rejects the whole new window while the original record time remains readable',async()=>{
 const s=await capabilities.endpoint(),entry=capabilities.entry(s),out=await capabilities.apply(await capabilities.input([entry])),id=out.facts[0]!.id,h=await capabilities.owner.history('maker',{id});
 const from='2026-03-01T00:00:00.000000',resume='2026-03-01T00:00:00.000001';
 await capabilities.apply(await capabilities.input([{...entry,action:'SUSPEND',target:{owner:'care-organization/unit-capability',id,expectedHead:'1'},row:{...entry.row,enabled:'N',record_status:'SUSPENDED',valid_from:from,valid_to:null}}]));
 expect((await capabilities.owner.read('maker',{id,businessAt:from})).state).toBe('SUSPENDED');
 await capabilities.apply(await capabilities.input([{...entry,action:'RESUME',target:{owner:'care-organization/unit-capability',id,expectedHead:'2'},row:{...entry.row,enabled:'Y',record_status:'ACTIVE',valid_from:resume,valid_to:null}}]));
 const window={applicability:s,validFrom:from,validTo:'2026-03-01T00:00:00.000002',mode:'CURRENT_ADMISSION' as const};
 const current=await capabilities.owner.evaluateWindow('maker',window);expect(current.status).toBe('NOT_SATISFIED');expect(current.checks).toContainEqual(expect.objectContaining({from,to:resume,reason:'CAPABILITY_SUSPENDED'}));
 expect((await capabilities.owner.evaluateWindow('maker',{...window,mode:'HISTORICAL',recordAsOf:h.versions[0]!.recordedAt})).status).toBe('SATISFIED');
 expect((await capabilities.owner.exact('maker',{id,version:'1'}))).toEqual(h.versions[0]);
 await expect(capabilities.owner.evaluateWindow('maker',{...window,recordAsOf:h.versions[0]!.recordedAt})).rejects.toThrow('CURRENT_RECORD_TIME_REQUIRED');
});

test.each([
 {type:'TEXT' as const,value:'  TEST POLICY ONLY exact text  '},
 {type:'INTEGER' as const,value:'9007199254740993123456789'},
 {type:'DECIMAL' as const,value:'9007199254740993.000001'},
 {type:'BOOLEAN' as const,value:false},
])('GOV09 $type uses its approved schema and retains its exact native value',async value=>{
 const d=await definition(value.type),draft=await values.command('maker',{action:'CREATE',requestId:randomUUID(),reason:'TEST lossless value',definitionVersionId:d.versionId,definitionDigest:d.reviewDigest,applicability:scope,value,purpose:'METADATA',validFrom:'2026-01-01T00:00:00',validTo:'2026-04-01T00:00:00',evidenceId:f.artifact.artifactId});
 const approved=await values.command('reviewer',{action:'APPROVE',requestId:randomUUID(),reason:'TEST independent typed approval',target:draft.id,versionId:draft.versionId,reviewDigest:draft.reviewDigest});expect((await values.read('maker',{id:approved.id})).value).toEqual(value);
 expect((await values.evaluateWindow('maker',{id:approved.id,validFrom:'2026-03-31T23:59:59.999999',validTo:'2026-04-01T00:00:00.000001'})).reason).toBe('PARAMETER_PERIOD_NOT_COVERED');
 await expect(values.command('maker',{action:'REVISE',requestId:randomUUID(),reason:'TEST wrong schema type',target:approved.id,expectedHead:'1',definitionVersionId:d.versionId,definitionDigest:d.reviewDigest,value:value.type==='BOOLEAN'?{type:'TEXT',value:'false'}:{type:'BOOLEAN',value:true},purpose:'METADATA',validFrom:'2026-01-01T00:00:00',validTo:null,evidenceId:f.artifact.artifactId})).rejects.toThrow('PARAMETER_VALUE_INVALID');
});

test('changed approved parameter values block current admission and require explicit re-adoption while original outcomes remain recoverable',async()=>{
 const s=await capabilities.endpoint(),d=await definition('BOOLEAN');
 const draft=await values.command('maker',{action:'CREATE',requestId:randomUUID(),reason:'TEST capability gate',definitionVersionId:d.versionId,definitionDigest:d.reviewDigest,applicability:s,value:{type:'BOOLEAN',value:true},purpose:'BOOLEAN_GATE_V1',validFrom:'2026-01-01T00:00:00',validTo:null,evidenceId:f.artifact.artifactId}),approved=await values.command('reviewer',{action:'APPROVE',requestId:randomUUID(),reason:'TEST gate approval',target:draft.id,versionId:draft.versionId,reviewDigest:draft.reviewDigest});
 const pin=(v:typeof approved)=>({owner:'governance-catalog/parameter-value' as const,parameterId:v.parameterId,valueId:v.id,versionId:v.versionId,definitionVersionId:v.definitionVersionId,definitionDigest:v.definitionDigest,valueDigest:v.reviewDigest});
 const entry={...capabilities.entry(s),rule:{kind:'BOOLEAN_GATE_V1' as const,parameter:pin(approved)},row:{...capabilities.row(s),rule_ref:d.id}},request=await capabilities.prepare(await capabilities.input([entry])),out=await capabilities.owner.applyUnit('maker',request);expect(out.status).toBe('COMMITTED');if(out.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');
 const id=out.facts[0]!.id,original=await capabilities.owner.exact('maker',{id,version:'1'}),window={applicability:s,validFrom:'2026-02-01T00:00:00',validTo:'2026-03-01T00:00:00',mode:'CURRENT_ADMISSION' as const};
 const revised=await values.command('maker',{action:'REVISE',requestId:randomUUID(),reason:'TEST deny new usage',target:approved.id,expectedHead:'1',definitionVersionId:d.versionId,definitionDigest:d.reviewDigest,value:{type:'BOOLEAN',value:false},purpose:'BOOLEAN_GATE_V1',validFrom:'2026-01-01T00:00:00',validTo:null,evidenceId:f.artifact.artifactId});
 expect((await capabilities.owner.evaluateWindow('maker',window)).status).toBe('SATISFIED');
 await values.command('reviewer',{action:'APPROVE',requestId:randomUUID(),reason:'TEST approve denied gate',target:revised.id,versionId:revised.versionId,reviewDigest:revised.reviewDigest});
 expect((await capabilities.owner.evaluateWindow('maker',window)).checks).toContainEqual(expect.objectContaining({reason:'PARAMETER_ADOPTION_CHANGED'}));
 const {responseStatus:_,...durable}=out;expect(await capabilities.owner.resumeOutcome('maker',request)).toEqual(durable);expect(await capabilities.owner.exact('maker',{id,version:'1'})).toEqual(original);
 const readyDraft=await values.command('maker',{action:'REVISE',requestId:randomUUID(),reason:'TEST ready again',target:approved.id,expectedHead:'2',definitionVersionId:d.versionId,definitionDigest:d.reviewDigest,value:{type:'BOOLEAN',value:true},purpose:'BOOLEAN_GATE_V1',validFrom:'2026-01-01T00:00:00',validTo:null,evidenceId:f.artifact.artifactId}),ready=await values.command('reviewer',{action:'APPROVE',requestId:randomUUID(),reason:'TEST approved ready gate',target:readyDraft.id,versionId:readyDraft.versionId,reviewDigest:readyDraft.reviewDigest});
 await capabilities.apply(await capabilities.input([{...entry,action:'REVISE',target:{owner:'care-organization/unit-capability',id,expectedHead:'1'},rule:{kind:'BOOLEAN_GATE_V1',parameter:pin(ready)}}]));
 expect((await capabilities.owner.evaluateWindow('maker',window)).status).toBe('SATISFIED');expect(await capabilities.owner.exact('maker',{id,version:'1'})).toEqual(original);
});


test('finite Department and Campus impacts preserve original evidence, reserve paused capabilities and recover exact committed END proofs',async()=>{
 const s=await capabilities.endpoint(),entry=capabilities.entry(s),grant=await capabilities.apply(await capabilities.input([entry])),id=grant.facts[0]!.id,unit=await f.owner.history('maker',{id:s.unit.id}),dept=unit.departmentId;
 const pool=new Pool({connectionString:connection,max:1});try{
  const refs=async()=> (await pool.query('select care_organization.capability_department_references($1,$2::jsonb,$3) r',['maker',JSON.stringify([dept]),'NORTH'])).rows[0].r;
  const first=(await refs()).find((r:{id:string})=>r.id===id);expect(first.current).toBe(true);expect(first.acceptedVersions.length).toBeGreaterThan(0);
  const paused={...entry,action:'SUSPEND' as const,target:{owner:'care-organization/unit-capability' as const,id,expectedHead:'1'},row:{...entry.row,enabled:'N' as const,record_status:'SUSPENDED' as const,valid_from:'2026-04-01T00:00:00'}};
  await capabilities.apply(await capabilities.input([paused]));expect((await refs()).find((r:{id:string})=>r.id===id).current).toBe(true);
  const endInput=await capabilities.input([{...paused,action:'END',target:{...paused.target,expectedHead:'2'},row:{...paused.row,record_status:'RETIRED',valid_from:'2026-05-01T00:00:00'}}]),request=await capabilities.prepare(endInput),ended=await capabilities.owner.applyUnit('maker',request);expect(ended.status).toBe('COMMITTED');
  const h=await capabilities.owner.history('maker',{id}),v=h.versions.at(-1)!,ref={owner:'UNIT_CAPABILITY',id,versionId:v.id,...request};
  const result=(await pool.query('select department_master.impact_result($1,$2::jsonb,$3) r',['maker',JSON.stringify(ref),'NORTH'])).rows[0].r;expect(result).toMatchObject({action:'END',safeShrink:true,period:{from:'2026-01-01T00:00:00.000000',to:'2026-05-01T00:00:00.000000'}});
  const current=(await refs()).find((r:{id:string})=>r.id===id);expect(current).toMatchObject({current:false,originalDigest:first.originalDigest,acceptedVersions:first.acceptedVersions});
  const deps=async(from:string,to:string|null)=> (await pool.query('select care_organization.capability_campus_dependencies($1,$2::uuid,$3::timestamp,$4::timestamp,NULL) r',['maker',s.campus.id,from,to])).rows[0].r;
  expect((await deps('2026-02-01T00:00:00','2026-03-01T00:00:00')).find((r:{id:string})=>r.id===id)).toMatchObject({active:true,outstanding:false});expect((await deps('2026-05-01T00:00:00',null)).find((r:{id:string})=>r.id===id)).toMatchObject({active:false,outstanding:false});
  await expect(capabilities.apply(await capabilities.input([{...entry,action:'RESUME',target:{...paused.target,expectedHead:'3'},row:{...entry.row,valid_from:'2026-05-01T00:00:00'}}]))).rejects.toThrow('CAPABILITY_ENDED');
 }finally{await pool.end();}
});


async function populated(enabled:'Y'|'N'='Y',to:string|null=null){const s=await capabilities.endpoint(),entry=capabilities.entry(s);entry.row.enabled=enabled;entry.row.valid_to=to;const out=await capabilities.apply(await capabilities.input([entry]));return {s,entry,id:out.facts[0]!.id};}
function command(a:Awaited<ReturnType<typeof populated>>,action:Exclude<CapabilityEntry['action'],'GRANT'>,head:string,from:string,to:string|null=null):CapabilityEntry{return {...a.entry,action,target:{owner:'care-organization/unit-capability',id:a.id,expectedHead:head},row:{...a.entry.row,valid_from:from,valid_to:to,enabled:action==='SUSPEND'||action==='END'?'N':a.entry.row.enabled,record_status:action==='END'?'RETIRED':action==='SUSPEND'?'SUSPENDED':'ACTIVE'}};}

test('disabled relations reserve their scope and explicit activation enables only the approved remaining period',async()=>{
 const a=await populated('N');const duplicate=capabilities.entry(a.s);await expect(capabilities.prepare(await capabilities.input([duplicate]))).rejects.toThrow('CAPABILITY_SCOPE_CONFLICT');
 expect((await capabilities.owner.read('maker',{id:a.id,businessAt:'2026-02-01T00:00:00'})).state).toBe('DISABLED');
 const activation=command(a,'ACTIVATE','1','2026-03-01T00:00:00');activation.row.enabled='Y';await capabilities.apply(await capabilities.input([activation]));
 expect((await capabilities.owner.read('maker',{id:a.id,businessAt:'2026-02-28T23:59:59.999999'})).state).toBe('DISABLED');expect((await capabilities.owner.read('maker',{id:a.id,businessAt:'2026-03-01T00:00:00'})).state).toBe('ACTIVE');
});
test('a finite latest declaration does not fall back to the original open version and REVISE never resumes a suspension',async()=>{
 const a=await populated();await capabilities.apply(await capabilities.input([command(a,'REVISE','1','2026-01-01T00:00:00','2026-05-01T00:00:00')]));
 const w={applicability:a.s,validFrom:'2026-05-01T00:00:00',validTo:null,mode:'CURRENT_ADMISSION' as const};expect((await capabilities.owner.evaluateWindow('maker',w)).status).toBe('NOT_SATISFIED');
 await capabilities.apply(await capabilities.input([command(a,'SUSPEND','2','2026-03-01T00:00:00')]));const r=command(a,'REVISE','3','2026-01-01T00:00:00','2026-06-01T00:00:00');await capabilities.apply(await capabilities.input([r]));expect((await capabilities.owner.read('maker',{id:a.id,businessAt:'2026-04-01T00:00:00'})).state).toBe('SUSPENDED');
});
test('END can be confirmed or shortened and exact older committed END evidence survives later shortening',async()=>{
 const a=await populated(),q=await capabilities.prepare(await capabilities.input([command(a,'END','1','2026-05-01T00:00:00')]));await capabilities.owner.applyUnit('maker',q);const original=await capabilities.owner.exact('maker',{id:a.id,version:'2'});
 await capabilities.apply(await capabilities.input([command(a,'END','2','2026-04-01T00:00:00')]));expect(await capabilities.owner.exact('maker',{id:a.id,version:'2'})).toEqual(original);
 await expect(capabilities.prepare(await capabilities.input([command(a,'END','3','2026-06-01T00:00:00')]))).rejects.toThrow('CAPABILITY_ENDED');
 const pool=new Pool({connectionString:connection,max:1});try{expect((await pool.query('select department_master.impact_result($1,$2::jsonb,$3) r',['maker',JSON.stringify({owner:'UNIT_CAPABILITY',id:a.id,versionId:original.id,...q}),'NORTH'])).rows[0].r.period.to).toBe('2026-05-01T00:00:00.000000');}finally{await pool.end();}
 const replacement=capabilities.entry(a.s);replacement.row.valid_from='2026-04-01T00:00:00';expect((await capabilities.apply(await capabilities.input([replacement]))).facts[0]!.id).not.toBe(a.id);
});
test('same expected head concurrent revisions commit once and a whole batch cannot reserve intersecting service scopes',async()=>{
 const a=await populated(),one=command(a,'REVISE','1','2026-01-01T00:00:00'),two=command(a,'REVISE','1','2026-01-01T00:00:00');one.row.approval_dept='TEST one';two.row.approval_dept='TEST two';const q1=await capabilities.prepare(await capabilities.input([one])),q2=await capabilities.prepare(await capabilities.input([two])),results=await Promise.allSettled([capabilities.owner.applyUnit('maker',q1),capabilities.owner.applyUnit('maker',q2)]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected')).toHaveLength(1);expect((await capabilities.owner.history('maker',{id:a.id})).versions).toHaveLength(2);
 const s=await capabilities.endpoint();await expect(capabilities.prepare(await capabilities.input([capabilities.entry(s),capabilities.entry(s)]))).rejects.toThrow('CAPABILITY_SCOPE_CONFLICT');
});
test('scope service gaps, nonempty unresolved rules and absent independent no-rule confirmation remain blocked',async()=>{
 const s=await capabilities.endpoint(),e=capabilities.entry(s);e.applicability.services=['DEMO_MEDICAL_B'];await expect(capabilities.prepare(await capabilities.input([e]))).rejects.toThrow('CAPABILITY_SCOPE_NOT_COVERED');
 const unknown=capabilities.entry(s);unknown.row.rule_ref='UNKNOWN';await expect(capabilities.prepare(await capabilities.input([unknown]))).rejects.toThrow('CAPABILITY_RULE_REFERENCE_INVALID');
 const v=await capabilities.input([capabilities.entry(s)]),i=await capabilities.owner.stage('maker',v),proof=capabilities.verification(v,i);proof.rows[0]!.ruleConfirmed=false;await capabilities.owner.verify('reviewer',proof);expect((await capabilities.owner.preview('maker',{inputId:i.inputId})).issues).toContainEqual(expect.objectContaining({code:'CAPABILITY_REVIEW_REQUIRED'}));
});
test('SQL rejects changed facts and stale database R even with a valid application transaction signature',async()=>{
 const s=await capabilities.endpoint(),q=await capabilities.prepare(await capabilities.input([capabilities.entry(s)])),c=await capabilities.owner.readApplyCandidate('reviewer',{candidateId:q.candidateId}),value=c.unit.commands[0]!.value,writes=JSON.parse(value['writes']!);writes[0].facts.approvalDepartment='TEST UNAPPROVED';
 const p=new Pool({connectionString:connection,max:1}),client=await p.connect(),key=Buffer.from(planBinding(validationKeys(receipt),'CAPABILITY_SQL_AUTHORITY_V1',{}),'hex');try{await client.query('BEGIN');const transaction=(await client.query('select pg_current_xact_id()::text v')).rows[0].v,point=(await client.query('select care_organization.capability_record_time() r')).rows[0].r;
  const badTime=canonicalPlan({operation:'APPLY',actor:'maker',transaction,inputId:value['inputId'],writes,writeIndex:1,writesDigest:value['writesDigest'],candidateId:q.candidateId,digest:c.digest,...point,recordAt:'2000-01-01T00:00:00.000000'});await client.query('SAVEPOINT wrong_time');await expect(client.query('select care_organization.capability_mutate($1,$2)',[badTime,createHmac('sha256',key).update(badTime).digest('hex')])).rejects.toMatchObject({message:'INVALID_PLAN_TOKEN'});await client.query('ROLLBACK TO SAVEPOINT wrong_time');
  const ticket=canonicalPlan({operation:'APPLY',actor:'maker',transaction,inputId:value['inputId'],writes,writeIndex:1,writesDigest:value['writesDigest'],candidateId:q.candidateId,digest:c.digest,...point});await expect(client.query('select care_organization.capability_mutate($1,$2)',[ticket,createHmac('sha256',key).update(ticket).digest('hex')])).rejects.toMatchObject({message:'STALE_VALIDATION'});
 }finally{await client.query('ROLLBACK');client.release();await p.end();key.fill(0);}expect((await capabilities.owner.applyUnit('maker',q)).status).toBe('COMMITTED');
});
test('failed audit rolls back capability facts and outcome, and committed recovery rechecks current authorization',async()=>{
 const s=await capabilities.endpoint(),q=await capabilities.prepare(await capabilities.input([capabilities.entry(s)]));peer(receipt.name,`CREATE FUNCTION care_organization.capability_test_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='CAPABILITY_GRANT' THEN RAISE EXCEPTION 'TEST_CAPABILITY_AUDIT';END IF;RETURN NEW;END $$;CREATE TRIGGER test_capability_audit BEFORE INSERT ON vnext_control.audit FOR EACH ROW EXECUTE FUNCTION care_organization.capability_test_failure();`);
 try{await expect(capabilities.owner.applyUnit('maker',q)).rejects.toThrow('APPLY_FAILED');expect(await capabilities.owner.resumeOutcome('maker',q)).toBeNull();}finally{peer(receipt.name,'DROP TRIGGER test_capability_audit ON vnext_control.audit;DROP FUNCTION care_organization.capability_test_failure();');}
 const out=await capabilities.owner.applyUnit('maker',q,async()=>{throw new Error('TEST_LOST_RESPONSE');});expect(out.status).toBe('COMMITTED');expect(out).toMatchObject({responseStatus:'POST_COMMIT_FAILED'});expect(await capabilities.owner.reconcileCommittedUnit('maker',q)).toMatchObject({status:'MATCHED'});
 peer(receipt.name,`DELETE FROM care_organization.capability_access WHERE actor='maker' AND campus_id=${quote(s.campus.id)}::uuid AND permission='READ';`);try{await expect(capabilities.owner.resumeOutcome('maker',q)).rejects.toThrow('ACCESS_DENIED');}finally{peer(receipt.name,`INSERT INTO care_organization.capability_access VALUES('maker',${quote(s.campus.id)}::uuid,'NORTH','READ');`);}
});
test.each(['CSV','JSON','XLSX'] as const)('ORG16 %s uses all source fields, protected parsing and the same Owner approval path',async format=>{
 const s=await capabilities.endpoint(),e=capabilities.entry(s),row={...e.row},fields=ORG16_FIELDS;
 const bytes=format==='JSON'?Buffer.from(JSON.stringify([row])):format==='CSV'?Buffer.from(fields.join(',')+'\n'+fields.map(f=>row[f]??'').join(',')):organizationWorkbook({'ORG16':[fields,fields.map(f=>String(row[f]??''))]});
 const r=await capabilities.owner.receiveFile('maker',{requestId:randomUUID(),fileRequestId:randomUUID(),job:{action:'CREATE',scope:'SYNTHETIC',requestId:randomUUID(),reason:'TEST_CAPABILITY_FILE',profile:'CORE',contractId:capabilities.contract!.id,contractVersionId:capabilities.contract!.versionId,input:{kind:'FILE',format,parserPolicy:'STRICT_CAPABILITY_V1'}},campus:'NORTH',timePolicy:'LOCAL',retentionSeconds:7200,operations:[{action:'GRANT',applicability:s,rule:e.rule,reason:e.reason,evidenceId:e.evidenceId}]},bytes);
 expect(r.structuralStatus).toBe('PARSED');expect(r.issues).toEqual([]);expect(r.input).not.toBeNull();const v=await capabilities.owner.readInput('maker',{inputId:r.input!.inputId});expect(Object.keys(v.entries[0]!.row)).toHaveLength(15);expect(v.entries[0]!.row.valid_to).toBeNull();expect(v.entries[0]!.row.version_no).toBe(format==='JSON'?9:'9');await capabilities.owner.verify('reviewer',capabilities.verification(v,r.input!));const requestId=randomUUID(),c=await capabilities.owner.plan('maker',{inputId:r.input!.inputId,requestId});await capabilities.owner.readApplyCandidate('reviewer',{candidateId:c.candidateId});await capabilities.owner.approveApplyUnit('reviewer',c);expect((await capabilities.owner.applyUnit('maker',{candidateId:c.candidateId,requestId})).status).toBe('COMMITTED');
});
test('generated clients publish through real HTTP and recover exact outcomes with current authorization',async()=>{
 const server=await buildCatalogServer(catalog,'CONTROL_PLANE',undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,{owner:values,actor:r=>actor(r.headers)},{owner:capabilities.owner,actor:r=>actor(r.headers)});
 try{const url=await server.listen({host:'127.0.0.1',port:0}),catalogClient=createVNextCatalogClient(url,'maker');expect((await catalogClient.GET('/api/vnext/catalog',{params:{query:{scope:'SYNTHETIC',page:1}}})).response.status).toBe(200);expect((await catalogClient.GET('/api/vnext/contracts/current',{params:{query:{scope:'BASELINE',page:1}}})).response.status).toBe(200);const maker=createUnitCapabilityClient(url,'maker'),reviewer=createUnitCapabilityClient(url,'reviewer'),s=await capabilities.endpoint(),v=await capabilities.input([capabilities.entry(s)]),i=await maker.stage(v);expect(i.response.status).toBe(200);expect((await maker.readInput({inputId:i.data!.inputId})).data?.entries[0]!.row.valid_to).toBeNull();expect((await reviewer.verify(capabilities.verification(v,i.data!))).response.status).toBe(200);const requestId=randomUUID(),c=await maker.plan({inputId:i.data!.inputId,requestId});expect(c.response.status,c.error?.code).toBe(200);expect((await reviewer.review({candidateId:c.data!.candidateId})).response.status).toBe(200);expect((await reviewer.approve(c.data!)).response.status).toBe(200);const q={candidateId:c.data!.candidateId,requestId},out=await maker.apply(q);expect(out.data?.status).toBe('COMMITTED');if(out.data?.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');expect((await maker.apply(q)).data).toEqual(out.data);expect((await maker.reconcile(q)).data).toMatchObject({status:'MATCHED'});const {responseStatus:_,...durable}=out.data;expect((await maker.resume(q)).data).toEqual(durable);expect((await maker.evaluate({applicability:s,validFrom:'2026-02-01T00:00:00',validTo:'2026-03-01T00:00:00',mode:'CURRENT_ADMISSION'})).data).toMatchObject({status:'SATISFIED',clinicalReadiness:'NOT_READY'});expect((await createUnitCapabilityClient(url,'outsider').query({id:out.data.facts[0]!.id})).response.status).toBe(403);
  const d=await definition('BOOLEAN'),pv=createParameterValueClient(url,'maker'),pr=createParameterValueClient(url,'reviewer'),draft=await pv.command({action:'CREATE',requestId:randomUUID(),reason:'TEST real HTTP value',definitionVersionId:d.versionId,definitionDigest:d.reviewDigest,applicability:s,value:{type:'BOOLEAN',value:true},purpose:'BOOLEAN_GATE_V1',validFrom:'2026-01-01T00:00:00',validTo:null,evidenceId:f.artifact.artifactId});expect(draft.response.status).toBe(200);const a=await pr.command({action:'APPROVE',requestId:randomUUID(),reason:'TEST real HTTP approval',target:draft.data!.id,versionId:draft.data!.versionId,reviewDigest:draft.data!.reviewDigest});expect(a.response.status).toBe(200);expect((await pv.query({id:a.data!.id})).data?.value).toEqual({type:'BOOLEAN',value:true});
 }finally{await server.close();}
});


test('database commit acknowledgement loss recovers the original outcome without creating another identity',async()=>{
 const s=await capabilities.endpoint(),q=await capabilities.prepare(await capabilities.input([capabilities.entry(s)])),original=Client.prototype.query;let injected=false;
 Client.prototype.query=(function(this:Client,config:string|QueryConfig,...args:unknown[]){const text=typeof config==='string'?config:config.text,result=Reflect.apply(original,this,[config,...args]);if(!injected&&text.trim().toLowerCase()==='commit'){injected=true;return Promise.resolve(result).then(()=>{throw Object.assign(new Error('ACK_LOST'),{code:'ECONNRESET'});});}return result;}) as typeof Client.prototype.query;
 try{expect((await capabilities.owner.applyUnit('maker',q)).status).toBe('COMMIT_UNKNOWN');expect(injected).toBe(true);}finally{Client.prototype.query=original;}
 const recovered=await capabilities.owner.resumeOutcome('maker',q),replay=await capabilities.owner.applyUnit('maker',q);expect(recovered?.status).toBe('COMMITTED');expect(replay).toMatchObject({status:'COMMITTED',facts:recovered?.facts,recordedAt:recovered?.recordedAt});
});
test('restricted SQL denies raw Owner DML, unsigned writes and startup without the installed key authority',async()=>{
 const p=new Pool({connectionString:connection,max:1});try{await expect(p.query('select * from care_organization.capability_version')).rejects.toMatchObject({code:'42501'});await expect(p.query('delete from governance_catalog.parameter_value_version')).rejects.toMatchObject({code:'42501'});await expect(p.query('select care_organization.capability_mutate($1,$2)',['{}','0'.repeat(64)])).rejects.toMatchObject({message:'ACCESS_DENIED'});}finally{await p.end();}
 await expect(assertUnitCapabilityProvisioned(connection,validationKeys(receipt))).resolves.toBeUndefined();
});
test('a Unit cross-campus REBIND carries no capability and the original historical grant remains in its original scope',async()=>{
 const a=await populated(),h=await f.owner.history('maker',{id:a.s.unit.id}),b=await f.endpoint(h.departmentId),u=h.versions[0]!.facts;
 await f.apply(await f.input([{action:'REBIND',target:{owner:'care-organization/unit',id:h.id,expectedHead:'1'},binding:b,row:{...f.row(b),unit_id:h.versions[0]!.facts.source.sourceAlias,unit_code:u.unitCode,valid_from:'2026-04-01T00:00:00'},reason:'TEST no propagated capability',evidenceId:f.artifact.artifactId}]));
 const next={...a.s,campus:b.campus,subject:b.subject};capabilities.grant(next);const w={validFrom:'2026-04-01T00:00:00',validTo:'2026-05-01T00:00:00',mode:'CURRENT_ADMISSION' as const};expect((await capabilities.owner.evaluateWindow('maker',{...w,applicability:next})).status).toBe('NOT_SATISFIED');expect((await capabilities.owner.evaluateWindow('maker',{...w,applicability:a.s})).status).toBe('NOT_SATISFIED');expect((await capabilities.owner.history('maker',{id:a.id})).applicability.campus.id).toBe(a.s.campus.id);
 const grant=capabilities.entry(next);grant.row.valid_from=w.validFrom;grant.row.valid_to=w.validTo;expect((await capabilities.apply(await capabilities.input([grant]))).status).toBe('COMMITTED');
});
test('dependency changes after approval invalidate a capability candidate, and safe END still works after Unit closure',async()=>{
 const a=await populated(),next=command(a,'REVISE','1','2026-01-01T00:00:00'),q=await capabilities.prepare(await capabilities.input([next])),h=await f.owner.history('maker',{id:a.s.unit.id}),b=h.bindings[0]!.versions.at(-1)!.binding;
 await f.apply(await f.input([{action:'CLOSE',target:{owner:'care-organization/unit',id:h.id,expectedHead:'1'},row:{...f.row(b),unit_id:h.versions[0]!.facts.source.sourceAlias,unit_code:h.versions[0]!.facts.unitCode,record_status:'RETIRED',valid_from:'2026-04-01T00:00:00'},reason:'TEST upstream closure',evidenceId:f.artifact.artifactId}]));
 await expect(capabilities.owner.applyUnit('maker',q)).rejects.toThrow('STALE_VALIDATION');expect((await capabilities.owner.evaluateWindow('maker',{applicability:a.s,validFrom:'2026-04-01T00:00:00',validTo:null,mode:'CURRENT_ADMISSION'})).status).toBe('NOT_SATISFIED');expect((await capabilities.apply(await capabilities.input([command(a,'END','1','2026-04-01T00:00:00')]))).status).toBe('COMMITTED');
});
test('Department evolution declares capability coverage and renaming leaves the actual capability constraint satisfied',async()=>{
 const provider=validationKeys(receipt),base=await organizationMappingFixture(receipt,catalog,provider,connection,undefined,f.dep),e=await evolutionFixture(receipt,catalog,provider,connection,base),b=await f.endpoint(e.targetId),u=await f.apply(await f.input([f.entry(b)])),s:CapabilityScope={unit:{owner:'care-organization/unit',id:u.facts[0]!.id},campus:b.campus,subject:b.subject,services:b.services,capabilityType:'CONSULT',careSetting:'OUTPATIENT'};capabilities.grant(s);const grant=await capabilities.apply(await capabilities.input([capabilities.entry(s)])),owner=openOrganizationEvolutions(connection,provider,withCareOrganizationImpacts(()=>f.owner,()=>undefined,()=>undefined,()=>capabilities.owner));
 try{const v=await e.input(),i=await owner.stage('maker',v);await owner.verify('reviewer',{requestId:randomUUID(),inputId:i.inputId,inputDigest:i.digest,reason:'TEST eleven domain approval',policyApproved:true,materialsAccepted:true,impactReviews:e.impactReviews});const requestId=randomUUID(),c=await owner.plan('maker',{inputId:i.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:c.candidateId});await owner.approveApplyUnit('reviewer',c);const out=await owner.applyUnit('maker',{candidateId:c.candidateId,requestId});expect(out.status).toBe('COMMITTED');if(out.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');const report=await owner.assessDepartmentChange('maker',{requestId:randomUUID(),reason:'TEST exact current capability reference',target:{kind:'EVENT',id:out.facts[0]!.id,campus:'NORTH'}});expect(report.coverage).toContainEqual({owner:'UNIT_CAPABILITY',status:'EVALUATED',reason:'OWNER_AVAILABLE'});expect(report.references).toContainEqual(expect.objectContaining({owner:'UNIT_CAPABILITY',id:grant.facts[0]!.id,change:'CHANGED',constraint:'SATISFIED'}));expect(report.coverage).toContainEqual({owner:'PERSONNEL',status:'NOT_EVALUABLE',reason:'OWNER_NOT_IMPLEMENTED'});
 }finally{await owner.close();}
});
test('a real Department suspension opens a capability case and an independently approved exact END disposition closes it',async()=>{
 const a=await populated(),provider=validationKeys(receipt),unit=await f.owner.history('maker',{id:a.s.unit.id}),dept=await f.department.history('maker',unit.departmentId),life=await f.lifecycle.history('maker',{id:unit.departmentId}),ports=withCareOrganizationImpacts(()=>f.owner,()=>undefined,()=>undefined,()=>capabilities.owner),lifecycle=openDepartmentLifecycle(connection,provider,ports),evolution=openOrganizationEvolutions(connection,provider,ports);
 try{const j=await f.dep.newJob(),i=await lifecycle.stage('maker',{requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',profile:'CORE',commands:[{action:'SUSPEND',department:{owner:'department-master',id:unit.departmentId,expectedVersion:dept.versions.at(-1)!.number,expectedLifecycleHead:life.lifecycle.at(-1)?.number??'0'},effectiveAt:'2026-04-01T00:00:00',reason:'TEST explicit capability exit',evidenceId:f.dep.artifact.artifactId}],impacts:f.impacts.map(v=>({...v,determination:['UNIT_CAPABILITY','SOURCE_MAPPING','IDENTIFIER','HIERARCHY'].includes(v.domain)?'AFFECTED':v.determination}))});await lifecycle.verify('reviewer',{requestId:randomUUID(),inputId:i.inputId,inputDigest:i.digest,reason:'TEST independent exit review',policyApproved:true,materialsAccepted:true,impactReviews:f.impactReviews});const requestId=randomUUID(),c=await lifecycle.plan('maker',{inputId:i.inputId,requestId});await lifecycle.readApplyCandidate('reviewer',{candidateId:c.candidateId});await lifecycle.approveApplyUnit('reviewer',c);const out=await lifecycle.applyUnit('maker',{candidateId:c.candidateId,requestId});expect(out.status).toBe('COMMITTED');if(out.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');const item=(await evolution.listImpactCases('maker',{eventId:out.facts[0]!.id,campus:'NORTH'})).items.find(v=>v.obligation.owner==='UNIT_CAPABILITY')!;expect(item.status).toBe('OPEN');
  const draft=await catalog.command('maker',{action:'CREATE',scope:'SYNTHETIC',requestId:randomUUID(),reason:'RESPONSIBILITY',kind:'RESPONSIBILITY',code:'CAP_IMPACT_'+randomUUID().replaceAll('-','').toUpperCase(),values:{dataset:'ORG16',authorityScope:'ALL',fieldGroup:'ALL',role:'OWNER',assigneeRole:'SYNTHETIC_OWNER_A'},validFrom:'2026-01-01T00:00:00'}),submitted=await catalog.command('maker',{action:'SUBMIT',scope:'SYNTHETIC',requestId:randomUUID(),reason:'RESPONSIBILITY',target:draft.id,expectedHead:draft.head}),r=await catalog.command('reviewer',{action:'PUBLISH',scope:'SYNTHETIC',requestId:randomUUID(),reason:'RESPONSIBILITY',target:draft.id,expectedHead:submitted.head,reviewDigest:submitted.reviewDigest});const assigned=await evolution.assignImpactCase('maker',{requestId:randomUUID(),reason:'TEST explicit capability Owner',caseId:item.id,campus:'NORTH',expectedHead:item.head,responsibilityId:r.id});
  const q=await capabilities.prepare(await capabilities.input([command(a,'END','1','2026-04-01T00:00:00')]));await capabilities.owner.applyUnit('maker',q);const v=await capabilities.owner.exact('maker',{id:a.id,version:'2'}),proof={owner:'UNIT_CAPABILITY' as const,id:a.id,versionId:v.id,...q},proposed=await evolution.recordDisposition('maker',{requestId:randomUUID(),reason:'TEST exact committed end',caseId:item.id,campus:'NORTH',expectedHead:assigned.head,disposition:{kind:'CLOSE_RELATION',evidenceId:f.dep.artifact.artifactId,result:proof}}),approved=await evolution.approveDisposition('reviewer',{requestId:randomUUID(),reason:'TEST independent disposition',caseId:item.id,campus:'NORTH',expectedHead:proposed.head,proposalEventId:proposed.eventId});expect((await evolution.recheckImpact('maker',{requestId:randomUUID(),reason:'TEST remaining obligation',caseId:item.id,campus:'NORTH',expectedHead:approved.head})).status).toBe('RESOLVED');
 }finally{await lifecycle.close();await evolution.close();}
});
test('Campus actual impact distinguishes past evidence from remaining future capability obligations',async()=>{
 const a=await populated('Y','2026-06-01T00:00:00'),campus=openCampus(connection,validationKeys(receipt),{owners:['UNIT_CAPABILITY'],readInTransaction:capabilities.owner.readCampusDependenciesInTransaction});try{const report=await campus.assessCampusImpact('maker',{id:a.s.campus.id,validFrom:'2026-02-01T00:00:00',validTo:'2026-03-01T00:00:00'});expect(report.dependencies).toContainEqual(expect.objectContaining({owner:'UNIT_CAPABILITY',id:a.id,active:true,outstanding:false}));expect(report.unavailable).not.toContain('UNIT_CAPABILITY');}finally{await campus.close();}
});


test.each(['Z','+09:00'])('source %s offset never silently becomes a local capability period',async offset=>{
 const s=await capabilities.endpoint(),e=capabilities.entry(s);e.row.valid_from+=offset;const v=await capabilities.input([e]),i=await capabilities.owner.stage('maker',v),proof=capabilities.verification(v,i);proof.rows[0]!.validFrom='2026-01-01T00:00:00';await capabilities.owner.verify('reviewer',proof);expect((await capabilities.owner.preview('maker',{inputId:i.inputId})).issues).toContainEqual(expect.objectContaining({code:'LOCAL_TIME_REQUIRED'}));
});
test('explicit +08 conversion retains original source tokens and approves an exact local microsecond window',async()=>{
 const s=await capabilities.endpoint(),e=capabilities.entry(s);e.row.valid_from+='.000001'+'+08:00';e.row.recorded_at+='+08:00';const v=await capabilities.input([e]);v.timePolicy='SOURCE_PLUS08_TO_LOCAL';const i=await capabilities.owner.stage('maker',v);expect((await capabilities.owner.readInput('maker',{inputId:i.inputId})).entries[0]!.row.recorded_at).toBe('2026-01-02T00:00:00+08:00');const proof=capabilities.verification(v,i);proof.rows[0]!.validFrom='2026-01-01T00:00:00.000001';await capabilities.owner.verify('reviewer',proof);const requestId=randomUUID(),c=await capabilities.owner.plan('maker',{inputId:i.inputId,requestId});await capabilities.owner.readApplyCandidate('reviewer',{candidateId:c.candidateId});await capabilities.owner.approveApplyUnit('reviewer',c);const out=await capabilities.owner.applyUnit('maker',{candidateId:c.candidateId,requestId});expect(out.status).toBe('COMMITTED');if(out.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');expect((await capabilities.owner.exact('maker',{id:out.facts[0]!.id,version:'1'})).validFrom).toBe('2026-01-01T00:00:00.000001');
});
test('parameter secrets and executable expressions are rejected as values and an adopted false gate cannot grant a capability',async()=>{
 const s=await capabilities.endpoint(),d=await definition('TEXT'),common={action:'CREATE' as const,reason:'TEST value constraints',definitionVersionId:d.versionId,definitionDigest:d.reviewDigest,applicability:s,purpose:'METADATA' as const,validFrom:'2026-01-01T00:00:00',validTo:null,evidenceId:f.artifact.artifactId};for(const text of ['Bearer TEST_TOKEN_ONLY','SELECT 1;','password=TEST_ONLY'])await expect(values.command('maker',{...common,requestId:randomUUID(),value:{type:'TEXT',value:text}})).rejects.toThrow('PARAMETER_VALUE_FORBIDDEN');
 const bool=await definition('BOOLEAN'),draft=await values.command('maker',{...common,requestId:randomUUID(),definitionVersionId:bool.versionId,definitionDigest:bool.reviewDigest,purpose:'BOOLEAN_GATE_V1',value:{type:'BOOLEAN',value:false}}),approved=await values.command('reviewer',{action:'APPROVE',requestId:randomUUID(),reason:'TEST deny gate',target:draft.id,versionId:draft.versionId,reviewDigest:draft.reviewDigest}),e=capabilities.entry(s);e.row.rule_ref=approved.parameterId;e.rule={kind:'BOOLEAN_GATE_V1',parameter:{owner:'governance-catalog/parameter-value',parameterId:approved.parameterId,valueId:approved.id,versionId:approved.versionId,definitionVersionId:approved.definitionVersionId,definitionDigest:approved.definitionDigest,valueDigest:approved.reviewDigest}};await expect(capabilities.prepare(await capabilities.input([e]))).rejects.toThrow('CAPABILITY_RULE_DENIED');
});
test('an unrelated unreadable capability cannot poison another Unit window and a same-name Unit receives no implicit capability',async()=>{
 const a=await populated(),b=await populated(),newBinding=await f.endpoint((await f.owner.history('maker',{id:a.s.unit.id})).departmentId),unit=await f.apply(await f.input([f.entry(newBinding)])),s={...a.s,unit:{owner:'care-organization/unit' as const,id:unit.facts[0]!.id},campus:newBinding.campus,subject:newBinding.subject};capabilities.grant(s);
 peer(receipt.name,`DELETE FROM care_organization.capability_access WHERE actor='maker' AND campus_id=${quote(b.s.campus.id)}::uuid AND permission='READ';`);try{const window={validFrom:'2026-02-01T00:00:00',validTo:'2026-03-01T00:00:00',mode:'CURRENT_ADMISSION' as const};expect((await capabilities.owner.evaluateWindow('maker',{...window,applicability:a.s})).status).toBe('SATISFIED');expect((await capabilities.owner.evaluateWindow('maker',{...window,applicability:s})).status).toBe('NOT_SATISFIED');}finally{peer(receipt.name,`INSERT INTO care_organization.capability_access VALUES('maker',${quote(b.s.campus.id)}::uuid,'NORTH','READ');`);}
});
test('existing operating license revocation blocks new capability admission at both the Owner and controlled SQL seams',async()=>{
 const s=await capabilities.endpoint(),q=await capabilities.prepare(await capabilities.input([capabilities.entry(s)])),c=await capabilities.owner.readApplyCandidate('reviewer',{candidateId:q.candidateId}),value=c.unit.commands[0]!.value,h=await f.operating.org.historyDetails('maker',s.subject.id),license=h.licenses[0]!;
 await f.operating.orgApply({...f.operating.common,validFrom:'2026-04-01T00:00:00',action:'REVOKE_LICENSE',target:{id:s.subject.id,version:'1'},licenseTarget:{id:license.id,version:license.version},reason:'TEST_LICENSE_REVOKED'});
 await expect(capabilities.owner.applyUnit('maker',q)).rejects.toThrow('STALE_VALIDATION');
 const pool=new Pool({connectionString:connection,max:1}),client=await pool.connect(),key=Buffer.from(planBinding(validationKeys(receipt),'CAPABILITY_SQL_AUTHORITY_V1',{}),'hex');try{await client.query('BEGIN');const transaction=(await client.query('select pg_current_xact_id()::text v')).rows[0].v,point=(await client.query('select care_organization.capability_record_time() r')).rows[0].r,ticket=canonicalPlan({operation:'APPLY',actor:'maker',transaction,inputId:value['inputId'],writes:JSON.parse(value['writes']!),writeIndex:1,writesDigest:value['writesDigest'],candidateId:q.candidateId,digest:c.digest,...point});await expect(client.query('select care_organization.capability_mutate($1,$2)',[ticket,createHmac('sha256',key).update(ticket).digest('hex')])).rejects.toMatchObject({message:'LICENSE_PERIOD_NOT_COVERED'});}finally{await client.query('ROLLBACK');client.release();await pool.end();key.fill(0);}
});


test.each(['OWNER','SQL'] as const)('parameter read grants apply independently to retained capability payload at the %s seam',async seam=>{
 const s=await capabilities.endpoint(),d=await definition('BOOLEAN'),draft=await values.command('maker',{action:'CREATE',requestId:randomUUID(),reason:'TEST separately authorized parameter',definitionVersionId:d.versionId,definitionDigest:d.reviewDigest,applicability:s,value:{type:'BOOLEAN',value:true},purpose:'BOOLEAN_GATE_V1',validFrom:'2026-01-01T00:00:00',validTo:null,evidenceId:f.artifact.artifactId}),a=await values.command('reviewer',{action:'APPROVE',requestId:randomUUID(),reason:'TEST independently signed value',target:draft.id,versionId:draft.versionId,reviewDigest:draft.reviewDigest}),entry=capabilities.entry(s);entry.row.rule_ref=a.parameterId;entry.rule={kind:'BOOLEAN_GATE_V1',parameter:{owner:'governance-catalog/parameter-value',parameterId:a.parameterId,valueId:a.id,versionId:a.versionId,definitionVersionId:a.definitionVersionId,definitionDigest:a.definitionDigest,valueDigest:a.reviewDigest}};const out=await capabilities.apply(await capabilities.input([entry])),id=out.facts[0]!.id;
 peer(receipt.name,`DELETE FROM governance_catalog.parameter_grant WHERE actor_code='maker' AND parameter_id=${quote(a.parameterId)}::uuid AND permission='READ';`);const pool=new Pool({connectionString:connection,max:1});try{
  await expect(values.read('maker',{id:a.id})).rejects.toThrow('ACCESS_DENIED');
  if(seam==='OWNER')await expect(capabilities.owner.history('maker',{id})).rejects.toThrow('ACCESS_DENIED');else await expect(pool.query('select care_organization.capability_snapshot($1,$2::uuid)',['maker',id])).rejects.toMatchObject({message:'ACCESS_DENIED'});
 }finally{await pool.end();peer(receipt.name,`INSERT INTO governance_catalog.parameter_grant VALUES('maker',${quote(a.parameterId)}::uuid,'READ');`);}
});


test.each(['capabilityType','careSetting'] as const)('restricted parameter command rejects null %s in a closed scope',async field=>{
 const d=await definition('BOOLEAN'),request={action:'CREATE',requestId:randomUUID(),reason:'TEST null scoped dimension',definitionVersionId:d.versionId,definitionDigest:d.reviewDigest,applicability:{...scope,[field]:null},value:{type:'BOOLEAN',value:true},purpose:'BOOLEAN_GATE_V1',validFrom:'2026-01-01T00:00:00',validTo:null,evidenceId:f.artifact.artifactId},pool=new Pool({connectionString:connection,max:1});try{const code=await pool.query('select governance_catalog.parameter_value_command($1,$2::jsonb)',['maker',JSON.stringify(request)]).then(()=> 'AUTHORIZED',(e:Error)=>e.message);expect(code).toBe('PARAMETER_SCOPE_REQUIRED');}finally{await pool.end();}
});
test('blank manual end time never becomes an unlimited approved capability',async()=>{
 const s=await capabilities.endpoint(),e=capabilities.entry(s);e.row.valid_to='';const v=await capabilities.input([e]),i=await capabilities.owner.stage('maker',v);await capabilities.owner.verify('reviewer',capabilities.verification(v,i));expect((await capabilities.owner.preview('maker',{inputId:i.inputId})).issues).toContainEqual(expect.objectContaining({code:'LOCAL_TIME_REQUIRED'}));
});
