import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {beforeAll,afterAll,test,expect} from 'vitest';
import {openCatalog,type Catalog} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import type {LocationUseEntry,LocationUseScope} from '../../apps/governance-api/src/modules/location-master/index.js';
import {locationUseFixture} from './p3-07-fixture.js';
import {validationKeys} from './p3-07-validation-keys.mjs';
import {peer,quote} from './lineage.mjs';
import {signedUseAttempt,locationUseFile,locationUseFileRequest} from './p3-07-validation-helpers.js';
const connection=process.env['VNEXT_VALIDATION_OWNER_URL']!,receipt=JSON.parse(readFileSync(process.env['VNEXT_TEST_RECEIPT']!,'utf8'));
let catalog:Catalog,f:Awaited<ReturnType<typeof locationUseFixture>>;
beforeAll(async()=>{const provider=validationKeys(receipt),pool=new Pool({connectionString:connection,max:1});try{catalog=await openCatalog(connection,provider);const role=(await pool.query('select current_user r')).rows[0]!.r;f=await locationUseFixture(receipt,role,catalog,provider,connection,process.env['VNEXT_P3_07_UPGRADED']==='1');}finally{await pool.end();}});
afterAll(async()=>{await f?.close();await catalog?.close();});
const end=(e:LocationUseEntry,id:string,head:string,at:string):LocationUseEntry=>({...e,action:'END',target:{owner:'location-master/location-use',id,expectedHead:head},endAt:at,row:{...e.row,record_status:'RETIRED'}});
const preview=async(entries:LocationUseEntry[])=>{const v=await f.input(entries),i=await f.owner.stage('maker',v);await f.owner.verify('reviewer',f.verification(v,i));return f.owner.preview('maker',{inputId:i.inputId});};
const window=(id:string)=>({id,validFrom:'2026-01-01T00:00:00',validTo:'2026-04-01T00:00:00',mode:'CURRENT_ADMISSION' as const});

test('AC01: two independently reviewed organizations share the whole location across purposes',async()=>{const a=await f.endpoint(),b=await f.endpoint('ORG',{campus:a.campus,location:a.location}),left=await f.entry(a),right=await f.entry(b),out=await f.apply(await f.input([left,right]));expect(out.facts).toHaveLength(2);for(const fact of out.facts)expect(await f.owner.evaluateWindow('maker',window(fact.id))).toMatchObject({declarationCovered:true,currentAdmissionCovered:true,clinicalReadiness:'NOT_READY'});});
test('AC02: any exclusive declaration rejects overlapping shared or exclusive use across purposes',async()=>{const a=await f.endpoint(),b=await f.endpoint('ORG',{campus:a.campus,location:a.location});await f.apply(await f.input([await f.entry(a)]));expect((await preview([await f.entry(b,{kind:'EXCLUSIVE',version:'WHOLE_LOCATION_V1'})])).issues).toContainEqual(expect.objectContaining({code:'LOCATION_USE_CONFLICT'}));const c=await f.endpoint(),d=await f.endpoint('ORG',{campus:c.campus,location:c.location});await f.apply(await f.input([await f.entry(c,{kind:'EXCLUSIVE',version:'WHOLE_LOCATION_V1'})]));for(const kind of ['SHARED','EXCLUSIVE'] as const)expect((await preview([await f.entry(d,{kind,version:'WHOLE_LOCATION_V1'})])).issues).toContainEqual(expect.objectContaining({code:'LOCATION_USE_CONFLICT'}));});
test.each(['ORG','UNIT','WARD','NURSING'] as const)('AC03: actual %s Owner admits the complete binding window without creating another identity',async targetType=>{const a=await f.endpoint(targetType),out=await f.apply(await f.input([await f.entry(a)])),id=out.facts[0]!.id;expect((await f.owner.read('maker',{id,businessAt:'2026-02-01T00:00:00'})).applicability).toEqual(a);expect(await f.owner.evaluateWindow('maker',window(id))).toMatchObject({declarationCovered:true,currentAdmissionCovered:true});});
test('AC03: mismatched target type and ID and foreign campus cannot publish',async()=>{const a=await f.endpoint('UNIT'),e=await f.entry(a),wrong={...e,row:{...e.row,target_type:'WARD' as const}};expect((await preview([wrong])).issues).toContainEqual(expect.objectContaining({code:'LOCATION_USE_ANCHOR_MISMATCH'}));const foreign=await f.endpoint('ORG'),scope={...a,location:foreign.location},changed={...e,applicability:scope,row:{...e.row,location_id:foreign.location.id}};expect((await preview([changed])).decision).toBe('BLOCKED');expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(0);});
test('AC04: a future location cannot be used before its exact microsecond start',async()=>{const a=await f.endpoint(),future=await f.newLocation(a.campus.id,'ROOM','2027-01-01T00:00:00.000001'),s={...a,location:future},e=await f.entry(s);expect((await preview([e])).decision).toBe('BLOCKED');const valid={...e,row:{...e.row,valid_from:'2027-01-01T00:00:00.000001',valid_to:'2027-03-01T00:00:00'}};const out=await f.apply(await f.input([valid]));expect((await f.owner.read('maker',{id:out.facts[0]!.id,businessAt:'2027-01-01T00:00:00.000000'})).state).toBe('NOT_EFFECTIVE');});
test('AC05: permanent END releases only use and preserves stable identities, original B/R, and exact replay',async()=>{const a=await f.endpoint(),e=await f.entry(a),request=await f.prepare(await f.input([e])),out=await f.owner.applyUnit('maker',request);if(out.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');const id=out.facts[0]!.id,original=await f.owner.exact('maker',{id,version:'1'}),at='2026-03-01T00:00:00.000001';await f.apply(await f.input([end(e,id,'1',at)]));expect((await f.owner.read('maker',{id,businessAt:'2026-03-01T00:00:00.000000'})).state).toBe('ACTIVE');expect((await f.owner.read('maker',{id,businessAt:at})).state).toBe('ENDED');expect((await f.owner.read('maker',{id,businessAt:at,recordAsOf:out.recordedAt})).state).toBe('ACTIVE');expect(await f.owner.exact('maker',{id,version:'1'})).toEqual(original);expect((await f.owner.history('maker',{id})).applicability).toEqual(a);expect(await f.owner.applyUnit('maker',request)).toEqual(out);const {responseStatus:_ack,...durable}=out;expect(await f.owner.resumeOutcome('maker',request)).toEqual(durable);expect((await f.owner.reconcileCommittedUnit('maker',request)).status).toBe('MATCHED');await expect(f.apply(await f.input([end(e,id,'2','2026-04-01T00:00:00')]))).rejects.toThrow('LOCATION_USE_ENDED');});
test('END edge: cancelling a never-started future relation permanently releases its planned occupation',async()=>{
 const a=await f.endpoint(),entry={...await f.entry(a,{kind:'EXCLUSIVE',version:'WHOLE_LOCATION_V1'}),row:{...await f.row(a),valid_from:'2027-01-01T00:00:00',valid_to:'2028-01-01T00:00:00'}},created=await f.apply(await f.input([entry])),id=created.facts[0]!.id,original=await f.owner.exact('maker',{id,version:'1'}),cancelAt='2026-12-01T00:00:00.000001';
 const cancellation=end(entry,id,'1',cancelAt),bytes=locationUseFile([cancellation.row],'JSON'),received=await f.owner.receiveFile('maker',locationUseFileRequest(f,[cancellation],'JSON'),bytes);expect(received.issues,JSON.stringify(received.issues)).toEqual([]);expect(received.input).not.toBeNull();
 const raw=await catalog.authorizeSensitiveRead('maker',{scope:'SYNTHETIC',requestId:randomUUID(),artifactId:received.sourceArtifactId,campus:'NORTH',purpose:'IDENTITY_VERIFY'});try{expect(Buffer.from(raw)).toEqual(bytes);}finally{raw.fill(0);}
 const stored=await f.owner.readInput('maker',{inputId:received.input!.inputId});expect(stored.entries[0]!.row).toEqual(cancellation.row);expect(stored.sourceRows).toEqual([1]);expect(stored.entries[0]!.row.version_no).toBe(9);await f.owner.verify('reviewer',f.verification(stored,received.input!));const requestId=randomUUID(),candidate=await f.owner.plan('maker',{inputId:received.input!.inputId,requestId});await f.owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await f.owner.approveApplyUnit('reviewer',candidate);expect((await f.owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId})).status).toBe('COMMITTED');expect((await f.owner.read('maker',{id,businessAt:'2026-12-01T00:00:00.000000'})).state).toBe('NOT_EFFECTIVE');expect((await f.owner.read('maker',{id,businessAt:cancelAt})).state).toBe('ENDED');expect((await f.owner.read('maker',{id,businessAt:'2027-01-01T00:00:00'})).state).toBe('ENDED');expect((await f.owner.read('maker',{id,businessAt:'2027-01-01T00:00:00',recordAsOf:created.recordedAt})).state).toBe('ACTIVE');expect(await f.owner.evaluateWindow('maker',{...window(id),validFrom:entry.row.valid_from,validTo:entry.row.valid_to})).toMatchObject({declarationCovered:false,currentAdmissionCovered:false});expect(await f.owner.exact('maker',{id,version:'1'})).toEqual(original);expect((await f.owner.history('maker',{id})).applicability).toEqual(a);
 const b=await f.endpoint('ORG',{campus:a.campus,location:a.location}),successor={...await f.entry(b,{kind:'EXCLUSIVE',version:'WHOLE_LOCATION_V1'}),row:{...await f.row(b),valid_from:entry.row.valid_from,valid_to:entry.row.valid_to}},replacement=await f.apply(await f.input([successor]));expect(replacement.facts[0]!.id).not.toBe(id);expect((await f.owner.read('maker',{id:replacement.facts[0]!.id,businessAt:entry.row.valid_from})).state).toBe('ACTIVE');
});

test('END edge: advancing an existing finite end preserves the earlier declaration and releases at the exact new boundary',async()=>{
 const a=await f.endpoint(),entry={...await f.entry(a,{kind:'EXCLUSIVE',version:'WHOLE_LOCATION_V1'}),row:{...await f.row(a),valid_to:'2030-06-01T00:00:00'}},created=await f.apply(await f.input([entry])),id=created.facts[0]!.id,original=await f.owner.exact('maker',{id,version:'1'}),earlierEnd='2030-03-01T00:00:00.000001';
 await f.apply(await f.input([end(entry,id,'1',earlierEnd)]));expect((await f.owner.read('maker',{id,businessAt:'2030-03-01T00:00:00.000000'})).state).toBe('ACTIVE');expect((await f.owner.read('maker',{id,businessAt:earlierEnd})).state).toBe('ENDED');expect((await f.owner.read('maker',{id,businessAt:earlierEnd,recordAsOf:created.recordedAt})).state).toBe('ACTIVE');expect(await f.owner.exact('maker',{id,version:'1'})).toEqual(original);
 const b=await f.endpoint('ORG',{campus:a.campus,location:a.location}),successor={...await f.entry(b,{kind:'EXCLUSIVE',version:'WHOLE_LOCATION_V1'}),row:{...await f.row(b),valid_from:earlierEnd,valid_to:entry.row.valid_to}},replacement=await f.apply(await f.input([successor]));expect((await f.owner.read('maker',{id:replacement.facts[0]!.id,businessAt:earlierEnd})).state).toBe('ACTIVE');await expect(f.apply(await f.input([end(entry,id,'2','2030-04-01T00:00:00')]))).rejects.toThrow('LOCATION_USE_ENDED');
});

test('latest finite declaration never falls back to old open statement and pure contraction survives dictionary disable',async()=>{const a=await f.endpoint(),e=await f.entry(a),out=await f.apply(await f.input([e])),id=out.facts[0]!.id,p=await f.dictionary.read('maker',{id:a.usageType.id});await f.dictionary.command('maker',{action:'DISABLE',requestId:randomUUID(),target:p.id,expectedHead:p.head,reason:'TEST suspension before safe contraction'});await f.apply(await f.input([{...e,action:'REVISE',target:{owner:'location-master/location-use',id,expectedHead:'1'},row:{...e.row,valid_to:'2026-03-01T00:00:00'}}]));expect((await f.owner.read('maker',{id,businessAt:'2026-04-01T00:00:00'})).state).toBe('NOT_EFFECTIVE');expect((await f.owner.read('maker',{id,businessAt:'2026-04-01T00:00:00',recordAsOf:out.recordedAt})).state).toBe('ACTIVE');await f.apply(await f.input([end({...e,row:{...e.row,valid_to:'2026-03-01T00:00:00'}},id,'2','2026-03-01T00:00:00')]));expect((await f.owner.history('maker',{id})).versions).toHaveLength(3);});
test('disabled purposes retain exclusive reservations and re-enable restores admission while B/R retains disabled state',async()=>{const a=await f.endpoint(),e=await f.entry(a,{kind:'EXCLUSIVE',version:'WHOLE_LOCATION_V1'}),out=await f.apply(await f.input([e])),id=out.facts[0]!.id,p=await f.dictionary.read('maker',{id:a.usageType.id}),disabled=await f.dictionary.command('maker',{action:'DISABLE',requestId:randomUUID(),target:p.id,expectedHead:p.head,reason:'TEST disabled purpose still reserves'});const disabledAt=disabled.events.at(-1)!.recordedAt;expect(await f.owner.evaluateWindow('maker',window(id))).toMatchObject({currentAdmissionCovered:true});expect(await f.owner.evaluateWindow('maker',{...window(id),validFrom:disabledAt,validTo:null})).toMatchObject({declarationCovered:true,currentAdmissionCovered:false});const b=await f.endpoint('ORG',{campus:a.campus,location:a.location});expect((await preview([await f.entry(b)])).issues).toContainEqual(expect.objectContaining({code:'LOCATION_USE_CONFLICT'}));const enabled=await f.dictionary.command('maker',{action:'ENABLE',requestId:randomUUID(),target:p.id,expectedHead:disabled.head,reason:'TEST restore current admission'});expect(await f.owner.evaluateWindow('maker',{...window(id),validFrom:enabled.events.at(-1)!.recordedAt,validTo:null})).toMatchObject({currentAdmissionCovered:true});expect(await f.owner.evaluateWindow('maker',{...window(id),validFrom:disabledAt,validTo:enabled.events.at(-1)!.recordedAt,mode:'HISTORICAL',recordAsOf:disabledAt})).toMatchObject({currentAdmissionCovered:false});});
test('primary uniqueness uses stable purpose identity across new locations and display-name revisions',async()=>{const a=await f.endpoint(),e={...await f.entry(a),row:{...await f.row(a),is_primary:'Y' as const}};await f.apply(await f.input([e]));const b={...a,location:await f.newLocation(a.campus.id)},candidate={...await f.entry(b),row:{...await f.row(b),is_primary:'Y' as const}};expect((await preview([candidate])).issues).toContainEqual(expect.objectContaining({code:'PRIMARY_LOCATION_CONFLICT'}));const different=await f.purpose(),other={...b,usageType:{owner:'location-master/usage-type' as const,id:different.id}},otherEntry={...await f.entry(other),row:{...await f.row(other),is_primary:'Y' as const}};expect((await f.apply(await f.input([otherEntry]))).facts).toHaveLength(1);});
test('atomic END plus CREATE succeeds and one invalid target cannot partly release the predecessor',async()=>{const a=await f.endpoint(),e=await f.entry(a),out=await f.apply(await f.input([e])),id=out.facts[0]!.id,T='2026-04-01T00:00:00',b={...a,location:await f.newLocation(a.campus.id)},incoming={...await f.entry(b),row:{...await f.row(b),valid_from:T}},invalid={...incoming,row:{...incoming.row,target_id:randomUUID()}};expect((await preview([end(e,id,'1',T),invalid])).decision).toBe('BLOCKED');expect((await f.owner.history('maker',{id})).versions).toHaveLength(1);const moved=await f.apply(await f.input([incoming,end(e,id,'1',T)]));expect(moved.facts).toHaveLength(2);expect((await f.owner.read('maker',{id,businessAt:T})).state).toBe('ENDED');const successor=moved.facts.find(x=>x.id!==id)!;expect((await f.owner.read('maker',{id:successor.id,businessAt:T})).state).toBe('ACTIVE');});
test('two real concurrent exclusive candidates cannot both commit',async()=>{const a=await f.endpoint(),b=await f.endpoint('ORG',{campus:a.campus,location:a.location}),policy={kind:'EXCLUSIVE' as const,version:'WHOLE_LOCATION_V1' as const},left=await f.prepare(await f.input([await f.entry(a,policy)])),right=await f.prepare(await f.input([await f.entry(b,policy)])),result=await Promise.allSettled([f.owner.applyUnit('maker',left),f.owner.applyUnit('maker',right)]);expect(result.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(result.filter(r=>r.status==='rejected')).toHaveLength(1);expect((await f.owner.list('maker',{campus:'NORTH',locationId:a.location.id})).items).toHaveLength(1);});
test('current human identity and restricted signed SQL recheck permissions after freeze',async()=>{const a=await f.endpoint(),v=await f.input([await f.entry(a)]),i=await f.owner.stage('maker',v);peer(receipt.name,`INSERT INTO location_master.use_access SELECT 'maker-alias',${quote(a.campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;`);await expect(f.owner.verify('maker-alias',f.verification(v,i))).rejects.toThrow('MAKER_CHECKER_REQUIRED');const q=await f.prepare(v),candidate=await f.owner.readApplyCandidate('reviewer',{candidateId:q.candidateId});expect(await signedUseAttempt(connection,receipt,candidate,q)).toBe('AUTHORIZED');peer(receipt.name,`DELETE FROM location_master.use_access WHERE actor='reviewer' AND campus_id=${quote(a.campus.id)}::uuid AND permission='REVIEW';`);try{expect(await signedUseAttempt(connection,receipt,candidate,q)).toBe('ACCESS_DENIED');await expect(f.owner.applyUnit('maker',q)).rejects.toThrow('ACCESS_DENIED');}finally{f.grant(a.campus.id);}expect(await f.owner.resumeOutcome('maker',q)).toBeNull();});
test('restricted SQL rejects forged authority and direct mutation',async()=>{const pool=new Pool({connectionString:connection,max:1});try{expect((await pool.query('select current_user r')).rows[0]!.r).toMatch(/^hdi_validation_[a-f0-9]{16}$/);await expect(pool.query('select location_master.use_mutate($1,$2)',['{}','0'.repeat(64)])).rejects.toMatchObject({message:'ACCESS_DENIED'});await expect(pool.query('insert into location_master.use_access values($1,$2,$3,$4)',['outsider',randomUUID(),'NORTH','READ'])).rejects.toMatchObject({code:'42501'});}finally{await pool.end();}});

test('a late CREATE database failure rolls back the preceding END, successor identity, audit and outcome together',async()=>{
 const a=await f.endpoint(),e=await f.entry(a),first=await f.apply(await f.input([e])),id=first.facts[0]!.id,T='2026-04-01T00:00:00',b={...a,location:await f.newLocation(a.campus.id)},next={...await f.entry(b),row:{...await f.row(b),valid_from:T}},q=await f.prepare(await f.input([next,end(e,id,'1',T)])),auditBefore=peer(receipt.name,"SELECT count(*) FROM vnext_control.audit WHERE action IN ('LOCATION_USE_CREATE','LOCATION_USE_END');");
 peer(receipt.name,`CREATE FUNCTION vnext_control.test_p3_07_atomic_failure() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN IF NEW.action='CREATE' AND EXISTS(SELECT 1 FROM location_master.use_version WHERE use_id=${quote(id)}::uuid AND action='END') THEN RAISE EXCEPTION 'TEST_P3_07_ATOMIC_FAILURE';END IF;RETURN NEW;END $$;CREATE TRIGGER test_p3_07_atomic_failure BEFORE INSERT ON location_master.use_version FOR EACH ROW EXECUTE FUNCTION vnext_control.test_p3_07_atomic_failure();`);
 try{await expect(f.owner.applyUnit('maker',q)).rejects.toThrow('APPLY_FAILED');expect(await f.owner.resumeOutcome('maker',q)).toBeNull();expect((await f.owner.history('maker',{id})).versions).toHaveLength(1);expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(1);expect(peer(receipt.name,"SELECT count(*) FROM vnext_control.audit WHERE action IN ('LOCATION_USE_CREATE','LOCATION_USE_END');")).toBe(auditBefore);}finally{peer(receipt.name,'DROP TRIGGER test_p3_07_atomic_failure ON location_master.use_version;DROP FUNCTION vnext_control.test_p3_07_atomic_failure();');}
 const recovered=await f.owner.applyUnit('maker',q);expect(recovered.status).toBe('COMMITTED');expect((await f.owner.history('maker',{id})).versions).toHaveLength(2);expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(2);
});

test('post-COMMIT response loss recovers the exact result and never creates another version',async()=>{
 const a=await f.endpoint(),q=await f.prepare(await f.input([await f.entry(a)])),out=await f.owner.applyUnit('maker',q,()=>{throw new Error('TEST_P3_07_ACK_LOSS');});
 if(out.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');expect(out.responseStatus).toBe('POST_COMMIT_FAILED');const {responseStatus:_response,...durable}=out;expect(await f.owner.resumeOutcome('maker',q)).toEqual(durable);expect(await f.owner.applyUnit('maker',q)).toMatchObject(durable);expect((await f.owner.reconcileCommittedUnit('maker',q)).status).toBe('MATCHED');expect((await f.owner.history('maker',{id:out.facts[0]!.id})).versions).toHaveLength(1);
});
