import {randomUUID} from 'node:crypto';
import {openUnitWardRelations,ORG10_FIELDS,type UnitWardEntry,type UnitWardRow,type UnitWardStage,type UnitWardVerification,type UnitWardScope,type UnitWardRule} from '../../apps/governance-api/src/modules/care-organization/index.js';
import type {Catalog,KeyProviderPort} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {unitWardUpstreamPorts} from '../../apps/governance-api/src/composition/unit-ward-dependencies.js';
import {conditionMappings} from '../../apps/governance-api/src/modules/governance-catalog/validation-sources.generated.js';
import {wardFixture} from './p3-02-fixture.js';
import {provisionUnitWard} from './p3-04-provisioning.mjs';
import {peer,quote} from './lineage.mjs';
export async function unitWardFixture(receipt:{name:string;oid:string},role:string,catalog:Catalog,provider:KeyProviderPort,connection:string,persistent=false,supplied?:Awaited<ReturnType<typeof wardFixture>>,sourceOverride?:{id:string;versionId:string}){
 const wards=supplied??await wardFixture(receipt,role,catalog,provider,connection,persistent),base=wards.base,source=sourceOverride??base.dep.source,cmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'TEST_UNIT_WARD',...extra});
 let dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.kind==='DATASET'&&i.code==='ORG10'&&i.status==='PUBLISHED');
 if(!dataset){const d=await catalog.command('maker',cmd('CREATE',{kind:'DATASET',code:'ORG10',values:{name:'TEST POLICY ONLY 科室病区关系'},validFrom:'2026-01-01T00:00:00'})),s=await catalog.command('maker',cmd('SUBMIT',{target:d.id,expectedHead:d.head}));await catalog.command('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:s.head,reviewDigest:s.reviewDigest}));dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.id===d.id)!;}
 const fields=dataset.payload.fields!.map(f=>f.original);if(fields.length!==ORG10_FIELDS.length)throw new Error('FULL_FIELD_OMISSION');
 const enums:Record<string,string[]>={relation_type:['收治','管理','共享'],is_primary:['Y','N'],record_status:['DRAFT','REVIEW','ACTIVE','SUSPENDED','RETIRED']};
 const definition={ruleVersion:sourceOverride?'ORG10_CORE_SRC_'+source.versionId.replaceAll('-','').toUpperCase():'ORG10_CORE_V1',templateVersion:'ORG10_CORE_V1',sourceVersionId:source.versionId,businessKey:['unit_ward_rel_id'],fields:fields.map(f=>({code:f.code,type:f.type,required:f.required,privacy:f.privacy,condition:f.required==='C'?'EVALUATED':f.required==='R'?'ALWAYS':'OPTIONAL',enumValues:enums[f.code]??[]})),references:fields.filter(f=>f.ref).map(f=>({field:f.code,target:f.ref,status:'UNIT_WARD_CORE'})),rules:[{id:'UNIT_WARD_EMPTY_END_V1',field:'valid_to',text:'CSV/XLSX blank valid_to is an explicit open end; JSON requires native null.',status:'MACHINE',version:'P3_04_EMPTY_END_V1'},{id:'UNIT_WARD_APPROVAL_V1',field:'approval_ref',text:'Source approval never replaces platform approval.',status:'MACHINE',version:'P3_04_V1'},...conditionMappings.filter(r=>r.dataset==='ORG10').map(r=>({id:r.id,field:r.field,text:r.text,status:'MACHINE',version:r.version}))],codeSets:Object.entries(enums).map(([field,codes])=>({field,codes,codeSystem:'SYNTHETIC_'+field.toUpperCase(),version:'TEST_POLICY_ONLY_1',status:'SYNTHETIC_ADOPTED',sourceVersionId:source.versionId,validFrom:'2026-01-01T00:00:00',validTo:null}))};
 let contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG10'&&c.profile==='CORE'&&c.status==='PUBLISHED');
 if(!contract||contract.definition.templateVersion!=='ORG10_CORE_V1'||contract.definition.sourceVersionId!==source.versionId){const d=await catalog.contractCommand('maker',contract?cmd('REVISE',{target:contract.id,expectedHead:contract.head,datasetVersionId:dataset.versionId,definition,validFrom:'2026-01-01T00:00:00',validTo:null}):cmd('CREATE',{datasetVersionId:dataset.versionId,profile:'CORE',definition,validFrom:'2026-01-01T00:00:00',validTo:null})),preImpact=contract?await catalog.contractImpact('reviewer','SYNTHETIC',d.id,'PUBLISH'):undefined,a=await catalog.contractCommand('reviewer',cmd('APPROVE',{target:d.id,expectedHead:d.head,reviewDigest:d.reviewDigest,...(preImpact?{impactDigest:preImpact.impactDigest}:{})})),impact=contract?await catalog.contractImpact('reviewer','SYNTHETIC',d.id,'PUBLISH'):undefined;await catalog.contractCommand('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:a.head,reviewDigest:a.reviewDigest,...(impact?{impactDigest:impact.impactDigest}:{})}));contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.id===d.id)!;}
 const newJob=()=>catalog.importJobCommand('maker',cmd('CREATE',{profile:'CORE',contractId:contract!.id,contractVersionId:contract!.versionId,input:{kind:'METADATA_ONLY',declaredSha256:'a'.repeat(64)}}));
 peer(receipt.name,`INSERT INTO vnext_control.protected_grant SELECT a,${quote(dataset.id)}::uuid,s,'IDENTITY_VERIFY',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['NORTH','SOUTH']) s CROSS JOIN unnest(ARRAY['READ','STORE']) p ON CONFLICT DO NOTHING;`);
 const j=await newJob(),artifact=await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds:7200},Buffer.from('TEST POLICY ONLY independently reviewed Unit Ward sharing boundaries'));
 provisionUnitWard(receipt,role,provider);const owner=openUnitWardRelations(connection,provider,unitWardUpstreamPorts(base.owner,wards.owner));
 const grant=(s:UnitWardScope)=>peer(receipt.name,`INSERT INTO care_organization.unit_ward_access SELECT a,${quote(s.campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED']) p ON CONFLICT DO NOTHING;INSERT INTO care_organization.unit_ward_access SELECT 'reviewer',${quote(s.campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;`);
 const endpoint=async():Promise<UnitWardScope>=>{const b=await wards.endpoint(),out=await wards.apply(await wards.input([wards.entry(b)])),s:UnitWardScope={unit:b.unit,ward:{owner:'care-organization/ward',id:out.facts[0]!.id},campus:b.campus,purpose:'ADMISSION'};grant(s);return s;};
 const sameWard=async(s:UnitWardScope):Promise<UnitWardScope>=>{const b=await wards.sameCampus({unit:s.unit,campus:s.campus});return {...s,unit:b.unit};};
 const row=(s:UnitWardScope):UnitWardRow=>({unit_ward_rel_id:randomUUID(),unit_id:s.unit.id,ward_id:s.ward.id,relation_type:s.purpose==='MANAGEMENT'?'管理':'收治',is_primary:'N',sharing_rule:null,version_no:9,valid_from:'2026-01-01T00:00:00',valid_to:null,record_status:'ACTIVE',source_system_id:source.id,source_record_id:'TEST/ORG10/2',approval_ref:'TEST_POLICY_ONLY',recorded_at:'2026-01-02T00:00:00'});
 const entry=(s:UnitWardScope):UnitWardEntry=>({action:'CREATE',applicability:s,rule:{kind:'NO_SHARING_REQUIRED'},row:row(s),reason:'TEST independently established relation',evidenceId:artifact.artifactId});
 const shared=(participants:string[]):UnitWardRule=>({kind:'SHARED_BOUNDARY',ruleReference:'TEST_SHARED_WARD',ruleVersion:'TEST_POLICY_ONLY_1',evidenceId:artifact.artifactId,participants:[...participants].sort(),validFrom:'2026-01-01T00:00:00',validTo:null});
 const input=async(entries:UnitWardEntry[]):Promise<UnitWardStage>=>{const j=await newJob();return {requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',profile:'CORE',timePolicy:'LOCAL',entries};};
 const verification=(v:UnitWardStage,i:{inputId:string;digest:string}):UnitWardVerification=>({requestId:randomUUID(),inputId:i.inputId,inputDigest:i.digest,reason:'TEST independent relation scope and sharing review',policyVersion:'ORG10_CORE_V1',rows:v.entries.map((e,index)=>({row:index+1,evidenceId:artifact.artifactId,classificationAccepted:true,scopeAccepted:true,ruleConfirmed:true,rule:e.rule,validFrom:e.row.valid_from,validTo:e.row.valid_to}))});
 const prepare=async(v:UnitWardStage)=>{const i=await owner.stage('maker',v);await owner.verify('reviewer',verification(v,i));const preview=await owner.preview('maker',{inputId:i.inputId});if(preview.decision!=='PASS')throw new Error(preview.issues.map(i=>i.code).join(','));const requestId=randomUUID(),c=await owner.plan('maker',{inputId:i.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:c.candidateId});await owner.approveApplyUnit('reviewer',c);return {candidateId:c.candidateId,requestId};};
 const apply=async(v:UnitWardStage)=>{const result=await owner.applyUnit('maker',await prepare(v));if(result.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');return result;};
 return {base,wards,owner,contract,dataset,artifact,endpoint,sameWard,grant,row,entry,shared,input,newJob,verification,prepare,apply,close:async()=>{await owner.close();if(!supplied)await wards.close();}};
}
