import {openCampus} from '../../apps/governance-api/src/modules/organization-master/index.js';
import {openOrganizationEvolutions} from '../../apps/governance-api/src/modules/department-master/index.js';
import {withCareOrganizationImpacts} from '../../apps/governance-api/src/composition/nursing-unit-dependencies.js';
import {peer,quote} from './lineage.mjs';
import {buildCatalogServer} from '../../apps/governance-api/src/composition/build-vnext-catalog.js';
import {actor} from '../../apps/governance-api/src/platform/fastify/vnext-catalog-routes.js';
import {createNursingUnitClient,createDepartmentImpactClient,createVNextCatalogClient} from '../../packages/generated-api-client/src/index.js';
import {ORG09_FIELDS,type NursingReceive} from '../../apps/governance-api/src/modules/care-organization/index.js';
import {organizationWorkbook} from './organization-workbook-fixture.js';
import {test,expect,afterAll} from 'vitest';
import {readFileSync} from 'node:fs';
import {Pool,Client,type QueryConfig} from 'pg';
import {randomUUID,createHmac} from 'node:crypto';
import type {NursingEntry,NursingHistory,NursingBindingInput} from '../../apps/governance-api/src/modules/care-organization/index.js';
import {openCatalog,canonicalPlan,planBinding} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {validationKeys} from './p3-03-validation-keys.mjs';
import {nursingFixture} from './p3-03-fixture.js';
const connection=process.env['VNEXT_VALIDATION_OWNER_URL']!,receipt=JSON.parse(readFileSync(process.env['VNEXT_TEST_RECEIPT']!,'utf8')),provider=validationKeys(receipt),catalog=await openCatalog(connection,provider);
const p=new Pool({connectionString:connection,max:1}),role=(await p.query('select current_user r')).rows[0].r;await p.end();
const f=await nursingFixture(receipt,role,catalog,provider,connection,process.env['VNEXT_P3_03_POPULATED']==='1');
afterAll(async()=>{await f.close();await catalog.close();});
test('P3-03 administrative management and a planning campus publish CORE without clinical service relations',async()=>{
 const b=await f.endpoint(),v=await f.input([f.entry(b)]),outcome=await f.apply(v),id=outcome.facts[0]!.id;
 expect(await f.owner.read('maker',{id,businessAt:'2026-04-01T00:00:00'})).toMatchObject({id,departmentId:b.department.id,state:'ACTIVE',clinicalReadiness:'NOT_READY',version:{facts:{careLevel:'TEST 原文',officePhone:null,responsibilityStatus:'PENDING'}}});
 expect(id).not.toBe(v.entries[0]!.row.nursing_unit_id);expect((await f.owner.history('maker',{id})).bindings).toHaveLength(1);
});
test('all raw rows need independent verification and FULL input remains retained and blocked',async()=>{
 const b=await f.endpoint(),v=await f.input([f.entry(b),f.entry(b)]),i=await f.owner.stage('maker',v);
 for(const numbers of [[1],[1,1],[2,3]]){const proof=f.verification(v,i);proof.rows=numbers.map(n=>({...proof.rows[0]!,row:n}));await expect(f.owner.verify('reviewer',proof)).rejects.toThrow('VERIFICATION_ROW_MISMATCH');}
 await expect(f.owner.verify('maker-alias',f.verification(v,i))).rejects.toThrow('ACCESS_DENIED');
 const full={...await f.input([f.entry(b)]),profile:'FULL' as const},retained=await f.owner.stage('maker',full);await f.owner.verify('reviewer',f.verification(full,retained));expect((await f.owner.readInput('maker',{inputId:retained.inputId})).profile).toBe('FULL');expect((await f.owner.preview('maker',{inputId:retained.inputId})).issues).toContainEqual(expect.objectContaining({code:'BLOCKED_DEPENDENCY'}));await expect(f.owner.plan('maker',{inputId:retained.inputId,requestId:randomUUID()})).rejects.toThrow('BLOCKED_DEPENDENCY');
});
test('wrong typed targets, input campus mismatches and non-atomic last rows cannot publish',async()=>{
 const b=await f.endpoint(),good=f.entry(b),bad=f.entry(b),wrong=await f.endpoint();bad.row.campus_id=wrong.campus.id;await expect(f.prepare(await f.input([good,bad]))).rejects.toThrow('NURSING_ANCHOR_MISMATCH');expect((await f.owner.list('maker',{campus:'NORTH',departmentId:b.department.id})).items).toHaveLength(0);
 const invalid={...await f.input([good]),entries:[{...good,binding:{...b,department:{owner:'location-master',id:b.department.id}}}]};await expect(f.owner.stage('maker',invalid as never)).rejects.toThrow('CLOSED_INPUT_REQUIRED');
 const v=await f.input([f.entry(b)]);v.entries[0]!.row.valid_from='2026-01-01T00:00:00Z';await expect(f.prepare(v)).rejects.toThrow('LOCAL_TIME_REQUIRED');
});
const populated=async()=>{const binding=await f.endpoint(),entry=f.entry(binding),request=await f.prepare(await f.input([entry])),outcome=await f.owner.applyUnit('maker',request);if(outcome.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');return {binding,d:binding.department.id,a:binding,entry,request,h:await f.owner.history('maker',{id:outcome.facts[0]!.id})};};
function revision(h:NursingHistory,entry:NursingEntry,action:'REVISE'|'REBIND'|'SUSPEND',from='2026-06-01T00:00:00',binding?:NursingBindingInput):NursingEntry{
 const row:NursingEntry['row']={...entry.row,valid_from:from,record_status:action==='SUSPEND'?'SUSPENDED':'ACTIVE'};
 if(binding){row.campus_id=binding.campus.id;row.managing_org_id=binding.department.id;}
 const common={row,reason:'TEST nursing '+action,evidenceId:entry.evidenceId,target:{owner:'care-organization/nursing' as const,id:h.id,expectedHead:h.versions.at(-1)!.number}};
 return action==='REBIND'?{...common,action,binding:binding!}:{...common,action};
}
test('explicit REBIND changes campus and manager atomically while preserving identity and old B/R',async()=>{
 const {entry,h}=await populated(),target=await f.endpoint(),r=revision(h,entry,'REBIND','2026-06-01T00:00:00',target);
 const o=await f.apply(await f.input([r]));expect(o.facts[0]!.id).toBe(h.id);
 expect(await f.owner.read('maker',{id:h.id,businessAt:'2026-07-01T00:00:00'})).toMatchObject({departmentId:target.department.id,binding:{binding:target}});
 expect((await f.owner.read('maker',{id:h.id,businessAt:'2026-05-31T23:59:59.999999'})).departmentId).toBe(entry.row.managing_org_id);
 expect((await f.owner.history('maker',{id:h.id,recordAsOf:h.versions[0]!.recordedAt})).bindings).toHaveLength(1);
});
test('suspension masks future bindings and attributes without deleting their historical evidence',async()=>{
 const {entry,h}=await populated(),target=await f.endpoint();await f.apply(await f.input([revision(h,entry,'REBIND','2026-09-01T00:00:00',target)]));
 const before=await f.owner.history('maker',{id:h.id});await f.apply(await f.input([revision(before,entry,'SUSPEND','2026-06-01T00:00:00')]));
 expect((await f.owner.read('maker',{id:h.id,businessAt:'2026-05-31T23:59:59.999999'})).state).toBe('ACTIVE');
 expect((await f.owner.read('maker',{id:h.id,businessAt:'2026-09-01T00:00:00'})).state).toBe('SUSPENDED');
 expect((await f.owner.coverage('maker',{id:h.id,validFrom:'2026-06-01T00:00:00',validTo:null})).covered).toBe(false);
 expect((await f.owner.history('maker',{id:h.id})).bindings).toHaveLength(2);
 expect((await f.owner.read('maker',{id:h.id,businessAt:'2026-09-01T00:00:00',recordAsOf:before.versions.at(-1)!.recordedAt})).state).toBe('ACTIVE');
});


test('concurrent permanent-code claims and same-head updates allow only one commit',async()=>{
 const d=await f.newDepartment(),a=await f.endpoint(d),first=f.entry(a),second=f.entry(a);second.row.nursing_code=first.row.nursing_code;const x=await f.prepare(await f.input([first])),y=await f.prepare(await f.input([second])),results=await Promise.allSettled([f.owner.applyUnit('maker',x),f.owner.applyUnit('maker',y)]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((await f.owner.list('maker',{campus:'NORTH',departmentId:d})).items).toHaveLength(1);
 const committed=results.find(r=>r.status==='fulfilled');if(committed?.status!=='fulfilled'||committed.value.status!=='COMMITTED')throw new Error();const h=await f.owner.history('maker',{id:committed.value.facts[0]!.id}),r1=revision(h,first,'REVISE'),r2=revision(h,first,'REVISE');r1.row.nursing_name='TEST ONE';r2.row.nursing_name='TEST TWO';const p1=await f.prepare(await f.input([r1])),p2=await f.prepare(await f.input([r2])),updates=await Promise.allSettled([f.owner.applyUnit('maker',p1),f.owner.applyUnit('maker',p2)]);expect(updates.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((await f.owner.history('maker',{id:h.id})).versions).toHaveLength(2);
});
test('same-name identities stay independent and property/code revision never releases a permanent claim',async()=>{
 const {a,h,entry}=await populated(),other=await f.apply(await f.input([f.entry(a)]));expect(other.facts[0]!.id).not.toBe(h.id);const changed=revision(h,entry,'REVISE');changed.row.nursing_name='TEST renamed unit';changed.row.nursing_code='TEST_'+randomUUID();await f.apply(await f.input([changed]));expect(await f.owner.read('maker',{id:h.id,businessAt:'2026-07-01T00:00:00'})).toMatchObject({id:h.id,version:{facts:{nursingName:'TEST renamed unit',nursingCode:changed.row.nursing_code}}});expect((await f.owner.diff('maker',{id:h.id,fromVersion:'1',toVersion:'2'})).before.facts.nursingName).toBe(entry.row.nursing_name);const duplicate=f.entry(a);duplicate.row.nursing_code=entry.row.nursing_code;await expect(f.apply(await f.input([duplicate]))).rejects.toThrow('NURSING_CODE_CONFLICT');
});
test('a failed audit rolls back the whole multi-unit revision and retry creates exactly one set',async()=>{
 const d=await f.newDepartment(),a=await f.endpoint(d),request=await f.prepare(await f.input([f.entry(a),f.entry(a)]));peer(receipt.name,"CREATE FUNCTION care_organization.nursing_test_audit_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='NURSING_CREATE' THEN RAISE EXCEPTION 'TEST_ATOMIC_FAILURE';END IF;RETURN NEW;END $$;CREATE TRIGGER test_audit_failure BEFORE INSERT ON vnext_control.audit FOR EACH ROW EXECUTE FUNCTION care_organization.nursing_test_audit_failure();");
 try{await expect(f.owner.applyUnit('maker',request)).rejects.toThrow('APPLY_FAILED');expect((await f.owner.list('maker',{campus:'NORTH',departmentId:d})).items).toHaveLength(0);expect(await f.owner.resumeOutcome('maker',request)).toBeNull();}finally{peer(receipt.name,'DROP TRIGGER test_audit_failure ON vnext_control.audit;DROP FUNCTION care_organization.nursing_test_audit_failure();');}
 const result=await f.owner.applyUnit('maker',request);expect(result.status).toBe('COMMITTED');if(result.status!=='COMMITTED')throw new Error();expect(result.facts).toHaveLength(2);expect(await f.owner.applyUnit('maker',request)).toEqual(result);
});
test('restricted SQL cannot read/write tables or forge a mutation, and explicit withdrawal prevents publication',async()=>{
 const b=await f.endpoint(),pool=new Pool({connectionString:connection});try{await expect(pool.query('SELECT * FROM care_organization.nursing_version')).rejects.toMatchObject({code:'42501'});await expect(pool.query("INSERT INTO care_organization.nursing_code VALUES('TEST_FORGED',$1)",[randomUUID()])).rejects.toMatchObject({code:'42501'});await expect(pool.query("select care_organization.nursing_mutate('{}','bad')")).rejects.toMatchObject({message:'ACCESS_DENIED'});await expect(pool.query('select care_organization.nursing_admission($1,$2,$3,$4,$5)',['maker',{...b,department:{owner:'location-master',id:b.department.id}},'2026-01-01',null,null])).rejects.toMatchObject({message:'REFERENCE_INVALID'});}finally{await pool.end();}
 const d=await f.newDepartment(),a=await f.endpoint(d),value=await f.input([f.entry(a)]),i=await f.owner.stage('maker',value),request={inputId:i.inputId,requestId:randomUUID()};expect(await f.owner.withdraw('maker',request)).toEqual({inputId:i.inputId,status:'WITHDRAWN'});expect(await f.owner.withdraw('maker',request)).toEqual({inputId:i.inputId,status:'WITHDRAWN'});await expect(f.owner.plan('maker',{inputId:i.inputId,requestId:randomUUID()})).rejects.toThrow('INPUT_WITHDRAWN');expect((await f.owner.readInput('maker',{inputId:i.inputId})).entries).toHaveLength(1);
});
test('generated client executes real HTTP verification, approval, publish and exact replay',async()=>{
 const d=await f.newDepartment(),a=await f.endpoint(d),value=await f.input([f.entry(a)]),contexts:Parameters<typeof buildCatalogServer>=[catalog,'CONTROL_PLANE'];contexts[16]={owner:f.owner,actor:r=>actor(r.headers)};const app=await buildCatalogServer(...contexts);
 try{const url=await app.listen({host:'127.0.0.1',port:0}),maker=createNursingUnitClient(url,'maker'),reviewer=createNursingUnitClient(url,'reviewer'),invalid={...value,entries:[{...value.entries[0]!,binding:{...a,department:{owner:'location-master',id:a.department.id}}}]};expect((await maker.stage(invalid as never)).response.status).toBe(400);const i=await maker.stage(value);expect(i.response.status).toBe(200);if(!i.data)throw new Error();expect((await reviewer.verify(f.verification(value,i.data))).response.status).toBe(200);
  const requestId=randomUUID(),c=await maker.plan({inputId:i.data.inputId,requestId});expect(c.response.status).toBe(200);if(!c.data)throw new Error();expect((await reviewer.review({candidateId:c.data.candidateId})).response.status).toBe(200);expect((await reviewer.approve(c.data)).response.status).toBe(200);const request={candidateId:c.data.candidateId,requestId},outcome=await maker.apply(request);expect(outcome.response.status).toBe(200);expect(outcome.data?.status).toBe('COMMITTED');expect((await maker.apply(request)).data).toEqual(outcome.data);if(outcome.data?.status!=='COMMITTED')throw new Error();const id=outcome.data.facts[0]!.id;expect((await maker.query({id,businessAt:'2026-04-01T00:00:00'})).data?.clinicalReadiness).toBe('NOT_READY');expect((await maker.history({id})).data?.versions).toHaveLength(1);expect((await maker.reconcile(request)).response.status).toBe(200);expect((await createNursingUnitClient(url,'outsider').query({id})).response.status).toBe(403);
 }finally{await app.close();}
});
test.each(['JSON','CSV','XLSX'] as const)('file %s follows the same Owner and preserves all 15 fields and physical row provenance',async(format)=>{
 const d=await f.newDepartment(),a=await f.endpoint(d),entry=f.entry(a),{row,...operation}=entry,bytes=format==='JSON'?Buffer.from(JSON.stringify([row])):format==='CSV'?Buffer.from(ORG09_FIELDS.join(',')+'\r\n'+ORG09_FIELDS.map(field=>row[field]).join(',')+'\r\n'):organizationWorkbook({ORG09:[ORG09_FIELDS,ORG09_FIELDS.map(field=>row[field])]}),input:NursingReceive={requestId:randomUUID(),fileRequestId:randomUUID(),campus:'NORTH',timePolicy:'LOCAL',retentionSeconds:7200,job:{action:'CREATE',scope:'SYNTHETIC',requestId:randomUUID(),reason:'SYNTHETIC_BUSINESS_UNIT',profile:'CORE',contractId:f.contract!.id,contractVersionId:f.contract!.versionId,input:{kind:'FILE',format,parserPolicy:'STRICT_NURSING_V1'}},operations:[operation]};
 const received=await f.owner.receiveFile('maker',input,bytes);expect(received.issues).toHaveLength(0);expect(received.input).not.toBeNull();if(!received.input)throw new Error();const retained=await f.owner.readInput('maker',{inputId:received.input.inputId});expect(Object.keys(retained.entries[0]!.row).sort()).toEqual([...ORG09_FIELDS].sort());expect(retained.entries[0]!.row.care_level).toBe('TEST 原文');
 const value={...await f.input([entry]),jobId:received.jobId,revisionId:received.revisionId};await f.owner.verify('reviewer',f.verification(value,received.input));const requestId=randomUUID(),c=await f.owner.plan('maker',{inputId:received.input.inputId,requestId});await f.owner.readApplyCandidate('reviewer',{candidateId:c.candidateId});await f.owner.approveApplyUnit('reviewer',c);const outcome=await f.owner.applyUnit('maker',{candidateId:c.candidateId,requestId});expect(outcome.status).toBe('COMMITTED');
});
test('a lost COMMIT acknowledgement recovers the exact durable Nursing identity',async()=>{
 const d=await f.newDepartment(),a=await f.endpoint(d),request=await f.prepare(await f.input([f.entry(a)])),original=Client.prototype.query;let loseAck=true,injected=false;
 Client.prototype.query=(function(this:Client,config:string|QueryConfig,...args:unknown[]){const text=typeof config==='string'?config:config.text,result=Reflect.apply(original,this,[config,...args]);if(loseAck&&text.trim().toLowerCase()==='commit'){loseAck=false;injected=true;return Promise.resolve(result).then(()=>{throw Object.assign(new Error('ACK_LOST'),{code:'ECONNRESET'});});}return result;}) as typeof Client.prototype.query;
 try{expect((await f.owner.applyUnit('maker',request)).status).toBe('COMMIT_UNKNOWN');expect(injected).toBe(true);}finally{Client.prototype.query=original;}
 const recovered=await f.owner.resumeOutcome('maker',request),replay=await f.owner.applyUnit('maker',request);expect(recovered?.status).toBe('COMMITTED');expect(replay.status).toBe('COMMITTED');if(recovered?.status==='COMMITTED'&&replay.status==='COMMITTED')expect(replay.facts).toEqual(recovered.facts);expect((await f.owner.list('maker',{campus:'NORTH',departmentId:d})).items).toHaveLength(1);
});

test('SQL rejects approved-plan fact tampering even with a valid transaction signature',async()=>{
 const d=await f.newDepartment(),a=await f.endpoint(d),request=await f.prepare(await f.input([f.entry(a)])),candidate=await f.owner.readApplyCandidate('reviewer',{candidateId:request.candidateId}),value=candidate.unit.commands[0]!.value,writes=JSON.parse(value['writes']!);writes[0].facts.nursingName='TEST_UNAPPROVED';
 const p=new Pool({connectionString:connection,max:1}),client=await p.connect(),key=Buffer.from(planBinding(provider,'NURSING_SQL_AUTHORITY_V1',{}),'hex');
 try{await client.query('BEGIN');const transaction=(await client.query('select pg_current_xact_id()::text v')).rows[0].v,ticket=canonicalPlan({operation:'APPLY',actor:'maker',transaction,inputId:value['inputId'],writes,writeIndex:1,writesDigest:value['writesDigest'],candidateId:request.candidateId,digest:candidate.digest});await expect(client.query('select care_organization.nursing_mutate($1,$2)',[ticket,createHmac('sha256',key).update(ticket).digest('hex')])).rejects.toMatchObject({message:'STALE_VALIDATION'});}finally{await client.query('ROLLBACK');client.release();await p.end();key.fill(0);}
 expect((await f.owner.list('maker',{campus:'NORTH',departmentId:d})).items).toHaveLength(0);expect((await f.owner.applyUnit('maker',request)).status).toBe('COMMITTED');
});

test('current independent verification authority is rechecked after freeze',async()=>{
 const d=await f.newDepartment(),a=await f.endpoint(d),value=await f.input([f.entry(a)]),i=await f.owner.stage('maker',value);await f.owner.verify('reviewer',f.verification(value,i));const requestId=randomUUID(),c=await f.owner.plan('maker',{inputId:i.inputId,requestId});
 await f.owner.readApplyCandidate('reviewer',{candidateId:c.candidateId});peer(receipt.name,`DELETE FROM care_organization.nursing_access WHERE actor='reviewer' AND campus_id=${quote(a.campus.id)}::uuid AND permission='VERIFY';`);
 try{await expect(f.owner.approveApplyUnit('reviewer',c)).rejects.toThrow('ACCESS_DENIED');}finally{peer(receipt.name,`INSERT INTO care_organization.nursing_access VALUES('reviewer',${quote(a.campus.id)}::uuid,'NORTH','VERIFY');`);}
 await f.owner.readApplyCandidate('reviewer',{candidateId:c.candidateId});await f.owner.approveApplyUnit('reviewer',c);expect((await f.owner.applyUnit('maker',{candidateId:c.candidateId,requestId})).status).toBe('COMMITTED');
});



test('real Nursing Owner references participate in Department and Campus impact assessment',async()=>{
 const {d,a,h,entry}=await populated(),campus=openCampus(connection,provider,{owners:['NURSING_UNIT'],readInTransaction:f.owner.readCampusDependenciesInTransaction}),evolution=openOrganizationEvolutions(connection,provider,withCareOrganizationImpacts(()=>f.base.owner,()=>f.owner));
 try{
  const impact=await campus.assessCampusImpact('maker',{id:a.campus.id,validFrom:'2026-06-01T00:00:00',validTo:null});expect(impact.unavailable).not.toContain('NURSING_UNIT');expect(impact.dependencies).toContainEqual(expect.objectContaining({owner:'NURSING_UNIT',id:h.id,outstanding:true}));
  const j=await f.dep.newJob(),i=await f.lifecycle.stage('maker',{requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',profile:'CORE',commands:[{action:'SUSPEND',department:{owner:'department-master',id:d,expectedVersion:'1',expectedLifecycleHead:'0'},effectiveAt:'2026-06-01T00:00:00',reason:'TEST upstream change',evidenceId:f.dep.artifact.artifactId}],impacts:f.impacts});
  const assessment=await evolution.assessDepartmentChange('maker',{requestId:randomUUID(),reason:'TEST finite unit impact',target:{kind:'INPUT',id:i.inputId}});
  expect(assessment.coverage).toContainEqual({owner:'NURSING_UNIT',status:'EVALUATED',reason:'OWNER_AVAILABLE'});expect(assessment.references).toContainEqual(expect.objectContaining({owner:'NURSING_UNIT',id:h.id,constraint:'UNSATISFIED'}));expect(assessment.coverage).toContainEqual({owner:'PERSONNEL',status:'NOT_EVALUABLE',reason:'OWNER_NOT_IMPLEMENTED'});
 }finally{await campus.close();await evolution.close();}
});

test('a future rebind retains the current manager obligation and serializes exact accepted versions over HTTP',async()=>{
 const {d,h,entry}=await populated(),target=await f.endpoint();await f.apply(await f.input([revision(h,entry,'REBIND','2030-01-01T00:00:00',target)]));
 const j=await f.dep.newJob(),i=await f.lifecycle.stage('maker',{requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',profile:'CORE',commands:[{action:'SUSPEND',department:{owner:'department-master',id:d,expectedVersion:'1',expectedLifecycleHead:'0'},effectiveAt:'2028-01-01T00:00:00',reason:'TEST before future transfer',evidenceId:f.dep.artifact.artifactId}],impacts:f.impacts}),evolution=openOrganizationEvolutions(connection,provider,withCareOrganizationImpacts(()=>f.base.owner,()=>f.owner));
 const contexts:Parameters<typeof buildCatalogServer>=[catalog,'CONTROL_PLANE'];contexts[11]={owner:evolution,actor:r=>actor(r.headers)};const app=await buildCatalogServer(...contexts);
 try{const url=await app.listen({host:'127.0.0.1',port:0}),client=createDepartmentImpactClient(url,'maker'),result=await client.assess({requestId:randomUUID(),reason:'TEST real serialized impact',target:{kind:'INPUT',id:i.inputId}});expect(result.response.status).toBe(200);const ref=result.data?.references.find(v=>v.owner==='NURSING_UNIT'&&v.id===h.id);expect(ref?.constraint).toBe('UNSATISFIED');expect(ref?.currentPeriod?.to).toBe('2030-01-01T00:00:00.000000');expect(ref?.acceptedVersions).toContainEqual(expect.objectContaining({versionId:expect.any(String),version:'1'}));
 }finally{await app.close();await evolution.close();}
});

test('an accepted source alias cannot register a second stable Nursing identity in another import job',async()=>{
 const {a,entry}=await populated(),duplicate=f.entry(a);duplicate.row.nursing_unit_id=entry.row.nursing_unit_id;await expect(f.apply(await f.input([duplicate]))).rejects.toThrow('NURSING_SOURCE_ALREADY_REGISTERED');expect((await f.owner.list('maker',{campus:'NORTH',departmentId:a.department.id})).items).toHaveLength(1);
});

test('a committed rebind result proves only its actual management target and business interval',async()=>{
 const {h,entry}=await populated(),b=await f.endpoint(),r=revision(h,entry,'REBIND','2027-01-01T00:00:00',b),request=await f.prepare(await f.input([r])),outcome=await f.owner.applyUnit('maker',request);expect(outcome.status).toBe('COMMITTED');const latest=(await f.owner.history('maker',{id:h.id})).versions.at(-1)!,pool=new Pool({connectionString:connection});
 try{const proof={owner:'NURSING_UNIT',id:h.id,versionId:latest.id,...request},result=(await pool.query('select department_master.impact_result($1,$2,$3) r',['maker',proof,'NORTH'])).rows[0].r;expect(result.departmentIds).toEqual([b.department.id]);expect(result.period.from).toBe('2027-01-01T00:00:00.000000');}finally{await pool.end();}
});

test('Nursing write authorization requires a human even when a service has identical grants',async()=>{
 const b=await f.endpoint(),input=await f.input([f.entry(b)]);peer(receipt.name,"UPDATE vnext_control.actor SET principal_kind='SERVICE' WHERE code='maker';");try{await expect(f.owner.stage('maker',input)).rejects.toThrow('ACCESS_DENIED');}finally{peer(receipt.name,"UPDATE vnext_control.actor SET principal_kind='HUMAN' WHERE code='maker';");}
});

test('historical admission excludes Campus assertions recorded after its requested R',async()=>{
 const {a,h}=await populated(),op=f.base.operating,old=await op.campus.references.read('maker',{id:a.campus.id});await op.campusApply({...op.common,validFrom:'2030-01-01T00:00:00',action:'REVISE',target:{owner:'organization-master/campus',id:a.campus.id,expectedVersion:old.head},evidence:op.artifact.artifactId,sourceOperationStatus:'PLANNING',facts:{...old.facts!,campusName:'TEST future Campus assertion'}});
 const window={id:h.id,validFrom:'2028-01-01T00:00:00',validTo:'2032-01-01T00:00:00'},historical=await f.owner.evaluateWindow('maker',{...window,recordAsOf:h.versions[0]!.recordedAt}),current=await f.owner.evaluateWindow('maker',window);expect(historical.checks).toEqual([expect.objectContaining({status:'SATISFIED',basis:expect.objectContaining({campus:expect.objectContaining({parts:[expect.objectContaining({version:'1'})]})})})]);expect(current.checks).toEqual([expect.objectContaining({status:'SATISFIED',basis:expect.objectContaining({campus:expect.objectContaining({parts:[expect.objectContaining({version:'1',to:'2030-01-01T00:00:00.000000'}),expect.objectContaining({version:'2',from:'2030-01-01T00:00:00.000000'})]})})})]);
});

test('failed target admission leaves the source binding and stable head unchanged',async()=>{
 const {h,entry}=await populated(),target=await f.endpoint(),op=f.base.operating,assessment=await op.campus.assessCampusImpact('maker',{id:target.campus.id,validFrom:'2027-01-01T00:00:00',validTo:null});await op.campusApply({...op.common,action:'RETIRE',validFrom:'2027-01-01T00:00:00',target:{owner:'organization-master/campus',id:target.campus.id,expectedVersion:'1'},evidence:op.artifact.artifactId,sourceOperationStatus:'RETIRED',reason:'TEST target retirement',assessmentDigest:assessment.digest,plan:{responsibleOwner:'TEST',dueAt:'2028-01-01T00:00:00',actions:'TEST explicit Owner disposition'}});
 await expect(f.prepare(await f.input([revision(h,entry,'REBIND','2026-06-01T00:00:00',target)]))).rejects.toThrow('NURSING_CAMPUS_NOT_ADMITTED');expect(await f.owner.history('maker',{id:h.id})).toEqual(h);
});

const southTarget=async(manager?:string)=>{peer(receipt.name,"INSERT INTO organization_master.access SELECT a,'00000000-0000-0000-0000-000000000000'::uuid,'SOUTH',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','REVIEW','READ_RESTRICTED']) p ON CONFLICT DO NOTHING;");const departmentId=manager??await f.newDepartment(),campus=await f.base.operating.createCampus('TEST South nursing campus','HEADQUARTERS','SOUTH');peer(receipt.name,`INSERT INTO care_organization.nursing_access SELECT a,${quote(campus.id)}::uuid,'SOUTH',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED']) p;INSERT INTO care_organization.nursing_access SELECT 'reviewer',${quote(campus.id)}::uuid,'SOUTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p;`);return {department:{owner:'department-master' as const,id:departmentId},campus:{owner:'organization-master/campus' as const,id:campus.id}};};
test('a row and typed target cannot publish against a different operational Campus scope',async()=>{
 const b=await southTarget();await expect(f.apply(await f.input([f.entry(b)]))).rejects.toThrow('NURSING_ANCHOR_MISMATCH');
});
test('authorized cross-scope REBIND retains identity and replays the original accepted scope with current permission',async()=>{
 const {h,d,entry,request:original}=await populated(),target=await southTarget(d),value=await f.input([revision(h,entry,'REBIND','2026-06-01T00:00:00',target)]);value.campus='SOUTH';const proof=await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),jobId:value.jobId,revisionId:value.revisionId,campus:'SOUTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds:3600},Buffer.from('TEST independently confirmed South nursing target'));value.entries[0]!.evidenceId=proof.artifactId;
 peer(receipt.name,`DELETE FROM care_organization.nursing_access WHERE actor='maker' AND campus_id=${quote(h.bindings[0]!.campusId)}::uuid AND permission='WRITE';`);try{await expect(f.owner.stage('maker',value)).rejects.toThrow('ACCESS_DENIED');}finally{peer(receipt.name,`INSERT INTO care_organization.nursing_access VALUES('maker',${quote(h.bindings[0]!.campusId)}::uuid,'NORTH','WRITE');`);}
 const i=await f.owner.stage('maker',value),verification=f.verification(value,i);verification.rows[0]!.evidenceId=proof.artifactId;await f.owner.verify('reviewer',verification);const requestId=randomUUID(),c=await f.owner.plan('maker',{inputId:i.inputId,requestId});await f.owner.readApplyCandidate('reviewer',{candidateId:c.candidateId});await f.owner.approveApplyUnit('reviewer',c);expect((await f.owner.applyUnit('maker',{candidateId:c.candidateId,requestId})).status).toBe('COMMITTED');expect(await f.owner.read('maker',{id:h.id,businessAt:'2026-06-01T00:00:00'})).toMatchObject({id:h.id,binding:{binding:target}});expect((await f.owner.read('maker',{id:h.id,businessAt:'2026-05-31T23:59:59.999999'})).departmentId).toBe(entry.row.managing_org_id);
 const j=await f.dep.newJob(),upstream=await f.lifecycle.stage('maker',{requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',profile:'CORE',commands:[{action:'SUSPEND',department:{owner:'department-master',id:d,expectedVersion:'1',expectedLifecycleHead:'0'},effectiveAt:'2028-01-01T00:00:00',reason:'TEST hospital-wide exit',evidenceId:f.dep.artifact.artifactId}],impacts:f.impacts}),evolution=openOrganizationEvolutions(connection,provider,withCareOrganizationImpacts(()=>f.base.owner,()=>f.owner));
 try{const assessment=await evolution.assessDepartmentChange('maker',{requestId:randomUUID(),reason:'TEST complete reverse set',target:{kind:'INPUT',id:upstream.inputId}});expect(assessment.references).toContainEqual(expect.objectContaining({owner:'NURSING_UNIT',id:h.id,constraint:'UNSATISFIED',affectedSpans:[{from:'2028-01-01T00:00:00.000000',to:null}]}));peer(receipt.name,`DELETE FROM care_organization.nursing_access WHERE actor='maker' AND campus_id=${quote(target.campus.id)}::uuid AND permission='READ';`);try{expect((await f.owner.applyUnit('maker',original)).status).toBe('COMMITTED');await expect(evolution.assessDepartmentChange('maker',{requestId:randomUUID(),reason:'TEST cannot omit inaccessible South',target:{kind:'INPUT',id:upstream.inputId}})).rejects.toThrow('ACCESS_DENIED');}finally{peer(receipt.name,`INSERT INTO care_organization.nursing_access VALUES('maker',${quote(target.campus.id)}::uuid,'SOUTH','READ');`);}}finally{await evolution.close();}
 peer(receipt.name,`DELETE FROM care_organization.nursing_access WHERE actor='maker' AND campus_id=${quote(h.bindings[0]!.campusId)}::uuid AND permission='READ';`);try{await expect(f.owner.applyUnit('maker',original)).rejects.toThrow('ACCESS_DENIED');}finally{peer(receipt.name,`INSERT INTO care_organization.nursing_access VALUES('maker',${quote(h.bindings[0]!.campusId)}::uuid,'NORTH','READ');`);}
});

test('nonexpanding suspension survives upstream suspension and preserves history and code',async()=>{
 const {d,a,h,entry}=await populated(),j=await f.dep.newJob(),i=await f.lifecycle.stage('maker',{requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',profile:'CORE',commands:[{action:'SUSPEND',department:{owner:'department-master',id:d,expectedVersion:'1',expectedLifecycleHead:'0'},effectiveAt:'2026-06-01T00:00:00',reason:'TEST suspension',evidenceId:f.dep.artifact.artifactId}],impacts:f.impacts.map(impact=>({...impact,determination:['IDENTIFIER','SOURCE_MAPPING','HIERARCHY'].includes(impact.domain)?'AFFECTED' as const:impact.determination}))});
 await f.lifecycle.verify('reviewer',{requestId:randomUUID(),inputId:i.inputId,inputDigest:i.digest,reason:'TEST explicit pending dispositions',policyApproved:true,materialsAccepted:true,impactReviews:f.impactReviews});const requestId=randomUUID(),c=await f.lifecycle.plan('maker',{inputId:i.inputId,requestId});await f.lifecycle.readApplyCandidate('reviewer',{candidateId:c.candidateId});await f.lifecycle.approveApplyUnit('reviewer',c);const lifecycleResult=await f.lifecycle.applyUnit('maker',{candidateId:c.candidateId,requestId});if(lifecycleResult.status!=='COMMITTED')throw new Error();
 const evolution=openOrganizationEvolutions(connection,provider,withCareOrganizationImpacts(()=>f.base.owner,()=>f.owner));
 try{
  const item=(await evolution.listImpactCases('maker',{eventId:lifecycleResult.facts[0]!.id,campus:'NORTH'})).items.find(v=>v.obligation.owner==='NURSING_UNIT')!;expect(item.status).toBe('OPEN');
  const draft=await catalog.command('maker',{action:'CREATE',scope:'SYNTHETIC',requestId:randomUUID(),reason:'RESPONSIBILITY',kind:'RESPONSIBILITY',code:'NURSING_IMPACT_'+randomUUID().replaceAll('-','').toUpperCase(),values:{dataset:'ORG09',authorityScope:'ALL',fieldGroup:'ALL',role:'OWNER',assigneeRole:'SYNTHETIC_OWNER_A'},validFrom:'2026-01-01T00:00:00'}),submitted=await catalog.command('maker',{action:'SUBMIT',scope:'SYNTHETIC',requestId:randomUUID(),reason:'RESPONSIBILITY',target:draft.id,expectedHead:draft.head}),r=await catalog.command('reviewer',{action:'PUBLISH',scope:'SYNTHETIC',requestId:randomUUID(),reason:'RESPONSIBILITY',target:draft.id,expectedHead:submitted.head,reviewDigest:submitted.reviewDigest});
  peer(receipt.name,"UPDATE vnext_control.actor SET principal_kind='SERVICE' WHERE code='maker';");try{await expect(evolution.assignImpactCase('maker',{requestId:randomUUID(),reason:'TEST service cannot adjudicate',caseId:item.id,campus:'NORTH',expectedHead:item.head,responsibilityId:r.id})).rejects.toThrow('ACCESS_DENIED');}finally{peer(receipt.name,"UPDATE vnext_control.actor SET principal_kind='HUMAN' WHERE code='maker';");}
  const assigned=await evolution.assignImpactCase('maker',{requestId:randomUUID(),reason:'TEST unit Owner',caseId:item.id,campus:'NORTH',expectedHead:item.head,responsibilityId:r.id});
  const closeRequest=await f.prepare(await f.input([revision(h,entry,'SUSPEND')])),result=await f.owner.applyUnit('maker',closeRequest);expect(result.status).toBe('COMMITTED');const v=(await f.owner.history('maker',{id:h.id})).versions.at(-1)!,proof={owner:'NURSING_UNIT' as const,id:h.id,versionId:v.id,...closeRequest};
  await expect(evolution.recordDisposition('maker',{requestId:randomUUID(),reason:'TEST forged result',caseId:item.id,campus:'NORTH',expectedHead:assigned.head,disposition:{kind:'CLOSE_RELATION',evidenceId:f.dep.artifact.artifactId,result:{...proof,requestId:randomUUID()}}})).rejects.toThrow();
  const proposed=await evolution.recordDisposition('maker',{requestId:randomUUID(),reason:'TEST committed closure',caseId:item.id,campus:'NORTH',expectedHead:assigned.head,disposition:{kind:'CLOSE_RELATION',evidenceId:f.dep.artifact.artifactId,result:proof}}),approved=await evolution.approveDisposition('reviewer',{requestId:randomUUID(),reason:'TEST independent result',caseId:item.id,campus:'NORTH',expectedHead:proposed.head,proposalEventId:proposed.eventId});expect((await evolution.recheckImpact('maker',{requestId:randomUUID(),reason:'TEST result recheck',caseId:item.id,campus:'NORTH',expectedHead:approved.head})).status).toBe('RESOLVED');
 }finally{await evolution.close();}
 expect((await f.owner.read('maker',{id:h.id,businessAt:'2026-07-01T00:00:00'})).state).toBe('SUSPENDED');expect((await f.owner.read('maker',{id:h.id,businessAt:'2026-07-01T00:00:00',recordAsOf:h.versions[0]!.recordedAt})).state).toBe('ACTIVE');
 const closed=await f.owner.history('maker',{id:h.id});await expect(f.prepare(await f.input([revision(closed,entry,'REVISE')]))).rejects.toThrow('NURSING_SUSPENDED');const duplicate=f.entry(a);duplicate.row.nursing_code=h.versions[0]!.facts.nursingCode;await expect(f.prepare(await f.input([duplicate]))).rejects.toThrow('NURSING_CODE_CONFLICT');
});

test('source evidence chains authorize the exact historical pin through the actual restricted role',async()=>{
 const cmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'SYNTHETIC_SOURCE_CHAIN',...extra}),publish=async(id:string,head:string)=>{const submitted=await catalog.command('maker',cmd('SUBMIT',{target:id,expectedHead:head})),impact=await catalog.sourceImpact('reviewer','SYNTHETIC',id,'PUBLISH');return catalog.command('reviewer',cmd('PUBLISH',{target:id,expectedHead:submitted.head,reviewDigest:submitted.reviewDigest,impactDigest:impact.impactDigest}));},source=async(parent:string)=>{const d=await catalog.command('maker',cmd('CREATE',{kind:'SOURCE',code:'NURSING_CHAIN_'+randomUUID().replaceAll('-','').toUpperCase(),values:{name:'TEST source chain',environment:'SYNTHETIC',sourceKind:'MANUAL',deploymentScope:'SYNTHETIC_ALL',businessOwnerRole:'TEST',technicalRole:'TEST',sourceEvidence:parent},validFrom:'2026-01-01T00:00:00'}));return publish(d.id,d.head);},x=await source(f.dep.source.id),y=await source(f.dep.source.id),leaf=await source(x.id);
 const revision=await catalog.command('maker',cmd('REVISE',{target:leaf.id,expectedHead:leaf.head,values:{sourceEvidence:y.id},validFrom:'2026-01-01T00:00:00'}));await publish(revision.id,revision.head);
 const revoke=(id:string)=>peer(receipt.name,`DELETE FROM vnext_control.object_grant WHERE actor_code='maker' AND object_id=${quote(id)}::uuid AND permission='READ' AND purpose='SYNTHETIC_REFERENCE';`),restore=(id:string,copy:string)=>peer(receipt.name,`INSERT INTO vnext_control.object_grant(actor_code,object_id,scope,object_kind,campus,field_group,permission,purpose) SELECT actor_code,${quote(id)}::uuid,scope,object_kind,campus,field_group,permission,purpose FROM vnext_control.object_grant WHERE actor_code='maker' AND object_id=${quote(copy)}::uuid AND permission='READ' AND purpose='SYNTHETIC_REFERENCE' ON CONFLICT DO NOTHING;`),pool=new Pool({connectionString:connection}),coverage=(at:string|null)=>pool.query('select governance_catalog.nursing_source_coverage($1,$2,$3,$4,$5) r',['maker',leaf.id,'2026-06-01',null,at]);
 try{revoke(x.id);try{await expect(coverage(leaf.recordedAt)).rejects.toThrow('ACCESS_DENIED');}finally{restore(x.id,y.id);}revoke(y.id);try{expect((await coverage(leaf.recordedAt)).rows[0].r).toMatchObject({versionId:leaf.versionId,covered:true});await expect(coverage(null)).rejects.toThrow('ACCESS_DENIED');}finally{restore(y.id,x.id);}}finally{await pool.end();}
});

test('source qualification is rechecked at current R without changing original historical acceptance',async()=>{
 const {h,entry}=await populated(),app=await buildCatalogServer(catalog);try{const url=await app.listen({host:'127.0.0.1',port:0}),detail=await createVNextCatalogClient(url,'reviewer').GET('/api/vnext/catalog/{id}',{params:{path:{id:entry.row.source_system_id},query:{scope:'SYNTHETIC'}}});expect(detail.response.status).toBe(200);if(!detail.data)throw new Error();const impact=await catalog.sourceImpact('reviewer','SYNTHETIC',detail.data.id,'RETIRE');await catalog.command('reviewer',{action:'RETIRE',scope:'SYNTHETIC',requestId:randomUUID(),reason:'SYNTHETIC_SOURCE_WITHDRAWAL',target:detail.data.id,expectedHead:detail.data.head,reviewDigest:detail.data.reviewDigest,impactDigest:impact.impactDigest});
 const window={id:h.id,validFrom:'2026-06-01T00:00:00',validTo:null};expect((await f.owner.evaluateWindow('maker',window)).checks).toEqual([expect.objectContaining({status:'NOT_SATISFIED',reason:'NURSING_SOURCE_NOT_ADMITTED'})]);expect((await f.owner.evaluateWindow('maker',{...window,recordAsOf:h.versions[0]!.recordedAt})).checks).toEqual([expect.objectContaining({status:'SATISFIED'})]);expect(await f.owner.history('maker',{id:h.id})).toEqual(h);expect((await f.apply(await f.input([revision(h,entry,'SUSPEND')]))).facts[0]!.id).toBe(h.id);
 }finally{await app.close();}
});
