import {withBusinessUnitImpacts} from '../../apps/governance-api/src/composition/business-unit-dependencies.js';
import {randomUUID} from 'node:crypto';
import type {Catalog,KeyProviderPort} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {openDepartment,openDepartmentLifecycle,EVOLUTION_IMPACT_DOMAINS} from '../../apps/governance-api/src/modules/department-master/index.js';
import {openBusinessUnit,UNIT_TYPES,type UnitBindingInput,type UnitStage,type UnitEntry,type UnitVerification,type UnitRow} from '../../apps/governance-api/src/modules/care-organization/index.js';
import {conditionMappings} from '../../apps/governance-api/src/modules/governance-catalog/validation-sources.generated.js';
import {campusCodeSet} from './campus-fixture.js';
import {departmentFixture} from './p2-01-fixture.js';
import {operatingScenario} from './operating-scenario.js';
import {provisionBusinessUnit} from './p3-01-provisioning.mjs';
import {peer,quote} from './lineage.mjs';
export async function businessUnitFixture(receipt:{name:string;oid:string},role:string,catalog:Catalog,provider:KeyProviderPort,connection:string,persistent=false){
 const dep=await departmentFixture(receipt,catalog,provider,{persistentSmoke:persistent,reusePublishedContract:persistent}),department=openDepartment(connection,provider),lifecycle=openDepartmentLifecycle(connection,provider,withBusinessUnitImpacts(()=>owner)),operating=await operatingScenario(receipt,connection,provider,catalog,persistent);
 peer(receipt.name,"INSERT INTO department_master.identifier_access SELECT a,'SYNTHETIC_DEPARTMENT_CODE','NORTH','READ' FROM unnest(ARRAY['maker','maker-alias','reviewer']) a ON CONFLICT DO NOTHING;");
 const cmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'SYNTHETIC_BUSINESS_UNIT',...extra});
 let dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.kind==='DATASET'&&i.code==='ORG07'&&i.status==='PUBLISHED');
 if(!dataset){const d=await catalog.command('maker',cmd('CREATE',{kind:'DATASET',code:'ORG07',values:{name:'TEST POLICY ONLY 院区业务单元'},validFrom:'2026-01-01T00:00:00'})),s=await catalog.command('maker',cmd('SUBMIT',{target:d.id,expectedHead:d.head})),p=await catalog.command('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:s.head,reviewDigest:s.reviewDigest}));dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.id===p.id)!;}
 const fields=dataset.payload.fields!.map(f=>f.original),enums:Record<string,string[]>={unit_type:[...UNIT_TYPES],record_status:['DRAFT','REVIEW','ACTIVE','SUSPENDED','RETIRED']};
 const definition={ruleVersion:'ORG07_CORE_V1',templateVersion:'ORG07_CORE_V1',sourceVersionId:dep.source.versionId,businessKey:['unit_id'],fields:fields.map(f=>({code:f.code,type:f.type,required:f.required,privacy:f.privacy,condition:f.required==='C'?'EVALUATED':f.required==='R'?'ALWAYS':'OPTIONAL',enumValues:enums[f.code]??[]})),references:fields.filter(f=>f.ref).map(f=>({field:f.code,target:f.ref,status:'UNIT_CORE'})),rules:[...conditionMappings.filter(r=>r.dataset==='ORG07').map(r=>({id:r.id,field:r.field,text:r.text,status:'MACHINE',version:r.version})),{id:'UNIT_APPROVAL_V1',field:'approval_ref',text:'Source approval never replaces platform approval.',status:'MACHINE',version:'P3_01_V1'}],codeSets:Object.entries(enums).map(([field,codes])=>({field,codes,codeSystem:'SYNTHETIC_'+field.toUpperCase(),version:'TEST_POLICY_ONLY_1',status:'SYNTHETIC_ADOPTED',sourceVersionId:dep.source.versionId,validFrom:'2026-01-01T00:00:00',validTo:null}))};
 let contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG07'&&c.profile==='CORE'&&c.status==='PUBLISHED');
 if(!contract||contract.definition.templateVersion!=='ORG07_CORE_V1'){
  const d=contract?await catalog.contractCommand('maker',cmd('REVISE',{target:contract.id,expectedHead:contract.head,datasetVersionId:dataset.versionId,definition,validFrom:'2026-01-01T00:00:00',validTo:null})):await catalog.contractCommand('maker',cmd('CREATE',{datasetVersionId:dataset.versionId,profile:'CORE',definition,validFrom:'2026-01-01T00:00:00',validTo:null})),a=await catalog.contractCommand('reviewer',cmd('APPROVE',{target:d.id,expectedHead:d.head,reviewDigest:d.reviewDigest}));await catalog.contractCommand('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:a.head,reviewDigest:a.reviewDigest}));contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.id===d.id)!;
 }
 const newJob=()=>catalog.importJobCommand('maker',cmd('CREATE',{profile:'CORE',contractId:contract!.id,contractVersionId:contract!.versionId,input:{kind:'METADATA_ONLY',declaredSha256:'a'.repeat(64)}}));
 peer(receipt.name,`INSERT INTO vnext_control.protected_grant SELECT a,${quote(dataset.id)}::uuid,s,'IDENTITY_VERIFY',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['NORTH','SOUTH']) s CROSS JOIN unnest(ARRAY['READ','STORE']) p ON CONFLICT DO NOTHING;`);
 const proof=await newJob(),artifact=await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),jobId:proof.id,revisionId:proof.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds:7200},Buffer.from('TEST POLICY ONLY independently confirmed no special receiving restriction'));
 provisionBusinessUnit(receipt,role,provider);
 const ports={departmentCoverage:lifecycle.readUnitBindingCoverageInTransaction,referenceAccess:lifecycle.authorizeUnitReferenceInTransaction,operatingWindow:operating.operating.evaluateOperatingWindowInTransaction},owner=openBusinessUnit(connection,provider,ports);
 const newDepartment=async()=>{const value=await dep.input(),i=await department.stage('maker',value);await department.verify('reviewer',{requestId:randomUUID(),inputId:i.inputId,inputDigest:i.digest,rows:[{row:1,disposition:'DEPARTMENT',historicalException:false,reason:'TEST logical Department',evidenceId:dep.artifact.artifactId}]});const requestId=randomUUID(),c=await department.plan('maker',{inputId:i.inputId,requestId});await department.readApplyCandidate('reviewer',{candidateId:c.candidateId});await department.approveApplyUnit('reviewer',c);const outcome=await department.applyUnit('maker',{candidateId:c.candidateId,requestId});if(outcome.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');const id=outcome.facts[0]!.id;peer(receipt.name,`INSERT INTO department_master.mapping_target_access SELECT a,'ORG',${quote(id)}::uuid,'NORTH' FROM unnest(ARRAY['maker','maker-alias','reviewer']) a ON CONFLICT DO NOTHING;`);return id;};
 const impacts=EVOLUTION_IMPACT_DOMAINS.map(domain=>({domain,determination:'UNAFFECTED' as const,ownerRole:'TEST_ONLY_'+domain,ownerSignatory:'TEST_ONLY_OWNER',ownerDecisionRef:'TEST_ONLY_DECISION',reason:'TEST POLICY ONLY declaration',requiredAction:'TEST POLICY ONLY bounded declaration',evidenceId:dep.artifact.artifactId})),impactReviews=EVOLUTION_IMPACT_DOMAINS.map(domain=>({domain,ownerAttestationAccepted:true,dispositionAccepted:true,reason:'TEST POLICY ONLY declared impacts'}));
 const endpoint=async(departmentId:string,from='2026-01-01T00:00:00',to:string|null=null,openingAt?:string):Promise<UnitBindingInput>=>{
  const subject=await operating.createSubject(),campus=await operating.createCampus();if(openingAt){const division=await campusCodeSet(catalog,operating.source.versionId),old=await operating.campus.references.read('maker',{id:campus.id}),revised=await operating.campusApply({...operating.common,validFrom:openingAt,action:'REVISE',target:{owner:'organization-master/campus',id:campus.id,expectedVersion:old.head},evidence:operating.artifact.artifactId,sourceOperationStatus:'PLANNING',facts:{...old.facts!,campusAddress:'TEST future address',adminDivision:division.reference}});await operating.campusApply({...operating.common,validFrom:openingAt,action:'ACTIVATE',target:{owner:'organization-master/campus',id:campus.id,expectedVersion:revised.version},evidence:operating.artifact.artifactId,sourceOperationStatus:'RUNNING',state:'RUNNING'});}else await operating.activateCampus(campus);operating.grantPair(subject.id,campus.id);const license=await operating.addLicense(subject),scope=await operating.verifyScope(subject,campus,license,['DEMO_MEDICAL_A']);
  await operating.operatingApply({...operating.common,...operating.endpoints(subject,campus),action:'ESTABLISH',evidence:operating.artifact.artifactId,facts:{role:'OPERATOR',relationTypeText:'TEST operator',primary:'Y',catalog:operating.codeSet.reference,services:['DEMO_MEDICAL_A'],scopeTargets:[scope],licenseScopeText:'TEST POLICY ONLY'}});
  const d=await department.history('maker',departmentId),life=await lifecycle.history('maker',{id:departmentId}),j=await dep.newJob(),i=await lifecycle.stage('maker',{requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',profile:'CORE',commands:[{action:'ASSIGN',department:{owner:'department-master',id:departmentId,expectedVersion:d.versions.at(-1)!.number,expectedLifecycleHead:life.lifecycle.at(-1)?.number??'0'},...operating.endpoints(subject,campus),services:['DEMO_MEDICAL_A'],validFrom:from,validTo:to,reason:'TEST unit service context',evidenceId:dep.artifact.artifactId}],impacts});
  await lifecycle.verify('reviewer',{requestId:randomUUID(),inputId:i.inputId,inputDigest:i.digest,reason:'TEST independently verified service context',policyApproved:true,materialsAccepted:true,impactReviews});const requestId=randomUUID(),c=await lifecycle.plan('maker',{inputId:i.inputId,requestId});await lifecycle.readApplyCandidate('reviewer',{candidateId:c.candidateId});await lifecycle.approveApplyUnit('reviewer',c);await lifecycle.applyUnit('maker',{candidateId:c.candidateId,requestId});
  const relation=(await lifecycle.history('maker',{id:departmentId})).relations.find(r=>r.campus_id===campus.id)!,version=relation.versions.at(-1)!;
  peer(receipt.name,`INSERT INTO care_organization.access SELECT a,${quote(campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED']) p ON CONFLICT DO NOTHING;INSERT INTO care_organization.access SELECT 'reviewer',${quote(campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;`);
  return {department:{owner:'department-master',id:departmentId},...operating.endpoints(subject,campus),services:['DEMO_MEDICAL_A'],relation:{owner:'department-master/campus-relation',id:relation.id,version:version.number,versionId:version.id}};
 };
 const row=(b:UnitBindingInput):UnitRow=>({unit_id:randomUUID(),unit_code:'TEST_'+randomUUID(),unit_name:'TEST 同名业务单元',org_id:b.department.id,campus_id:b.campus.id,legal_entity_id:b.subject.id,unit_type:'OPD',public_phone:'010-TEST',service_description:'TEST service',receiving_rule_ref:'',business_owner_id:'',version_no:'9',valid_from:'2026-01-01T00:00:00',valid_to:'',record_status:'ACTIVE',source_system_id:dep.source.id,source_record_id:'TEST/ORG07/2',approval_ref:'TEST_POLICY_ONLY',recorded_at:'2026-01-02T00:00:00'});
 const entry=(b:UnitBindingInput):UnitEntry=>({action:'CREATE',binding:b,row:row(b),reason:'TEST unit creation',evidenceId:artifact.artifactId});
 const input=async(entries:UnitEntry[]):Promise<UnitStage>=>{const j=await newJob();return {requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',profile:'CORE',timePolicy:'LOCAL',entries};};
 const verification=(value:UnitStage,i:{inputId:string;digest:string}):UnitVerification=>({requestId:randomUUID(),inputId:i.inputId,inputDigest:i.digest,reason:'TEST independent receiving review',policyVersion:'ORG07_CORE_V1',rows:value.entries.map((e,index)=>({row:index+1,evidenceId:artifact.artifactId,classificationAccepted:true,receiving:{kind:'NO_SPECIAL_RESTRICTION',confirmed:true,validFrom:e.row.valid_from,validTo:e.row.valid_to||null}}))});
 const prepare=async(value:UnitStage)=>{const i=await owner.stage('maker',value);await owner.verify('reviewer',verification(value,i));const requestId=randomUUID(),c=await owner.plan('maker',{inputId:i.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:c.candidateId});await owner.approveApplyUnit('reviewer',c);return {candidateId:c.candidateId,requestId};};
 const apply=async(value:UnitStage)=>{const outcome=await owner.applyUnit('maker',await prepare(value));if(outcome.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');return outcome;};
 return {owner,department,lifecycle:lifecycle as ReturnType<typeof openDepartmentLifecycle>,operating,ports,impacts,impactReviews,dep,contract,dataset,artifact,newJob,newDepartment,endpoint,row,entry,input,verification,prepare,apply,close:async()=>{await owner.close();await department.close();await lifecycle.close();await operating.close();}};
}
