import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {beforeAll,afterAll,test,expect} from 'vitest';
import {openCatalog,type Catalog} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {unzip,type ParserResult} from '../../apps/governance-api/src/modules/governance-catalog/file-parser.js';
import {zipText} from '../../apps/governance-api/src/modules/governance-catalog/issue-workbook.js';
import {ORG13_FIELDS,type LocationUseEntry} from '../../apps/governance-api/src/modules/location-master/index.js';
import type {NursingEntry} from '../../apps/governance-api/src/modules/care-organization/index.js';
import {buildCatalogServer} from '../../apps/governance-api/src/composition/build-vnext-catalog.js';
import {actor} from '../../apps/governance-api/src/platform/fastify/vnext-catalog-routes.js';
import {createLocationUseClient} from '../../packages/generated-api-client/src/index.js';
import {locationUseFixture} from './p3-07-fixture.js';
import {validationKeys} from './p3-07-validation-keys.mjs';
import {peer,quote} from './lineage.mjs';
import {locationUseFile,locationUseFileRequest,signedUseAttempt,type LocationUseFixture} from './p3-07-validation-helpers.js';

const connection=process.env['VNEXT_VALIDATION_OWNER_URL']!,receipt=JSON.parse(readFileSync(process.env['VNEXT_TEST_RECEIPT']!,'utf8'));
let catalog:Catalog,f:LocationUseFixture,app:Awaited<ReturnType<typeof buildCatalogServer>>,url:string;
beforeAll(async()=>{
 const provider=validationKeys(receipt),pool=new Pool({connectionString:connection,max:1});
 try{catalog=await openCatalog(connection,provider);const role=(await pool.query('select current_user r')).rows[0]!.r;f=await locationUseFixture(receipt,role,catalog,provider,connection,process.env['VNEXT_P3_07_UPGRADED']==='1');const contexts:Parameters<typeof buildCatalogServer>=[catalog,'CONTROL_PLANE'];contexts[24]={owner:f.owner,usageTypes:f.dictionary,actor:r=>actor(r.headers)};app=await buildCatalogServer(...contexts);url=await app.listen({host:'127.0.0.1',port:0});}finally{await pool.end();}
});
afterAll(async()=>{await app?.close();await f?.close();await catalog?.close();});
const cmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'TEST_CLOUD_REVIEW',...extra});
const sensitive=(id:string)=>catalog.authorizeSensitiveRead('maker',{scope:'SYNTHETIC',requestId:randomUUID(),artifactId:id,campus:'NORTH',purpose:'IDENTITY_VERIFY'});
type ParsedEvidence={result:ParserResult;conversions:Array<{row:number;field:string;sourceValue:unknown;value:unknown;ruleVersion:string}>};
async function parseEvidence(id:string):Promise<ParsedEvidence>{const bytes=await sensitive(id);try{return JSON.parse(Buffer.from(bytes).toString('utf8'));}finally{bytes.fill(0);}}
function nativeWorkbook(entry:LocationUseEntry,token:string,typeAttribute:string){
 const fields=[...ORG13_FIELDS].reverse(),files=Object.fromEntries(unzip(locationUseFile([entry.row],'XLSX',fields),true)),address=String.fromCharCode(65+fields.indexOf('version_no'))+'2';
 files['xl/worksheets/sheet9.xml']=files['xl/worksheets/sheet9.xml']!.replace(new RegExp('<c r="'+address+'"[^>]*>.*?</c>'),'<c r="'+address+'"'+typeAttribute+'><v>'+token+'</v></c>');return zipText(files);
}
async function freezeHttp(entries:LocationUseEntry[]){
 const maker=createLocationUseClient(url,'maker'),reviewer=createLocationUseClient(url,'reviewer'),value=await f.input(entries),staged=await maker.stage(f.nativeInput(value));expect(staged.response.status,JSON.stringify(staged.error)).toBe(200);
 expect((await reviewer.verify(f.verification(value,staged.data!))).response.status).toBe(200);const preview=await maker.preview({inputId:staged.data!.inputId});expect(preview.data?.issues,JSON.stringify(preview.error??preview.data?.issues)).toEqual([]);expect(preview.data?.decision).toBe('PASS');
 const requestId=randomUUID(),planned=await maker.plan({inputId:staged.data!.inputId,requestId});expect(planned.response.status,JSON.stringify(planned.error)).toBe(200);expect((await reviewer.review({candidateId:planned.data!.candidateId})).response.status).toBe(200);expect((await reviewer.approve(planned.data!)).response.status).toBe(200);return {candidateId:planned.data!.candidateId,requestId,inputId:staged.data!.inputId};
}
async function publishContractRevision(contractId:string,datasetVersionId:string,definition:unknown){
 const current=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.id===contractId)!,draft=await catalog.contractCommand('maker',cmd('REVISE',{target:current.id,expectedHead:current.head,datasetVersionId,definition,validFrom:'2026-01-01T00:00:00',validTo:null})),preImpact=await catalog.contractImpact('reviewer','SYNTHETIC',draft.id,'PUBLISH'),approved=await catalog.contractCommand('reviewer',cmd('APPROVE',{target:draft.id,expectedHead:draft.head,reviewDigest:draft.reviewDigest,impactDigest:preImpact.impactDigest})),impact=await catalog.contractImpact('reviewer','SYNTHETIC',draft.id,'PUBLISH');await catalog.contractCommand('reviewer',cmd('PUBLISH',{target:draft.id,expectedHead:approved.head,reviewDigest:approved.reviewDigest,impactDigest:impact.impactDigest}));return (await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.id===draft.id)!;
}

test.each([{token:'9',typeAttribute:' t="n"'},{token:'9',typeAttribute:''},{token:'9.0',typeAttribute:' t="n"'},{token:'9e0',typeAttribute:''}])('R1: native XLSX $token $typeAttribute needs exact conversion evidence while final native9 remains supported',async({token,typeAttribute})=>{
 const scope=await f.endpoint(),entry=await f.entry(scope);entry.row.source_record_id='000019';const bytes=nativeWorkbook(entry,token,typeAttribute),maker=createLocationUseClient(url,'maker'),received=await maker.file({input:locationUseFileRequest(f,[entry],'XLSX'),contentBase64:bytes.toString('base64')});expect(received.response.status,JSON.stringify(received.error)).toBe(200);expect(received.data?.issues).toEqual([]);const result=received.data!;
 const raw=await sensitive(result.sourceArtifactId);try{expect(Buffer.from(raw)).toEqual(bytes);}finally{raw.fill(0);}const parsed=await parseEvidence(result.validation.run.parseArtifactId);expect(parsed.result.cells.find(cell=>cell.field==='version_no')).toMatchObject({value:token,sourceType:'n'});
 expect.soft(parsed.result.nativeRows?.[0]?.['version_no']).toBe(token);expect.soft(parsed.conversions).toContainEqual(expect.objectContaining({row:1,field:'version_no',sourceValue:token,value:9,ruleVersion:'P3_07_NATIVE_VERSION_V1'}));
 const stored=await maker.readInput({inputId:result.input!.inputId});expect(stored.data?.entries[0]?.row).toMatchObject({version_no:9,source_record_id:'000019'});const reviewer=createLocationUseClient(url,'reviewer');expect((await reviewer.verify(f.verification(stored.data!,result.input!))).response.status).toBe(200);const preview=await maker.preview({inputId:result.input!.inputId});expect(preview.data?.issues,JSON.stringify(preview.error??preview.data?.issues)).toEqual([]);expect(preview.data?.decision).toBe('PASS');
 const requestId=randomUUID(),planned=await maker.plan({inputId:result.input!.inputId,requestId});expect(planned.response.status).toBe(200);expect((await reviewer.review({candidateId:planned.data!.candidateId})).response.status).toBe(200);expect((await reviewer.approve(planned.data!)).response.status).toBe(200);const applied=await maker.apply({candidateId:planned.data!.candidateId,requestId});expect(applied.response.status,JSON.stringify(applied.error)).toBe(200);if(applied.data?.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');expect((await maker.exact({id:applied.data.facts[0]!.id,version:'1'})).data?.facts.source).toMatchObject({sourceVersion:'9',recordLocatorEvidence:{row:2}});
});

test.each(['9.00000000000000001','2147483648'])('R1: native XLSX invalid version $0 keeps raw evidence and cannot stage an integer',async token=>{
 const scope=await f.endpoint(),entry=await f.entry(scope),bytes=nativeWorkbook(entry,token,' t="n"'),received=await createLocationUseClient(url,'maker').file({input:locationUseFileRequest(f,[entry],'XLSX'),contentBase64:bytes.toString('base64')});expect(received.response.status).toBe(200);const result=received.data!;expect(result.input).toBeNull();expect(result.issues,JSON.stringify(result.issues)).toContainEqual(expect.objectContaining({code:'TEXT_CELL_REQUIRED',status:'FAIL'}));const parsed=await parseEvidence(result.validation.run.parseArtifactId),cell=parsed.result.cells.find(cell=>cell.field==='version_no');if(cell)expect(cell).toMatchObject({value:token,sourceType:'n'});else expect(parsed.result.structuralStatus).toBe('REJECTED');const raw=await sensitive(result.sourceArtifactId);try{expect(Buffer.from(raw)).toEqual(bytes);}finally{raw.fill(0);}
});

test.each(['EXCLUSIVE','PRIMARY'] as const)('R3: frozen HTTP race retains stale control and current replanning exposes specific409 $0 conflict',async kind=>{
 const first=await f.endpoint(),second=kind==='EXCLUSIVE'?await f.endpoint('ORG',{campus:first.campus,location:first.location}):{...first,location:await f.newLocation(first.campus.id)},a=await f.entry(first,kind==='EXCLUSIVE'?{kind:'EXCLUSIVE',version:'WHOLE_LOCATION_V1'}:undefined),b=await f.entry(second);if(kind==='PRIMARY'){a.row.is_primary='Y';b.row.is_primary='Y';}
 const q1=await freezeHttp([a]),q2=await freezeHttp([b]),maker=createLocationUseClient(url,'maker'),results=await Promise.all([maker.apply({candidateId:q1.candidateId,requestId:q1.requestId}),maker.apply({candidateId:q2.candidateId,requestId:q2.requestId})]),winner=results.find(r=>r.response.status===200),loser=results.find(r=>r.response.status!==200);expect(results.filter(r=>r.response.status===200)).toHaveLength(1);expect(winner?.data?.status).toBe('COMMITTED');expect(loser).toBeDefined();
 const code=kind==='EXCLUSIVE'?'LOCATION_USE_CONFLICT':'PRIMARY_LOCATION_CONFLICT',message=kind==='EXCLUSIVE'?'地点在相交期间存在独占使用声明，请核对或先按审批流程释放。':'同一组织、院区和用途在相交期间已有主要地点。';expect(loser!.error?.code).toBe('STALE_VALIDATION');expect(loser!.response.status).toBe(409);
 const loserIndex=results.indexOf(loser!),loserPlan=loserIndex===0?q1:q2,loserRequest={candidateId:loserPlan.candidateId,requestId:loserPlan.requestId},conflict=await maker.plan({inputId:loserPlan.inputId,requestId:randomUUID()});expect(conflict.error?.code).toBe(code);expect.soft(conflict.response.status).toBe(409);expect.soft(conflict.error?.message).toBe(message);const candidate=await f.owner.readApplyCandidate('reviewer',{candidateId:loserPlan.candidateId});expect(await signedUseAttempt(connection,receipt,candidate,loserRequest)).toBe(code);expect(await f.owner.resumeOutcome('maker',loserRequest)).toBeNull();if(winner?.data?.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');const winningId=winner.data.facts[0]!.id;expect((await f.owner.list('maker',{campus:'NORTH',campusId:first.campus.id})).items.map(item=>item.id)).toEqual([winningId]);expect(JSON.stringify(conflict.error)).not.toMatch(/PL\/pgSQL|use_mutate|candidateId|source_record_id/);
});

test('R2: requested current B-only nursing window ignores inaccessible historical A, while A and originalR controls retain authorization',async()=>{
 const scope=await f.endpoint('NURSING'),earlyEntry=await f.entry(scope);earlyEntry.row.valid_to='2026-02-01T00:00:00';const early=await f.apply(await f.input([earlyEntry])),earlyId=early.facts[0]!.id,earlyWindow={id:earlyId,validFrom:'2026-01-01T00:00:00',validTo:'2026-02-01T00:00:00',mode:'CURRENT_ADMISSION' as const};expect((await f.owner.evaluateWindow('maker',earlyWindow)).currentAdmissionCovered).toBe(true);
 const nursingHistory=await f.nursing.owner.history('maker',{id:scope.target.id}),original=(await f.nursing.owner.readInput('maker',{inputId:nursingHistory.versions[0]!.facts.source.recordLocatorEvidence.inputId})).entries[0]!,created=await catalog.command('maker',cmd('CREATE',{kind:'SOURCE',code:'TEST_R2_SOURCE_'+randomUUID().replaceAll('-','').toUpperCase(),values:{name:'TEST R2 historical nursing property source',environment:'SYNTHETIC',sourceKind:'MANUAL',deploymentScope:'SYNTHETIC_ALL',businessOwnerRole:'TEST',technicalRole:'TEST',sourceEvidence:f.source.id},validFrom:'2026-01-01T00:00:00',validTo:null})),submitted=await catalog.command('maker',cmd('SUBMIT',{target:created.id,expectedHead:created.head})),sourceA=await catalog.command('reviewer',cmd('PUBLISH',{target:created.id,expectedHead:submitted.head,reviewDigest:submitted.reviewDigest}));
 const reviseContract=async(sourceVersionId:string,label:string)=>{const current=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.id===f.nursing.contract!.id)!,definition={...f.nursing.contract!.definition,ruleVersion:'ORG09_CORE_R2_'+label+'_'+randomUUID().replaceAll('-','').toUpperCase(),sourceVersionId,codeSets:f.nursing.contract!.definition.codeSets.map(c=>({...c,sourceVersionId}))},draft=await catalog.contractCommand('maker',cmd('REVISE',{target:current.id,expectedHead:current.head,datasetVersionId:f.nursing.dataset!.versionId,definition,validFrom:'2026-01-01T00:00:00',validTo:null})),preImpact=await catalog.contractImpact('reviewer','SYNTHETIC',draft.id,'PUBLISH'),approved=await catalog.contractCommand('reviewer',cmd('APPROVE',{target:draft.id,expectedHead:draft.head,reviewDigest:draft.reviewDigest,impactDigest:preImpact.impactDigest})),impact=await catalog.contractImpact('reviewer','SYNTHETIC',draft.id,'PUBLISH');await catalog.contractCommand('reviewer',cmd('PUBLISH',{target:draft.id,expectedHead:approved.head,reviewDigest:approved.reviewDigest,impactDigest:impact.impactDigest}));return (await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.id===draft.id)!;};
 const reviseNursing=async(contract:Awaited<ReturnType<typeof reviseContract>>,sourceId:string,from:string,version:string,recordedAt:string,to='',action:'REVISE'|'SUSPEND'='REVISE')=>{const job=await catalog.importJobCommand('maker',cmd('CREATE',{profile:'CORE',contractId:contract.id,contractVersionId:contract.versionId,input:{kind:'METADATA_ONLY',declaredSha256:'a'.repeat(64)}})),artifact=await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),jobId:job.id,revisionId:job.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds:7200},Buffer.from('TEST R2 independently reviewed nursing source '+version)),h=await f.nursing.owner.history('maker',{id:scope.target.id}),entry:NursingEntry={action,target:{owner:'care-organization/nursing',id:h.id,expectedHead:h.versions.at(-1)!.number},row:{...original.row,source_system_id:sourceId,valid_from:from,valid_to:to,version_no:version,recorded_at:recordedAt,record_status:action==='SUSPEND'?'SUSPENDED':'ACTIVE'},reason:'TEST R2 reviewed property period',evidenceId:artifact.artifactId},value={requestId:randomUUID(),jobId:job.id,revisionId:job.revisionId,campus:'NORTH' as const,profile:'CORE' as const,timePolicy:'LOCAL' as const,entries:[entry]},staged=await f.nursing.owner.stage('maker',value);await f.nursing.owner.verify('reviewer',{requestId:randomUUID(),inputId:staged.inputId,inputDigest:staged.digest,reason:'TEST R2 independent source classification',policyVersion:'ORG09_CORE_V1',rows:[{row:1,evidenceId:artifact.artifactId,classificationAccepted:true}]});const preview=await f.nursing.owner.preview('maker',{inputId:staged.inputId});expect(preview.issues).toEqual([]);expect(preview.decision).toBe('PASS');const requestId=randomUUID(),q=await f.nursing.owner.plan('maker',{inputId:staged.inputId,requestId});await f.nursing.owner.readApplyCandidate('reviewer',{candidateId:q.candidateId});await f.nursing.owner.approveApplyUnit('reviewer',q);const outcome=await f.nursing.owner.applyUnit('maker',{candidateId:q.candidateId,requestId});expect(outcome.status).toBe('COMMITTED');if(outcome.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');return outcome;};
 const lateEntry=await f.entry(scope);lateEntry.row.valid_from='2026-04-01T00:00:00';lateEntry.row.valid_to='2026-12-01T00:00:00';const late=await f.apply(await f.input([lateEntry])),lateFull={id:late.facts[0]!.id,validFrom:lateEntry.row.valid_from,validTo:lateEntry.row.valid_to,mode:'CURRENT_ADMISSION' as const},lateWindow={...lateFull,validTo:'2026-07-01T00:00:00'};
 const sourceAOutcome=await reviseNursing(await reviseContract(sourceA.versionId,'A'),sourceA.id,'2026-01-01T00:00:00','10','2026-01-03T00:00:00'),contractB=await reviseContract(f.source.versionId,'B');await reviseNursing(contractB,f.source.id,'2026-03-01T00:00:00.000001','11','2026-03-02T00:00:00','2026-08-01T00:00:00');expect((await f.owner.evaluateWindow('maker',lateWindow)).currentAdmissionCovered).toBe(true);
 const predicate=`actor_code='maker' AND object_id=${quote(sourceA.id)}::uuid AND scope='SYNTHETIC' AND object_kind='SOURCE' AND purpose='SYNTHETIC_REFERENCE' AND permission='READ'`,grants=JSON.parse(peer(receipt.name,`SELECT coalesce(jsonb_agg(g),'[]')::text FROM vnext_control.object_grant g WHERE ${predicate};`));expect(grants.length).toBeGreaterThan(0);peer(receipt.name,`DELETE FROM vnext_control.object_grant WHERE ${predicate};`);
 try{const actual=await f.owner.evaluateWindow('maker',lateWindow).then(value=>({value,error:undefined}),error=>({value:undefined,error:String(error.message)}));expect.soft(actual.error).toBeUndefined();expect.soft(actual.value?.currentAdmissionCovered).toBe(true);const http=await createLocationUseClient(url,'maker').evaluate(lateWindow);expect.soft(http.response.status,JSON.stringify(http.error)).toBe(200);expect.soft(http.data?.currentAdmissionCovered).toBe(true);await expect(f.owner.evaluateWindow('maker',earlyWindow)).rejects.toThrow('ACCESS_DENIED');await expect(f.owner.evaluateWindow('maker',{...earlyWindow,mode:'HISTORICAL',recordAsOf:sourceAOutcome.recordedAt})).rejects.toThrow('ACCESS_DENIED');expect((await f.owner.evaluateWindow('maker',{...earlyWindow,mode:'HISTORICAL',recordAsOf:early.recordedAt})).currentAdmissionCovered).toBe(true);const finite=await f.owner.evaluateWindow('maker',lateFull).then(value=>({value,error:undefined}),error=>({value:undefined,error:String(error.message)}));expect.soft(finite.error).toBeUndefined();expect.soft(finite.value).toMatchObject({currentAdmissionCovered:false,currentGaps:[{from:'2026-08-01T00:00:00.000000',to:'2026-12-01T00:00:00.000000'}]});await reviseNursing(contractB,f.source.id,'2026-06-01T00:00:00.000001','12','2026-06-02T00:00:00','','SUSPEND');const suspended=await f.owner.evaluateWindow('maker',lateWindow).then(value=>({value,error:undefined}),error=>({value:undefined,error:String(error.message)}));expect.soft(suspended.error).toBeUndefined();expect.soft(suspended.value).toMatchObject({currentAdmissionCovered:false,currentGaps:[{from:'2026-06-01T00:00:00.000001',to:'2026-07-01T00:00:00.000000'}]});}finally{peer(receipt.name,`INSERT INTO vnext_control.object_grant SELECT * FROM jsonb_populate_recordset(NULL::vnext_control.object_grant,${quote(JSON.stringify(grants))}::jsonb) ON CONFLICT DO NOTHING;`);}
});

test('R1: a valid published contract without the native XLSX conversion rule cannot stage its numeric source cell',async()=>{
 const scope=await f.endpoint(),entry=await f.entry(scope),current=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.id===f.contract!.id)!,definition={...current.definition,ruleVersion:'ORG13_CORE_REVIEW1_NO_NUMERIC_'+randomUUID().replaceAll('-','').toUpperCase(),rules:current.definition.rules.filter(rule=>rule.id!=='LOCATION_USE_NATIVE_VERSION_V1')};expect(definition.rules.some(rule=>rule.id==='LOCATION_USE_NATIVE_VERSION_V1')).toBe(false);
 const published=await publishContractRevision(current.id,f.dataset!.versionId,definition);expect(published.status).toBe('PUBLISHED');
 try{const input=locationUseFileRequest(f,[entry],'XLSX');if(input.job.action!=='CREATE')throw new Error('CREATE_FILE_JOB_REQUIRED');input.job={...input.job,contractVersionId:published.versionId};const bytes=nativeWorkbook(entry,'9',' t="n"'),received=await createLocationUseClient(url,'maker').file({input,contentBase64:bytes.toString('base64')});expect(received.response.status,JSON.stringify(received.error)).toBe(200);const result=received.data!;expect.soft(result.input).toBeNull();expect.soft(result.issues).toContainEqual(expect.objectContaining({field:'version_no',code:'LOCATION_USE_NATIVE_VERSION_RULE_REQUIRED',status:'BLOCKED'}));const parsed=await parseEvidence(result.validation.run.parseArtifactId);expect(parsed.result.cells.find(cell=>cell.field==='version_no')).toMatchObject({value:'9',sourceType:'n'});expect((await f.owner.list('maker',{campus:'NORTH',targetId:scope.target.id})).items).toEqual([]);}finally{const restored=await publishContractRevision(current.id,f.dataset!.versionId,{...current.definition,ruleVersion:'ORG13_CORE_REVIEW_RESTORED_'+randomUUID().replaceAll('-','').toUpperCase()});expect(restored.status).toBe('PUBLISHED');expect(restored.definition.rules).toContainEqual(expect.objectContaining({id:'LOCATION_USE_NATIVE_VERSION_V1',version:'P3_07_NATIVE_VERSION_V1',status:'MACHINE'}));}
});
