import {randomUUID} from 'node:crypto';
import type {Catalog,KeyProviderPort} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {openLocationUse,ORG13_FIELDS,type LocationUseScope,type LocationUseEntry,type LocationUseRow,type LocationUseStage,type LocationUseVerification,type LocationUsePolicy} from '../../apps/governance-api/src/modules/location-master/index.js';
import {openLocationUsageTypes} from '../../apps/governance-api/src/modules/location-master/usage-types.js';
import type {UsageTypeItem,UsageTypeReference} from '../../apps/governance-api/src/modules/location-master/usage-type-contracts.js';
import {locationUseUpstreamPorts} from '../../apps/governance-api/src/composition/location-use-dependencies.js';
import {locationFixture} from './p3-06-fixture.js';
import {wardFixture} from './p3-02-fixture.js';
import {nursingFixture} from './p3-03-fixture.js';
import {provisionLocationUse} from './p3-07-provisioning.mjs';
import {peer,quote} from './lineage.mjs';

export async function locationUseFixture(receipt:{name:string;oid:string},role:string,catalog:Catalog,provider:KeyProviderPort,connection:string,persistent=false){
 const published=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG04'&&c.profile==='CORE'&&c.status==='PUBLISHED');
 persistent=!!published&&(await catalog.read('maker',{scope:'SYNTHETIC'})).items.some(i=>i.kind==='SOURCE'&&i.status==='PUBLISHED'&&i.versionId===published.definition.sourceVersionId);
 const wards=await wardFixture(receipt,role,catalog,provider,connection,persistent),base=wards.base,locations=await locationFixture(receipt,role,catalog,provider,connection),nursing=await nursingFixture(receipt,role,catalog,provider,connection,true);
 const cmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'TEST_LOCATION_USE',...extra});
 let dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.kind==='DATASET'&&i.code==='ORG13'&&i.status==='PUBLISHED');
 if(!dataset){const d=await catalog.command('maker',cmd('CREATE',{kind:'DATASET',code:'ORG13',values:{name:'TEST POLICY ONLY 组织地点使用关系'},validFrom:'2026-01-01T00:00:00'})),s=await catalog.command('maker',cmd('SUBMIT',{target:d.id,expectedHead:d.head}));await catalog.command('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:s.head,reviewDigest:s.reviewDigest}));dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.id===d.id)!;}
 const source=base.dep.source,fields=dataset.payload.fields!.map(f=>f.original);if(fields.length!==15||ORG13_FIELDS.length!==15)throw new Error('FULL_FIELD_OMISSION');
 const enums:Record<string,string[]>={target_type:['LEGAL','CAMPUS','ORG','UNIT','WARD','NURSING','TEAM','LOCATION','COST','BED'],is_primary:['Y','N'],record_status:['DRAFT','REVIEW','ACTIVE','SUSPENDED','RETIRED']};
 const definition={ruleVersion:'ORG13_CORE_SRC_'+source.versionId.replaceAll('-','').toUpperCase(),templateVersion:'ORG13_CORE_V1',sourceVersionId:source.versionId,businessKey:['object_location_rel_id'],fields:fields.map(f=>({code:f.code,type:f.type,required:f.required,privacy:f.privacy,condition:f.required==='C'?'EVALUATED':f.required==='R'?'ALWAYS':'OPTIONAL',enumValues:enums[f.code]??[]})),references:fields.filter(f=>f.ref).map(f=>({field:f.code,target:f.ref,status:'LOCATION_USE_CORE'})),rules:[{id:'LOCATION_USE_NATIVE_VERSION_V1',field:'version_no',text:'CSV/XLSX decimal version_no is a source integer; retain original lexeme; JSON requires a native integer.',status:'MACHINE',version:'P3_07_NATIVE_VERSION_V1'},{id:'LOCATION_USE_EMPTY_END_V1',field:'valid_to',text:'CSV/XLSX blank valid_to is an explicit open end; JSON requires native null.',status:'MACHINE',version:'P3_07_EMPTY_END_V1'},{id:'LOCATION_USE_SOURCE_PLUS08_V1',field:'valid_from',text:'Explicit source +08:00 to Asia/Shanghai local; retain original timestamps.',status:'MACHINE',version:'P3_07_TIME_V1'},{id:'LOCATION_USE_APPROVAL_V1',field:'approval_ref',text:'Source approval never replaces platform approval.',status:'MACHINE',version:'P3_07_V1'}],codeSets:Object.entries(enums).map(([field,codes])=>({field,codes,codeSystem:'SYNTHETIC_'+field.toUpperCase(),version:'TEST_POLICY_ONLY_1',status:'SYNTHETIC_ADOPTED',sourceVersionId:source.versionId,validFrom:'2026-01-01T00:00:00',validTo:null}))};
 let contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG13'&&c.profile==='CORE'&&c.status==='PUBLISHED');
 if(!contract||contract.definition.templateVersion!=='ORG13_CORE_V1'||contract.definition.sourceVersionId!==source.versionId){const d=await catalog.contractCommand('maker',contract?cmd('REVISE',{target:contract.id,expectedHead:contract.head,datasetVersionId:dataset.versionId,definition,validFrom:'2026-01-01T00:00:00',validTo:null}):cmd('CREATE',{datasetVersionId:dataset.versionId,profile:'CORE',definition,validFrom:'2026-01-01T00:00:00',validTo:null})),preImpact=contract?await catalog.contractImpact('reviewer','SYNTHETIC',d.id,'PUBLISH'):undefined,a=await catalog.contractCommand('reviewer',cmd('APPROVE',{target:d.id,expectedHead:d.head,reviewDigest:d.reviewDigest,...(preImpact?{impactDigest:preImpact.impactDigest}:{})})),impact=contract?await catalog.contractImpact('reviewer','SYNTHETIC',d.id,'PUBLISH'):undefined;await catalog.contractCommand('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:a.head,reviewDigest:a.reviewDigest,...(impact?{impactDigest:impact.impactDigest}:{})}));contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.id===d.id)!;}
 const newJob=()=>catalog.importJobCommand('maker',cmd('CREATE',{profile:'CORE',contractId:contract!.id,contractVersionId:contract!.versionId,input:{kind:'METADATA_ONLY',declaredSha256:'a'.repeat(64)}}));
 peer(receipt.name,`INSERT INTO vnext_control.protected_grant SELECT a,${quote(dataset.id)}::uuid,s,'IDENTITY_VERIFY',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['NORTH','SOUTH']) s CROSS JOIN unnest(ARRAY['READ','STORE']) p ON CONFLICT DO NOTHING;`);
 const j=await newJob(),artifact=await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds:7200},Buffer.from('TEST POLICY ONLY independently reviewed whole-location purpose and sharing policy'));
 provisionLocationUse(receipt,role,provider);peer(receipt.name,"INSERT INTO location_master.usage_type_access SELECT a,p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE']) p ON CONFLICT DO NOTHING;INSERT INTO location_master.usage_type_access SELECT 'reviewer',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;");
 const dictionary=openLocationUsageTypes(connection,provider),owner=openLocationUse(connection,provider,locationUseUpstreamPorts(locations.owner,wards.lifecycle,base.owner,wards.owner,nursing.owner),dictionary);
 const purpose=async(code='OFFICE_'+randomUUID().slice(0,8).toUpperCase()):Promise<UsageTypeItem>=>{const d=await dictionary.command('maker',{action:'CREATE',requestId:randomUUID(),reason:'TEST POLICY ONLY dictionary',code,name:'TEST 办公用途',meaning:'TEST office occupation meaning '+code,description:null,validFrom:'2026-01-01T00:00:00',validTo:null,sourceId:source.id,sourceVersionId:source.versionId,evidenceId:artifact.artifactId});await dictionary.command('reviewer',{action:'VERIFY',requestId:randomUUID(),reason:'TEST independently checked meaning',target:d.id,expectedHead:d.head,versionId:d.versionId,reviewDigest:d.reviewDigest,evidenceId:artifact.artifactId,meaningAccepted:true});return dictionary.command('reviewer',{action:'APPROVE',requestId:randomUUID(),reason:'TEST independently approved meaning',target:d.id,expectedHead:d.head,versionId:d.versionId,reviewDigest:d.reviewDigest});};
 const reference=(p:UsageTypeItem):UsageTypeReference=>({owner:'location-master/usage-type',id:p.id,versionId:p.versionId,version:p.version});
 const grant=(campusId:string)=>peer(receipt.name,`INSERT INTO location_master.access SELECT a,${quote(campusId)}::uuid,'NORTH',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED']) p ON CONFLICT DO NOTHING;INSERT INTO location_master.access SELECT 'reviewer',${quote(campusId)}::uuid,'NORTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;INSERT INTO location_master.use_access SELECT a,${quote(campusId)}::uuid,'NORTH',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED']) p ON CONFLICT DO NOTHING;INSERT INTO location_master.use_access SELECT 'reviewer',${quote(campusId)}::uuid,'NORTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;`);
 const floors=new Map<string,string>();
 const newLocation=async(campusId:string,type='ROOM',from='2026-01-01T00:00:00')=>{grant(campusId);const floor=floors.get(campusId);if(floor){const e={action:'CREATE' as const,parent:{kind:'EXISTING' as const,reference:{owner:'location-master' as const,id:floor}},row:{...locations.row(campusId,type,randomUUID(),floor),valid_from:from},reason:'TEST additional physical location',evidenceId:locations.artifact.artifactId},out=await locations.apply(await locations.input(campusId,[e]));return {owner:'location-master' as const,id:out.facts[0]!.id};}const tree=locations.tree(campusId).map((e,index)=>index===3?{...e,row:{...e.row,location_type:type,valid_from:from}}:e),out=await locations.apply(await locations.input(campusId,tree));floors.set(campusId,out.facts[2]!.id);return {owner:'location-master' as const,id:out.facts[3]!.id};};
 const endpoint=async(targetType:LocationUseScope['targetType']='ORG',supplied?:{campus:{owner:'organization-master/campus';id:string};location:{owner:'location-master';id:string}}):Promise<LocationUseScope>=>{
  let campus=supplied?.campus,target:LocationUseScope['target'];
  if(targetType==='ORG'){target={owner:'department-master',id:await base.newDepartment()};campus??={owner:'organization-master/campus',id:await locations.newCampus()};}
  else if(targetType==='NURSING'){campus??={owner:'organization-master/campus',id:await locations.newCampus()};peer(receipt.name,`INSERT INTO care_organization.nursing_access SELECT a,${quote(campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED']) p ON CONFLICT DO NOTHING;INSERT INTO care_organization.nursing_access SELECT 'reviewer',${quote(campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;`);const out=await nursing.apply(await nursing.input([nursing.entry({department:{owner:'department-master',id:await nursing.newDepartment()},campus})]));target={owner:'care-organization/nursing',id:out.facts[0]!.id};}
  else{const binding=await wards.endpoint();if(campus&&campus.id!==binding.campus.id)throw new Error('FIXTURE_TARGET_CAMPUS_MISMATCH');campus=binding.campus;target=targetType==='UNIT'?binding.unit:{owner:'care-organization/ward',id:(await wards.apply(await wards.input([wards.entry(binding)]))).facts[0]!.id};}
  grant(campus.id);const p=await purpose();return {targetType,target,campus,location:supplied?.location??await newLocation(campus.id),usageType:{owner:'location-master/usage-type',id:p.id}};
 };
 const row=async(a:LocationUseScope):Promise<LocationUseRow>=>({object_location_rel_id:randomUUID(),target_type:a.targetType,target_id:a.target.id,location_id:a.location.id,usage_type:(await dictionary.read('maker',{id:a.usageType.id})).code,is_primary:'N',sharing_description:'TEST plain source wording',version_no:9,valid_from:'2026-01-01T00:00:00',valid_to:null,record_status:'ACTIVE',source_system_id:source.id,source_record_id:'TEST/ORG13/2',approval_ref:'TEST_POLICY_ONLY',recorded_at:'2026-01-02T00:00:00'});
 const entry=async(a:LocationUseScope,policy:LocationUsePolicy={kind:'SHARED',version:'WHOLE_LOCATION_V1'}):Promise<LocationUseEntry>=>({action:'CREATE',applicability:a,usageType:reference(await dictionary.read('maker',{id:a.usageType.id})),policy,row:await row(a),reason:'TEST independently established location use',evidenceId:artifact.artifactId});
 const input=async(entries:LocationUseEntry[]):Promise<LocationUseStage>=>{const j=await newJob();return {requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',profile:'CORE',timePolicy:'LOCAL',entries};};
 const nativeInput=(value:LocationUseStage)=>({...value,entries:value.entries.map(entry=>{if(typeof entry.row.version_no!=='number')throw new Error('CLOSED_INPUT_REQUIRED');return {...entry,row:{...entry.row,version_no:entry.row.version_no}};})});
 const verification=(v:LocationUseStage,i:{inputId:string;digest:string}):LocationUseVerification=>({requestId:randomUUID(),inputId:i.inputId,inputDigest:i.digest,reason:'TEST independent object, entire period and whole-location policy',policyVersion:'ORG13_CORE_V1',rows:v.entries.map((e,index)=>({row:index+1,evidenceId:artifact.artifactId,classificationAccepted:true,scopeAccepted:true,policyAccepted:true,policy:e.policy,validFrom:e.row.valid_from,validTo:e.row.valid_to||null}))});
 const prepare=async(v:LocationUseStage)=>{const staged=await owner.stage('maker',v);await owner.verify('reviewer',verification(v,staged));const preview=await owner.preview('maker',{inputId:staged.inputId});if(preview.decision!=='PASS')throw new Error(preview.issues.map(i=>i.code).join(','));const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:staged.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);return {candidateId:candidate.candidateId,requestId};};
 const apply=async(v:LocationUseStage)=>{const result=await owner.applyUnit('maker',await prepare(v));if(result.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');return result;};
 return {owner,dictionary,wards,base,locations,nursing,source,dataset,contract,artifact,newJob,purpose,reference,grant,newLocation,endpoint,row,entry,input,nativeInput,verification,prepare,apply,close:async()=>{await owner.close();await dictionary.close();await locations.owner.close();await locations.campus.close();await nursing.close();await wards.close();}};
}
