import {randomUUID} from 'node:crypto';
import type {Catalog,KeyProviderPort} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {openNursingUnit,type NursingBindingInput,type NursingStage,type NursingEntry,type NursingVerification,type NursingRow} from '../../apps/governance-api/src/modules/care-organization/index.js';
import {nursingUpstreamPorts} from '../../apps/governance-api/src/composition/nursing-unit-dependencies.js';
import {businessUnitFixture} from './p3-01-fixture.js';
import {provisionNursingUnit} from './p3-03-provisioning.mjs';
import {peer,quote} from './lineage.mjs';
import {openDepartmentLifecycle} from '../../apps/governance-api/src/modules/department-master/index.js';
import {withCareOrganizationImpacts} from '../../apps/governance-api/src/composition/nursing-unit-dependencies.js';

export async function nursingFixture(receipt:{name:string;oid:string},role:string,catalog:Catalog,provider:KeyProviderPort,connection:string,persistent=false){
 const base=await businessUnitFixture(receipt,role,catalog,provider,connection,persistent);
 const cmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'TEST_NURSING',...extra});
 let dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.kind==='DATASET'&&i.code==='ORG09'&&i.status==='PUBLISHED');
 if(!dataset){const d=await catalog.command('maker',cmd('CREATE',{kind:'DATASET',code:'ORG09',values:{name:'TEST POLICY ONLY 护理单元'},validFrom:'2026-01-01T00:00:00'})),s=await catalog.command('maker',cmd('SUBMIT',{target:d.id,expectedHead:d.head}));await catalog.command('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:s.head,reviewDigest:s.reviewDigest}));dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.id===d.id)!;}
 const fields=dataset.payload.fields!.map(f=>f.original),codes=['DRAFT','REVIEW','ACTIVE','SUSPENDED','RETIRED'];
 const definition={ruleVersion:'ORG09_CORE_V1',templateVersion:'ORG09_CORE_V1',sourceVersionId:base.dep.source.versionId,businessKey:['nursing_unit_id'],fields:fields.map(f=>({code:f.code,type:f.type,required:f.required,privacy:f.privacy,condition:f.required==='C'?'EVALUATED':f.required==='R'?'ALWAYS':'OPTIONAL',enumValues:f.code==='record_status'?codes:[]})),references:fields.filter(f=>f.ref).map(f=>({field:f.code,target:f.ref,status:'NURSING_CORE'})),rules:[{id:'NURSING_APPROVAL_V1',field:'approval_ref',text:'Source approval never replaces platform approval.',status:'MACHINE',version:'P3_03_V1'}],codeSets:[{field:'record_status',codes,codeSystem:'SYNTHETIC_RECORD_STATUS',version:'TEST_POLICY_ONLY_1',status:'SYNTHETIC_ADOPTED',sourceVersionId:base.dep.source.versionId,validFrom:'2026-01-01T00:00:00',validTo:null}]};
 let contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG09'&&c.profile==='CORE'&&c.status==='PUBLISHED');
 if(!contract||contract.definition.templateVersion!=='ORG09_CORE_V1'){const d=await catalog.contractCommand('maker',contract?cmd('REVISE',{target:contract.id,expectedHead:contract.head,datasetVersionId:dataset.versionId,definition,validFrom:'2026-01-01T00:00:00',validTo:null}):cmd('CREATE',{datasetVersionId:dataset.versionId,profile:'CORE',definition,validFrom:'2026-01-01T00:00:00',validTo:null})),a=await catalog.contractCommand('reviewer',cmd('APPROVE',{target:d.id,expectedHead:d.head,reviewDigest:d.reviewDigest})),impact=contract?await catalog.contractImpact('reviewer','SYNTHETIC',d.id,'PUBLISH'):undefined;await catalog.contractCommand('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:a.head,reviewDigest:a.reviewDigest,...(impact?{impactDigest:impact.impactDigest}:{})}));contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.id===d.id)!;}
 const newJob=()=>catalog.importJobCommand('maker',cmd('CREATE',{profile:'CORE',contractId:contract!.id,contractVersionId:contract!.versionId,input:{kind:'METADATA_ONLY',declaredSha256:'a'.repeat(64)}}));
 peer(receipt.name,`INSERT INTO vnext_control.protected_grant SELECT a,${quote(dataset.id)}::uuid,s,'IDENTITY_VERIFY',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['NORTH','SOUTH']) s CROSS JOIN unnest(ARRAY['READ','STORE']) p ON CONFLICT DO NOTHING;`);
 const j=await newJob(),artifact=await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds:7200},Buffer.from('TEST POLICY ONLY independently verified nursing organization'));
 provisionNursingUnit(receipt,role,provider);const owner=openNursingUnit(connection,provider,nursingUpstreamPorts),lifecycle=openDepartmentLifecycle(connection,provider,withCareOrganizationImpacts(()=>base.owner,()=>owner));
 const endpoint=async(suppliedDepartmentId?:string):Promise<NursingBindingInput>=>{const departmentId=suppliedDepartmentId??await base.newDepartment(),campus=await base.operating.createCampus();peer(receipt.name,`INSERT INTO care_organization.nursing_access SELECT a,${quote(campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED']) p ON CONFLICT DO NOTHING;INSERT INTO care_organization.nursing_access SELECT 'reviewer',${quote(campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;`);return {department:{owner:'department-master',id:departmentId},campus:{owner:'organization-master/campus',id:campus.id}};};
 const row=(b:NursingBindingInput):NursingRow=>({nursing_unit_id:randomUUID(),nursing_code:'TEST_'+randomUUID(),nursing_name:'TEST 同名护理组织',campus_id:b.campus.id,managing_org_id:b.department.id,care_level:'TEST 原文',office_phone:'',version_no:'9',valid_from:'2026-01-01T00:00:00',valid_to:'',record_status:'ACTIVE',source_system_id:base.dep.source.id,source_record_id:'TEST/ORG09/2',approval_ref:'TEST_POLICY_ONLY',recorded_at:'2026-01-02T00:00:00'});
 const entry=(b:NursingBindingInput):NursingEntry=>({action:'CREATE',binding:b,row:row(b),reason:'TEST nursing creation',evidenceId:artifact.artifactId});
 const input=async(entries:NursingEntry[]):Promise<NursingStage>=>{const j=await newJob();return {requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',profile:'CORE',timePolicy:'LOCAL',entries};};
 const verification=(v:NursingStage,i:{inputId:string;digest:string}):NursingVerification=>({requestId:randomUUID(),inputId:i.inputId,inputDigest:i.digest,reason:'TEST independent nursing classification',policyVersion:'ORG09_CORE_V1',rows:v.entries.map((_,index)=>({row:index+1,evidenceId:artifact.artifactId,classificationAccepted:true}))});
 const prepare=async(v:NursingStage)=>{const i=await owner.stage('maker',v);await owner.verify('reviewer',verification(v,i));const preview=await owner.preview('maker',{inputId:i.inputId});if(preview.decision!=='PASS')throw new Error(preview.issues.map(i=>i.code).join(','));const requestId=randomUUID(),c=await owner.plan('maker',{inputId:i.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:c.candidateId});await owner.approveApplyUnit('reviewer',c);return {candidateId:c.candidateId,requestId};};
 const apply=async(v:NursingStage)=>{const result=await owner.applyUnit('maker',await prepare(v));if(result.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');return result;};
 return {base,dep:base.dep,lifecycle:lifecycle as ReturnType<typeof openDepartmentLifecycle>,impacts:base.impacts,impactReviews:base.impactReviews,newDepartment:base.newDepartment,owner,contract,dataset,artifact,newJob,endpoint,row,entry,input,verification,prepare,apply,close:async()=>{await lifecycle.close();await owner.close();await base.close();}};
}
