import {readFileSync} from 'node:fs';
import {Pool} from 'pg';
import {openCatalog} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {validationKeys} from './p3-03-validation-keys.mjs';
import {businessUnitFixture} from './p3-01-fixture.js';
import {randomUUID} from 'node:crypto';
const connection=process.env['VNEXT_VALIDATION_OWNER_URL']!,receipt=JSON.parse(readFileSync(process.env['VNEXT_TEST_RECEIPT']!,'utf8')),provider=validationKeys(receipt),catalog=await openCatalog(connection,provider);
const pool=new Pool({connectionString:connection,max:1});let fixture;
try{const role=(await pool.query('select current_user r')).rows[0].r;fixture=await businessUnitFixture(receipt,role,catalog,provider,connection);const department=await fixture.newDepartment(),binding=await fixture.endpoint(department),outcome=await fixture.apply(await fixture.input([fixture.entry(binding)]));if(outcome.status!=='COMMITTED')throw new Error('UPGRADE_PREDECESSOR_REQUIRED');
 const cmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'SYNTHETIC_PREDECESSOR',...extra}),d=await catalog.command('maker',cmd('CREATE',{kind:'DATASET',code:'ORG09',values:{name:'TEST predecessor generic metadata'},validFrom:'2026-01-01T00:00:00'})),submitted=await catalog.command('maker',cmd('SUBMIT',{target:d.id,expectedHead:d.head}));await catalog.command('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:submitted.head,reviewDigest:submitted.reviewDigest}));
 const dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(v=>v.id===d.id)!,field=dataset.payload.fields!.find(v=>v.original.code==='nursing_unit_id')!.original,c=await catalog.contractCommand('maker',cmd('CREATE',{datasetVersionId:dataset.versionId,profile:'CORE',validFrom:'2026-01-01T00:00:00',validTo:null,definition:{ruleVersion:'P3_03_PREDECESSOR_GENERIC_V1',templateVersion:'P3_03_PREDECESSOR_GENERIC_V1',sourceVersionId:fixture.dep.source.versionId,businessKey:[field.code],fields:[{code:field.code,type:field.type,required:field.required,privacy:field.privacy,condition:'ALWAYS',enumValues:[]}],rules:[],references:[],codeSets:[]}})),a=await catalog.contractCommand('reviewer',cmd('APPROVE',{target:c.id,expectedHead:c.head,reviewDigest:c.reviewDigest}));await catalog.contractCommand('reviewer',cmd('PUBLISH',{target:c.id,expectedHead:a.head,reviewDigest:a.reviewDigest}));
 console.log(JSON.stringify({gate:'P3_03_POPULATED_0161',status:'PASS',departmentId:department,unitId:outcome.facts[0]!.id,realOwners:true,genericORG09Contract:true}));}finally{await fixture?.close();await pool.end();await catalog.close();}
