import {randomUUID} from 'node:crypto';
import type {Catalog,KeyProviderPort} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {openCampus,type CampusCommand} from '../../apps/governance-api/src/modules/organization-master/index.js';
import {openLocation,LOCATION_TYPES,type LocationEntry,type LocationRow,type LocationStage} from '../../apps/governance-api/src/modules/location-master/index.js';
import {conditionMappings} from '../../apps/governance-api/src/modules/governance-catalog/validation-sources.generated.js';
import {peer,quote} from './lineage.mjs';
import {provisionCampusAuthority} from './campus-authority.mjs';
import {provisionLocation} from './p3-06-provisioning.mjs';

export async function locationFixture(receipt:{name:string;oid:string},role:string,catalog:Catalog,provider:KeyProviderPort,connection:string){
 const cmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'SYNTHETIC_LOCATION',...extra});
 const publish=async(d:Awaited<ReturnType<Catalog['command']>>)=>{const s=await catalog.command('maker',cmd('SUBMIT',{target:d.id,expectedHead:d.head}));return catalog.command('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:s.head,reviewDigest:s.reviewDigest}));};
 let source=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.kind==='SOURCE'&&i.status==='PUBLISHED'&&i.validTo===null);
 if(!source){const published=await publish(await catalog.command('maker',cmd('CREATE',{kind:'SOURCE',code:'LOCATION_TEST_SOURCE',values:{name:'TEST POLICY ONLY manual location inventory',environment:'SYNTHETIC',sourceKind:'MANUAL',deploymentScope:'SYNTHETIC_ALL',businessOwnerRole:'TEST',technicalRole:'TEST',sourceEvidence:'SYNTHETIC_BOOTSTRAP'},validFrom:'2026-01-01T00:00:00'})));source=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.id===published.id)!;}
 let dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.kind==='DATASET'&&i.code==='ORG12'&&i.status==='PUBLISHED');
 if(!dataset){const published=await publish(await catalog.command('maker',cmd('CREATE',{kind:'DATASET',code:'ORG12',values:{name:'TEST POLICY ONLY 空间地点'},validFrom:'2026-01-01T00:00:00'})));dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.id===published.id)!;}
 const fields=dataset.payload.fields!.map(f=>f.original),enums:Record<string,string[]>={location_type:[...LOCATION_TYPES],is_accessible:['Y','N'],record_status:['DRAFT','REVIEW','ACTIVE','SUSPENDED','RETIRED']};
 const definition={ruleVersion:'ORG12_CORE_V1',templateVersion:'ORG12_CORE_V1',sourceVersionId:source.versionId,businessKey:['location_id'],fields:fields.map(f=>({code:f.code,type:f.type,required:f.required,privacy:f.privacy,condition:f.required==='C'?'EVALUATED':f.required==='R'?'ALWAYS':'OPTIONAL',enumValues:enums[f.code]??[]})),references:fields.filter(f=>f.ref).map(f=>({field:f.code,target:f.ref,status:'LOCATION_CORE'})),rules:[...conditionMappings.filter(r=>r.dataset==='ORG12').map(r=>({id:r.id,field:r.field,text:r.text,status:'MACHINE',version:r.version})),{id:'LOCATION_APPROVAL_V1',field:'approval_ref',text:'Source approval never replaces platform approval.',status:'MACHINE',version:'P3_06_V1'}],codeSets:Object.entries(enums).map(([field,codes])=>({field,codes,codeSystem:'SYNTHETIC_'+field.toUpperCase(),version:'TEST_POLICY_ONLY_1',status:'SYNTHETIC_ADOPTED',sourceVersionId:source!.versionId,validFrom:'2026-01-01T00:00:00',validTo:null}))};
 let contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG12'&&c.profile==='CORE'&&c.status==='PUBLISHED');
 if(!contract||contract.definition.templateVersion!=='ORG12_CORE_V1'){
  // CORE is a stable registry identity. Adopt a new explicit version through its
  // public approval workflow when the retained database has a legacy template.
  const d=contract?await catalog.contractCommand('maker',cmd('REVISE',{target:contract.id,expectedHead:contract.head,datasetVersionId:dataset.versionId,definition,validFrom:'2026-01-01T00:00:00',validTo:null})):await catalog.contractCommand('maker',cmd('CREATE',{datasetVersionId:dataset.versionId,profile:'CORE',definition,validFrom:'2026-01-01T00:00:00',validTo:null}));
  const a=await catalog.contractCommand('reviewer',cmd('APPROVE',{target:d.id,expectedHead:d.head,reviewDigest:d.reviewDigest}));await catalog.contractCommand('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:a.head,reviewDigest:a.reviewDigest}));contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.id===d.id)!;
 }
 const newJob=()=>catalog.importJobCommand('maker',cmd('CREATE',{profile:'CORE',contractId:contract!.id,contractVersionId:contract!.versionId,input:{kind:'METADATA_ONLY',declaredSha256:'a'.repeat(64)}}));
 peer(receipt.name,`INSERT INTO vnext_control.protected_grant SELECT a,${quote(dataset.id)}::uuid,'NORTH','IDENTITY_VERIFY',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','STORE']) p ON CONFLICT DO NOTHING;`);
 const proof=await newJob(),artifact=await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),jobId:proof.id,revisionId:proof.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds:7200},Buffer.from('TEST POLICY ONLY physical inventory, explicit root and strict type adoption; no hospital policy approval'));
 provisionCampusAuthority(receipt,provider);provisionLocation(receipt,role,provider);
 const campus=openCampus(connection,provider),owner=openLocation(connection,provider,campus.references);
 const newCampus=async()=>{
  const j=await newJob(),command:CampusCommand={action:'CREATE',source:{systemId:source!.id,versionId:source!.versionId,alias:'TEST_CAMPUS',versionNo:1,recordLocator:'TEST/ORG02/2',recordedAt:'2026-01-01T00:00:00',recordStatus:'PUBLISHED',approvalRef:'TEST_POLICY_ONLY'},evidence:artifact.artifactId,sourceOperationStatus:'PLANNING',validFrom:'2026-01-01T00:00:00',validTo:null,facts:{campusCode:'TEST_'+randomUUID(),campusName:'TEST campus without clinical authority',nodeRole:'HEADQUARTERS',nodeKind:'PHYSICAL',campusAddress:null,adminDivision:null,publicPhone:null,openingDate:null}};
  const staged=await campus.stage('maker',{requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',command});const requestId=randomUUID(),candidate=await campus.plan('maker',{inputId:staged.inputId,requestId});await campus.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await campus.approveApplyUnit('reviewer',candidate);const outcome=await campus.applyUnit('maker',{candidateId:candidate.candidateId,requestId});if(outcome.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');const id=outcome.facts[0]!.id;
  peer(receipt.name,`INSERT INTO location_master.access SELECT a,${quote(id)}::uuid,'NORTH',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED']) p;INSERT INTO location_master.access SELECT 'reviewer',${quote(id)}::uuid,'NORTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p;`);
  return id;
 };
 const row=(campusId:string,type='ROOM',alias:string=randomUUID(),parent=''):LocationRow=>({location_id:alias,location_code:'TEST_'+randomUUID(),location_name:'TEST location',campus_id:campusId,parent_location_id:parent,location_type:type,floor_label:['CAMPUS','BUILDING'].includes(type)?'':'1',room_number:['ROOM','CLINIC_ROOM','OPERATING_ROOM'].includes(type)?'001':'',address_detail:'',is_accessible:'',version_no:'7',valid_from:'2026-01-01T00:00:00',valid_to:'',record_status:'ACTIVE',source_system_id:source!.id,source_record_id:'TEST/ORG12/2',approval_ref:'TEST_POLICY_ONLY',recorded_at:'2026-01-02T00:00:00'});
 const entry=(campusId:string,type:string,alias:string,parent:string|null):LocationEntry=>({action:'CREATE',parent:parent===null?null:{kind:'ALIAS',clientKey:parent},row:row(campusId,type,alias,parent??''),reason:'TEST POLICY ONLY creation',evidenceId:artifact.artifactId});
 const tree=(id:string)=>[entry(id,'CAMPUS','C',null),entry(id,'BUILDING','B','C'),entry(id,'FLOOR','F','B'),entry(id,'ROOM','R','F')];
 const input=async(campusId:string,entries:LocationEntry[]):Promise<LocationStage>=>{const j=await newJob();return {requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',campusId,profile:'CORE',timePolicy:'LOCAL',entries};};
 const prepare=async(value:LocationStage)=>{const staged=await owner.stage('maker',value);await owner.verify('reviewer',{requestId:randomUUID(),inputId:staged.inputId,inputDigest:staged.digest,evidenceId:artifact.artifactId,reason:'TEST POLICY ONLY physical facts checked',physicalFactsAccepted:true,policyVersion:'ORG12_CORE_V1'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:staged.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);return {candidateId:candidate.candidateId,requestId};};
 const apply=async(value:LocationStage)=>{const result=await owner.applyUnit('maker',await prepare(value));if(result.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');return result;};
 const retireCampus=async(id:string,at:string)=>{
  const h=await campus.references.history('maker',id),j=await newJob(),assessment=await campus.assessCampusImpact('maker',{id,validFrom:at,validTo:null});
  const command:CampusCommand={action:'RETIRE',target:{owner:'organization-master/campus',id,expectedVersion:h.head},source:{systemId:source!.id,versionId:source!.versionId,alias:'TEST_CAMPUS',versionNo:2,recordLocator:'TEST/ORG02/3',recordedAt:'2026-01-02T00:00:00',recordStatus:'PUBLISHED',approvalRef:'TEST_POLICY_ONLY'},evidence:artifact.artifactId,sourceOperationStatus:'RETIRED',validFrom:at,validTo:null,reason:'TEST retirement with pending disposition',assessmentDigest:assessment.digest,plan:{responsibleOwner:'TEST office',dueAt:'2027-01-01T00:00:00',actions:'TEST explicit location disposition remains pending'}};
  const staged=await campus.stage('maker',{requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',command}),requestId=randomUUID(),candidate=await campus.plan('maker',{inputId:staged.inputId,requestId});await campus.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await campus.approveApplyUnit('reviewer',candidate);return campus.applyUnit('maker',{candidateId:candidate.candidateId,requestId});
 };
 return {owner,campus,source,contract,dataset,artifact,newJob,newCampus,row,entry,tree,input,prepare,apply,retireCampus};
}
