import {randomUUID} from 'node:crypto';
import type {Catalog,ImportContractItem} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {conditionMappings} from '../../apps/governance-api/src/modules/governance-catalog/validation-sources.generated.js';
export async function subjectPermissionContract(catalog:Catalog,source:{id:string;versionId:string}){
 const cmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'TEST_SUBJECT_PERMISSION',...extra});
 let dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.kind==='DATASET'&&i.code==='ORG17'&&i.status==='PUBLISHED');
 if(!dataset){const d=await catalog.command('maker',cmd('CREATE',{kind:'DATASET',code:'ORG17',values:{name:'TEST POLICY ONLY 诊疗科目许可'},validFrom:'2026-01-01T00:00:00'})),s=await catalog.command('maker',cmd('SUBMIT',{target:d.id,expectedHead:d.head}));await catalog.command('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:s.head,reviewDigest:s.reviewDigest}));dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.id===d.id)!;}
 const fields=dataset.payload.fields!.map(f=>f.original),enums:Record<string,string[]>={target_type:['LEGAL','ORG','UNIT'],record_status:['DRAFT','REVIEW','ACTIVE','SUSPENDED','RETIRED']};
 const definition={ruleVersion:'ORG17_CORE_V1',templateVersion:'ORG17_CORE_V1',sourceVersionId:source.versionId,businessKey:['subject_license_id'],fields:fields.map(f=>({code:f.code,type:f.type,required:f.required,privacy:f.privacy,condition:f.required==='C'?'EVALUATED':f.required==='R'?'ALWAYS':'OPTIONAL',enumValues:enums[f.code]??[]})),references:fields.filter(f=>f.ref).map(f=>({field:f.code,target:f.ref,status:'SUBJECT_CORE'})),rules:[...conditionMappings.filter(r=>r.dataset==='ORG17').map(r=>({id:r.id,field:r.field,text:r.text,status:'MACHINE',version:r.version})),{id:'SUBJECT_APPROVAL_V1',field:'approval_ref',text:'Source approval never replaces platform approval.',status:'MACHINE',version:'P3_09_V1'},{id:'SUBJECT_EMPTY_END_V1',field:'valid_to',text:'CSV/XLSX blank valid_to is an explicit open end; JSON requires native null.',status:'MACHINE',version:'P3_09_EMPTY_END_V1'},{id:'SUBJECT_SOURCE_PLUS08_V1',field:'valid_from',text:'Explicit source +08:00 to Asia/Shanghai local; retain original timestamps.',status:'MACHINE',version:'P3_09_TIME_V1'}],codeSets:Object.entries(enums).map(([field,codes])=>({field,codes,codeSystem:'SYNTHETIC_'+field.toUpperCase(),version:'TEST_POLICY_ONLY_1',status:'SYNTHETIC_ADOPTED',sourceVersionId:source.versionId,validFrom:'2026-01-01T00:00:00',validTo:null}))};
 const d=await catalog.contractCommand('maker',cmd('CREATE',{datasetVersionId:dataset.versionId,profile:'CORE',definition,validFrom:'2026-01-01T00:00:00',validTo:null})),a=await catalog.contractCommand('reviewer',cmd('APPROVE',{target:d.id,expectedHead:d.head,reviewDigest:d.reviewDigest}));await catalog.contractCommand('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:a.head,reviewDigest:a.reviewDigest}));
 const contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.id===d.id)!;
 const newJob=()=>catalog.importJobCommand('maker',cmd('CREATE',{profile:'CORE',contractId:contract.id,contractVersionId:contract.versionId,input:{kind:'METADATA_ONLY',declaredSha256:'a'.repeat(64)}}));
 return {dataset,contract:contract as ImportContractItem,newJob};
}
