import {test,expect} from 'vitest';
import {normalizeUnitRow,unitCheck,UnitEntrySchema,type UnitRow} from '../../apps/governance-api/src/modules/care-organization/index.js';
const id='00000000-0000-7000-8000-000000000001';
const row:UnitRow={unit_id:'source-alias',unit_code:'TEST_U',unit_name:'TEST',org_id:id,campus_id:id,legal_entity_id:id,unit_type:'OPD',public_phone:'',service_description:'',receiving_rule_ref:'',business_owner_id:'',version_no:'1',valid_from:'2026-01-01T00:00:00.123456',valid_to:'',record_status:'ACTIVE',source_system_id:id,source_record_id:'TEST/2',approval_ref:'TEST',recorded_at:'2026-01-02T00:00:00'};
test('microseconds and unbounded half-open periods retain source values',()=>{expect(normalizeUnitRow(row,'LOCAL')).toMatchObject({from:'2026-01-01T00:00:00.123456',to:null,row});});
test.each(['2026-02-30T00:00:00','2026-01-01T00:00:00Z','2026-01-01T00:00:00+08:00'])('local API rejects invalid or offset time %s',valid_from=>{expect(()=>normalizeUnitRow({...row,valid_from},'LOCAL')).toThrow('LOCAL_TIME_REQUIRED');});
test('explicit source +08 conversion preserves original bytes and microseconds',()=>{const input={...row,valid_from:row.valid_from+'+08:00',recorded_at:row.recorded_at+'+08:00'};expect(normalizeUnitRow(input,'SOURCE_PLUS08_TO_LOCAL')).toMatchObject({from:row.valid_from,row:input});});
test('zero or reversed periods cannot become facts',()=>{expect(()=>normalizeUnitRow({...row,valid_to:row.valid_from},'LOCAL')).toThrow('INVALID_BUSINESS_PERIOD');});
test('CREATE cannot choose a platform target and REVISE cannot carry a hidden binding',()=>{const binding={department:{owner:'department-master',id},campus:{owner:'organization-master/campus',id},subject:{owner:'organization-master',id},relation:{owner:'department-master/campus-relation',id,version:'1',versionId:id},services:['TEST_SERVICE']},common={row,reason:'TEST',evidenceId:id},target={owner:'care-organization/unit',id,expectedHead:'1'};expect(()=>unitCheck(UnitEntrySchema,{...common,action:'CREATE',binding,target})).toThrow('CLOSED_INPUT_REQUIRED');expect(()=>unitCheck(UnitEntrySchema,{...common,action:'REVISE',target,binding})).toThrow('CLOSED_INPUT_REQUIRED');});
