import {readFileSync} from 'node:fs';
import {randomUUID,createHash} from 'node:crypto';
import {Pool} from 'pg';
import {beforeAll,afterAll,test,expect} from 'vitest';
import {openCatalog,type Catalog} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {unzip,type ParserResult} from '../../apps/governance-api/src/modules/governance-catalog/file-parser.js';
import {zipText} from '../../apps/governance-api/src/modules/governance-catalog/issue-workbook.js';
import {ORG13_FIELDS} from '../../apps/governance-api/src/modules/location-master/index.js';
import {buildCatalogServer} from '../../apps/governance-api/src/composition/build-vnext-catalog.js';
import {actor} from '../../apps/governance-api/src/platform/fastify/vnext-catalog-routes.js';
import {createLocationUseClient,createLocationUsageTypeClient} from '../../packages/generated-api-client/src/index.js';
import {locationUseFixture} from './p3-07-fixture.js';
import {validationKeys} from './p3-07-validation-keys.mjs';
import {peer,quote} from './lineage.mjs';
import {locationUseFile,locationUseFileRequest,signedUseAttempt,type LocationUseFixture} from './p3-07-validation-helpers.js';
import {workbookBarrier} from './p3-05-validation-helpers.js';

const connection=process.env['VNEXT_VALIDATION_OWNER_URL']!,receipt=JSON.parse(readFileSync(process.env['VNEXT_TEST_RECEIPT']!,'utf8'));
let catalog:Catalog,f:LocationUseFixture,app:Awaited<ReturnType<typeof buildCatalogServer>>,url:string;
beforeAll(async()=>{
 const provider=validationKeys(receipt),pool=new Pool({connectionString:connection,max:1});
 try{catalog=await openCatalog(connection,provider);const role=(await pool.query('select current_user r')).rows[0]!.r;f=await locationUseFixture(receipt,role,catalog,provider,connection,process.env['VNEXT_P3_07_UPGRADED']==='1');const contexts:Parameters<typeof buildCatalogServer>=[catalog,'CONTROL_PLANE'];contexts[24]={owner:f.owner,usageTypes:f.dictionary,actor:r=>actor(r.headers)};app=await buildCatalogServer(...contexts);url=await app.listen({host:'127.0.0.1',port:0});}finally{await pool.end();}
});
afterAll(async()=>{await app?.close();await f?.close();await catalog?.close();});
const sensitive=async(id:string)=>catalog.authorizeSensitiveRead('maker',{scope:'SYNTHETIC',requestId:randomUUID(),artifactId:id,campus:'NORTH',purpose:'IDENTITY_VERIFY'});

test.each(['CSV','JSON','XLSX'] as const)('actual generated HTTP %s preserves all15 fields, source lexemes, raw bytes and conversion evidence through Apply',async format=>{
 const a=await f.endpoint(),entry=await f.entry(a),marker='TEST_PRIVATE_LOCATOR_'+randomUUID();entry.row={...entry.row,sharing_description:'TEST plain source description',source_record_id:marker,valid_from:'2026-01-01T00:00:00.000001',recorded_at:'2026-01-02T00:00:00.120'};
 const fields=[...ORG13_FIELDS].reverse(),bytes=locationUseFile([entry.row],format,fields),maker=createLocationUseClient(url,'maker'),reviewer=createLocationUseClient(url,'reviewer'),received=await maker.file({input:locationUseFileRequest(f,[entry],format),contentBase64:bytes.toString('base64')});
 expect(received.response.status,JSON.stringify(received.error)).toBe(200);const result=received.data!;expect(result.issues).toEqual([]);expect(result.input).not.toBeNull();
 const raw=await sensitive(result.sourceArtifactId);try{expect(Buffer.from(raw)).toEqual(bytes);}finally{raw.fill(0);}
 const stored=(await maker.readInput({inputId:result.input!.inputId})).data!;expect(Object.keys(stored.entries[0]!.row).sort()).toEqual([...ORG13_FIELDS].sort());expect(stored.entries[0]!.row).toEqual(entry.row);expect(stored.sourceRows).toEqual([format==='JSON'?1:2]);expect(stored.sourceArtifactId).toBe(result.sourceArtifactId);
 const parseBytes=await sensitive(result.validation.run.parseArtifactId);let parsed:{result:ParserResult;conversions:Array<{field:string;sourceValue:unknown;value:unknown;ruleVersion:string}>};try{parsed=JSON.parse(Buffer.from(parseBytes).toString('utf8'));}finally{parseBytes.fill(0);}
 expect(parsed.result.cells).toHaveLength(15);expect(parsed.result.cells.find(cell=>cell.field==='source_record_id')).toMatchObject({value:marker,column:fields.indexOf('source_record_id')+1,sourceRow:format==='JSON'?1:2});expect(parsed.result.cells.find(cell=>cell.field==='recorded_at')?.value).toBe(entry.row.recorded_at);expect(parsed.result.nativeRows?.[0]?.['version_no']).toBe(format==='JSON'?9:'9');
 if(format==='JSON'){expect(parsed.result.nativeRows?.[0]?.['valid_to']).toBeNull();expect(parsed.conversions).toEqual([]);}else{expect(parsed.conversions).toContainEqual(expect.objectContaining({field:'version_no',sourceValue:'9',value:9,ruleVersion:'P3_07_NATIVE_VERSION_V1'}));expect(parsed.conversions).toContainEqual(expect.objectContaining({field:'valid_to',sourceValue:'',value:null,ruleVersion:'P3_07_EMPTY_END_V1'}));}
 expect((await reviewer.verify(f.verification(stored,result.input!))).response.status).toBe(200);const preview=await maker.preview({inputId:result.input!.inputId});expect(preview.data?.issues,JSON.stringify(preview.data?.issues??preview.error)).toEqual([]);expect(preview.data?.decision,JSON.stringify(preview.data?.issues??preview.error)).toBe('PASS');
 const requestId=randomUUID(),planned=await maker.plan({inputId:result.input!.inputId,requestId});expect(planned.response.status).toBe(200);const candidate=await reviewer.review({candidateId:planned.data!.candidateId});expect(candidate.response.status).toBe(200);expect(JSON.stringify(candidate.data)).toContain(marker);expect((await reviewer.approve(planned.data!)).response.status).toBe(200);
 const applied=await maker.apply({candidateId:planned.data!.candidateId,requestId});expect(applied.response.status,JSON.stringify(applied.error)).toBe(200);if(applied.data?.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');const exact=await maker.exact({id:applied.data.facts[0]!.id,version:'1'});expect(exact.data).toMatchObject({validFrom:'2026-01-01T00:00:00.000001',validTo:null,facts:{sharingDescription:entry.row.sharing_description,source:{sourceVersion:'9',sourceRecordedAt:'2026-01-02T00:00:00.120000',recordLocatorEvidence:{row:format==='JSON'?1:2}}}});
 const masked=await catalog.readMasked('maker',{scope:'SYNTHETIC',requestId:randomUUID(),artifactId:result.sourceArtifactId,campus:'NORTH',purpose:'IDENTITY_VERIFY'});expect(masked.masked).toBe('[REDACTED]');for(const value of [preview.data,masked,applied.data,exact.data])expect(JSON.stringify(value)).not.toContain(marker);expect(JSON.stringify(applied.data)).not.toContain(createHash('sha256').update(bytes).digest('hex'));
 expect((await createLocationUseClient(url,'outsider').readInput({inputId:result.input!.inputId})).response.status).toBe(403);await expect(catalog.authorizeSensitiveRead('outsider',{scope:'SYNTHETIC',requestId:randomUUID(),artifactId:result.sourceArtifactId,campus:'NORTH',purpose:'IDENTITY_VERIFY'})).rejects.toThrow('ACCESS_DENIED');
});

test.each(['CSV','JSON'] as const)('actual generated HTTP %s preserves optional source approval exactly while platform verification and approval remain required',async format=>{
 const a=await f.endpoint(),entry=await f.entry(a),sourceApproval=format==='CSV'?'':null;entry.row.approval_ref=sourceApproval;
 const bytes=locationUseFile([entry.row],format),maker=createLocationUseClient(url,'maker'),reviewer=createLocationUseClient(url,'reviewer'),received=await maker.file({input:locationUseFileRequest(f,[entry],format),contentBase64:bytes.toString('base64')});
 expect(received.response.status,JSON.stringify(received.error)).toBe(200);const result=received.data!;expect(result.issues).toEqual([]);expect(result.input).not.toBeNull();const raw=await sensitive(result.sourceArtifactId);try{expect(Buffer.from(raw)).toEqual(bytes);}finally{raw.fill(0);}
 const stored=(await maker.readInput({inputId:result.input!.inputId})).data!;expect(stored.entries[0]!.row.approval_ref).toBe(sourceApproval);
 const parseBytes=await sensitive(result.validation.run.parseArtifactId);let parsed:{result:ParserResult;conversions:Array<{field:string;sourceValue:unknown;value:unknown;ruleVersion:string}>};try{parsed=JSON.parse(Buffer.from(parseBytes).toString('utf8'));}finally{parseBytes.fill(0);}
 expect(parsed.result.cells.find(cell=>cell.field==='approval_ref')).toMatchObject({value:format==='CSV'?'':'null',sourceType:format});expect(parsed.conversions.filter(conversion=>conversion.field==='approval_ref')).toEqual([]);
 const before=await maker.preview({inputId:result.input!.inputId});expect(before.data?.decision).toBe('BLOCKED');expect(before.data?.issues).toContainEqual(expect.objectContaining({code:'LEGAL_REVIEW_REQUIRED'}));
 expect((await reviewer.verify(f.verification(stored,result.input!))).response.status).toBe(200);const preview=await maker.preview({inputId:result.input!.inputId});expect(preview.data?.issues,JSON.stringify(preview.data?.issues??preview.error)).toEqual([]);expect(preview.data?.decision).toBe('PASS');
 const requestId=randomUUID(),planned=await maker.plan({inputId:result.input!.inputId,requestId});expect(planned.response.status,JSON.stringify(planned.error)).toBe(200);expect((await reviewer.review({candidateId:planned.data!.candidateId})).response.status).toBe(200);expect((await reviewer.approve(planned.data!)).response.status).toBe(200);
 const applied=await maker.apply({candidateId:planned.data!.candidateId,requestId});expect(applied.response.status,JSON.stringify(applied.error)).toBe(200);if(applied.data?.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');const id=applied.data.facts[0]!.id,ownerExact=await f.owner.exact('maker',{id,version:'1'});expect(ownerExact.facts.source.approvalReference).toBe(entry.row.approval_ref);const exact=await maker.exact({id,version:'1'});expect(exact.response.status,JSON.stringify(exact.error)).toBe(200);expect(exact.data?.facts.source.approvalReference).toBe(sourceApproval);
});

test('actual generated dictionary list includes approved and draft content visible to the current reader',async()=>{
 const approved=await f.purpose(),maker=createLocationUsageTypeClient(url,'maker'),created=await maker.command({action:'CREATE',requestId:randomUUID(),reason:'TEST list draft beside accepted purpose',code:'LIST_'+randomUUID().replaceAll('-','').toUpperCase(),name:'TEST list-only draft',meaning:'TEST independent office purpose draft',description:null,validFrom:'2026-01-01T00:00:00',validTo:null,sourceId:f.source.id,sourceVersionId:f.source.versionId,evidenceId:f.artifact.artifactId});expect(created.response.status,JSON.stringify(created.error)).toBe(200);const listed=await maker.list({limit:100});expect(listed.response.status,JSON.stringify(listed.error)).toBe(200);const items=[...listed.data!.items];let after=listed.data!.nextAfterId;while(after!==null){const page=await maker.list({after,limit:100});expect(page.response.status,JSON.stringify(page.error)).toBe(200);items.push(...page.data!.items);after=page.data!.nextAfterId;}expect(items).toContainEqual(expect.objectContaining({id:approved.id,status:'APPROVED'}));expect(items).toContainEqual(expect.objectContaining({id:created.data!.id,status:'DRAFT'}));expect((await createLocationUsageTypeClient(url,'outsider').list({limit:100})).response.status).toBe(403);
});

test('public dictionary B/R Owner preserves enablement before the actual disable business boundary in read, history and list',async()=>{
 const approved=await f.purpose(),disabled=await f.dictionary.command('maker',{action:'DISABLE',requestId:randomUUID(),reason:'TEST B/R dictionary disable boundary',target:approved.id,expectedHead:approved.head}),eventAt=disabled.events.at(-1)!.recordedAt;
 const before={id:approved.id,recordAsOf:eventAt,businessAt:'2026-01-01T00:00:00'},boundary={...before,businessAt:eventAt};
 expect(await f.dictionary.read('maker',before)).toMatchObject({enabled:true,applicableAtBusinessTime:true});expect(await f.dictionary.read('maker',boundary)).toMatchObject({enabled:false,applicableAtBusinessTime:true});expect((await f.dictionary.read('maker',{...before,businessAt:'2025-12-31T23:59:59.999999'})).applicableAtBusinessTime).toBe(false);expect((await f.dictionary.read('maker',{id:approved.id,recordAsOf:eventAt})).applicableAtBusinessTime).toBeNull();
 expect((await f.dictionary.history('maker',before)).at(-1)?.enabled).toBe(true);expect((await f.dictionary.history('maker',boundary)).at(-1)?.enabled).toBe(false);
 for(const [businessAt,enabled] of [['2026-01-01T00:00:00',true],[eventAt,false]] as const){const input={limit:100,recordAsOf:eventAt,businessAt},page=await f.dictionary.list('maker',input),items=[...page.items];let after=page.nextAfterId;while(after!==null){const next=await f.dictionary.list('maker',{...input,after});items.push(...next.items);after=next.nextAfterId;}expect(items.find(item=>item.id===approved.id)?.enabled).toBe(enabled);}
});

test('public dictionary B/R HTTP sends explicit businessAt through the generated client and preserves the disable boundary',async()=>{
 const approved=await f.purpose(),client=createLocationUsageTypeClient(url,'maker'),disabled=await client.command({action:'DISABLE',requestId:randomUUID(),reason:'TEST generated HTTP B/R boundary',target:approved.id,expectedHead:approved.head});expect(disabled.response.status,JSON.stringify(disabled.error)).toBe(200);const eventAt=disabled.data!.events.at(-1)!.recordedAt;
 const before={id:approved.id,recordAsOf:eventAt,businessAt:'2026-01-01T00:00:00'},boundary={...before,businessAt:eventAt},earlier=await client.read(before);expect(earlier.response.status,JSON.stringify(earlier.error)).toBe(200);expect(earlier.data).toMatchObject({enabled:true,applicableAtBusinessTime:true});const beforeContent=await client.read({...before,businessAt:'2025-12-31T23:59:59.999999'}),defaultRead=await client.read({id:approved.id,recordAsOf:eventAt});expect(beforeContent.response.status,JSON.stringify(beforeContent.error)).toBe(200);expect(beforeContent.data?.applicableAtBusinessTime).toBe(false);expect(defaultRead.response.status,JSON.stringify(defaultRead.error)).toBe(200);expect(defaultRead.data?.applicableAtBusinessTime).toBeNull();const atBoundary=await client.read(boundary);expect(atBoundary.response.status,JSON.stringify(atBoundary.error)).toBe(200);expect(atBoundary.data).toMatchObject({enabled:false,applicableAtBusinessTime:true});
 const earlierHistory=await client.history(before),boundaryHistory=await client.history(boundary);expect(earlierHistory.response.status,JSON.stringify(earlierHistory.error)).toBe(200);expect(earlierHistory.data?.at(-1)?.enabled).toBe(true);expect(boundaryHistory.response.status,JSON.stringify(boundaryHistory.error)).toBe(200);expect(boundaryHistory.data?.at(-1)?.enabled).toBe(false);
 for(const [businessAt,enabled] of [['2026-01-01T00:00:00',true],[eventAt,false]] as const){const input={limit:100,recordAsOf:eventAt,businessAt},page=await client.list(input);expect(page.response.status,JSON.stringify(page.error)).toBe(200);const items=[...page.data!.items];let after=page.data!.nextAfterId;while(after!==null){const next=await client.list({...input,after});expect(next.response.status,JSON.stringify(next.error)).toBe(200);items.push(...next.data!.items);after=next.data!.nextAfterId;}expect(items.find(item=>item.id===approved.id)?.enabled).toBe(enabled);}
});

test('actual XLSX native numeric version is retained as number without coercing its leading-zero locator',async()=>{
 const a=await f.endpoint(),entry=await f.entry(a);entry.row.source_record_id='000019';const fields=[...ORG13_FIELDS].reverse(),files=Object.fromEntries(unzip(locationUseFile([entry.row],'XLSX',fields),true)),column=String.fromCharCode(65+fields.indexOf('version_no')),address=column+'2';files['xl/worksheets/sheet9.xml']=files['xl/worksheets/sheet9.xml']!.replace(new RegExp('<c r="'+address+'"[^>]*>.*?</c>'),'<c r="'+address+'" t="n"><v>9</v></c>');
 const bytes=zipText(files),received=await createLocationUseClient(url,'maker').file({input:locationUseFileRequest(f,[entry],'XLSX'),contentBase64:bytes.toString('base64')});expect(received.response.status,JSON.stringify(received.error)).toBe(200);expect(received.data?.issues).toEqual([]);const result=received.data!,stored=await f.owner.readInput('maker',{inputId:result.input!.inputId});expect(stored.entries[0]!.row).toMatchObject({version_no:9,source_record_id:'000019'});const parsedBytes=await sensitive(result.validation.run.parseArtifactId);try{const parsed:{result:ParserResult}=JSON.parse(Buffer.from(parsedBytes).toString('utf8'));expect(parsed.result.cells.find(cell=>cell.field==='version_no')).toMatchObject({value:'9',sourceType:'n'});expect(parsed.result.nativeRows?.[0]?.['version_no']).toBe(9);}finally{parsedBytes.fill(0);}await f.owner.verify('reviewer',f.verification(stored,result.input!));const preview=await f.owner.preview('maker',{inputId:result.input!.inputId});expect(preview.issues,JSON.stringify(preview.issues)).toEqual([]);expect(preview.decision,JSON.stringify(preview.issues)).toBe('PASS');const requestId=randomUUID(),q=await f.owner.plan('maker',{inputId:result.input!.inputId,requestId});await f.owner.readApplyCandidate('reviewer',{candidateId:q.candidateId});await f.owner.approveApplyUnit('reviewer',q);const out=await f.owner.applyUnit('maker',{candidateId:q.candidateId,requestId});if(out.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');expect((await f.owner.exact('maker',{id:out.facts[0]!.id,version:'1'})).facts.source.sourceVersion).toBe('9');
});

test('CSV physical source rows survive a multiline description and column reordering',async()=>{
 const a=await f.endpoint(),b=await f.endpoint('ORG',{campus:a.campus,location:a.location}),first=await f.entry(a),second=await f.entry(b);first.row.sharing_description='first\r\nsecond';const bytes=locationUseFile([first.row,second.row],'CSV',[...ORG13_FIELDS].reverse()),received=await f.owner.receiveFile('maker',locationUseFileRequest(f,[first,second],'CSV'),bytes);expect(received.issues).toEqual([]);const stored=await f.owner.readInput('maker',{inputId:received.input!.inputId});expect(stored.sourceRows).toEqual([2,4]);expect(stored.entries[0]!.row.sharing_description).toBe('first\r\nsecond');await f.owner.verify('reviewer',f.verification(stored,received.input!));const preview=await f.owner.preview('maker',{inputId:received.input!.inputId});expect(preview.issues,JSON.stringify(preview.issues)).toEqual([]);expect(preview.decision,JSON.stringify(preview.issues)).toBe('PASS');const requestId=randomUUID(),q=await f.owner.plan('maker',{inputId:received.input!.inputId,requestId});await f.owner.readApplyCandidate('reviewer',{candidateId:q.candidateId});await f.owner.approveApplyUnit('reviewer',q);const out=await f.owner.applyUnit('maker',{candidateId:q.candidateId,requestId});if(out.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');expect(out.facts.map(fact=>fact.source?.row)).toEqual([2,4]);
});

test.each(['MACRO','FORMULA','HIDDEN','EXTERNAL'] as const)('actual XLSX %s barrier retains rejected evidence and publishes no location use',async barrier=>{
 const a=await f.endpoint(),entry=await f.entry(a),bytes=workbookBarrier(locationUseFile([entry.row],'XLSX'),barrier),received=await createLocationUseClient(url,'maker').file({input:locationUseFileRequest(f,[entry],'XLSX'),contentBase64:bytes.toString('base64')});expect(received.response.status).toBe(200);expect(received.data).toMatchObject({structuralStatus:'REJECTED',input:null});expect(received.data!.issues).toContainEqual(expect.objectContaining({code:barrier==='HIDDEN'?'HIDDEN_UNDECLARED':'ACTIVE_CONTENT'}));const raw=await sensitive(received.data!.sourceArtifactId);try{expect(Buffer.from(raw)).toEqual(bytes);}finally{raw.fill(0);}expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(0);
});

test('actual JSON duplicate and escaped duplicate keys and extra columns cannot become last-write-wins input',async()=>{
 const a=await f.endpoint(),entry=await f.entry(a),text=JSON.stringify([entry.row]),sources=[text.replace('"version_no":9','"version_no":8,"version_no":9'),text.replace('"version_no":9','"version_no":8,"version_\\u006eo":9'),text.replace('"version_no":9','"version_no":9,"extra_column":"TEST forbidden"')];for(const [index,source] of sources.entries()){const received=await createLocationUseClient(url,'maker').file({input:locationUseFileRequest(f,[entry],'JSON'),contentBase64:Buffer.from(source).toString('base64')});expect(received.response.status).toBe(200);expect(received.data!.input).toBeNull();expect(received.data!.issues).toContainEqual(expect.objectContaining({code:index<2?'DUPLICATE_FIELD':'FIELD_CONTRACT'}));}expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(0);
});

test.each(['CSV','JSON','XLSX'] as const)('actual %s one bad row blocks the whole intake and preserves source evidence',async format=>{
 const a=await f.endpoint(),b=await f.endpoint('ORG',{campus:a.campus,location:a.location}),first=await f.entry(a),second=await f.entry(b);second.row.source_record_id=' leading-space';const bytes=locationUseFile([first.row,second.row],format),received=await f.owner.receiveFile('maker',locationUseFileRequest(f,[first,second],format),bytes);expect(received.input).toBeNull();expect(received.issues).toContainEqual(expect.objectContaining({code:'WHITESPACE_REJECTED',row:format==='JSON'?2:3}));const raw=await sensitive(received.sourceArtifactId);try{expect(Buffer.from(raw)).toEqual(bytes);}finally{raw.fill(0);}expect((await f.owner.list('maker',{campus:'NORTH',locationId:a.location.id})).items).toHaveLength(0);
});

test.each(['CSV','JSON','XLSX'] as const)('actual %s repeated source aliases cannot publish a partial reviewed unit',async format=>{
 const a=await f.endpoint(),b=await f.endpoint('ORG',{campus:a.campus,location:a.location}),first=await f.entry(a),second=await f.entry(b);second.row.object_location_rel_id=first.row.object_location_rel_id;const received=await f.owner.receiveFile('maker',locationUseFileRequest(f,[first,second],format),locationUseFile([first.row,second.row],format));expect(received.input).not.toBeNull();const value=await f.owner.readInput('maker',{inputId:received.input!.inputId});await f.owner.verify('reviewer',f.verification(value,received.input!));expect((await f.owner.preview('maker',{inputId:received.input!.inputId})).issues).toContainEqual(expect.objectContaining({code:'BATCH_CONFLICT'}));await expect(f.owner.plan('maker',{inputId:received.input!.inputId,requestId:randomUUID()})).rejects.toThrow('BATCH_CONFLICT');expect((await f.owner.list('maker',{campus:'NORTH',locationId:a.location.id})).items).toHaveLength(0);
});

test('FULL remains blocked and never falls back to the CORE contract',async()=>{
 const a=await f.endpoint(),value=await f.input([await f.entry(a)]),full={...value,profile:'FULL' as const},staged=await f.owner.stage('maker',full);await f.owner.verify('reviewer',f.verification(full,staged));expect((await f.owner.preview('maker',{inputId:staged.inputId})).issues).toContainEqual(expect.objectContaining({field:'profile',code:'BLOCKED_DEPENDENCY',status:'BLOCKED'}));await expect(f.owner.plan('maker',{inputId:staged.inputId,requestId:randomUUID()})).rejects.toThrow('BLOCKED_DEPENDENCY');expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(0);
});

test('actual JSON source+08 uses only the published conversion rule and preserves raw time lexemes',async()=>{
 const a=await f.endpoint(),entry=await f.entry(a);entry.row={...entry.row,valid_from:'2026-01-01T00:00:00.000001+08:00',recorded_at:'2026-01-02T00:00:00.120+08:00'};const request={...locationUseFileRequest(f,[entry],'JSON'),timePolicy:'SOURCE_PLUS08_TO_LOCAL' as const},bytes=locationUseFile([entry.row],'JSON'),client=createLocationUseClient(url,'maker'),received=await client.file({input:request,contentBase64:bytes.toString('base64')});expect(received.response.status,JSON.stringify(received.error)).toBe(200);expect(received.data?.issues).toEqual([]);const result=received.data!,stored=await f.owner.readInput('maker',{inputId:result.input!.inputId});expect(stored.entries[0]!.row).toEqual(entry.row);expect(f.contract!.definition.rules).toContainEqual(expect.objectContaining({id:'LOCATION_USE_SOURCE_PLUS08_V1',status:'MACHINE'}));const verification=f.verification(stored,result.input!);verification.rows=verification.rows.map(row=>({...row,validFrom:'2026-01-01T00:00:00.000001'}));await f.owner.verify('reviewer',verification);const preview=await f.owner.preview('maker',{inputId:result.input!.inputId});expect(preview.issues,JSON.stringify(preview.issues)).toEqual([]);expect(preview.decision,JSON.stringify(preview.issues)).toBe('PASS');const requestId=randomUUID(),q=await f.owner.plan('maker',{inputId:result.input!.inputId,requestId});await f.owner.readApplyCandidate('reviewer',{candidateId:q.candidateId});await f.owner.approveApplyUnit('reviewer',q);const out=await f.owner.applyUnit('maker',{candidateId:q.candidateId,requestId});if(out.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');expect(await f.owner.exact('maker',{id:out.facts[0]!.id,version:'1'})).toMatchObject({validFrom:'2026-01-01T00:00:00.000001',facts:{source:{sourceRecordedAt:'2026-01-02T00:00:00.120000'}}});const raw=await sensitive(result.sourceArtifactId);try{expect(Buffer.from(raw)).toEqual(bytes);}finally{raw.fill(0);}
});

test('actual JSON source+09 is rejected rather than shifted or interpreted as local',async()=>{
 const a=await f.endpoint(),entry=await f.entry(a);entry.row.valid_from='2026-01-01T00:00:00+09:00';entry.row.recorded_at='2026-01-02T00:00:00+09:00';const bytes=locationUseFile([entry.row],'JSON'),received=await f.owner.receiveFile('maker',{...locationUseFileRequest(f,[entry],'JSON'),timePolicy:'SOURCE_PLUS08_TO_LOCAL'},bytes);expect(received.input).toBeNull();expect(received.issues).toContainEqual(expect.objectContaining({code:'LOCAL_TIME_REQUIRED'}));const raw=await sensitive(received.sourceArtifactId);try{expect(Buffer.from(raw)).toEqual(bytes);}finally{raw.fill(0);}expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(0);
});

test('actual JSON string version cannot borrow the CSV/XLSX native-number conversion',async()=>{
 const a=await f.endpoint(),entry=await f.entry(a);entry.row.version_no='9';const received=await f.owner.receiveFile('maker',locationUseFileRequest(f,[entry],'JSON'),locationUseFile([entry.row],'JSON'));expect(received.input).toBeNull();expect(received.issues).toContainEqual(expect.objectContaining({field:'version_no',code:'NATIVE_INTEGER_REQUIRED'}));expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(0);
});

test.each(['1.0','1e0'])('actual generated JSON raw integer token %s publishes native1 while retaining the original numeric spelling',async lexeme=>{
 const a=await f.endpoint(),entry=await f.entry(a);entry.row.version_no=1;const bytes=Buffer.from(locationUseFile([entry.row],'JSON').toString('utf8').replace('"version_no":1','"version_no":'+lexeme)),maker=createLocationUseClient(url,'maker'),reviewer=createLocationUseClient(url,'reviewer'),received=await maker.file({input:locationUseFileRequest(f,[entry],'JSON'),contentBase64:bytes.toString('base64')});
 expect(received.response.status,JSON.stringify(received.error)).toBe(200);const result=received.data!;expect(result.issues,JSON.stringify(result.issues)).toEqual([]);expect(result.input).not.toBeNull();const stored=(await maker.readInput({inputId:result.input!.inputId})).data!;expect(stored.entries[0]!.row.version_no).toBe(1);const raw=await sensitive(result.sourceArtifactId);try{expect(Buffer.from(raw)).toEqual(bytes);}finally{raw.fill(0);}
 const parseBytes=await sensitive(result.validation.run.parseArtifactId);try{const parsed:{result:ParserResult;conversions:Array<{field:string}>}=JSON.parse(Buffer.from(parseBytes).toString('utf8'));expect(parsed.result.cells.find(cell=>cell.field==='version_no')).toMatchObject({value:lexeme,sourceType:'JSON'});expect(parsed.result.nativeRows?.[0]?.['version_no']).toBe(1);expect(parsed.conversions).toEqual([]);}finally{parseBytes.fill(0);}
 expect((await reviewer.verify(f.verification(stored,result.input!))).response.status).toBe(200);const preview=await maker.preview({inputId:result.input!.inputId});expect(preview.data?.issues,JSON.stringify(preview.data?.issues??preview.error)).toEqual([]);expect(preview.data?.decision).toBe('PASS');const requestId=randomUUID(),planned=await maker.plan({inputId:result.input!.inputId,requestId});expect(planned.response.status,JSON.stringify(planned.error)).toBe(200);expect((await reviewer.review({candidateId:planned.data!.candidateId})).response.status).toBe(200);expect((await reviewer.approve(planned.data!)).response.status).toBe(200);const applied=await maker.apply({candidateId:planned.data!.candidateId,requestId});expect(applied.response.status,JSON.stringify(applied.error)).toBe(200);if(applied.data?.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');const exact=await maker.exact({id:applied.data.facts[0]!.id,version:'1'});expect(exact.response.status,JSON.stringify(exact.error)).toBe(200);expect(exact.data?.facts.source.sourceVersion).toBe('1');
});

test('actual JSON fractional token rounded by JavaScript retains its precision and cannot publish an integer version',async()=>{
 const a=await f.endpoint(),entry=await f.entry(a);entry.row.version_no=1;const lexeme='1.00000000000000001',bytes=Buffer.from(locationUseFile([entry.row],'JSON').toString('utf8').replace('"version_no":1','"version_no":'+lexeme)),received=await createLocationUseClient(url,'maker').file({input:locationUseFileRequest(f,[entry],'JSON'),contentBase64:bytes.toString('base64')});
 expect(received.response.status,JSON.stringify(received.error)).toBe(200);const result=received.data!;expect(result).toMatchObject({structuralStatus:'PARSED',input:null});expect(result.issues).toContainEqual(expect.objectContaining({field:'version_no',status:'FAIL'}));expect(result.validation.evaluation.decision).toBe('FAIL');const raw=await sensitive(result.sourceArtifactId);try{expect(Buffer.from(raw)).toEqual(bytes);}finally{raw.fill(0);}
 const parseBytes=await sensitive(result.validation.run.parseArtifactId);try{const parsed:{result:ParserResult}=JSON.parse(Buffer.from(parseBytes).toString('utf8'));expect(parsed.result.cells.find(cell=>cell.field==='version_no')).toMatchObject({value:lexeme,sourceType:'JSON'});expect(parsed.result.nativeRows?.[0]?.['version_no']).not.toBe(1);}finally{parseBytes.fill(0);}expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(0);
});

test('actual HTTP closed anchors and scalar types reject unsupported owners, numeric strings, unknown fields and duplicate keys',async()=>{
 const a=await f.endpoint(),value=await f.input([await f.entry(a)]),entry=value.entries[0]!;const invalid=[{...entry,applicability:{...entry.applicability,target:{...entry.applicability.target,owner:'organization-master'}}},{...entry,row:{...entry.row,version_no:'9'}},{...entry,row:{...entry.row,valid_to:0}},{...entry,roster:[]},{...entry,applicability:{...entry.applicability,targetType:'TEAM'}}];for(const candidate of invalid){const response=await fetch(url+'/api/vnext/location-uses/inputs',{method:'POST',headers:{'content-type':'application/json','x-catalog-actor':'maker'},body:JSON.stringify({...value,requestId:randomUUID(),entries:[candidate]})});expect(response.status).toBe(400);expect(await response.json()).toMatchObject({code:'CLOSED_INPUT_REQUIRED'});}const duplicated=JSON.stringify(value).replace('"version_no":9','"version_no":8,"version_no":9'),response=await fetch(url+'/api/vnext/location-uses/inputs',{method:'POST',headers:{'content-type':'application/json','x-catalog-actor':'maker'},body:duplicated});expect(response.status).toBe(400);expect(await response.json()).toMatchObject({code:'CLOSED_INPUT_REQUIRED'});expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(0);
});

test.each(['1.00000000000000001','100000000000000001e-17'])('raw HTTP native version precision rejects noninteger token %s before staging or publication',async token=>{
 const a=await f.endpoint(),input=await f.input([await f.entry(a)]),serialized=JSON.stringify(f.nativeInput(input));expect(serialized).toContain('"version_no":9');
 const response=await fetch(url+'/api/vnext/location-uses/inputs',{method:'POST',headers:{'content-type':'application/json','x-catalog-actor':'maker'},body:serialized.replace('"version_no":9','"version_no":'+token)});
 let acceptedStoredVersion:unknown='NOT_STAGED';if(response.status===200){const staged:{inputId:string}=await response.json(),read=await createLocationUseClient(url,'maker').readInput({inputId:staged.inputId});acceptedStoredVersion=read.data?.entries[0]?.row.version_no??'UNAVAILABLE';}else{await response.arrayBuffer();}
 expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(0);
 // Only the accepted native scalar is exposed when this wire lexical guard fails.
 expect(response.status,JSON.stringify({acceptedStoredVersion})).toBe(400);
});

test.each(['1.0','1e0'])('raw HTTP native version precision accepts exact integer token %s as native1',async token=>{
 const a=await f.endpoint(),input=await f.input([await f.entry(a)]),serialized=JSON.stringify(f.nativeInput(input));expect(serialized).toContain('"version_no":9');
 const response=await fetch(url+'/api/vnext/location-uses/inputs',{method:'POST',headers:{'content-type':'application/json','x-catalog-actor':'maker'},body:serialized.replace('"version_no":9','"version_no":'+token)}),staged:{inputId?:string;code?:string}=await response.json();expect(response.status,staged.code).toBe(200);expect(staged.inputId).toBeDefined();const read=await createLocationUseClient(url,'maker').readInput({inputId:staged.inputId!});expect(read.response.status,read.error?.code).toBe(200);expect(read.data?.entries[0]?.row.version_no).toBe(1);expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(0);
});

test('generated client receives actual413 and a101-command unit cannot be staged',async()=>{
 const a=await f.endpoint(),entry=await f.entry(a),value=await f.input([entry]);await expect(f.owner.stage('maker',{...value,entries:Array.from({length:101},()=>entry)})).rejects.toThrow('CLOSED_INPUT_REQUIRED');const response=await createLocationUseClient(url,'maker').stage(f.nativeInput({...value,entries:[{...entry,reason:'X'.repeat(300001)}]}));expect(response.response.status).toBe(413);expect(response.error?.code).toBe('FST_ERR_CTP_BODY_TOO_LARGE');expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(0);
});

test('SERVICE cannot maintain a purpose or stage a relation despite copied grants',async()=>{
 const a=await f.endpoint(),value=await f.input([await f.entry(a)]),purpose=await f.dictionary.read('maker',{id:a.usageType.id});peer(receipt.name,"UPDATE vnext_control.actor SET principal_kind='SERVICE' WHERE code='maker';");try{expect((await createLocationUseClient(url,'maker').stage(f.nativeInput(value))).response.status).toBe(403);expect((await createLocationUsageTypeClient(url,'maker').command({action:'DISABLE',requestId:randomUUID(),target:purpose.id,expectedHead:purpose.head,reason:'TEST SERVICE cannot maintain'})).response.status).toBe(403);}finally{peer(receipt.name,"UPDATE vnext_control.actor SET principal_kind='HUMAN' WHERE code='maker';");}expect((await f.dictionary.read('maker',{id:purpose.id})).enabled).toBe(true);
});

test('historical and exact queries and durable recovery recheck current READ authority',async()=>{
 const a=await f.endpoint(),q=await f.prepare(await f.input([await f.entry(a)])),out=await f.owner.applyUnit('maker',q);if(out.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');const id=out.facts[0]!.id,client=createLocationUseClient(url,'maker');peer(receipt.name,`DELETE FROM location_master.use_access WHERE actor='maker' AND campus_id=${quote(a.campus.id)}::uuid AND permission='READ';`);try{for(const call of [()=>client.query({id,businessAt:'2026-02-01T00:00:00',recordAsOf:out.recordedAt}),()=>client.exact({id,version:'1'}),()=>client.history({id,recordAsOf:out.recordedAt}),()=>client.resume(q),()=>client.reconcile(q)])expect((await call()).response.status).toBe(403);}finally{f.grant(a.campus.id);}expect((await client.history({id})).data?.versions).toHaveLength(1);const {responseStatus:_ack,...durable}=out;expect((await client.resume(q)).data).toEqual(durable);
});

test('same underlying maker alias cannot independently verify or approve a relation',async()=>{
 const a=await f.endpoint(),value=await f.input([await f.entry(a)]),staged=await f.owner.stage('maker',value);peer(receipt.name,`INSERT INTO location_master.use_access SELECT 'maker-alias',${quote(a.campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;`);try{await expect(f.owner.verify('maker-alias',f.verification(value,staged))).rejects.toThrow('MAKER_CHECKER_REQUIRED');const q=await f.prepare(value),candidate=await f.owner.readApplyCandidate('maker-alias',{candidateId:q.candidateId});await expect(f.owner.approveApplyUnit('maker-alias',{candidateId:candidate.candidateId,digest:candidate.digest})).rejects.toThrow('MAKER_CHECKER_REQUIRED');expect(await f.owner.resumeOutcome('maker',q)).toBeNull();}finally{peer(receipt.name,`DELETE FROM location_master.use_access WHERE actor='maker-alias' AND campus_id=${quote(a.campus.id)}::uuid AND permission IN ('VERIFY','REVIEW');`);}
});

test('a semantically equal new verification invalidates the exact frozen pin in Owner and restricted SQL',async()=>{
 const a=await f.endpoint(),value=await f.input([await f.entry(a)]),q=await f.prepare(value),candidate=await f.owner.readApplyCandidate('reviewer',{candidateId:q.candidateId}),staged=await f.owner.stage('maker',value);await f.owner.verify('reviewer',f.verification(value,staged));await expect(f.owner.applyUnit('maker',q)).rejects.toThrow('STALE_VALIDATION');expect(await signedUseAttempt(connection,receipt,candidate,q)).toBe('STALE_VALIDATION');expect(await f.owner.resumeOutcome('maker',q)).toBeNull();expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(0);
});

test('restricted signed SQL rejects changed writes, write index and frozen digest without publishing facts',async()=>{
 const a=await f.endpoint(),q=await f.prepare(await f.input([await f.entry(a)])),candidate=await f.owner.readApplyCandidate('reviewer',{candidateId:q.candidateId});expect(await signedUseAttempt(connection,receipt,candidate,q)).toBe('AUTHORIZED');
 const changed=await signedUseAttempt(connection,receipt,candidate,q,ticket=>{const writes=structuredClone(ticket['writes']);if(!Array.isArray(writes)||!writes[0]||typeof writes[0]!=='object')throw new Error('TEST_WRITE_SHAPE_REQUIRED');writes[0].reason='tampered approved declaration';return {...ticket,writes};});expect(changed).toBe('STALE_VALIDATION');expect(await signedUseAttempt(connection,receipt,candidate,q,ticket=>({...ticket,writesDigest:'0'.repeat(64)}))).toBe('STALE_VALIDATION');expect(await signedUseAttempt(connection,receipt,candidate,q,ticket=>({...ticket,writeIndex:2}))).toBe('PLAN_INPUT_LIMIT');expect(await f.owner.resumeOutcome('maker',q)).toBeNull();expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(0);expect((await f.owner.applyUnit('maker',q)).status).toBe('COMMITTED');
});

test.each([['maker','WRITE'],['maker','READ_RESTRICTED'],['reviewer','VERIFY'],['reviewer','READ_RESTRICTED']] as const)('restricted signed SQL and Owner recheck current %s %s after freeze',async(identity,permission)=>{
 const a=await f.endpoint(),q=await f.prepare(await f.input([await f.entry(a)])),candidate=await f.owner.readApplyCandidate('reviewer',{candidateId:q.candidateId});expect(await signedUseAttempt(connection,receipt,candidate,q)).toBe('AUTHORIZED');
 peer(receipt.name,`DELETE FROM location_master.use_access WHERE actor=${quote(identity)} AND campus_id=${quote(a.campus.id)}::uuid AND permission=${quote(permission)};`);
 try{expect(await signedUseAttempt(connection,receipt,candidate,q)).toBe('ACCESS_DENIED');await expect(f.owner.applyUnit('maker',q)).rejects.toThrow('ACCESS_DENIED');}
 finally{f.grant(a.campus.id);}
 expect(await signedUseAttempt(connection,receipt,candidate,q)).toBe('AUTHORIZED');expect(await f.owner.resumeOutcome('maker',q)).toBeNull();expect((await f.owner.list('maker',{campus:'NORTH',targetId:a.target.id})).items).toHaveLength(0);
});
