import {wardUpstreamPorts} from '../../apps/governance-api/src/composition/ward-dependencies.js';
import {conditionMappings} from '../../apps/governance-api/src/modules/governance-catalog/validation-sources.generated.js';
import {randomUUID} from 'node:crypto';
import type {Catalog,KeyProviderPort} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {openWard,type WardBindingInput,type WardStage,type WardEntry,type WardVerification,type WardRow} from '../../apps/governance-api/src/modules/care-organization/index.js';
import {businessUnitFixture} from './p3-01-fixture.js';
import {provisionWard} from './p3-02-provisioning.mjs';
import {peer,quote} from './lineage.mjs';
import {openDepartmentLifecycle} from '../../apps/governance-api/src/modules/department-master/index.js';
import {withCareOrganizationImpacts} from '../../apps/governance-api/src/composition/nursing-unit-dependencies.js';

export async function wardFixture(receipt:{name:string;oid:string},role:string,catalog:Catalog,provider:KeyProviderPort,connection:string,persistent=false){
 const base=await businessUnitFixture(receipt,role,catalog,provider,connection,persistent);
 const cmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'TEST_WARD',...extra});
 let dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.kind==='DATASET'&&i.code==='ORG08'&&i.status==='PUBLISHED');
 if(!dataset){const d=await catalog.command('maker',cmd('CREATE',{kind:'DATASET',code:'ORG08',values:{name:'TEST POLICY ONLY 病区'},validFrom:'2026-01-01T00:00:00'})),s=await catalog.command('maker',cmd('SUBMIT',{target:d.id,expectedHead:d.head}));await catalog.command('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:s.head,reviewDigest:s.reviewDigest}));dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.id===d.id)!;}
 const fields=dataset.payload.fields!.map(f=>f.original),codes=['DRAFT','REVIEW','ACTIVE','SUSPENDED','RETIRED'];
 const definition={ruleVersion:'ORG08_CORE_V1',templateVersion:'ORG08_CORE_V1',sourceVersionId:base.dep.source.versionId,businessKey:['ward_id'],fields:fields.map(f=>({code:f.code,type:f.type,required:f.required,privacy:f.privacy,condition:f.required==='C'?'EVALUATED':f.required==='R'?'ALWAYS':'OPTIONAL',enumValues:f.code==='record_status'?codes:[]})),references:fields.filter(f=>f.ref).map(f=>({field:f.code,target:f.ref,status:'WARD_CORE'})),rules:[{id:'WARD_SOURCE_PLUS08_V1',field:'valid_from',text:'Explicit source +08:00 to Asia/Shanghai local; retain original timestamps.',status:'MACHINE',version:'P3_02_TIME_V1'},...conditionMappings.filter(r=>r.dataset==='ORG08').map(r=>({id:r.id,field:r.field,text:r.text,status:'MACHINE',version:r.version})),{id:'WARD_APPROVAL_V1',field:'approval_ref',text:'Source approval never replaces platform approval.',status:'MACHINE',version:'P3_02_V1'}],codeSets:[{field:'record_status',codes,codeSystem:'SYNTHETIC_RECORD_STATUS',version:'TEST_POLICY_ONLY_1',status:'SYNTHETIC_ADOPTED',sourceVersionId:base.dep.source.versionId,validFrom:'2026-01-01T00:00:00',validTo:null}]};
 let contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG08'&&c.profile==='CORE'&&c.status==='PUBLISHED');
 if(!contract||contract.definition.templateVersion!=='ORG08_CORE_V1'){const d=await catalog.contractCommand('maker',contract?cmd('REVISE',{target:contract.id,expectedHead:contract.head,datasetVersionId:dataset.versionId,definition,validFrom:'2026-01-01T00:00:00',validTo:null}):cmd('CREATE',{datasetVersionId:dataset.versionId,profile:'CORE',definition,validFrom:'2026-01-01T00:00:00',validTo:null})),a=await catalog.contractCommand('reviewer',cmd('APPROVE',{target:d.id,expectedHead:d.head,reviewDigest:d.reviewDigest})),impact=contract?await catalog.contractImpact('reviewer','SYNTHETIC',d.id,'PUBLISH'):undefined;await catalog.contractCommand('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:a.head,reviewDigest:a.reviewDigest,...(impact?{impactDigest:impact.impactDigest}:{})}));contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.id===d.id)!;}
 const newJob=()=>catalog.importJobCommand('maker',cmd('CREATE',{profile:'CORE',contractId:contract!.id,contractVersionId:contract!.versionId,input:{kind:'METADATA_ONLY',declaredSha256:'a'.repeat(64)}}));
 peer(receipt.name,`INSERT INTO vnext_control.protected_grant SELECT a,${quote(dataset.id)}::uuid,s,'IDENTITY_VERIFY',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['NORTH','SOUTH']) s CROSS JOIN unnest(ARRAY['READ','STORE']) p ON CONFLICT DO NOTHING;`);
 const j=await newJob(),artifact=await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds:7200},Buffer.from('TEST POLICY ONLY independently verified Ward organization'));
 provisionWard(receipt,role,provider);const owner=openWard(connection,provider,wardUpstreamPorts(base.owner)),lifecycle=openDepartmentLifecycle(connection,provider,withCareOrganizationImpacts(()=>base.owner,()=>undefined,()=>owner));
 const grant=(campusId:string)=>peer(receipt.name,`INSERT INTO care_organization.ward_access SELECT a,${quote(campusId)}::uuid,'NORTH',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED']) p ON CONFLICT DO NOTHING;INSERT INTO care_organization.ward_access SELECT 'reviewer',${quote(campusId)}::uuid,'NORTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;`);
 const endpoint=async(suppliedDepartmentId?:string):Promise<WardBindingInput>=>{const departmentId=suppliedDepartmentId??await base.newDepartment(),binding=await base.endpoint(departmentId),outcome=await base.apply(await base.input([base.entry(binding)]));grant(binding.campus.id);return {unit:{owner:'care-organization/unit',id:outcome.facts[0]!.id},campus:binding.campus};};
 const sameCampus=async(b:WardBindingInput):Promise<WardBindingInput>=>{const h=await base.owner.history('maker',{id:b.unit.id}),binding=h.bindings[0]!.versions.at(-1)!.binding,outcome=await base.apply(await base.input([base.entry(binding)]));return {unit:{owner:'care-organization/unit',id:outcome.facts[0]!.id},campus:b.campus};};
 const row=(b:WardBindingInput):WardRow=>({ward_id:randomUUID(),ward_code:'TEST_'+randomUUID(),ward_name:'TEST 同名病区',campus_id:b.campus.id,managing_unit_id:b.unit.id,ward_type:'TEST 普通病区',admission_rule_ref:null,public_phone:null,version_no:'9',valid_from:'2026-01-01T00:00:00',valid_to:'',record_status:'ACTIVE',source_system_id:base.dep.source.id,source_record_id:'TEST/ORG08/2',approval_ref:'TEST_POLICY_ONLY',recorded_at:'2026-01-02T00:00:00'});
 const entry=(b:WardBindingInput):WardEntry=>({action:'CREATE',binding:b,row:row(b),reason:'TEST ward creation',evidenceId:artifact.artifactId});
 const input=async(entries:WardEntry[]):Promise<WardStage>=>{const j=await newJob();return {requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',profile:'CORE',timePolicy:'LOCAL',entries};};
 const verification=(v:WardStage,i:{inputId:string;digest:string}):WardVerification=>({requestId:randomUUID(),inputId:i.inputId,inputDigest:i.digest,reason:'TEST independent ward classification',policyVersion:'ORG08_CORE_V1',rows:v.entries.map((_,index)=>({row:index+1,evidenceId:artifact.artifactId,classificationAccepted:true,managementAccepted:true,receiving:{kind:'NO_SPECIAL_RESTRICTION',confirmed:true,validFrom:v.entries[index]!.row.valid_from,validTo:v.entries[index]!.row.valid_to||null}}))});
 const prepare=async(v:WardStage)=>{const i=await owner.stage('maker',v);await owner.verify('reviewer',verification(v,i));const preview=await owner.preview('maker',{inputId:i.inputId});if(preview.decision!=='PASS')throw new Error(preview.issues.map(i=>i.code).join(','));const requestId=randomUUID(),c=await owner.plan('maker',{inputId:i.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:c.candidateId});await owner.approveApplyUnit('reviewer',c);return {candidateId:c.candidateId,requestId};};
 const apply=async(v:WardStage)=>{const result=await owner.applyUnit('maker',await prepare(v));if(result.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');return result;};
 return {base,dep:base.dep,lifecycle:lifecycle as ReturnType<typeof openDepartmentLifecycle>,impacts:base.impacts,impactReviews:base.impactReviews,newDepartment:base.newDepartment,owner,contract,dataset,artifact,newJob,endpoint,sameCampus,grant,row,entry,input,verification,prepare,apply,close:async()=>{await lifecycle.close();await owner.close();await base.close();}};
}
