import {openParameterValues} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {randomUUID} from 'node:crypto';
import {openWardNursingCoverage,ORG11_FIELDS,type WardNursingEntry,type WardNursingRow,type WardNursingStage,type WardNursingVerification,type WardNursingScope,type WardNursingRule,type CoverageScope,type ApprovedScopeSet} from '../../apps/governance-api/src/modules/care-organization/index.js';
import type {Catalog,KeyProviderPort} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {wardNursingUpstreamPorts} from '../../apps/governance-api/src/composition/ward-nursing-dependencies.js';
import {conditionMappings} from '../../apps/governance-api/src/modules/governance-catalog/validation-sources.generated.js';
import {nursingFixture} from './p3-03-fixture.js';
import {wardFixture} from './p3-02-fixture.js';
import {provisionWardNursing} from './p3-05-provisioning.mjs';
import {peer,quote} from './lineage.mjs';
export async function wardNursingFixture(receipt:{name:string;oid:string},role:string,catalog:Catalog,provider:KeyProviderPort,connection:string,persistent=false,supplied?:Awaited<ReturnType<typeof wardFixture>>,sourceOverride?:{id:string;versionId:string}){
 const published=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG04'&&c.profile==='CORE'&&c.status==='PUBLISHED');
 persistent=!!published&&(await catalog.read('maker',{scope:'SYNTHETIC'})).items.some(i=>i.kind==='SOURCE'&&i.status==='PUBLISHED'&&i.versionId===published.definition.sourceVersionId);
 const nursing=await nursingFixture(receipt,role,catalog,provider,connection,persistent);const wards=supplied??await wardFixture(receipt,role,catalog,provider,connection,true),base=wards.base,source=sourceOverride??base.dep.source,cmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'TEST_WARD_NURSING',...extra});
 let dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.kind==='DATASET'&&i.code==='ORG11'&&i.status==='PUBLISHED');
 if(!dataset){const d=await catalog.command('maker',cmd('CREATE',{kind:'DATASET',code:'ORG11',values:{name:'TEST POLICY ONLY 科室病区关系'},validFrom:'2026-01-01T00:00:00'})),s=await catalog.command('maker',cmd('SUBMIT',{target:d.id,expectedHead:d.head}));await catalog.command('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:s.head,reviewDigest:s.reviewDigest}));dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.id===d.id)!;}
 const fields=dataset.payload.fields!.map(f=>f.original);if(fields.length!==ORG11_FIELDS.length)throw new Error('FULL_FIELD_OMISSION');
 const enums:Record<string,string[]>={is_primary:['Y','N'],record_status:['DRAFT','REVIEW','ACTIVE','SUSPENDED','RETIRED']};
 const definition={ruleVersion:'ORG11_CORE_SRC_'+source.versionId.replaceAll('-','').toUpperCase()+'_'+randomUUID().slice(0,8).toUpperCase(),templateVersion:'ORG11_CORE_V1',sourceVersionId:source.versionId,businessKey:['ward_nursing_rel_id'],fields:fields.map(f=>({code:f.code,type:f.type,required:f.required,privacy:f.privacy,condition:f.required==='C'?'EVALUATED':f.required==='R'?'ALWAYS':'OPTIONAL',enumValues:enums[f.code]??[]})),references:fields.filter(f=>f.ref).map(f=>({field:f.code,target:f.ref,status:'WARD_NURSING_CORE'})),rules:[{id:'WARD_NURSING_EMPTY_END_V1',field:'valid_to',text:'CSV/XLSX blank valid_to is an explicit open end; JSON requires native null.',status:'MACHINE',version:'P3_05_EMPTY_END_V1'},{id:'WARD_NURSING_APPROVAL_V1',field:'approval_ref',text:'Source approval never replaces platform approval.',status:'MACHINE',version:'P3_05_V1'}],codeSets:Object.entries(enums).map(([field,codes])=>({field,codes,codeSystem:'SYNTHETIC_'+field.toUpperCase(),version:'TEST_POLICY_ONLY_1',status:'SYNTHETIC_ADOPTED',sourceVersionId:source.versionId,validFrom:'2026-01-01T00:00:00',validTo:null}))};
 let contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG11'&&c.profile==='CORE'&&c.status==='PUBLISHED');
 if(!contract||contract.definition.templateVersion!=='ORG11_CORE_V1'||contract.definition.sourceVersionId!==source.versionId){const d=await catalog.contractCommand('maker',contract?cmd('REVISE',{target:contract.id,expectedHead:contract.head,datasetVersionId:dataset.versionId,definition,validFrom:'2026-01-01T00:00:00',validTo:null}):cmd('CREATE',{datasetVersionId:dataset.versionId,profile:'CORE',definition,validFrom:'2026-01-01T00:00:00',validTo:null})),preImpact=contract?await catalog.contractImpact('reviewer','SYNTHETIC',d.id,'PUBLISH'):undefined,a=await catalog.contractCommand('reviewer',cmd('APPROVE',{target:d.id,expectedHead:d.head,reviewDigest:d.reviewDigest,...(preImpact?{impactDigest:preImpact.impactDigest}:{})})),impact=contract?await catalog.contractImpact('reviewer','SYNTHETIC',d.id,'PUBLISH'):undefined;await catalog.contractCommand('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:a.head,reviewDigest:a.reviewDigest,...(impact?{impactDigest:impact.impactDigest}:{})}));contract=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.id===d.id)!;}
 const newJob=()=>catalog.importJobCommand('maker',cmd('CREATE',{profile:'CORE',contractId:contract!.id,contractVersionId:contract!.versionId,input:{kind:'METADATA_ONLY',declaredSha256:'a'.repeat(64)}}));
 peer(receipt.name,`INSERT INTO vnext_control.protected_grant SELECT a,${quote(dataset.id)}::uuid,s,'IDENTITY_VERIFY',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['NORTH','SOUTH']) s CROSS JOIN unnest(ARRAY['READ','STORE']) p ON CONFLICT DO NOTHING;`);
 const j=await newJob(),artifact=await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds:7200},Buffer.from('TEST POLICY ONLY independently reviewed Unit Ward sharing boundaries'));
 provisionWardNursing(receipt,role,provider);const sources=openParameterValues(connection),owner=openWardNursingCoverage(connection,provider,wardNursingUpstreamPorts(wards.owner,nursing.owner,base.owner,sources));
 const grant=(s:WardNursingScope)=>peer(receipt.name,`INSERT INTO care_organization.ward_nursing_access SELECT a,${quote(s.campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED']) p ON CONFLICT DO NOTHING;INSERT INTO care_organization.ward_nursing_access SELECT 'reviewer',${quote(s.campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;`);
 const newNursing=async(campus:{owner:'organization-master/campus';id:string})=>{const binding={department:{owner:'department-master' as const,id:await nursing.newDepartment()},campus};peer(receipt.name,`INSERT INTO care_organization.nursing_access SELECT a,${quote(campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED']) p ON CONFLICT DO NOTHING;INSERT INTO care_organization.nursing_access SELECT 'reviewer',${quote(campus.id)}::uuid,'NORTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;`);const out=await nursing.apply(await nursing.input([nursing.entry(binding)]));return {owner:'care-organization/nursing' as const,id:out.facts[0]!.id};};
 const endpoint=async():Promise<WardNursingScope>=>{const b=await wards.endpoint(),out=await wards.apply(await wards.input([wards.entry(b)])),s:WardNursingScope={nursing:await newNursing(b.campus),ward:{owner:'care-organization/ward',id:out.facts[0]!.id},campus:b.campus,purpose:'NURSING_COVERAGE'};grant(s);return s;};
 const sameWard=async(s:WardNursingScope):Promise<WardNursingScope>=>({...s,nursing:await newNursing(s.campus)});
 const row=(s:WardNursingScope,coverage:CoverageScope={kind:'WHOLE_WARD'}):WardNursingRow=>({ward_nursing_rel_id:randomUUID(),nursing_unit_id:s.nursing.id,ward_id:s.ward.id,coverage_scope:JSON.stringify(coverage),is_primary:'Y',handover_rule_ref:null,version_no:9,valid_from:'2026-01-01T00:00:00',valid_to:null,record_status:'ACTIVE',source_system_id:source.id,source_record_id:'TEST/ORG11/2',approval_ref:'TEST_POLICY_ONLY',recorded_at:'2026-01-02T00:00:00'});
 const entry=(s:WardNursingScope,coverage:CoverageScope={kind:'WHOLE_WARD'}):WardNursingEntry=>({action:'CREATE',applicability:s,coverage,rule:{kind:'NO_SHARING_REQUIRED'},row:row(s,coverage),reason:'TEST independently established nursing coverage',evidenceId:artifact.artifactId});
 const shared=(participants:string[],coverage:CoverageScope={kind:'WHOLE_WARD'}):WardNursingRule=>({kind:'SHARED_BOUNDARY',coverage,ruleReference:'TEST_SHARED_NURSING',ruleVersion:'TEST_POLICY_ONLY_1',evidenceId:artifact.artifactId,participants:[...participants].sort(),validFrom:'2026-01-01T00:00:00',validTo:null});
 const input=async(entries:WardNursingEntry[]):Promise<WardNursingStage>=>{const j=await newJob();return {kind:'COVERAGE',requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',profile:'CORE',timePolicy:'LOCAL',entries};};
 const verification=(v:WardNursingStage,i:{inputId:string;digest:string}):WardNursingVerification=>({requestId:randomUUID(),inputId:i.inputId,inputDigest:i.digest,reason:'TEST independent nursing coverage review',policyVersion:'ORG11_CORE_V1',rows:v.kind==='COVERAGE'?v.entries.map((e,index)=>({row:index+1,evidenceId:artifact.artifactId,classificationAccepted:true,scopeAccepted:true,ruleConfirmed:true,rule:e.rule,coverage:e.coverage,handover:{kind:'NO_HANDOVER_REQUIRED',confirmed:true},validFrom:e.row.valid_from,validTo:e.row.valid_to})):[],...(v.kind==='SCOPE_DEFINITION'?{scopeDefinition:{completeAndDisjoint:true,definitionDigest:i.digest,evidenceId:artifact.artifactId}}:{})});
 const confirmHandover=async(v:WardNursingVerification,actor='reviewer'):Promise<WardNursingVerification>=>{const value=structuredClone(v);for(const row of value.rows)if(row.handover.kind==='CONFIRMED_HANDOVER'&&!row.handover.nursingConfirmation){const handover=row.handover;if(!handover.confirmed)throw new Error('HANDOVER_NOT_CONFIRMED');const result=await nursing.owner.confirmCoverageHandover(actor,{requestId:randomUUID(),inputId:value.inputId,inputDigest:value.inputDigest,row:row.row,handover:{...handover,confirmed:true},reason:'TEST Nursing Owner independently confirms exact responsibility handover'});row.handover={...handover,nursingConfirmation:{id:result.confirmationId,digest:result.digest}};}return value;};
 const prepare=async(v:WardNursingStage,custom?:(v:WardNursingVerification)=>WardNursingVerification)=>{const i=await owner.stage('maker',v);await owner.verify('reviewer',await confirmHandover(custom?custom(verification(v,i)):verification(v,i)));const preview=await owner.preview('maker',{inputId:i.inputId});if(preview.decision!=='PASS')throw new Error(preview.issues.map(i=>i.code).join(','));const requestId=randomUUID(),c=await owner.plan('maker',{inputId:i.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:c.candidateId});await owner.approveApplyUnit('reviewer',c);return {candidateId:c.candidateId,requestId};};
 const apply=async(v:WardNursingStage,custom?:(v:WardNursingVerification)=>WardNursingVerification)=>{const result=await owner.applyUnit('maker',await prepare(v,custom));if(result.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');return result;};
 const scopeInput=async(a:WardNursingScope):Promise<WardNursingStage>=>{const job=await newJob(),stage:WardNursingStage={kind:'SCOPE_DEFINITION',requestId:randomUUID(),jobId:job.id,revisionId:job.revisionId,campus:'NORTH',profile:'CORE',timePolicy:'LOCAL',definition:{sourceAlias:randomUUID(),applicability:{ward:a.ward,campus:a.campus,purpose:a.purpose},partitions:[{sourceAlias:'A',name:'TEST area A',boundary:'TEST independently disjoint A'},{sourceAlias:'B',name:'TEST area B',boundary:'TEST independently disjoint B'}],validFrom:'2026-01-01T00:00:00',validTo:null,sourceSystemId:source.id,sourceRecordedAt:'2026-01-02T00:00:00',approvalReference:'TEST_POLICY_ONLY',evidenceId:artifact.artifactId,reason:'TEST complete logical scope definition'}};return stage;};
 const register=async(a:WardNursingScope):Promise<ApprovedScopeSet>=>{const out=await apply(await scopeInput(a));return owner.readScopeDefinition('maker',{id:out.facts[0]!.id});};
 const partition=(set:ApprovedScopeSet,indices:number[]):CoverageScope=>({kind:'PARTITIONS',scopeSetId:set.id,version:'1',partitionIds:indices.map(i=>set.partitions[i]!.id)});
 return {base,wards,nursing,owner,scopeInput,register,partition,contract,dataset,artifact,endpoint,sameWard,grant,row,entry,shared,input,newJob,verification,confirmHandover,prepare,apply,close:async()=>{await owner.close();await sources.close();await nursing.close();if(!supplied)await wards.close();}};
}
