import {subjectPermissionUpstreamPorts} from '../../apps/governance-api/src/composition/subject-permission-dependencies.js';
import {randomUUID} from 'node:crypto';
import type {Catalog,KeyProviderPort} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {openSubjectCodes} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {openSubjectPermissions,type SubjectScope,type SubjectStage,type SubjectDirectEntry,type SubjectVerification} from '../../apps/governance-api/src/modules/care-organization/index.js';
import type {businessUnitFixture} from './p3-01-fixture.js';
import {subjectPermissionContract} from './p3-09-fixture.js';
import {provisionSubjects} from './p3-09-provisioning.mjs';
import {peer,quote} from './lineage.mjs';
import {conditionMappings} from '../../apps/governance-api/src/modules/governance-catalog/validation-sources.generated.js';

/** Native materials must be bound to the exact SOURCE version they attest. */
export async function subjectSourceEvidence(receipt:{name:string},catalog:Catalog,sourceVersionId:string,validFrom:string){
 const cmd=<A extends string>(action:A,extra:Record<string,unknown>={})=>({action,scope:'SYNTHETIC' as const,requestId:randomUUID(),reason:'TEST_SUBJECT_SOURCE_EVIDENCE',...extra});
 let dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.kind==='DATASET'&&i.code==='ORG22'&&i.status==='PUBLISHED');
 if(!dataset){const d=await catalog.command('maker',cmd('CREATE',{kind:'DATASET',code:'ORG22',values:{name:'TEST POLICY ONLY exact adopted source materials'},validFrom:'2026-01-01T00:00:00'})),s=await catalog.command('maker',cmd('SUBMIT',{target:d.id,expectedHead:d.head}));await catalog.command('reviewer',cmd('PUBLISH',{target:d.id,expectedHead:s.head,reviewDigest:s.reviewDigest}));dataset=(await catalog.read('maker',{scope:'SYNTHETIC'})).items.find(i=>i.id===d.id)!;}
 const fields=dataset.payload.fields!.map(f=>f.original),enums:Record<string,string[]>={target_type:['LEGAL','CAMPUS','ORG','UNIT','WARD','NURSING','TEAM','LOCATION'],mapping_relation:['EXACT','BROADER','NARROWER','RELATED','UNRESOLVED'],record_status:['DRAFT','REVIEW','ACTIVE','SUSPENDED','RETIRED']};
 const definition={templateVersion:'ORG22_CORE_V1',ruleVersion:'ORG22_CORE_SRC_'+sourceVersionId.replaceAll('-','').toUpperCase(),sourceVersionId,businessKey:['org_map_id'],fields:fields.map(f=>({code:f.code,type:f.type,required:f.required,privacy:f.privacy,condition:f.required==='C'?'EVALUATED':f.required==='R'?'ALWAYS':'OPTIONAL',enumValues:enums[f.code]??[]})),rules:[...conditionMappings.filter(r=>r.dataset==='ORG22').map(r=>({id:r.id,field:r.field,text:r.text,status:'MACHINE',version:r.version})),{id:'ORG_MAPPING_APPROVAL_V1',field:'approval_ref',text:'Source approval never replaces platform approval.',status:'MACHINE',version:'P2_03_V1'}],references:fields.filter(f=>f.ref).map(f=>({field:f.code,target:f.ref,status:'ORGANIZATION_MAPPING_CORE'})),codeSets:Object.entries(enums).map(([field,codes])=>({field,codes,codeSystem:'SYNTHETIC_'+field.toUpperCase(),version:'TEST_SOURCE_'+sourceVersionId.replaceAll('-','').toUpperCase(),status:'SYNTHETIC_ADOPTED',sourceVersionId,validFrom,validTo:null}))};
 const previous=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG22'&&c.profile==='CORE'&&c.status==='PUBLISHED'),draft=await catalog.contractCommand('maker',previous?cmd('REVISE',{target:previous.id,expectedHead:previous.head,datasetVersionId:dataset.versionId,definition,validFrom,validTo:null}):cmd('CREATE',{datasetVersionId:dataset.versionId,profile:'CORE',definition,validFrom,validTo:null})),impact=previous?await catalog.contractImpact('reviewer','SYNTHETIC',draft.id,'PUBLISH'):null,approved=await catalog.contractCommand('reviewer',cmd('APPROVE',{target:draft.id,expectedHead:draft.head,reviewDigest:draft.reviewDigest,...(impact?{impactDigest:impact.impactDigest}:{})})),published=await catalog.contractCommand('reviewer',cmd('PUBLISH',{target:approved.id,expectedHead:approved.head,reviewDigest:approved.reviewDigest,...(previous?{impactDigest:(await catalog.contractImpact('reviewer','SYNTHETIC',draft.id,'PUBLISH')).impactDigest}:{})}));
 peer(receipt.name,`INSERT INTO vnext_control.protected_grant SELECT a,${quote(dataset.id)}::uuid,'NORTH','IDENTITY_VERIFY',p FROM unnest(ARRAY['maker','reviewer']) a CROSS JOIN unnest(ARRAY['READ','STORE']) p ON CONFLICT DO NOTHING;`);
 const job=await catalog.importJobCommand('maker',cmd('CREATE',{profile:'CORE',contractId:published.id,contractVersionId:published.versionId,input:{kind:'METADATA_ONLY',declaredSha256:'a'.repeat(64)}}));
 return (await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),jobId:job.id,revisionId:job.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds:7200},Buffer.from('TEST POLICY ONLY exact source version '+sourceVersionId))).artifactId;
}
export async function careSubjectFixture(receipt:{name:string;oid:string},role:string,catalog:Catalog,provider:KeyProviderPort,connection:string,base:Awaited<ReturnType<typeof businessUnitFixture>>){
 provisionSubjects(receipt,role,provider);peer(receipt.name,"INSERT INTO governance_catalog.subject_code_access SELECT a,p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE']) p ON CONFLICT DO NOTHING;INSERT INTO governance_catalog.subject_code_access SELECT 'reviewer',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;");
 const owner=openSubjectPermissions(connection,provider,subjectPermissionUpstreamPorts(base.owner,base.lifecycle,base.operating.operating)),codes=openSubjectCodes(connection,provider),transport=await subjectPermissionContract(catalog,base.dep.source,true);
 const draft=await codes.command('maker',{action:'CREATE',requestId:randomUUID(),reason:'TEST POLICY ONLY bounded adoption',systemCode:'TEST_P3_10_'+randomUUID().slice(0,8).toUpperCase(),sourceId:base.dep.source.id,sourceVersionId:base.dep.source.versionId,evidenceId:base.artifact.artifactId,reference:{owner:'governance-catalog/subject-code',dataset:'REF01',namespace:'REF01.code_system_id',sourceAlias:'TEST_REF01_P3_10_'+randomUUID().slice(0,8)},codeSystemName:'TEST 诊疗科目',namespaceUri:'urn:hdip:test:p3-10',standardDocument:'TEST DOCUMENT 2022',issuer:'TEST POLICY ONLY',codeSystemVersion:'2022版',sourcePage:'TEST page 1',sourceSummary:'TEST POLICY ONLY complete two-code synthetic adoption',adoptedOn:'2026-10-10',label:'TEST_POLICY_ONLY',validFrom:'2026-01-01T00:00:00',validTo:null,codes:[{code:'TEST_A',name:'TEST 科目甲',meaning:'TEST_A_MEANING',status:'ACTIVE',replacement:null},{code:'TEST_B',name:'TEST 科目乙',meaning:'TEST_B_MEANING',status:'ACTIVE',replacement:null}]});
 await codes.command('reviewer',{action:'VERIFY',requestId:randomUUID(),reason:'TEST independent source review',target:draft.id,versionId:draft.versionId,reviewDigest:draft.reviewDigest,evidenceId:base.artifact.artifactId,sourceReviewed:true});
 const adoption=await codes.command('reviewer',{action:'APPROVE',requestId:randomUUID(),reason:'TEST independent source approval',target:draft.id,versionId:draft.versionId,reviewDigest:draft.reviewDigest});
 peer(receipt.name,`INSERT INTO vnext_control.protected_grant SELECT a,${quote(transport.dataset.id)}::uuid,'NORTH','IDENTITY_VERIFY',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','STORE']) p ON CONFLICT DO NOTHING;`);
 const job=await transport.newJob(),artifact=await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),jobId:job.id,revisionId:job.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds:7200},Buffer.from('TEST POLICY ONLY exact diagnostic subject scope and licensed institution'));
 const grant=(scope:SubjectScope,kind:'MAPPING'|'PERMISSION')=>peer(receipt.name,`INSERT INTO care_organization.subject_access SELECT a,${quote(scope.subject.id)}::uuid,${quote(scope.campus.id)}::uuid,${quote(scope.target.type)},${quote(scope.target.id)}::uuid,${quote(kind)},p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED','VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;`);
 const entry=async(scope:SubjectScope,kind:'MAPPING'|'PERMISSION'='PERMISSION'):Promise<SubjectDirectEntry>=>{
  grant(scope,kind);const window=await base.operating.operating.evaluateOperatingWindow('maker',{subject:scope.subject,campus:scope.campus,services:scope.services,validFrom:'2026-01-01T00:00:00',validTo:null});if(window.status!=='SATISFIED')throw new Error('FIXTURE_LICENSE_NOT_READY');
  const common={action:'RECORD' as const,scope,adoption:{owner:'governance-catalog/subject-code' as const,systemId:adoption.id,versionId:adoption.versionId,version:adoption.head,code:'TEST_A'},row:{subject_license_id:randomUUID(),target_type:scope.target.type,target_id:scope.target.id,code_system_id:adoption.reference.sourceAlias,code_system_version:adoption.codeSystemVersion,subject_code:'TEST_A',license_ref:'TEST_DIAGNOSTIC_LICENSE_DOCUMENT',permitted_scope:null,verifier:'TEST 医务部核验岗',version_no:9,valid_from:'2026-01-01T00:00:00',valid_to:null,record_status:'ACTIVE',source_system_id:base.dep.source.id,source_record_id:'TEST/ORG17/2',approval_ref:'TEST_POLICY_ONLY',recorded_at:'2026-01-02T00:00:00'},reason:'TEST independent diagnostic subject relation',evidenceId:artifact.artifactId};
  return kind==='PERMISSION'?{...common,kind,license:window.services[0]!.segments[0]!.license,limitations:{kind:'NO_ADDITIONAL_LIMITS'}}:{...common,kind,semantic:'EQUIVALENT'};
 };
 const input=async(entries:SubjectDirectEntry[]):Promise<SubjectStage>=>{const j=await transport.newJob();return {requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',profile:'CORE',timePolicy:'LOCAL',entries};};
 const verification=(native:SubjectStage,staged:{inputId:string;digest:string}):SubjectVerification=>({requestId:randomUUID(),inputId:staged.inputId,inputDigest:staged.digest,reason:'TEST independent full scope and adoption review',policyVersion:'ORG17_CORE_V1',rows:native.entries.map((e,index)=>({row:index+1,evidenceId:e.evidenceId,classificationAccepted:true,scopeAccepted:true,adoptionConfirmed:true,limitationsConfirmed:true,license:e.kind==='PERMISSION'?e.license:null,...(e.kind==='MAPPING'?{semantic:e.semantic}:{}),validFrom:e.row.valid_from,validTo:e.row.valid_to}))});
 const apply=async(native:SubjectStage)=>{const staged=await owner.stage('maker',native);await owner.verify('reviewer',verification(native,staged));const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:staged.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);const outcome=await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId});if(outcome.status!=='COMMITTED')throw new Error('COMMIT_UNKNOWN');return outcome;};
 return {owner,codes,adoption,transport,artifact,grant,entry,input,verification,apply,close:async()=>{await owner.close();await codes.close();}};
}
