import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {Pool} from 'pg';
import {test,expect} from 'vitest';
import {openCatalog,openSubjectCodes} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {openSubjectPermissions,type SubjectScope,type SubjectStage,type SubjectDirectEntry} from '../../apps/governance-api/src/modules/care-organization/index.js';
import {openCareLocationLifecycle} from '../../apps/governance-api/src/modules/care-organization/lifecycle-owner.js';
import {openCampus} from '../../apps/governance-api/src/modules/organization-master/index.js';
import {openLocation} from '../../apps/governance-api/src/modules/location-master/index.js';
import {validationKeys} from './p3-11-validation-keys.mjs';
import {businessUnitFixture} from './p3-01-fixture.js';
import {capabilityFixture} from './p3-08-fixture.js';
import {subjectPermissionContract} from './p3-09-fixture.js';
import {provisionSubjects} from './p3-09-provisioning.mjs';
import {provisionCareLifecycle} from './p3-11-provisioning.mjs';
import {peer} from './lineage.mjs';

test('the bundle rejects more than 100 expanded real Unit and binding commands without splitting or writing them',async()=>{
 const connection=process.env['VNEXT_VALIDATION_OWNER_URL']!,receipt=JSON.parse(readFileSync(process.env['VNEXT_TEST_RECEIPT']!,'utf8')),provider=validationKeys(receipt),catalog=await openCatalog(connection,provider),pool=new Pool({connectionString:connection,max:1}),role=(await pool.query('select current_user r')).rows[0]!.r,predecessor=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG04'&&c.profile==='CORE'&&c.status==='PUBLISHED'),warm=!!predecessor&&(await catalog.read('maker',{scope:'SYNTHETIC'})).items.some(i=>i.kind==='SOURCE'&&i.status==='PUBLISHED'&&i.versionId===predecessor.definition.sourceVersionId),base=await businessUnitFixture(receipt,role,catalog,provider,connection,warm);provisionCareLifecycle(receipt,role);const campus=openCampus(connection,provider),locations=openLocation(connection,provider,campus.references),bundle=openCareLocationLifecycle(connection,provider,{UNIT:base.owner,LOCATION:locations});
 try{
  const binding=await base.endpoint(await base.newDepartment()),entries=Array.from({length:34},()=>base.entry(binding)),created=await base.apply(await base.input(entries)),target=await base.endpoint(binding.department.id),T='2027-12-01T00:00:00.000001',moves=[];
  for(const fact of created.facts){const h=await base.owner.history('maker',{id:fact.id}),f=h.versions[0]!.facts,e=base.entry(target);if(e.action!=='CREATE')throw new Error('TEST_CREATE_REQUIRED');moves.push({...e,action:'REBIND' as const,target:{owner:'care-organization/unit' as const,id:h.id,expectedHead:'1'},row:{...e.row,unit_id:f.source.sourceAlias,unit_code:f.unitCode,unit_name:f.unitName,unit_type:f.unitType,public_phone:f.publicPhone??'',service_description:f.serviceDescription??'',receiving_rule_ref:f.receivingRuleReference??'',valid_from:T}});}
  const data=await base.input(moves),input=await base.owner.stage('maker',data);await base.owner.verify('reviewer',base.verification(data,input));await expect(bundle.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',cutover:T,policy:'TEST_POLICY_ONLY',reason:'TEST 34 Unit versions and 68 binding commands exceed the fixed bound',members:[{owner:'UNIT',...input,contractVersionId:base.contract!.versionId}]})).rejects.toThrow('PLAN_INPUT_LIMIT');for(const fact of created.facts)expect((await base.owner.history('maker',{id:fact.id})).versions).toHaveLength(1);
 }finally{await bundle.close();await locations.close();await campus.close();await base.close();await catalog.close();await pool.end();}
});

test('cross-campus Unit movement explicitly retires source capabilities and permissions and grants independently verified target facts',async()=>{
 const connection=process.env['VNEXT_VALIDATION_OWNER_URL']!,receipt=JSON.parse(readFileSync(process.env['VNEXT_TEST_RECEIPT']!,'utf8')),provider=validationKeys(receipt),catalog=await openCatalog(connection,provider),pool=new Pool({connectionString:connection,max:1}),role=(await pool.query('select current_user r')).rows[0]!.r;
 const predecessor=(await catalog.contractRead('maker',{scope:'SYNTHETIC',mode:'CURRENT'})).find(c=>c.dataset==='ORG04'&&c.profile==='CORE'&&c.status==='PUBLISHED'),warm=!!predecessor&&(await catalog.read('maker',{scope:'SYNTHETIC'})).items.some(i=>i.kind==='SOURCE'&&i.status==='PUBLISHED'&&i.versionId===predecessor.definition.sourceVersionId);
 const base=await businessUnitFixture(receipt,role,catalog,provider,connection,warm),cap=await capabilityFixture(receipt,role,catalog,provider,connection,base,true);provisionSubjects(receipt,role,provider);provisionCareLifecycle(receipt,role);
 const codes=openSubjectCodes(connection,provider),permissions=openSubjectPermissions(connection,provider,{operatingWindow:base.operating.operating.evaluateOperatingWindowInTransaction}),campus=openCampus(connection,provider),locations=openLocation(connection,provider,campus.references),bundle=openCareLocationLifecycle(connection,provider,{UNIT:base.owner,CAPABILITY:cap.owner,PERMISSION:permissions,LOCATION:locations});
 try{
  peer(receipt.name,"INSERT INTO governance_catalog.subject_code_access SELECT a,p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE']) p ON CONFLICT DO NOTHING;INSERT INTO governance_catalog.subject_code_access SELECT 'reviewer',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;");
  const system=await codes.command('maker',{action:'CREATE',requestId:randomUUID(),reason:'TEST lifecycle exact adopted subjects',systemCode:'TEST_P311_SUBJECTS',sourceId:base.dep.source.id,sourceVersionId:base.dep.source.versionId,evidenceId:base.artifact.artifactId,reference:{owner:'governance-catalog/subject-code',dataset:'REF01',namespace:'REF01.code_system_id',sourceAlias:'TEST_REF01_P311_SUBJECTS'},codeSystemName:'TEST lifecycle diagnostic subjects',namespaceUri:'urn:hdip:test:p311:subjects',standardDocument:'TEST DOCUMENT',issuer:'TEST POLICY ONLY',codeSystemVersion:'TEST_VERSION_1',sourcePage:'TEST page 1',sourceSummary:'TEST complete synthetic snapshot',adoptedOn:'2026-10-08',label:'TEST_POLICY_ONLY',validFrom:'2026-01-01T00:00:00',validTo:null,codes:[{code:'TEST_A',name:'TEST subject A',meaning:'TEST_A_MEANING',status:'ACTIVE',replacement:null}]});
  const pin={target:system.id,versionId:system.versionId,reviewDigest:system.reviewDigest};await codes.command('reviewer',{action:'VERIFY',requestId:randomUUID(),reason:'TEST independent source read',...pin,evidenceId:base.artifact.artifactId,sourceReviewed:true});await codes.command('reviewer',{action:'APPROVE',requestId:randomUUID(),reason:'TEST independent adoption',...pin});
  const contract=await subjectPermissionContract(catalog,base.dep.source,true),j=await contract.newJob();peer(receipt.name,`INSERT INTO vnext_control.protected_grant SELECT a,'${contract.dataset.id}'::uuid,'NORTH','IDENTITY_VERIFY',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','STORE']) p ON CONFLICT DO NOTHING;`);
  const evidence=await catalog.storeProtectedArtifact('maker',{scope:'SYNTHETIC',requestId:randomUUID(),jobId:j.id,revisionId:j.revisionId,campus:'NORTH',purpose:'IDENTITY_VERIFY',kind:'RAW_CELL',retentionSeconds:7200},Buffer.from('TEST POLICY ONLY exact source and target campus subject permission material'));
  const a=await cap.endpoint(),unit=await base.owner.history('maker',{id:a.unit.id}),target=await base.endpoint(unit.departmentId),T='2027-08-01T00:00:00.000001',next={...a,campus:target.campus,subject:target.subject,services:target.services};cap.grant(next);
  const scope=(b:typeof a):SubjectScope=>({target:{owner:'care-organization/unit',type:'UNIT',id:b.unit.id},campus:b.campus,subject:b.subject,services:b.services}),sourceScope=scope(a),targetScope=scope(next);
  for(const s of [sourceScope,targetScope])peer(receipt.name,`INSERT INTO care_organization.subject_access SELECT a,'${s.subject.id}'::uuid,'${s.campus.id}'::uuid,'UNIT','${s.target.id}'::uuid,'PERMISSION',p FROM unnest(ARRAY['maker','maker-alias','reviewer']) a CROSS JOIN unnest(ARRAY['READ','WRITE','READ_RESTRICTED','VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;`);
  const adoption={owner:'governance-catalog/subject-code' as const,systemId:system.id,versionId:system.versionId,version:'1',code:'TEST_A'};
  const permission=async(s:SubjectScope,from:string):Promise<Extract<SubjectDirectEntry,{kind:'PERMISSION';action:'RECORD'}>>=>{const operating=await base.operating.operating.evaluateOperatingWindow('maker',{subject:s.subject,campus:s.campus,services:s.services,validFrom:from,validTo:null});if(operating.status!=='SATISFIED')throw new Error('TEST_OPERATING_REQUIRED');return {kind:'PERMISSION',action:'RECORD',scope:s,adoption,license:operating.services[0]!.segments[0]!.license,limitations:{kind:'NO_ADDITIONAL_LIMITS'},row:{subject_license_id:randomUUID(),target_type:'UNIT',target_id:s.target.id,code_system_id:'TEST_REF01_P311_SUBJECTS',code_system_version:'TEST_VERSION_1',subject_code:'TEST_A',license_ref:'TEST_LICENSE_DOCUMENT',permitted_scope:null,verifier:'TEST reviewer',version_no:1,valid_from:from,valid_to:null,record_status:'ACTIVE',source_system_id:base.dep.source.id,source_record_id:'TEST/ORG17/P311',approval_ref:'TEST_POLICY_ONLY',recorded_at:'2026-01-02T00:00:00'},reason:'TEST exact independently admitted permission',evidenceId:evidence.artifactId};};
  const preparePermission=async(entries:SubjectDirectEntry[])=>{const job=await contract.newJob(),data:SubjectStage={requestId:randomUUID(),jobId:job.id,revisionId:job.revisionId,campus:'NORTH',profile:'CORE',timePolicy:'LOCAL',entries},staged=await permissions.stage('maker',data);await permissions.verify('reviewer',{requestId:randomUUID(),inputId:staged.inputId,inputDigest:staged.digest,reason:'TEST exact license and full periods independently checked',policyVersion:'ORG17_CORE_V1',rows:entries.map((e,index)=>({row:index+1,evidenceId:e.evidenceId,classificationAccepted:true,scopeAccepted:true,adoptionConfirmed:true,limitationsConfirmed:true,license:e.kind==='PERMISSION'?e.license:null,validFrom:e.row.valid_from,validTo:e.row.valid_to}))});return staged;};
  const oldCap=cap.entry(a),capOut=await cap.apply(await cap.input([oldCap])),oldPermission=await permission(sourceScope,'2026-01-01T00:00:00'),ps=await preparePermission([oldPermission]),pr=randomUUID(),pc=await permissions.plan('maker',{inputId:ps.inputId,requestId:pr});await permissions.readApplyCandidate('reviewer',{candidateId:pc.candidateId});await permissions.approveApplyUnit('reviewer',pc);const oldResult=await permissions.applyUnit('maker',{candidateId:pc.candidateId,requestId:pr});if(oldResult.status!=='COMMITTED')throw new Error('TEST_COMMITTED_REQUIRED');
  expect((await permissions.evaluateWindow('maker',{scope:targetScope,adoption,validFrom:T,validTo:null,mode:'CURRENT_ADMISSION'})).status).toBe('NOT_SATISFIED');
  const uf=unit.versions[0]!.facts,ue=base.entry(target);if(ue.action!=='CREATE')throw new Error('TEST_CREATE_REQUIRED');const rebind={...ue,action:'REBIND' as const,target:{owner:'care-organization/unit' as const,id:unit.id,expectedHead:'1'},row:{...ue.row,unit_id:uf.source.sourceAlias,unit_code:uf.unitCode,unit_name:uf.unitName,unit_type:uf.unitType,public_phone:uf.publicPhone??'',service_description:uf.serviceDescription??'',receiving_rule_ref:uf.receivingRuleReference??'',valid_from:T}},ud=await base.input([rebind]),us=await base.owner.stage('maker',ud);await base.owner.verify('reviewer',base.verification(ud,us));
  const cg=cap.entry(next);cg.row.valid_from=T;const cd=await cap.input([{...oldCap,action:'END',target:{owner:'care-organization/unit-capability',id:capOut.facts[0]!.id,expectedHead:'1'},row:{...oldCap.row,valid_from:T,enabled:'N',record_status:'RETIRED'}},cg]),cs=await cap.owner.stage('maker',cd);await cap.owner.verify('reviewer',cap.verification(cd,cs));
  const ns=await preparePermission([{...oldPermission,action:'RETIRE',target:{owner:'care-organization/subject-permission',id:oldResult.facts[0]!.id,expectedHead:'1'},row:{...oldPermission.row,valid_from:T,record_status:'RETIRED'}},await permission(targetScope,T)]);
  const staged=await bundle.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',cutover:T,policy:'TEST_POLICY_ONLY',reason:'TEST explicit source retirement and target entitlement admission',members:[{owner:'PERMISSION',...ns,contractVersionId:contract.contract.versionId},{owner:'CAPABILITY',...cs,contractVersionId:cap.contract!.versionId},{owner:'UNIT',...us,contractVersionId:base.contract!.versionId}]});await bundle.verify('reviewer',{requestId:randomUUID(),inputId:staged.inputId,inputDigest:staged.digest,policy:'TEST_POLICY_ONLY',reason:'TEST all producer inputs, scopes, and licenses independently checked'});const requestId=randomUUID(),candidate=await bundle.plan('maker',{inputId:staged.inputId,requestId});await bundle.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await bundle.approveApplyUnit('reviewer',candidate);const out=await bundle.applyUnit('maker',{candidateId:candidate.candidateId,requestId});expect(out.status).toBe('COMMITTED');if(out.status!=='COMMITTED')throw new Error('TEST_COMMITTED_REQUIRED');expect(out.facts).toHaveLength(5);
  expect((await cap.owner.evaluateWindow('maker',{applicability:next,validFrom:T,validTo:null,mode:'CURRENT_ADMISSION'})).status).toBe('SATISFIED');expect((await permissions.evaluateWindow('maker',{scope:targetScope,adoption,validFrom:T,validTo:null,mode:'CURRENT_ADMISSION'})).status).toBe('SATISFIED');expect((await permissions.read('maker',{id:oldResult.facts[0]!.id,businessAt:T})).state).toBe('RETIRED');expect(await bundle.reconcileCommittedUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'MATCHED'});
  for(const fact of out.facts){const h=fact.owner==='care-organization/unit'?await base.owner.history('maker',{id:fact.id}):fact.owner==='care-organization/unit-capability'?await cap.owner.history('maker',{id:fact.id}):await permissions.history('maker',{id:fact.id});expect(h.versions.at(-1)!.recordedAt).toBe(out.recordedAt);const facts=h.versions.at(-1)!.facts;if('dependencies' in facts)expect(JSON.stringify(facts.dependencies)).not.toContain('LIFECYCLE_CARE_INPUT');}
 }finally{await bundle.close();await permissions.close();await codes.close();await locations.close();await campus.close();await cap.close();await base.close();await catalog.close();await pool.end();}
});
