import {randomUUID} from 'node:crypto';
import {openCatalog,canonicalPlan,type KeyProviderPort} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {openCareWorkspace,type CareWorkspaceKind,type CareValidationPorts} from '../../apps/governance-api/src/modules/care-organization/index.js';
import {locationUseFixture} from './p3-07-fixture.js';
import {unitWardFixture} from './p3-04-fixture.js';
import {wardNursingFixture} from './p3-05-fixture.js';
import {capabilityFixture} from './p3-08-fixture.js';
import {careSubjectFixture} from './p3-10-subject-fixture.js';
import {provisionCareLifecycle} from './p3-11-provisioning.mjs';
import {provisionCareWorkspace} from './p3-10-provisioning.mjs';
export async function prepareCareBrowser(receipt:{name:string;oid:string},role:string,connection:string,provider:KeyProviderPort){
 const catalog=await openCatalog(connection,provider),space=await locationUseFixture(receipt,role,catalog,provider,connection,true),relations=await unitWardFixture(receipt,role,catalog,provider,connection,true,space.wards),coverage=await wardNursingFixture(receipt,role,catalog,provider,connection,true,space.wards),capabilities=await capabilityFixture(receipt,role,catalog,provider,connection,space.base,true),subjects=await careSubjectFixture(receipt,role,catalog,provider,connection,space.base),ports:CareValidationPorts={UNIT:space.base.owner,NURSING:space.nursing.owner,WARD:space.wards.owner,LOCATION:space.locations.owner,LOCATION_USE:space.owner,UNIT_WARD:relations.owner,WARD_NURSING:coverage.owner,CAPABILITY:capabilities.owner,PERMISSION:subjects.owner};
 provisionCareLifecycle(receipt,role);provisionCareWorkspace(receipt,role);const workspace=openCareWorkspace(connection,provider,ports);
 try{
  const drafts:Array<{kind:CareWorkspaceKind;draftId:string;version:string;native:unknown;verification:unknown;flow?:string}>=[];
  const save=async(kind:CareWorkspaceKind,native:Record<string,unknown>,contract:{id:string;versionId:string},verification:unknown)=>{const {requestId:_,jobId:__,revisionId:___,campus,profile,...payload}=native,saved=await workspace.save('maker',{kind,campus:campus as 'NORTH',profile:profile as 'CORE',payload,requestId:randomUUID(),transport:{contractId:contract.id,contractVersionId:contract.versionId}});drafts.push({kind,draftId:saved.id,version:saved.version,native,verification});};
  const units=space.base,u=await units.input([units.entry(await units.endpoint(await units.newDepartment()))]);await save('UNIT',u,units.contract!,units.verification(u,{inputId:'<original input>',digest:'<original digest>'}));
  const n=await space.nursing.input([space.nursing.entry(await space.nursing.endpoint())]);await save('NURSING',n,space.nursing.contract!,space.nursing.verification(n,{inputId:'<original input>',digest:'<original digest>'}));
  const w=await space.wards.input([space.wards.entry(await space.wards.endpoint())]);await save('WARD',w,space.wards.contract!,space.wards.verification(w,{inputId:'<original input>',digest:'<original digest>'}));
  const campus=await space.locations.newCampus(),l=await space.locations.input(campus,space.locations.tree(campus));await save('LOCATION',l,space.locations.contract!,{policyVersion:'ORG12_CORE_V1',evidenceId:space.locations.artifact.artifactId,physicalFactsAccepted:false,reason:'TEST independently reviewed physical containment'});
  const uw=await relations.input([relations.entry(await relations.endpoint())]);await save('UNIT_WARD',uw,relations.contract!,relations.verification(uw,{inputId:'<original input>',digest:'<original digest>'}));
  const scope=await coverage.endpoint(),set=await coverage.register(scope),wn=await coverage.input([coverage.entry(scope,coverage.partition(set,[0]))]);await save('WARD_NURSING',wn,coverage.contract!,coverage.verification(wn,{inputId:'<original input>',digest:'<original digest>'}));
  const c=await capabilities.input([capabilities.entry(await capabilities.endpoint())]);await save('CAPABILITY',c,capabilities.contract!,capabilities.verification(c,{inputId:'<original input>',digest:'<original digest>'}));
  const s=await units.endpoint(await units.newDepartment()),published=await units.apply(await units.input([units.entry(s)])),permission=await subjects.input([await subjects.entry({target:{type:'UNIT',owner:'care-organization/unit',id:published.facts[0]!.id},subject:s.subject,campus:s.campus,services:s.services})]);await save('PERMISSION',permission,subjects.transport.contract,subjects.verification(permission,{inputId:'<original input>',digest:'<original digest>'}));
  const use=await space.input([await space.entry(await space.endpoint('UNIT'))]);await save('LOCATION_USE',use,space.contract!,space.verification(use,{inputId:'<original input>',digest:'<original digest>'}));
  const scopeDefinition=await coverage.scopeInput(await coverage.endpoint());await save('WARD_NURSING',scopeDefinition,coverage.contract!,coverage.verification(scopeDefinition,{inputId:'<original input>',digest:'<original digest>'}));drafts.at(-1)!.flow='SCOPE_DEFINITION';
  const mapping=await subjects.input([await subjects.entry({target:{type:'UNIT',owner:'care-organization/unit',id:published.facts[0]!.id},subject:s.subject,campus:s.campus,services:s.services},'MAPPING')]);await save('PERMISSION',mapping,subjects.transport.contract,subjects.verification(mapping,{inputId:'<original input>',digest:'<original digest>'}));drafts.at(-1)!.flow='SUBJECT_MAPPING';
  const parameterScope=await capabilities.endpoint(),definition=await catalog.parameterCommand('maker',{action:'CREATE',scope:'SYNTHETIC',requestId:randomUUID(),reason:'TEST_BROWSER_BASIS',systemVersionId:units.dep.source.versionId,parameterKey:'BROWSER_'+randomUUID().replaceAll('-','').toUpperCase(),group:'CARE',campus:'SYNTHETIC_ALL',definition:{kind:'VALUE_SCHEMA_V1',valueType:'BOOLEAN',enumValues:[],description:'TEST POLICY ONLY actual browser parameter maintenance'},validFrom:'2026-01-01T00:00:00',validTo:null});await catalog.parameterCommand('reviewer',{action:'APPROVE',scope:'SYNTHETIC',requestId:randomUUID(),reason:'TEST_BROWSER_BASIS',target:definition.id,versionId:definition.versionId,reviewDigest:definition.reviewDigest});
  const parameterValueCreate={action:'CREATE',requestId:randomUUID(),reason:'TEST POLICY ONLY actual browser basis maintenance',definitionVersionId:definition.versionId,definitionDigest:definition.reviewDigest,applicability:parameterScope,value:{type:'BOOLEAN',value:true},purpose:'BOOLEAN_GATE_V1',validFrom:'2026-01-01T00:00:00',validTo:null,evidenceId:capabilities.artifact.artifactId};
  const subjectAdoptionCreate={action:'CREATE',requestId:randomUUID(),reason:'TEST POLICY ONLY actual browser source adoption',systemCode:'BROWSER_'+randomUUID().replaceAll('-','').toUpperCase(),sourceId:units.dep.source.id,sourceVersionId:units.dep.source.versionId,evidenceId:units.artifact.artifactId,reference:{owner:'governance-catalog/subject-code',dataset:'REF01',namespace:'REF01.code_system_id',sourceAlias:'TEST_BROWSER_REF01_'+randomUUID().slice(0,8)},codeSystemName:'TEST 浏览器合成科目',namespaceUri:'urn:hdip:test:p3-10:browser',standardDocument:'TEST DOCUMENT 2022',issuer:'TEST POLICY ONLY',codeSystemVersion:'2022版',sourcePage:'TEST page 1',sourceSummary:'TEST POLICY ONLY independently reviewed complete synthetic adoption',adoptedOn:'2026-10-10',label:'TEST_POLICY_ONLY',validFrom:'2026-01-01T00:00:00',validTo:null,codes:[{code:'TEST_BROWSER_A',name:'TEST 浏览器科目甲',meaning:'TEST_BROWSER_MEANING',status:'ACTIVE',replacement:null}]};
  const input=await units.input([units.entry(await units.endpoint(await units.newDepartment()))]),created=await units.apply(input),entry=input.entries[0]!;if(entry.action!=='CREATE')throw new Error('FIXTURE_INVALID');const {binding:_,...command}=entry,native=await units.input([{...command,action:'SUSPEND',target:{owner:'care-organization/unit',id:created.facts[0]!.id,expectedHead:'1'},row:{...entry.row,valid_from:'2029-01-01T00:00:00.000001',record_status:'SUSPENDED'}}]),member=await units.owner.stage('maker',native);await units.owner.verify('reviewer',units.verification(native,member));
  const saveBundle=async(flow:string,kind:'MOVE'|'CLOSE'|'RESUME'|'HANDOVER'|'REPARTITION',cutover:string,members:Array<{owner:'UNIT'|'WARD'|'WARD_NURSING'|'LOCATION_USE';inputId:string;revisionId:string;digest:string;contractVersionId:string}>)=>{const saved=await workspace.save('maker',{kind:'LIFECYCLE',campus:'NORTH',profile:'CORE',requestId:randomUUID(),payload:{kind,policy:'TEST_POLICY_ONLY',cutover,reason:'TEST browser '+flow,members}});drafts.push({kind:'LIFECYCLE',flow,draftId:saved.id,version:saved.version,native:null,verification:{reason:'TEST independently confirmed original producer and full window',policy:'TEST_POLICY_ONLY'}});};
  await saveBundle('PAUSE','CLOSE','2029-01-01T00:00:00.000001',[{owner:'UNIT',...member,contractVersionId:units.contract!.versionId}]);
  const T='2029-02-01T00:00:00.000001';
  // Each browser flow owns distinct facts and only pre-verifies its native members.
  // The root composition is still submitted, independently verified and applied in the UI.
  const moveScope=await space.endpoint('UNIT'),moveOld=await space.entry(moveScope),moveCreated=await space.apply(await space.input([moveOld])),moveNew=await space.entry({...moveScope,location:await space.newLocation(moveScope.campus.id)});
  moveNew.row.valid_from=T;const moveInput=await space.input([{...moveOld,action:'END',target:{owner:'location-master/location-use',id:moveCreated.facts[0]!.id,expectedHead:'1'},endAt:T,row:{...moveOld.row,record_status:'RETIRED'}},moveNew]),move=await space.owner.stage('maker',moveInput);await space.owner.verify('reviewer',space.verification(moveInput,move));
  await saveBundle('SAME_CAMPUS_LOCATION','MOVE',T,[{owner:'LOCATION_USE',...move,contractVersionId:space.contract!.versionId}]);
  const wardSource=await space.wards.endpoint(),wardEntry=space.wards.entry(wardSource),wardCreated=await space.wards.apply(await space.wards.input([wardEntry])),wardTarget=await space.wards.endpoint(),wardData=await space.wards.input([{...wardEntry,action:'REBIND',target:{owner:'care-organization/ward',id:wardCreated.facts[0]!.id,expectedHead:'1'},binding:wardTarget,row:{...wardEntry.row,campus_id:wardTarget.campus.id,managing_unit_id:wardTarget.unit.id,valid_from:T}}]),wardMove=await space.wards.owner.stage('maker',wardData);await space.wards.owner.verify('reviewer',space.wards.verification(wardData,wardMove));
  await saveBundle('CROSS_CAMPUS_REBIND','MOVE',T,[{owner:'WARD',...wardMove,contractVersionId:space.wards.contract!.versionId}]);
  const handA=await coverage.endpoint(),handB=await coverage.sameWard(handA),handSet=await coverage.register(handA),whole=coverage.partition(handSet,[0,1]),handOld=coverage.entry(handA,whole),handCreated=await coverage.apply(await coverage.input([handOld])),handId=handCreated.facts[0]!.id,left=coverage.entry(handA,coverage.partition(handSet,[0])),right=coverage.entry(handB,coverage.partition(handSet,[1]));
  for(const successor of [left,right]){successor.row.valid_from=T;successor.row.handover_rule_ref='TEST_PARTIAL';}
  const handData=await coverage.input([{...handOld,action:'END',target:{owner:'care-organization/ward-nursing-coverage',id:handId,expectedHead:'1'},endAt:T,row:{...handOld.row,record_status:'RETIRED'}},left,right]),hand=await coverage.owner.stage('maker',handData),handReview=coverage.verification(handData,hand),partitionPlan={sourceCoverage:whole,successors:[{sourceAlias:left.row.ward_nursing_rel_id,nursing:handA.nursing,coverage:left.coverage},{sourceAlias:right.row.ward_nursing_rel_id,nursing:handB.nursing,coverage:right.coverage}]};
  for(const [index,successor] of [left,right].entries())handReview.rows[index+1]!.handover={kind:'CONFIRMED_HANDOVER',source:{owner:'care-organization/ward-nursing-coverage',id:handId,expectedHead:'1'},successorSourceAlias:successor.row.ward_nursing_rel_id,successorNursing:successor.applicability.nursing,coverage:successor.coverage,cutover:T,ruleReference:'TEST_PARTIAL',ruleVersion:'TEST_POLICY_ONLY_1',evidenceId:coverage.artifact.artifactId,confirmed:true,partitionPlan};
  await coverage.owner.verify('reviewer',await coverage.confirmHandover(handReview));await saveBundle('NURSING_HANDOVER','HANDOVER',T,[{owner:'WARD_NURSING',...hand,contractVersionId:coverage.contract!.versionId}]);
  const partScope=await coverage.endpoint(),partSet=await coverage.register(partScope),partData=await coverage.scopeInput(partScope);if(partData.kind!=='SCOPE_DEFINITION')throw new Error('FIXTURE_INVALID');
  const revised={...partData,kind:'SCOPE_REVISION' as const,target:{id:partSet.id,expectedHead:'1'},definition:{...partData.definition,sourceAlias:partSet.sourceAlias,validFrom:T,partitions:partData.definition.partitions.map(p=>({...p,boundary:p.boundary+' TEST browser reviewed boundary'}))},mapping:partSet.partitions.map(p=>({version:'1',partitionId:p.id,toAliases:[p.sourceAlias]}))},part=await coverage.owner.stage('maker',revised);await coverage.owner.verify('reviewer',{...coverage.verification(revised,part),scopeDefinition:{completeAndDisjoint:true,definitionDigest:part.digest,evidenceId:coverage.artifact.artifactId}});
  await saveBundle('REPARTITION','REPARTITION',T,[{owner:'WARD_NURSING',inputId:part.inputId,revisionId:part.revisionId,digest:part.digest,contractVersionId:coverage.contract!.versionId}]);
  for(const action of ['RESUME','CLOSE'] as const){const originalInput=await units.input([units.entry(await units.endpoint(await units.newDepartment()))]),original=await units.apply(originalInput),initial=originalInput.entries[0]!;if(initial.action!=='CREATE')throw new Error('FIXTURE_INVALID');const {binding:__,...base}=initial;let head='1';if(action==='RESUME'){await units.apply(await units.input([{...base,action:'SUSPEND',target:{owner:'care-organization/unit',id:original.facts[0]!.id,expectedHead:head},row:{...initial.row,valid_from:'2029-01-01T00:00:00.000001',record_status:'SUSPENDED'}}]));head='2';}
   const data=await units.input([{...base,action,target:{owner:'care-organization/unit',id:original.facts[0]!.id,expectedHead:head},row:{...initial.row,valid_from:T,record_status:action==='RESUME'?'ACTIVE':'RETIRED'}}]),staged=await units.owner.stage('maker',data);await units.owner.verify('reviewer',units.verification(data,staged));await saveBundle(action==='RESUME'?'RESUME':'PERMANENT_EXIT',action,T,[{owner:'UNIT',...staged,contractVersionId:units.contract!.versionId}]);}
  const partial=await workspace.save('maker',{kind:'UNIT',campus:'NORTH',profile:'CORE',requestId:randomUUID(),payload:{entries:[{row:{unit_name:'TEST 浏览器不完整草稿'}}]}});
  return {policy:'TEST POLICY ONLY',scope:'SYNTHETIC_OWNED_TEMPORARY',drafts:JSON.parse(canonicalPlan(drafts)),partialDraftId:partial.id,createdLifecycleUnitId:created.facts[0]!.id,fieldRows:u.entries.map(e=>e.row),fileContract:{id:units.contract!.id,versionId:units.contract!.versionId},fileOperations:u.entries.map(({row:_,...operation})=>operation),source:units.dep.source,material:units.artifact,subjectAdoption:subjects.adoption,parameterDefinition:definition,parameterValueCreate,subjectAdoptionCreate};
 }finally{await workspace.close();await subjects.close();await capabilities.close();await coverage.close();await relations.close();await space.close();await catalog.close();}
}
