import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {Pool} from 'pg';
import {withP310Predecessor,p310PredecessorBaseline} from './p3-10-predecessor.mjs';
import {readReceipt} from './lineage.mjs';
import {validationKeys} from './p3-10-validation-keys.mjs';
import {openCatalog} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {openCareLocationLifecycle} from '../../apps/governance-api/src/modules/care-organization/index.js';
import {openLocationUse,openLocation,openLocationUsageTypes} from '../../apps/governance-api/src/modules/location-master/index.js';
import {openBusinessUnit,openWard,openNursingUnit} from '../../apps/governance-api/src/modules/care-organization/index.js';
import {openDepartmentLifecycle} from '../../apps/governance-api/src/modules/department-master/index.js';
import {openOperatingRelations,openCampus} from '../../apps/governance-api/src/modules/organization-master/index.js';
import {locationUseUpstreamPorts} from '../../apps/governance-api/src/composition/location-use-dependencies.js';
import {wardUpstreamPorts} from '../../apps/governance-api/src/composition/ward-dependencies.js';
import {nursingUpstreamPorts} from '../../apps/governance-api/src/composition/nursing-unit-dependencies.js';
import type {locationUseFixture} from './p3-07-fixture.js';
const args=process.argv.slice(2);assert.ok(args.length===0||args.length===1&&args[0]==='--verify');
const receiptPath=process.env['VNEXT_TEST_RECEIPT']!,connection=process.env['VNEXT_VALIDATION_OWNER_URL']!,receipt=readReceipt(receiptPath);assert.equal(receipt.taskId,'P3-10');assert.equal(receipt.purpose,'TEMPORARY_VALIDATION');const provider=validationKeys(receipt),pool=new Pool({connectionString:connection,max:1}),evidence=receiptPath+'.p3-10-predecessor0252.json';
try{
 const identity=(await pool.query('select current_user role,current_database() name,d.oid::text oid from pg_database d where d.datname=current_database()')).rows[0];assert.equal(identity.name,receipt.name);assert.equal(identity.oid,receipt.oid);assert.match(identity.role,/^hdi_validation_[a-f0-9]{16}$/);
 if(!args.length){assert.equal((await pool.query('select count(*)::integer n from vnext_control.migration')).rows[0].n,252);await withP310Predecessor(async(directory:string,source:unknown)=>{
  const load=(path:string)=>import(pathToFileURL(resolve(directory,path)).href),{locationUseFixture:legacyFixture}=await load('tooling/vnext/p3-07-fixture.ts') as {locationUseFixture:typeof locationUseFixture},{openCatalog:legacyCatalog}=await load('apps/governance-api/src/modules/governance-catalog/index.ts') as {openCatalog:typeof openCatalog},{openCareLocationLifecycle:legacyLifecycle}=await load('apps/governance-api/src/modules/care-organization/index.ts') as {openCareLocationLifecycle:typeof openCareLocationLifecycle};
  const previousStep=process.env['VNEXT_CONNECTION_STEP'];process.env['VNEXT_CONNECTION_STEP']='P3-11';const catalog=await legacyCatalog(connection,provider);let fixture:Awaited<ReturnType<typeof locationUseFixture>>|undefined,group:ReturnType<typeof openCareLocationLifecycle>|undefined;
  // Establish the original service's full finite P3 public port grants before
  // freezing ACL evidence; later coverage must not add grants to old routines.
  for(const [file,name] of [['p3-04-provisioning.mjs','provisionUnitWard'],['p3-05-provisioning.mjs','provisionWardNursing'],['p3-08-provisioning.mjs','provisionUnitCapability'],['p3-09-provisioning.mjs','provisionSubjects']]){const provisioning=await load('tooling/vnext/'+file);provisioning[name!](receipt,identity.role,provider);}
  try{fixture=await legacyFixture({...receipt,taskId:'P3-11'},identity.role,catalog,provider,connection,true);const a=await fixture.endpoint('UNIT'),use=await fixture.apply(await fixture.input([await fixture.entry(a)])),n=await fixture.endpoint('NURSING'),ids={unit:a.target.id,nursing:n.target.id,location:a.location.id,use:use.facts[0]!.id};
   const units=fixture.base,entry=units.entry(await units.endpoint(await units.newDepartment())),unitCreated=await units.apply(await units.input([entry]));ids.unit=unitCreated.facts[0]!.id;const history=await units.owner.history('maker',{id:ids.unit});assert.equal(entry.action,'CREATE');const {binding:_,...native}=entry,input=await units.input([{...native,action:'SUSPEND',target:{owner:'care-organization/unit',id:ids.unit,expectedHead:history.versions.at(-1)!.number},row:{...entry.row,valid_from:'2029-01-01T00:00:00.000001',record_status:'SUSPENDED'}}]),member=await units.owner.stage('maker',input);await units.owner.verify('reviewer',units.verification(input,member));
   group=legacyLifecycle(connection,provider,{UNIT:units.owner,NURSING:fixture.nursing.owner,WARD:fixture.wards.owner,LOCATION:fixture.locations.owner,LOCATION_USE:fixture.owner});const root=await group.stage('maker',{requestId:randomUUID(),campus:'NORTH',policy:'TEST_POLICY_ONLY',kind:'CLOSE',cutover:'2029-01-01T00:00:00.000001',reason:'TEST exact0252 original lifecycle suspension',members:[{owner:'UNIT',...member,contractVersionId:units.contract!.versionId}]});await group.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST original0252 independent verification',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await group.plan('maker',{inputId:root.inputId,requestId});await group.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await group.approveApplyUnit('reviewer',candidate);const request={candidateId:candidate.candidateId,requestId},outcome=await group.applyUnit('maker',request);assert.equal(outcome.status,'COMMITTED');assert.equal((await group.reconcileCommittedUnit('maker',request)).status,'MATCHED');
   const resume=await group.resumeOutcome('maker',request),replay=await group.applyUnit('maker',request);const histories={unit:await units.owner.history('maker',{id:ids.unit}),nursing:await fixture.nursing.owner.history('maker',{id:ids.nursing}),location:await fixture.locations.owner.history('maker',{id:ids.location}),use:await fixture.owner.history('maker',{id:ids.use})},oldR=(await units.owner.read('maker',{id:ids.unit,businessAt:'2029-02-01T00:00:00',recordAsOf:history.versions[0]!.recordedAt}));writeFileSync(evidence,JSON.stringify({baseline:p310PredecessorBaseline,source,ids,request,outcome,resume,replay,histories,oldR,rootInputId:root.inputId},null,2),{flag:'wx'});
  }finally{await group?.close();await fixture?.close();await catalog.close();process.env['VNEXT_CONNECTION_STEP']=previousStep;}
 },receipt);
 }else{const original=JSON.parse(readFileSync(evidence,'utf8')),operating=openOperatingRelations(connection,provider),department=openDepartmentLifecycle(connection,provider),units=openBusinessUnit(connection,provider,{departmentCoverage:department.readUnitBindingCoverageInTransaction,departmentBoundaries:department.readUnitBindingBoundariesInTransaction,referenceAccess:department.authorizeUnitReferenceInTransaction,operatingWindow:operating.evaluateOperatingWindowInTransaction}),campus=openCampus(connection,provider),locations=openLocation(connection,provider,campus.references),nursing=openNursingUnit(connection,provider,nursingUpstreamPorts),ward=openWard(connection,provider,wardUpstreamPorts(units)),dictionary=openLocationUsageTypes(connection,provider),use=openLocationUse(connection,provider,locationUseUpstreamPorts(locations,department,units,ward,nursing),dictionary),group=openCareLocationLifecycle(connection,provider,{UNIT:units,NURSING:nursing,WARD:ward,LOCATION:locations,LOCATION_USE:use});try{
   assert.deepEqual(await units.history('maker',{id:original.ids.unit}),original.histories.unit);assert.deepEqual(await nursing.history('maker',{id:original.ids.nursing}),original.histories.nursing);assert.deepEqual(await locations.history('maker',{id:original.ids.location}),original.histories.location);assert.deepEqual(await use.history('maker',{id:original.ids.use}),original.histories.use);assert.deepEqual(await units.read('maker',{id:original.ids.unit,businessAt:'2029-02-01T00:00:00',recordAsOf:original.histories.unit.versions[0].recordedAt}),original.oldR);assert.deepEqual(await group.applyUnit('maker',original.request),original.replay);assert.deepEqual(await group.resumeOutcome('maker',original.request),original.resume);assert.equal((await group.reconcileCommittedUnit('maker',original.request)).status,'MATCHED');console.log(JSON.stringify({gate:'P3_10_ORIGINAL_0252_UPGRADE',status:'PASS',baseline:original.baseline,historyAndOldRPreserved:true,originalRequestReplayed:true}));
  }finally{await group.close();await use.close();await dictionary.close();await ward.close();await nursing.close();await locations.close();await campus.close();await units.close();await department.close();await operating.close();}
 }
}finally{await pool.end();}
