import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {Pool,Client,type QueryConfig} from 'pg';
import type {FastifyRequest} from 'fastify';
import {test,expect,afterAll} from 'vitest';
import type {NursingEntry} from '../../apps/governance-api/src/modules/care-organization/nursing-contracts.js';
import {openCatalog} from '../../apps/governance-api/src/modules/governance-catalog/index.js';
import {openCareLocationLifecycle} from '../../apps/governance-api/src/modules/care-organization/lifecycle-owner.js';
import {createCareLocationLifecycleClient} from '../../packages/generated-api-client/src/index.js';
import {actor} from '../../apps/governance-api/src/platform/fastify/vnext-catalog-routes.js';
import {validationKeys} from './p3-11-validation-keys.mjs';
import {locationUseFixture} from './p3-07-fixture.js';
import {provisionCareLifecycle} from './p3-11-provisioning.mjs';
import {startWorkbench} from './workbench-runtime.mjs';
import {unitWardFixture} from './p3-04-fixture.js';
import {peer} from './lineage.mjs';

const connection=process.env['VNEXT_VALIDATION_OWNER_URL']!,receipt=JSON.parse(readFileSync(process.env['VNEXT_TEST_RECEIPT']!,'utf8')),provider=validationKeys(receipt),catalog=await openCatalog(connection,provider),pool=new Pool({connectionString:connection,max:1}),role=(await pool.query('select current_user r')).rows[0]!.r;
const fixture=await locationUseFixture(receipt,role,catalog,provider,connection,true);provisionCareLifecycle(receipt,role);
const owner=openCareLocationLifecycle(connection,provider,{UNIT:fixture.base.owner,WARD:fixture.wards.owner,NURSING:fixture.nursing.owner,LOCATION:fixture.locations.owner,LOCATION_USE:fixture.owner});
const runtime=await startWorkbench({port:0,validationContext:{receipt,connection,provider,locationUse:{owner:fixture.owner,usageTypes:fixture.dictionary,actor:(r:FastifyRequest)=>actor(r.headers)},careLifecycle:{owner,actor:(r:FastifyRequest)=>actor(r.headers)}}});
const maker=createCareLocationLifecycleClient(runtime.url,'maker'),reviewer=createCareLocationLifecycleClient(runtime.url,'reviewer');
afterAll(async()=>{await runtime.close();await owner.close();await fixture.close();await catalog.close();await pool.end();});
const success=<T>(result:{response:Response;data?:T;error?:{code:string}})=>{expect(result.response.status,result.error?.code).toBe(200);if(!result.data)throw new Error('HTTP_DATA_REQUIRED');return result.data;};
const diagnosticQuery=Client.prototype.query;
Client.prototype.query=(function(this:Client,config:string|QueryConfig,...args:unknown[]){const result=Reflect.apply(diagnosticQuery,this,[config,...args]);if(result&&typeof result.then==='function')return Promise.resolve(result).catch((error:unknown)=>{if(error instanceof Error&&'code' in error&&typeof error.code==='string'){const code=/^[A-Z][A-Z0-9_]+$/.test(error.message)?error.message:null,frames='where' in error&&typeof error.where==='string'?error.where.split('\n').filter(line=>/^PL\/pgSQL function [a-z_]+\.[a-z_]+\([a-z, ]*\) line [0-9]+ at [a-z ]+$/.test(line)):[];console.error(JSON.stringify({gate:'P3_11_SQL_DIAGNOSTIC',sqlstate:error.code,code,frames}));}throw error;});return result;}) as typeof diagnosticQuery;
afterAll(()=>{Client.prototype.query=diagnosticQuery;});

test.each([false,true])('Unit Ward relation successors consume exact Unit and Ward producers at the same cross-campus cutover (shared=%s)',async(shared)=>{
 const relations=await unitWardFixture(receipt,role,catalog,provider,connection,true,fixture.wards),group=openCareLocationLifecycle(connection,provider,{UNIT:fixture.base.owner,WARD:fixture.wards.owner,UNIT_WARD:relations.owner,LOCATION:fixture.locations.owner});
 try{
  const a=await relations.endpoint(),old=relations.entry(a),created=await relations.apply(await relations.input([old])),unit=await fixture.base.owner.history('maker',{id:a.unit.id}),ward=await fixture.wards.owner.history('maker',{id:a.ward.id}),target=await fixture.base.endpoint(unit.departmentId),T='2027-09-01T00:00:00.000001';fixture.wards.grant(target.campus.id);
  const uf=unit.versions[0]!.facts,ue=fixture.base.entry(target);if(ue.action!=='CREATE')throw new Error('TEST_CREATE_REQUIRED');const u={...ue,action:'REBIND' as const,target:{owner:'care-organization/unit' as const,id:unit.id,expectedHead:'1'},row:{...ue.row,unit_id:uf.source.sourceAlias,unit_code:uf.unitCode,unit_name:uf.unitName,unit_type:uf.unitType,public_phone:uf.publicPhone??'',service_description:uf.serviceDescription??'',receiving_rule_ref:uf.receivingRuleReference??'',valid_from:T}},ui=await fixture.base.input([u]),us=await fixture.base.owner.stage('maker',ui);await fixture.base.owner.verify('reviewer',fixture.base.verification(ui,us));
  const wf=ward.versions[0]!.facts,we=fixture.wards.entry({unit:a.unit,campus:target.campus}),w={...we,action:'REBIND' as const,binding:{unit:a.unit,campus:target.campus},target:{owner:'care-organization/ward' as const,id:ward.id,expectedHead:'1'},row:{...we.row,ward_id:wf.source.sourceAlias,ward_code:wf.wardCode,ward_name:wf.wardName,ward_type:wf.wardType,public_phone:wf.publicPhone,admission_rule_ref:wf.admissionRuleReference,valid_from:T}},wi=await fixture.wards.input([w]),ws=await fixture.wards.owner.stage('maker',wi);await fixture.wards.owner.verify('reviewer',fixture.wards.verification(wi,ws));
  const next={...a,campus:target.campus};relations.grant(next);const successor=relations.entry(next);successor.row.valid_from=T;if(shared){const received=await fixture.base.apply(await fixture.base.input([fixture.base.entry(target)]));const rule=relations.shared([a.unit.id,received.facts[0]!.id]);if(rule.kind!=='SHARED_BOUNDARY')throw new Error('TEST_SHARED_REQUIRED');successor.rule={...rule,validFrom:T};successor.row.relation_type='共享';successor.row.sharing_rule='TEST_SHARED_WARD';}const end={...old,action:'END' as const,target:{owner:'care-organization/unit-ward-relation' as const,id:created.facts[0]!.id,expectedHead:'1'},endAt:T,row:{...old.row,record_status:'RETIRED' as const}},ri=await relations.input([end,successor]),rs=await relations.owner.stage('maker',ri);await relations.owner.verify('reviewer',relations.verification(ri,rs));
  const root=await group.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',cutover:T,policy:'TEST_POLICY_ONLY',reason:'TEST explicit source and target Unit Ward relation disposition',members:[{owner:'UNIT_WARD',...rs,contractVersionId:relations.contract!.versionId},{owner:'WARD',...ws,contractVersionId:fixture.wards.contract!.versionId},{owner:'UNIT',...us,contractVersionId:fixture.base.contract!.versionId}]});await group.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST exact full windows and producer scopes independently checked',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await group.plan('maker',{inputId:root.inputId,requestId});await group.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await group.approveApplyUnit('reviewer',candidate);const result=await group.applyUnit('maker',{candidateId:candidate.candidateId,requestId});expect(result.status).toBe('COMMITTED');if(result.status!=='COMMITTED')throw new Error('TEST_COMMITTED_REQUIRED');expect(result.facts).toHaveLength(4);const accepted=result.facts.find(f=>f.owner==='care-organization/unit-ward-relation'&&f.version==='1')!;const history=await relations.owner.history('maker',{id:accepted.id});expect(history.versions[0]!.recordedAt).toBe(result.recordedAt);expect(JSON.stringify(history.versions[0]!.facts.dependencies)).not.toContain('LIFECYCLE_CARE_INPUT');expect(await group.reconcileCommittedUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'MATCHED'});
 }finally{await group.close();await relations.close();}
});

test('lifecycle history at R before verification does not disclose the later verification or reason',async()=>{
 const a=await fixture.endpoint('UNIT'),entry=await fixture.entry(a),created=await fixture.apply(await fixture.input([entry])),id=created.facts[0]!.id,T='2027-07-01T00:00:00',end={...entry,action:'END' as const,target:{owner:'location-master/location-use' as const,id,expectedHead:'1'},endAt:T,row:{...entry.row,record_status:'RETIRED' as const}},data=await fixture.input([end]),member=await fixture.owner.stage('maker',data);await fixture.owner.verify('reviewer',fixture.verification(data,member));
 const root=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'CLOSE',policy:'TEST_POLICY_ONLY',cutover:T,reason:'TEST historical record cognition',members:[{owner:'LOCATION_USE',...member,contractVersionId:fixture.contract!.versionId}]}),before=await owner.history('maker',{inputId:root.inputId});expect(before.originalAcceptedBasis.verification).toBeNull();await owner.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST later independently verified reason',policy:'TEST_POLICY_ONLY'});
 const historical=await owner.history('maker',{inputId:root.inputId,recordAsOf:before.currentDependencyReview.recordAsOf});expect(historical.originalAcceptedBasis).toEqual(before.originalAcceptedBasis);expect((await owner.history('maker',{inputId:root.inputId})).originalAcceptedBasis.verification).not.toBeNull();
});

test('two approved room bundles racing on the same expected head commit exactly one successor',async()=>{
 const a=await fixture.endpoint('UNIT'),old=await fixture.entry(a),created=await fixture.apply(await fixture.input([old])),id=created.facts[0]!.id,T='2027-10-01T00:00:00.000001',requests=[];
 for(let n=0;n<2;n++){const next=await fixture.entry({...a,location:await fixture.newLocation(a.campus.id)});next.row.valid_from=T;const end={...old,action:'END' as const,target:{owner:'location-master/location-use' as const,id,expectedHead:'1'},endAt:T,row:{...old.row,record_status:'RETIRED' as const}},data=await fixture.input([end,next]),member=await fixture.owner.stage('maker',data);await fixture.owner.verify('reviewer',fixture.verification(data,member));const root=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',cutover:T,policy:'TEST_POLICY_ONLY',reason:'TEST independently approved same-head contender',members:[{owner:'LOCATION_USE',...member,contractVersionId:fixture.contract!.versionId}]});await owner.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST original exact relation head and room window',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:root.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);requests.push({candidateId:candidate.candidateId,requestId});}
 const results=await Promise.allSettled(requests.map(request=>owner.applyUnit('maker',request)));expect(results.filter(r=>r.status==='fulfilled'&&r.value.status==='COMMITTED')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected'&&r.reason instanceof Error&&r.reason.message==='STALE_VALIDATION')).toHaveLength(1);expect((await fixture.owner.history('maker',{id})).versions).toHaveLength(2);for(const [index,result] of results.entries()){const outcome=await owner.resumeOutcome('maker',requests[index]!);if(result.status==='fulfilled')expect(outcome).toMatchObject({status:'COMMITTED'});else expect(outcome).toBeNull();}
});

test('a source relation accepted after bundle approval invalidates the frozen complete dependency set',async()=>{
 const a=await fixture.endpoint('UNIT'),unit=await fixture.base.owner.history('maker',{id:a.target.id}),target=await fixture.base.endpoint(unit.departmentId),T='2027-11-01T00:00:00.000001',f=unit.versions[0]!.facts,e=fixture.base.entry(target);if(e.action!=='CREATE')throw new Error('TEST_CREATE_REQUIRED');const rebind={...e,action:'REBIND' as const,target:{owner:'care-organization/unit' as const,id:unit.id,expectedHead:'1'},row:{...e.row,unit_id:f.source.sourceAlias,unit_code:f.unitCode,unit_name:f.unitName,unit_type:f.unitType,public_phone:f.publicPhone??'',service_description:f.serviceDescription??'',receiving_rule_ref:f.receivingRuleReference??'',valid_from:T}},data=await fixture.base.input([rebind]),member=await fixture.base.owner.stage('maker',data);await fixture.base.owner.verify('reviewer',fixture.base.verification(data,member));const root=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',cutover:T,policy:'TEST_POLICY_ONLY',reason:'TEST empty source dependencies at freeze',members:[{owner:'UNIT',...member,contractVersionId:fixture.base.contract!.versionId}]});await owner.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST independently checked complete original dependencies',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:root.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);
 const added=await fixture.apply(await fixture.input([await fixture.entry(a)]));await expect(owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId})).rejects.toThrow('STALE_VALIDATION');expect((await fixture.base.owner.history('maker',{id:unit.id})).versions).toHaveLength(1);expect((await fixture.owner.history('maker',{id:added.facts[0]!.id})).versions).toHaveLength(1);expect(await owner.resumeOutcome('maker',{candidateId:candidate.candidateId,requestId})).toBeNull();
});

test.each(['binding','successor'] as const)('AC04 failure at the target %s after a separate source END rolls back every Owner and receipt',async(boundary)=>{
 const a=await fixture.endpoint('UNIT'),old=await fixture.entry(a),created=await fixture.apply(await fixture.input([old])),oldId=created.facts[0]!.id,unit=await fixture.base.owner.history('maker',{id:a.target.id}),target=await fixture.base.endpoint(unit.departmentId),T='2028-02-01T00:00:00.000001',f=unit.versions[0]!.facts,e=fixture.base.entry(target);if(e.action!=='CREATE')throw new Error('TEST_CREATE_REQUIRED');const rebind={...e,action:'REBIND' as const,target:{owner:'care-organization/unit' as const,id:unit.id,expectedHead:'1'},row:{...e.row,unit_id:f.source.sourceAlias,unit_code:f.unitCode,unit_name:f.unitName,unit_type:f.unitType,public_phone:f.publicPhone??'',service_description:f.serviceDescription??'',receiving_rule_ref:f.receivingRuleReference??'',valid_from:T}},ui=await fixture.base.input([rebind]),us=await fixture.base.owner.stage('maker',ui);await fixture.base.owner.verify('reviewer',fixture.base.verification(ui,us));
 const end={...old,action:'END' as const,target:{owner:'location-master/location-use' as const,id:oldId,expectedHead:'1'},endAt:T,row:{...old.row,record_status:'RETIRED' as const}},next=await fixture.entry({...a,campus:target.campus,location:await fixture.newLocation(target.campus.id)});next.row.valid_from=T;const parts=[];for(const row of [end,next]){const data=await fixture.input([row]),input=await fixture.owner.stage('maker',data);await fixture.owner.verify('reviewer',fixture.verification(data,input));parts.push({owner:'LOCATION_USE' as const,...input,contractVersionId:fixture.contract!.versionId});}
 const root=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',cutover:T,policy:'TEST_POLICY_ONLY',reason:'TEST source END precedes target producer and successor',members:[parts[1]!,{owner:'UNIT',...us,contractVersionId:fixture.base.contract!.versionId},parts[0]!]});await owner.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST independent full source and target scopes',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:root.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);
 const table=boundary==='binding'?'care_organization.binding_version':'location_master.use_version',condition=boundary==='binding'?'NEW.number=1':"NEW.action='CREATE'",before=Client.prototype.query;let observed=false;
 peer(receipt.name,`CREATE FUNCTION care_organization.p3_11_target_fail() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF ${condition} THEN IF EXISTS(SELECT 1 FROM location_master.use_version WHERE use_id='${oldId}'::uuid AND action='END') THEN RAISE EXCEPTION 'TEST_TARGET_FAILURE_AFTER_SOURCE_END';ELSE RAISE EXCEPTION 'TEST_TARGET_FAILURE_BEFORE_SOURCE_END';END IF;END IF;RETURN NEW;END $$;CREATE TRIGGER p3_11_target_fail BEFORE INSERT ON ${table} FOR EACH ROW EXECUTE FUNCTION care_organization.p3_11_target_fail();`);
 Client.prototype.query=(function(this:Client,config:string|QueryConfig,...args:unknown[]){const value=Reflect.apply(before,this,[config,...args]);if(value&&typeof value.then==='function')return Promise.resolve(value).catch((error:unknown)=>{if(error instanceof Error&&error.message==='TEST_TARGET_FAILURE_AFTER_SOURCE_END')observed=true;throw error;});return value;}) as typeof before;
 try{await expect(owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId})).rejects.toThrow('APPLY_FAILED');expect(observed).toBe(true);}finally{Client.prototype.query=before;peer(receipt.name,`DROP TRIGGER p3_11_target_fail ON ${table};DROP FUNCTION care_organization.p3_11_target_fail();`);}
 expect((await fixture.owner.history('maker',{id:oldId})).versions).toHaveLength(1);expect((await fixture.base.owner.history('maker',{id:unit.id})).versions).toHaveLength(1);expect(await owner.resumeOutcome('maker',{candidateId:candidate.candidateId,requestId})).toBeNull();expect((await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId})).status).toBe('COMMITTED');expect(await owner.reconcileCommittedUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'MATCHED'});
});

test('Nursing rebind and room use require target current admission and preserve the Nursing identity',async()=>{
 const a=await fixture.endpoint('NURSING'),old=await fixture.entry(a),original=await fixture.apply(await fixture.input([old])),relationId=original.facts[0]!.id,h=await fixture.nursing.owner.history('maker',{id:a.target.id}),target=await fixture.nursing.endpoint(),T='2027-05-01T00:00:00.000001',facts=h.versions[0]!.facts,entry=fixture.nursing.entry(target);
 const rebind:NursingEntry={...entry,action:'REBIND',binding:target,target:{owner:'care-organization/nursing',id:h.id,expectedHead:'1'},row:{...entry.row,nursing_unit_id:facts.source.sourceAlias,nursing_code:facts.nursingCode,nursing_name:facts.nursingName,care_level:facts.careLevel,office_phone:facts.officePhone,valid_from:T}},data=await fixture.nursing.input([rebind]),member=await fixture.nursing.owner.stage('maker',data);await fixture.nursing.owner.verify('reviewer',fixture.nursing.verification(data,member));
 const room=await fixture.newLocation(target.campus.id),next=await fixture.entry({...a,campus:target.campus,location:room});next.row.valid_from=T;const end={...old,action:'END' as const,target:{owner:'location-master/location-use' as const,id:relationId,expectedHead:'1'},endAt:T,row:{...old.row,record_status:'RETIRED' as const}},spaceData=await fixture.input([end,next]),space=await fixture.owner.stage('maker',spaceData);await fixture.owner.verify('reviewer',fixture.verification(spaceData,space));
 const root=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',policy:'TEST_POLICY_ONLY',cutover:T,reason:'TEST exact Nursing and target-campus room move',members:[{owner:'LOCATION_USE',...space,contractVersionId:fixture.contract!.versionId},{owner:'NURSING',...member,contractVersionId:fixture.nursing.contract!.versionId}]});await owner.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST target department and full Nursing periods checked',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:root.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);const applied=await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId});expect(applied.status).toBe('COMMITTED');if(applied.status!=='COMMITTED')throw new Error('TEST_COMMITTED_REQUIRED');expect(applied.facts).toHaveLength(3);expect(await fixture.nursing.owner.read('maker',{id:h.id,businessAt:T})).toMatchObject({id:h.id,binding:{binding:target}});expect(await fixture.nursing.owner.read('maker',{id:h.id,businessAt:T,recordAsOf:h.versions[0]!.recordedAt})).toMatchObject({binding:{binding:{campus:a.campus}}});expect(await owner.reconcileCommittedUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'MATCHED'});
});

const differentFloor=async(campusId:string,roomId:string)=>{const room=await fixture.locations.owner.history('maker',{id:roomId}),floor=await fixture.locations.owner.history('maker',{id:room.versions[0]!.facts.parentId!}),parentId=floor.versions[0]!.facts.parentId!,created=await fixture.locations.apply(await fixture.locations.input(campusId,[{action:'CREATE',parent:{kind:'EXISTING',reference:{owner:'location-master',id:parentId}},row:fixture.locations.row(campusId,'FLOOR',randomUUID(),parentId),reason:'TEST distinct physical floor',evidenceId:fixture.locations.artifact.artifactId}]));expect(created.facts[0]!.id).not.toBe(floor.id);return created.facts[0]!.id;};

test('physical containment movement preserves Location and Unit identities and requires explicit disposition of the room use',async()=>{
 const a=await fixture.endpoint('UNIT'),old=await fixture.entry(a),created=await fixture.apply(await fixture.input([old])),oldId=created.facts[0]!.id,h=await fixture.locations.owner.history('maker',{id:a.location.id}),unit=await fixture.base.owner.history('maker',{id:a.target.id}),parentId=await differentFloor(a.campus.id,a.location.id),f=h.versions.at(-1)!.facts,T='2028-03-01T00:00:00.000001';
 const move={action:'MOVE_CONTAINMENT' as const,target:{owner:'location-master' as const,id:h.id,expectedVersion:h.versions.at(-1)!.number},parent:{kind:'EXISTING' as const,reference:{owner:'location-master' as const,id:parentId}},row:{...fixture.locations.row(a.campus.id,f.locationType,f.source.sourceAlias,parentId),location_code:f.locationCode,location_name:f.locationName,floor_label:f.floorLabel??'',room_number:f.roomNumber??'',address_detail:f.addressDetail??'',is_accessible:f.isAccessible??'',valid_from:T},reason:'TEST explicit physical parent adjustment',evidenceId:fixture.locations.artifact.artifactId},data=await fixture.locations.input(a.campus.id,[move]),native=await fixture.locations.owner.stage('maker',data);await fixture.locations.owner.verify('reviewer',{requestId:randomUUID(),inputId:native.inputId,inputDigest:native.digest,evidenceId:fixture.locations.artifact.artifactId,reason:'TEST independently checked physical parent and exact window',physicalFactsAccepted:true,policyVersion:'ORG12_CORE_V1'});
 const member={owner:'LOCATION' as const,...native,contractVersionId:fixture.locations.contract!.versionId};await expect(owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',cutover:T,policy:'TEST_POLICY_ONLY',reason:'TEST room usage disposition omitted',members:[member]})).rejects.toThrow('LIFECYCLE_DISPOSITION_INCOMPLETE');
 const end={...old,action:'END' as const,target:{owner:'location-master/location-use' as const,id:oldId,expectedHead:'1'},endAt:T,row:{...old.row,record_status:'RETIRED' as const}},ei=await fixture.input([end]),es=await fixture.owner.stage('maker',ei);await fixture.owner.verify('reviewer',fixture.verification(ei,es));const root=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',cutover:T,policy:'TEST_POLICY_ONLY',reason:'TEST explicit physical adjustment and old room-use END',members:[member,{owner:'LOCATION_USE',...es,contractVersionId:fixture.contract!.versionId}]});await owner.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST current physical impact set and source disposition',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:root.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);const result=await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId});expect(result.status).toBe('COMMITTED');expect(await fixture.base.owner.history('maker',{id:unit.id})).toEqual(unit);expect(await fixture.locations.owner.history('maker',{id:h.id})).toMatchObject({id:h.id,campusId:a.campus.id,versions:[...h.versions,expect.objectContaining({action:'MOVE_CONTAINMENT',facts:expect.objectContaining({parentId})})]});expect(await fixture.locations.owner.history('maker',{id:h.id,recordAsOf:h.versions[0]!.recordedAt})).toEqual(h);expect(await owner.reconcileCommittedUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'MATCHED'});
});

test('finite physical reparenting preserves an exact future room use outside its business window',async()=>{
 const a=await fixture.endpoint('UNIT'),use=await fixture.entry(a);use.row.valid_from='2030-01-01T00:00:00.000001';const created=await fixture.apply(await fixture.input([use])),id=created.facts[0]!.id,before=await fixture.owner.history('maker',{id}),h=await fixture.locations.owner.history('maker',{id:a.location.id}),f=h.versions.at(-1)!.facts,parentId=await differentFloor(a.campus.id,a.location.id),T='2028-03-01T00:00:00.000001',U='2029-03-01T00:00:00.000001';
 const move={action:'MOVE_CONTAINMENT' as const,target:{owner:'location-master' as const,id:h.id,expectedVersion:h.versions.at(-1)!.number},parent:{kind:'EXISTING' as const,reference:{owner:'location-master' as const,id:parentId}},row:{...fixture.locations.row(a.campus.id,f.locationType,f.source.sourceAlias,parentId),location_code:f.locationCode,location_name:f.locationName,floor_label:f.floorLabel??'',room_number:f.roomNumber??'',address_detail:f.addressDetail??'',is_accessible:f.isAccessible??'',valid_from:T,valid_to:U},reason:'TEST exact finite physical reparenting window',evidenceId:fixture.locations.artifact.artifactId},data=await fixture.locations.input(a.campus.id,[move]),native=await fixture.locations.owner.stage('maker',data);await fixture.locations.owner.verify('reviewer',{requestId:randomUUID(),inputId:native.inputId,inputDigest:native.digest,evidenceId:fixture.locations.artifact.artifactId,reason:'TEST exact finite containment and preserved later arrangements',physicalFactsAccepted:true,policyVersion:'ORG12_CORE_V1'});
 const root=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',cutover:T,policy:'TEST_POLICY_ONLY',reason:'TEST later room use falls outside physical impact interval',members:[{owner:'LOCATION',...native,contractVersionId:fixture.locations.contract!.versionId}]});await owner.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST exact physical command period and current impact set',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:root.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);expect((await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId})).status).toBe('COMMITTED');expect(await fixture.owner.history('maker',{id})).toEqual(before);expect(await fixture.locations.owner.read('maker',{id:h.id,businessAt:T})).toMatchObject({version:{facts:{parentId}}});expect(await fixture.locations.owner.read('maker',{id:h.id,businessAt:U})).toMatchObject({version:{facts:{parentId:f.parentId}}});expect(await owner.reconcileCommittedUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'MATCHED'});
});

test.each(['UNIT','WARD','NURSING'] as const)('AC03 %s suspension and permanent exit preserve occupied LocationUse history and report unfinished disposition',async(kind)=>{
 const a=await fixture.endpoint(kind),use=await fixture.entry(a),created=await fixture.apply(await fixture.input([use])),relationId=created.facts[0]!.id,before=await fixture.owner.history('maker',{id:relationId}),T='2028-04-01T00:00:00.000001',U='2028-05-01T00:00:00.000001';
 const stageLife=async(action:'SUSPEND'|'CLOSE',head:string,at:string)=>{
  const record_status=action==='SUSPEND'?'SUSPENDED' as const:'RETIRED' as const;
  if(kind==='UNIT'){const h=await fixture.base.owner.history('maker',{id:a.target.id}),source=await fixture.base.owner.readInput('maker',{inputId:h.versions[0]!.facts.source.recordLocatorEvidence.inputId}),entry=source.entries[0]!;if(entry.action!=='CREATE')throw new Error('TEST_CREATE_REQUIRED');const {binding:_,...accepted}=entry,data=await fixture.base.input([{...accepted,action,target:{owner:'care-organization/unit',id:h.id,expectedHead:head},row:{...entry.row,valid_from:at,record_status}}]),i=await fixture.base.owner.stage('maker',data);await fixture.base.owner.verify('reviewer',fixture.base.verification(data,i));return {...i,contractVersionId:fixture.base.contract!.versionId};}
  if(kind==='WARD'){const h=await fixture.wards.owner.history('maker',{id:a.target.id}),source=await fixture.wards.owner.readInput('maker',{inputId:h.versions[0]!.facts.source.recordLocatorEvidence.inputId}),entry=source.entries[0]!;if(entry.action!=='CREATE')throw new Error('TEST_CREATE_REQUIRED');const {binding:_,...accepted}=entry,data=await fixture.wards.input([{...accepted,action,target:{owner:'care-organization/ward',id:h.id,expectedHead:head},row:{...entry.row,valid_from:at,record_status}}]),i=await fixture.wards.owner.stage('maker',data);await fixture.wards.owner.verify('reviewer',fixture.wards.verification(data,i));return {...i,contractVersionId:fixture.wards.contract!.versionId};}
  const h=await fixture.nursing.owner.history('maker',{id:a.target.id}),source=await fixture.nursing.owner.readInput('maker',{inputId:h.versions[0]!.facts.source.recordLocatorEvidence.inputId}),entry=source.entries[0]!;if(entry.action!=='CREATE')throw new Error('TEST_CREATE_REQUIRED');const {binding:_,...accepted}=entry,data=await fixture.nursing.input([{...accepted,action,target:{owner:'care-organization/nursing',id:h.id,expectedHead:head},row:{...entry.row,valid_from:at,record_status}}]),i=await fixture.nursing.owner.stage('maker',data);await fixture.nursing.owner.verify('reviewer',fixture.nursing.verification(data,i));return {...i,contractVersionId:fixture.nursing.contract!.versionId};
 };
 for(const [action,head,at,state] of [['SUSPEND','1',T,'SUSPENDED'],['CLOSE','2',U,'CLOSED']] as const){const member=await stageLife(action,head,at),root=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'CLOSE',cutover:at,policy:'TEST_POLICY_ONLY',reason:'TEST identity lifecycle does not dispose the occupied relation',members:[{owner:kind,...member}]});await owner.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST independently checked retained relations and unfinished disposition',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:root.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);expect((await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId})).status).toBe('COMMITTED');expect(await fixture.owner.history('maker',{id:relationId})).toEqual(before);expect(await fixture.owner.history('maker',{id:relationId,recordAsOf:created.recordedAt})).toEqual(before);if(action==='SUSPEND'){const input={campus:'NORTH' as const,campusId:a.campus.id,businessAt:at};const listed=kind==='UNIT'?await fixture.base.owner.list('maker',input):kind==='NURSING'?await fixture.nursing.owner.list('maker',input):await fixture.wards.owner.list('maker',{...input,managingUnitId:(await fixture.wards.owner.history('maker',{id:a.target.id})).bindings[0]!.managingUnitId});expect(listed.items).toEqual(expect.arrayContaining([expect.objectContaining({id:a.target.id,state:'SUSPENDED'})]));} expect((await owner.history('maker',{inputId:root.inputId,businessAt:at})).currentDependencyReview.items).toEqual(expect.arrayContaining([expect.objectContaining({target:{kind,id:a.target.id},lifecycle:expect.objectContaining({state}),dispositionStatus:'OPEN',overallDisposition:'NOT_EVALUABLE'})]));}
});

test('an assembler can bind a separately identified native submitter while approval remains independent of both',async()=>{
 const a=await fixture.endpoint('UNIT'),entry=await fixture.entry(a),created=await fixture.apply(await fixture.input([entry])),id=created.facts[0]!.id,T='2027-06-01T00:00:00.000001',end={...entry,action:'END' as const,target:{owner:'location-master/location-use' as const,id,expectedHead:'1'},endAt:T,row:{...entry.row,record_status:'RETIRED' as const}},data=await fixture.input([end]);
 peer(receipt.name,"UPDATE vnext_control.actor SET identity_code='SYNTHETIC_P3_11_MEMBER' WHERE code='maker-alias';");
 peer(receipt.name,`INSERT INTO location_master.use_access SELECT 'maker-alias','${a.campus.id}'::uuid,'NORTH',p FROM unnest(ARRAY['VERIFY','REVIEW']) p ON CONFLICT DO NOTHING;`);
 try{
  const job=await catalog.importJobCommand('maker-alias',{action:'CREATE',requestId:randomUUID(),scope:'SYNTHETIC',reason:'TEST_INDEPENDENT_MEMBER',profile:'CORE',contractId:fixture.contract!.id,contractVersionId:fixture.contract!.versionId,input:{kind:'METADATA_ONLY',declaredSha256:'a'.repeat(64)}}),memberData={...data,jobId:job.id,revisionId:job.revisionId},member=await fixture.owner.stage('maker-alias',memberData);await fixture.owner.verify('reviewer',fixture.verification(memberData,member));
  const root=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'CLOSE',policy:'TEST_POLICY_ONLY',cutover:T,reason:'TEST root assembler differs from exact native maker',members:[{owner:'LOCATION_USE',...member,contractVersionId:fixture.contract!.versionId}]});await expect(owner.verify('maker-alias',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST member maker must not approve root',policy:'TEST_POLICY_ONLY'})).rejects.toThrow('MAKER_CHECKER_REQUIRED');await owner.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST independently checked both maker identities',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:root.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await expect(owner.approveApplyUnit('maker-alias',candidate)).rejects.toThrow('MAKER_CHECKER_REQUIRED');await owner.approveApplyUnit('reviewer',candidate);expect((await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId})).status).toBe('COMMITTED');expect(await owner.reconcileCommittedUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'MATCHED'});
 }finally{peer(receipt.name,"UPDATE vnext_control.actor SET identity_code='SYNTHETIC_MAKER' WHERE code='maker-alias';");}
});

test('AC01 actual room relocation changes only exact LocationUse relations through generated real HTTP and preserves Unit and physical history',async()=>{
 const a=await fixture.endpoint('UNIT'),entry=await fixture.entry(a,{kind:'EXCLUSIVE',version:'WHOLE_LOCATION_V1'}),created=await fixture.apply(await fixture.input([entry])),oldId=created.facts[0]!.id,unitBefore=await fixture.base.owner.history('maker',{id:a.target.id}),roomBefore=await fixture.locations.owner.history('maker',{id:a.location.id}),T='2027-01-01T00:00:00.000001',newRoom=await fixture.newLocation(a.campus.id);
 const end={...entry,action:'END' as const,target:{owner:'location-master/location-use' as const,id:oldId,expectedHead:'1'},endAt:T,row:{...entry.row,record_status:'RETIRED' as const}},next=await fixture.entry({...a,location:newRoom},{kind:'EXCLUSIVE',version:'WHOLE_LOCATION_V1'});next.row.valid_from=T;
 const data=await fixture.input([end,next]),staged=await fixture.owner.stage('maker',data);await fixture.owner.verify('reviewer',fixture.verification(data,staged));
 const root={requestId:randomUUID(),campus:'NORTH' as const,policy:'TEST_POLICY_ONLY' as const,kind:'MOVE' as const,cutover:T,reason:'TEST independently reviewed physical room move',members:[{owner:'LOCATION_USE' as const,...staged,contractVersionId:fixture.contract!.versionId}]},group=success(await maker.scheduleUnitMove(root));
 expect(success(await maker.scheduleUnitMove(root))).toEqual(group);expect((await maker.scheduleUnitMove({...root,reason:'TEST altered request payload'})).response.status).toBe(409);
 success(await reviewer.verify({requestId:randomUUID(),inputId:group.inputId,inputDigest:group.digest,reason:'TEST full room move independently checked',policy:'TEST_POLICY_ONLY'}));
 const preview=success(await maker.preview({inputId:group.inputId}));expect(preview.decision).toBe('PASS');expect(preview.changes[0]!.change.format).toBe('OWNER_BASIS_JSON_V1');const requestId=randomUUID(),candidate=success(await maker.plan({inputId:group.inputId,requestId})),review=success(await reviewer.review({candidateId:candidate.candidateId}));expect(review.unit.atomicRule).toBe('CARE_LOCATION_LIFECYCLE_V1');expect(review.unit.basis.members[0]!.unit.format).toBe('OWNER_BASIS_JSON_V1');expect(JSON.stringify(review)).not.toMatch(/ciphertext|nonce|envelope/);expect(success(await reviewer.approve(candidate)).approvedBy).toBe('reviewer');
 const request={candidateId:candidate.candidateId,requestId},result=success(await maker.apply(request));expect(result.status).toBe('COMMITTED');if(result.status!=='COMMITTED')throw new Error('TEST_COMMITTED_REQUIRED');expect(result.facts).toHaveLength(2);
 expect(success(await maker.apply(request))).toEqual(result);expect(success(await maker.resume(request))).toMatchObject({status:'COMMITTED',recordedAt:result.recordedAt,facts:result.facts});expect(success(await maker.reconcile(request)).status).toBe('MATCHED');
 const history=success(await maker.history({inputId:group.inputId}));expect(history).toMatchObject({originalAcceptedBasis:{inputDigest:group.digest,verification:{basis:{reason:'TEST full room move independently checked'}}},currentDependencyReview:{items:expect.arrayContaining([expect.objectContaining({target:{kind:'UNIT',id:a.target.id},lifecycle:expect.objectContaining({state:'ACTIVE'}),overallDisposition:'NOT_EVALUABLE'})])}});expect(JSON.stringify(history)).not.toMatch(/ciphertext|nonce|envelope/);
 expect(success(await maker.scheduleUnitMove(root))).toEqual(group);
 expect(await fixture.base.owner.history('maker',{id:a.target.id})).toEqual(unitBefore);expect(await fixture.locations.owner.history('maker',{id:a.location.id})).toEqual(roomBefore);
 expect(await fixture.owner.read('maker',{id:oldId,businessAt:T})).toMatchObject({state:'ENDED'});expect(await fixture.owner.read('maker',{id:result.facts[1]!.id,businessAt:T})).toMatchObject({state:'ACTIVE',applicability:{location:newRoom,target:a.target}});
 expect(await fixture.owner.read('maker',{id:oldId,businessAt:T,recordAsOf:created.recordedAt})).toMatchObject({state:'ACTIVE',applicability:{location:a.location}});
 const personnelWrite=(await pool.query("select coalesce(bool_or(has_table_privilege(current_user,c.oid,'INSERT,UPDATE,DELETE')),false) allowed from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind='r' and (n.nspname in ('person','personnel') or c.relname ~ '^(person_|personnel_|assignment_)')")).rows[0]!.allowed;expect(personnelWrite).toBe(false);
 const assessment=success(await maker.assessSpaceMove({target:{kind:'UNIT',id:a.target.id},validFrom:T,validTo:null}));expect(assessment).toMatchObject({unavailable:expect.arrayContaining([{owner:'PERSONNEL_ASSIGNMENT',status:'NOT_EVALUABLE'}])});
 expect((await createCareLocationLifecycleClient(runtime.url,'outsider').assessSpaceMove({target:{kind:'LOCATION',id:a.location.id},validFrom:T,validTo:null})).response.status).toBe(403);
});

test('Unit and Ward rebind with a target-campus room retain exact producer provenance and common R',async()=>{
 const a=await fixture.endpoint('WARD'),old=await fixture.entry(a),out=await fixture.apply(await fixture.input([old])),relationId=out.facts[0]!.id,ward=await fixture.wards.owner.history('maker',{id:a.target.id}),binding=ward.bindings[0]!.versions[0]!.binding,unit=await fixture.base.owner.history('maker',{id:binding.unit.id}),target=await fixture.base.endpoint(unit.departmentId),T='2027-04-01T00:00:00.000001';fixture.wards.grant(target.campus.id);
 const uf=unit.versions[0]!.facts,ue=fixture.base.entry(target);if(ue.action!=='CREATE')throw new Error('TEST_CREATE_REQUIRED');
 const u={...ue,action:'REBIND' as const,target:{owner:'care-organization/unit' as const,id:unit.id,expectedHead:'1'},row:{...ue.row,unit_id:uf.source.sourceAlias,unit_code:uf.unitCode,unit_name:uf.unitName,unit_type:uf.unitType,public_phone:uf.publicPhone??'',service_description:uf.serviceDescription??'',receiving_rule_ref:uf.receivingRuleReference??'',valid_from:T}},ui=await fixture.base.input([u]),us=await fixture.base.owner.stage('maker',ui);await fixture.base.owner.verify('reviewer',fixture.base.verification(ui,us));
 const wf=ward.versions[0]!.facts,we=fixture.wards.entry({unit:binding.unit,campus:target.campus}),w={...we,action:'REBIND' as const,binding:{unit:binding.unit,campus:target.campus},target:{owner:'care-organization/ward' as const,id:ward.id,expectedHead:'1'},row:{...we.row,ward_id:wf.source.sourceAlias,ward_code:wf.wardCode,ward_name:wf.wardName,ward_type:wf.wardType,public_phone:wf.publicPhone,admission_rule_ref:wf.admissionRuleReference,valid_from:T}},wi=await fixture.wards.input([w]),ws=await fixture.wards.owner.stage('maker',wi);await fixture.wards.owner.verify('reviewer',fixture.wards.verification(wi,ws));
 const room=await fixture.newLocation(target.campus.id),next=await fixture.entry({...a,campus:target.campus,location:room});next.row.valid_from=T;const end={...old,action:'END' as const,target:{owner:'location-master/location-use' as const,id:relationId,expectedHead:'1'},endAt:T,row:{...old.row,record_status:'RETIRED' as const}},li=await fixture.input([end,next]),ls=await fixture.owner.stage('maker',li);await fixture.owner.verify('reviewer',fixture.verification(li,ls));
 const input=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',policy:'TEST_POLICY_ONLY',cutover:T,reason:'TEST exact Unit Ward and room producer chain',members:[{owner:'LOCATION_USE',...ls,contractVersionId:fixture.contract!.versionId},{owner:'WARD',...ws,contractVersionId:fixture.wards.contract!.versionId},{owner:'UNIT',...us,contractVersionId:fixture.base.contract!.versionId}]});await owner.verify('reviewer',{requestId:randomUUID(),inputId:input.inputId,inputDigest:input.digest,reason:'TEST all exact producer inputs and source dispositions checked',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:input.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);const applied=await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId});expect(applied.status).toBe('COMMITTED');if(applied.status!=='COMMITTED')throw new Error('TEST_COMMITTED_REQUIRED');expect(applied.facts).toHaveLength(4);
 const wh=await fixture.wards.owner.history('maker',{id:ward.id}),uh=await fixture.base.owner.history('maker',{id:unit.id});expect(wh.versions.at(-1)!.recordedAt).toBe(applied.recordedAt);expect(uh.versions.at(-1)!.recordedAt).toBe(applied.recordedAt);expect(wh.bindings.at(-1)!.versions.at(-1)!.dependencies).not.toHaveProperty('kind','LIFECYCLE_CARE_INPUT');expect(await fixture.wards.owner.read('maker',{id:ward.id,businessAt:T})).toMatchObject({binding:{binding:{campus:target.campus}}});expect(await fixture.wards.owner.read('maker',{id:ward.id,businessAt:T,recordAsOf:ward.versions[0]!.recordedAt})).toMatchObject({binding:{binding:{campus:a.campus}}});
 expect(await owner.reconcileCommittedUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'MATCHED'});
});

test.each(['successor','audit','outcome','ack'] as const)('AC04 actual transaction and exact recovery at the %s boundary',async(failure)=>{
 const a=await fixture.endpoint('UNIT'),old=await fixture.entry(a),out=await fixture.apply(await fixture.input([old])),id=out.facts[0]!.id,T='2027-02-01T00:00:00',next=await fixture.entry({...a,location:await fixture.newLocation(a.campus.id)});next.row.valid_from=T;
 const end={...old,action:'END' as const,target:{owner:'location-master/location-use' as const,id,expectedHead:'1'},endAt:T,row:{...old.row,record_status:'RETIRED' as const}},data=await fixture.input([end,next]),staged=await fixture.owner.stage('maker',data);await fixture.owner.verify('reviewer',fixture.verification(data,staged));
 const grouped=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',policy:'TEST_POLICY_ONLY',cutover:T,reason:'TEST actual SQL successor rollback',members:[{owner:'LOCATION_USE',...staged,contractVersionId:fixture.contract!.versionId}]});await owner.verify('reviewer',{requestId:randomUUID(),inputId:grouped.inputId,inputDigest:grouped.digest,reason:'TEST exact relation switch independently reviewed',policy:'TEST_POLICY_ONLY'});
 const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:grouped.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);
 if(failure==='ack'){
  const original=Client.prototype.query;let pending=false,lost=false;
  Client.prototype.query=(function(this:Client,config:string|QueryConfig,...args:unknown[]){const text=typeof config==='string'?config:config.text,values=typeof config==='string'?(Array.isArray(args[0])?args[0]:[]):config.values??[],result=Reflect.apply(original,this,[config,...args]);if(result&&typeof result.then==='function')return Promise.resolve(result).then(value=>{if(text.includes('governance_catalog.apply_record')&&values.includes('COMMIT'))pending=true;if(pending&&text.trim().toLowerCase()==='commit'){pending=false;lost=true;throw new Error('TEST_COMMIT_ACK_LOST_AFTER_REAL_COMMIT');}return value;});return result;}) as typeof original;
  try{expect(await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'COMMIT_UNKNOWN'});}finally{Client.prototype.query=original;}
  expect(lost).toBe(true);expect((await fixture.owner.history('maker',{id})).versions).toHaveLength(2);expect(await owner.resumeOutcome('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'COMMITTED'});expect(await owner.reconcileCommittedUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'MATCHED'});expect((await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId})).status).toBe('COMMITTED');expect((await fixture.owner.history('maker',{id})).versions).toHaveLength(2);return;
 }
 const table=failure==='successor'?'location_master.use_version':failure==='audit'?'vnext_control.audit':'vnext_control.outcome',condition=failure==='successor'?"NEW.action='CREATE'":failure==='audit'?"NEW.action='LOCATION_USE_CREATE'":"NEW.result->>'status'='COMMITTED'";
 peer(receipt.name,`CREATE FUNCTION location_master.p3_11_fail() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF ${condition} THEN RAISE EXCEPTION 'TEST_INJECTED_SUCCESSOR_FAILURE';END IF;RETURN NEW;END $$;CREATE TRIGGER p3_11_fail BEFORE INSERT ON ${table} FOR EACH ROW EXECUTE FUNCTION location_master.p3_11_fail();`);
 try{await expect(owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId})).rejects.toThrow('APPLY_FAILED');}finally{peer(receipt.name,`DROP TRIGGER p3_11_fail ON ${table};DROP FUNCTION location_master.p3_11_fail();`);}
 expect((await fixture.owner.history('maker',{id})).versions).toHaveLength(1);expect(await owner.resumeOutcome('maker',{candidateId:candidate.candidateId,requestId})).toBeNull();expect((await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId})).status).toBe('COMMITTED');
});

test.each([{start:'2026-01-01T00:00:00',finish:null},{start:'2028-01-01T00:00:00.000001',finish:'2029-01-01T00:00:00.000001'}])('a Unit rebind and target-campus room use consume exact producer inputs in one approval and one transaction: %j',async({start,finish})=>{
 const a=await fixture.endpoint('UNIT'),old=await fixture.entry(a);old.row.valid_from=start;old.row.valid_to=finish;const out=await fixture.apply(await fixture.input([old])),relationId=out.facts[0]!.id,unit=await fixture.base.owner.history('maker',{id:a.target.id}),target=await fixture.base.endpoint(unit.departmentId),T='2027-03-01T00:00:00.000001';
 const accepted=unit.versions[0]!,entry=fixture.base.entry(target);if(entry.action!=='CREATE')throw new Error('TEST_CREATE_REQUIRED');
 const rebind={...entry,action:'REBIND' as const,target:{owner:'care-organization/unit' as const,id:unit.id,expectedHead:'1'},row:{...entry.row,unit_id:accepted.facts.source.sourceAlias,unit_code:accepted.facts.unitCode,unit_name:accepted.facts.unitName,unit_type:accepted.facts.unitType,public_phone:accepted.facts.publicPhone??'',service_description:accepted.facts.serviceDescription??'',receiving_rule_ref:accepted.facts.receivingRuleReference??'',valid_from:T}};
 const unitData=await fixture.base.input([rebind]),unitInput=await fixture.base.owner.stage('maker',unitData);await fixture.base.owner.verify('reviewer',fixture.base.verification(unitData,unitInput));
 const K=start>T?start:T;const room=await fixture.newLocation(target.campus.id),next=await fixture.entry({...a,campus:target.campus,location:room});next.row.valid_from=K;next.row.valid_to=finish;
 const end={...old,action:'END' as const,target:{owner:'location-master/location-use' as const,id:relationId,expectedHead:'1'},endAt:K,row:{...old.row,record_status:'RETIRED' as const}},data=await fixture.input([end,next]),space=await fixture.owner.stage('maker',data);await fixture.owner.verify('reviewer',fixture.verification(data,space));
 const grouped=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',policy:'TEST_POLICY_ONLY',cutover:T,reason:'TEST exact Unit producer and LocationUse consumer',members:[{owner:'LOCATION_USE',...space,contractVersionId:fixture.contract!.versionId},{owner:'UNIT',...unitInput,contractVersionId:fixture.base.contract!.versionId}]});
 await owner.verify('reviewer',{requestId:randomUUID(),inputId:grouped.inputId,inputDigest:grouped.digest,reason:'TEST all source and target scopes independently checked',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:grouped.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});
 if(start<T){
  for(const [table,campusId] of [['care_organization.access',a.campus.id],['location_master.use_access',target.campus.id]] as const){peer(receipt.name,`DELETE FROM ${table} WHERE actor='reviewer' AND campus_id='${campusId}'::uuid AND permission='REVIEW';`);try{await expect(owner.approveApplyUnit('reviewer',candidate)).rejects.toThrow('ACCESS_DENIED');}finally{peer(receipt.name,`INSERT INTO ${table} VALUES('reviewer','${campusId}'::uuid,'NORTH','REVIEW') ON CONFLICT DO NOTHING;`);}}
  peer(receipt.name,`DELETE FROM vnext_control.protected_grant WHERE actor_code='reviewer' AND dataset_id='${fixture.dataset.id}'::uuid AND campus='NORTH' AND purpose='IDENTITY_VERIFY' AND permission='READ';`);try{await expect(owner.approveApplyUnit('reviewer',candidate)).rejects.toThrow('ACCESS_DENIED');}finally{peer(receipt.name,`INSERT INTO vnext_control.protected_grant VALUES('reviewer','${fixture.dataset.id}'::uuid,'NORTH','IDENTITY_VERIFY','READ') ON CONFLICT DO NOTHING;`);}
 }
 await owner.approveApplyUnit('reviewer',candidate);
 if(start<T){peer(receipt.name,`DELETE FROM care_organization.access WHERE actor='reviewer' AND campus_id='${target.campus.id}'::uuid AND permission='VERIFY';`);try{await expect(owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId})).rejects.toThrow('ACCESS_DENIED');expect((await fixture.base.owner.history('maker',{id:unit.id})).versions).toHaveLength(1);}finally{peer(receipt.name,`INSERT INTO care_organization.access VALUES('reviewer','${target.campus.id}'::uuid,'NORTH','VERIFY') ON CONFLICT DO NOTHING;`);}}

 const applied=await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId});expect(applied.status).toBe('COMMITTED');if(applied.status!=='COMMITTED')throw new Error('TEST_COMMITTED_REQUIRED');expect(applied.facts).toHaveLength(3);
 expect(await fixture.base.owner.read('maker',{id:unit.id,businessAt:T})).toMatchObject({id:unit.id,departmentId:unit.departmentId,binding:{binding:{campus:target.campus}}});expect(await fixture.base.owner.read('maker',{id:unit.id,businessAt:T,recordAsOf:unit.versions[0]!.recordedAt})).toMatchObject({binding:{binding:{campus:a.campus}}});
 const successor=applied.facts.find(f=>f.owner==='location-master/location-use'&&f.id!==relationId)!;expect(await fixture.owner.read('maker',{id:successor.id,businessAt:K})).toMatchObject({state:'ACTIVE',applicability:{campus:target.campus,location:room}});expect(await owner.reconcileCommittedUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'MATCHED'});
});

test.each([false,true,'FINITE'] as const)('physical producer and exact same-room successor resolve the approved new graph regardless of member order: %s',async(useFirst)=>{
 const a=await fixture.endpoint('UNIT'),old=await fixture.entry(a),created=await fixture.apply(await fixture.input([old])),id=created.facts[0]!.id,h=await fixture.locations.owner.history('maker',{id:a.location.id}),f=h.versions.at(-1)!.facts,parentId=await differentFloor(a.campus.id,a.location.id),T='2028-06-01T00:00:00.000001';
 const move={action:'MOVE_CONTAINMENT' as const,target:{owner:'location-master' as const,id:h.id,expectedVersion:h.versions.at(-1)!.number},parent:{kind:'EXISTING' as const,reference:{owner:'location-master' as const,id:parentId}},row:{...fixture.locations.row(a.campus.id,f.locationType,f.source.sourceAlias,parentId),location_code:f.locationCode,location_name:f.locationName,floor_label:f.floorLabel??'',room_number:f.roomNumber??'',address_detail:f.addressDetail??'',is_accessible:f.isAccessible??'',valid_from:T,valid_to:useFirst==='FINITE'?'2029-06-01T00:00:00.000001':''},reason:'TEST exact physical producer',evidenceId:fixture.locations.artifact.artifactId},li=await fixture.locations.input(a.campus.id,[move]),ls=await fixture.locations.owner.stage('maker',li);await fixture.locations.owner.verify('reviewer',{requestId:randomUUID(),inputId:ls.inputId,inputDigest:ls.digest,evidenceId:fixture.locations.artifact.artifactId,reason:'TEST physical parent and source independently confirmed',physicalFactsAccepted:true,policyVersion:'ORG12_CORE_V1'});
 const end={...old,action:'END' as const,target:{owner:'location-master/location-use' as const,id,expectedHead:'1'},endAt:T,row:{...old.row,record_status:'RETIRED' as const}},next=await fixture.entry(a);next.row.valid_from=T;const ui=await fixture.input([end,next]),us=await fixture.owner.stage('maker',ui);await fixture.owner.verify('reviewer',fixture.verification(ui,us));
 const members=[{owner:'LOCATION' as const,...ls,contractVersionId:fixture.locations.contract!.versionId},{owner:'LOCATION_USE' as const,...us,contractVersionId:fixture.contract!.versionId}];if(useFirst===true)members.reverse();
 const root=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',cutover:T,policy:'TEST_POLICY_ONLY',reason:'TEST same-room explicit successor with exact physical producer',members});await owner.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST all exact source and successor dependencies independently checked',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:root.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);const result=await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId});expect(result.status).toBe('COMMITTED');if(result.status!=='COMMITTED')throw new Error('TEST_COMMITTED_REQUIRED');
 const successor=result.facts.find(v=>v.owner==='location-master/location-use'&&v.id!==id)!;const accepted=await fixture.owner.history('maker',{id:successor.id});const graph=JSON.stringify(accepted.versions[0]!.facts.dependencies);expect(graph).toContain(parentId);if(useFirst==='FINITE'){expect(graph).toContain(f.parentId!);expect(await fixture.locations.owner.read('maker',{id:h.id,businessAt:'2029-06-01T00:00:00.000001'})).toMatchObject({version:{facts:{parentId:f.parentId}}});}else expect(graph).not.toContain(f.parentId!);expect(graph).not.toContain('LIFECYCLE_LOCATION_INPUT');expect(accepted.versions[0]!.recordedAt).toBe(result.recordedAt);expect((await fixture.locations.owner.history('maker',{id:h.id})).versions.at(-1)!.recordedAt).toBe(result.recordedAt);expect(await fixture.owner.read('maker',{id,businessAt:T})).toMatchObject({state:'ENDED'});expect(await owner.reconcileCommittedUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'MATCHED'});
});

test('Nursing suspended and permanently closed attribution retains the last effective department and historical R after a rebind',async()=>{
 const first=await fixture.nursing.endpoint(),entry=fixture.nursing.entry(first);if(entry.action!=='CREATE')throw new Error('TEST_CREATE_REQUIRED');const created=await fixture.nursing.apply(await fixture.nursing.input([entry])),id=created.facts[0]!.id,second={...first,department:{owner:'department-master' as const,id:await fixture.nursing.newDepartment()}},T='2028-07-01T00:00:00.000001',U='2028-08-01T00:00:00.000001';
 await fixture.nursing.apply(await fixture.nursing.input([{...entry,action:'REBIND',target:{owner:'care-organization/nursing',id,expectedHead:'1'},binding:second,row:{...entry.row,managing_org_id:second.department.id,valid_from:T}}]));const {binding:_,...accepted}=entry;await fixture.nursing.apply(await fixture.nursing.input([{...accepted,action:'SUSPEND',target:{owner:'care-organization/nursing',id,expectedHead:'2'},row:{...entry.row,managing_org_id:second.department.id,valid_from:U,record_status:'SUSPENDED'}}]));
 expect(await fixture.nursing.owner.read('maker',{id,businessAt:U})).toMatchObject({state:'SUSPENDED',departmentId:second.department.id,binding:null});expect(await fixture.nursing.owner.read('maker',{id,businessAt:U,recordAsOf:created.recordedAt})).toMatchObject({state:'ACTIVE',departmentId:first.department.id});
 expect((await fixture.nursing.owner.list('maker',{campus:'NORTH',departmentId:second.department.id,businessAt:U})).items).toEqual(expect.arrayContaining([expect.objectContaining({id,departmentId:second.department.id})]));
 await fixture.nursing.apply(await fixture.nursing.input([{...accepted,action:'CLOSE',target:{owner:'care-organization/nursing',id,expectedHead:'3'},row:{...entry.row,managing_org_id:second.department.id,valid_from:'2028-09-01T00:00:00.000001',record_status:'RETIRED'}}]));
 expect(await fixture.nursing.owner.read('maker',{id,businessAt:'2028-09-01T00:00:00.000001'})).toMatchObject({state:'CLOSED',departmentId:second.department.id,binding:null});
});

test('permanent Nursing closure masks scheduled future attribution while old R keeps its exact binding',async()=>{
 const first=await fixture.nursing.endpoint(),entry=fixture.nursing.entry(first);if(entry.action!=='CREATE')throw new Error('TEST_CREATE_REQUIRED');const created=await fixture.nursing.apply(await fixture.nursing.input([entry])),id=created.facts[0]!.id,second=await fixture.nursing.endpoint(),T='2028-02-01T00:00:00.000001',future='2030-01-01T00:00:00.000001';
 await fixture.nursing.apply(await fixture.nursing.input([{...entry,action:'REBIND',target:{owner:'care-organization/nursing',id,expectedHead:'1'},binding:second,row:{...entry.row,campus_id:second.campus.id,managing_org_id:second.department.id,valid_from:future}}]));const before=await fixture.nursing.owner.history('maker',{id}),recordAsOf=before.versions.at(-1)!.recordedAt,{binding:_,...accepted}=entry;
 const data=await fixture.nursing.input([{...accepted,action:'CLOSE',target:{owner:'care-organization/nursing',id,expectedHead:'2'},row:{...entry.row,valid_from:T,record_status:'RETIRED'}}]),member=await fixture.nursing.owner.stage('maker',data);await fixture.nursing.owner.verify('reviewer',fixture.nursing.verification(data,member));
 const root=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'CLOSE',cutover:T,policy:'TEST_POLICY_ONLY',reason:'TEST permanent exit masks the earlier approved future attribution',members:[{owner:'NURSING',...member,contractVersionId:fixture.nursing.contract!.versionId}]});await owner.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST terminal state and retained original future evidence independently checked',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:root.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);expect((await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId})).status).toBe('COMMITTED');
 const filter={campus:'NORTH' as const,campusId:second.campus.id,departmentId:second.department.id,businessAt:future};expect((await fixture.nursing.owner.list('maker',filter)).items).not.toContainEqual(expect.objectContaining({id}));expect((await fixture.nursing.owner.list('maker',{...filter,recordAsOf})).items).toContainEqual(expect.objectContaining({id,state:'ACTIVE',departmentId:second.department.id}));expect((await fixture.nursing.owner.history('maker',{id})).bindings).toEqual(before.bindings);expect(await fixture.nursing.owner.read('maker',{id,businessAt:future})).toMatchObject({state:'CLOSED',binding:null});expect(await owner.reconcileCommittedUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'MATCHED'});
});

test('permanent Ward closure freezes the last effective cross-campus attribution and masks a later approved future campus',async()=>{
 const first=await fixture.wards.endpoint(),entry=fixture.wards.entry(first);if(entry.action!=='CREATE')throw new Error('TEST_CREATE_REQUIRED');const created=await fixture.wards.apply(await fixture.wards.input([entry])),id=created.facts[0]!.id,second=await fixture.wards.endpoint(),third=await fixture.wards.endpoint(),P='2027-02-01T00:00:00.000001',T='2028-02-01T00:00:00.000001',F='2030-02-01T00:00:00.000001';
 const apply=async(action:'REBIND'|'CLOSE',head:string,at:string,binding:typeof first)=>{const {binding:_,...accepted}=entry,target={owner:'care-organization/ward' as const,id,expectedHead:head},row={...entry.row,campus_id:binding.campus.id,managing_unit_id:binding.unit.id,valid_from:at,record_status:action==='CLOSE'?'RETIRED' as const:'ACTIVE' as const},native=action==='REBIND'?{...accepted,action,target,binding,row}:{...accepted,action,target,row},data=await fixture.wards.input([native]),member=await fixture.wards.owner.stage('maker',data);await fixture.wards.owner.verify('reviewer',fixture.wards.verification(data,member));const root=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:action==='CLOSE'?'CLOSE':'MOVE',cutover:at,policy:'TEST_POLICY_ONLY',reason:'TEST accurate terminal Ward attribution',members:[{owner:'WARD',...member,contractVersionId:fixture.wards.contract!.versionId}]});await owner.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST independent current source target and terminal binding check',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:root.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);expect((await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId})).status).toBe('COMMITTED');expect(await owner.reconcileCommittedUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'MATCHED'});};
 await apply('REBIND','1',P,second);await apply('REBIND','2',F,third);const before=await fixture.wards.owner.history('maker',{id}),recordAsOf=before.versions.at(-1)!.recordedAt;await apply('CLOSE','3',T,second);
 expect(await fixture.wards.owner.read('maker',{id,businessAt:F})).toMatchObject({state:'CLOSED',binding:null,campusId:second.campus.id});expect(await fixture.wards.owner.read('maker',{id,businessAt:F,recordAsOf})).toMatchObject({state:'ACTIVE',campusId:third.campus.id});expect((await fixture.wards.owner.list('maker',{campus:'NORTH',campusId:third.campus.id,businessAt:F})).items).not.toContainEqual(expect.objectContaining({id}));expect((await fixture.wards.owner.list('maker',{campus:'NORTH',businessAt:F})).items).toContainEqual(expect.objectContaining({id,state:'CLOSED',campusId:second.campus.id}));expect((await fixture.wards.owner.history('maker',{id})).bindings).toEqual(before.bindings);expect((await fixture.wards.owner.history('maker',{id})).campusId).toBe(first.campus.id);
});

test('an explicitly revalidated subtree preserves its room and floor identities under a legal building move',async()=>{
 const a=await fixture.endpoint('UNIT'),old=await fixture.entry(a),created=await fixture.apply(await fixture.input([old])),id=created.facts[0]!.id,room=await fixture.locations.owner.history('maker',{id:a.location.id}),floor=await fixture.locations.owner.history('maker',{id:room.versions[0]!.facts.parentId!}),building=await fixture.locations.owner.history('maker',{id:floor.versions[0]!.facts.parentId!}),campusParent=building.versions[0]!.facts.parentId!,T='2028-11-01T00:00:00.000001';
 const newBuilding=await fixture.locations.apply(await fixture.locations.input(a.campus.id,[{action:'CREATE',parent:{kind:'EXISTING',reference:{owner:'location-master',id:campusParent}},row:fixture.locations.row(a.campus.id,'BUILDING',randomUUID(),campusParent),reason:'TEST separate legal building',evidenceId:fixture.locations.artifact.artifactId}]));const newParent=newBuilding.facts[0]!.id;
 const moves=[{h:floor,parent:newParent},{h:room,parent:floor.id}].map(({h,parent})=>{const f=h.versions[0]!.facts;return {action:'MOVE_CONTAINMENT' as const,target:{owner:'location-master' as const,id:h.id,expectedVersion:'1'},parent:{kind:'EXISTING' as const,reference:{owner:'location-master' as const,id:parent}},row:{...fixture.locations.row(a.campus.id,f.locationType,f.source.sourceAlias,parent),location_code:f.locationCode,location_name:f.locationName,floor_label:f.floorLabel??'',room_number:f.roomNumber??'',address_detail:f.addressDetail??'',is_accessible:f.isAccessible??'',valid_from:T},reason:'TEST independently revalidate the preserved subtree identity',evidenceId:fixture.locations.artifact.artifactId};});
 const li=await fixture.locations.input(a.campus.id,moves),ls=await fixture.locations.owner.stage('maker',li);await fixture.locations.owner.verify('reviewer',{requestId:randomUUID(),inputId:ls.inputId,inputDigest:ls.digest,evidenceId:fixture.locations.artifact.artifactId,reason:'TEST all physical contributor versions independently revalidated',physicalFactsAccepted:true,policyVersion:'ORG12_CORE_V1'});
 const end={...old,action:'END' as const,target:{owner:'location-master/location-use' as const,id,expectedHead:'1'},endAt:T,row:{...old.row,record_status:'RETIRED' as const}},next=await fixture.entry(a);next.row.valid_from=T;const ui=await fixture.input([end,next]),us=await fixture.owner.stage('maker',ui);await fixture.owner.verify('reviewer',fixture.verification(ui,us));const root=await owner.stage('maker',{requestId:randomUUID(),campus:'NORTH',kind:'MOVE',cutover:T,policy:'TEST_POLICY_ONLY',reason:'TEST physical subtree and exact room use successor',members:[{owner:'LOCATION_USE',...us,contractVersionId:fixture.contract!.versionId},{owner:'LOCATION',...ls,contractVersionId:fixture.locations.contract!.versionId}]});await owner.verify('reviewer',{requestId:randomUUID(),inputId:root.inputId,inputDigest:root.digest,reason:'TEST accurate whole subtree dependency disposition',policy:'TEST_POLICY_ONLY'});const requestId=randomUUID(),candidate=await owner.plan('maker',{inputId:root.inputId,requestId});await owner.readApplyCandidate('reviewer',{candidateId:candidate.candidateId});await owner.approveApplyUnit('reviewer',candidate);const result=await owner.applyUnit('maker',{candidateId:candidate.candidateId,requestId});expect(result.status).toBe('COMMITTED');expect(await fixture.locations.owner.read('maker',{id:floor.id,businessAt:T})).toMatchObject({id:floor.id,version:{facts:{parentId:newParent}}});expect(await fixture.locations.owner.read('maker',{id:room.id,businessAt:T})).toMatchObject({id:room.id,version:{facts:{parentId:floor.id}}});expect(await fixture.locations.owner.history('maker',{id:room.id,recordAsOf:room.versions[0]!.recordedAt})).toEqual(room);expect(await owner.reconcileCommittedUnit('maker',{candidateId:candidate.candidateId,requestId})).toMatchObject({status:'MATCHED'});
});
