import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '../../..');
const START_HEAD = '3dcd9e018b6ffe2ca1c0c73cb4aada709de434f8';
const file = 'contracts/openapi/phase-01.openapi.json';
const before = JSON.parse(execFileSync('git', ['show', `${START_HEAD}:${file}`], { cwd: root, encoding: 'utf8', windowsHide: true }));
const bytes = readFileSync(resolve(root, file));
const after = JSON.parse(bytes.toString('utf8'));
const prefix = '/v1/phase-01/consumer-subscriptions/{subscriptionId}';
const added = `${prefix}/releases/{releaseId}/replay-context`;
assert.equal(before.paths[added], undefined);
assert.deepEqual(Object.keys(after.paths[added]), ['get']);
assert.deepEqual(after.paths[added].get.security, [{ serviceBearer: [] }]);
assert.equal(after.paths[added].get.operationId, 'getPhase01ConsumerReplayContext');
assert.equal(after.paths[added].get.responses[200].content['application/json'].schema.additionalProperties, false);
delete after.paths[added];
const snapshot = `${prefix}/snapshots/{snapshotId}/content`;
assert.deepEqual(after.paths[snapshot].get.parameters.filter((p: { in: string }) => p.in === 'query').map((p: { name: string }) => p.name), ['replayReleaseId']);
after.paths[snapshot].get.parameters = after.paths[snapshot].get.parameters.filter((p: { in: string }) => p.in !== 'query');
assert.ok(after.paths[snapshot].get.responses[400]); delete after.paths[snapshot].get.responses[400];
const receipt = after.paths[`${prefix}/receipts`].post.requestBody.content['application/json'].schema;
assert.equal(receipt.required.includes('replay'), false);
assert.equal(receipt.properties.replay.additionalProperties, false);
assert.deepEqual(receipt.properties.replay.required.sort(), ['operationId', 'reason', 'releaseId', 'subscriptionVersionId']);
delete receipt.properties.replay;
assert.deepEqual(after, before, 'C02_CHANGE_OUTSIDE_EXACT_REPLAY_CONTRACT');
const hash = createHash('sha256').update(bytes).digest('hex');
assert.equal(readFileSync(resolve(root, 'contracts/openapi/phase-01.openapi.sha256'), 'utf8').trim(), `${hash}  phase-01.openapi.json`);
console.log(JSON.stringify({ status: 'PASSED', START_HEAD, pathsAdded: 1, pathsModified: 2,
  componentsChanged: 0, departmentBrowserPathsChanged: 0, canonicalSnapshotSchemasChanged: 0, openapiSha256: hash }));
