import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join, resolve } from 'node:path';
import {
  ABG_COVERAGE_MATRIX,
  type AbgCoverageMatrixEntry,
  validateAbgCoverageMatrix,
} from './abg-coverage-matrix.js';
import { ABG_GATES } from './abg-catalog.js';

const repositoryRoot = resolve(import.meta.dirname, '../../..');
const reportPath = join(repositoryRoot, 'docs/design/phase-01-abg-evidence-coverage.md');
const code = String.fromCharCode(96);

export function renderAbgCoverageMarkdown(
  matrix: readonly AbgCoverageMatrixEntry[] = ABG_COVERAGE_MATRIX,
): string {
  validateAbgCoverageMatrix(matrix);
  const producerCounts = new Map<string, number>();
  for (const entry of matrix) {
    for (const producerId of entry.producerIds) {
      producerCounts.set(producerId, (producerCounts.get(producerId) ?? 0) + 1);
    }
  }

  const lines = [
    '# Phase 01 ABG Evidence Coverage',
    '',
    '<!-- Generated by npm run report:abg-coverage --workspace @hospital-data-intelligence/verification-tooling. Do not edit manually. -->',
    '',
    'This is a derived view of tooling/verification/src/abg-coverage-matrix.ts. It defines required coverage, not a formal ABG result.',
    '',
    '## Summary',
    '',
    '- Gates: ' + matrix.length,
    '- Gate-scoped assertions: ' + matrix.reduce((total, entry) => total + entry.assertionIds.length, 0),
    '- Distinct scenarios: ' + new Set(matrix.flatMap((entry) => entry.scenarioIds)).size,
    '- Distinct producers: ' + producerCounts.size,
    '- Required evidence selectors: ' + matrix.reduce((total, entry) => total + entry.evidenceSelectors.length, 0),
    '',
    '## Producer coverage',
    '',
    '| Producer | Gates requiring it |',
    '| --- | ---: |',
    ...[...producerCounts.entries()]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([producerId, count]) => '| ' + producerId + ' | ' + count + ' |'),
    '',
    '## Gate coverage',
  ];

  for (const entry of matrix) {
    const gate = ABG_GATES.find((candidate) => candidate.gateId === entry.gateId);
    if (!gate) throw new Error('ABG_COVERAGE_REPORT_GATE_UNKNOWN:' + entry.gateId);
    lines.push(
      '',
      '### ' + entry.gateId + ' — ' + gate.title,
      '',
      '- Evidence class: ' + entry.evidenceClass,
      '- Scenarios: ' + entry.scenarioIds.map((scenarioId) => code + scenarioId + code).join(', '),
      '- Gate-scoped assertions: ' + entry.assertionIds.map((assertionId) => code + assertionId + code).join(', '),
      '- Producers: ' + entry.producerIds.map((producerId) => code + producerId + code).join(', '),
      '- Required references: ' + entry.requiredReferenceKinds.map((kind) => code + kind + code).join(', '),
      '- Required frozen inputs: ' + entry.requiredFrozenInputs.map((kind) => code + kind + code).join(', '),
      '- Failure policy: ' + entry.failurePolicy.mode + '; every listed required condition fails closed.',
      '- Required selectors:',
    );
    for (const selector of entry.evidenceSelectors) {
      lines.push(
        '  - ' +
          code + selector.producerId + code + ' / ' + code + selector.artifactId + code + ' / ' +
          code + selector.scenarioId + code + ' / ' + code + selector.assertionId + code + ' / ' +
          code + selector.jsonPointer + code + ' / expected ' + code + selector.expectedStatus + code,
      );
    }
  }

  return lines.join('\n') + '\n';
}

async function main(): Promise<void> {
  const output = renderAbgCoverageMarkdown();
  const mode = process.argv.slice(2);
  if (mode.length === 0) {
    process.stdout.write(output);
    return;
  }
  if (mode.length !== 1 || (mode[0] !== '--write' && mode[0] !== '--check')) {
    throw new Error('ABG_COVERAGE_REPORT_USAGE');
  }
  if (mode[0] === '--write') {
    await writeFile(reportPath, output, 'utf8');
    return;
  }
  const existing = await readFile(reportPath, 'utf8');
  if (existing !== output) throw new Error('ABG_COVERAGE_REPORT_OUT_OF_DATE');
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
