import {intersect} from '../organization-master/index.js';
type Span={from:string;to:string|null};
import type {CapabilityHistory,CapabilityVersion} from './capability-contracts.js';
export function knownCapability(h:CapabilityHistory,r?:string):CapabilityHistory{return {...h,versions:h.versions.filter(v=>!r||v.recordedAt<=r)};}
export function declaration(h:CapabilityHistory){return h.versions.filter(v=>v.action==='GRANT'||v.action==='REVISE').at(-1)??null;}
export function capabilityEnd(h:CapabilityHistory){return h.versions.filter(v=>v.action==='END').map(v=>v.validFrom).sort()[0]??null;}
export function capabilityState(h:CapabilityHistory,at:string):'ACTIVE'|'DISABLED'|'SUSPENDED'|'ENDED'|'NOT_EFFECTIVE'{const d=declaration(h),end=capabilityEnd(h);if(end&&at>=end)return 'ENDED';if(!d||at<d.validFrom||(d.validTo!==null&&at>=d.validTo))return 'NOT_EFFECTIVE';let state:'ACTIVE'|'DISABLED'|'SUSPENDED'=d.facts.initiallyEnabled?'ACTIVE':'DISABLED';const events=h.versions.filter(v=>!['GRANT','REVISE','END'].includes(v.action)&&v.validFrom<=at).sort((a,b)=>a.validFrom.localeCompare(b.validFrom)||Number(BigInt(a.number)-BigInt(b.number)));for(const v of events)state=v.action==='SUSPEND'?'SUSPENDED':'ACTIVE';return state;}
export function capabilityReserved(h:CapabilityHistory):Span[]{const d=declaration(h);if(!d)return [];const end=capabilityEnd(h),to=d.validTo===null?end:end===null?d.validTo:d.validTo<end?d.validTo:end;return to!==null&&to<=d.validFrom?[]:[{from:d.validFrom,to}];}
export function capabilityPieces(h:CapabilityHistory,w:Span){const d=declaration(h);if(!d)return [] as Array<Span&{version:CapabilityVersion;state:ReturnType<typeof capabilityState>}>;const spans=capabilityReserved(h).flatMap(p=>intersect(p,w));return spans.flatMap(p=>{const bounds=[p.from,...h.versions.filter(v=>v.validFrom>p.from&&(p.to===null||v.validFrom<p.to)).map(v=>v.validFrom),...(p.to?[p.to]:[])].filter((v,i,a)=>a.indexOf(v)===i).sort();return bounds.flatMap((from,index)=>{const to=bounds[index+1]??p.to;return to===from?[]:[{from,to,version:d,state:capabilityState(h,from)}];});});}
