import {createCipheriv,createDecipheriv,createHmac,randomBytes,randomUUID} from 'node:crypto';
import {lifecycleCareInput,lifecycleCareBinding} from './lifecycle-care-inputs.js';
import {Kysely,PostgresDialect,sql} from 'kysely';
import {vnextPool} from '../../platform/database/vnext-pool.js';
import type {DB} from '../../platform/database/vnext-types.generated.js';
import {CatalogTransactionScope,applyCoordinator,canonicalPlan,planBinding,authenticateRegistrationEvidence,fileIntake,boundedParse,recordOwnerFileValidation,type ApplyOwnerPort,type OwnerFact,type ImportJob,type ImportContractItem,type KeyProviderPort,type ValidationEvaluation} from '../governance-catalog/index.js';
import {localTime,covered,intersect,subtract} from '../organization-master/index.js';
import {NursingId,NursingStoredStageSchema,NursingStageSchema,NursingInputSchema,NursingPlanSchema,NursingVerifySchema,NursingReceiveSchema,NursingHistorySchema,NursingReadSchema,NursingListSchema,NursingExactSchema,NursingWindowSchema,NursingDiffSchema,ORG09_FIELDS,nursingCheck,normalizeNursingRow,type NursingStage,type NursingStoredStage,type NursingVerification,type NursingReceive,type NursingHistory,type NursingFacts,type NursingWrite,type NursingIssue,type NursingUpstreamPorts,type NursingBindingInput} from './nursing-contracts.js';
import {nursingAt,nursingContentAt,nursingClosureBasis,nursingPeriods,knownNursing,bindingAt,declaredBindingAt,bindingHead,bindingPeriods} from './nursing-timeline.js';
import type {ImpactReference} from '../department-master/index.js';
import {nursingHandover} from './nursing-handover.js';
import {NursingHandoverConfirmSchema,type NursingHandoverConfirm,type NursingHandoverConfirmationBasis,type NursingHandoverBinding} from './nursing-handover-contracts.js';
import {careClosePoint,careState,careWindowOpen,careUnavailable} from './care-lifecycle-time.js';
type Scope=CatalogTransactionScope;
interface Envelope {keyId:string;nonce:string;tag:string;ciphertext:string}
interface InputRecord {id:string;revision:string;job_id:string;job_revision:string;identity_code:string;withdrawn?:boolean;digest:string;campus_ids:string[];scope:'NORTH'|'SOUTH';envelope:Envelope;verification:null|{id:string;number:string;actor:string;identity_code:string;digest:string;envelope:Envelope}}
type Staged={inputId:string;revisionId:string;digest:string};
const verificationCoversRows=(rows:NursingVerification['rows'],count:number)=>rows.length===count&&new Set(rows.map(v=>v.row)).size===count&&rows.every(v=>v.row>=1&&v.row<=count);

export function openNursingUnit(connection:string,provider:KeyProviderPort,ports:NursingUpstreamPorts,coverage?:{wardNursingCoveragesAvailable():boolean}){
 const handover=nursingHandover(provider);
 const db=new Kysely<DB>({dialect:new PostgresDialect({pool:vnextPool(connection)})});
 const root=<T>(work:(s:Scope)=>Promise<T>)=>db.transaction().execute(async trx=>{await sql`select pg_advisory_xact_lock(901002)`.execute(trx);return work(CatalogTransactionScope.from(trx));});
 const clock=async(s:Scope)=>(await sql<{v:string}>`select to_char(timezone('Asia/Shanghai',clock_timestamp()),'YYYY-MM-DD"T"HH24:MI:SS.US') v`.execute(s)).rows[0]!.v;
 const snapshot=async(s:Scope,actor:string,id:string,asOf?:string)=>(await (asOf?sql<{r:NursingHistory}>`select care_organization.nursing_snapshot_at(${actor},${id}::uuid,${localTime(asOf)}::timestamp) r`:sql<{r:NursingHistory}>`select care_organization.nursing_snapshot(${actor},${id}::uuid) r`).execute(s)).rows[0]!.r;
 const snapshotVersion=async(s:Scope,actor:string,id:string,version:string)=>(await sql<{r:NursingHistory}>`select care_organization.nursing_snapshot_version(${actor},${id}::uuid,${version}) r`.execute(s)).rows[0]!.r;
 const histories=async(s:Scope,actor:string,scope:string,asOf?:string)=>(await (asOf?sql<{r:NursingHistory[]}>`select care_organization.nursing_list_at(${actor},${scope},${localTime(asOf)}::timestamp) r`:sql<{r:NursingHistory[]}>`select care_organization.nursing_list(${actor},${scope}) r`).execute(s)).rows[0]!.r;
 const record=async(s:Scope,actor:string,id:string,permission='READ_RESTRICTED')=>(await sql<{r:InputRecord}>`select care_organization.nursing_input_read(${actor},${id}::uuid,${permission}) r`.execute(s)).rows[0]!.r;
 const inputJob=async(s:Scope,actor:string,id:string)=>(await sql<{r:ImportJob}>`select care_organization.nursing_job_read(${actor},${id}::uuid) r`.execute(s)).rows[0]!.r;
 const job=async(s:Scope,actor:string,id:string)=>(await sql<{r:ImportJob}>`select governance_catalog.import_job_read(${actor},${JSON.stringify({scope:'SYNTHETIC',jobId:id})}::jsonb) r`.execute(s)).rows[0]!.r;
 const authorize=async(s:Scope,actor:string,id:string,p:string)=>(await sql<{r:string}>`select care_organization.nursing_authorize(${actor},${id}::uuid,${p}) r`.execute(s)).rows[0]!.r;
 const sealed=(domain:string,value:unknown)=>{const digest=planBinding(provider,domain,value),{id,key}=provider.current(),nonce=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,nonce);cipher.setAAD(Buffer.from(domain+'\0'+digest));const bytes=Buffer.from(canonicalPlan(value));try{const ciphertext=Buffer.concat([cipher.update(bytes),cipher.final()]);return {digest,envelope:{keyId:id,nonce:nonce.toString('hex'),tag:cipher.getAuthTag().toString('hex'),ciphertext:ciphertext.toString('hex')}};}finally{bytes.fill(0);}};
 const unseal=<T>(domain:string,r:{digest:string;envelope:Envelope},schema:unknown):T=>{try{const e=r.envelope,d=createDecipheriv('aes-256-gcm',provider.payload(e.keyId),Buffer.from(e.nonce,'hex'));d.setAAD(Buffer.from(domain+'\0'+r.digest));d.setAuthTag(Buffer.from(e.tag,'hex'));const bytes=Buffer.concat([d.update(Buffer.from(e.ciphertext,'hex')),d.final()]);try{const value:unknown=JSON.parse(bytes.toString());nursingCheck(schema,value);if(planBinding(provider,domain,value)!==r.digest)throw new Error();return value as T;}finally{bytes.fill(0);}}catch{throw new Error('PAYLOAD_UNAVAILABLE');}};
 const recoverable=async<T>(s:Scope,work:()=>Promise<T>)=>{await sql`savepoint unit_dependency`.execute(s);try{const v=await work();await sql`release savepoint unit_dependency`.execute(s);return v;}catch(error){await sql`rollback to savepoint unit_dependency`.execute(s);await sql`release savepoint unit_dependency`.execute(s);throw error;}};
 const mutate=async<T>(s:Scope,actor:string,value:Record<string,unknown>):Promise<T>=>{const transaction=(await sql<{v:string}>`select pg_current_xact_id()::text v`.execute(s)).rows[0]!.v,ticket=canonicalPlan({...value,actor,transaction}),key=Buffer.from(planBinding(provider,'NURSING_SQL_AUTHORITY_V1',{}),'hex');try{return (await sql<{r:T}>`select care_organization.nursing_mutate(${ticket},${createHmac('sha256',key).update(ticket).digest('hex')}) r`.execute(s)).rows[0]!.r;}finally{key.fill(0);}};
 const material=async(s:Scope,actor:string,id:string,c:ImportContractItem,campus:string)=>{const proof=(await sql<{r:Parameters<typeof authenticateRegistrationEvidence>[0]}>`select governance_catalog.registration_evidence(${actor},${id}::uuid,${c.definition.sourceVersionId}::uuid,${campus}) r`.execute(s)).rows[0]!.r;const bytes=authenticateRegistrationEvidence(proof,provider);try{return {id,digest:planBinding(provider,'NURSING_EVIDENCE_V1',bytes.toString('base64'))};}finally{bytes.fill(0);}};
 const referenceAccess=async(s:Scope,actor:string,input:NursingStoredStage,c:ImportContractItem,extra:readonly string[]=[])=>{
  for(const entry of input.entries){if('binding' in entry)await ports.referenceAccess(s,actor,entry.binding);if('target' in entry){const h=await snapshotVersion(s,actor,entry.target.id,entry.target.expectedHead);for(const b of h.bindings)for(const v of b.versions)await ports.referenceAccess(s,actor,v.binding);}}
  for(const id of new Set(input.entries.map(e=>e.row.source_system_id)))await sql`select governance_catalog.nursing_source_reference(${actor},${id}::uuid,${c.definition.sourceVersionId}::uuid)`.execute(s);
  for(const id of new Set([...input.entries.map(e=>e.evidenceId),...(input.sourceArtifactId?[input.sourceArtifactId]:[]),...extra]))await sql`select governance_catalog.registration_evidence_access(${actor},${id}::uuid,${c.definition.sourceVersionId}::uuid,${input.campus})`.execute(s);
 };
 const stageIn=async(s:Scope,actor:string,input:NursingStoredStage)=>{const campusIds=new Set(input.entries.map(e=>e.row.campus_id));for(const e of input.entries)if('target' in e)for(const b of (await snapshot(s,actor,e.target.id)).bindings)campusIds.add(b.campusId);return mutate<Staged>(s,actor,{operation:'STAGE',requestId:input.requestId,jobId:input.jobId,revisionId:input.revisionId,campus:input.campus,campusIds:[...campusIds].sort(),...sealed('NURSING_INPUT_V1',input)});};
 const admission=(s:Scope,actor:string,b:NursingBindingInput,from:string,to:string|null,asOf:string)=>ports.admit(s,actor,{...b,validFrom:from,validTo:to,recordAsOf:asOf});
 const inspectInput=async(s:Scope,actor:string,id:string)=>{
  const r=await record(s,actor,id),input=unseal<NursingStoredStage>('NURSING_INPUT_V1',r,NursingStoredStageSchema),j=await inputJob(s,actor,id),c=j.contract,now=await clock(s),issues:NursingIssue[]=[],writes:NursingWrite[]=[],materials:Array<{id:string;digest:string}>=[],dependencies:unknown[]=[],original:NursingHistory[]=[];
  const issue=(row:number,field:string,code:string,status:NursingIssue['status']='FAIL')=>issues.push({row,field,code,status});
  if(r.withdrawn)throw new Error('INPUT_WITHDRAWN');if(j.currentRevisionId!==r.job_revision||j.status==='REJECTED')throw new Error('STALE_REVISION');
  await referenceAccess(s,actor,input,c);if(c.dataset!=='ORG09'||c.definition.templateVersion!=='ORG09_CORE_V1')throw new Error('BLOCKED_DEPENDENCY');
  if(input.profile!=='CORE'||j.profile!=='CORE')issue(0,'profile','BLOCKED_DEPENDENCY','BLOCKED');
  if(c.definition.fields.length!==15||!ORG09_FIELDS.every(field=>c.definition.fields.some(f=>f.code===field)))throw new Error('FULL_FIELD_OMISSION');
  if(input.timePolicy==='SOURCE_PLUS08_TO_LOCAL'&&!c.definition.rules.some(rule=>rule.id==='NURSING_SOURCE_PLUS08_V1'&&rule.status==='MACHINE'))throw new Error('BLOCKED_DEPENDENCY');
  const verification=r.verification?unseal<NursingVerification>('NURSING_VERIFICATION_V1',r.verification,NursingVerifySchema):null;
  if(!verification)issue(0,'verification','LEGAL_REVIEW_REQUIRED','BLOCKED');else{
   if(verification.inputDigest!==r.digest)throw new Error('STALE_VALIDATION');
   for(const id of r.campus_ids)if(await authorize(s,r.verification!.actor,id,'VERIFY')!==r.verification!.identity_code)throw new Error('ACCESS_DENIED');
   await referenceAccess(s,r.verification!.actor,input,c);
   if(!verificationCoversRows(verification.rows,input.entries.length))issue(0,'verification','VERIFICATION_ROW_MISMATCH');
  }
  const touched=new Set<string>(),aliases=new Set<string>();
  for(const [index,entry] of input.entries.entries())try{await recoverable(s,async()=>{
    const n=index+1,e=normalizeNursingRow(entry.row,input.timePolicy),target='target' in entry?entry.target:null,h=target?await snapshot(s,actor,target.id):null,head=h?.versions.at(-1),close=h&&entry.action==='CLOSE'?nursingClosureBasis(h,e.from):null;
    const at=h?(entry.action==='CLOSE'?close!.version:entry.action==='RESUME'?nursingContentAt(h,e.from):nursingAt(h,e.from)):null;
    const b=h?(entry.action==='CLOSE'?close!.binding:entry.action==='RESUME'?h.bindings.find(b=>bindingHead(b).validFrom<=e.from&&(bindingHead(b).validTo===null||e.from<bindingHead(b).validTo!)):bindingAt(h,e.from)):null;
   if(target){if(touched.has(target.id))throw new Error('BATCH_CONFLICT');touched.add(target.id);if(head?.number!==target.expectedHead)throw new Error('STALE_HEAD');if(h!.versions.some(v=>v.action==='CLOSE'))throw new Error('NURSING_CLOSED');if(entry.action==='SUSPEND'?careState(h!.versions,e.from)!=='ACTIVE':entry.action!=='RESUME'&&entry.action!=='CLOSE'&&!careWindowOpen(h!.versions,e.from,e.to))throw new Error('NURSING_SUSPENDED');original.push(h!);}
   else{if(aliases.has(e.row.nursing_unit_id))throw new Error('BATCH_CONFLICT');aliases.add(e.row.nursing_unit_id);if((await sql<{r:boolean}>`select care_organization.nursing_source_conflict(${actor},${e.row.source_system_id}::uuid,${e.row.nursing_unit_id}) r`.execute(s)).rows[0]!.r)throw new Error('NURSING_SOURCE_ALREADY_REGISTERED');}
   const closing=entry.action==='SUSPEND'||entry.action==='CLOSE',checked=verification?.rows.find(v=>v.row===n);
   if(verification&&(!checked||!checked.classificationAccepted))throw new Error('VERIFICATION_ROW_MISMATCH');
   const facts:NursingFacts={nursingCode:e.row.nursing_code,nursingName:e.row.nursing_name,careLevel:e.row.care_level||null,officePhone:e.row.office_phone||null,responsibilityStatus:'PENDING',source:{sourceAlias:e.row.nursing_unit_id,sourceVersion:e.row.version_no,sourceSystemId:e.row.source_system_id,sourceRecordedAt:e.sourceRecordedAt,recordLocatorEvidence:{inputId:r.id,row:input.sourceRows?.[index]??n},recordStatus:e.row.record_status,approvalReference:e.row.approval_ref},contractVersionId:c.versionId,managementBasis:checked?{verificationId:r.verification!.id,verificationVersion:String(r.verification!.number),inputDigest:r.digest}:null};
   if((await sql<{r:boolean}>`select care_organization.nursing_code_conflict(${actor},${facts.nursingCode},${target?.id??null}::uuid) r`.execute(s)).rows[0]!.r||writes.some(w=>w.key!==(target?.id??'alias:'+e.row.nursing_unit_id)&&w.facts.nursingCode===facts.nursingCode))throw new Error('NURSING_CODE_CONFLICT');
   materials.push(await material(s,actor,entry.evidenceId,c,r.scope));if(checked){materials.push(await material(s,actor,checked.evidenceId,c,r.scope));await material(s,r.verification!.actor,checked.evidenceId,c,r.scope);}
   const bindingChanges:NursingWrite['bindingChanges']=[];
   let bind:NursingBindingInput|null='binding' in entry?entry.binding:b?bindingHead(b).binding:null;
   if(bind&&(bind.department.id!==e.row.managing_org_id||bind.campus.id!==e.row.campus_id))throw new Error('NURSING_ANCHOR_MISMATCH');
   if(bind&&(await ports.referenceAccess(s,actor,bind)).scope!==r.scope)throw new Error('NURSING_ANCHOR_MISMATCH');
   if(!e.row.approval_ref.trim())throw new Error('BLOCKED_DEPENDENCY');
   const sameFacts=(basis:NursingFacts)=>{for(const key of ['nursingCode','nursingName','careLevel','officePhone'] as const)if(facts[key]!==basis[key])throw new Error('NURSING_CONTENT_CHANGED');};
   if(closing){
    if(!at||!b||e.to!==null||e.row.record_status!==(entry.action==='CLOSE'?'RETIRED':'SUSPENDED'))throw new Error('NURSING_SUSPENSION_EXPANSION');sameFacts(at.facts);facts.managementBasis=at.facts.managementBasis;
   }else{
    if(!e.row.approval_ref.trim()||e.row.record_status!=='ACTIVE')throw new Error('BLOCKED_DEPENDENCY');
    if(!covered([{from:c.validFrom,to:c.validTo}],e.from,e.to))throw new Error('BLOCKED_DEPENDENCY');
    const codes=c.definition.codeSets.find(x=>x.field==='record_status');if(!codes||codes.status!=='SYNTHETIC_ADOPTED'||!codes.codes.includes(e.row.record_status)||!covered([{from:codes.validFrom,to:codes.validTo}],e.from,e.to))throw new Error('BLOCKED_DEPENDENCY');
    await sql`select governance_catalog.nursing_source_reference(${actor},${e.row.source_system_id}::uuid,${c.definition.sourceVersionId}::uuid)`.execute(s);const source=(await sql<{r:unknown}>`select governance_catalog.nursing_source_coverage(${actor},${e.row.source_system_id}::uuid,${e.from}::timestamp,${e.to}::timestamp,${now}::timestamp) r`.execute(s)).rows[0]!.r;dependencies.push(source);
    if(!bind)throw new Error('NURSING_BINDING_REQUIRED');
    if(entry.action==='CREATE'){const deps=await admission(s,actor,bind,e.from,e.to,now);dependencies.push(deps);bindingChanges.push({id:null,expectedHead:null,validFrom:e.from,validTo:e.to,binding:bind,dependencies:deps});}
    else if(entry.action==='RESUME'){
     if(!at||!b||careState(h!.versions,e.from)!=='SUSPENDED'||!covered([{from:bindingHead(b).validFrom,to:bindingHead(b).validTo}],e.from,e.to))throw new Error('UNSUPPORTED_STATE_TRANSITION');sameFacts(at.facts);facts.managementBasis=at.facts.managementBasis;const deps=await admission(s,actor,bind,e.from,e.to,now);dependencies.push(deps);
    }else if(entry.action==='REBIND'){
     if(!b||!at||bindingHead(b).validFrom>=e.from)throw new Error('NURSING_REBIND_INVALID');sameFacts(at.facts);
     const prior=bindingHead(b),deps=await admission(s,actor,bind,e.from,e.to,now);dependencies.push(deps);
     bindingChanges.push({id:b.id,expectedHead:prior.number,validFrom:prior.validFrom,validTo:e.from,binding:prior.binding,dependencies:prior.dependencies},{id:null,expectedHead:null,validFrom:e.from,validTo:e.to,binding:bind,dependencies:deps});
    }else{
     if(!covered(nursingPeriods(h!),e.from,e.to))throw new Error('NURSING_PERIOD_NOT_COVERED');
     const pieces=h!.bindings.flatMap(prior=>intersect({from:bindingHead(prior).validFrom,to:bindingHead(prior).validTo},{from:e.from,to:e.to}).map(p=>({prior,...p})));
     if(!covered(pieces,e.from,e.to))throw new Error('NURSING_BINDING_REQUIRED');for(const part of pieces){const existing=bindingHead(part.prior).binding;if(existing.department.id!==e.row.managing_org_id||existing.campus.id!==e.row.campus_id)throw new Error('NURSING_ANCHOR_MISMATCH');const deps=await admission(s,actor,existing,part.from,part.to,now);dependencies.push(deps);}
    }
   }
   writes.push({key:target?.id??'alias:'+e.row.nursing_unit_id,targetId:target?.id??null,expectedHead:target?.expectedHead??null,action:entry.action,validFrom:e.from,validTo:e.to,facts,binding:bind,bindingChanges,reason:entry.reason,sourceRow:input.sourceRows?.[index]??n,scope:r.scope});
  });}catch(error){if(error instanceof Error&&['ACCESS_DENIED','KEY_UNAVAILABLE','PAYLOAD_UNAVAILABLE'].includes(error.message))throw error;issue(index+1,'',error instanceof Error?error.message:'CLOSED_INPUT_REQUIRED');}
  if(writes.some(w=>w.action!=='SUSPEND'&&w.action!=='CLOSE')){const active=(await sql<{r:ImportContractItem[]}>`select governance_catalog.contract_read(${actor},${JSON.stringify({scope:'SYNTHETIC',mode:'EFFECTIVE',target:c.id,businessAt:now})}::jsonb) r`.execute(s)).rows[0]!.r;if(active[0]?.versionId!==c.versionId)issue(0,'contract','STALE_VALIDATION','BLOCKED');}
  if(writes.reduce((count,w)=>count+1+w.bindingChanges.length,0)>100)issue(0,'entries','PLAN_INPUT_LIMIT');
  return {r,input,contract:c,verification,issues,writes,materials,dependencies,original};
 };
 const port:ApplyOwnerPort={
  async authorize(s,actor,input,p){const r=await record(s,actor,input.jobId,p);if(r.revision!==input.revisionId||r.scope!==input.campus||input.purpose!=='IDENTITY_VERIFY')throw new Error('ACCESS_DENIED');},
  async authorizeApproval(s,actor,input){const r=await record(s,actor,input.jobId,'REVIEW');for(const id of r.campus_ids)if(await authorize(s,actor,id,'REVIEW')===r.identity_code)throw new Error('MAKER_CHECKER_REQUIRED');},
  async authorizeFrozen(s,actor,unit){nursingCheck(NursingStoredStageSchema,unit.basis['input']);const materials=unit.basis['materials'],dependencies=unit.basis['dependencies'];if(!Array.isArray(materials)||!Array.isArray(dependencies))throw new Error('INVALID_PLAN_TOKEN');const ids=materials.map(m=>{nursingCheck(NursingId,m?.id);return m.id as string;});const j=await inputJob(s,actor,unit.input.jobId);await referenceAccess(s,actor,unit.basis['input'] as NursingStoredStage,j.contract,ids);for(const dependency of dependencies)if(dependency?.sourceId){nursingCheck(NursingId,dependency.sourceId);nursingCheck(NursingId,dependency.versionId);await sql`select governance_catalog.nursing_source_reference(${actor},${dependency.sourceId}::uuid,${dependency.versionId}::uuid)`.execute(s);}},
  async observe(s,actor,input){const v=await inspectInput(s,actor,input.jobId);if(!v.writes.length&&v.issues.length)throw new Error(v.issues[0]!.code);return {input,atomicRule:'ORG09_WHOLE_REVISION_V1',basis:{input:v.input,inputDigest:v.r.digest,contract:v.contract,verificationId:v.r.verification?.id??null,verificationDigest:v.r.verification?.digest??null,issues:v.issues,heads:v.original,materials:v.materials,dependencies:v.dependencies},commands:v.writes.map((w,index)=>({owner:'care-organization/nursing',row:index+1,intent:w.action==='CREATE'?'CREATE' as const:'REVISE' as const,target:w.targetId?{owner:'care-organization/nursing',id:w.targetId,version:w.expectedHead!}:null,aliases:[],value:{inputId:v.r.id,...(index===0?{writes:canonicalPlan(v.writes)}:{}),writeIndex:String(index+1),writesDigest:planBinding(provider,'NURSING_WRITES_V1',v.writes)}})),diff:v.writes.map(w=>({action:w.action,targetId:w.targetId,name:w.facts.nursingName,from:w.validFrom,to:w.validTo}))};},
  async validate(_s,_actor,unit,_stage){const issues=unit.basis['issues'] as NursingIssue[];if(issues.length||!unit.commands.length)throw new Error(issues[0]?.code??'BATCH_REJECTED');},
  async afterFreeze(s,actor,unit,c){const value=unit.commands[0]!.value;await mutate(s,actor,{operation:'FREEZE',inputId:value['inputId'],writes:JSON.parse(value['writes']!),writesDigest:value['writesDigest'],...c});},
  async apply(s,actor,command,_resolved,approval){return {ok:true,fact:await mutate<OwnerFact>(s,actor,{operation:'APPLY',inputId:command.value['inputId'],writes:JSON.parse(command.value['writes']??'[]'),writeIndex:Number(command.value['writeIndex']),writesDigest:command.value['writesDigest'],...approval})};},
  async exactRead(s,actor,_input,fact){if(fact.owner!=='care-organization/nursing')return null;return (await snapshotVersion(s,actor,fact.id,fact.version)).versions.some(v=>v.number===fact.version)?fact:null;},
 };
 const coordinator=applyCoordinator(db,provider,port),files=fileIntake(db,provider);
 const historyIn=async(s:Scope,actor:string,id:string,asOf?:string)=>{const h=knownNursing(await snapshot(s,actor,id,asOf),asOf);if(!h.versions.length)throw new Error('NOT_FOUND');return h;};
 const readIn=async(s:Scope,actor:string,input:{id:string;businessAt?:string;recordAsOf?:string})=>{const h=await historyIn(s,actor,input.id,input.recordAsOf),at=input.businessAt?localTime(input.businessAt):await clock(s),v=nursingAt(h,at),binding=declaredBindingAt(h,at),closedAt=careClosePoint(h.versions,at),affiliation=closedAt?h.bindings.filter(b=>localTime(bindingHead(b).validFrom)<closedAt).sort((a,b)=>bindingHead(a).validFrom.localeCompare(bindingHead(b).validFrom)).at(-1):binding;return {id:h.id,departmentId:affiliation?.versions.at(-1)?.binding.department.id??h.departmentId,head:h.versions.at(-1)!.number,state:v?'ACTIVE' as const:careState(h.versions,at)==='CLOSED'?'CLOSED' as const:careState(h.versions,at)==='SUSPENDED'?'SUSPENDED' as const:'NOT_EFFECTIVE' as const,version:v,binding:v&&binding?bindingHead(binding):null,clinicalReadiness:'NOT_READY' as const,reasons:['RESPONSIBILITY_NOT_IMPLEMENTED',coverage?.wardNursingCoveragesAvailable()?'NURSING_COVERAGE_INDEPENDENT_ASSESSMENT_REQUIRED':'NURSING_COVERAGE_NOT_IMPLEMENTED','CLINICAL_CAPABILITY_NOT_IMPLEMENTED','OPERATING_PERMISSION_NOT_EVALUABLE']};};
 return {
  lifecyclePort:port,
  lifecycleStateInTransaction:readIn,
  async lifecycleReferenceInTransaction(s:Scope,actor:string,inputId:string){const r=await record(s,actor,inputId);const j=await inputJob(s,actor,inputId);return {inputId:r.id,revisionId:r.revision,digest:r.digest,contractVersionId:j.contract.versionId,makerIdentity:r.identity_code,campus:r.scope};},
  async confirmCoverageHandover(actor:string,input:NursingHandoverConfirm){nursingCheck(NursingHandoverConfirmSchema,input);input=structuredClone(input);return root(s=>handover.confirm(s,actor,input));},
  readHandoverConfirmationInTransaction(s:Scope,actor:string,basis:NursingHandoverConfirmationBasis,expected:NursingHandoverBinding){return handover.read(s,actor,basis,expected);},
  async authorizeCoverageReferenceInTransaction(s:Scope,actor:string,input:{id:string;campusId:string}){await snapshot(s,actor,input.id);return (await sql<{r:{scope:'NORTH'|'SOUTH'}}>`select organization_master.campus_snapshot(${actor},${input.campusId}::uuid) r`.execute(s)).rows[0]!.r;},
  async evaluateCoverageWindowInTransaction(s:Scope,actor:string,input:{id:string;campusId:string;validFrom:string;validTo:string|null;recordAsOf:string}){const proposal=lifecycleCareInput(s,'NURSING',input);if(proposal){await historyIn(s,actor,input.id,input.recordAsOf);return proposal;}return (await sql<{r:unknown}>`select care_organization.ward_nursing_master_window(${actor},'NURSING',${input.id}::uuid,${input.campusId}::uuid,${localTime(input.validFrom)}::timestamp,${input.validTo===null?null:localTime(input.validTo)}::timestamp,${localTime(input.recordAsOf)}::timestamp) r`.execute(s)).rows[0]!.r;},
  async readCoverageBoundariesInTransaction(s:Scope,actor:string,input:{id:string;recordAsOf:string}){
   const h=await historyIn(s,actor,input.id,input.recordAsOf),points=[...h.versions.flatMap(v=>[v.validFrom,v.validTo]),...h.bindings.flatMap(b=>b.versions.flatMap(v=>[v.validFrom,v.validTo]))].filter((v):v is string=>v!==null);
   if(ports.boundaries)for(const b of h.bindings)for(const v of b.versions)points.push(...await ports.boundaries(s,actor,{...v.binding,validFrom:v.validFrom,validTo:v.validTo,recordAsOf:input.recordAsOf}));
   return {points,sourceIds:[...new Set(h.versions.map(v=>v.facts.source.sourceSystemId))],departmentWindows:bindingPeriods(h).map(p=>({id:bindingHead(p.binding).binding.department.id,from:p.from,to:p.to}))};
  },
  async readLocationUseBoundariesInTransaction(s:Scope,actor:string,input:{id:string;campusId:string;validFrom:string;validTo:string|null;recordAsOf:string}){
   nursingCheck(NursingId,input.campusId);nursingCheck(NursingWindowSchema,{id:input.id,validFrom:input.validFrom,validTo:input.validTo,recordAsOf:input.recordAsOf});
   const r=localTime(input.recordAsOf),requested={from:localTime(input.validFrom),to:input.validTo===null?null:localTime(input.validTo)};
   if(requested.to!==null&&requested.to<=requested.from)throw new Error('INVALID_BUSINESS_PERIOD');
   const proposal=lifecycleCareInput(s,'NURSING',input);if(proposal){await historyIn(s,actor,input.id,r);const b=lifecycleCareBinding(s,'NURSING',input.id);if(!b?.department)throw new Error('INVALID_PLAN_TOKEN');return {points:[proposal.validFrom,...(proposal.validTo?[proposal.validTo]:[])],departmentWindows:[{id:b.department.id,from:proposal.validFrom,to:proposal.validTo}]};}
   const h=await historyIn(s,actor,input.id,r),bindings=h.bindings.map(bindingHead),points=[...h.versions.flatMap(v=>[v.validFrom,v.validTo]),...bindings.flatMap(v=>[v.validFrom,v.validTo])].filter((v):v is string=>v!==null),
    sources=new Map<string,{id:string;from:string;to:string|null}>(),departments=new Map<string,{id:string;from:string;to:string|null}>();
   // Match ward_nursing_master_window: a later declaration masks the prior one
   // from its start permanently, including after a finite successor has ended.
   for(const property of h.versions.filter(v=>v.action==='CREATE'||v.action==='REVISE')){
    const periods=subtract({from:localTime(property.validFrom),to:property.validTo===null?null:localTime(property.validTo)},[...h.versions.filter(v=>(v.action==='CREATE'||v.action==='REVISE')&&BigInt(v.number)>BigInt(property.number)).map(v=>({from:localTime(v.validFrom),to:null})),...careUnavailable(h.versions)]);
    for(const period of periods)for(const binding of bindings)for(const overlap of intersect(period,{from:localTime(binding.validFrom),to:binding.validTo===null?null:localTime(binding.validTo)}))for(const part of intersect(overlap,requested)){
     if(binding.binding.campus.id!==input.campusId)throw new Error('CROSS_CAMPUS_POLICY_REQUIRED');
     points.push(part.from,...(part.to===null?[]:[part.to]));
     const source={id:property.facts.source.sourceSystemId,...part},department={id:binding.binding.department.id,...part};
     sources.set(JSON.stringify(source),source);departments.set(JSON.stringify(department),department);
    }
   }
   // Filter by the caller's B/R window before authorizing Source references.
   // Historical sources that contribute no interval must not deny this read.
   for(const source of sources.values()){
    const spans=(await sql<{r:Array<{from:string;to:string|null}>}>`select governance_catalog.use_source_windows(${actor},${source.id}::uuid,${source.from}::timestamp,${source.to}::timestamp,${r}::timestamp) r`.execute(s)).rows[0]!.r;
    points.push(...spans.flatMap(span=>[span.from,span.to]).filter((v):v is string=>v!==null));
   }
   return {points:[...new Set(points.map(localTime).filter(point=>point>=requested.from&&(requested.to===null||point<=requested.to)))].sort(),departmentWindows:[...departments.values()]};
  },
  async readDepartmentReferencesInTransaction(s:Scope,actor:string,ids:string[],campus:string){return (await sql<{r:ImpactReference[]}>`select care_organization.nursing_department_references(${actor},${JSON.stringify(ids)}::jsonb,${campus}) r`.execute(s)).rows[0]!.r;},
  async authorizeReferenceInTransaction(s:Scope,actor:string,ref:ImpactReference){await sql`select care_organization.nursing_reference_access(${actor},${JSON.stringify(ref)}::jsonb,'READ')`.execute(s);},
  async readCampusDependenciesInTransaction(s:Scope,actor:string,input:{id:string;validFrom:string;validTo:string|null;asOf?:string}){return (await sql<{r:Array<{owner:'NURSING_UNIT';id:string;version:string;active:boolean;outstanding:boolean}>}>`select care_organization.nursing_campus_dependencies(${actor},${input.id}::uuid,${localTime(input.validFrom)}::timestamp,${input.validTo===null?null:localTime(input.validTo)}::timestamp,${input.asOf?localTime(input.asOf):null}::timestamp) r`.execute(s)).rows[0]!.r;},
  async stage(actor:string,input:NursingStage){nursingCheck(NursingStageSchema,input);input=structuredClone(input);return root(s=>stageIn(s,actor,input));},
  async readInput(actor:string,input:{inputId:string}){nursingCheck(NursingInputSchema,input);return root(async s=>{const r=await record(s,actor,input.inputId),value=unseal<NursingStoredStage>('NURSING_INPUT_V1',r,NursingStoredStageSchema),j=await inputJob(s,actor,r.id);await referenceAccess(s,actor,value,j.contract);return value;});},
  async verify(actor:string,input:NursingVerification){nursingCheck(NursingVerifySchema,input);input=structuredClone(input);return root(async s=>{const r=await record(s,actor,input.inputId,'VERIFY'),j=await inputJob(s,actor,r.id),value=unseal<NursingStoredStage>('NURSING_INPUT_V1',r,NursingStoredStageSchema);if(!verificationCoversRows(input.rows,value.entries.length))throw new Error('VERIFICATION_ROW_MISMATCH');await referenceAccess(s,actor,value,j.contract);for(const row of input.rows){await material(s,actor,row.evidenceId,j.contract,r.scope);}return mutate<{verificationId:string}>(s,actor,{operation:'VERIFY',inputId:input.inputId,inputDigest:input.inputDigest,requestId:input.requestId,...sealed('NURSING_VERIFICATION_V1',input)});});},
  async preview(actor:string,input:{inputId:string}){nursingCheck(NursingInputSchema,input);return root(async s=>{const v=await inspectInput(s,actor,input.inputId);return {decision:v.issues.length?'BLOCKED' as const:'PASS' as const,issues:v.issues,changes:v.writes.map(w=>({action:w.action,targetId:w.targetId,name:w.facts.nursingName,validFrom:w.validFrom,validTo:w.validTo}))};});},
  async plan(actor:string,input:{inputId:string;requestId:string}){nursingCheck(NursingPlanSchema,input);const r=await root(s=>record(s,actor,input.inputId,'WRITE'));if(r.identity_code!==await root(s=>authorize(s,actor,r.campus_ids[0]!,'WRITE')))throw new Error('ACCESS_DENIED');return coordinator.planOwnerUnit(actor,{requestId:input.requestId,jobId:r.id,revisionId:r.revision,scope:'SYNTHETIC',campus:r.scope,purpose:'IDENTITY_VERIFY'});},
  readApplyCandidate:coordinator.readApplyCandidate,approveApplyUnit:coordinator.approveApplyUnit,applyUnit:coordinator.applyUnit,resumeOutcome:coordinator.resumeOutcome,reconcileCommittedUnit:coordinator.reconcileCommittedUnit,
  async withdraw(actor:string,input:{inputId:string;requestId:string}){nursingCheck(NursingPlanSchema,input);input=structuredClone(input);return root(async s=>{const transaction=(await sql<{v:string}>`select pg_current_xact_id()::text v`.execute(s)).rows[0]!.v,ticket=canonicalPlan({...input,actor,transaction}),key=Buffer.from(planBinding(provider,'NURSING_SQL_AUTHORITY_V1',{}),'hex');try{return (await sql<{r:{inputId:string;status:'WITHDRAWN'}}> `select care_organization.nursing_withdraw(${ticket},${createHmac('sha256',key).update(ticket).digest('hex')}) r`.execute(s)).rows[0]!.r;}finally{key.fill(0);}});},
  async history(actor:string,input:{id:string;recordAsOf?:string}){nursingCheck(NursingHistorySchema,input);return root(s=>historyIn(s,actor,input.id,input.recordAsOf));},
  async read(actor:string,input:{id:string;businessAt?:string;recordAsOf?:string}){nursingCheck(NursingReadSchema,input);return root(s=>readIn(s,actor,input));},
  async exact(actor:string,input:{id:string;version:string;recordAsOf?:string}){nursingCheck(NursingExactSchema,input);return root(async s=>{const h=await snapshotVersion(s,actor,input.id,input.version);if(input.recordAsOf&&h.versions.at(-1)!.recordedAt>localTime(input.recordAsOf))throw new Error('NOT_FOUND');const v=h.versions.find(v=>v.number===input.version);if(!v)throw new Error('NOT_FOUND');return v;});},
  async diff(actor:string,input:{id:string;fromVersion:string;toVersion:string}){nursingCheck(NursingDiffSchema,input);return root(async s=>{const h=await historyIn(s,actor,input.id),before=h.versions.find(v=>v.number===input.fromVersion),after=h.versions.find(v=>v.number===input.toVersion);if(!before||!after)throw new Error('NOT_FOUND');return {id:h.id,before,after};});},
  async list(actor:string,input:{campus:'NORTH'|'SOUTH';campusId?:string;departmentId?:string;after?:string;limit?:number;businessAt?:string;recordAsOf?:string}){nursingCheck(NursingListSchema,input);return root(async s=>{const at=input.businessAt?localTime(input.businessAt):await clock(s),all=(await histories(s,actor,input.campus,input.recordAsOf)).map(h=>knownNursing(h,input.recordAsOf)).filter(h=>h.versions.length&&(!input.departmentId||declaredBindingAt(h,at)?.versions.at(-1)?.binding.department.id===input.departmentId)&&(!input.after||h.id>input.after)&&(!input.campusId||declaredBindingAt(h,at)?.campusId===input.campusId)),page=all.slice(0,input.limit??50);return {items:await Promise.all(page.map(h=>readIn(s,actor,{id:h.id,businessAt:at,...(input.recordAsOf?{recordAsOf:input.recordAsOf}:{})}))),nextAfterId:all.length>page.length?page.at(-1)!.id:null};});},
  async coverage(actor:string,input:{id:string;validFrom:string;validTo:string|null;recordAsOf?:string}){nursingCheck(NursingWindowSchema,input);return root(async s=>{const h=await historyIn(s,actor,input.id,input.recordAsOf),from=localTime(input.validFrom),to=input.validTo===null?null:localTime(input.validTo);if(to!==null&&to<=from)throw new Error('INVALID_BUSINESS_PERIOD');const parts=nursingPeriods(h).flatMap(p=>intersect(p,{from,to}).map(span=>({...span,version:p.version.number,versionId:p.version.id})));return {id:h.id,covered:covered(parts,from,to),parts,clinicalReadiness:'NOT_READY' as const};});},
  async evaluateWindow(actor:string,input:{id:string;validFrom:string;validTo:string|null;recordAsOf?:string}){nursingCheck(NursingWindowSchema,input);return root(async s=>{const h=await historyIn(s,actor,input.id,input.recordAsOf),from=localTime(input.validFrom),to=input.validTo===null?null:localTime(input.validTo),asOf=input.recordAsOf?localTime(input.recordAsOf):await clock(s);if(to!==null&&to<=from)throw new Error('INVALID_BUSINESS_PERIOD');const checks=[];for(const part of bindingPeriods(h))for(const p of intersect(part,{from,to})){const b=part.binding;try{const basis=await recoverable(s,()=>admission(s,actor,bindingHead(b).binding,p.from,p.to,asOf)),property=nursingAt(h,p.from)!,source=await recoverable(s,async()=> (await sql<{r:unknown}>`select governance_catalog.nursing_source_coverage(${actor},${property.facts.source.sourceSystemId}::uuid,${p.from}::timestamp,${p.to}::timestamp,${asOf}::timestamp) r`.execute(s)).rows[0]!.r);checks.push({from:p.from,to:p.to,status:'SATISFIED' as const,basis,source});}catch(error){if(error instanceof Error&&error.message==='ACCESS_DENIED')throw error;checks.push({from:p.from,to:p.to,status:'NOT_SATISFIED' as const,reason:error instanceof Error?error.message:'BLOCKED_DEPENDENCY'});}}return {id:h.id,coreCovered:covered(nursingPeriods(h),from,to),checks,clinicalReadiness:'NOT_READY' as const,responsibility:'NOT_EVALUABLE' as const,clinicalCapability:'NOT_EVALUABLE' as const};});},
  async receiveFile(actor:string,input:NursingReceive,bytes:Uint8Array){
   nursingCheck(NursingReceiveSchema,input);input=structuredClone(input);if(input.job.input.kind!=='FILE'||input.job.input.parserPolicy!=='STRICT_NURSING_V1'||!(bytes instanceof Uint8Array)||bytes.length<1||bytes.length>1048576)throw new Error('CLOSED_FILE_REQUIRED');const privateBytes=Buffer.from(bytes);
   try{const received=await files.receiveFile(actor,{job:input.job,fileRequestId:input.fileRequestId,extension:input.job.input.format==='CSV'?'.csv':input.job.input.format==='JSON'?'.json':'.xlsx',campus:input.campus,purpose:'IDENTITY_VERIFY',retentionSeconds:input.retentionSeconds},privateBytes);return await root(async s=>{const j=await job(s,actor,received.job.id),parsed=await boundedParse(privateBytes,input.job.input.kind==='FILE'?input.job.input.format:'JSON',j.contract.definition.fields,'STRICT_NURSING_V1'),issues:NursingIssue[]=parsed.issues.map(i=>({row:i.row,field:ORG09_FIELDS[i.column-1]??'',code:i.code,status:'FAIL'}));let staged:Staged|null=null;if(parsed.structuralStatus==='PARSED'&&parsed.rows.length===input.operations.length&&!issues.length){try{const value={requestId:input.requestId,jobId:j.id,revisionId:j.currentRevisionId,campus:input.campus,profile:j.profile,timePolicy:input.timePolicy,entries:input.operations.map((operation,index)=>({...operation,row:parsed.rows[index]!})),sourceArtifactId:received.artifact.artifactId,sourceRows:parsed.rows.map((_,index)=>parsed.cells.find(c=>c.row===index+1)?.sourceRow??index+2)};nursingCheck(NursingStoredStageSchema,value);staged=await recoverable(s,()=>stageIn(s,actor,value as NursingStoredStage));}catch(error){if(error instanceof Error&&error.message==='ACCESS_DENIED')throw error;issues.push({row:0,field:'',code:error instanceof Error?error.message:'CLOSED_INPUT_REQUIRED',status:'FAIL'});}}else if(parsed.rows.length!==input.operations.length)issues.push({row:0,field:'operations',code:'BATCH_CONFLICT',status:'FAIL'});const evaluation:ValidationEvaluation={decision:issues.length?'FAIL':'BLOCKED',issues:issues.length?issues.map(i=>({rule:'ORG09_'+i.code,layer:2,row:i.row,field:i.field,status:'FAIL',code:i.code})):[{rule:'ORG09_RECEIVING_REVIEW',layer:7,row:0,field:'',status:'UNKNOWN',code:'LEGAL_REVIEW_REQUIRED'}],layers:[{layer:1,status:parsed.structuralStatus==='PARSED'?'PASS':'FAIL'},{layer:2,status:issues.length?'FAIL':'UNKNOWN'}],evidenceRequirements:[],dependencies:[],interpretationPolicy:'EXACT_TEXT_V1'};const validation=await recordOwnerFileValidation(s,provider,actor,{jobId:j.id,revisionId:j.currentRevisionId,sourceArtifactId:received.artifact.artifactId,campus:input.campus,requestId:randomUUID(),parseRequestId:randomUUID(),outputRequestId:randomUUID(),contractVersionId:j.contract.versionId,ruleVersion:j.contract.definition.ruleVersion,parserPolicy:'STRICT_NURSING_V1',structuralStatus:parsed.structuralStatus,parsed:{sourceArtifactId:received.artifact.artifactId,result:parsed},evaluation});return {jobId:j.id,revisionId:j.currentRevisionId,sourceArtifactId:received.artifact.artifactId,structuralStatus:parsed.structuralStatus,input:staged,issues,validation};});}finally{privateBytes.fill(0);}
  },
  async close(){await db.destroy();},
 };
}
export type NursingUnitOwner=ReturnType<typeof openNursingUnit>;
