/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 完成服务端OIDC代码交换并建立不透明会话 */
        get: operations["completeBrowserLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 启动服务端Authorization Code与PKCE S256登录 */
        get: operations["beginBrowserLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤销当前服务端会话 */
        post: operations["logoutBrowserSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取当前服务端会话和CSRF请求令牌 */
        get: operations["getBrowserSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 检查治理 API 进程健康状态 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/phase-01/charge-item-publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发布 Phase 01 收费项目版本和规范快照 */
        post: operations["publishPhase01ChargeItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/phase-01/consumer-subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 建立精确投影契约的仿真消费者订阅 */
        post: operations["createPhase01ConsumerSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/phase-01/consumer-subscriptions/{subscriptionId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按对象内版本顺序查询可消费发布事件 */
        get: operations["listPhase01ConsumerEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/phase-01/consumer-subscriptions/{subscriptionId}/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 记录仿真消费者校验应用回执并推进检查点 */
        post: operations["recordPhase01ConsumerReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/phase-01/consumer-subscriptions/{subscriptionId}/replays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 在新支持版本生效后受控恢复原事件与原快照投递 */
        post: operations["replayPhase01BlockedConsumerDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/phase-01/consumer-subscriptions/{subscriptionId}/snapshots/{snapshotId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载完整且不可分段的规范快照字节 */
        get: operations["downloadPhase01CanonicalSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/phase-01/consumer-subscriptions/{subscriptionId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 以不可变新版本更新消费者精确投影支持声明 */
        post: operations["createPhase01ConsumerSubscriptionVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/phase-01/price-list-publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发布 Phase 01 完整价表版本和规范快照 */
        post: operations["publishPhase01PriceList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/phase-01/price-resolutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 按服务发生时点执行 Phase 01 价格解析 */
        post: operations["resolvePhase01Price"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChargeCatalogProjectionV1 */
        "def-0": {
            catalogCode: string;
            items: {
                billingUnitCode: string;
                /** @enum {string} */
                businessStatus: "ACTIVE";
                businessValidFrom: string;
                businessValidTo: string | null;
                chargeItemId: string;
                chargeItemVersionId: string;
                chargingMethodCode: string;
                contentHash: string;
                formalName: string;
                internalCode: string;
                recordedFrom: string;
                serviceDefinition: string;
                versionNo: string;
            }[];
        };
        /** PriceListProjectionV0 */
        "def-1": {
            legacyEntries: {
                itemCode: string;
                unitPrice: string;
            }[];
            priceListCode: string;
            priceListId: string;
        };
        /** PriceListProjectionV1 */
        "def-2": {
            businessValidFrom: string;
            businessValidTo: string | null;
            contentHash: string;
            currencyCode: string;
            displayName: string;
            entries: {
                billingUnitCode: string;
                businessValidFrom: string;
                businessValidTo: string | null;
                campusId: string | null;
                chargeItemId: string;
                chargeItemInternalCode: string;
                chargeItemVersionId: string;
                contentHash: string;
                currencyCode: string;
                encounterMode: "GENERAL" | "SPECIFIC";
                encounterType: "OUTPATIENT" | "INPATIENT" | "EMERGENCY" | "CHECKUP" | null;
                entryNo: string;
                fixedUnitPrice: string;
                priceEntryId: string;
                priceNature: "HOSPITAL_DEFAULT" | "CAMPUS_DIFFERENCE";
                scopeLevel: "HOSPITAL" | "CAMPUS";
                zeroPriceReason: string | null;
            }[];
            priceListCode: string;
            priceListId: string;
            priceListReleaseId: string;
            recordedFrom: string;
            releaseNo: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    completeBrowserLogin: {
        parameters: {
            query: {
                code: string;
                state: string;
                iss?: string;
                session_state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
        };
    };
    beginBrowserLogin: {
        parameters: {
            query?: {
                returnTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
        };
    };
    logoutBrowserSession: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        loggedOut: true;
                    };
                };
            };
            /** @description Default Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
        };
    };
    getBrowserSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        csrfToken: string;
                        principalId: string;
                        /** @enum {string} */
                        principalKind: "PERSON";
                    };
                };
            };
            /** @description Default Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
    publishPhase01ChargeItem: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    billingUnitCode: string;
                    businessValidFrom: string;
                    businessValidTo: string | null;
                    catalogCode: string;
                    changeReason: string;
                    chargingMethodCode: string;
                    formalName: string;
                    governanceObjectId: string;
                    internalCode: string;
                    serviceDefinition: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        eventId: string;
                        releaseId: string;
                        snapshotId: string;
                        stableId: string;
                        versionId: string;
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
        };
    };
    createPhase01ConsumerSubscription: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    governanceObjectId: string;
                    projectionSchemaVersion: "0" | "1";
                    /** @enum {string} */
                    projectionType: "hdi.price-list";
                    servicePrincipalId: string;
                    subscriptionCode: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subscriptionId: string;
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
        };
    };
    listPhase01ConsumerEvents: {
        parameters: {
            query?: {
                afterAggregateVersion?: string;
            };
            header?: never;
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events: {
                            aggregateVersion: string;
                            eventId: string;
                            governanceObjectId: string;
                            projectionPayloadDigest: string;
                            projectionSchemaDigest: string;
                            projectionSchemaVersion: string;
                            projectionType: string;
                            releaseId: string;
                            snapshotArtifactDigest: string;
                            snapshotId: string;
                        }[];
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
        };
    };
    recordPhase01ConsumerReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    applyResult: "APPLIED" | "NOT_APPLIED";
                    eventId: string;
                    processedAt: string;
                    processingDigest: string;
                    receiveResult: "ACCEPTED" | "REJECTED";
                    validationResult: "VALID" | "INVALID";
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        receiptId: string;
                        receiptSequence: string;
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
        };
    };
    replayPhase01BlockedConsumerDelivery: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    eventId: string;
                    governanceObjectId: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deliveryId: string;
                        deliveryStateId: string;
                        stateSequence: string;
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
        };
    };
    downloadPhase01CanonicalSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscriptionId: string;
                snapshotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.hdi.canonical-snapshot+json": {
                        /** @enum {string} */
                        envelopeContractVersion: "phase-01.v1";
                        payload: components["schemas"]["def-0"];
                        projectionContract: {
                            projectionType: string;
                            schemaDigest: string;
                            /** @enum {string} */
                            schemaDigestAlgorithm: "SHA-256";
                            /** @enum {string} */
                            schemaVersion: "1";
                        };
                        release: {
                            /** @enum {string} */
                            aggregateType: "CHARGE_CATALOG";
                            businessValidFrom: string;
                            businessValidTo: string | null;
                            governanceObjectId: string;
                            releaseId: string;
                            releaseNo: string;
                        };
                        /** @enum {string} */
                        serializationProfileVersion: "canonical-json.v1";
                    } | {
                        /** @enum {string} */
                        envelopeContractVersion: "phase-01.v1";
                        payload: components["schemas"]["def-1"];
                        projectionContract: {
                            projectionType: string;
                            schemaDigest: string;
                            /** @enum {string} */
                            schemaDigestAlgorithm: "SHA-256";
                            /** @enum {string} */
                            schemaVersion: "0";
                        };
                        release: {
                            /** @enum {string} */
                            aggregateType: "PRICE_LIST";
                            businessValidFrom: string;
                            businessValidTo: string | null;
                            governanceObjectId: string;
                            releaseId: string;
                            releaseNo: string;
                        };
                        /** @enum {string} */
                        serializationProfileVersion: "canonical-json.v1";
                    } | {
                        /** @enum {string} */
                        envelopeContractVersion: "phase-01.v1";
                        payload: components["schemas"]["def-2"];
                        projectionContract: {
                            projectionType: string;
                            schemaDigest: string;
                            /** @enum {string} */
                            schemaDigestAlgorithm: "SHA-256";
                            /** @enum {string} */
                            schemaVersion: "1";
                        };
                        release: {
                            /** @enum {string} */
                            aggregateType: "PRICE_LIST";
                            businessValidFrom: string;
                            businessValidTo: string | null;
                            governanceObjectId: string;
                            releaseId: string;
                            releaseNo: string;
                        };
                        /** @enum {string} */
                        serializationProfileVersion: "canonical-json.v1";
                    };
                };
            };
            /** @description Default Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.hdi.canonical-snapshot+json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.hdi.canonical-snapshot+json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.hdi.canonical-snapshot+json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.hdi.canonical-snapshot+json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
        };
    };
    createPhase01ConsumerSubscriptionVersion: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    governanceObjectId: string;
                    projectionSchemaVersion: "0" | "1";
                    /** @enum {string} */
                    projectionType: "hdi.price-list";
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subscriptionId: string;
                        subscriptionVersionId: string;
                        versionNo: string;
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
        };
    };
    publishPhase01PriceList: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    businessValidFrom: string;
                    businessValidTo: string | null;
                    changeReason: string;
                    currencyCode: string;
                    displayName: string;
                    entries: {
                        billingUnitCode: string;
                        businessValidFrom: string;
                        businessValidTo: string | null;
                        campusId: string | null;
                        chargeItemId: string;
                        chargeItemVersionId: string;
                        encounterMode: "GENERAL" | "SPECIFIC";
                        encounterType: ("OUTPATIENT" | "INPATIENT" | "EMERGENCY" | "CHECKUP") | null;
                        fixedUnitPrice: string;
                        scopeLevel: "HOSPITAL" | "CAMPUS";
                        zeroPriceReason: string | null;
                    }[];
                    governanceObjectId: string;
                    priceListCode: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        eventId: string;
                        releaseId: string;
                        snapshotId: string;
                        stableId: string;
                        versionId: string;
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
        };
    };
    resolvePhase01Price: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    campusId: string;
                    chargeItemId: string;
                    chargeItemVersionId: string;
                    encounterType: "OUTPATIENT" | "INPATIENT" | "EMERGENCY" | "CHECKUP";
                    governanceObjectId: string;
                    priceListId: string;
                    quantity: string;
                    recordAsOf: string;
                    requestId: string;
                    serviceOccurredAt: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        currencyCode: string | null;
                        finalAmount: string | null;
                        priceListReleaseId: string | null;
                        priceResolutionId: string;
                        requestId: string;
                        resultDigest: string | null;
                        status: "SUCCEEDED" | "NO_PRICE" | "CONFLICT" | "SUSPENDED";
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        requestId: string;
                    };
                };
            };
        };
    };
}
