/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/vnext/catalog/effective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEffectiveCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vnext/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vnext/catalog/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCatalogEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vnext/catalog/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["catalogCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vnext/catalog/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["catalogHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vnext/sources/{id}/qualification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sourceQualification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listEffectiveCatalog: {
        parameters: {
            query: {
                scope: "BASELINE" | "SYNTHETIC";
                businessAt: string;
                asOf?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            kind: "DATASET" | "SOURCE" | "RESPONSIBILITY";
                            scope: "BASELINE" | "SYNTHETIC";
                            code: string;
                            version: number;
                            versionId: string;
                            head: string;
                            status: "DRAFT" | "REVIEW" | "PUBLISHED" | "RETIRED";
                            payload: {
                                fields?: {
                                    original: {
                                        [key: string]: unknown;
                                    };
                                    pointer: string;
                                    routing: {
                                        [key: string]: string;
                                    };
                                }[];
                                adopted?: {
                                    name: string;
                                    explanation: string;
                                };
                                original?: {
                                    [key: string]: string;
                                };
                                domain?: string;
                                dependencies?: {
                                    [key: string]: unknown;
                                }[];
                                model?: {
                                    [key: string]: unknown;
                                };
                                name?: string;
                                dataset?: string;
                                authorityScope?: string;
                                fieldGroup?: string;
                                role?: string;
                                assigneeRole?: string;
                                sourceEvidence?: string;
                            } & {
                                [key: string]: unknown;
                            };
                            reviewDigest: string;
                            validFrom: string;
                            validTo: string | null;
                            recordedAt: string;
                        }[];
                        domains: {
                            code: string;
                            name: string;
                            datasets: string[];
                        }[];
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
        };
    };
    listCatalog: {
        parameters: {
            query: {
                scope: "BASELINE" | "SYNTHETIC";
                asOf?: string;
                page?: number;
                domain?: string;
                owner?: string;
                status?: "DRAFT" | "REVIEW" | "PUBLISHED" | "RETIRED";
                kind?: "DATASET" | "SOURCE" | "RESPONSIBILITY";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            kind: "DATASET" | "SOURCE" | "RESPONSIBILITY";
                            scope: "BASELINE" | "SYNTHETIC";
                            code: string;
                            version: number;
                            versionId: string;
                            head: string;
                            status: "DRAFT" | "REVIEW" | "PUBLISHED" | "RETIRED";
                            payload: {
                                fields?: {
                                    original: {
                                        [key: string]: unknown;
                                    };
                                    pointer: string;
                                    routing: {
                                        [key: string]: string;
                                    };
                                }[];
                                adopted?: {
                                    name: string;
                                    explanation: string;
                                };
                                original?: {
                                    [key: string]: string;
                                };
                                domain?: string;
                                dependencies?: {
                                    [key: string]: unknown;
                                }[];
                                model?: {
                                    [key: string]: unknown;
                                };
                                name?: string;
                                dataset?: string;
                                authorityScope?: string;
                                fieldGroup?: string;
                                role?: string;
                                assigneeRole?: string;
                                sourceEvidence?: string;
                            } & {
                                [key: string]: unknown;
                            };
                            reviewDigest: string;
                            validFrom: string;
                            validTo: string | null;
                            recordedAt: string;
                        }[];
                        total: number;
                        page: number;
                        domains: {
                            code: string;
                            name: string;
                            datasets: string[];
                        }[];
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
        };
    };
    getCatalogEntry: {
        parameters: {
            query: {
                scope: "BASELINE" | "SYNTHETIC";
                asOf?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        kind: "DATASET" | "SOURCE" | "RESPONSIBILITY";
                        scope: "BASELINE" | "SYNTHETIC";
                        code: string;
                        version: number;
                        versionId: string;
                        head: string;
                        status: "DRAFT" | "REVIEW" | "PUBLISHED" | "RETIRED";
                        payload: {
                            fields?: {
                                original: {
                                    [key: string]: unknown;
                                };
                                pointer: string;
                                routing: {
                                    [key: string]: string;
                                };
                            }[];
                            adopted?: {
                                name: string;
                                explanation: string;
                            };
                            original?: {
                                [key: string]: string;
                            };
                            domain?: string;
                            dependencies?: {
                                [key: string]: unknown;
                            }[];
                            model?: {
                                [key: string]: unknown;
                            };
                            name?: string;
                            dataset?: string;
                            authorityScope?: string;
                            fieldGroup?: string;
                            role?: string;
                            assigneeRole?: string;
                            sourceEvidence?: string;
                        } & {
                            [key: string]: unknown;
                        };
                        reviewDigest: string;
                        validFrom: string;
                        validTo: string | null;
                        recordedAt: string;
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
        };
    };
    catalogCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    scope: "BASELINE" | "SYNTHETIC";
                    /** Format: uuid */
                    requestId: string;
                    reason: string;
                    /** @enum {string} */
                    action: "CREATE";
                    kind: "DATASET" | "SOURCE" | "RESPONSIBILITY";
                    code: string;
                    values: {
                        name?: string;
                        explanation?: string;
                        environment?: string;
                        sourceKind?: string;
                        deploymentScope?: string;
                        vendor?: string;
                        systemVersion?: string;
                        businessOwnerRole?: string;
                        technicalRole?: string;
                        sourceEvidence?: "SYNTHETIC_BOOTSTRAP" | string;
                        interfaceContractRef?: string;
                        dataset?: string;
                        authorityScope?: string;
                        fieldGroup?: string;
                        role?: string;
                        assigneeRole?: string;
                    };
                    validFrom: string;
                    validTo?: string | null;
                } | {
                    scope: "BASELINE" | "SYNTHETIC";
                    /** Format: uuid */
                    requestId: string;
                    reason: string;
                    /** @enum {string} */
                    action: "REVISE";
                    /** Format: uuid */
                    target: string;
                    expectedHead: string;
                    values: {
                        name?: string;
                        explanation?: string;
                        environment?: string;
                        sourceKind?: string;
                        deploymentScope?: string;
                        vendor?: string;
                        systemVersion?: string;
                        businessOwnerRole?: string;
                        technicalRole?: string;
                        sourceEvidence?: "SYNTHETIC_BOOTSTRAP" | string;
                        interfaceContractRef?: string;
                        dataset?: string;
                        authorityScope?: string;
                        fieldGroup?: string;
                        role?: string;
                        assigneeRole?: string;
                    };
                    validFrom: string;
                    validTo?: string | null;
                } | {
                    scope: "BASELINE" | "SYNTHETIC";
                    /** Format: uuid */
                    requestId: string;
                    reason: string;
                    action: "SUBMIT" | "REJECT";
                    /** Format: uuid */
                    target: string;
                    expectedHead: string;
                } | {
                    scope: "BASELINE" | "SYNTHETIC";
                    /** Format: uuid */
                    requestId: string;
                    reason: string;
                    action: "PUBLISH" | "RETIRE";
                    /** Format: uuid */
                    target: string;
                    expectedHead: string;
                    reviewDigest: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        head: string;
                        version: number;
                        versionId: string;
                        status: "DRAFT" | "REVIEW" | "PUBLISHED" | "RETIRED";
                        reviewDigest: string;
                        recordedAt: string;
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
        };
    };
    catalogHistory: {
        parameters: {
            query: {
                scope: "BASELINE" | "SYNTHETIC";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        head: string;
                        status: "DRAFT" | "REVIEW" | "PUBLISHED" | "RETIRED";
                        version: number;
                        payload: {
                            fields?: {
                                original: {
                                    [key: string]: unknown;
                                };
                                pointer: string;
                                routing: {
                                    [key: string]: string;
                                };
                            }[];
                            adopted?: {
                                name: string;
                                explanation: string;
                            };
                            original?: {
                                [key: string]: string;
                            };
                            domain?: string;
                            dependencies?: {
                                [key: string]: unknown;
                            }[];
                            model?: {
                                [key: string]: unknown;
                            };
                            name?: string;
                            dataset?: string;
                            authorityScope?: string;
                            fieldGroup?: string;
                            role?: string;
                            assigneeRole?: string;
                            sourceEvidence?: string;
                        } & {
                            [key: string]: unknown;
                        };
                        validFrom: string;
                        validTo: string | null;
                        recordedAt: string;
                    }[];
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
        };
    };
    sourceQualification: {
        parameters: {
            query: {
                scope: "BASELINE" | "SYNTHETIC";
                businessAt: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
            /** @description Default Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        message: string;
                        field?: string;
                    };
                };
            };
        };
    };
}
