SELECT pg_advisory_xact_lock(901002);
CREATE TABLE vnext_control.location_use_write_authority(singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),key_hex text NOT NULL CHECK(key_hex ~ '^[a-f0-9]{64}$'));
CREATE TABLE location_master.usage_type_access(actor text NOT NULL REFERENCES vnext_control.actor(code),permission text NOT NULL CHECK(permission IN ('READ','WRITE','VERIFY','REVIEW')),PRIMARY KEY(actor,permission));
CREATE TABLE location_master.usage_type(id uuid PRIMARY KEY DEFAULT uuidv7(),code text NOT NULL UNIQUE CHECK(code ~ '^[A-Z][A-Z0-9_]{0,63}$'),meaning text NOT NULL CHECK(length(meaning) BETWEEN 1 AND 2000));
CREATE TABLE location_master.usage_type_version(id uuid PRIMARY KEY DEFAULT uuidv7(),usage_type_id uuid NOT NULL REFERENCES location_master.usage_type(id),number bigint NOT NULL CHECK(number>0),content jsonb NOT NULL,maker_identity text NOT NULL,review_digest text NOT NULL CHECK(review_digest ~ '^[a-f0-9]{64}$'),recorded_at timestamp NOT NULL DEFAULT timezone('Asia/Shanghai',clock_timestamp()),UNIQUE(usage_type_id,number));
CREATE TABLE location_master.usage_type_verification(id uuid PRIMARY KEY DEFAULT uuidv7(),version_id uuid NOT NULL REFERENCES location_master.usage_type_version(id),sequence bigint NOT NULL CHECK(sequence>0),actor text NOT NULL REFERENCES vnext_control.actor(code),identity_code text NOT NULL,evidence_id uuid NOT NULL REFERENCES governance_catalog.protected_artifact(id),meaning_accepted boolean NOT NULL,material_digest text NOT NULL,recorded_at timestamp NOT NULL DEFAULT timezone('Asia/Shanghai',clock_timestamp()),UNIQUE(version_id,sequence));
CREATE TABLE location_master.usage_type_approval(version_id uuid PRIMARY KEY REFERENCES location_master.usage_type_version(id),verification_id uuid NOT NULL REFERENCES location_master.usage_type_verification(id),actor text NOT NULL REFERENCES vnext_control.actor(code),identity_code text NOT NULL,recorded_at timestamp NOT NULL DEFAULT timezone('Asia/Shanghai',clock_timestamp()));
-- One domain action journal also carries exact command recovery; no parallel result ledger.
CREATE TABLE location_master.usage_type_action(id uuid PRIMARY KEY DEFAULT uuidv7(),usage_type_id uuid NOT NULL REFERENCES location_master.usage_type(id),sequence bigint NOT NULL CHECK(sequence>0),actor text NOT NULL REFERENCES vnext_control.actor(code),identity_code text NOT NULL,request_id uuid NOT NULL,action text NOT NULL CHECK(action IN ('CREATE','REVISE','VERIFY','APPROVE','ENABLE','DISABLE')),reason text NOT NULL,digest text NOT NULL,result jsonb,recorded_at timestamp NOT NULL DEFAULT timezone('Asia/Shanghai',clock_timestamp()),UNIQUE(identity_code,request_id),UNIQUE(usage_type_id,sequence));
CREATE FUNCTION location_master.use_closed(p_value jsonb,p_keys text[]) RETURNS void LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog AS $$ BEGIN IF jsonb_typeof(p_value) IS DISTINCT FROM 'object' OR NOT p_value ?& p_keys OR p_value-p_keys<>'{}'::jsonb THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;END $$;
CREATE FUNCTION location_master.usage_type_command_shape(p_command jsonb,p_keys text[]) RETURNS void LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog AS $$
DECLARE field text;BEGIN
 PERFORM location_master.use_closed(p_command,p_keys);
 FOREACH field IN ARRAY p_keys LOOP
  IF field IN ('description','validTo') THEN IF jsonb_typeof(p_command->field) NOT IN ('string','null') THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
  ELSIF field='meaningAccepted' THEN IF jsonb_typeof(p_command->field) IS DISTINCT FROM 'boolean' THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
  ELSIF jsonb_typeof(p_command->field) IS DISTINCT FROM 'string' THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
  IF field IN ('requestId','target','versionId','sourceId','sourceVersionId','evidenceId') AND p_command->>field !~ '^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$' THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
  IF field='expectedHead' AND p_command->>field !~ '^[1-9][0-9]{0,18}$' OR field='reviewDigest' AND p_command->>field !~ '^[a-f0-9]{64}$' THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
 END LOOP;
END $$;
CREATE FUNCTION location_master.use_attest(p_ticket text,p_signature text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE t jsonb:=p_ticket::jsonb;k bytea;ip bytea:=decode(repeat('36',64),'hex');op bytea:=decode(repeat('5c',64),'hex');i integer;BEGIN
 PERFORM pg_advisory_xact_lock(901002);SELECT decode(key_hex,'hex') INTO k FROM vnext_control.location_use_write_authority;
 IF k IS NULL OR t->>'transaction' IS DISTINCT FROM pg_current_xact_id()::text THEN RAISE EXCEPTION 'ACCESS_DENIED';END IF;
 FOR i IN 0..31 LOOP ip:=set_byte(ip,i,get_byte(ip,i)#get_byte(k,i));op:=set_byte(op,i,get_byte(op,i)#get_byte(k,i));END LOOP;
 IF p_signature IS DISTINCT FROM encode(sha256(op||sha256(ip||convert_to(p_ticket,'UTF8'))),'hex') THEN RAISE EXCEPTION 'ACCESS_DENIED';END IF;RETURN t;
END $$;
CREATE FUNCTION location_master.usage_type_authorize(p_actor text,p_permission text) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE identity text;BEGIN
 PERFORM pg_advisory_xact_lock(901002);IF p_permission NOT IN ('READ','WRITE','VERIFY','REVIEW') THEN RAISE EXCEPTION 'ACCESS_DENIED';END IF;
 identity:=vnext_control.authorize(p_actor,'SYNTHETIC',CASE WHEN p_permission='VERIFY' THEN 'REVIEW' ELSE p_permission END);
 IF NOT EXISTS(SELECT 1 FROM location_master.usage_type_access WHERE actor=p_actor AND permission=p_permission) OR (p_permission<>'READ' AND NOT EXISTS(SELECT 1 FROM vnext_control.actor WHERE code=p_actor AND active AND principal_kind='HUMAN')) THEN RAISE EXCEPTION 'ACCESS_DENIED';END IF;RETURN identity;
END $$;
CREATE FUNCTION location_master.usage_type_head(p_id uuid,p_r timestamp) RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ SELECT coalesce((SELECT max(number) FROM location_master.usage_type_version WHERE usage_type_id=p_id AND recorded_at<=p_r),0)+(SELECT count(*) FROM location_master.usage_type_action WHERE usage_type_id=p_id AND action IN ('ENABLE','DISABLE') AND recorded_at<=p_r) $$;
CREATE FUNCTION location_master.usage_type_enabled(p_id uuid,p_b timestamp,p_r timestamp) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$
 SELECT EXISTS(SELECT 1 FROM location_master.usage_type_version v JOIN location_master.usage_type_approval a ON a.version_id=v.id WHERE v.usage_type_id=p_id AND a.recorded_at<=p_r) AND coalesce((SELECT action='ENABLE' FROM location_master.usage_type_action WHERE usage_type_id=p_id AND action IN ('ENABLE','DISABLE') AND recorded_at<=p_r AND recorded_at<=p_b ORDER BY sequence DESC LIMIT 1),true)
$$;
CREATE FUNCTION location_master.usage_type_read(p_actor text,p_input jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE r timestamp;b timestamp;result jsonb;entry jsonb;BEGIN
 PERFORM location_master.usage_type_authorize(p_actor,'READ');IF jsonb_typeof(p_input) IS DISTINCT FROM 'object' OR NOT p_input ? 'id' OR p_input-ARRAY['id','versionId','businessAt','recordAsOf','history']<>'{}'::jsonb THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
 r:=CASE WHEN p_input ? 'recordAsOf' THEN governance_catalog.contract_time(p_input->>'recordAsOf') ELSE timezone('Asia/Shanghai',clock_timestamp()) END;
 b:=CASE WHEN p_input ? 'businessAt' THEN governance_catalog.contract_time(p_input->>'businessAt') ELSE r END;
 SELECT coalesce(jsonb_agg(item ORDER BY number),'[]') INTO result FROM(SELECT v.number,v.content||jsonb_build_object('id',u.id,'versionId',v.id,'version',v.number::text,'head',location_master.usage_type_head(u.id,r)::text,'status',CASE WHEN a.version_id IS NOT NULL THEN 'APPROVED' WHEN q.id IS NOT NULL THEN 'REVIEW' ELSE 'DRAFT' END,'enabled',location_master.usage_type_enabled(u.id,b,r),'applicableAtBusinessTime',CASE WHEN p_input ? 'businessAt' THEN tsrange(governance_catalog.contract_time(v.content->>'validFrom'),CASE WHEN v.content->>'validTo' IS NULL THEN NULL ELSE governance_catalog.contract_time(v.content->>'validTo') END,'[)') @> b ELSE NULL END,'reviewDigest',v.review_digest,'recordedAt',to_char(v.recorded_at,'YYYY-MM-DD"T"HH24:MI:SS.US'),'approvedAt',to_char(a.recorded_at,'YYYY-MM-DD"T"HH24:MI:SS.US'),'verification',CASE WHEN q.id IS NULL THEN NULL ELSE jsonb_build_object('id',q.id,'actor',q.actor,'identity',q.identity_code,'evidenceId',q.evidence_id,'meaningAccepted',q.meaning_accepted,'recordedAt',to_char(q.recorded_at,'YYYY-MM-DD"T"HH24:MI:SS.US')) END,'events',coalesce((SELECT jsonb_agg(jsonb_build_object('id',e.id,'sequence',e.sequence::text,'action',e.action,'actor',e.actor,'identity',e.identity_code,'reason',e.reason,'requestId',e.request_id,'recordedAt',to_char(e.recorded_at,'YYYY-MM-DD"T"HH24:MI:SS.US')) ORDER BY e.sequence) FROM location_master.usage_type_action e WHERE e.usage_type_id=u.id AND e.action IN ('ENABLE','DISABLE') AND e.recorded_at<=r),'[]')) item
 FROM location_master.usage_type_version v JOIN location_master.usage_type u ON u.id=v.usage_type_id
 LEFT JOIN location_master.usage_type_approval a ON a.version_id=v.id AND a.recorded_at<=r
 LEFT JOIN LATERAL(SELECT q.* FROM location_master.usage_type_verification q WHERE q.version_id=v.id AND q.recorded_at<=r AND (a.version_id IS NULL OR q.id=a.verification_id) ORDER BY q.sequence DESC LIMIT 1) q ON true
 WHERE u.id=(p_input->>'id')::uuid AND v.recorded_at<=r AND (NOT p_input ? 'versionId' OR v.id=(p_input->>'versionId')::uuid) ORDER BY v.number DESC LIMIT CASE WHEN coalesce((p_input->>'history')::boolean,false) THEN 10000 ELSE 1 END) items;
 FOR entry IN SELECT value FROM jsonb_array_elements(result) LOOP PERFORM vnext_control.require_source_access(p_actor,'SYNTHETIC',(entry->>'sourceId')::uuid,(entry->>'sourceVersionId')::uuid);PERFORM governance_catalog.registration_evidence_access(p_actor,(entry->>'evidenceId')::uuid,(entry->>'sourceVersionId')::uuid,'NORTH');IF entry->'verification'<>'null'::jsonb THEN PERFORM governance_catalog.registration_evidence_access(p_actor,(entry->'verification'->>'evidenceId')::uuid,(entry->>'sourceVersionId')::uuid,'NORTH');END IF;END LOOP;RETURN result;
END $$;
CREATE FUNCTION location_master.usage_type_list(p_actor text,p_input jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE u record;items jsonb:='[]';n integer:=coalesce((p_input->>'limit')::integer,50);r timestamp;b timestamp;last_id uuid;BEGIN
 PERFORM location_master.usage_type_authorize(p_actor,'READ');IF p_input-ARRAY['after','limit','businessAt','recordAsOf']<>'{}'::jsonb OR n NOT BETWEEN 1 AND 100 THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;r:=CASE WHEN p_input ? 'recordAsOf' THEN governance_catalog.contract_time(p_input->>'recordAsOf') ELSE timezone('Asia/Shanghai',clock_timestamp()) END;
 IF p_input ? 'businessAt' THEN b:=governance_catalog.contract_time(p_input->>'businessAt');END IF;
 FOR u IN SELECT listed.id FROM location_master.usage_type listed WHERE (NOT p_input ? 'after' OR listed.id>(p_input->>'after')::uuid) AND EXISTS(SELECT 1 FROM location_master.usage_type_version v WHERE v.usage_type_id=listed.id AND v.recorded_at<=r) ORDER BY listed.id LIMIT n+1 LOOP
 IF jsonb_array_length(items)=n THEN RETURN jsonb_build_object('items',items,'nextAfterId',last_id);END IF;items:=items||location_master.usage_type_read(p_actor,jsonb_build_object('id',u.id,'recordAsOf',to_char(r,'YYYY-MM-DD"T"HH24:MI:SS.US'))||CASE WHEN p_input ? 'businessAt' THEN jsonb_build_object('businessAt',to_char(b,'YYYY-MM-DD"T"HH24:MI:SS.US')) ELSE '{}'::jsonb END);last_id:=u.id;END LOOP;RETURN jsonb_build_object('items',items,'nextAfterId',NULL);
END $$;
CREATE FUNCTION location_master.usage_type_command(p_ticket text,p_signature text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE t jsonb;c jsonb;identity text;d text;prior location_master.usage_type_action;u location_master.usage_type;v location_master.usage_type_version;q location_master.usage_type_verification;response jsonb;keys text[];usage_id uuid;selected_version_id uuid;event_id uuid;next_number bigint;now_at timestamp:=timezone('Asia/Shanghai',clock_timestamp());f timestamp;e timestamp;BEGIN
 t:=location_master.use_attest(p_ticket,p_signature);now_at:=timezone('Asia/Shanghai',clock_timestamp());PERFORM location_master.use_closed(t,ARRAY['actor','transaction','command','materialDigest']);c:=t->'command';IF coalesce(c->>'reason','') !~ '\S' OR length(c->>'reason')>2000 OR t->>'materialDigest' !~ '^[a-f0-9]{64}$' THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
 identity:=location_master.usage_type_authorize(t->>'actor',CASE c->>'action' WHEN 'VERIFY' THEN 'VERIFY' WHEN 'APPROVE' THEN 'REVIEW' ELSE 'WRITE' END);d:=encode(sha256(convert_to(c::text,'UTF8')),'hex');
 SELECT * INTO prior FROM location_master.usage_type_action WHERE identity_code=identity AND request_id=(c->>'requestId')::uuid;IF FOUND THEN IF prior.digest<>d THEN RAISE EXCEPTION 'REQUEST_CONFLICT';END IF;PERFORM location_master.usage_type_read(t->>'actor',jsonb_build_object('id',prior.usage_type_id,'versionId',prior.result->>'versionId'));RETURN prior.result;END IF;
 IF c->>'action' IN ('CREATE','REVISE') THEN
  keys:=ARRAY['action','requestId','reason','code','name','meaning','description','validFrom','validTo','sourceId','sourceVersionId','evidenceId']||CASE WHEN c->>'action'='REVISE' THEN ARRAY['target','expectedHead'] ELSE ARRAY[]::text[] END;PERFORM location_master.usage_type_command_shape(c,keys);
  IF c->>'code' !~ '^[A-Z][A-Z0-9_]{0,63}$' OR coalesce(c->>'name','') !~ '\S' OR coalesce(c->>'meaning','') !~ '\S' OR length(c->>'name')>2000 OR length(c->>'meaning')>2000 OR (jsonb_typeof(c->'description') NOT IN ('string','null')) OR length(c->>'description')>2000 THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
  f:=governance_catalog.contract_time(c->>'validFrom');e:=CASE WHEN c->>'validTo' IS NULL THEN NULL ELSE governance_catalog.contract_time(c->>'validTo') END;IF e<=f THEN RAISE EXCEPTION 'INVALID_BUSINESS_PERIOD';END IF;
  PERFORM vnext_control.require_source_access(t->>'actor','SYNTHETIC',(c->>'sourceId')::uuid,(c->>'sourceVersionId')::uuid);PERFORM governance_catalog.registration_evidence_access(t->>'actor',(c->>'evidenceId')::uuid,(c->>'sourceVersionId')::uuid,'NORTH');
  IF NOT governance_catalog.source_valid_spans((c->>'sourceVersionId')::uuid,now_at) @> tsrange(f,e,'[)') THEN RAISE EXCEPTION 'SOURCE_NOT_READY';END IF;
  IF c->>'action'='CREATE' THEN IF EXISTS(SELECT 1 FROM location_master.usage_type WHERE code=c->>'code') THEN RAISE EXCEPTION 'USAGE_TYPE_CODE_CONFLICT';END IF;INSERT INTO location_master.usage_type(code,meaning) VALUES(c->>'code',c->>'meaning') RETURNING * INTO u;next_number:=1;
  ELSE SELECT * INTO u FROM location_master.usage_type WHERE id=(c->>'target')::uuid;IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND';END IF;IF location_master.usage_type_head(u.id,now_at)::text IS DISTINCT FROM c->>'expectedHead' THEN RAISE EXCEPTION 'STALE_HEAD';END IF;IF u.code IS DISTINCT FROM c->>'code' OR u.meaning IS DISTINCT FROM c->>'meaning' THEN RAISE EXCEPTION 'USAGE_TYPE_MEANING_IMMUTABLE';END IF;IF governance_catalog.contract_time(c->>'validFrom') IS DISTINCT FROM (SELECT governance_catalog.contract_time(v0.content->>'validFrom') FROM location_master.usage_type_version v0 WHERE v0.usage_type_id=u.id ORDER BY v0.number LIMIT 1) THEN RAISE EXCEPTION 'USAGE_TYPE_START_IMMUTABLE';END IF;SELECT coalesce(max(v1.number),0)+1 INTO next_number FROM location_master.usage_type_version v1 WHERE usage_type_id=u.id;END IF;
  usage_id:=u.id;INSERT INTO location_master.usage_type_version(usage_type_id,number,content,maker_identity,review_digest,recorded_at) VALUES(usage_id,next_number,c-ARRAY['action','requestId','reason','target','expectedHead'],identity,encode(sha256(convert_to((c-ARRAY['action','requestId','reason'])::text,'UTF8')),'hex'),now_at) RETURNING * INTO v;selected_version_id:=v.id;
 ELSIF c->>'action' IN ('ENABLE','DISABLE') THEN
  PERFORM location_master.usage_type_command_shape(c,ARRAY['action','requestId','reason','target','expectedHead']);SELECT * INTO u FROM location_master.usage_type WHERE id=(c->>'target')::uuid;IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND';END IF;IF location_master.usage_type_head(u.id,now_at)::text IS DISTINCT FROM c->>'expectedHead' THEN RAISE EXCEPTION 'STALE_HEAD';END IF;
  SELECT v1.* INTO v FROM location_master.usage_type_version v1 JOIN location_master.usage_type_approval a ON a.version_id=v1.id WHERE v1.usage_type_id=u.id ORDER BY v1.number DESC LIMIT 1;IF NOT FOUND THEN RAISE EXCEPTION 'APPROVAL_REQUIRED';END IF;PERFORM location_master.usage_type_read(t->>'actor',jsonb_build_object('id',u.id,'versionId',v.id));usage_id:=u.id;selected_version_id:=v.id;
 ELSE
  keys:=ARRAY['action','requestId','reason','target','expectedHead','versionId','reviewDigest']||CASE WHEN c->>'action'='VERIFY' THEN ARRAY['evidenceId','meaningAccepted'] ELSE ARRAY[]::text[] END;PERFORM location_master.usage_type_command_shape(c,keys);IF c->>'action' NOT IN ('VERIFY','APPROVE') THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
  SELECT v1.* INTO v FROM location_master.usage_type_version v1 WHERE v1.id=(c->>'versionId')::uuid AND v1.usage_type_id=(c->>'target')::uuid;IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND';END IF;IF location_master.usage_type_head(v.usage_type_id,now_at)::text IS DISTINCT FROM c->>'expectedHead' OR v.number<>(SELECT max(number) FROM location_master.usage_type_version WHERE usage_type_id=v.usage_type_id) OR v.review_digest IS DISTINCT FROM c->>'reviewDigest' THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;
  IF identity=v.maker_identity THEN RAISE EXCEPTION 'MAKER_CHECKER_REQUIRED';END IF;PERFORM location_master.usage_type_read(t->>'actor',jsonb_build_object('id',v.usage_type_id,'versionId',v.id));IF EXISTS(SELECT 1 FROM location_master.usage_type_approval WHERE version_id=v.id) THEN RAISE EXCEPTION 'ALREADY_COMMITTED';END IF;usage_id:=v.usage_type_id;selected_version_id:=v.id;
  IF c->>'action'='VERIFY' THEN IF jsonb_typeof(c->'meaningAccepted') IS DISTINCT FROM 'boolean' THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;PERFORM governance_catalog.registration_evidence_access(t->>'actor',(c->>'evidenceId')::uuid,(v.content->>'sourceVersionId')::uuid,'NORTH');INSERT INTO location_master.usage_type_verification(version_id,sequence,actor,identity_code,evidence_id,meaning_accepted,material_digest,recorded_at) VALUES(v.id,(SELECT coalesce(max(sequence),0)+1 FROM location_master.usage_type_verification WHERE version_id=v.id),t->>'actor',identity,(c->>'evidenceId')::uuid,(c->>'meaningAccepted')::boolean,t->>'materialDigest',now_at);
  ELSE SELECT * INTO q FROM location_master.usage_type_verification WHERE version_id=v.id ORDER BY sequence DESC LIMIT 1;IF NOT FOUND OR NOT q.meaning_accepted THEN RAISE EXCEPTION 'LEGAL_REVIEW_REQUIRED';END IF;IF q.material_digest IS DISTINCT FROM t->>'materialDigest' THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;IF location_master.usage_type_authorize(q.actor,'VERIFY') IS DISTINCT FROM q.identity_code OR q.identity_code=v.maker_identity THEN RAISE EXCEPTION 'ACCESS_DENIED';END IF;PERFORM governance_catalog.registration_evidence_access(q.actor,q.evidence_id,(v.content->>'sourceVersionId')::uuid,'NORTH');IF NOT governance_catalog.source_valid_spans((v.content->>'sourceVersionId')::uuid,now_at) @> tsrange(governance_catalog.contract_time(v.content->>'validFrom'),CASE WHEN v.content->>'validTo' IS NULL THEN NULL ELSE governance_catalog.contract_time(v.content->>'validTo') END,'[)') THEN RAISE EXCEPTION 'SOURCE_NOT_READY';END IF;INSERT INTO location_master.usage_type_approval VALUES(v.id,q.id,t->>'actor',identity,now_at);END IF;
 END IF;
 -- Insert the event before projection so direct ENABLE/DISABLE returns its new head and state.
 INSERT INTO location_master.usage_type_action(usage_type_id,sequence,actor,identity_code,request_id,action,reason,digest,recorded_at) VALUES(usage_id,(SELECT coalesce(max(sequence),0)+1 FROM location_master.usage_type_action WHERE usage_type_id=usage_id),t->>'actor',identity,(c->>'requestId')::uuid,c->>'action',c->>'reason',d,now_at) RETURNING id INTO event_id;
 response:=location_master.usage_type_read(t->>'actor',jsonb_build_object('id',usage_id,'versionId',selected_version_id))->0;UPDATE location_master.usage_type_action x SET result=response WHERE x.id=event_id;
 INSERT INTO vnext_control.audit(actor_code,object_id,action,reason,content_digest) VALUES(t->>'actor',usage_id,'LOCATION_USAGE_TYPE_'||(c->>'action'),'OWNER_PURPOSE_GOVERNANCE',d);RETURN response;
END $$;
CREATE FUNCTION location_master.usage_type_action_immutable() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$BEGIN
 IF TG_OP='UPDATE' AND OLD.result IS NULL AND NEW.result IS NOT NULL AND (to_jsonb(OLD)-'result')=(to_jsonb(NEW)-'result') THEN RETURN NEW;END IF;RAISE EXCEPTION 'IMMUTABLE_FACT';
END $$;
CREATE TRIGGER usage_type_action_immutable BEFORE UPDATE OR DELETE ON location_master.usage_type_action FOR EACH ROW EXECUTE FUNCTION location_master.usage_type_action_immutable();
CREATE FUNCTION location_master.use_owner_ready(p_proof text) RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS $$SELECT EXISTS(SELECT 1 FROM vnext_control.location_use_write_authority WHERE encode(sha256(decode(key_hex,'hex')),'hex')=p_proof)$$;
CREATE FUNCTION location_master.usage_type_access_audit() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN INSERT INTO vnext_control.audit(actor_code,object_id,action,reason,content_digest) VALUES(coalesce(NEW.actor,OLD.actor),'00000000-0000-0000-0000-000000000201','LOCATION_USAGE_TYPE_AUTHORIZATION',TG_OP,encode(sha256(convert_to(coalesce(to_jsonb(NEW),to_jsonb(OLD))::text,'UTF8')),'hex'));RETURN coalesce(NEW,OLD);END $$;
CREATE TRIGGER usage_type_access_lock BEFORE INSERT OR UPDATE OR DELETE ON location_master.usage_type_access FOR EACH STATEMENT EXECUTE FUNCTION vnext_control.lock_authorization_change();
CREATE TRIGGER usage_type_access_audit AFTER INSERT OR UPDATE OR DELETE ON location_master.usage_type_access FOR EACH ROW EXECUTE FUNCTION location_master.usage_type_access_audit();
-- Capability hints are actor scoped. Every operation independently rechecks authority.
CREATE FUNCTION location_master.usage_type_permissions(p_actor text) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS $$
 SELECT jsonb_build_object('read',coalesce(a.active AND EXISTS(SELECT 1 FROM vnext_control.actor_grant g WHERE g.actor_code=p_actor AND scope='SYNTHETIC' AND permission='READ') AND EXISTS(SELECT 1 FROM location_master.usage_type_access g WHERE g.actor=p_actor AND permission='READ'),false),
 'write',coalesce(a.active AND a.principal_kind='HUMAN' AND EXISTS(SELECT 1 FROM vnext_control.actor_grant g WHERE g.actor_code=p_actor AND scope='SYNTHETIC' AND permission='WRITE') AND EXISTS(SELECT 1 FROM location_master.usage_type_access g WHERE g.actor=p_actor AND permission='WRITE'),false),
 'verify',coalesce(a.active AND a.principal_kind='HUMAN' AND EXISTS(SELECT 1 FROM vnext_control.actor_grant g WHERE g.actor_code=p_actor AND scope='SYNTHETIC' AND permission='REVIEW') AND EXISTS(SELECT 1 FROM location_master.usage_type_access g WHERE g.actor=p_actor AND permission='VERIFY'),false),
 'review',coalesce(a.active AND a.principal_kind='HUMAN' AND EXISTS(SELECT 1 FROM vnext_control.actor_grant g WHERE g.actor_code=p_actor AND scope='SYNTHETIC' AND permission='REVIEW') AND EXISTS(SELECT 1 FROM location_master.usage_type_access g WHERE g.actor=p_actor AND permission='REVIEW'),false),
 'human',coalesce(a.active AND a.principal_kind='HUMAN',false)) FROM (SELECT 1) singleton LEFT JOIN vnext_control.actor a ON a.code=p_actor
$$;
CREATE FUNCTION location_master.usage_type_replay(p_actor text,p_command jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE identity text;prior location_master.usage_type_action;BEGIN
 identity:=location_master.usage_type_authorize(p_actor,CASE p_command->>'action' WHEN 'VERIFY' THEN 'VERIFY' WHEN 'APPROVE' THEN 'REVIEW' ELSE 'WRITE' END);
 SELECT * INTO prior FROM location_master.usage_type_action WHERE identity_code=identity AND request_id=(p_command->>'requestId')::uuid;
 IF NOT FOUND THEN RETURN NULL;END IF;IF prior.digest IS DISTINCT FROM encode(sha256(convert_to(p_command::text,'UTF8')),'hex') THEN RAISE EXCEPTION 'REQUEST_CONFLICT';END IF;
 PERFORM location_master.usage_type_read(p_actor,jsonb_build_object('id',prior.usage_type_id,'versionId',prior.result->>'versionId'));RETURN prior.result;
END $$;
-- Boundary reads remain available when qualification has gaps, allowing a truthful
-- segmented evaluation instead of hiding a middle interval behind its endpoints.
CREATE FUNCTION location_master.usage_type_boundaries(p_actor text,p_pin jsonb,p_from timestamp,p_to timestamp,p_r timestamp) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE exact jsonb;current_version location_master.usage_type_version;result jsonb;BEGIN
 PERFORM location_master.use_closed(p_pin,ARRAY['owner','id','versionId','version']);IF p_pin->>'owner' IS DISTINCT FROM 'location-master/usage-type' OR p_from IS NULL OR p_r IS NULL OR p_to<=p_from THEN RAISE EXCEPTION 'INVALID_BUSINESS_PERIOD';END IF;
 exact:=location_master.usage_type_read(p_actor,jsonb_build_object('id',p_pin->>'id','versionId',p_pin->>'versionId','recordAsOf',to_char(p_r,'YYYY-MM-DD"T"HH24:MI:SS.US')))->0;
 IF exact IS NULL OR exact->>'version' IS DISTINCT FROM p_pin->>'version' OR exact->>'status' IS DISTINCT FROM 'APPROVED' THEN RAISE EXCEPTION 'BLOCKED_DEPENDENCY';END IF;
 SELECT v.* INTO current_version FROM location_master.usage_type_version v JOIN location_master.usage_type_approval a ON a.version_id=v.id WHERE v.usage_type_id=(p_pin->>'id')::uuid AND v.recorded_at<=p_r AND a.recorded_at<=p_r ORDER BY v.number DESC LIMIT 1;
 PERFORM location_master.usage_type_read(p_actor,jsonb_build_object('id',p_pin->>'id','versionId',current_version.id,'recordAsOf',to_char(p_r,'YYYY-MM-DD"T"HH24:MI:SS.US')));
 SELECT coalesce(jsonb_agg(to_char(point,'YYYY-MM-DD"T"HH24:MI:SS.US') ORDER BY point),'[]') INTO result FROM (
  SELECT DISTINCT point FROM (
   SELECT governance_catalog.contract_time(current_version.content->>'validFrom') point UNION ALL SELECT governance_catalog.contract_time(current_version.content->>'validTo') WHERE current_version.content->>'validTo' IS NOT NULL
   UNION ALL SELECT e.recorded_at FROM location_master.usage_type_action e WHERE e.usage_type_id=(p_pin->>'id')::uuid AND e.action IN ('ENABLE','DISABLE') AND e.recorded_at<=p_r
   UNION ALL SELECT lower(s) FROM unnest(governance_catalog.source_valid_spans((current_version.content->>'sourceVersionId')::uuid,p_r)) s
   UNION ALL SELECT upper(s) FROM unnest(governance_catalog.source_valid_spans((current_version.content->>'sourceVersionId')::uuid,p_r)) s
  ) points WHERE point>p_from AND (p_to IS NULL OR point<p_to)
 ) bounded;RETURN result;
END $$;
CREATE FUNCTION location_master.usage_type_require_enabled(p_actor text,p_pin jsonb,p_r timestamp) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE exact jsonb;BEGIN
 PERFORM location_master.use_closed(p_pin,ARRAY['owner','id','versionId','version']);IF p_pin->>'owner' IS DISTINCT FROM 'location-master/usage-type' OR p_r IS NULL THEN RAISE EXCEPTION 'BLOCKED_DEPENDENCY';END IF;
 exact:=location_master.usage_type_read(p_actor,jsonb_build_object('id',p_pin->>'id','versionId',p_pin->>'versionId','recordAsOf',to_char(p_r,'YYYY-MM-DD"T"HH24:MI:SS.US')))->0;
 IF exact IS NULL OR exact->>'version' IS DISTINCT FROM p_pin->>'version' OR exact->>'status' IS DISTINCT FROM 'APPROVED' THEN RAISE EXCEPTION 'BLOCKED_DEPENDENCY';END IF;
 IF NOT location_master.usage_type_enabled((p_pin->>'id')::uuid,p_r,p_r) THEN RAISE EXCEPTION 'USAGE_TYPE_DISABLED';END IF;
END $$;
CREATE FUNCTION location_master.usage_type_window(p_actor text,p_pin jsonb,p_code text,p_from timestamp,p_to timestamp,p_r timestamp) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE exact jsonb;current_version location_master.usage_type_version;points jsonb;point text;starts timestamp[];n integer;parts jsonb:='[]';stop_at timestamp;BEGIN
 points:=location_master.usage_type_boundaries(p_actor,p_pin,p_from,p_to,p_r);
 exact:=location_master.usage_type_read(p_actor,jsonb_build_object('id',p_pin->>'id','versionId',p_pin->>'versionId','recordAsOf',to_char(p_r,'YYYY-MM-DD"T"HH24:MI:SS.US')))->0;
 IF exact->>'code' IS DISTINCT FROM p_code OR NOT tsrange(governance_catalog.contract_time(exact->>'validFrom'),CASE WHEN exact->>'validTo' IS NULL THEN NULL ELSE governance_catalog.contract_time(exact->>'validTo') END,'[)') @> tsrange(p_from,p_to,'[)') THEN RAISE EXCEPTION 'USAGE_TYPE_PERIOD_NOT_COVERED';END IF;
 SELECT v.* INTO current_version FROM location_master.usage_type_version v JOIN location_master.usage_type_approval a ON a.version_id=v.id WHERE v.usage_type_id=(p_pin->>'id')::uuid AND v.recorded_at<=p_r AND a.recorded_at<=p_r ORDER BY v.number DESC LIMIT 1;
 IF NOT tsrange(governance_catalog.contract_time(current_version.content->>'validFrom'),CASE WHEN current_version.content->>'validTo' IS NULL THEN NULL ELSE governance_catalog.contract_time(current_version.content->>'validTo') END,'[)') @> tsrange(p_from,p_to,'[)') OR NOT governance_catalog.source_valid_spans((current_version.content->>'sourceVersionId')::uuid,p_r) @> tsrange(p_from,p_to,'[)') THEN RAISE EXCEPTION 'USAGE_TYPE_PERIOD_NOT_COVERED';END IF;
 starts:=ARRAY[p_from];FOR point IN SELECT jsonb_array_elements_text(points) LOOP starts:=array_append(starts,governance_catalog.contract_time(point));END LOOP;
 FOR n IN 1..array_length(starts,1) LOOP stop_at:=CASE WHEN n=array_length(starts,1) THEN p_to ELSE starts[n+1] END;
  IF NOT location_master.usage_type_enabled((p_pin->>'id')::uuid,starts[n],p_r) THEN RAISE EXCEPTION 'USAGE_TYPE_DISABLED';END IF;
  parts:=parts||jsonb_build_array(jsonb_build_object('from',to_char(starts[n],'YYYY-MM-DD"T"HH24:MI:SS.US'),'to',to_char(stop_at,'YYYY-MM-DD"T"HH24:MI:SS.US'),'versionId',current_version.id,'version',current_version.number::text));
 END LOOP;RETURN jsonb_build_object('id',p_pin->>'id','versionId',p_pin->>'versionId','version',p_pin->>'version','code',p_code,'meaning',exact->>'meaning','parts',parts);
END $$;
CREATE TRIGGER location_use_key_immutable BEFORE UPDATE OR DELETE ON vnext_control.location_use_write_authority FOR EACH ROW EXECUTE FUNCTION vnext_control.immutable();
DO $$DECLARE tab text;f record;BEGIN
 FOREACH tab IN ARRAY ARRAY['usage_type','usage_type_version','usage_type_verification','usage_type_approval'] LOOP EXECUTE format('CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON location_master.%I FOR EACH ROW EXECUTE FUNCTION vnext_control.immutable()',tab);END LOOP;
 FOREACH tab IN ARRAY ARRAY['usage_type','usage_type_version','usage_type_verification','usage_type_approval','usage_type_action','usage_type_access'] LOOP EXECUTE format('ALTER TABLE location_master.%I ENABLE ROW LEVEL SECURITY',tab);EXECUTE format('REVOKE ALL ON location_master.%I FROM PUBLIC,hdi_prototype',tab);END LOOP;
 FOR f IN SELECT p.oid::regprocedure name FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='location_master' AND (p.proname LIKE 'usage_type_%' OR p.proname IN ('use_closed','use_attest','use_owner_ready')) LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,hdi_prototype',f.name);END LOOP;
END $$;
ALTER TABLE vnext_control.location_use_write_authority ENABLE ROW LEVEL SECURITY;REVOKE ALL ON vnext_control.location_use_write_authority FROM PUBLIC,hdi_prototype;
