SELECT pg_advisory_xact_lock(901002);
-- ORG13 facts belong to Location Owner. Catalog remains the only outcome ledger.
CREATE TABLE location_master.use_access(actor text NOT NULL REFERENCES vnext_control.actor(code),campus_id uuid NOT NULL REFERENCES organization_master.campus(id),scope text NOT NULL CHECK(scope IN ('NORTH','SOUTH')),permission text NOT NULL CHECK(permission IN ('READ','WRITE','REVIEW','VERIFY','READ_RESTRICTED')),PRIMARY KEY(actor,campus_id,scope,permission));
CREATE TABLE location_master.use_input(id uuid PRIMARY KEY DEFAULT uuidv7(),revision uuid NOT NULL DEFAULT uuidv7(),job_id uuid NOT NULL REFERENCES governance_catalog.import_job(id),job_revision uuid NOT NULL REFERENCES governance_catalog.import_input_revision(id),maker text NOT NULL REFERENCES vnext_control.actor(code),identity_code text NOT NULL,request_id uuid NOT NULL,digest text NOT NULL CHECK(digest ~ '^[a-f0-9]{64}$'),campus_ids uuid[] NOT NULL CHECK(cardinality(campus_ids)>0),scope text NOT NULL CHECK(scope IN ('NORTH','SOUTH')),envelope jsonb NOT NULL,recorded_at timestamp NOT NULL DEFAULT timezone('Asia/Shanghai',clock_timestamp()),UNIQUE(identity_code,request_id),UNIQUE(job_id,job_revision));
CREATE TABLE location_master.use_verification(id uuid PRIMARY KEY DEFAULT uuidv7(),input_id uuid NOT NULL REFERENCES location_master.use_input(id),number bigint NOT NULL CHECK(number>0),actor text NOT NULL REFERENCES vnext_control.actor(code),identity_code text NOT NULL,request_id uuid NOT NULL,digest text NOT NULL CHECK(digest ~ '^[a-f0-9]{64}$'),envelope jsonb NOT NULL,rows jsonb NOT NULL CHECK(jsonb_typeof(rows)='array' AND jsonb_array_length(rows) BETWEEN 1 AND 100),recorded_at timestamp NOT NULL DEFAULT timezone('Asia/Shanghai',clock_timestamp()),UNIQUE(identity_code,request_id),UNIQUE(input_id,number));
CREATE TABLE location_master.use_relation(id uuid PRIMARY KEY DEFAULT uuidv7(),target_type text NOT NULL CHECK(target_type IN ('ORG','UNIT','WARD','NURSING')),target_id uuid NOT NULL,campus_id uuid NOT NULL REFERENCES organization_master.campus(id),location_id uuid NOT NULL REFERENCES location_master.location(id),usage_type_id uuid NOT NULL REFERENCES location_master.usage_type(id),scope text NOT NULL CHECK(scope IN ('NORTH','SOUTH')),applicability jsonb NOT NULL,source_system_id uuid NOT NULL REFERENCES governance_catalog.object(id),source_alias text NOT NULL CHECK(length(source_alias) BETWEEN 1 AND 64 AND source_alias ~ '\S'),UNIQUE(source_system_id,source_alias));
CREATE INDEX use_location_scope ON location_master.use_relation(location_id,campus_id);
CREATE INDEX use_primary_target ON location_master.use_relation(target_type,target_id,campus_id,usage_type_id);
CREATE TABLE location_master.use_change(id uuid PRIMARY KEY DEFAULT uuidv7(),input_id uuid NOT NULL UNIQUE REFERENCES location_master.use_input(id),candidate_id uuid NOT NULL UNIQUE REFERENCES governance_catalog.apply_candidate(id),digest text NOT NULL,results jsonb NOT NULL,recorded_at timestamp NOT NULL);
CREATE TABLE location_master.use_apply_binding(candidate_id uuid PRIMARY KEY REFERENCES governance_catalog.apply_candidate(id),input_id uuid NOT NULL REFERENCES location_master.use_input(id),candidate_digest text NOT NULL,writes_digest text NOT NULL,writes_hash text NOT NULL,verification_id uuid NOT NULL REFERENCES location_master.use_verification(id),verification_number bigint NOT NULL,verification_digest text NOT NULL);
CREATE TABLE location_master.use_version(id uuid PRIMARY KEY DEFAULT uuidv7(),use_id uuid NOT NULL REFERENCES location_master.use_relation(id),number bigint NOT NULL CHECK(number>0),action text NOT NULL CHECK(action IN ('CREATE','REVISE','END')),valid_from timestamp NOT NULL,valid_to timestamp,facts jsonb NOT NULL,reason text NOT NULL CHECK(length(reason) BETWEEN 1 AND 2000 AND reason ~ '\S'),change_id uuid NOT NULL REFERENCES location_master.use_change(id) DEFERRABLE INITIALLY DEFERRED,recorded_at timestamp NOT NULL,UNIQUE(use_id,number),CHECK(valid_to IS NULL OR valid_to>valid_from),CHECK(action<>'END' OR valid_to IS NULL));
CREATE TABLE location_master.use_withdrawal(input_id uuid PRIMARY KEY REFERENCES location_master.use_input(id),actor text NOT NULL REFERENCES vnext_control.actor(code),request_id uuid NOT NULL,recorded_at timestamp NOT NULL DEFAULT timezone('Asia/Shanghai',clock_timestamp()));
CREATE FUNCTION location_master.use_text_fields(p_value jsonb,p_required text[],p_nullable text[] DEFAULT ARRAY[]::text[]) RETURNS void LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog AS $$DECLARE key text;BEGIN FOREACH key IN ARRAY p_required LOOP IF jsonb_typeof(p_value->key) IS DISTINCT FROM 'string' THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;END LOOP;FOREACH key IN ARRAY p_nullable LOOP IF jsonb_typeof(p_value->key) IS NULL OR jsonb_typeof(p_value->key) NOT IN ('string','null') THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;END LOOP;END $$;
CREATE FUNCTION location_master.use_envelope_guard(p_value jsonb) RETURNS void LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog AS $$BEGIN PERFORM location_master.use_closed(p_value,ARRAY['keyId','nonce','tag','ciphertext']);PERFORM location_master.use_text_fields(p_value,ARRAY['keyId','nonce','tag','ciphertext']);IF length(p_value->>'keyId') NOT BETWEEN 1 AND 128 OR p_value->>'nonce' !~ '^[a-f0-9]{24}$' OR p_value->>'tag' !~ '^[a-f0-9]{32}$' OR p_value->>'ciphertext' !~ '^([a-f0-9]{2})+$' OR length(p_value->>'ciphertext')>8388608 THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;END $$;

CREATE FUNCTION location_master.use_authorize(p_actor text,p_campus uuid,p_permission text) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE identity text;c jsonb;BEGIN
 PERFORM pg_advisory_xact_lock(901002);IF p_permission NOT IN ('READ','WRITE','REVIEW','VERIFY','READ_RESTRICTED') THEN RAISE EXCEPTION 'ACCESS_DENIED';END IF;
 IF p_permission IN ('WRITE','VERIFY','REVIEW') AND NOT EXISTS(SELECT 1 FROM vnext_control.actor WHERE code=p_actor AND active AND principal_kind='HUMAN') THEN RAISE EXCEPTION 'ACCESS_DENIED';END IF;
 identity:=vnext_control.authorize(p_actor,'SYNTHETIC',CASE WHEN p_permission IN ('REVIEW','VERIFY') THEN 'REVIEW' WHEN p_permission='WRITE' THEN 'WRITE' ELSE 'READ' END);c:=organization_master.campus_snapshot(p_actor,p_campus);
 IF NOT EXISTS(SELECT 1 FROM location_master.use_access WHERE actor=p_actor AND campus_id=p_campus AND scope=c->>'scope' AND permission=p_permission) THEN RAISE EXCEPTION 'ACCESS_DENIED';END IF;RETURN identity;
END $$;
CREATE FUNCTION location_master.use_input_read(p_actor text,p_id uuid,p_permission text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE r location_master.use_input;v location_master.use_verification;campus uuid;BEGIN
 PERFORM vnext_control.authorize(p_actor,'SYNTHETIC','READ');SELECT * INTO r FROM location_master.use_input WHERE id=p_id;IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND';END IF;
 FOREACH campus IN ARRAY r.campus_ids LOOP PERFORM location_master.use_authorize(p_actor,campus,p_permission);PERFORM location_master.use_authorize(p_actor,campus,'READ');END LOOP;
 PERFORM governance_catalog.import_job_context(p_actor,jsonb_build_object('scope','SYNTHETIC','jobId',r.job_id));
 IF p_permission='READ_RESTRICTED' THEN INSERT INTO vnext_control.audit(actor_code,object_id,action,reason,content_digest) VALUES(p_actor,r.id,'LOCATION_USE_READ_RESTRICTED','ORG13_SOURCE',r.digest);END IF;
 SELECT * INTO v FROM location_master.use_verification WHERE input_id=r.id ORDER BY number DESC LIMIT 1;
 RETURN to_jsonb(r)||jsonb_build_object('withdrawn',EXISTS(SELECT 1 FROM location_master.use_withdrawal WHERE input_id=r.id),'verification',CASE WHEN v.id IS NULL THEN NULL ELSE to_jsonb(v) END);
END $$;
CREATE FUNCTION location_master.use_job_read(p_actor text,p_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE r jsonb;BEGIN r:=location_master.use_input_read(p_actor,p_id,'READ_RESTRICTED');RETURN governance_catalog.import_job_context(p_actor,jsonb_build_object('scope','SYNTHETIC','jobId',r->>'job_id'));END $$;
CREATE FUNCTION location_master.use_record_time() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE point text;k bytea;ip bytea:=decode(repeat('36',64),'hex');op bytea:=decode(repeat('5c',64),'hex');i integer;BEGIN
 PERFORM pg_advisory_xact_lock(901002);SELECT decode(key_hex,'hex') INTO k FROM vnext_control.location_use_write_authority;IF k IS NULL THEN RAISE EXCEPTION 'LOCATION_USE_OWNER_NOT_PROVISIONED';END IF;
 FOR i IN 0..31 LOOP ip:=set_byte(ip,i,get_byte(ip,i)#get_byte(k,i));op:=set_byte(op,i,get_byte(op,i)#get_byte(k,i));END LOOP;point:=to_char(timezone('Asia/Shanghai',clock_timestamp()),'YYYY-MM-DD"T"HH24:MI:SS.US');
 RETURN jsonb_build_object('recordAt',point,'recordAtProof',encode(sha256(op||sha256(ip||convert_to('LOCATION_USE_TRANSACTION_R_V1|'||pg_current_xact_id()::text||'|'||point,'UTF8'))),'hex'));
END $$;
CREATE FUNCTION governance_catalog.use_source_reference(p_actor text,p_source uuid,p_version uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN PERFORM governance_catalog.unit_ward_source_reference(p_actor,p_source,p_version);END $$;
CREATE FUNCTION governance_catalog.use_source_coverage(p_actor text,p_source uuid,p_from timestamp,p_to timestamp,p_r timestamp) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN RETURN governance_catalog.unit_ward_source_coverage(p_actor,p_source,p_from,p_to,p_r);END $$;
CREATE FUNCTION governance_catalog.use_source_windows(p_actor text,p_source uuid,p_from timestamp,p_to timestamp,p_r timestamp) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN RETURN governance_catalog.unit_ward_source_windows(p_actor,p_source,p_from,p_to,p_r);END $$;

-- Master-only Department admission deliberately adds no clinical-service permit.
CREATE FUNCTION department_master.use_department_window(p_actor text,p_id uuid,p_from timestamp,p_to timestamp,p_r timestamp) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE basis jsonb;part jsonb;v department_master.version;parts jsonb:='[]';source jsonb;BEGIN
 basis:=department_master.nursing_management_coverage(p_actor,p_id,p_from,p_to,p_r);
 FOR part IN SELECT value FROM jsonb_array_elements(basis->'parts') LOOP
  SELECT * INTO v FROM department_master.version WHERE id=(part->>'versionId')::uuid AND department_id=p_id AND recorded_at<=p_r;IF NOT FOUND THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;
  source:=governance_catalog.use_source_coverage(p_actor,(v.facts->>'sourceSystemId')::uuid,(part->>'from')::timestamp,(part->>'to')::timestamp,p_r);parts:=parts||jsonb_build_array(part||jsonb_build_object('source',source));
 END LOOP;RETURN jsonb_set(basis,'{parts}',parts);
END $$;
CREATE FUNCTION department_master.use_department_reference(p_actor text,p_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN PERFORM department_master.snapshot(p_actor,p_id);END $$;
CREATE FUNCTION department_master.use_department_boundaries(p_actor text,p_id uuid,p_from timestamp,p_to timestamp,p_r timestamp) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE points jsonb;v record;part jsonb;BEGIN
 PERFORM department_master.use_department_reference(p_actor,p_id);SELECT coalesce(jsonb_agg(to_char(t,'YYYY-MM-DD"T"HH24:MI:SS.US') ORDER BY t),'[]') INTO points FROM(SELECT DISTINCT t FROM(SELECT valid_from t FROM department_master.version WHERE department_id=p_id AND recorded_at<=p_r UNION SELECT valid_to FROM department_master.version WHERE department_id=p_id AND recorded_at<=p_r UNION SELECT effective_at FROM department_master.lifecycle_version WHERE department_id=p_id AND recorded_at<=p_r) q WHERE t>=p_from AND (p_to IS NULL OR t<=p_to)) bounds;
 FOR v IN SELECT DISTINCT (facts->>'sourceSystemId')::uuid source_id FROM department_master.version WHERE department_id=p_id AND recorded_at<=p_r LOOP FOR part IN SELECT value FROM jsonb_array_elements(governance_catalog.use_source_windows(p_actor,v.source_id,p_from,p_to,p_r)) LOOP points:=points||jsonb_build_array(part->>'from');IF part->>'to' IS NOT NULL THEN points:=points||jsonb_build_array(part->>'to');END IF;END LOOP;END LOOP;RETURN points;
END $$;
CREATE FUNCTION organization_master.use_location_boundaries(p_actor text,p_id uuid,p_from timestamp,p_to timestamp,p_r timestamp) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE points jsonb;BEGIN PERFORM organization_master.campus_snapshot(p_actor,p_id);SELECT coalesce(jsonb_agg(to_char(t,'YYYY-MM-DD"T"HH24:MI:SS.US') ORDER BY t),'[]') INTO points FROM(SELECT DISTINCT t FROM(SELECT valid_from t FROM organization_master.campus_event WHERE campus_id=p_id AND recorded_at<=p_r UNION SELECT valid_to FROM organization_master.campus_event WHERE campus_id=p_id AND recorded_at<=p_r) q WHERE t>=p_from AND (p_to IS NULL OR t<=p_to)) bounds;RETURN points;END $$;
CREATE FUNCTION location_master.use_ancestor_windows(p_id uuid,p_from timestamp,p_to timestamp,p_r timestamp) RETURNS TABLE(location_id uuid,version_id uuid,period tsrange) LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$
 WITH RECURSIVE effective AS(
  SELECT v.location_id,v.id version_id,v.parent_id,
   tsmultirange(tsrange(v.valid_from,v.valid_to,'[)'))
   -coalesce((SELECT range_agg(tsrange(n.valid_from,n.valid_to,'[)')) FROM location_master.version n WHERE n.location_id=v.location_id AND n.number>v.number AND n.action<>'CLOSE' AND n.recorded_at<=p_r),'{}'::tsmultirange)
   -coalesce((SELECT range_agg(tsrange(n.valid_from,NULL,'[)')) FROM location_master.version n WHERE n.location_id=v.location_id AND n.action='CLOSE' AND n.recorded_at<=p_r),'{}'::tsmultirange) spans
  FROM location_master.version v WHERE v.action<>'CLOSE' AND v.recorded_at<=p_r
 ),ancestry(id,requested) AS(
  SELECT p_id,tsrange(p_from,p_to,'[)') UNION
  SELECT e.parent_id,p.piece FROM ancestry a JOIN effective e ON e.location_id=a.id CROSS JOIN LATERAL unnest(e.spans*tsmultirange(a.requested)) p(piece) WHERE e.parent_id IS NOT NULL
 ) SELECT e.location_id,e.version_id,p.piece FROM ancestry a JOIN effective e ON e.location_id=a.id CROSS JOIN LATERAL unnest(e.spans*tsmultirange(a.requested)) p(piece)
$$;
CREATE FUNCTION location_master.use_location_boundaries(p_actor text,p_id uuid,p_campus uuid,p_from timestamp,p_to timestamp,p_r timestamp) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE l location_master.location;source_row record;source_parts jsonb;part jsonb;points jsonb;ancestors uuid[];BEGIN
 SELECT * INTO l FROM location_master.location WHERE id=p_id;IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND';END IF;PERFORM location_master.authorize(p_actor,l.campus_id,l.scope,'READ');IF l.campus_id<>p_campus THEN RAISE EXCEPTION 'LOCATION_CAMPUS_MISMATCH';END IF;
 SELECT array_agg(DISTINCT a.location_id) INTO ancestors FROM location_master.use_ancestor_windows(p_id,p_from,p_to,p_r) a;
 SELECT coalesce(jsonb_agg(to_char(t,'YYYY-MM-DD"T"HH24:MI:SS.US') ORDER BY t),'[]') INTO points FROM(SELECT DISTINCT t FROM(SELECT valid_from t FROM location_master.version v WHERE v.location_id=ANY(ancestors) AND v.recorded_at<=p_r UNION SELECT valid_to FROM location_master.version v WHERE v.location_id=ANY(ancestors) AND v.recorded_at<=p_r AND valid_to IS NOT NULL) bounds WHERE t>=p_from AND (p_to IS NULL OR t<=p_to)) q;
 points:=points||organization_master.use_location_boundaries(p_actor,p_campus,p_from,p_to,p_r);
 FOR source_row IN SELECT DISTINCT (x.facts->'source'->>'sourceSystemId')::uuid source_id FROM location_master.version x JOIN location_master.use_ancestor_windows(p_id,p_from,p_to,p_r) a ON a.version_id=x.id LOOP
  source_parts:=governance_catalog.use_source_windows(p_actor,source_row.source_id,p_from,p_to,p_r);FOR part IN SELECT value FROM jsonb_array_elements(source_parts) LOOP points:=points||jsonb_build_array(part->>'from');IF part->>'to' IS NOT NULL THEN points:=points||jsonb_build_array(part->>'to');END IF;END LOOP;
 END LOOP;RETURN points;
END $$;
CREATE FUNCTION location_master.use_location_window(p_actor text,p_id uuid,p_campus uuid,p_from timestamp,p_to timestamp,p_r timestamp) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE l location_master.location;n location_master.location;v location_master.version;parent location_master.version;point timestamp;finish timestamp;cursor_id uuid;visited uuid[];graph jsonb;parts jsonb:='[]';campus jsonb;source jsonb;child_type text;parent_type text;BEGIN
 IF p_from IS NULL OR p_to<=p_from THEN RAISE EXCEPTION 'INVALID_BUSINESS_PERIOD';END IF;SELECT * INTO l FROM location_master.location WHERE id=p_id;IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND';END IF;PERFORM location_master.authorize(p_actor,l.campus_id,l.scope,'READ');IF l.campus_id<>p_campus THEN RAISE EXCEPTION 'LOCATION_CAMPUS_MISMATCH';END IF;
 campus:=organization_master.nursing_campus_coverage(p_actor,p_campus,p_from,p_to,p_r);
 FOR point,finish IN WITH bounds AS(SELECT p_from t UNION SELECT value::timestamp FROM jsonb_array_elements_text(location_master.use_location_boundaries(p_actor,p_id,p_campus,p_from,p_to,p_r)) UNION SELECT p_to WHERE p_to IS NOT NULL),segments AS(SELECT t,lead(t) OVER(ORDER BY t) e FROM bounds) SELECT t,e FROM segments WHERE t>=p_from AND (p_to IS NULL OR t<p_to) LOOP
  graph:='[]';cursor_id:=p_id;visited:=ARRAY[]::uuid[];child_type:=NULL;
  WHILE cursor_id IS NOT NULL LOOP
   IF cursor_id=ANY(visited) THEN RAISE EXCEPTION 'LOCATION_CYCLE';END IF;visited:=array_append(visited,cursor_id);SELECT * INTO n FROM location_master.location WHERE id=cursor_id;IF NOT FOUND OR n.campus_id<>p_campus THEN RAISE EXCEPTION 'LOCATION_CAMPUS_MISMATCH';END IF;PERFORM location_master.authorize(p_actor,n.campus_id,n.scope,'READ');
   SELECT * INTO v FROM location_master.version x WHERE x.location_id=cursor_id AND x.action<>'CLOSE' AND x.recorded_at<=p_r AND x.valid_from<=point AND (x.valid_to IS NULL OR point<x.valid_to) AND NOT EXISTS(SELECT 1 FROM location_master.version e WHERE e.location_id=cursor_id AND e.action='CLOSE' AND e.recorded_at<=p_r AND e.valid_from<=point) ORDER BY x.number DESC LIMIT 1;
   IF NOT FOUND THEN RAISE EXCEPTION 'LOCATION_WINDOW_NOT_COVERED';END IF;parent_type:=v.facts->>'locationType';IF cursor_id=p_id AND parent_type NOT IN ('ROOM','CLINIC_ROOM','OPERATING_ROOM','WAREHOUSE','DISPENSING_WINDOW') THEN RAISE EXCEPTION 'LOCATION_TYPE_INVALID';END IF;
   IF child_type IS NOT NULL AND NOT ((child_type='BUILDING' AND parent_type='CAMPUS') OR (child_type='FLOOR' AND parent_type='BUILDING') OR (child_type IN ('ROOM','CLINIC_ROOM','OPERATING_ROOM','WAREHOUSE') AND parent_type='FLOOR') OR (child_type='DISPENSING_WINDOW' AND parent_type IN ('FLOOR','ROOM','CLINIC_ROOM','OPERATING_ROOM','WAREHOUSE'))) THEN RAISE EXCEPTION 'LOCATION_TYPE_INVALID';END IF;
   IF parent_type='CAMPUS' AND v.parent_id IS NOT NULL OR parent_type<>'CAMPUS' AND v.parent_id IS NULL THEN RAISE EXCEPTION 'PARENT_PERIOD_NOT_COVERED';END IF;
   IF parent_type NOT IN ('CAMPUS','BUILDING') AND coalesce(v.facts->>'floorLabel','') !~ '\S' THEN RAISE EXCEPTION 'FLOOR_LABEL_REQUIRED';END IF;IF parent_type IN ('ROOM','CLINIC_ROOM','OPERATING_ROOM') AND coalesce(v.facts->>'roomNumber','') !~ '\S' THEN RAISE EXCEPTION 'ROOM_NUMBER_REQUIRED';END IF;
   source:=governance_catalog.use_source_coverage(p_actor,(v.facts->'source'->>'sourceSystemId')::uuid,point,finish,p_r);graph:=graph||jsonb_build_array(jsonb_build_object('id',n.id,'versionId',v.id,'version',v.number::text,'type',parent_type,'parentId',v.parent_id,'source',source));child_type:=parent_type;cursor_id:=v.parent_id;
  END LOOP;parts:=parts||jsonb_build_array(jsonb_build_object('from',to_char(point,'YYYY-MM-DD"T"HH24:MI:SS.US'),'to',to_char(finish,'YYYY-MM-DD"T"HH24:MI:SS.US'),'graph',graph));
 END LOOP;IF jsonb_array_length(parts)=0 THEN RAISE EXCEPTION 'LOCATION_WINDOW_NOT_COVERED';END IF;RETURN jsonb_build_object('id',p_id,'campusId',p_campus,'parts',parts,'campus',campus);
END $$;

CREATE FUNCTION location_master.use_reference_access(p_actor text,p_a jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN
 PERFORM location_master.use_closed(p_a,ARRAY['targetType','target','campus','location','usageType']);PERFORM location_master.use_closed(p_a->'target',ARRAY['owner','id']);PERFORM location_master.use_closed(p_a->'campus',ARRAY['owner','id']);PERFORM location_master.use_closed(p_a->'location',ARRAY['owner','id']);PERFORM location_master.use_closed(p_a->'usageType',ARRAY['owner','id']);
 PERFORM location_master.use_text_fields(p_a,ARRAY['targetType']);PERFORM location_master.use_text_fields(p_a->'target',ARRAY['owner','id']);PERFORM location_master.use_text_fields(p_a->'campus',ARRAY['owner','id']);PERFORM location_master.use_text_fields(p_a->'location',ARRAY['owner','id']);PERFORM location_master.use_text_fields(p_a->'usageType',ARRAY['owner','id']);
 IF p_a->'campus'->>'owner' IS DISTINCT FROM 'organization-master/campus' OR p_a->'location'->>'owner' IS DISTINCT FROM 'location-master' OR p_a->'usageType'->>'owner' IS DISTINCT FROM 'location-master/usage-type' OR p_a->'target'->>'owner' IS DISTINCT FROM (CASE p_a->>'targetType' WHEN 'ORG' THEN 'department-master' WHEN 'UNIT' THEN 'care-organization/unit' WHEN 'WARD' THEN 'care-organization/ward' WHEN 'NURSING' THEN 'care-organization/nursing' END) OR p_a->>'targetType' NOT IN ('ORG','UNIT','WARD','NURSING') THEN RAISE EXCEPTION 'REFERENCE_INVALID';END IF;
 PERFORM location_master.use_authorize(p_actor,(p_a->'campus'->>'id')::uuid,'READ');PERFORM location_master.snapshot(p_actor,(p_a->'location'->>'id')::uuid);PERFORM location_master.usage_type_authorize(p_actor,'READ');IF NOT EXISTS(SELECT 1 FROM location_master.usage_type WHERE id=(p_a->'usageType'->>'id')::uuid) THEN RAISE EXCEPTION 'NOT_FOUND';END IF;
 CASE p_a->>'targetType' WHEN 'ORG' THEN PERFORM department_master.snapshot(p_actor,(p_a->'target'->>'id')::uuid);WHEN 'UNIT' THEN PERFORM care_organization.snapshot(p_actor,(p_a->'target'->>'id')::uuid);WHEN 'WARD' THEN PERFORM care_organization.ward_snapshot(p_actor,(p_a->'target'->>'id')::uuid);WHEN 'NURSING' THEN PERFORM care_organization.nursing_snapshot(p_actor,(p_a->'target'->>'id')::uuid);ELSE RAISE EXCEPTION 'REFERENCE_INVALID';END CASE;
END $$;

CREATE FUNCTION location_master.use_unit_current_shape(p_basis jsonb) RETURNS void LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog AS $$DECLARE part jsonb;BEGIN IF jsonb_typeof(p_basis->'parts') IS DISTINCT FROM 'array' OR jsonb_typeof(p_basis->'current') IS DISTINCT FROM 'array' OR jsonb_array_length(p_basis->'parts')=0 OR jsonb_array_length(p_basis->'parts')<>jsonb_array_length(p_basis->'current') THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;FOR part IN SELECT value FROM jsonb_array_elements(p_basis->'parts') LOOP IF (SELECT count(*) FROM jsonb_array_elements(p_basis->'current') q WHERE q->>'from'=part->>'from' AND q->>'to' IS NOT DISTINCT FROM part->>'to')<>1 THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;END LOOP;END $$;
CREATE FUNCTION location_master.use_upstream_guard(p_actor text,p_a jsonb,p_basis jsonb,p_from timestamp,p_to timestamp,p_r timestamp) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE fresh jsonb;part jsonb;BEGIN
 CASE p_a->>'targetType'
 WHEN 'ORG' THEN fresh:=department_master.use_department_window(p_actor,(p_a->'target'->>'id')::uuid,p_from,p_to,p_r);IF fresh IS DISTINCT FROM p_basis THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;
 WHEN 'UNIT' THEN fresh:=care_organization.ward_management_coverage(p_actor,(p_a->'target'->>'id')::uuid,(p_a->'campus'->>'id')::uuid,p_from,p_to,p_r);IF fresh IS DISTINCT FROM (p_basis-'current') THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;PERFORM location_master.use_unit_current_shape(p_basis);PERFORM care_organization.unit_ward_operating_guard(p_actor,jsonb_build_object('unit',p_basis),p_r);
 WHEN 'WARD' THEN FOR part IN SELECT value FROM jsonb_array_elements(p_basis->'parts') LOOP PERFORM location_master.use_unit_current_shape(part->'unit');END LOOP;PERFORM care_organization.unit_ward_ward_guard(p_actor,jsonb_build_object('ward',p_a->'target','campus',p_a->'campus'),p_basis,p_from,p_to,p_r);
 WHEN 'NURSING' THEN fresh:=care_organization.ward_nursing_master_window(p_actor,'NURSING',(p_a->'target'->>'id')::uuid,(p_a->'campus'->>'id')::uuid,p_from,p_to,p_r);IF fresh IS DISTINCT FROM p_basis THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;
 ELSE RAISE EXCEPTION 'REFERENCE_INVALID';END CASE;
END $$;
CREATE FUNCTION location_master.use_withdraw(p_ticket text,p_signature text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE t jsonb;r location_master.use_input;prior location_master.use_withdrawal;BEGIN
 t:=location_master.use_attest(p_ticket,p_signature);PERFORM location_master.use_closed(t,ARRAY['actor','transaction','inputId','requestId']||(CASE WHEN t ? 'operation' THEN ARRAY['operation'] ELSE ARRAY[]::text[] END));PERFORM location_master.use_text_fields(t,ARRAY['actor','transaction','inputId','requestId']);IF t ? 'operation' AND t->>'operation' IS DISTINCT FROM 'WITHDRAW' THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;r:=jsonb_populate_record(NULL::location_master.use_input,location_master.use_input_read(t->>'actor',(t->>'inputId')::uuid,'WRITE'));
 IF r.identity_code IS DISTINCT FROM vnext_control.authorize(t->>'actor','SYNTHETIC','WRITE') THEN RAISE EXCEPTION 'ACCESS_DENIED';END IF;IF EXISTS(SELECT 1 FROM location_master.use_change WHERE input_id=r.id) THEN RAISE EXCEPTION 'ALREADY_COMMITTED';END IF;
 SELECT * INTO prior FROM location_master.use_withdrawal WHERE input_id=r.id;IF FOUND THEN IF prior.request_id::text IS DISTINCT FROM t->>'requestId' THEN RAISE EXCEPTION 'REQUEST_CONFLICT';END IF;ELSE INSERT INTO location_master.use_withdrawal(input_id,actor,request_id) VALUES(r.id,t->>'actor',(t->>'requestId')::uuid);INSERT INTO vnext_control.audit(actor_code,object_id,action,reason,content_digest) VALUES(t->>'actor',r.id,'LOCATION_USE_WITHDRAW','EXPLICIT_WITHDRAWAL',r.digest);END IF;RETURN jsonb_build_object('inputId',r.id,'status','WITHDRAWN');
END $$;

CREATE FUNCTION location_master.use_mutate(p_ticket text,p_signature text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE t jsonb;actor text;op text;identity text;r location_master.use_input;verify location_master.use_verification;j jsonb;c jsonb;frozen location_master.use_apply_binding;change location_master.use_change;u location_master.use_relation;previous location_master.use_version;declaration location_master.use_version;w jsonb;review_row jsonb;fresh jsonb;codes jsonb;field text;approved_by text;target uuid;root_id uuid;campus uuid;campuses uuid[];from_at timestamp;to_at timestamp;record_at timestamp;k bytea;ip bytea:=decode(repeat('36',64),'hex');opad bytea:=decode(repeat('5c',64),'hex');i integer;reduction boolean;results jsonb:='[]';source_version uuid;BEGIN
 t:=location_master.use_attest(p_ticket,p_signature);PERFORM location_master.use_text_fields(t,ARRAY['actor','transaction','operation']);actor:=t->>'actor';op:=t->>'operation';IF op='WITHDRAW' THEN RETURN location_master.use_withdraw(p_ticket,p_signature);END IF;IF op NOT IN ('STAGE','VERIFY','FREEZE','APPLY') THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;record_at:=timezone('Asia/Shanghai',clock_timestamp());
 IF op='STAGE' THEN
  PERFORM location_master.use_closed(t,ARRAY['operation','actor','transaction','requestId','jobId','revisionId','campus','campusIds','digest','envelope']);IF jsonb_typeof(t->'campusIds') IS DISTINCT FROM 'array' OR jsonb_array_length(t->'campusIds') NOT BETWEEN 1 AND 100 OR t->>'digest' !~ '^[a-f0-9]{64}$' OR t->>'campus' NOT IN ('NORTH','SOUTH') THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
  PERFORM location_master.use_text_fields(t,ARRAY['requestId','jobId','revisionId','campus','digest']);PERFORM location_master.use_envelope_guard(t->'envelope');IF EXISTS(SELECT 1 FROM jsonb_array_elements(t->'campusIds') x WHERE jsonb_typeof(x) IS DISTINCT FROM 'string') THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
  SELECT array_agg(value::uuid) INTO campuses FROM jsonb_array_elements_text(t->'campusIds');IF cardinality(campuses)<>(SELECT count(DISTINCT x) FROM unnest(campuses) x) THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
  FOREACH campus IN ARRAY campuses LOOP identity:=location_master.use_authorize(actor,campus,'WRITE');PERFORM location_master.use_authorize(actor,campus,'READ_RESTRICTED');IF organization_master.campus_snapshot(actor,campus)->>'scope' IS DISTINCT FROM t->>'campus' THEN RAISE EXCEPTION 'LOCATION_USE_ANCHOR_MISMATCH';END IF;END LOOP;
  SELECT * INTO r FROM location_master.use_input WHERE identity_code=identity AND request_id=(t->>'requestId')::uuid;IF FOUND THEN IF r.digest IS DISTINCT FROM t->>'digest' THEN RAISE EXCEPTION 'REQUEST_CONFLICT';END IF;PERFORM location_master.use_job_read(actor,r.id);RETURN jsonb_build_object('inputId',r.id,'revisionId',r.revision,'digest',r.digest);END IF;
  j:=governance_catalog.import_job_context(actor,jsonb_build_object('scope','SYNTHETIC','jobId',t->>'jobId'));IF j->>'submitterIdentity' IS DISTINCT FROM identity OR j->>'currentRevisionId' IS DISTINCT FROM t->>'revisionId' OR j->'contract'->>'dataset' IS DISTINCT FROM 'ORG13' OR j->>'profile' IS DISTINCT FROM 'CORE' OR j->'contract'->'definition'->>'templateVersion' IS DISTINCT FROM 'ORG13_CORE_V1' THEN RAISE EXCEPTION 'STALE_REVISION';END IF;
  INSERT INTO location_master.use_input(job_id,job_revision,maker,identity_code,request_id,digest,campus_ids,scope,envelope) VALUES((j->>'id')::uuid,(j->>'currentRevisionId')::uuid,actor,identity,(t->>'requestId')::uuid,t->>'digest',campuses,t->>'campus',t->'envelope') RETURNING * INTO r;
  INSERT INTO vnext_control.audit(actor_code,object_id,action,reason,content_digest) VALUES(actor,r.id,'LOCATION_USE_INPUT','ORG13_CORE',r.digest);RETURN jsonb_build_object('inputId',r.id,'revisionId',r.revision,'digest',r.digest);
 END IF;
 PERFORM location_master.use_text_fields(t,ARRAY['inputId']);r:=jsonb_populate_record(NULL::location_master.use_input,location_master.use_input_read(actor,(t->>'inputId')::uuid,CASE WHEN op='VERIFY' THEN 'VERIFY' ELSE 'WRITE' END));IF EXISTS(SELECT 1 FROM location_master.use_withdrawal WHERE input_id=r.id) THEN RAISE EXCEPTION 'INPUT_WITHDRAWN';END IF;
 j:=location_master.use_job_read(actor,r.id);source_version:=(j->'contract'->'definition'->>'sourceVersionId')::uuid;
 IF op='VERIFY' THEN
  PERFORM location_master.use_closed(t,ARRAY['operation','actor','transaction','inputId','inputDigest','requestId','digest','envelope','rows','policyVersion']);identity:=vnext_control.authorize(actor,'SYNTHETIC','REVIEW');IF identity=r.identity_code THEN RAISE EXCEPTION 'MAKER_CHECKER_REQUIRED';END IF;IF r.digest IS DISTINCT FROM t->>'inputDigest' THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;
  PERFORM location_master.use_text_fields(t,ARRAY['inputDigest','requestId','digest','policyVersion']);PERFORM location_master.use_envelope_guard(t->'envelope');
  IF t->>'policyVersion' IS DISTINCT FROM 'ORG13_CORE_V1' OR t->>'digest' !~ '^[a-f0-9]{64}$' OR jsonb_typeof(t->'rows') IS DISTINCT FROM 'array' OR jsonb_array_length(t->'rows') NOT BETWEEN 1 AND 100 OR (SELECT count(DISTINCT value->>'row') FROM jsonb_array_elements(t->'rows'))<>jsonb_array_length(t->'rows') THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
  FOR review_row IN SELECT value FROM jsonb_array_elements(t->'rows') LOOP
   PERFORM location_master.use_closed(review_row,ARRAY['row','evidenceId','classificationAccepted','scopeAccepted','policyAccepted','policy','validFrom','validTo']);PERFORM location_master.use_closed(review_row->'policy',ARRAY['kind','version']);
   PERFORM location_master.use_text_fields(review_row,ARRAY['evidenceId','validFrom'],ARRAY['validTo']);PERFORM location_master.use_text_fields(review_row->'policy',ARRAY['kind','version']);
   IF jsonb_typeof(review_row->'row') IS DISTINCT FROM 'number' OR (review_row->>'row')::numeric<>trunc((review_row->>'row')::numeric) OR (review_row->>'row')::integer NOT BETWEEN 1 AND jsonb_array_length(t->'rows') OR jsonb_typeof(review_row->'classificationAccepted') IS DISTINCT FROM 'boolean' OR jsonb_typeof(review_row->'scopeAccepted') IS DISTINCT FROM 'boolean' OR jsonb_typeof(review_row->'policyAccepted') IS DISTINCT FROM 'boolean' OR review_row->'policy'->>'kind' NOT IN ('SHARED','EXCLUSIVE') OR review_row->'policy'->>'version' IS DISTINCT FROM 'WHOLE_LOCATION_V1' THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
   from_at:=location_master.local_time(review_row->>'validFrom');to_at:=CASE WHEN review_row->>'validTo' IS NULL THEN NULL ELSE location_master.local_time(review_row->>'validTo') END;IF to_at<=from_at THEN RAISE EXCEPTION 'INVALID_BUSINESS_PERIOD';END IF;PERFORM governance_catalog.registration_evidence_access(actor,(review_row->>'evidenceId')::uuid,source_version,r.scope);
  END LOOP;
  SELECT * INTO verify FROM location_master.use_verification WHERE identity_code=identity AND request_id=(t->>'requestId')::uuid;IF FOUND THEN IF verify.input_id<>r.id OR verify.digest IS DISTINCT FROM t->>'digest' OR verify.rows IS DISTINCT FROM t->'rows' THEN RAISE EXCEPTION 'REQUEST_CONFLICT';END IF;RETURN jsonb_build_object('verificationId',verify.id);END IF;
  IF EXISTS(SELECT 1 FROM location_master.use_change WHERE input_id=r.id) THEN RAISE EXCEPTION 'ALREADY_COMMITTED';END IF;
  INSERT INTO location_master.use_verification(input_id,number,actor,identity_code,request_id,digest,envelope,rows) VALUES(r.id,(SELECT coalesce(max(number),0)+1 FROM location_master.use_verification WHERE input_id=r.id),actor,identity,(t->>'requestId')::uuid,t->>'digest',t->'envelope',t->'rows') RETURNING * INTO verify;
  INSERT INTO vnext_control.audit(actor_code,object_id,action,reason,content_digest) VALUES(actor,r.id,'LOCATION_USE_VERIFY','CLASSIFICATION_SCOPE_POLICY',verify.digest);RETURN jsonb_build_object('verificationId',verify.id);
 END IF;
 IF op NOT IN ('FREEZE','APPLY') THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
 PERFORM location_master.use_text_fields(t,ARRAY['candidateId','digest','writesDigest']);
 c:=governance_catalog.apply_record(actor,'READ_CANDIDATE',jsonb_build_object('candidateId',(t->>'candidateId')::uuid));IF c->>'digest' IS DISTINCT FROM t->>'digest' OR c->'input'->>'jobId' IS DISTINCT FROM r.id::text OR c->'input'->>'revisionId' IS DISTINCT FROM r.revision::text OR c->>'makerIdentity' IS DISTINCT FROM r.identity_code THEN RAISE EXCEPTION 'APPROVAL_REQUIRED';END IF;
 SELECT * INTO verify FROM location_master.use_verification WHERE input_id=r.id ORDER BY number DESC LIMIT 1;IF NOT FOUND THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;PERFORM location_master.use_job_read(verify.actor,r.id);
 FOREACH campus IN ARRAY r.campus_ids LOOP identity:=location_master.use_authorize(verify.actor,campus,'VERIFY');IF identity IS DISTINCT FROM verify.identity_code OR identity=r.identity_code THEN RAISE EXCEPTION 'MAKER_CHECKER_REQUIRED';END IF;END LOOP;
 IF jsonb_typeof(t->'writes') IS DISTINCT FROM 'array' OR jsonb_array_length(t->'writes')>100 THEN RAISE EXCEPTION 'PLAN_INPUT_LIMIT';END IF;
 IF (op='FREEZE' OR t->>'writeIndex'='1') AND (jsonb_array_length(t->'writes')<1 OR jsonb_array_length(t->'writes')<>jsonb_array_length(verify.rows) OR (SELECT count(DISTINCT value->>'verificationRow') FROM jsonb_array_elements(t->'writes'))<>jsonb_array_length(t->'writes')) THEN RAISE EXCEPTION 'PLAN_INPUT_LIMIT';END IF;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(t->'writes') command_row WHERE command_row->'facts'->'verificationBasis'->>'id' IS DISTINCT FROM verify.id::text OR command_row->'facts'->'verificationBasis'->>'version' IS DISTINCT FROM verify.number::text OR command_row->'facts'->'verificationBasis'->>'digest' IS DISTINCT FROM r.digest) THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;
 IF op='FREEZE' THEN PERFORM location_master.use_closed(t,ARRAY['operation','actor','transaction','inputId','writes','writesDigest','candidateId','digest']);INSERT INTO location_master.use_apply_binding VALUES((c->>'id')::uuid,r.id,c->>'digest',t->>'writesDigest',encode(sha256(convert_to((t->'writes')::text,'UTF8')),'hex'),verify.id,verify.number,verify.digest);RETURN '{}';END IF;
 PERFORM location_master.use_closed(t,ARRAY['operation','actor','transaction','inputId','writes','writeIndex','writesDigest','candidateId','digest','recordAt','recordAtProof']);record_at:=location_master.local_time(t->>'recordAt');SELECT decode(key_hex,'hex') INTO k FROM vnext_control.location_use_write_authority;
 PERFORM location_master.use_text_fields(t,ARRAY['recordAt','recordAtProof']);IF jsonb_typeof(t->'writeIndex') IS DISTINCT FROM 'number' OR (t->>'writeIndex')::numeric<>trunc((t->>'writeIndex')::numeric) OR (t->>'writeIndex')::integer NOT BETWEEN 1 AND 100 THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
 FOR i IN 0..31 LOOP ip:=set_byte(ip,i,get_byte(ip,i)#get_byte(k,i));opad:=set_byte(opad,i,get_byte(opad,i)#get_byte(k,i));END LOOP;IF t->>'recordAtProof' IS DISTINCT FROM encode(sha256(opad||sha256(ip||convert_to('LOCATION_USE_TRANSACTION_R_V1|'||pg_current_xact_id()::text||'|'||(t->>'recordAt'),'UTF8'))),'hex') THEN RAISE EXCEPTION 'INVALID_PLAN_TOKEN';END IF;
 approved_by:=c->>'approvedBy';IF approved_by IS NULL THEN RAISE EXCEPTION 'APPROVAL_REQUIRED';END IF;PERFORM governance_catalog.apply_record(approved_by,'CHECK_APPROVAL',jsonb_build_object('candidateId',(c->>'id')::uuid));PERFORM location_master.use_job_read(approved_by,r.id);
 FOREACH campus IN ARRAY r.campus_ids LOOP identity:=location_master.use_authorize(approved_by,campus,'REVIEW');IF identity=r.identity_code THEN RAISE EXCEPTION 'MAKER_CHECKER_REQUIRED';END IF;END LOOP;
 SELECT * INTO frozen FROM location_master.use_apply_binding WHERE candidate_id=(c->>'id')::uuid;IF NOT FOUND OR frozen.input_id<>r.id OR frozen.candidate_digest IS DISTINCT FROM t->>'digest' OR frozen.writes_digest IS DISTINCT FROM t->>'writesDigest' OR (t->>'writeIndex'='1' AND frozen.writes_hash IS DISTINCT FROM encode(sha256(convert_to((t->'writes')::text,'UTF8')),'hex')) OR frozen.verification_id IS DISTINCT FROM verify.id OR frozen.verification_number IS DISTINCT FROM verify.number OR frozen.verification_digest IS DISTINCT FROM verify.digest THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;
 SELECT * INTO change FROM location_master.use_change WHERE input_id=r.id;IF FOUND THEN IF change.candidate_id<>(c->>'id')::uuid OR change.digest IS DISTINCT FROM t->>'writesDigest' THEN RAISE EXCEPTION 'REQUEST_CONFLICT';END IF;IF (t->>'writeIndex')::integer NOT BETWEEN 1 AND jsonb_array_length(change.results) THEN RAISE EXCEPTION 'PLAN_INPUT_LIMIT';END IF;FOR w IN SELECT value FROM jsonb_array_elements(change.results) LOOP PERFORM location_master.use_snapshot(actor,(w->>'id')::uuid);END LOOP;RETURN change.results->((t->>'writeIndex')::integer-1);END IF;
 IF (t->>'writeIndex')::integer<>1 THEN RAISE EXCEPTION 'PLAN_INPUT_LIMIT';END IF;IF r.job_revision IS DISTINCT FROM (j->>'currentRevisionId')::uuid THEN RAISE EXCEPTION 'STALE_REVISION';END IF;
 IF (SELECT count(DISTINCT value->>'targetId') FROM jsonb_array_elements(t->'writes') WHERE value->>'targetId' IS NOT NULL)<>(SELECT count(*) FROM jsonb_array_elements(t->'writes') WHERE value->>'targetId' IS NOT NULL) THEN RAISE EXCEPTION 'BATCH_CONFLICT';END IF;root_id:=uuidv7();
 FOR w IN SELECT value FROM jsonb_array_elements(t->'writes') LOOP
  PERFORM location_master.use_closed(w,ARRAY['key','targetId','expectedHead','action','validFrom','validTo','applicability','facts','reason','sourceRow','scope','reduction','verificationRow']);PERFORM location_master.use_reference_access(actor,w->'applicability');
  PERFORM location_master.use_closed(w->'facts',ARRAY['isPrimary','sharingDescription','policy','usageType','usageCode','contractVersionId','verificationBasis','dependencies','source']);PERFORM location_master.use_closed(w->'facts'->'policy',ARRAY['kind','version']);PERFORM location_master.use_closed(w->'facts'->'usageType',ARRAY['owner','id','versionId','version']);PERFORM location_master.use_closed(w->'facts'->'verificationBasis',ARRAY['id','version','digest']);PERFORM location_master.use_closed(w->'facts'->'dependencies',ARRAY['source','usageType','location','upstream']);PERFORM location_master.use_closed(w->'facts'->'source',ARRAY['sourceAlias','sourceVersion','sourceSystemId','sourceRecordedAt','recordLocatorEvidence','recordStatus','approvalReference']);PERFORM location_master.use_closed(w->'facts'->'source'->'recordLocatorEvidence',ARRAY['inputId','row']);
  PERFORM location_master.use_text_fields(w,ARRAY['key','action','validFrom','reason','scope'],ARRAY['targetId','expectedHead','validTo']);PERFORM location_master.use_text_fields(w->'facts',ARRAY['usageCode','contractVersionId'],ARRAY['sharingDescription']);PERFORM location_master.use_text_fields(w->'facts'->'policy',ARRAY['kind','version']);PERFORM location_master.use_text_fields(w->'facts'->'usageType',ARRAY['owner','id','versionId','version']);PERFORM location_master.use_text_fields(w->'facts'->'verificationBasis',ARRAY['id','version','digest']);PERFORM location_master.use_text_fields(w->'facts'->'source',ARRAY['sourceAlias','sourceVersion','sourceSystemId','sourceRecordedAt','recordStatus'],ARRAY['approvalReference']);PERFORM location_master.use_text_fields(w->'facts'->'source'->'recordLocatorEvidence',ARRAY['inputId']);IF jsonb_typeof(w->'reduction') IS DISTINCT FROM 'boolean' OR jsonb_typeof(w->'facts'->'source'->'recordLocatorEvidence'->'row') IS DISTINCT FROM 'number' THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
  IF jsonb_typeof(w->'facts'->'isPrimary') IS DISTINCT FROM 'boolean' OR jsonb_typeof(w->'facts'->'sharingDescription') NOT IN ('string','null') OR length(w->'facts'->>'sharingDescription')>2000 OR length(w->'facts'->'source'->>'approvalReference')>2000 OR w->'facts'->'policy'->>'kind' NOT IN ('SHARED','EXCLUSIVE') OR w->'facts'->'policy'->>'version' IS DISTINCT FROM 'WHOLE_LOCATION_V1' OR w->'facts'->'usageType'->>'owner' IS DISTINCT FROM 'location-master/usage-type' OR w->'facts'->'usageType'->>'id' IS DISTINCT FROM w->'applicability'->'usageType'->>'id' OR w->'facts'->'usageType'->>'version' !~ '^[1-9][0-9]*$' OR w->'facts'->>'contractVersionId' IS DISTINCT FROM j->'contract'->>'versionId' OR w->'facts'->'source'->'recordLocatorEvidence'->>'inputId' IS DISTINCT FROM r.id::text OR w->'facts'->'source'->>'sourceVersion' !~ '^[1-9][0-9]{0,9}$' OR coalesce(w->>'reason','') !~ '\S' OR length(w->>'reason')>2000 OR w->'facts'->'source'->>'recordStatus' NOT IN ('DRAFT','REVIEW','ACTIVE','SUSPENDED','RETIRED') THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
  IF jsonb_typeof(w->'sourceRow') IS DISTINCT FROM 'number' OR (w->>'sourceRow')::numeric<>trunc((w->>'sourceRow')::numeric) OR (w->>'sourceRow')::integer NOT BETWEEN 1 AND 1048576 OR w->'facts'->'source'->'recordLocatorEvidence'->>'row' IS DISTINCT FROM w->>'sourceRow' OR jsonb_typeof(w->'verificationRow') IS DISTINCT FROM 'number' OR (w->>'verificationRow')::numeric<>trunc((w->>'verificationRow')::numeric) OR (w->>'verificationRow')::integer NOT BETWEEN 1 AND jsonb_array_length(verify.rows) THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
  IF (w->'facts'->'source'->>'sourceVersion')::numeric>2147483647 OR (w->>'action'='END' AND w->'facts'->'source'->>'recordStatus' IS DISTINCT FROM 'RETIRED') OR (w->>'action'<>'END' AND w->'facts'->'source'->>'recordStatus' IS DISTINCT FROM 'ACTIVE') OR (w->>'expectedHead' IS NOT NULL AND w->>'expectedHead' !~ '^[1-9][0-9]*$') THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
  PERFORM location_master.local_time(w->'facts'->'source'->>'sourceRecordedAt');from_at:=location_master.local_time(w->>'validFrom');to_at:=CASE WHEN w->>'validTo' IS NULL THEN NULL ELSE location_master.local_time(w->>'validTo') END;IF to_at<=from_at THEN RAISE EXCEPTION 'INVALID_BUSINESS_PERIOD';END IF;
  SELECT value INTO review_row FROM jsonb_array_elements(verify.rows) WHERE value->>'row'=w->>'verificationRow';IF review_row IS NULL OR NOT (review_row->>'classificationAccepted')::boolean OR NOT (review_row->>'scopeAccepted')::boolean OR NOT (review_row->>'policyAccepted')::boolean OR review_row->'policy' IS DISTINCT FROM w->'facts'->'policy' THEN RAISE EXCEPTION 'LEGAL_REVIEW_REQUIRED';END IF;
  PERFORM governance_catalog.registration_evidence_access(verify.actor,(review_row->>'evidenceId')::uuid,source_version,r.scope);PERFORM governance_catalog.use_source_reference(actor,(w->'facts'->'source'->>'sourceSystemId')::uuid,source_version);PERFORM governance_catalog.use_source_reference(approved_by,(w->'facts'->'source'->>'sourceSystemId')::uuid,source_version);PERFORM governance_catalog.use_source_reference(verify.actor,(w->'facts'->'source'->>'sourceSystemId')::uuid,source_version);
  campus:=(w->'applicability'->'campus'->>'id')::uuid;IF NOT campus=ANY(r.campus_ids) OR w->>'scope' IS DISTINCT FROM r.scope OR organization_master.campus_snapshot(actor,campus)->>'scope' IS DISTINCT FROM r.scope THEN RAISE EXCEPTION 'LOCATION_USE_ANCHOR_MISMATCH';END IF;PERFORM location_master.use_authorize(actor,campus,'WRITE');PERFORM location_master.use_authorize(approved_by,campus,'REVIEW');PERFORM location_master.use_authorize(verify.actor,campus,'VERIFY');PERFORM location_master.use_reference_access(approved_by,w->'applicability');PERFORM location_master.use_reference_access(verify.actor,w->'applicability');
  IF w->>'action'='CREATE' THEN
   IF w->>'targetId' IS NOT NULL OR w->>'expectedHead' IS NOT NULL THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;
   IF EXISTS(SELECT 1 FROM location_master.use_relation WHERE source_system_id=(w->'facts'->'source'->>'sourceSystemId')::uuid AND source_alias=w->'facts'->'source'->>'sourceAlias') THEN RAISE EXCEPTION 'LOCATION_USE_SOURCE_ALREADY_REGISTERED';END IF;
   INSERT INTO location_master.use_relation(target_type,target_id,campus_id,location_id,usage_type_id,scope,applicability,source_system_id,source_alias) VALUES(w->'applicability'->>'targetType',(w->'applicability'->'target'->>'id')::uuid,campus,(w->'applicability'->'location'->>'id')::uuid,(w->'applicability'->'usageType'->>'id')::uuid,r.scope,w->'applicability',(w->'facts'->'source'->>'sourceSystemId')::uuid,w->'facts'->'source'->>'sourceAlias') RETURNING * INTO u;target:=u.id;previous:=NULL;declaration:=NULL;
  ELSE
   IF w->>'action' NOT IN ('REVISE','END') THEN RAISE EXCEPTION 'CLOSED_INPUT_REQUIRED';END IF;target:=(w->>'targetId')::uuid;PERFORM location_master.use_snapshot(actor,target);SELECT * INTO u FROM location_master.use_relation WHERE id=target;
   SELECT * INTO previous FROM location_master.use_version WHERE use_id=target ORDER BY number DESC LIMIT 1;SELECT * INTO declaration FROM location_master.use_version WHERE use_id=target AND action IN ('CREATE','REVISE') ORDER BY number DESC LIMIT 1;
   IF previous.number::text IS DISTINCT FROM w->>'expectedHead' THEN RAISE EXCEPTION 'STALE_HEAD';END IF;IF u.applicability IS DISTINCT FROM w->'applicability' OR u.source_system_id::text IS DISTINCT FROM w->'facts'->'source'->>'sourceSystemId' OR u.source_alias IS DISTINCT FROM w->'facts'->'source'->>'sourceAlias' THEN RAISE EXCEPTION 'LOCATION_USE_ANCHOR_MISMATCH';END IF;
   IF EXISTS(SELECT 1 FROM location_master.use_version WHERE use_id=target AND action='END' AND (w->>'action'<>'END' OR valid_from<from_at)) THEN RAISE EXCEPTION 'LOCATION_USE_ENDED';END IF;
   IF w->>'action'='REVISE' AND from_at<>declaration.valid_from THEN RAISE EXCEPTION 'LOCATION_USE_REVISE_INVALID';END IF;
   -- A never-started declaration can be cancelled before its planned start.
   -- Once started, END cannot erase its earlier business coverage.
   IF w->>'action'='END' AND (to_at IS NOT NULL OR (from_at<declaration.valid_from AND declaration.valid_from<=record_at) OR from_at>coalesce(declaration.valid_to,'infinity'::timestamp) OR ((w->'facts')-ARRAY['source','verificationBasis','contractVersionId','dependencies']) IS DISTINCT FROM (declaration.facts-ARRAY['source','verificationBasis','contractVersionId','dependencies'])) THEN RAISE EXCEPTION 'LOCATION_USE_LIFECYCLE_INVALID';END IF;
  END IF;
  IF NOT tsrange(location_master.local_time(review_row->>'validFrom'),CASE WHEN review_row->>'validTo' IS NULL THEN NULL ELSE location_master.local_time(review_row->>'validTo') END,'[)') @> (CASE WHEN w->>'action'='END' THEN tsrange(declaration.valid_from,declaration.valid_to,'[)') ELSE tsrange(from_at,to_at,'[)') END) THEN RAISE EXCEPTION 'LEGAL_REVIEW_REQUIRED';END IF;
  reduction:=w->>'action'='REVISE' AND to_at IS NOT NULL AND (declaration.valid_to IS NULL OR to_at<declaration.valid_to) AND ((w->'facts')-ARRAY['source','verificationBasis','contractVersionId','dependencies']) IS NOT DISTINCT FROM (declaration.facts-ARRAY['source','verificationBasis','contractVersionId','dependencies']);
  IF w->>'action'='END' OR reduction THEN IF w->'facts'->'dependencies' IS DISTINCT FROM declaration.facts->'dependencies' THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;PERFORM location_master.usage_type_read(actor,jsonb_build_object('id',u.usage_type_id,'versionId',w->'facts'->'usageType'->>'versionId'));
  ELSE
   IF NOT location_master.usage_type_enabled(u.usage_type_id,record_at,record_at) THEN RAISE EXCEPTION 'USAGE_TYPE_DISABLED';END IF;
   FOREACH field IN ARRAY ARRAY['target_type','is_primary','record_status'] LOOP SELECT value INTO codes FROM jsonb_array_elements(j->'contract'->'definition'->'codeSets') WHERE value->>'field'=field;IF codes IS NULL OR codes->>'status' IS DISTINCT FROM 'SYNTHETIC_ADOPTED' OR NOT codes->'codes' ? (CASE field WHEN 'target_type' THEN u.target_type WHEN 'is_primary' THEN CASE WHEN (w->'facts'->>'isPrimary')::boolean THEN 'Y' ELSE 'N' END ELSE w->'facts'->'source'->>'recordStatus' END) OR NOT tsrange(location_master.local_time(codes->>'validFrom'),CASE WHEN codes->>'validTo' IS NULL THEN NULL ELSE location_master.local_time(codes->>'validTo') END,'[)') @> tsrange(from_at,to_at,'[)') THEN RAISE EXCEPTION 'BLOCKED_DEPENDENCY';END IF;END LOOP;
   IF (governance_catalog.contract_read(actor,jsonb_build_object('scope','SYNTHETIC','mode','EFFECTIVE','target',j->'contract'->>'id','businessAt',to_char(record_at,'YYYY-MM-DD"T"HH24:MI:SS.US')))->0->>'versionId') IS DISTINCT FROM j->'contract'->>'versionId' OR NOT tsrange((j->'contract'->>'validFrom')::timestamp,(j->'contract'->>'validTo')::timestamp,'[)') @> tsrange(from_at,to_at,'[)') THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;
   fresh:=governance_catalog.use_source_coverage(actor,u.source_system_id,from_at,to_at,record_at);IF fresh IS DISTINCT FROM w->'facts'->'dependencies'->'source' THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;
   fresh:=location_master.usage_type_window(actor,w->'facts'->'usageType',w->'facts'->>'usageCode',from_at,to_at,record_at);IF fresh IS DISTINCT FROM w->'facts'->'dependencies'->'usageType' THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;
   fresh:=location_master.use_location_window(actor,u.location_id,campus,from_at,to_at,record_at);IF fresh IS DISTINCT FROM w->'facts'->'dependencies'->'location' THEN RAISE EXCEPTION 'STALE_VALIDATION';END IF;
   PERFORM location_master.use_upstream_guard(actor,u.applicability,w->'facts'->'dependencies'->'upstream',from_at,to_at,record_at);
   PERFORM governance_catalog.use_source_coverage(approved_by,u.source_system_id,from_at,to_at,record_at);PERFORM governance_catalog.use_source_coverage(verify.actor,u.source_system_id,from_at,to_at,record_at);PERFORM location_master.usage_type_window(approved_by,w->'facts'->'usageType',w->'facts'->>'usageCode',from_at,to_at,record_at);PERFORM location_master.usage_type_window(verify.actor,w->'facts'->'usageType',w->'facts'->>'usageCode',from_at,to_at,record_at);PERFORM location_master.use_location_window(approved_by,u.location_id,campus,from_at,to_at,record_at);PERFORM location_master.use_location_window(verify.actor,u.location_id,campus,from_at,to_at,record_at);PERFORM location_master.use_upstream_guard(approved_by,u.applicability,w->'facts'->'dependencies'->'upstream',from_at,to_at,record_at);PERFORM location_master.use_upstream_guard(verify.actor,u.applicability,w->'facts'->'dependencies'->'upstream',from_at,to_at,record_at);
  END IF;
  INSERT INTO location_master.use_version(use_id,number,action,valid_from,valid_to,facts,reason,change_id,recorded_at) VALUES(target,coalesce(previous.number,0)+1,w->>'action',from_at,to_at,w->'facts',w->>'reason',root_id,record_at);
  results:=results||jsonb_build_array(jsonb_build_object('owner','location-master/location-use','id',target,'version',(coalesce(previous.number,0)+1)::text,'source',jsonb_build_object('dataset','ORG13','row',(w->>'sourceRow')::integer,'step',w->>'action')));INSERT INTO vnext_control.audit(actor_code,object_id,action,reason,content_digest) VALUES(actor,target,'LOCATION_USE_'||(w->>'action'),'APPROVED_ORG13_COMMAND',t->>'writesDigest');
 END LOOP;
 PERFORM location_master.use_group_validate(record_at);INSERT INTO location_master.use_change VALUES(root_id,r.id,(c->>'id')::uuid,t->>'writesDigest',results,record_at);RETURN results->0;
END $$;

CREATE FUNCTION location_master.use_access_audit() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN INSERT INTO vnext_control.audit(actor_code,object_id,action,reason,content_digest) VALUES(coalesce(NEW.actor,OLD.actor),coalesce(NEW.campus_id,OLD.campus_id),'LOCATION_USE_AUTHORIZATION',TG_OP,encode(sha256(convert_to(coalesce(to_jsonb(NEW),to_jsonb(OLD))::text,'UTF8')),'hex'));RETURN coalesce(NEW,OLD);END $$;
CREATE TRIGGER use_access_lock BEFORE INSERT OR UPDATE OR DELETE ON location_master.use_access FOR EACH STATEMENT EXECUTE FUNCTION vnext_control.lock_authorization_change();
CREATE TRIGGER use_access_audit AFTER INSERT OR UPDATE OR DELETE ON location_master.use_access FOR EACH ROW EXECUTE FUNCTION location_master.use_access_audit();
DO $$DECLARE tab text;f record;BEGIN
 FOREACH tab IN ARRAY ARRAY['use_input','use_verification','use_relation','use_change','use_apply_binding','use_version','use_withdrawal'] LOOP EXECUTE format('CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON location_master.%I FOR EACH ROW EXECUTE FUNCTION vnext_control.immutable()',tab);END LOOP;
 FOREACH tab IN ARRAY ARRAY['use_access','use_input','use_verification','use_relation','use_change','use_apply_binding','use_version','use_withdrawal'] LOOP EXECUTE format('ALTER TABLE location_master.%I ENABLE ROW LEVEL SECURITY',tab);EXECUTE format('REVOKE ALL ON location_master.%I FROM PUBLIC,hdi_prototype',tab);END LOOP;
 FOR f IN SELECT p.oid::regprocedure name FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE (n.nspname='location_master' AND p.proname LIKE 'use_%') OR (n.nspname='department_master' AND p.proname LIKE 'use_department_%') OR (n.nspname='governance_catalog' AND p.proname LIKE 'use_source_%') OR (n.nspname='organization_master' AND p.proname='use_location_boundaries') LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,hdi_prototype',f.name);END LOOP;
END $$;
CREATE FUNCTION location_master.use_snapshot_at(p_actor text,p_id uuid,p_r timestamp) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE u location_master.use_relation;accepted_version record;BEGIN
 PERFORM pg_advisory_xact_lock(901002);SELECT * INTO u FROM location_master.use_relation WHERE id=p_id;IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND';END IF;PERFORM location_master.use_reference_access(p_actor,u.applicability);
 FOR accepted_version IN SELECT * FROM location_master.use_version WHERE use_id=u.id AND recorded_at<=p_r LOOP
  PERFORM location_master.use_basis_access(p_actor,u.applicability,accepted_version.facts);
  PERFORM location_master.usage_type_read(p_actor,jsonb_build_object('id',accepted_version.facts->'usageType'->>'id','versionId',accepted_version.facts->'usageType'->>'versionId','recordAsOf',to_char(p_r,'YYYY-MM-DD"T"HH24:MI:SS.US')));
 END LOOP;RETURN jsonb_build_object('id',u.id,'scope',u.scope,'applicability',u.applicability,'versions',coalesce((SELECT jsonb_agg(jsonb_build_object('id',v.id,'number',v.number::text,'action',v.action,'validFrom',to_char(v.valid_from,'YYYY-MM-DD"T"HH24:MI:SS.US'),'validTo',to_char(v.valid_to,'YYYY-MM-DD"T"HH24:MI:SS.US'),'recordedAt',to_char(v.recorded_at,'YYYY-MM-DD"T"HH24:MI:SS.US'),'facts',v.facts,'reason',v.reason,'changeId',v.change_id) ORDER BY v.number) FROM location_master.use_version v WHERE v.use_id=u.id AND v.recorded_at<=p_r),'[]'));
END $$;
CREATE FUNCTION location_master.use_snapshot(p_actor text,p_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS $$SELECT location_master.use_snapshot_at(p_actor,p_id,timezone('Asia/Shanghai',clock_timestamp()))$$;
CREATE FUNCTION location_master.use_snapshot_version(p_actor text,p_id uuid,p_version text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE r timestamp;BEGIN SELECT recorded_at INTO r FROM location_master.use_version WHERE use_id=p_id AND number::text=p_version;IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND';END IF;RETURN location_master.use_snapshot_at(p_actor,p_id,r);END $$;
CREATE FUNCTION location_master.use_list_at(p_actor text,p_scope text,p_r timestamp) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE u record;items jsonb:='[]';BEGIN PERFORM vnext_control.authorize(p_actor,'SYNTHETIC','READ');IF p_scope NOT IN ('NORTH','SOUTH') THEN RAISE EXCEPTION 'ACCESS_DENIED';END IF;FOR u IN SELECT * FROM location_master.use_relation x WHERE scope=p_scope AND EXISTS(SELECT 1 FROM location_master.use_version v WHERE v.use_id=x.id AND v.recorded_at<=p_r) ORDER BY id LOOP IF EXISTS(SELECT 1 FROM location_master.use_access WHERE actor=p_actor AND campus_id=u.campus_id AND scope=p_scope AND permission='READ') THEN items:=items||jsonb_build_array(location_master.use_snapshot_at(p_actor,u.id,p_r));END IF;END LOOP;RETURN items;END $$;
CREATE FUNCTION location_master.use_list(p_actor text,p_scope text) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS $$SELECT location_master.use_list_at(p_actor,p_scope,timezone('Asia/Shanghai',clock_timestamp()))$$;
CREATE FUNCTION location_master.use_scope_histories(p_actor text,p_a jsonb,p_r timestamp) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE u record;items jsonb:='[]';BEGIN PERFORM location_master.use_reference_access(p_actor,p_a);FOR u IN SELECT * FROM location_master.use_relation WHERE campus_id=(p_a->'campus'->>'id')::uuid AND (location_id=(p_a->'location'->>'id')::uuid OR (target_type=p_a->>'targetType' AND target_id=(p_a->'target'->>'id')::uuid AND usage_type_id=(p_a->'usageType'->>'id')::uuid)) ORDER BY id LOOP items:=items||jsonb_build_array(location_master.use_snapshot_at(p_actor,u.id,p_r));END LOOP;RETURN items;END $$;
CREATE FUNCTION location_master.use_source_conflict(p_actor text,p_source uuid,p_alias text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN PERFORM vnext_control.authorize(p_actor,'SYNTHETIC','READ');RETURN EXISTS(SELECT 1 FROM location_master.use_relation WHERE source_system_id=p_source AND source_alias=p_alias);END $$;
-- Choose latest complete declaration before clamping all permanent END events.
CREATE FUNCTION location_master.use_reserved(p_id uuid,p_r timestamp) RETURNS tsrange LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE v location_master.use_version;ending timestamp;BEGIN SELECT * INTO v FROM location_master.use_version WHERE use_id=p_id AND action IN ('CREATE','REVISE') AND recorded_at<=p_r ORDER BY number DESC LIMIT 1;IF NOT FOUND THEN RETURN 'empty'::tsrange;END IF;SELECT min(valid_from) INTO ending FROM location_master.use_version WHERE use_id=p_id AND action='END' AND recorded_at<=p_r;ending:=least(ending,v.valid_to);IF ending IS NOT NULL AND ending<=v.valid_from THEN RETURN 'empty'::tsrange;END IF;RETURN tsrange(v.valid_from,ending,'[)');END $$;
CREATE FUNCTION location_master.use_group_validate(p_r timestamp) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE a record;b record;v location_master.use_version;other location_master.use_version;span tsrange;BEGIN
 FOR a IN SELECT * FROM location_master.use_relation ORDER BY id LOOP span:=location_master.use_reserved(a.id,p_r);IF isempty(span) THEN CONTINUE;END IF;SELECT * INTO v FROM location_master.use_version WHERE use_id=a.id AND action IN ('CREATE','REVISE') AND recorded_at<=p_r ORDER BY number DESC LIMIT 1;
  FOR b IN SELECT * FROM location_master.use_relation x WHERE x.id>a.id AND (x.location_id=a.location_id OR (x.target_type=a.target_type AND x.target_id=a.target_id AND x.campus_id=a.campus_id AND x.usage_type_id=a.usage_type_id)) LOOP
   IF NOT span&&location_master.use_reserved(b.id,p_r) THEN CONTINUE;END IF;SELECT * INTO other FROM location_master.use_version WHERE use_id=b.id AND action IN ('CREATE','REVISE') AND recorded_at<=p_r ORDER BY number DESC LIMIT 1;
   IF a.location_id=b.location_id AND (v.facts->'policy'->>'kind'='EXCLUSIVE' OR other.facts->'policy'->>'kind'='EXCLUSIVE') THEN RAISE EXCEPTION 'LOCATION_USE_CONFLICT';END IF;
   IF a.target_type=b.target_type AND a.target_id=b.target_id AND a.campus_id=b.campus_id AND a.usage_type_id=b.usage_type_id AND (v.facts->>'isPrimary')::boolean AND (other.facts->>'isPrimary')::boolean THEN RAISE EXCEPTION 'PRIMARY_LOCATION_CONFLICT';END IF;
  END LOOP;
 END LOOP;
END $$;
-- Accepted references are authorized independently of today's qualification.
-- Each wrapper inspects only its own immutable fact tables and public Owner ports.
CREATE FUNCTION department_master.use_department_version_reference(p_actor text,p_id uuid,p_version uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE stored department_master.version;BEGIN
 PERFORM department_master.snapshot(p_actor,p_id);SELECT * INTO stored FROM department_master.version WHERE department_id=p_id AND id=p_version;IF NOT FOUND THEN RAISE EXCEPTION 'REFERENCE_INVALID';END IF;PERFORM vnext_control.require_source_access(p_actor,'SYNTHETIC',(stored.facts->>'sourceSystemId')::uuid);PERFORM governance_catalog.contract_require_access(p_actor,'SYNTHETIC',(stored.facts->>'policyVersionId')::uuid,'READ');
END $$;
CREATE FUNCTION department_master.use_binding_reference_access(p_actor text,p_binding jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE stored department_master.campus_relation_version;input_id uuid;input_json jsonb;BEGIN
 PERFORM department_master.unit_reference_access(p_actor,(p_binding->'department'->>'id')::uuid,(p_binding->'relation'->>'id')::uuid,p_binding->'relation'->>'version',(p_binding->'relation'->>'versionId')::uuid,(p_binding->'campus'->>'id')::uuid,(p_binding->'subject'->>'id')::uuid);
 SELECT * INTO stored FROM department_master.campus_relation_version WHERE id=(p_binding->'relation'->>'versionId')::uuid;SELECT x.input_id INTO input_id FROM department_master.lifecycle_operation x WHERE x.id=stored.operation_id;input_json:=department_master.lifecycle_input_read(p_actor,input_id,'READ');PERFORM governance_catalog.import_job_context(p_actor,jsonb_build_object('scope','SYNTHETIC','jobId',input_json->>'job_id'));
END $$;
CREATE FUNCTION organization_master.use_license_reference_access(p_actor text,p_subject uuid,p_ref jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE stored organization_master.license_version;input_json jsonb;job jsonb;BEGIN
 PERFORM organization_master.qualification_snapshot(p_actor,p_subject);SELECT x.* INTO stored FROM organization_master.license_version x JOIN organization_master.license l ON l.id=x.license_id WHERE l.subject_id=p_subject AND x.id=(p_ref->>'versionId')::uuid AND x.license_id=(p_ref->>'id')::uuid AND x.number::text=p_ref->>'version';IF NOT FOUND THEN RAISE EXCEPTION 'REFERENCE_INVALID';END IF;
 input_json:=organization_master.input_read(p_actor,stored.input_id,'READ');job:=governance_catalog.import_job_context(p_actor,jsonb_build_object('scope','SYNTHETIC','jobId',input_json->>'jobId'));PERFORM governance_catalog.registration_evidence_access(p_actor,stored.evidence,(job->'contract'->'definition'->>'sourceVersionId')::uuid,input_json->>'campus');
END $$;
CREATE FUNCTION organization_master.use_operating_reference_access(p_actor text,p_ref jsonb,p_kind text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE history jsonb;stored jsonb;input_json jsonb;job jsonb;scope_ref jsonb;BEGIN
 IF p_kind NOT IN ('SCOPE','RELATION') THEN RAISE EXCEPTION 'REFERENCE_INVALID';END IF;history:=organization_master.operating_snapshot(p_actor,(p_ref->>'id')::uuid,p_kind);SELECT value INTO stored FROM jsonb_array_elements(history->'versions') WHERE value->>'id'=p_ref->>'versionId' AND value->>'number'=p_ref->>'version';IF stored IS NULL THEN RAISE EXCEPTION 'REFERENCE_INVALID';END IF;
 input_json:=organization_master.operating_input_read(p_actor,(stored->>'input_id')::uuid,'READ');job:=governance_catalog.import_job_context(p_actor,jsonb_build_object('scope','SYNTHETIC','jobId',input_json->>'jobId'));PERFORM governance_catalog.contract_require_access(p_actor,'SYNTHETIC',(stored->'facts'->'catalog'->>'contractVersionId')::uuid,'READ');
 IF stored->'basis'->'evidence'->>'artifactId' IS NOT NULL THEN PERFORM governance_catalog.registration_evidence_access(p_actor,(stored->'basis'->'evidence'->>'artifactId')::uuid,(job->'contract'->'definition'->>'sourceVersionId')::uuid,input_json->>'campus');END IF;
 IF p_kind='SCOPE' THEN PERFORM organization_master.use_license_reference_access(p_actor,(history->>'subject_id')::uuid,stored->'facts'->'license');ELSE FOR scope_ref IN SELECT value FROM jsonb_array_elements(stored->'facts'->'scopeTargets') LOOP PERFORM organization_master.use_operating_reference_access(p_actor,scope_ref,'SCOPE');END LOOP;END IF;
END $$;
CREATE FUNCTION care_organization.use_master_reference_access(p_actor text,p_kind text,p_id uuid,p_version uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE history jsonb;stored jsonb;BEGIN
 CASE p_kind WHEN 'UNIT' THEN history:=care_organization.snapshot(p_actor,p_id);WHEN 'WARD' THEN history:=care_organization.ward_snapshot(p_actor,p_id);WHEN 'NURSING' THEN history:=care_organization.nursing_snapshot(p_actor,p_id);ELSE RAISE EXCEPTION 'REFERENCE_INVALID';END CASE;
 SELECT value INTO stored FROM jsonb_array_elements(history->'versions') WHERE value->>'id'=p_version::text;IF stored IS NULL THEN RAISE EXCEPTION 'REFERENCE_INVALID';END IF;PERFORM vnext_control.require_source_access(p_actor,'SYNTHETIC',(stored->'facts'->'source'->>'sourceSystemId')::uuid);PERFORM governance_catalog.contract_require_access(p_actor,'SYNTHETIC',(stored->'facts'->>'contractVersionId')::uuid,'READ');
END $$;
CREATE FUNCTION care_organization.use_unit_basis_access(p_actor text,p_basis jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE part jsonb;current_part jsonb;service jsonb;segment jsonb;BEGIN
 FOR part IN SELECT value FROM jsonb_array_elements(p_basis->'parts') LOOP PERFORM care_organization.use_master_reference_access(p_actor,'UNIT',(p_basis->>'id')::uuid,(part->>'versionId')::uuid);PERFORM department_master.use_binding_reference_access(p_actor,part->'binding');END LOOP;
 FOR current_part IN SELECT value FROM jsonb_array_elements(p_basis->'current') LOOP FOR service IN SELECT value FROM jsonb_array_elements(current_part->'dependencies'->'operating'->'services') LOOP FOR segment IN SELECT value FROM jsonb_array_elements(service->'segments') LOOP PERFORM organization_master.use_operating_reference_access(p_actor,segment->'relation','RELATION');PERFORM organization_master.use_operating_reference_access(p_actor,segment->'scope','SCOPE');PERFORM organization_master.use_license_reference_access(p_actor,(current_part->'dependencies'->'operating'->'subject'->>'id')::uuid,segment->'license');END LOOP;END LOOP;END LOOP;
END $$;
CREATE FUNCTION care_organization.use_ward_basis_access(p_actor text,p_id uuid,p_basis jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE part jsonb;BEGIN FOR part IN SELECT value FROM jsonb_array_elements(p_basis->'parts') LOOP PERFORM care_organization.use_master_reference_access(p_actor,'WARD',p_id,(part->>'versionId')::uuid);PERFORM governance_catalog.use_source_reference(p_actor,(part->'source'->>'sourceId')::uuid,(part->'source'->>'versionId')::uuid);PERFORM care_organization.use_unit_basis_access(p_actor,part->'unit');END LOOP;END $$;
CREATE FUNCTION care_organization.use_nursing_basis_access(p_actor text,p_id uuid,p_basis jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE part jsonb;department_part jsonb;BEGIN FOR part IN SELECT value FROM jsonb_array_elements(p_basis->'parts') LOOP PERFORM care_organization.use_master_reference_access(p_actor,'NURSING',p_id,(part->>'propertyVersionId')::uuid);PERFORM governance_catalog.use_source_reference(p_actor,(part->'source'->>'sourceId')::uuid,(part->'source'->>'versionId')::uuid);FOR department_part IN SELECT value FROM jsonb_array_elements(part->'basis'->'department'->'parts') LOOP PERFORM department_master.use_department_version_reference(p_actor,(part->'binding'->'department'->>'id')::uuid,(department_part->>'versionId')::uuid);END LOOP;END LOOP;END $$;
CREATE FUNCTION location_master.use_basis_access(p_actor text,p_a jsonb,p_facts jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE part jsonb;node jsonb;verification location_master.use_verification;input_record jsonb;input_job jsonb;review_row jsonb;BEGIN
 PERFORM governance_catalog.use_source_reference(p_actor,(p_facts->'source'->>'sourceSystemId')::uuid,(p_facts->'dependencies'->'source'->>'versionId')::uuid);
 FOR part IN SELECT value FROM jsonb_array_elements(p_facts->'dependencies'->'location'->'parts') LOOP FOR node IN SELECT value FROM jsonb_array_elements(part->'graph') LOOP PERFORM location_master.snapshot(p_actor,(node->>'id')::uuid);PERFORM governance_catalog.use_source_reference(p_actor,(node->'source'->>'sourceId')::uuid,(node->'source'->>'versionId')::uuid);END LOOP;END LOOP;
 CASE p_a->>'targetType' WHEN 'ORG' THEN FOR part IN SELECT value FROM jsonb_array_elements(p_facts->'dependencies'->'upstream'->'parts') LOOP PERFORM department_master.use_department_version_reference(p_actor,(p_a->'target'->>'id')::uuid,(part->>'versionId')::uuid);PERFORM governance_catalog.use_source_reference(p_actor,(part->'source'->>'sourceId')::uuid,(part->'source'->>'versionId')::uuid);END LOOP;
 WHEN 'UNIT' THEN PERFORM care_organization.use_unit_basis_access(p_actor,p_facts->'dependencies'->'upstream');WHEN 'WARD' THEN PERFORM care_organization.use_ward_basis_access(p_actor,(p_a->'target'->>'id')::uuid,p_facts->'dependencies'->'upstream');WHEN 'NURSING' THEN PERFORM care_organization.use_nursing_basis_access(p_actor,(p_a->'target'->>'id')::uuid,p_facts->'dependencies'->'upstream');ELSE RAISE EXCEPTION 'REFERENCE_INVALID';END CASE;
 SELECT * INTO verification FROM location_master.use_verification WHERE id=(p_facts->'verificationBasis'->>'id')::uuid;IF NOT FOUND THEN RAISE EXCEPTION 'REFERENCE_INVALID';END IF;input_record:=location_master.use_input_read(p_actor,verification.input_id,'READ');input_job:=governance_catalog.import_job_context(p_actor,jsonb_build_object('scope','SYNTHETIC','jobId',input_record->>'job_id'));FOR review_row IN SELECT value FROM jsonb_array_elements(verification.rows) LOOP PERFORM governance_catalog.registration_evidence_access(p_actor,(review_row->>'evidenceId')::uuid,(input_job->'contract'->'definition'->>'sourceVersionId')::uuid,input_record->>'scope');END LOOP;
END $$;
DO $$DECLARE f record;BEGIN FOR f IN SELECT p.oid::regprocedure name FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE (n.nspname IN ('location_master','department_master','organization_master','care_organization') AND p.proname LIKE 'use_%') OR (n.nspname='governance_catalog' AND p.proname LIKE 'use_source_%') LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,hdi_prototype',f.name);END LOOP;END $$;
