export { normalizePersonFacts } from './contracts.js';
export type { PersonFacts, PersonSubject, PersonSubjectVersion, PersonReference, CreatePersonSubject, CreatePersonSubjectVersion, PersonAsOfQuery, PersonCoreApplication } from './contracts.js';
export { createPersonCoreApplication } from './application.js';
export { createPersonMasterModule, type PersonMasterModule } from './repository.js';
export * from './identifier-contracts.js';
export { createPersonIdentifierApplication } from './identifier-application.js';
export { createPersonIdentifierModule } from './identifier-repository.js';
export * from './source-mapping-contracts.js';
export { createPersonSourceMappingApplication } from './source-mapping-application.js';
export { createPersonSourceMappingModule, type PersonSourceMappingModule } from './source-mapping-repository.js';
