export type ReleaseConsumerErrorCode =
  | 'TRANSPORT_FAILED' | 'HTTP_FAILED' | 'RESPONSE_INVALID' | 'IDENTITY_MISMATCH'
  | 'RELEASE_NOT_FOUND' | 'SNAPSHOT_DIGEST_MISMATCH' | 'SNAPSHOT_DIGEST_HEADER_MISMATCH'
  | 'PROJECTION_TYPE_MISMATCH' | 'PROJECTION_VERSION_MISMATCH' | 'SCHEMA_DIGEST_MISMATCH'
  | 'ENVELOPE_INVALID' | 'PAYLOAD_INVALID' | 'PAYLOAD_DIGEST_MISMATCH'
  | 'STATE_INVALID' | 'STATE_IO_FAILED' | 'APPLY_FAILED' | 'APPLY_NOT_DURABLE'
  | 'EVENT_GAP' | 'CHECKPOINT_NOT_ADVANCED' | 'UNVERIFIED_INPUT' | 'CONCURRENT_CONSUMPTION'
  | 'SUSPENDED' | 'REVOKED' | 'ARCHIVED'
  | 'CONSUMER_SUBSCRIPTION_NOT_ACTIVE' | 'CONSUMER_SUBSCRIPTION_FORBIDDEN'
  | 'CONSUMER_SUBSCRIPTION_NOT_FOUND' | 'SNAPSHOT_NOT_AVAILABLE_TO_SUBSCRIPTION'
  | 'CONSUMER_EVENT_NOT_AVAILABLE' | 'CONSUMER_PROCESSING_DIGEST_MISMATCH'
  | 'CONSUMER_RECEIPT_RESULT_INCOHERENT' | 'CONSUMER_CHECKPOINT_GAP'
  | 'REQUEST_SCHEMA_INVALID' | 'SERVICE_TOKEN_UNAUTHENTICATED' | 'PRINCIPAL_KIND_FORBIDDEN';

/** No raw response, request, callback exception, body, credential or cause. */
export class ReleaseConsumerError extends Error {
  readonly code: ReleaseConsumerErrorCode;
  readonly stage: string;
  constructor(code: ReleaseConsumerErrorCode, stage: string) {
    super(`RELEASE_CONSUMER_${code}`);
    this.name = 'ReleaseConsumerError';
    this.code = code;
    this.stage = stage;
  }
}
