import {useState,useRef,useEffect} from 'react';
import type {CareOperation} from '@hospital-data-intelligence/generated-api-client';
import {DepartmentData,initialForm,fixedForm,type ReferenceChoices} from './department-form.js';
import {definiteFailure} from './department-request.js';
import {CareForm} from './care-form.js';
import {careSchema,record,text,careStatus} from './care-model.js';
import {careExecute,careError,careRequestIds,newCareRequest,careMutation,careFormBranch} from './care-request.js';
export function downloadCareBytes(base64:string,filename:string){const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes]));const link=document.createElement('a');link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url);}
export function CareOperationPanel({actor,operation,label,initial={},choices={},enabled=true,initiallyPending=false,onResult,onBefore,onPending,onFailure,onIssue,issueOrigin,omitFormFields=[]}:{actor:string;operation:CareOperation;label:string;initial?:Record<string,unknown>;choices?:ReferenceChoices;enabled?:boolean;initiallyPending?:boolean;onResult?:(value:unknown,body:Record<string,unknown>)=>void;onBefore?:(body:Record<string,unknown>)=>void|Promise<void>;onPending?:(pending:boolean)=>void;onFailure?:(uncertain:boolean)=>void;onIssue?:((issue:Record<string,unknown>)=>void)|undefined;issueOrigin?:Record<string,unknown>;omitFormFields?:string[]}){
 const schema=careSchema(operation),[body,setBody]=useState<Record<string,unknown>>(()=>({...record(initialForm(careFormBranch(schema,initial))),...initial})),[result,setResult]=useState<unknown>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(initiallyPending),generation=useRef(0),pending=useRef<Record<string,unknown>|null>(initiallyPending?initial:null);
 const protectedKeys=['inputId','inputDigest','candidateId','digest','requestId',...(operation==='readCareWorkspaceMaterial'?['access','kind']:[])].filter(key=>key in initial),filterBound=(branch:typeof schema):typeof schema=>branch.properties?{...branch,properties:Object.fromEntries(Object.entries(branch.properties).filter(([key])=>!protectedKeys.includes(key)&&!omitFormFields.includes(key)))}:branch,boundBranch=protectedKeys.some(key=>key==='access'||key==='kind')?careFormBranch(schema,initial):schema,formSchema=boundBranch.anyOf?{...boundBranch,anyOf:boundBranch.anyOf.map(filterBound)}:filterBound(boundBranch);
 useEffect(()=>()=>{generation.current++;},[]);
 async function execute(){const replay=!!pending.current,token=generation.current,input=pending.current??record(careRequestIds(schema,fixedForm(schema,{...body,...Object.fromEntries(protectedKeys.map(key=>[key,initial[key]]))})));if(careMutation(operation))pending.current=input;setBody(input);setBusy(true);setError('');onPending?.(true);try{await onBefore?.(input);const value=await careExecute(actor,operation,input);if(token!==generation.current)return;const unknown=careMutation(operation)&&record(value)['status']==='COMMIT_UNKNOWN';pending.current=unknown?input:null;setUncertain(unknown);setResult(value);onResult?.(value,input);onPending?.(unknown);}catch(error){if(token===generation.current){const unknown=careMutation(operation)&&(replay||!definiteFailure(error));if(!unknown)pending.current=null;setUncertain(unknown);setError(careError(error)+(unknown?' 原请求结果尚未确认，编辑已锁定，请恢复同一请求。':''));if(!unknown)onPending?.(false);onFailure?.(unknown);}}finally{if(token===generation.current)setBusy(false);}}
 return <section className="care-operation" aria-label={label}><h3>{label}</h3>{protectedKeys.length>0&&<p className="care-bound-reference">绑定原申请／候选：{protectedKeys.filter(k=>k!=='digest'&&k!=='inputDigest').map(k=>text(initial[k])).join(' · ')}</p>}{formSchema.properties&&Object.keys(formSchema.properties).length===0?null:<CareForm schema={formSchema} value={body} onChange={value=>{setBody(record(newCareRequest(value)));setResult(null);setError('');}} choices={choices} disabled={busy||!enabled||uncertain}/>}<button disabled={busy||!enabled} onClick={()=>void execute()}>{busy?'正在处理…':uncertain?'恢复同一'+label+'请求':label}</button>{error&&<p role="alert">{error}</p>}{result!==null&&<CareFacts value={result} onIssue={onIssue} issueDisabled={busy||!enabled||uncertain} issueOrigin={issueOrigin}/>}</section>;
}
function materialText(base64:string):string|null {
 if(!base64||base64.length>90000)return null;
 try {const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0)),content=new TextDecoder('utf-8',{fatal:true}).decode(bytes);return /[\u0000-\u0008\u000E-\u001F]/.test(content)?null:content;} catch {return null;}
}
export function CareFacts({value,onIssue,issueDisabled=false,issueOrigin}:{value:unknown;onIssue?:((issue:Record<string,unknown>)=>void)|undefined;issueDisabled?:boolean;issueOrigin?:Record<string,unknown>|undefined}){
 const facts=record(value),bytes=text(facts['download']??facts['contentBase64']),preview=materialText(bytes),issues=Array.isArray(facts['issues'])?facts['issues']:Array.isArray(facts['items'])?facts['items'].filter(item=>['NOT_SATISFIED','UNKNOWN'].includes(text(record(item)['status']))):[],visible=Object.keys(facts).length?Object.fromEntries(Object.entries(facts).filter(([key])=>!['download','contentBase64','commandFacts'].includes(key))):value;
 const locatedIssues=issues.map(issue=>{const raw=record(issue),sourceRows=issueOrigin?.['sourceRows'],physical=Array.isArray(sourceRows)&&Number(raw['row'])>0?sourceRows[Number(raw['row'])-1]:undefined,source=record(raw['source']),fileReceipt=typeof facts['sourceArtifactId']==='string';return {...raw,...(issueOrigin?{inputId:issueOrigin['inputId'],source:{origin:issueOrigin['origin']??(issueOrigin['sourceArtifactId']?'FILE':'PAGE'),sourceArtifactId:issueOrigin['sourceArtifactId']??null,worksheet:issueOrigin['worksheet']??source['worksheet']??null,sourceRow:physical??raw['row']}}:fileReceipt?{source:{origin:'FILE',sourceArtifactId:facts['sourceArtifactId'],worksheet:facts['worksheet']??null,sourceRow:raw['row']}}:{})} as Record<string,unknown>;});
 return <div className="care-result"><p>{careStatus(facts['state']??facts['status']??facts['decision'])} {text(facts['recordAsOf'])&&'· R '+text(facts['recordAsOf'])}</p>
 {bytes&&<button onClick={()=>downloadCareBytes(bytes,text(facts['filename'])||'依据材料.bin')}>下载当前授权内容</button>}
 {preview!==null&&<details open><summary>当前授权材料原文（UTF-8）</summary><pre className="care-material-preview">{preview}</pre></details>}
 {locatedIssues.length>0&&<button onClick={()=>{const rows=['工作表,原始行号,字段,原因,状态',...locatedIssues.map(r=>{const source=record(r['source']);return [source['worksheet'],source['sourceRow']??r['row'],r['field'],r['code']??r['reason'],r['status']].map(v=>'"'+text(v).replaceAll('"','""')+'"').join(',');})].join('\r\n');downloadCareBytes(btoa(String.fromCharCode(...new TextEncoder().encode('\uFEFF'+rows))),'原申请问题.csv');}}>下载原申请问题</button>}
 {locatedIssues.length>0&&<table className="care-issues"><caption>原问题定位</caption><thead><tr><th>来源／行</th><th>字段与原因</th><th>期间</th><th>操作</th></tr></thead><tbody>{locatedIssues.map((item,index)=>{const source=record(item['source']),row=source['sourceRow']??item['row'];return <tr key={index}><td>{text(source['worksheet'])||'原输入'} · {text(row)||'整包'}</td><td>{text(item['field'])||'整行'} · {text(item['code']??item['reason'])}<small>{careStatus(item['status'])}</small></td><td>{item['problemScope']==='ROW'?'整行问题':item['problemScope']==='BUNDLE'?'整包问题':<>{text(item['from'])}{item['from']!==undefined&&' — '}{item['to']===null?'无界':text(item['to'])}</>}</td><td>{onIssue?<button disabled={issueDisabled} onClick={()=>{if(!issueDisabled)onIssue(item);}}>定位编辑位置</button>:text(item['inputId'])&&<a href={'/admin/vnext/care-space?'+new URLSearchParams({actor:new URL(location.href).searchParams.get('actor')??'maker',kind:text(item['owner']),application:text(item['inputId']),issueRow:text(row),issueField:text(item['field']),issueSheet:text(source['worksheet'])}).toString()}>定位准确原输入</a>}</td></tr>;})}</tbody></table>}
 <DepartmentData value={visible}/>{facts['commandFacts']!==undefined&&<details><summary>冻结领域命令依据</summary><DepartmentData value={facts['commandFacts']}/></details>}</div>;
}
