import {createVNextCatalogClient,createCampusClient,createDepartmentClient,createOrganizationClient} from '@hospital-data-intelligence/generated-api-client';
import type {ReferenceChoice,ReferenceChoices} from './department-form.js';
import {departmentValue} from './department-request.js';
import {careExecute,careError} from './care-request.js';
import {carePipelines,careOwners,careNames,record,text} from './care-model.js';
import type {CareOperation} from '@hospital-data-intelligence/generated-api-client';
import type {CareReferenceChoice} from './care-reference-fields.js';
export interface CareReferencePage {owner:string;label:string;operation:CareOperation;input:Record<string,unknown>;after:string}
function choice(owner:string,value:unknown):ReferenceChoice{
 const row=record(value),versions=Array.isArray(row['versions'])?row['versions']:[],version=record(row['version']??versions.at(-1)),facts=record(row['facts']??version['facts']),binding=record(record(row['binding'])['binding']),applicability=record(row['applicability']),scope=record(row['scope']);
 const id=text(row['id']),head=text(row['head']??version['number']),campus=text(row['campusId']??record(binding['campus']??applicability['campus']??scope['campus'])['id']);
 const name=text(facts['unitName']??facts['nursingName']??facts['wardName']??facts['locationName']??facts['campusName']??facts['legalName']??facts['name']??row['name'])||id;
 const code=text(facts['unitCode']??facts['nursingCode']??facts['wardCode']??facts['locationCode']??facts['campusCode']??facts['code']??row['initialCode']);
 const type=text(facts['unitType']??facts['locationType']??facts['wardType']??facts['nodeKind']??row['kind']??applicability['capabilityType']);
 return {value:id,owner,version:head,versionId:text(version['id']),label:`${name} · ${code||id.slice(-8)} · ${type||owner.split('/').at(-1)} · 院区 ${campus||text(row['scope'])||'—'} · v${head||'—'}`};
}
export async function loadCareReferences(actor:string,campus:'NORTH'|'SOUTH'):Promise<{choices:ReferenceChoices;errors:string[];pages:CareReferencePage[]}>{
 const choices:Record<string,ReferenceChoice[]>={},errors:string[]=[],pages:CareReferencePage[]=[];
 const attempt=async(label:string,work:()=>Promise<void>)=>{try{await work();}catch(error){errors.push(label+'：'+careError(error));}};
 await Promise.all([
  attempt('院区引用',async()=>{const values=await departmentValue(createCampusClient(location.origin,actor).list({limit:100})),rows=values.map(item=>choice('organization-master/campus',item));choices['organization-master/campus']=rows;choices['campus_id']=rows;choices['campusId']=rows;}),
  attempt('运营主体引用',async()=>{const values=await departmentValue(createOrganizationClient(location.origin,actor).read({mode:'LIST',limit:100}));const rows=values.map(item=>choice('organization-master',item));choices['organization-master']=rows;choices['legal_entity_id']=rows;const licenses=await Promise.all(values.map(item=>careExecute(actor,'readOrganizationLicenses',{id:item.id,mode:'HISTORY'})));choices['organization-master/license']=licenses.flatMap((result,i)=>Array.isArray(result)?result.map(value=>{const r=record(value);return {value:text(r['id']),owner:'organization-master/license',version:text(r['version']),versionId:text(r['versionId']),label:`${rows[i]!.label} · 许可 ${text(r['authority'])} · v${text(r['version'])} · ${text(r['validFrom'])} — ${text(r['validTo'])||'无界'}`};}):[]);}),
  attempt('科室引用',async()=>{const client=createDepartmentClient(location.origin,actor),ids=await departmentValue(client.list({limit:100})),histories=await Promise.all(ids.map(id=>departmentValue(client.history({id}))));choices['department-master']=histories.map(item=>{const v=item.versions.at(-1)!;return {value:item.id,owner:'department-master',version:v.number,versionId:v.id,label:`${v.facts.name} · ${item.initialCode} · v${v.number}`};});for(const key of ['org_id','managing_org_id'])choices[key]=choices['department-master'];const relationships=await Promise.all(ids.map(id=>careExecute(actor,'getDepartmentLifecycleHistory',{id})));choices['department-master/campus-relation']=relationships.flatMap(value=>{const relations=record(value)['relations'];return Array.isArray(relations)?relations.filter(value=>record(value)['scope']===campus).flatMap(value=>{const r=record(value),versions=r['versions'];return Array.isArray(versions)?versions.map(value=>{const v=record(value);return {value:text(r['id']),owner:'department-master/campus-relation',version:text(v['version']),versionId:text(v['id']),label:`科室 ${text(r['departmentId'])} · 院区 ${text(r['campusId'])} · ${text(v['action'])} · v${text(v['version'])} · ${text(v['validFrom'])} — ${text(v['validTo'])||'无界'}`};}):[];}):[];});}),
  attempt('用途引用',async()=>{const values=record(await careExecute(actor,'listLocationUsageTypes',{limit:100})),items=values['items'];choices['location-master/usage-type']=Array.isArray(items)?items.map(value=>{const r=record(value);return {value:text(r['id']),owner:'location-master/usage-type',version:text(r['version']),versionId:text(r['versionId']),label:`${text(r['name'])} · ${text(r['code'])} · ${r['enabled']?'启用':'停用'} · v${text(r['version'])}`};}):[];}),
  attempt('来源引用',async()=>{const entries=await departmentValue(createVNextCatalogClient(location.origin,actor).GET('/api/vnext/catalog',{params:{query:{scope:'SYNTHETIC',kind:'SOURCE',page:1}}}));choices['governance-catalog/source']=entries.items.filter(entry=>entry.status==='PUBLISHED').map(entry=>({value:entry.id,owner:'governance-catalog/source',version:entry.head,versionId:entry.versionId,label:`${entry.payload.adopted?.name??entry.payload.name??entry.code} · ${entry.code} · v${entry.head}`}));for(const key of ['source_system_id','sourceSystemId','sourceId'])choices[key]=choices['governance-catalog/source'];}),
  ...(['UNIT','NURSING','WARD','UNIT_WARD','WARD_NURSING','CAPABILITY','LOCATION_USE','PERMISSION'] as const).map(kind=>attempt(careNames[kind]+'引用',async()=>{const operation=carePipelines[kind].list!,input={campus,limit:100},result=record(await careExecute(actor,operation,input)),items=Array.isArray(result['items'])?result['items']:[];choices[careOwners[kind]]=items.map(item=>choice(careOwners[kind],item));if(typeof result['nextAfterId']==='string')pages.push({owner:careOwners[kind],label:careNames[kind],operation,input,after:result['nextAfterId']});})),
 ]);
 const locations:ReferenceChoice[]=[];await Promise.all((choices['organization-master/campus']??[]).map(c=>attempt('院区地点 '+c.label,async()=>{const input={campusId:c.value,limit:100},page=record(await careExecute(actor,'listLocations',input)),items=page['items'];if(Array.isArray(items))locations.push(...items.map(item=>choice('location-master',item)));if(typeof page['nextAfterId']==='string')pages.push({owner:'location-master',label:'地点 · '+c.label,operation:'listLocations',input,after:page['nextAfterId']});})));choices['location-master']=locations;
 await Promise.all(([
  ['parameterValue','参数值','listParameterValues',{campus,limit:100}],
  ['subjectAdoption','科目采纳','listSubjectCodeSnapshots',{limit:100}],
  ['nursingScope','护理分区','listWardNursingScopeDefinitions',{campus,limit:100}],
 ] as const).map(([owner,label,operation,input])=>attempt(label,async()=>{const page=record(await careExecute(actor,operation,input)),items=Array.isArray(page['items'])?page['items']:[];choices[owner]=basisChoices(owner,items);if(typeof page['nextAfterId']==='string')pages.push({owner,label,operation,input,after:page['nextAfterId']});})));
 await attempt('参数定义',async()=>{const definitions=await departmentValue(createVNextCatalogClient(location.origin,actor).GET('/api/vnext/parameter-definitions',{params:{query:{scope:'SYNTHETIC',mode:'APPROVED'}}}));choices['definitionVersionId']=definitions.items.map(item=>({value:item.versionId,label:`${item.parameterKey} · ${item.definition.valueType} · v${item.version}`,fields:{definitionVersionId:item.versionId,definitionDigest:item.reviewDigest}} satisfies CareReferenceChoice));});
 basisAliases(choices);
 for(const [kind,owner] of Object.entries(careOwners))choices[kind]=choices[owner]??[];
 for(const [field,owner] of Object.entries({managing_unit_id:'care-organization/unit',nursing_unit_id:'care-organization/nursing',ward_id:'care-organization/ward'}))choices[field]=choices[owner]??[];
 return {choices,errors,pages};
}
export async function loadMoreCareReferences(actor:string,page:CareReferencePage,previous:ReferenceChoices){const result=record(await careExecute(actor,page.operation,{...page.input,after:page.after})),items=Array.isArray(result['items'])?result['items']:[],rows=[...(previous[page.owner]??[]),...(basisOwners.has(page.owner)?basisChoices(page.owner,items):items.map(item=>choice(page.owner,item)))],merged=[...new Map(rows.map(row=>[row.value+'|'+row.versionId,row])).values()],choices={...previous,[page.owner]:merged};for(const [key,values] of Object.entries(previous))if(values===previous[page.owner])choices[key]=merged;basisAliases(choices);return {choices,next:typeof result['nextAfterId']==='string'?{...page,after:result['nextAfterId']}:null};}
const basisOwners=new Set(['parameterValue','subjectAdoption','nursingScope']);
function basisAliases(choices:Record<string,readonly ReferenceChoice[]>){for(const [field,owner] of Object.entries({valueId:'parameterValue',systemId:'subjectAdoption',scopeSetId:'nursingScope'}))choices[field]=choices[owner]??[];}
function basisChoices(owner:string,items:unknown[]):CareReferenceChoice[]{return items.map(value=>{const row=record(value),id=text(row['id']),version=text(row['head']??row['version']),versionId=text(row['versionId']),scope=record(row['applicability']);
 const fields=owner==='parameterValue'?{valueId:id,versionId,parameterId:row['parameterId'],definitionVersionId:row['definitionVersionId'],definitionDigest:row['definitionDigest'],valueDigest:row['reviewDigest']}:owner==='subjectAdoption'?{systemId:id,versionId,version,code:'',codes:Array.isArray(row['codes'])?row['codes'].filter(value=>record(value)['status']==='ACTIVE'):[]}:{scopeSetId:id,version,partitionIds:[],partitions:row['partitions']};
 const name=owner==='parameterValue'?`${text(row['purpose'])} · ${JSON.stringify(row['value'])} · 单元 ${text(record(scope['unit'])['id'])}`:owner==='subjectAdoption'?`${text(row['codeSystemName'])} · ${text(row['codeSystemVersion'])}`:`分区 ${text(row['sourceAlias'])} · 病区 ${text(record(scope['ward'])['id'])}`;
 return {value:id,version,versionId,label:`${name} · ${id.slice(-8)} · v${version} · ${text(row['validFrom'])} — ${text(row['validTo'])||'无界'}`,fields};});}
