import {useEffect,useState,useRef} from 'react';
import {createCareWorkspaceClient,type CareOperation,type VNextOperations as Operations} from '@hospital-data-intelligence/generated-api-client';
import {carePipelines,careSchema,record,text,type CareKind} from './care-model.js';
import {CareFacts,CareOperationPanel} from './care-operation.js';
import {initialForm,type ReferenceChoices} from './department-form.js';
import {departmentValue} from './department-request.js';
import {careExecute,careError,careLocator} from './care-request.js';
type Application=Operations['readCareWorkspaceApplicationReference']['responses'][200]['content']['application/json'];
type Execution=Operations['listCareWorkspaceExecutions']['responses'][200]['content']['application/json']['items'][number];
export function CareApplication({actor,kind,application,choices,permissions,onLock,onCorrect,issueLocator}:{actor:string;kind:CareKind;application:Application;choices:ReferenceChoices;permissions:{verify:boolean;review:boolean;write:boolean};onLock?:(locked:boolean)=>void;onCorrect?:(original:Record<string,unknown>,issue:Record<string,unknown>)=>Promise<boolean>;issueLocator?:{row:number|null;field:string;worksheet:string|null}}){
 const pipeline=carePipelines[kind],input=application.submission,workspace=createCareWorkspaceClient(location.origin,actor);
 const [candidate,setCandidate]=useState<Execution|null>(null),[executions,setExecutions]=useState<Execution[]>([]),[cursor,setCursor]=useState<string|null>(null),[native,setNative]=useState<unknown>(null),[error,setError]=useState(''),[outcome,setOutcome]=useState<unknown>(null),[matched,setMatched]=useState(false),[pending,setPending]=useState<CareOperation|null>(null);
 const [sourceOrigin,setSourceOrigin]=useState<Record<string,unknown>>({});
 const located=useRef(false);
 useEffect(()=>{if(located.current||native===null||!issueLocator||!onCorrect||!Object.keys(sourceOrigin).length)return;located.current=true;const original=record(native),sourceRows=original['sourceRows'],index=Array.isArray(sourceRows)?sourceRows.indexOf(issueLocator.row):-1;void onCorrect(original,{row:index>=0?index+1:issueLocator.row,field:issueLocator.field,source:{sourceRow:issueLocator.row,worksheet:sourceOrigin['worksheet']??issueLocator.worksheet}}).then(success=>{if(success)careLocator({issueRow:null,issueField:null,issueSheet:null});});},[native,sourceOrigin,issueLocator,onCorrect]);
 async function reload(after?:string){const result=await departmentValue(workspace.executions({kind,inputId:input.inputId,limit:50,...(after?{after}:{})}));setExecutions(result.items);setCursor(result.nextAfterId);return result.items;}
 useEffect(()=>{let active=true;void (async()=>{try{const [original,history,context]=await Promise.all([careExecute(actor,pipeline.read,{inputId:input.inputId}),departmentValue(workspace.executions({kind,inputId:input.inputId,limit:50})),departmentValue(workspace.applicationReference({kind,inputId:input.inputId}))]);if(!active)return;setNative(original);setSourceOrigin(record(context.source));setExecutions(history.items);setCursor(history.nextAfterId);const url=new URL(location.href),id=url.searchParams.get('candidate'),requestId=url.searchParams.get('execution'),exactPage=id||requestId?await departmentValue(workspace.executions({kind,inputId:input.inputId,limit:1,...(id?{candidateId:id}:{}),...(requestId?{requestId}:{})})):null,exact=exactPage?.items[0];if(!active)return;if(exact){setCandidate(exact);careLocator({candidate:exact.candidateId,execution:exact.requestId});}else if(id||requestId)setError('服务器没有与当前申请及准确候选／原请求同时匹配的记录。请保留原标识，恢复原冻结请求。');}catch(error){if(active)setError(careError(error));}})();return()=>{active=false;};},[actor,input.inputId]);
 const select=(item:Execution)=>{setCandidate(item);setOutcome(null);setMatched(false);careLocator({candidate:item.candidateId,execution:item.requestId});};
 const setLock=(operation:CareOperation,locked:boolean)=>{setPending(locked?operation:null);onLock?.(locked);};
 const enabled=(operation:CareOperation,allowed:boolean)=>allowed&&(!pending||pending===operation);
 const original=record(native),verifySchema=careSchema(pipeline.verify),branch=verifySchema.anyOf?.find(branch=>branch.properties?.['kind']?.enum?.includes(original['kind']))??verifySchema,verification=record(initialForm(branch)),rows=original['entries'];
 if(Array.isArray(rows)&&branch.properties?.['rows'])verification['rows']=rows.map((entry,index)=>{const row=record(entry),source=record(row['row']),schema=branch.properties!['rows']!.items!,review=record(initialForm(schema)),from=source['valid_from'],to=source['valid_to']||null;for(const field of ['rule','coverage','license','semantic','policy'])if(schema.properties?.[field]&&row[field]!==undefined)review[field]=row[field];if(schema.properties?.['validFrom'])review['validFrom']=from;if(schema.properties?.['validTo'])review['validTo']=to;return {...review,row:index+1,evidenceId:row['evidenceId'],...(review['receiving']?{receiving:{...record(review['receiving']),validFrom:from,validTo:to}}:{})};});
 const scopeReview=kind==='WARD_NURSING'&&['SCOPE_DEFINITION','SCOPE_REVISION'].includes(text(original['kind'])),omitVerificationFields=kind==='WARD_NURSING'?(scopeReview?['rows']:['scopeDefinition']):[];
 if(scopeReview)verification['scopeDefinition']={completeAndDisjoint:false,definitionDigest:input.digest,evidenceId:record(original['definition'])['evidenceId']};
 return <section aria-label="原申请执行流程"><h3>原申请 · {input.inputId.slice(-8)}</h3><p>原编辑人 {application.maker} · 准确修订 {input.revisionId} · 校验、独立核验、冻结、审批和应用分别执行。</p>{error&&<p role="alert">{error}</p>}{native!==null&&<details><summary>服务器原申请与准确依据</summary><CareFacts value={native}/></details>}<CareOperationPanel actor={actor} operation={pipeline.preview} label="预检原申请" initial={{inputId:input.inputId}} choices={choices} enabled={!pending} issueOrigin={{...record(native),...sourceOrigin,inputId:input.inputId}} onIssue={issue=>{if(!pending)onCorrect?.(record(native),issue);}}/><CareOperationPanel key={'verify'+text(record(native)['requestId'])} actor={actor} operation={pipeline.verify} label="提交独立核验" initial={{...verification,inputId:input.inputId,inputDigest:input.digest}} choices={choices} omitFormFields={omitVerificationFields} enabled={enabled(pipeline.verify,permissions.verify&&native!==null)} onPending={locked=>setLock(pipeline.verify,locked)}/><CareOperationPanel actor={actor} operation={pipeline.plan} label="冻结准确候选" initial={{inputId:input.inputId,...(new URL(location.href).searchParams.get('execution')&&!candidate?{requestId:new URL(location.href).searchParams.get('execution')}:{})}} choices={choices} enabled={enabled(pipeline.plan,permissions.write&&!candidate)} onPending={locked=>setLock(pipeline.plan,locked)} onBefore={body=>careLocator({execution:text(body['requestId'])})} onResult={(value,body)=>{const result=record(value);select({candidateId:text(result['candidateId']),digest:text(result['digest']),requestId:text(body['requestId']),recordedAt:text(result['recordedAt']),approvedBy:null,committed:false});void reload().catch(error=>setError(careError(error)));}}/>
 <details open={!!candidate}><summary>服务器候选与原执行请求</summary>{executions.length===0&&<p>尚无已冻结候选。</p>}{executions.map(item=><button key={item.candidateId} disabled={!!pending} onClick={()=>select(item)}>{item.candidateId.slice(-8)} · {item.committed?'已提交':item.approvedBy?'已批准':'待审批'} · 原请求 {item.requestId.slice(-8)}</button>)}{cursor&&<button disabled={!!pending} onClick={()=>void reload(cursor).catch(error=>setError(careError(error)))}>下一页候选</button>}<button disabled={!!pending} onClick={()=>void reload().catch(error=>setError(careError(error)))}>重新读取服务器候选</button></details>
 {candidate&&<div key={candidate.candidateId}><CareOperationPanel actor={actor} operation={pipeline.review} label="审阅冻结候选" initial={{candidateId:candidate.candidateId}} choices={choices} enabled={permissions.review}/><CareOperationPanel actor={actor} operation={pipeline.approve} label="批准准确候选" initial={{candidateId:candidate.candidateId,digest:candidate.digest}} choices={choices} enabled={enabled(pipeline.approve,permissions.review)} onPending={locked=>setLock(pipeline.approve,locked)}/><CareOperationPanel actor={actor} operation={pipeline.apply} label="应用已批准候选" initial={{candidateId:candidate.candidateId,requestId:candidate.requestId}} choices={choices} enabled={enabled(pipeline.apply,permissions.write)} onPending={locked=>setLock(pipeline.apply,locked)} onResult={value=>{setOutcome(value);setMatched(false);}}/><CareOperationPanel actor={actor} operation={pipeline.resume} label="恢复原执行结果" initial={{candidateId:candidate.candidateId,requestId:candidate.requestId}} choices={choices} onResult={value=>{setOutcome(value);if(record(value)['status']==='COMMITTED'){setPending(null);onLock?.(false);}}}/><CareOperationPanel actor={actor} operation={pipeline.reconcile} label="核对已提交事实" initial={{candidateId:candidate.candidateId,requestId:candidate.requestId}} choices={choices} onResult={value=>setMatched(record(value)['status']==='MATCHED')}/>{record(outcome)['status']==='COMMITTED'&&matched&&<p role="status">已完成：服务器提交成功，事实核对一致。</p>}</div>}
 {kind==='WARD_NURSING'&&!scopeReview&&native!==null&&<CareOperationPanel actor={actor} operation="confirmNursingCoverageHandover" label="独立护理交接确认" initial={{inputId:input.inputId,inputDigest:input.digest}} choices={choices} enabled={enabled('confirmNursingCoverageHandover',permissions.verify)} onPending={locked=>setLock('confirmNursingCoverageHandover',locked)}/>}
 {'jobId' in input&&<CareOperationPanel actor={actor} operation="readCareWorkspaceMaterial" label="按当前权限审阅依据材料" initial={{access:'INPUT',kind,inputId:input.inputId}} choices={choices}/>}
 </section>;
}
