import {DepartmentForm,type FormSchema,type ReferenceChoices} from './department-form.js';
import {bindCareReferenceFields,careContextChoices} from './care-reference-fields.js';
export const careFieldLabels:Record<string,string>={
 classificationAccepted:'已独立确认对象分类',scopeAccepted:'已独立核对完整业务范围',ruleConfirmed:'已独立确认规则',confirmed:'已独立确认该依据',receiving:'接诊／接收依据',policyVersion:'核验规则版本',physicalFactsAccepted:'已独立核对物理地点事实',adoptionConfirmed:'已核对准确科目采纳',limitationsConfirmed:'已确认许可限制',sourceReviewed:'已独立审阅来源材料',materialsAccepted:'已核对全部材料',policyApproved:'已核对治理依据',policyAccepted:'已独立确认地点使用规则',scopeDefinition:'护理分区定义依据',completeAndDisjoint:'已确认分区完整且互不重叠',artifactId:'依据材料标识',
 unit_id:'来源业务单元键',unit_code:'业务单元代码',unit_name:'业务单元名称',unit_type:'业务单元类型',org_id:'归属科室',campus_id:'院区',legal_entity_id:'运营主体',public_phone:'公开电话',service_description:'服务说明',receiving_rule_ref:'接诊规则原文',business_owner_id:'业务责任人来源引用',
 ward_id:'病区',ward_code:'病区代码',ward_name:'病区名称',managing_unit_id:'管理业务单元',ward_type:'病区类型原文',admission_rule_ref:'收治规则原文',
 nursing_unit_id:'护理单元',nursing_code:'护理单元代码',nursing_name:'护理单元名称',managing_org_id:'管理科室',care_level:'护理级别原文',office_phone:'办公电话',
 location_id:'地点',location_code:'地点代码',location_name:'地点名称',parent_location_id:'来源父地点键',location_type:'地点类型',floor_label:'楼层标记',room_number:'房间号',address_detail:'地址说明',is_accessible:'无障碍',parent:'物理父节点',clientKey:'来源行键',
 unit_ward_rel_id:'来源科室病区关系键',relation_type:'关系类型原文',is_primary:'主要关系',sharing_rule:'共享规则原文',applicability:'准确业务范围',purpose:'关系用途',
 ward_nursing_rel_id:'来源护理覆盖键',coverage_scope:'覆盖范围原文',coverage:'准确护理覆盖',handover_rule_ref:'交接规则原文',scopeSetId:'护理分区集合',partitionIds:'准确分区',partitions:'完整分区',boundary:'分区边界',mapping:'分区后继映射',toAliases:'后继分区来源键',nursing:'护理单元',ward:'病区',
 object_location_rel_id:'来源地点使用关系键',target_type:'使用对象类型',target_id:'使用对象',usage_type:'用途代码',usageType:'用途字典引用',sharing_description:'共享说明原文',targetType:'对象类型',location:'物理地点',policy:'治理依据',
 capability_id:'来源能力键',capability_type:'业务能力类型',capabilityType:'准确能力类型',care_setting:'服务场景',careSetting:'准确服务场景',enabled:'能力启用',rule_ref:'规则原文',approval_dept:'批准科室原文',rule:'独立规则确认',adoption:'准确采纳依据',valueId:'参数值',parameterId:'参数定义',definitionVersionId:'准确参数定义版本',definitionDigest:'参数定义摘要',valueDigest:'参数值摘要',
 subject_license_id:'来源科目关系键',code_system_id:'科目编码体系来源键',code_system_version:'科目体系来源版本',subject_code:'诊疗科目代码',license_ref:'许可原文',permitted_scope:'许可范围原文',verifier:'来源核验人',semantic:'映射语义',limitations:'许可范围限制',license:'准确许可',subject:'运营主体',department:'科室',unit:'业务单元',relation:'科室院区关系',services:'准确服务集合',
 entries:'维护条目',row:'来源字段',action:'维护动作',binding:'归属关系',timePolicy:'来源时间解释',cutover:'组合生效时间',members:'准确已暂存成员',inputId:'原申请',inputDigest:'原申请摘要',contractVersionId:'准确契约版本',reason:'维护理由',mode:'评价方式',targets:'准确对象引用',field:'问题字段',sourceRow:'原始文件行',worksheet:'原始工作表',material:'依据材料',candidateId:'冻结候选',requestId:'原执行请求',sourceSystemId:'来源系统',sourceRecordedAt:'来源记录时间',approvalReference:'来源批准依据',contentBase64:'导入原文件',transport:'材料来源契约',
};
export function CareForm(props:{schema:FormSchema;value:unknown;onChange:(value:unknown)=>void;choices?:ReferenceChoices;disabled?:boolean;label?:string}){return <div data-care-form><DepartmentForm {...props} bindReferenceSelection={(schema,field,value)=>bindCareReferenceFields(schema,field,value,props.choices??{})} resolveReferenceChoices={(field,root)=>careContextChoices(props.choices??{},field,root)} labels={careFieldLabels} preserveTimePrecision/></div>;}
/** Focus only an already rendered editor control; this never changes a value. */
export function focusCareField(root:HTMLElement,row:number|null,field:string){const rows=[...root.querySelectorAll<HTMLElement>('[data-array-field="entries"][data-row]')],container=rows.find(element=>Number(element.dataset['row'])===row)??root,wrapper=[...container.querySelectorAll<HTMLElement>('[data-field]')].find(element=>element.dataset['field']===field),control=(wrapper??container).querySelector<HTMLElement>('input:not([disabled]),select:not([disabled]),textarea:not([disabled]),button:not([disabled])');(wrapper??container).scrollIntoView({block:'center'});control?.focus();}
