import {WorkspaceMaterial} from './workspace-material.js';
import {useEffect,useRef,useState} from 'react';
import {createVNextCatalogClient,type VNextOperations as Operations} from '@hospital-data-intelligence/generated-api-client';
import {ReviewValues} from './workspace-application.js';
export type WorkspaceBundle=Operations['listWorkspaceOrganizationBundles']['responses'][200]['content']['application/json'][number];
type Legal=Operations['readOrganizationBundleLegalReview']['responses'][200]['content']['application/json'];
type Revision=Operations['readOrganizationBundleRevision']['responses'][200]['content']['application/json'];
type Candidate=Operations['reviewOrganizationBundle']['responses'][200]['content']['application/json'];
const states={STAGED:'待校验与资料核验',VERIFIED:'资料已核验',CANDIDATE:'待整包审批',APPROVED:'整包已批准',COMMITTED:'已原子应用'};
export function WorkspaceBundleApplication({actor,entry,onChanged}:{actor:string;entry:WorkspaceBundle;onChanged:()=>Promise<void>}){
 const [revision,setRevision]=useState<Revision|null>(null),[legal,setLegal]=useState<Legal|null>(null),[candidate,setCandidate]=useState<Candidate|null>(null),[outcome,setOutcome]=useState<unknown>(null),[issues,setIssues]=useState<unknown>(null),[message,setMessage]=useState('整包是唯一应用单元。'),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[seen,setSeen]=useState<string[]>([]);
 const [grantRows,setGrantRows]=useState<number[]>([]),[grantee,setGrantee]=useState('maker'),[permissions,setPermissions]=useState<Array<'READ'|'CREATE'|'REVISE'|'REVIEW'>>([]),[grantAllowed,setGrantAllowed]=useState(true);
 const pendingGrant=useRef<{payload:string;requestId:string}|null>(null);
 const epoch=useRef(0),requests=useRef(new Map<string,string>());const api=()=>createVNextCatalogClient(location.origin,actor),reference={jobId:entry.jobId,revisionId:entry.revisionId};
 const request=(key:string)=>{let id=requests.current.get(key);if(!id){id=crypto.randomUUID();requests.current.set(key,id);}return id;};
 useEffect(()=>{const e=epoch.current;void api().POST('/api/vnext/import/organization-bundles/revision',{body:reference}).then(r=>{if(e!==epoch.current)return;if(r.data)setRevision(r.data);else setMessage(r.error?.message??'读取失败');}).catch(()=>{if(e===epoch.current)setMessage('服务不可用。');});return()=>{epoch.current++;};},[]);
 async function run(action:'validate'|'grant'|'legal'|'verify'|'plan'|'review'|'approve'|'apply'|'resume'){
  const e=epoch.current;setBusy(true);try{
   if(action==='validate'){const r=await api().POST('/api/vnext/import/organization-bundles/validate/bundle',{body:{...reference,requestId:request('validate')}});if(e!==epoch.current)return;if(r.error)throw new Error(r.error.message+' ['+r.error.code+']');setIssues(r.data);setMessage('逐表问题保留物理行定位；校验成功仍不代表批准。');}
   else if(action==='grant'){const grants=grantRows.map(row=>({row,actor:grantee,permissions,allowed:grantAllowed}));const payload=JSON.stringify(grants);if(pendingGrant.current?.payload!==payload)pendingGrant.current={payload,requestId:crypto.randomUUID()};const r=await api().POST('/api/vnext/import/organization-bundles/preauthorize',{body:{...reference,requestId:pendingGrant.current.requestId,grants}});if(e!==epoch.current)return;if(r.error)throw new Error(r.error.message+' ['+r.error.code+']');pendingGrant.current=null;setMessage(grantAllowed?'所列准确行配对已预授权；没有授予业务审批身份。':'已撤销所列准确行、身份和动作的预授权。');}
   else if(action==='legal'||action==='review'){
    setLegal(null);setCandidate(null);setConfirmed(false);setSeen([]);const r=await api().POST('/api/vnext/import/organization-bundles/legal-review',{body:reference});if(e!==epoch.current)return;if(r.error)throw new Error(r.error.message+' ['+r.error.code+']');setLegal(r.data);
    if(action==='review'&&entry.candidateId){const c=await api().POST('/api/vnext/import/organization-bundles/review',{body:{candidateId:entry.candidateId}});if(e!==epoch.current)return;if(c.error)throw new Error(c.error.message+' ['+c.error.code+']');setCandidate(c.data);}setMessage('请展开逐行解释及材料，核对后显式确认。');
   }else if(action==='verify'&&legal){const r=await api().POST('/api/vnext/import/organization-bundles/verify',{body:{...reference,digest:legal.digest,requestId:request('verify/'+legal.digest)}});if(e!==epoch.current)return;if(r.error)throw new Error(r.error.message+' ['+r.error.code+']');setMessage('独立资料核验已记录；尚未整包批准。');}
   else if(action==='plan'){const r=await api().POST('/api/vnext/import/organization-bundles/plan',{body:{...reference,requestId:entry.requestId??request('plan')}});if(e!==epoch.current)return;if(r.error)throw new Error(r.error.message+' ['+r.error.code+']');setMessage('整包候选已冻结。');}
   else if(action==='approve'&&candidate){const r=await api().POST('/api/vnext/import/organization-bundles/approve',{body:{candidateId:candidate.candidateId,digest:candidate.digest}});if(e!==epoch.current)return;if(r.error)throw new Error(r.error.message+' ['+r.error.code+']');setMessage('整包审批已记录，应用前仍重检。');}
   else if((action==='apply'||action==='resume')&&entry.candidateId&&entry.requestId){const r=await api().POST(action==='apply'?'/api/vnext/import/organization-bundles/apply':'/api/vnext/import/organization-bundles/resume',{body:{candidateId:entry.candidateId,requestId:entry.requestId}});if(e!==epoch.current)return;if(r.error)throw new Error(r.error.message+' ['+r.error.code+']');setOutcome(r.data);setMessage(r.data?'已返回原整包结果与正式身份映射。':'尚无已提交结果。');}
   if(e===epoch.current)await onChanged();
  }catch(error){if(e===epoch.current){setConfirmed(false);setMessage(error instanceof Error?error.message:'连接失败；结果未知，请恢复原请求。');}}finally{if(e===epoch.current)setBusy(false);}
 }
 const complete=!!legal&&legal.materials.every(m=>seen.includes(m.id))&&confirmed;
 return <section className="editor-card"><h3>组织工作簿 · {states[entry.state]}</h3>{!entry.currentRevision&&<p>历史输入修订：仅可读取与恢复原结果，不能继续预授权、审批或应用。</p>}<p>原提交人：{entry.maker}；整包应用不会启用院区。</p><p role="status">{message}</p><div className="action-bar"><button disabled={busy||!entry.access.canWrite||entry.state==='COMMITTED'} onClick={()=>void run('validate')}>整包校验并定位问题</button><button disabled={busy||!entry.access.canReview||entry.state==='COMMITTED'} onClick={()=>void run('legal')}>读取独立核验材料</button><button disabled={busy||!entry.access.canReview||!complete||entry.state==='COMMITTED'} onClick={()=>void run('verify')}>确认资料核验</button><button disabled={busy||!entry.access.canPlan||entry.state!=='VERIFIED'} onClick={()=>void run('plan')}>冻结整包候选</button><button disabled={busy||!entry.access.canReview||!entry.candidateId||entry.state==='COMMITTED'} onClick={()=>void run('review')}>读取最终准确候选</button><button disabled={busy||!entry.access.canReview||!candidate||!complete||entry.state==='COMMITTED'} onClick={()=>void run('approve')}>批准整包</button><button disabled={busy||!entry.access.canWrite||entry.state!=='APPROVED'} onClick={()=>void run('apply')}>应用完整工作簿</button><button disabled={busy||!entry.candidateId} onClick={()=>void run('resume')}>恢复原结果</button></div>
 {entry.access.canPreauthorize&&revision&&entry.state!=='COMMITTED'&&<fieldset><legend>准确行配对预授权</legend>{revision.manifest.rows.filter(r=>r.dataset==='ORG03').map(row=><label key={row.row}><input type="checkbox" disabled={busy} checked={grantRows.includes(row.row)} onChange={e=>setGrantRows(e.target.checked?[...grantRows,row.row]:grantRows.filter(r=>r!==row.row))}/>ORG03 物理行 {row.row}<ReviewValues value={{subject:row.subject,campus:row.campus,scope:row.governanceScope}}/></label>)}<label>被授权合成身份<select value={grantee} disabled={busy} onChange={e=>setGrantee(e.target.value)}><option value="maker">院办</option><option value="workspace-reviewer">核验 / 审批人</option></select></label>{(['READ','CREATE','REVISE','REVIEW'] as const).map(permission=><label key={permission}><input type="checkbox" disabled={busy} checked={permissions.includes(permission)} onChange={e=>setPermissions(e.target.checked?[...permissions,permission]:permissions.filter(p=>p!==permission))}/>{permission}</label>)}<label>授权操作<select value={grantAllowed?'ALLOW':'REVOKE'} disabled={busy} onChange={e=>setGrantAllowed(e.target.value==='ALLOW')}><option value="ALLOW">授予所选权限</option><option value="REVOKE">撤销所选权限</option></select></label><button disabled={busy||!grantRows.length||!permissions.length} onClick={()=>void run('grant')}>{grantAllowed?'预授权所选行、身份与动作':'撤销所选行、身份与动作的预授权'}</button></fieldset>}
 {issues!==null&&<ReviewValues value={issues}/>} {legal&&<><details><summary>原始工作表与采纳清单</summary><ReviewValues value={{cells:legal.cells,manifest:legal.manifest}}/></details>{legal.materials.map(material=><WorkspaceMaterial key={material.id} id={material.id} bytesBase64={material.contentBase64} onRead={()=>setSeen(rows=>[...new Set([...rows,material.id])])}/>)}<label className="confirmation"><input type="checkbox" disabled={busy||!legal.materials.every(m=>seen.includes(m.id))} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>已核对原材料、准确版本、服务及完整期间</label></>}{candidate&&<ReviewValues value={candidate.commands.map(c=>({sequence:c.sequence,command:JSON.parse(c.interpretation)}))}/>} {outcome!==null&&<ReviewValues value={outcome}/>}</section>;
}
