import {Field,Group,textField,objectField} from './workspace-fields.js';
import type {VNextOperations as Operations} from '@hospital-data-intelligence/generated-api-client';
type Contract=Operations['listImportContracts']['responses'][200]['content']['application/json']['items'][number];
const options={PLANNING:'筹建',TRIAL_RUNNING:'试运行',RUNNING:'运行',SUSPENDED:'停用'};
export function WorkspaceCommandFields({domain,command,disabled,contracts,onChange}:{domain:'ORG01'|'ORG02'|'ORG03';command:unknown;disabled:boolean;contracts:Contract[];onChange:(patch:Record<string,unknown>)=>void}){
 const action=textField(command,'action'),facts=objectField(command,'facts'),license=objectField(command,'license');
 const patchFacts=(key:string,value:unknown)=>onChange({facts:{...facts,[key]:value}});
 const patchLicense=(key:string,value:unknown)=>onChange({license:{...license,[key]:value}});
 if(domain==='ORG01')return <>
  {['CREATE','REVISE'].includes(action)&&<><Group title="机构基本资料">{[['legalName','机构名称'],['entityNature','机构性质'],['authority','登记主管机关'],['legalAddress','登记地址']].map(([key,label])=><Field key={key} label={label!} value={textField(facts,key!)} disabled={disabled} onChange={value=>patchFacts(key!,value||(['authority','legalAddress'].includes(key!)?null:undefined))}/>)}</Group><IdentifierFields command={command} disabled={disabled} onChange={onChange}/></>}
  {['ADD_LICENSE','REVISE_LICENSE'].includes(action)&&<Group title="证照准确资料">{[['namespace','号码命名空间'],['number','证照号码（受限）'],['authority','发证机关'],['validFrom','证照生效值']].map(([key,label])=><Field key={key} label={label!} time={key==='validFrom'} value={textField(license,key!)} disabled={disabled} onChange={value=>patchLicense(key!,value||undefined)}/>)}<label>证照结束语义<select disabled={disabled} value={textField(license,'endKind')} onChange={e=>onChange({license:{...license,endKind:e.target.value,validTo:null}})}><option value="">请选择</option><option value="FINITE">有明确结束值</option><option value="VERIFIED_UNBOUNDED">已核验无固定期限</option><option value="UNKNOWN">结束值未知（阻断持证发布）</option></select></label>{textField(license,'endKind')==='FINITE'&&<Field time label="证照结束值" value={textField(license,'validTo')} disabled={disabled} onChange={value=>patchLicense('validTo',value||null)} hint="日期结束值在当日零点失效；填写具体时刻时该时刻起失效。"/>}</Group>}
  {action==='VERIFY_REGISTRATION'&&<Group title="登记核验声明"><label>统一社会信用代码<select disabled={disabled} value={textField(command,'creditCodeStatus')} onChange={e=>onChange({creditCodeStatus:e.target.value||undefined})}><option value="">请选择</option><option value="HELD">已持有</option><option value="NOT_APPLICABLE">不适用（须独立材料确认）</option></select></label><p>核验依据必须绑定所选准确证照版本，提交人不能独立完成批准。</p></Group>}
  {action==='REVOKE_LICENSE'&&<Field label="撤销原因代码" value={textField(command,'reason')} disabled={disabled} onChange={value=>onChange({reason:value||undefined})} hint="使用明确大写原因代码，例如 WRONG_ASSERTION。"/>}
 </>;
 if(domain==='ORG02')return <>
  {['CREATE','REVISE'].includes(action)&&<Group title="物理院区资料">{[['campusCode','院区业务代码'],['campusName','院区名称'],['campusAddress','院区地址'],['publicPhone','公众联系电话'],['openingDate','实际启用日期']].map(([key,label])=><Field key={key} label={label!} value={textField(facts,key!)} disabled={disabled} onChange={value=>patchFacts(key!,value||(['campusAddress','publicPhone','openingDate'].includes(key!)?null:undefined))} {...(key==='openingDate'?{hint:'有证据的实际日期，不能把计划日期填为实际启用日期。'}:{})}/>)}<label>节点角色<select disabled={disabled} value={textField(facts,'nodeRole')} onChange={e=>patchFacts('nodeRole',e.target.value||undefined)}><option value="">请选择</option><option value="HEADQUARTERS">本部</option><option value="HIGH_TECH">高新</option><option value="CITY_CENTER">中心</option></select></label><label>已采纳行政区划<select disabled={disabled} value={textField(objectField(facts,'adminDivision'),'contractVersionId')+'/'+textField(objectField(facts,'adminDivision'),'code')} onChange={e=>{const [version,code]=e.target.value.split('/'),c=contracts.find(c=>c.versionId===version),set=c?.definition.codeSets.find(s=>s.field==='admin_division_code'&&s.codes.includes(code!));patchFacts('adminDivision',c&&set?{contractId:c.id,contractVersionId:c.versionId,codeSystem:set.codeSystem,version:set.version,code,sourceVersionId:set.sourceVersionId}:null);}}><option value="/">未填写（不是地区通配）</option>{contracts.flatMap(c=>c.definition.codeSets.filter(s=>s.field==='admin_division_code'&&s.status==='SYNTHETIC_ADOPTED').flatMap(s=>s.codes.map(code=><option key={c.versionId+'/'+code} value={c.versionId+'/'+code}>{code} · {s.codeSystem} · {s.version}</option>)))}</select></label></Group>}
  <Group title="院区状态声明"><label>来源声明的运营状态<select disabled={disabled} value={textField(command,'sourceOperationStatus')} onChange={e=>onChange({sourceOperationStatus:e.target.value||undefined})}><option value="">请选择准确来源声明</option>{Object.entries(options).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><p className="muted">资料修订不会改变运营状态；来源声明仍由 Owner 核对。</p>{action==='SCHEDULE_OPENING'&&<Field time label="计划开业时间" value={textField(command,'plannedOpeningAt')} disabled={disabled} onChange={value=>onChange({plannedOpeningAt:value||undefined})}/>} {action==='ACTIVATE'&&<label>申请启用状态<select disabled={disabled} value={textField(command,'state')} onChange={e=>onChange({state:e.target.value||undefined})}><option value="">请选择</option><option value="TRIAL_RUNNING">试运行</option><option value="RUNNING">运行</option></select></label>}{['CANCEL_OPENING','SUSPEND'].includes(action)&&<Field label="操作原因" value={textField(command,'reason')} disabled={disabled} onChange={value=>onChange({reason:value||undefined})}/>}</Group>
 </>;
 return <Group title="关系与许可范围">{['CLOSE','REVOKE_SCOPE'].includes(action)?<Field label="操作原因" value={textField(command,'reason')} disabled={disabled} onChange={value=>onChange({reason:value||undefined})}/>:<><Field label="许可范围原文" value={textField(facts,'licenseScopeText')} disabled={disabled} onChange={value=>patchFacts('licenseScopeText',value||null)}/>{!['VERIFY_SCOPE','REVISE_SCOPE'].includes(action)&&<><label>关系角色<select disabled={disabled} value={textField(facts,'role')} onChange={e=>patchFacts('role',e.target.value||undefined)}><option value="">请选择</option>{['OPERATOR','REGISTRANT','MANAGER','BILLING','OTHER'].map(v=><option key={v}>{v}</option>)}</select></label><Field label="来源关系类型原文" value={textField(facts,'relationTypeText')} disabled={disabled} onChange={value=>patchFacts('relationTypeText',value||undefined)}/><label>主运营声明<select disabled={disabled} value={textField(facts,'primary')} onChange={e=>patchFacts('primary',e.target.value||undefined)}><option value="">请选择</option><option value="Y">是（Y）</option><option value="N">否（N）</option></select></label></>}</>}</Group>;
}
function IdentifierFields({command,disabled,onChange}:{command:unknown;disabled:boolean;onChange:(patch:Record<string,unknown>)=>void}){
 const raw=command&&typeof command==='object'?Reflect.get(command,'identifiers'):null,rows:unknown[]=Array.isArray(raw)?raw:[];
 const edit=(index:number,key:string,value:string)=>onChange({identifiers:rows.map((row,i)=>i===index?{...(row&&typeof row==='object'?row:{}),[key]:value||undefined}:row)});
 return <Group title="机构标识（受限）">{rows.map((row,index)=><div key={index}><label>标识类型<select disabled={disabled} value={textField(row,'kind')} onChange={e=>edit(index,'kind',e.target.value)}><option value="">请选择</option><option value="UNIFIED_CREDIT_CODE">统一社会信用代码</option><option value="INSTITUTION_CODE">医疗机构登记代码</option></select></label><Field label="标识命名空间" value={textField(row,'namespace')} disabled={disabled} onChange={value=>edit(index,'namespace',value)}/><Field label="标识原值" value={textField(row,'value')} disabled={disabled} onChange={value=>edit(index,'value',value)}/><button className="secondary" disabled={disabled} onClick={()=>onChange({identifiers:rows.filter((_,i)=>i!==index)})}>移除此项标识声明</button></div>)}<button className="secondary" disabled={disabled||rows.length>=2} onClick={()=>onChange({identifiers:[...rows,{}]})}>添加标识声明</button><p className="muted">修订底稿保留原标识；移除与新增都在准确候选中交由独立审批。</p></Group>;
}
