import {useEffect,useRef,useState} from 'react';
import {createVNextCatalogClient} from '@hospital-data-intelligence/generated-api-client';
import {Field,Group} from './workspace-fields.js';
import {ReviewValues} from './workspace-application.js';
export function WorkspaceOperatingWindow({actor,subjectId,campusId,asOf,codes}:{actor:string;subjectId:string;campusId:string;asOf:string;codes:string[]}){
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[services,setServices]=useState<string[]>([]),[result,setResult]=useState<unknown>(null),[message,setMessage]=useState('填写完整业务期间后评估。'),[busy,setBusy]=useState(false);const generation=useRef(0);
 useEffect(()=>{generation.current++;setResult(null);return()=>{generation.current++;};},[actor,subjectId,campusId,asOf]);
 async function evaluate(){const e=generation.current;setBusy(true);setResult(null);try{const r=await createVNextCatalogClient(location.origin,actor).POST('/api/vnext/operating-relations/evaluate',{body:{subject:{owner:'organization-master',id:subjectId},campus:{owner:'organization-master/campus',id:campusId},services,validFrom:from,validTo:to||null,asOf}});if(e!==generation.current)return;if(r.error)setMessage(r.error.message+' ['+r.error.code+']');else{setResult(r.data);setMessage('评估按每项服务返回分段、缺口与待复核原因。');}}catch{if(e===generation.current)setMessage('评估不可用，不能推断允许运营。');}finally{if(e===generation.current)setBusy(false);}}
 return <section className="editor-card"><h3>完整运营窗口评估</h3><p>普通院区状态不代表运营获准；这里同时核对主体、院区、服务及完整期间。</p><Group title="评估期间与服务"><Field time label="评估开始时间" value={from} onChange={value=>{setResult(null);setFrom(value);}} disabled={busy}/><Field time label="评估结束时间" value={to} onChange={value=>{setResult(null);setTo(value);}} disabled={busy} hint="半开期间；留空请求持续无界覆盖。"/>{codes.map(code=><label key={code}><input type="checkbox" disabled={busy} checked={services.includes(code)} onChange={e=>{setResult(null);setServices(e.target.checked?[...services,code]:services.filter(c=>c!==code));}}/>{code}</label>)}</Group><button disabled={busy||!subjectId||!campusId||!from||!services.length||!asOf} onClick={()=>void evaluate()}>评估完整期间</button><p role="status">{message}</p>{result!==null&&<ReviewValues value={result}/>}</section>;
}
