import {displayTime} from './workspace-fields.js';
import {useEffect,useRef,useState,useId} from 'react';
import {createVNextCatalogClient,type VNextOperations as Operations} from '@hospital-data-intelligence/generated-api-client';
import {Field,Group,textField,objectField} from './workspace-fields.js';
import {readAllWorkspacePages} from './workspace-pagination.js';
import {WorkspaceLicenseDependencyOptions} from './workspace-license-dependencies.js';
export function WorkspaceEndpointFields({actor,subjectId,campusId,disabled=false,onChange}:{actor:string;subjectId:string;campusId:string;disabled?:boolean;onChange:(subjectId:string,campusId:string)=>void}){
 const [subjects,setSubjects]=useState<Array<{id:string;legalName:string}>>([]),[campuses,setCampuses]=useState<Array<{id:string;name:string}>>([]),[error,setError]=useState('');
 useEffect(()=>{let live=true;setSubjects([]);setCampuses([]);setError('');const api=createVNextCatalogClient(location.origin,actor);
  void Promise.all([readAllWorkspacePages(after=>api.POST('/api/vnext/organizations/query',{body:{mode:'LIST',limit:100,...(after?{after}: {})}})),readAllWorkspacePages(after=>api.POST('/api/vnext/campuses/list',{body:{limit:100,...(after?{after}: {})}}))]).then(([org,node])=>{if(!live)return;if(org.error||node.error||!org.data||!node.data){setError('对象选择读取失败；未使用旧身份缓存。');return;}setSubjects(org.data);setCampuses(node.data.map(c=>({id:c.id,name:c.facts?.campusName??'资料空档院区'})));}).catch(()=>{if(live)setError('服务不可用，不能推断对象引用。');});return()=>{live=false;};},[actor]);
 return <><label>机构主体<select disabled={disabled} value={subjectId} onChange={e=>onChange(e.target.value,campusId)}><option value="">选择当前可读主体</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.legalName} · {s.id.slice(-8)}</option>)}</select></label><label>物理院区<select disabled={disabled} value={campusId} onChange={e=>onChange(subjectId,e.target.value)}><option value="">选择当前可读院区</option>{campuses.map(c=><option key={c.id} value={c.id}>{c.name} · {c.id.slice(-8)}</option>)}</select></label>{error&&<p role="alert">{error}</p>}<p className="muted">两端可读不等于配对获授权；选择后仍须核验准确组合权限。</p></>;
}
type License=Operations['readOrganizationLicenses']['responses'][200]['content']['application/json'][number];
type Scope=Operations['readLicenseScope']['responses'][200]['content']['application/json'][number];
export function WorkspaceScopeReferencePicker({actor,subjectId,campusId,initialBusinessAt,disabled,onSelect}:{actor:string;subjectId:string;campusId:string;initialBusinessAt:string;disabled:boolean;onSelect:(reference:{owner:'organization-master/license-scope';id:string;version:string;versionId:string})=>void}){
 const [businessAt,setBusinessAt]=useState(initialBusinessAt),[objects,setObjects]=useState<Scope[]>([]),[versions,setVersions]=useState<Scope[]>([]),[selected,setSelected]=useState(''),[message,setMessage]=useState('按明确两端与业务时点读取范围依据。'),[busy,setBusy]=useState(false);const generation=useRef(0);
 useEffect(()=>{generation.current++;setBusy(false);setObjects([]);setVersions([]);setSelected('');return()=>{generation.current++;};},[actor,subjectId,campusId]);
 async function read(id?:string){const e=++generation.current;setBusy(true);setVersions([]);try{const r=await createVNextCatalogClient(location.origin,actor).POST('/api/vnext/license-scope-evidence/query',{body:id?{kind:'SCOPE',mode:'HISTORY',id}:{kind:'SCOPE',mode:'LIST',subjectId,campusId,businessAt}});if(e!==generation.current)return;if(r.error){setMessage(r.error.message);return;}if(id)setVersions(r.data);else{setObjects(r.data);setSelected('');}setMessage('请选择确实属于该配对的准确范围版本。');}catch{if(e===generation.current)setMessage('范围依据读取失败。');}finally{if(e===generation.current)setBusy(false);}}
 return <Group title="选择既有范围依据"><Field time label="范围查询业务时点" value={businessAt} disabled={disabled||busy} onChange={value=>{generation.current++;setBusinessAt(value);setObjects([]);setVersions([]);setSelected('');}}/><button disabled={disabled||busy||!subjectId||!campusId||!businessAt} onClick={()=>void read()}>读取该配对范围</button><label>范围对象<select value={selected} disabled={disabled||busy} onChange={e=>{setSelected(e.target.value);if(e.target.value)void read(e.target.value);else setVersions([]);}}><option value="">请选择可读范围</option>{objects.map(r=><option key={r.id} value={r.id}>{r.id.slice(-8)} · {displayTime(r.validFrom)} 至 {r.validTo?displayTime(r.validTo):'无界'}</option>)}</select></label><label>准确范围版本<select value="" disabled={disabled||busy} onChange={e=>{const r=versions.find(r=>r.versionId===e.target.value);if(r)onSelect({owner:'organization-master/license-scope',id:r.id,version:r.version,versionId:r.versionId});}}><option value="">选择后追加此版本依据</option>{versions.filter(r=>r.action!=='REVOKE_SCOPE').map(r=><option key={r.versionId} value={r.versionId}>v{r.version} · {displayTime(r.validFrom)} 至 {r.validTo?displayTime(r.validTo):'无界'}</option>)}</select></label><p role="status">{message}</p></Group>;
}
type Contract=Operations['listImportContracts']['responses'][200]['content']['application/json']['items'][number];
export function WorkspaceTargetPicker({actor,kind,id,disabled,subjectId,campusId,onSelect}:{actor:string;kind:'ORGANIZATION'|'CAMPUS'|'RELATION';id:string;disabled:boolean;subjectId?:string;campusId?:string;onSelect:(value:{owner:'organization-master'|'organization-master/campus'|'organization-master/operating-relation';id:string;expectedVersion:string}|undefined)=>void}){
 const generation=useRef(0),latestSelect=useRef(onSelect);latestSelect.current=onSelect;
 const [rows,setRows]=useState<Array<{id:string;name:string}>>([]),[error,setError]=useState('');
 useEffect(()=>{let live=true;setRows([]);setError('');const api=createVNextCatalogClient(location.origin,actor);void(async()=>{
  if(kind==='ORGANIZATION'){const r=await readAllWorkspacePages(after=>api.POST('/api/vnext/organizations/query',{body:{mode:'LIST',limit:100,...(after?{after}: {})}}));if(!live)return;if(r.error||!r.data)setError('机构主体引用读取失败；未截断为前 100 项。');else setRows(r.data.map(v=>({id:v.id,name:v.legalName})));}
  else if(kind==='CAMPUS'){const r=await readAllWorkspacePages(after=>api.POST('/api/vnext/campuses/list',{body:{limit:100,...(after?{after}: {})}}));if(!live)return;if(r.error||!r.data)setError('院区引用读取失败；未截断为前 100 项。');else setRows(r.data.map(v=>({id:v.id,name:v.facts?.campusName??'资料空档院区'})));}
  else if(subjectId&&campusId){const r=await api.POST('/api/vnext/operating-relations/query',{body:{kind:'RELATION',mode:'LIST',subjectId,campusId}});if(!live)return;if(r.error)setError(r.error.message);else setRows(r.data.map(v=>({id:v.id,name:textField(v.facts,'role')+' · v'+v.version})));}
 })().catch(()=>{if(live)setError('引用读取失败');});return()=>{live=false;generation.current++;};},[actor,kind,subjectId,campusId]);
 async function choose(id:string){const e=++generation.current;if(!id){latestSelect.current(undefined);return;}const r=await createVNextCatalogClient(location.origin,actor).POST('/api/vnext/organization-workspace/references/context',{body:{kind,id}});if(e!==generation.current)return;if(r.error){setError(r.error.message);return;}latestSelect.current({owner:kind==='ORGANIZATION'?'organization-master':kind==='CAMPUS'?'organization-master/campus':'organization-master/operating-relation',id:r.data.id,expectedVersion:r.data.head});}
 return <label>准确既有对象<select value={id} disabled={disabled} onChange={e=>void choose(e.target.value)}><option value="">选择对象并固定当前并发版本</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name} · {r.id.slice(-8)}</option>)}</select>{error&&<span role="alert">{error}</span>}</label>;
}
export function WorkspaceLicenseSelection({actor,subjectId,selected,multiple,disabled,onChange,purpose='DEPENDENCY'}:{actor:string;subjectId:string;selected:Array<{id:string;version:string}>;multiple:boolean;disabled:boolean;purpose?:'DEPENDENCY'|'CURRENT_REVISION';onChange:(refs:Array<{owner:'organization-master/license';id:string;version:string;versionId:string}>)=>void}){
 const [rows,setRows]=useState<License[]>([]),[error,setError]=useState(''),groupName=useId();
 useEffect(()=>{let live=true;setRows([]);setError('');if(subjectId)void createVNextCatalogClient(location.origin,actor).POST('/api/vnext/organizations/licenses/query',{body:{id:subjectId,mode:'HISTORY'}}).then(r=>{if(!live)return;if(r.error)setError(r.error.message);else setRows(r.data);}).catch(()=>{if(live)setError('证照版本读取失败');});return()=>{live=false;};},[actor,subjectId]);
 return <Group title="准确证照版本">{error?<p role="alert">{error}</p>:<WorkspaceLicenseDependencyOptions rows={rows} selected={selected} multiple={multiple} disabled={disabled} purpose={purpose} groupName={groupName} onChange={onChange} label={row=><>{row.id.slice(-8)} · v{row.version} · {displayTime(row.validFrom)} 至 {(row.validTo?displayTime(row.validTo):null)??(row.endKind==='VERIFIED_UNBOUNDED'?'已核验无界':'结束时间未知')}</>}/>}</Group>;
}
export function WorkspaceServiceSelection({actor,command,contracts,disabled,onChange}:{actor:string;command:unknown;contracts:Contract[];disabled:boolean;onChange:(patch:Record<string,unknown>)=>void}){
 const facts=objectField(command,'facts'),subjectId=textField(objectField(command,'subject'),'id'),campusId=textField(objectField(command,'campus'),'id'),action=textField(command,'action');
 const [scopes,setScopes]=useState<Scope[]>([]),[error,setError]=useState('');
 const scopeAction=action==='VERIFY_SCOPE'||action==='REVISE_SCOPE';
 useEffect(()=>{let live=true;setScopes([]);setError('');if(!scopeAction&&subjectId&&campusId)void createVNextCatalogClient(location.origin,actor).POST('/api/vnext/license-scope-evidence/query',{body:{kind:'SCOPE',mode:'LIST',subjectId,campusId}}).then(r=>{if(!live)return;if(r.error)setError(r.error.message);else setScopes(r.data);}).catch(()=>{if(live)setError('准确配对的范围依据读取失败');});return()=>{live=false;};},[actor,subjectId,campusId,scopeAction]);
 const patch=(values:Record<string,unknown>)=>onChange({facts:{...facts,...values}}),catalog=objectField(facts,'catalog'),versionId=textField(catalog,'contractVersionId'),selected=contracts.find(c=>c.versionId===versionId),codeSet=selected?.definition.codeSets.find(c=>c.field==='license_scope');
 const services=Array.isArray(facts['services'])?facts['services']:[],targets=Array.isArray(facts['scopeTargets'])?facts['scopeTargets']:[],license=objectField(facts,'license');
 return <><Group title="已采纳服务范围"><label>服务码表准确版本<select value={versionId} disabled={disabled} onChange={e=>{const c=contracts.find(c=>c.versionId===e.target.value),set=c?.definition.codeSets.find(s=>s.field==='license_scope');patch({catalog:c&&set?{contractId:c.id,contractVersionId:c.versionId,codeSystem:set.codeSystem,version:set.version,sourceVersionId:set.sourceVersionId}:undefined,services:[]});}}><option value="">请选择服务码表</option>{contracts.filter(c=>c.definition.codeSets.some(s=>s.field==='license_scope'&&s.status==='SYNTHETIC_ADOPTED')).map(c=><option key={c.versionId} value={c.versionId}>{c.definition.templateVersion} · v{c.version}</option>)}</select></label>{codeSet?.codes.map(code=><label key={code}><input type="checkbox" checked={services.includes(code)} disabled={disabled} onChange={e=>patch({services:e.target.checked?[...services,code]:services.filter(s=>s!==code)})}/>{code}</label>)}<p className="muted">合成采纳服务，不代表真实医疗许可标准；每项服务仍需完整期间依据。</p></Group>{scopeAction?<WorkspaceLicenseSelection actor={actor} subjectId={subjectId} disabled={disabled} multiple={false} selected={textField(license,'id')?[{id:textField(license,'id'),version:textField(license,'version')}]:[]} onChange={refs=>patch({license:refs[0]})}/>:<Group title="准确许可范围依据">{targets.map((target,index)=><div key={textField(target,'versionId')||index}><span>已选依据 {textField(target,'id').slice(-8)} · v{textField(target,'version')}</span><button className="secondary" disabled={disabled} onClick={()=>patch({scopeTargets:targets.filter((_,i)=>i!==index)})}>移除此项范围依据</button></div>)}<WorkspaceScopeReferencePicker actor={actor} subjectId={subjectId} campusId={campusId} initialBusinessAt={textField(command,'validFrom')} disabled={disabled} onSelect={reference=>{if(!targets.some(t=>textField(t,'versionId')===reference.versionId))patch({scopeTargets:[...targets,reference]});}}/>{error&&<p role="alert">{error}</p>}{scopes.map(scope=><label key={scope.versionId}><input type="checkbox" disabled={disabled} checked={targets.some(t=>textField(t,'versionId')===scope.versionId)} onChange={e=>patch({scopeTargets:e.target.checked?[...targets,{owner:'organization-master/license-scope',id:scope.id,version:scope.version,versionId:scope.versionId}]:targets.filter(t=>textField(t,'versionId')!==scope.versionId)})}/>{scope.id.slice(-8)} · v{scope.version} · {displayTime(scope.validFrom)} 至 {scope.validTo?displayTime(scope.validTo):'无界'}</label>)}</Group>}</>;
}
